- CHANGELOG.md
- modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpChannel.java
- modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpChannelTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/11751 to `2.x`
> [Backport] [2.x] Add the means to extract the contextual underlying channel from HttpChannel without excessive typecasting (#11751)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
- server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
- server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
We have a bug where a flat object field with inner fields that contain dots will "push" the dotted name onto the dot-path from the root, but then would just "pop" off the last part of the dotted name.
This change adds more robust support for flat object keys and subkeys that contain dots (i.e. it pops off the entirety of the latest key, regardless of how many dots it contains).
Resolves https://github.com/opensearch-project/OpenSearch/issues/11402 …
> Fix parsing of flat object fields with dots in keys

- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/11_match_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/20_ngram_search_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/30_ngram_highligthing_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/40_query_string_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/41_query_string_with_default_analyzer_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/50_queries_with_synonyms_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/60_synonym_graph_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/70_intervals_field_match_only_text.yml
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.suggest/20_phrase_field_match_only_text.yml
- modules/mapper-extras/src/yamlRestTest/resources/rest-api-spec/test/search-as-you-type/20_highlighting_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/indices.validate_query/20_query_string_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/30_sig_terms_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/90_sig_text_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.inner_hits/20_highlighting_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search/160_exists_query_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search/200_phrase_search_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search/310_match_bool_prefix_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search/320_disallow_queries_field_match_only_text.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/10_basic_field_match_only_field.yml
Update the skip version for match_only_text field integ tests to `2.11.99` after the backport to 2.x - 
More details - https://github.com/opensearch-project/OpenSearch/pull/11039#issuecomment-1823522002
> Update the skip version for match_only_text field Integ tests to 2.11.99

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
In RemoteStoreStatsIT, for tests (1) testDownloadStatsCorrectnessSinglePrimarySingleReplica and (2) testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards, we see an assertion failure in a similar spot. 
The failing assertions check that a successful upload AND no failures took place for an index with remote store enabled. This is before any docs are indexed and after ensureGreen. 
Even after days of running this test, we weren't able to reproduce it. Judging by the point of assertion failure, the hypothesis is that we see this failure when the upload didn't take place in time after running refresh. To test this, we are adding in a lightweight log statement before these assertions so we can confirm this is the cause if it fails again. 
Previous build failures:
5 …
> Add logging for tests in RemoteStoreStatsIT to catch assertion failure cause

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
- test/framework/src/main/java/org/opensearch/test/engine/MockEngineFactory.java
This PR Conditionally(When segment replication is enabled and shard is replica) returns NRTReplicationEngine() from [MockEngineFactory](https://github.com/opensearch-project/OpenSearch/blob/7b1c2c78c16d566da93001d0f6a8224b2de9e8d0/test/framework/src/main/java/org/opensearch/test/engine/MockEngineFactory.java#L48)
Resolves #11715 
> [Segment Replication] [Remote Store] Replace overriding mockInternalEngine() in test classes with NRTReplicationEngine.

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
- server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
- server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
Backport PR for https://github.com/opensearch-project/OpenSearch/pull/11678
- [] ~New functionality has been documented.~
> [Backport 2.x] Add deleted doc count in _cat/shards

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
This PR introduces new `WRITEABLE_REMOTE_INDEX` feature flag to gate the writeable remote index functionality.
Resolves #11705 
> Introduce a new feature flag "WRITEABLE_REMOTE_INDEX" to gate the writeable remote index functionality

- rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
Since we merged #11209 we would need to fix the skip version to match the BWC tests
> Update skip version to match branches

- server/src/internalClusterTest/java/org/opensearch/cluster/allocation/AwarenessAllocationIT.java
This change mutes the flaky test - testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness. 
The test fails frequently because OpenSearch in a way follows greedy approach while allocating shards and doesn't compute the optimal allocation for all the shards that needs to be allocated. This approach based on certain filters and rules tries to control nodes where shards are assigned.
The unassigned shards causing test failure is due to the same above reason where a node where the shard was supposed to be assigned created a conflict with the awareness allocation decider. Hence, it is stuck in a state, waiting for space to allocate the unassigned shard because it cannot assign it to the only node with space. This also seemed more likely to happen in this particular test case because it is …
> Mute flaky testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness

- .github/ISSUE_TEMPLATE/bug_template.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Update required dropdowns in issue templates to have no option selected by default.
This change updates the bug and feature templates to set the first option as empty. This prevents form submission until an option is selected.
This wasn't all that intuitive, see https://github.com/orgs/community/discussions/61648, but workaround here is to set the first option to empty.
See my fork to test this behavior out - https://github.com/mch2/OpenSearch/issues/new/choose The form cannot be submit until a value is selected.
N/A …
> Update dropdowns in issue templates to have no option selected by default

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/SearchQueryAggregationCategorizer.java
- server/src/main/java/org/opensearch/action/search/SearchQueryCategorizer.java
- server/src/main/java/org/opensearch/action/search/SearchQueryCategorizingVisitor.java
- server/src/main/java/org/opensearch/action/search/SearchQueryCounters.java
- server/src/main/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilder.java
- server/src/test/java/org/opensearch/action/search/SearchQueryCategorizerTests.java
This changes is part of the [Query Visibility Project](https://github.com/opensearch-project/OpenSearch/issues/11008) and [Search Query Categorization phase 2](https://github.com/opensearch-project/OpenSearch/issues/11040) initiative.
In this change we address the following:
[Search Query Categorization] Expanding the capture of query type and level information #11364
[Search Query Categorization] Identifying the types of aggregations #11366
Resolves #11364,#11366
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of- …
> Capture information for additional query types and aggregations types

- CHANGELOG.md
- buildSrc/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/11798 to `2.x`
> [Backport] [2.x] Bump net.java.dev.jna:jna from 5.13.0 to 5.14.0 (#11798)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
- server/src/main/java/org/opensearch/common/util/concurrent/ThreadContextStatePropagator.java
- server/src/main/java/org/opensearch/tasks/TaskThreadContextStatePropagator.java
- server/src/main/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorage.java
- server/src/main/java/org/opensearch/transport/TransportService.java
- server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
- server/src/test/java/org/opensearch/tasks/TaskThreadContextStatePropagatorTests.java
- server/src/test/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorageTests.java
Skips the Current_Span transient header propagation for the scheduled task. This was messing up with setting up the parent span.
Resolves #10291
- [] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
> Add support for conditional Transient header propagation

- modules/ingest-common/src/main/java/org/opensearch/ingest/common/ScriptProcessor.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/ScriptProcessorTests.java
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/190_script_processor.yml
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/90_simulate.yml
- server/src/main/java/org/opensearch/ingest/IngestDocument.java
- server/src/test/java/org/opensearch/ingest/IngestDocumentTests.java
Additional validations in ingest pipeline script processor
> Fixed ingest pipeline script issue

- server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
The test fails while asserting non-emtpy set of corrupted files [here](https://github.com/opensearch-project/OpenSearch/blob/919aef6aa7a312d2477a1a8b7727c997aa37f603/server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java#L512C13-L512C49). I suspect the failure happens because first round of segment replication completes pre-maturely without actually copying any files, which breaks this assertion. This is possible as listener (for copying files) gets resolved immediately due to [exception](https://github.com/opensearch-project/OpenSearch/blob/ebda9639f4ca98a2181bdcb2c43f82224b1d2a34/server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java#L482) inside custom RemoteStoreReplicationSource. The actual file copy continues async BUT inside test we have …
> Unmute testNoFailuresOnFileReads flaky test

- CHANGELOG.md
- libs/common/src/main/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessor.java
- libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
Spotted a typo in API annotation check message
```
> Task :server:compileJava
Note: Processing Log4j annotations
Note: Annotations processed
Note: Processing OpenSearch Api annotations
Note: The element org.opensearch.common.inject.Module is part of the public APIs but is not maked as @PublicApi, @ExperimentalApi or @DeprecatedApi (referenced by org.opensearch.plugins.Plugin)
(here ⬆︎)
```
Fix typo in API annotation check message.
(Fixing some internal comments as well.)
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cert …
> Fix typo in API annotation check message

- libs/core/src/main/java/org/opensearch/Version.java
Bump 2.12.0 to Lucene 9.9.1 in Version.java
To be merged after https://github.com/opensearch-project/OpenSearch/pull/11832
https://github.com/opensearch-project/OpenSearch/issues/11414
> Bump 2.12.0 to Lucene 9.9.1 in Version.java

- server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityWithRequestBreakerIT.java
Enabling the test as the memory leak wouldn't happen after lucene 99 upgrade as explained [here](https://github.com/opensearch-project/OpenSearch/issues/10154#issuecomment-1876236618)
Validated that the required lucene change is present and ran the test with relevant seed for 500 times to ensure successful runs.
Resolves #10154 
> Enable test CardinalityWithRequestBreakerIT.testRequestBreaker after lucene 99 upgrade

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
- server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
- server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
We have a bug where a flat object field with inner fields that contain dots will "push" the dotted name onto the dot-path from the root, but then would just "pop" off the last part of the dotted name.
This change adds more robust support for flat object keys and subkeys that contain dots (i.e. it pops off the entirety of the latest key, regardless of how many dots it contains).
Fixes https://github.com/opensearch-project/OpenSearch/issues/11402
Backport of https://github.com/opensearch-project/OpenSearch/pull/11425
(cherry picked from commit 22b628bacaab56c145538898ca190ffce9778c6e) …
> [Backport 2.x] Fix parsing of flat object fields with dots in keys

- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
This feature has been released and the feature flag is no longer used.
> Remove unused segment replication feature flag

- server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java
- server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
The explain itself is coming from Lucene: https://github.com/apache/lucene/blob/a6f70ad2bb0b682eb65feb522358ee6d16cad766/lucene/join/src/java/org/apache/lucene/search/join/ToParentBlockJoinQuery.java#L432-L440
Here's some info on the docIds in lucene:
- A DocId in lucene is not actually unique to the Index but is unique to a Segment. Lucene does this mainly to optimize writing and compression. Since it is only unique to a Segment, how can a Doc be uniquely identified at the Index level? The solution is simple. The segments are ordered. To take a simple example, an Index has two segments and each segment has 100 docs respectively. The DocId's in the Segment are 0-100 but when they are converted to the Index level, the range of the DocId's in the second Segment is converted to 100-200.
- …
> Fix SimpleNestedIT.testExplain flaky test

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/ShardSizeTermsIT.java
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsDocCountErrorIT.java
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsFixedDocCountErrorIT.java
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsShardMinDocCountIT.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalTerms.java
- server/src/main/java/org/opensearch/search/internal/SearchContext.java
This PR fixes how doc count error is calculated for terms aggregations for conurrent segment search and sets the `slice_size` heuristic introduced in #11585 to be equal to the `shard_size`.
The crux of this change is the introduction of `hasSliceLevelDocCountError`, to indicate to the coordinator whether or not the `slice_size` is the reason for why the error exists. This affects how the top level aggregation error is then calculated in the single shard (and single slice) scenarios.
Resolves #11680
Resolves #11702 …
> Correctly calculate doc count error at the slice level for concurrent segment search

- DEVELOPER_GUIDE.md
- gradle/run.gradle
Update runTask to optionally install plugins from the command line.
Resolves https://github.com/opensearch-project/OpenSearch/issues/6285
> Update runTask to optionally install plugins

- CHANGELOG.md
- libs/common/src/main/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessor.java
- libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
- Fixing some internal comments as well
(cherry picked from commit feeb595be5c998efca4d11d65ea6a3d00cea17dd)
Resolves #11836 
> [Backport] [2.x] Fix typo in API annotation check message (#11836)

- DEVELOPER_GUIDE.md
- gradle/run.gradle
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/11844 to 2.x
> [Backport 2.x] Update runTask to optionally install plugins (#11844)

- server/src/test/java/org/opensearch/common/logging/LoggersTests.java
- server/src/test/java/org/opensearch/common/settings/InsecureSettingTests.java
The appender was being added to the logger before the appender was started. This can lead to logger errors with concurrently running tests because the logger is static state shared across the JVM. See #10799.
I've also added a removeAppender call that was missing from LoggersTests, but that is mostly hygiene and would not lead to failures.
Resolves #10799
> Fix log appender in InsecureSettingTests

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/indices.update_aliases/40_remove_with_must_exist.yml
This [PR](https://github.com/opensearch-project/OpenSearch/pull/11210) enables the parameter must_exist in update aliases API and will be release in 2.12.0, in order to ensure the backward compatibility checks pass, the supported version in yaml test file was set to 3.0.0 in that PR, after the PR was merged and backport to 2.x, we need to update the supported version to 2.12.0 in main branch so that the backward compatibility checks can cover the change.
Backport 2.x is not needed.
https://github.com/opensearch-project/OpenSearch/issues/2949 …
> Update supported version for must_exist parameter in update aliases API

- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
This PR adds the code missed from the backport of the PR #10513.
Resolves #10585 & #10513
> Add missing code in InternalEngine part of #10513

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/CopyProcessor.java
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/CopyProcessorFactoryTests.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/CopyProcessorTests.java
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/10_basic.yml
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/300_copy_processor.yml
- server/src/main/java/org/opensearch/ingest/IngestDocument.java
This PR adds a new ingest processor called `copy` processor which can copy the whole object from one existing field to another field, this is useful when users want to copy a nested field to the root level and then delete the original field, this cannot be achieved by set processor because it doesn't support copying object, only basic data types are supported. In addition, even though script processor can be used to copy object, but writing painless script is not easy for users. The copy processor provides an easy way to copy object.
The usage of copy processor are as follows:
```
POST _ingest/pipeline/_simulate
{
"pipeline": {
"processors": [
{
"copy": {
"source_field": "{{foo}}", 
"target_field":"target",
"ignore_missing":true,
"override_target":true,
"remove_source":true
}
}
]
}, …
```
> Add copy ingest processor

- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
This closes #11256. The flakiness in the `RemoteStoreRefreshListenerTests.testTrackerData` test is happening due to `RemoteSegmentStoreDirectory.init()` method being called on account of simultaneous refreshes from test. In the test setup, we create a full fledged IndexShard and use it's remote store classes for mimicing/mocking certain test behaviours. Now, the refreshes of the underlying IndexShard and the manually invoked test's afterRefreshes were happening simultaneously causing the shared `RemoteSegmentStoreDirectory` object's `segmentsUploadedToRemoteStore` map to get cleared. The changes now ensures that the concurrency does not happen any more.
Resolves #11256
For …
> Fix flaky RemoteStoreRefreshListenerTests testTrackerData #11256

- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
This closes #9605. The flakiness in this test is on account of translog.trimUnreferencedReaders() being no-op when called due to previous deletion still ongoing and holding the permits. The current run of translog.trimUnreferencedReaders() on checking for permits sees that the required permits are not available and skips the deletion. To elaborate more on generation deletion, the approach is to acquire the permits, trigger async deletion and post successful deletion, release the permits. With this PR, I am making sure that after `trimUnreferencedReaders()`, we check that the required permits are available before calling the same method back again. 
Resolves #9605 
For more …
> Fix flaky RemoteFSTranslogTests testMetadataFileDeletion test #9605

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/50_noop_update.yml
Part of https://github.com/opensearch-project/OpenSearch/pull/11485, after the original PR has been backported to 2.x branch, we need to update the supported version to 2.12.0 so that the backward compatibility checks can cover the change.
This PR needs to backport to 2.x because the supported version in 2.x branch is also 3.0.0(it's done by the bot).
https://github.com/opensearch-project/OpenSearch/issues/9857
> Update supported version for fixing the bug of noop_update_total metric cannot be updated by bulk API

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
- server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsMoveShardsTests.java
Two changes here:
1. Support index level allocation filtering for searchable snapshot index: filter out the shards that cannot remain on the current node and prioritize moving them to eligible nodes before considering moving shards on excluded nodes;
2. Eliminate the logic of swapping primary with replica, as a shard cannot be transitioned from primary to replica mode.
https://github.com/opensearch-project/OpenSearch/blob/6bb53dea24264fc91dc46824041157066a16b74e/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L604
Resolves #11468 …
> Support index level allocation filtering for searchable snapshot index

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/path/PathTrie.java
- server/src/main/java/org/opensearch/rest/MethodHandlers.java
- server/src/main/java/org/opensearch/rest/RestController.java
- server/src/main/java/org/opensearch/rest/RestMethodHandlers.java
- server/src/test/java/org/opensearch/common/path/PathTrieTests.java
- server/src/test/java/org/opensearch/rest/RestControllerTests.java
Coming from https://github.com/opensearch-project/OpenSearch/pull/11843, expose just enough methods to be able to move that plugin implementation out of OpenSearch core.
- Adds `PathTrie#retrieveAll`, an lazy-ish exhaustive iterator traversing the trie structure.
- Make public `MethodHandlers#getPath` and `getValidMethods`.
- Adds `RestController#getAllHandlers()` returning a method handlers iterator.
- https://github.com/opensearch-project/OpenSearch/issues/3090
- https://github.com/opensearch-project/opensearch-api-specification/issues/168
- https://github.com/opensearch-project/opensearch-clients/issues/58 …
> Expose RestController all handlers iterator.

- libs/common/src/main/java20/org/opensearch/common/round/RoundableFactory.java
Since non-core plugins run integration tests using JDK-21, the `jdk.incubator.vector` is not enabled by default, causing:
```
Caused by:                                                                                                                                                   
java.lang.NoClassDefFoundError: jdk/incubator/vector/LongVector                                                                                              
at __randomizedtesting.SeedInfo.seed([D65A64F81C71BE2B]:0)                                                                                               
at org.opensearch.common.round.RoundableFactory.<clinit>(RoundableFactory.java:39)                                                                       
at …
```
> Only check LongVector.SPECIES_PREFERRED when jdk.incubator.vector is enabled

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
- RemoteStoreRestoreIT has bunch of tests which require empty translog during restore, ie no data is ingested after last refresh/commit.
- Currently our tests were ingesting data even after last refresh/commit even though tests did not want that.
- This PR allows last iteration of data ingestion method to skip ingestion after last refresh/commit
NA
> Allow empty translog for ITs testing no ingestion post refresh/commit

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/util/ReorganizingLongHash.java
Signed-off-by: Neetika Singhal <neetiks@amazon.com>
(cherry picked from commit 84f303b6069893cf9350556a4c316153ba526901)
Backports https://github.com/opensearch-project/OpenSearch/pull/11953
> Fix memory leak issue in ReorganizingLongHash (#11953)

- .github/workflows/version.yml
- Coming in from https://github.com/opensearch-project/OpenSearch/pull/7442#issuecomment-1542766937 
- Built on top of #7442 with the necessary suggestions
- Sample run: https://github.com/kotwanikunal/OpenSearch/issues/154
New components: 
- Utilizes [peternied/opensearch-core-version-updater](https://github.com/peternied/opensearch-core-version-updater)
- Related to #7396
> [Github Action] Enhance version increment script to create tracking issue

- CHANGELOG.md
- buildSrc/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/11963 to `2.x`
> [Backport] [2.x] Bump com.networknt:json-schema-validator from 1.1.0 to 1.2.0 (#11963)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
- server/src/test/java/org/opensearch/common/util/concurrent/OpenSearchExecutorsTests.java
Workaround for https://bugs.openjdk.org/browse/JDK-8323659 regression, introduced in JDK-21.0.2
See please https://github.com/opensearch-project/OpenSearch/issues/11906
> Workaround for https://bugs.openjdk.org/browse/JDK-8323659 regression, introduced in JDK-21.0.2

- modules/ingest-common/src/test/java/org/opensearch/ingest/common/CopyProcessorTests.java
Flaky test found in `org.opensearch.ingest.common.CopyProcessorTests.testCopyToExistingField`, the reason is that when one filed to another, we use [deepCopy](https://github.com/opensearch-project/OpenSearch/blob/b0eab7579aaf7715c6eea7a3d1e206b7d1cb6760/server/src/main/java/org/opensearch/ingest/IngestDocument.java#L760), if the copied object is a map and its value is array, the `equalTo` assertion in CopyProcessorTests will fail, we should handle this case correctly. I've added a new assert method to handle that case, the code are inspired by [here.](https://github.com/opensearch-project/OpenSearch/blob/b0eab7579aaf7715c6eea7a3d1e206b7d1cb6760/test/framework/src/main/java/org/opensearch/test/hamcrest/OpenSearchAssertions.java#L769).
Ran 1000 times in my local env with this change, never …
> Fix flaky test for CopyProcessorTests

- server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRemoteClusterInfoAction.java
- server/src/main/java/org/opensearch/rest/action/admin/indices/RestPutMappingAction.java
Coming from https://github.com/opensearch-project/opensearch-api-specification/pull/179 which flags a couple of false positives because of mismatched trailing slash.
> Fix: remove unnecessary trailing/missing leading slash from REST paths.

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveProcessor.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorFactoryTests.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorTests.java
Fix the typo in RemoveProcessor, ether should be `either`, and `either ... and` should be `either ... or`. 
No issue, the typo was introduced by [this PR](https://github.com/opensearch-project/OpenSearch/pull/10967), when I wrote document for the functionality in that PR, I found this typo.
> Fix typo in RemoveProcessor

- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsFixedDocCountErrorIT.java
Set index refresh interval to -1, should make segment count for these tests stable. Ran offline 10k times.
Resolves #11950
> Disable index refresh for TermsFixedDocCountErrorIT

- CHANGELOG.md
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestClusterRule.java
- test/framework/src/test/java/org/opensearch/test/ParameterizedDynamicSettingsOpenSearchIntegTests.java
- test/framework/src/test/java/org/opensearch/test/ParameterizedStaticSettingsOpenSearchIntegTests.java
- test/framework/src/test/java/org/opensearch/test/SuiteScopedParameterizedDynamicSettingsOpenSearchIntegTests.java
- test/framework/src/test/java/org/opensearch/test/SuiteScopedParameterizedStaticSettingsOpenSearchIntegTests.java
- test/framework/src/test/java/org/opensearch/test/TestScopedParameterizedDynamicSettingsOpenSearchIntegTests.java
- test/framework/src/test/java/org/opensearch/test/TestScopedParameterizedStaticSettingsOpenSearchIntegTests.java
There are duality in how the suite scoped test cases are managed by OpenSearch integration test framework:
- `@ClusterScope(scope = Scope.SUITE)` 
- `@OpenSearchIntegTestCase.SuiteScopeTestCase`
It turns out handling those follow very different flows, and I've covered `@OpenSearchIntegTestCase.SuiteScopeTestCase` for parameterized tests only, but not `@ClusterScope(scope = Scope.SUITE)`, fixing that now.
Thanks @Rishikesh1159  for find this one out.
@andrross @Rishikesh1159 please
Followup on https://github.com/opensearch-project/OpenSearch/pull/11877#issuecomment-1906812635 …
> Fix test cluster behavior @ClusterScope(scope = Scope.SUITE) and @OpenSearchIntegTestCase.SuiteScopeTestCase for parameterized test cases

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveProcessor.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorFactoryTests.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/11983 to 2.x
No issue, the typo was introduced by https://github.com/opensearch-project/OpenSearch/pull/10967, when I wrote document for the functionality in that PR, I found this typo.
> [Backport 2.x] Fix typo in RemoveProcessor (#11983)

- test/fixtures/minio-fixture/docker-compose.yml
While I was trying to run the S3 `testRequestStats` tests,  Minio Fixture was seeing problems with docker-compose specifically with volumes having extended notation. 
```
> Task :test:fixtures:minio-fixture:composeBuild FAILED
The Compose file './docker-compose.yml' is invalid because:
services.minio-fixture.volumes contains an invalid type, it should be a string
services.minio-fixture-for-snapshot-tool.volumes contains an invalid type, it should be a string
services.minio-fixture-other.volumes contains an invalid type, it should be a string
``` 
From docker https://github.com/docker/compose/issues/4763, version 3.2 supports extended notations and it works!
Background: Was trying to fix https://github.com/opensearch-project/OpenSearch/issues/9859 and ended up on repository S3 test which …
> Fixing Minio docker compose fixture

- CHANGELOG.md
- NOTICE.txt
- server/src/main/java/org/opensearch/common/time/DateFormatters.java
- server/src/main/java/org/opensearch/common/time/FormatNames.java
- server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
- server/src/main/java/org/opensearch/common/time/OpenSearchDateTimeFormatter.java
- server/src/main/java/org/opensearch/common/time/OpenSearchDateTimePrinter.java
- server/src/main/java/org/opensearch/common/time/RFC3339CompatibleDateTimeFormatter.java
- server/src/test/java/org/opensearch/common/joda/JavaJodaTimeDuellingTests.java
- server/src/test/java/org/opensearch/common/time/DateFormattersTests.java
This PR adds new `rfc3339` format for datetime parsing whose implementation is not based on the usual java datetime formatters but is hand written to make it extremely fast. RFC3339 format is one of the most used format for datetime across internet. The parser implements a lenient version of rfc3339 which aligns more with W3C Note.
This implementation is 42x faster than `strict_date_optional_time_format` to parse rfc3339 compatible datetime strings.
Microbenchmark results
```
DocumentParsingBenchmark.benchRFC3339Parser               2023-01-01T23:38:34.000Z  avgt   30    66.321 ±  0.424  ns/op
DocumentParsingBenchmark.benchRFC3339Parser               1970-01-01T00:16:12.675Z  avgt   30    68.199 ±  1.341  ns/op
DocumentParsingBenchmark.benchRFC3339Parser …
```
> Added New Fast DateTime parser implementation for RFC3339 Datetime format

- test/framework/src/main/java/org/opensearch/test/MockLogAppender.java
Issue #10799 is caused by a stopped or unstarted appender still being present in the static logger state. I have not been able to find the improper usage of the log appender that would cause this error. To help debug, this commit adds the calling class name to the mock log appender. Any future occurrence should result in an error message with the class name that incorrected configured the logger.
I've also added an override to the `stop()` method to force that callers use the close() method that properly cleans up the logger state as opposed to stopping the appender directly. …
> Add calling class name to mock log appender

- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
Minor bugfix that ensures the right boundary value is checked while pulling objects from S3 remote store. Existing logic checks `totalObjects > limit`, which could lead to extra S3 calls if the next page needs to be fetched to breach this condition. This is unnecessary if we have already hit `limit` with the current pages. This further ensures we don't make additional S3 calls down the pipeline when we consume the `results`.
N/A
> Fix limit check for listing S3 objects

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
Today, `RemoteShardsBalancer` uses `AllocationDecider#canAllocateAnyShardToNode` to filter throttled or ineligible nodes during allocating unassigned shards. If all eligible nodes of an unassigned shard are filtered before trying to allocate this shard, the shard will be marked as ignored with `UnassignedInfo.AllocationStatus.DECIDERS_NO` status. As a result, the corresponding `ShardRestoreStatus` will be set to `Failure` (`RestoreService.RestoreInProgressUpdater#unassignedInfoUpdated`). This pull request takes throttled nodes into account and ensures that shards are marked with the appropriate status.
For more …
> [BUG] Fix remote shards balancer when filtering throttled nodes

- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManager.java
- server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- server/src/test/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManagerTests.java
**<Pending Tests>**
- Currently, snapshot interop with remote store takes a lock on remote segment store metadata files.
- This lock ensures that the metadata file is not deleted as part of cleanup of stale files.
- Cleanup of stale metadata files happen at each flush and to check if the lock is acquired or not, a remote store call is made.
- This can result in too many remote store calls when there are too many snapshots present and frequent flushes.
- In this change, we list all the lock files to avoid multiple remote store calls.
Resolves https://github.com/opensearch-project/OpenSearch/issues/11409 …
> Fetch all the locks for a shard to avoid multiple remote store calls

- CHANGELOG.md
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
1. Add configurable S3 plugin's  setting `max_sync_connections` for sync client's max connections.
2. Uses  existing setting `connection_acquisition_timeout` for sync client as well . Today it is only used in async client. 
Resolves #12027 
> Adding configurable connection count setting for S3 Sync Client

- CHANGELOG.md
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
* Adding configurable connection count setting for S3 Sync Client
* Address PR Comments
* Increase number of connections to 500
---------
1. Add configurable S3 plugin's  setting `max_sync_connections` for sync client's max connections.
2. Uses  existing setting `connection_acquisition_timeout` for sync client as well . Today it is only used in async client. 
Resolves #12027 
> [Backport 2.x] Adding configurable connection count setting for S3 Sync Client (#12028)

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
- During primary failover, post primaryMode activate on the new primary, the new primary can still upload segment metadata with older primary term
- This is because the ReplicationCheckpoint used to get the primaryTerm during upload might itself have the older primaryTerm
- This is more prominent if indexing has stopped during failover(need to verify this)
- Currently it seems the replication checkpoint is only updated during recovery, failover, refresh, that too if the latest segmentInfos version and generation doesnt match with the current replication checkpoint.
- After failover we trigger refresh, which should update the replication checkpoint but since there is not new data, we use the cached replication checkpoint
- With this PR, we have added additional check on primaryTerm to make …
> Ensure latest replication checkpoint post failover has correct operational primary term

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
This changes enables trace logging on replication and recovery package for `testRelocateWhileContinuouslyIndexingAndWaitingForRefresh` test. This test currently fails due to documents not present on target primary shard post shard relocation. 
https://build.ci.opensearch.org/job/gradle-check/30438/testReport/org.opensearch.indices.replication/SegmentReplicationRelocationIT/testRelocateWhileContinuouslyIndexingAndWaitingForRefresh_2/
```
java.lang.AssertionError: Expected search hits on node: node_t2 to be at least 1000 but was: 873
```
Related: #6778  …
> Flaky testRelocateWhileContinuouslyIndexingAndWaitingForRefresh test: Enable trace logs on replication and recovery

- CHANGELOG.md
This entry will be released in 2.12 so it should not be in the 3.0 section.
> Move Google Application Default Credentials CHANGELOG entry to 2.x

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Coming from https://github.com/opensearch-project/OpenSearch/issues/11299, need to enable logs at cluster and replication level for debugging the cause of cluster heapth request timeout. 
Related https://github.com/opensearch-project/OpenSearch/issues/11299
> Enable cluster and replication package debug logging for testSingleIndexShardAllocation test

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/SearchPhaseName.java
- server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
The SearchRequestOperationsListener `onPhaseStart()` method is getting called TWICE consecutively during query phase in select cases. This occurs any time following can match phase. `onPhaseStart()` should only be called ONCE per search phase and must be paired with either `onPhaseEnd()` or `onPhaseFailure()`.
1. Rename first instance of duplicate "query" phase to "none" phase as it is not yet reached `SearchQueryThenFetchAsyncAction`
2. Call onPhaseStart() only when current phase is one of 6 search phases we track
```
public enum SearchPhaseName {
DFS_PRE_QUERY("dfs_pre_query"),
QUERY("query"),
FETCH("fetch"),
DFS_QUERY("dfs_query"),
EXPAND("expand"),
CAN_MATCH("can_match");
}
```
- existing UTs
- phase_took search
```
% curl -XGET 'localhost:9200/_search?pretty&phase_took' -H …
```
> [Bug] Check phase name before SearchRequestOperationsListener onPhaseStart

- qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
- server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
- server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
This change fixes and unmutes segrep bwc test testIndexingWithSegRep.
This change removes retries within PrimaryShardReplicationSource and relies on retries in one place at the start of replication. This is done within SegmentReplicationTargetService's processLatestReceivedCheckpoint after a failure/success occurs. The timeout on these retries is the cause of flaky failures from SegmentReplication's bwc test within IndexingIT, that can occur on node disconnect.  The retries will persist for over ~1m to the same primary node that has been relocated/shut down and cause the test to timeout.
This change also includes simplifications to the cancellation flow on the target service before the shard is closed. Previously we "request" a cancel that does not remove the target from the ongoing …
> Remove compounding retries within PrimaryShardReplicationSource

- DEVELOPER_GUIDE.md
Trivial typo fix. (Sorry if you don’t want such tiny PRs, I tried looking for other typos in `.md` files but couldn’t find any.)
> Fixed typo in DEVELOPER_GUIDE.md.

- CHANGELOG.md
- plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleApplicationDefaultCredentials.java
- plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageService.java
- plugins/repository-gcs/src/test/java/org/opensearch/repositories/gcs/GoogleCloudStorageServiceTests.java
backport [#8394](https://github.com/opensearch-project/OpenSearch/pull/8394) to `2.x`
> [Backport 2.x] Support for Google Application Default Credentials (#8394)

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
Fixes flaky test SegmentReplicationStatsIT.testMultipleIndices. The test was failing an assertion error on the replica stats after the segmentReplicationStatsResponse was received. We fix this by adding in an assertBusy on the stats request call. 
Ran the test 1000 times and an additional 200 times as part of the SegmentReplicationStatsIT test suite.
Resolves #11454
> Fix flaky test SegmentReplicationStatsIT.testMultipleIndices

- server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
This PR fixes the flakiness in the testRerouteRecovery of RemoteIndexRecoveryIT.
The issue is happening due to 2 reasons as we have seen the stack trace -
1. Index not found
```
org.opensearch.remotestore.RemoteIndexRecoveryIT > testRerouteRecovery FAILED
[test-idx-1/gUdo_ZgeQSeTKz75x2BNLA] IndexNotFoundException[no such index [test-idx-1]]
at __randomizedtesting.SeedInfo.seed([216A80F8C219BD32:8CC133ACF741DF70]:0)
at app//org.opensearch.indices.IndicesService.indexServiceSafe(IndicesService.java:689)
at app//org.opensearch.indices.recovery.IndexRecoveryIT.lambda$testRerouteRecovery$1(IndexRecoveryIT.java:528)
```
2. Assertion failure 
```
Expected: <1>
but: was <0>
at __randomizedtesting.SeedInfo.seed([A66685B0FBDCA162:BCD36E4CE84C320]:0)
at …
```
> Fix flaky RemoteIndexRecoveryIT testRerouteRecovery test #9580

- CHANGELOG.md
- NOTICE.txt
- server/src/main/java/org/opensearch/common/time/DateFormatters.java
- server/src/main/java/org/opensearch/common/time/FormatNames.java
- server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
- server/src/main/java/org/opensearch/common/time/OpenSearchDateTimeFormatter.java
- server/src/main/java/org/opensearch/common/time/OpenSearchDateTimePrinter.java
- server/src/main/java/org/opensearch/common/time/RFC3339CompatibleDateTimeFormatter.java
- server/src/test/java/org/opensearch/common/joda/JavaJodaTimeDuellingTests.java
- server/src/test/java/org/opensearch/common/time/DateFormattersTests.java
Backporting #11465
Resolves #8361
> [Backport 2.x] Added New Fast DateTime parser implementation for RFC3339 Datetime format

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
- Fixes flaky test org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT.testFullClusterRestoreGlobalMetadata
- We were not using assertBusy properly, handled IllegalStateException and throwing AssertionError
Resolves https://github.com/opensearch-project/OpenSearch/issues/10749
> fix flaky test - handle IllegalStateException and throw AssertionError to use assertbusy

- server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java
The test was errorring out due to timeout.
> java.lang.AssertionError: Unexpected exception: ProcessClusterEventTimeoutException[failed to process cluster event (add-block-index-to-close [[vquumsvuoq/KiZV1g8bRsWoscd3K-G7Tg]]) within 30s]
Increased the timeout to 60s. 5000 iterations passed locally.
Screenshot of 1000 iterations passing:
Resolves #11610
> Fix Flaky CloseIndexIT.testCloseWhileDeletingIndices

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
- server/src/main/java/org/opensearch/index/fielddata/AbstractNumericDocValues.java
- server/src/main/java/org/opensearch/index/fielddata/FieldData.java
- server/src/main/java/org/opensearch/index/fielddata/NumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsNumericDocValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToSortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToSortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/plain/SortedNumericIndexFieldData.java
- server/src/main/java/org/opensearch/index/query/functionscore/DecayFunctionBuilder.java
- server/src/main/java/org/opensearch/search/MultiValueMode.java
- server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
- server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
Add advance(int) for numeric values in order to allow point based optimization to kick in, huge thanks to @jed326 for investigating the cause of the issue (quoting below):
It looks like we encounter the problem with sort for, double_value, and unsigned_long_value as well.
The problem seems to be related to this change: https://github.com/apache/lucene/pull/12405
Specifically: https://github.com/apache/lucene/commit/d9109907bcafd9e3ac6a23bff9e5b1b2605bb2f8#diff-79c6a57519ecd1ef504629e62e13d17859a4ffedc58f4602e583ce758a15adc8R291-R295
﻿﻿﻿﻿﻿﻿﻿As the comparator is getting set to NumericComparator::NumericLeafComparator. In the non-concurrent search case we don't go into the if statement so the competitiveIterator is not updated.
The if statement seems to be related to the number of documents …
> Add advance(int) for numeric values in order to allow point based optimization to kick in

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationResizeRequestIT.java
- server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
For a call to shrink index in a segment replication enabled cluster, we perform a fast fail whenever the replica shards of the source index are not up to date with their primary shard. However, the exception we provide only asks customers/users to retry after sometime but does not specify how to check if their replicas are now up to date and ready for a retry of a shrink operation. Changed the exception to reflect this additional information. 
Resolves #11352 partially.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifica …
> [Segment Replication] Modify shrink exception to be more informative

- build.gradle
- Adds `testThreeNodesNoClusterManagerBlock ` to the retry test list
- The test is noisy and has led to a ton of failures
Related: #10006 
> Add test testThreeNodesNoClusterManagerBlock to retry list

- test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
The test currently blocks on receiving a response to the request for the "internal:testNotSeen" action. However, that response is sent from TransportService before the trace logger [writes its log message][1]. Since the test was not polling for this "sent response" log message to appear that meant it was possible for the test to remove/stop the mock log appender concurrently with the logging of that final message. The fix is to include this final log message as an expectation, so the test will poll until this message appears and the logger should be quiescent when the appender is removed and stopped.
[1]: https://github.com/opensearch-project/OpenSearch/blob/71f1fabe149fd0777edf44502ace4a8f0911feeb/server/src/main/java/org/opensearch/transport/TransportService.java#L1273
Resolves #10799 …
> Fix race condition in testTracerLog

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
- server/src/main/java/org/opensearch/index/fielddata/AbstractNumericDocValues.java
- server/src/main/java/org/opensearch/index/fielddata/FieldData.java
- server/src/main/java/org/opensearch/index/fielddata/NumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsNumericDocValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToSortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/SortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToSortedNumericDoubleValues.java
- server/src/main/java/org/opensearch/index/fielddata/plain/SortedNumericIndexFieldData.java
- server/src/main/java/org/opensearch/index/query/functionscore/DecayFunctionBuilder.java
- server/src/main/java/org/opensearch/search/MultiValueMode.java
- server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
- server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/12089 to `2.x`
> [Backport] [2.x] Add advance(int) for numeric values in order to allow point based optimization to kick in (#12089)

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationBuilder.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/filter/FilterAggregatorFactory.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
Composite aggregations are able to run under a filter aggregation with no change required (other than not throwing an exception). Similarly, they can run under a reverse nested aggregation.
Also cleaned up FilterAggregatorFactory a little.
Resolves #11131
> Allow composite aggregation under filter or reverse_nested parent 

- rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/cat.thread_pool/10_basic.yml
Fix bwc after https://github.com/opensearch-project/OpenSearch/pull/12152 has been merged
> Fix bwc for concurrent segment search GA

- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
- Acquire refresh permits before closing the IndexShard in `RemoteStoreRefreshListenerTests`.
- https://github.com/opensearch-project/OpenSearch/issues/9773
- https://github.com/opensearch-project/OpenSearch/issues/8947
- https://github.com/opensearch-project/OpenSearch/issues/8945
> Add drainRefreshes as part of tearDown in RemoteStoreRefreshListenerTests

- CHANGELOG.md
- distribution/packages/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/12167 to `2.x`
> [Backport] [2.x] Bump com.netflix.nebula.ospackage-base from 11.6.0 to 11.8.0 in /distribution/packages (#12167)

- qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Test is flaky as seg-rep is causing issues during lucene codec upgrade. There is a separate test for seg-rep and upgrade. Disabling seg-rep in the fuzzy filter tests
> Disable seg-rep for fuzzy filter postings upgrade IT

- CHANGELOG.md
- plugins/query-insights/build.gradle
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/MetricType.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/package-info.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecordTests.java
- server/src/main/java/org/opensearch/action/search/SearchRequest.java
- server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
- server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
- server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
- server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactoryTests.java
Backporting https://github.com/opensearch-project/OpenSearch/pull/11903 to 2.x
---------
Signed-off-by: Chenyang Ji <cyji@amazon.com>
(cherry picked from commit 3cbf54e7358fd707a0d73e6c016b04ce78884d30)
> [Backport 2.x] Query insights plugin implementation (#11903)

- server/src/main/java/org/opensearch/threadpool/ThreadPool.java
With the Lucene 9.9 changes the `search` threadpool will now offload *all* the tasks to the `index_searcher` threadpool. Since the number of threads for the `index_searcher` threadpool today is `allocatedProcessors`, this will significantly reduce the throughput of concurrent segment search.
Previously, there are 1.5x processors for the search threadpool and 1x processors for the index_searcher threadpool, giving 2.5x processor threads available for search. With the Lucene 9.9 change there will only be 1x processors available for the `index_searcher` threadpool to use. Even for the single slice case this is a significant throughput decrease as previously the single slice case would be executed on the `search` threadpool which has 1.5x processor threads.
This PR bumps the `index_searcher` …
> Increase index_searcher thread count to 2x processor

- server/src/main/java/org/opensearch/common/lucene/search/function/ScriptScoreQuery.java
- server/src/test/java/org/opensearch/search/query/ScriptScoreQueryTests.java
This is a bug when `_score` is included in script, and the `TwoPhaseIterator` of a `MinScoreScorer` doesn't check the `ScriptScorer` for a `match` before asking it for a score for the current doc:
https://github.com/opensearch-project/OpenSearch/blob/a9ce180b57dc20408e5a36337dbdc85d6e1fd306/server/src/main/java/org/opensearch/common/lucene/search/function/MinScoreScorer.java#L98-L103
https://github.com/opensearch-project/OpenSearch/issues/8155
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/C …
> [Bugfix] Pass TwoPhaseIterator from subQueryScorer

- CHANGELOG.md
- plugins/query-insights/src/internalClusterTest/java/org/opensearch/plugin/insights/QueryInsightsPluginTransportIT.java
- plugins/query-insights/src/javaRestTest/java/org/opensearch/plugin/insights/TopQueriesRestIT.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueries.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesAction.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequest.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponse.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesAction.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesAction.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/package-info.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequestTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponseTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesActionTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesActionTests.java
> [Backport 2.x] Top N Queries by latency implementation

- server/src/main/java/org/opensearch/threadpool/ThreadPool.java
> [Backport 2.12] Increase index_searcher thread count to 2x processor (#12196)

- server/src/main/java/org/opensearch/threadpool/ThreadPool.java
> [Backport 2.x] Increase index_searcher thread count to 2x processor (#12196)

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonPlugin.java
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveByPatternProcessor.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveByPatternProcessorFactoryTests.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveByPatternProcessorTests.java
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/10_basic.yml
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/310_remove_by_pattern_processor.yml
Backport https://github.com/opensearch-project/OpenSearch/pull/11920 to 2.x.
https://github.com/opensearch-project/OpenSearch/issues/1578
> [Backport 2.x] Add remove_by_pattern ingest processor (#11920)

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonPlugin.java
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveByPatternProcessor.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveByPatternProcessorFactoryTests.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveByPatternProcessorTests.java
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/10_basic.yml
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/310_remove_by_pattern_processor.yml
Backport https://github.com/opensearch-project/OpenSearch/pull/11920 to 2.12.
https://github.com/opensearch-project/OpenSearch/issues/1578
> [Backport 2.12] Add remove_by_pattern ingest processor (#11920)

- CHANGELOG.md
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/OTelTelemetryPlugin.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/OTelTelemetrySettings.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelResourceProvider.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/sampler/OTelSamplerFactory.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/sampler/ProbabilisticSampler.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/sampler/ProbabilisticTransportActionSampler.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/sampler/RequestSampler.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/OTelTelemetryPluginTests.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/sampler/OTelSamplerFactoryTests.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/sampler/ProbabilisticSamplerTests.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/sampler/ProbabilisticTransportActionSamplerTests.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/sampler/RequestSamplerTests.java
- server/src/main/java/org/opensearch/telemetry/TelemetrySettings.java
- server/src/test/java/org/opensearch/telemetry/TelemetrySettingsTests.java
* Added custom sampler support based on action in request
Signed-off-by: Dev Agarwal <devagarwal1803@gmail.com>
* UT Fix
Signed-off-by: Dev Agarwal <devagarwal1803@gmail.com>
* Added Transport action sampler, which will sample based on different probability for all actions
Signed-off-by: Dev Agarwal <devagarwal1803@gmail.com>
* Added Transport action sampler, which will sample based on different probability for all actions. Also added setting to define order of samplers
Signed-off-by: Dev Agarwal <devagarwal1803@gmail.com>
* Added missing java-doc
Signed-off-by: Dev Agarwal <devagarwal1803@gmail.com>
* Moving sampler class settings to OtelTelemetry setting
Signed-off-by: Dev Agarwal <devagarwal1803@gmail.com>
* Minor refactor
Signed-off-by: Dev Agarwal <devagarwal1803@gmail.com>
* …
> Added custom sampler support based on action in request (#10136)

- CHANGELOG.md
- server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
- server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
- server/src/test/java/org/opensearch/telemetry/tracing/SpanBuilderTests.java
* bug fix to have RestActions rawPath as operation names, query params as tags and avoid using exact URI (#10791)
---------
Signed-off-by: Atharva Sharma <athrv@amazon.com>
Signed-off-by: Atharva Sharma <60044988+atharvasharma61@users.noreply.github.com>
Co-authored-by: Atharva Sharma <athrv@amazon.com>
(cherry picked from commit c0fca74709e96ec7c8cf295cdca6110946b592b8)
Backport/backport 12005 to 2.12
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-or …
> Backport/backport 12005 to 2.12

- buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
- gradle/code-coverage.gradle
Update the lucene snapshot url (correctly)
Issues:
- Driver of this change https://github.com/opensearch-project/opensearch-build/issues/3874#issuecomment-1934891715
- Previous change updated the wrong location #11728
> Update the lucene snapshot url

- server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
testIssue6614 was a flaky test failing intermittently due to FileSystemException "Too many open files". This was caused due to the high number of shards created by the test (~750 shards). 
Reducing the range of possible number of indices created solved this issue with minimal change required to underlying OpenSearchIntegTestCase and the rest of the randomized parameters for the test (shards, replicas, data nodes, etc). It also doesn't affect the logic of the test. 
More details in linked issue. 
Resolves #11347  …
> Fix flaky test FieldSortIT.testIssue6614

- CHANGELOG.md
- distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/ListPluginsCommand.java
- distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
- distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/ListPluginsCommandTests.java
- libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
- libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
- libs/core/src/main/java/org/opensearch/semver/SemverRange.java
- libs/core/src/main/java/org/opensearch/semver/expr/Caret.java
- libs/core/src/main/java/org/opensearch/semver/expr/Equal.java
- libs/core/src/main/java/org/opensearch/semver/expr/Expression.java
- libs/core/src/main/java/org/opensearch/semver/expr/Tilde.java
- libs/core/src/main/java/org/opensearch/semver/expr/package-info.java
- libs/core/src/main/java/org/opensearch/semver/package-info.java
- libs/core/src/test/java/org/opensearch/semver/SemverRangeTests.java
- libs/core/src/test/java/org/opensearch/semver/expr/CaretTests.java
- libs/core/src/test/java/org/opensearch/semver/expr/EqualTests.java
- libs/core/src/test/java/org/opensearch/semver/expr/TildeTests.java
- qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/PluginInfoIT.java
- qa/mixed-cluster/src/test/java/org/opensearch/backwards/PluginInfoIT.java
- server/src/internalClusterTest/java/org/opensearch/plugins/PluginsServiceIT.java
- server/src/main/java/org/opensearch/plugins/PluginInfo.java
- server/src/main/java/org/opensearch/plugins/PluginsService.java
- server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
- server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
- test/framework/src/main/java/org/opensearch/test/VersionUtils.java
Backport https://github.com/opensearch-project/OpenSearch/pull/11441 to 2.x.
Following are the additional changes: 
1. Updated PluginInfo version check for serialization of semver range list to use V_2_13_0.
2. Updated PluginInfo version check of Version.V_1_1_0 for custom folder name and related test. 
3. Resolved minor conflicts in ListPluginsCommandTests.java
Resolves https://github.com/opensearch-project/OpenSearch/issues/1707
> [Backport 2.x] Add support for dependencies in plugin descriptor properties with semver range #11441

- server/src/main/java/org/opensearch/plugins/PluginInfo.java
Fixes BwC versioning introduced with https://github.com/opensearch-project/OpenSearch/pull/12271
Note, BwC tests will fail until https://github.com/opensearch-project/OpenSearch/pull/12271 is merged
Resolves #[1707]
> Fix BwC for PluginInfo with semver range support

- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterRewriteIT.java
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/MinDocCountIT.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
#12073 handle the segment level match all scenario and build fast filters at segment level. However the built filter from a segment is saved in the FastFilterContext lived through the shard search and stop the subsequent segments from computing their filters. This change reset the filters built at segment level and add integration tests to cover that.
The reason previous flaky test catches this is pretty interesting. It's flaky because it happens at this scenario:
first search hit one shard (s1_1), second search hit another shard (s1_2)
The segments on these 2 shards are different, and the indexRandom method from test framework introduces random dummy document deletions which will stop the fast filter optimization we added in. So imagine s1_1 has multiple segments without deletion and …
> Fix: reset the filter built at segment level for date histogram optimization

- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramIT.java
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterRewriteIT.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
> [Backport 2.x] 12073 and 12267

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
- server/src/main/java/org/opensearch/action/get/MultiGetRequest.java
- server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java
- server/src/test/java/org/opensearch/action/admin/indices/create/CreateIndexRequestTests.java
- server/src/test/java/org/opensearch/action/get/MultiGetRequestTests.java
- server/src/test/java/org/opensearch/action/search/MultiSearchRequestTests.java
fix #12144
Make debugging easier with toString() method in MultiSearchRequest class.
Resolves #12144
> Add toString() to MultiSearchRequest class.

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
- server/src/main/java/org/opensearch/index/query/QueryShardContext.java
- server/src/main/java/org/opensearch/index/query/support/NestedScope.java
- server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
> Introduce `index.query.max_nested_depth`. backport 2.x

- CHANGELOG.md
- libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentContraints.java
- libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
- libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
Add a system property to configure YamlParser codepoint limits (similarly how we do it for other XContent parsers but this is YAML parser specific at the moment).  
Closes https://github.com/opensearch-project/OpenSearch/issues/12276
> Add a system property to configure YamlParser codepoint limits

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.12.0.md
This change was not backported to 2.x in time to make the 2.12 release and therefore will be pending until the 2.13 release.
> Remove PR #11499 from 2.12 release notes

- CHANGELOG.md
- libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentContraints.java
- libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
- libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/12301 to `2.x`
> [Backport] [2.x] Add a system property to configure YamlParser codepoint limits (#12301)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/lucene/store/ByteArrayIndexInput.java
- server/src/test/java/org/opensearch/common/lucene/store/ByteArrayIndexInputTests.java
Fixes `ByteArrayIndexInput::validatePos` and adds UT
Resolves #10481 
> Fixes ByteArrayIndexInput::validatePos and adds UT

- gradle/ide.gradle
If you configure IntelliJ to use JDK 21 then all unit tests will fail to run in the IDE when attempting to set the security manager in the test bootstrap code. This change configures all tests to include the required VM argument to enable the security manager.
> Allow security manager in IntelliJ unit tests

- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterRewriteIT.java
The test is flaky because `time` or `dateTerm` can be same after mod operation `%20` because `longTerm` can be 0 or 20. So line 84, expected is wrong when the value is overriden by the same key.
Only the test has problem, not the date histogram.
Resolves #12303 
> test: fix flaky for testMinDocCountOnDateHistogram

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- test/framework/src/main/java/org/opensearch/test/MockLogAppender.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Fix error in RemoteSegmentStoreDirectory when debug logging is enabled
Also updated test code to print the exception source for traceability 
- Discovered in https://github.com/opensearch-project/OpenSearch/pull/11957
> Fix error in RemoteSegmentStoreDirectory when debug logging is enabled

- server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
- server/src/internalClusterTest/java/org/opensearch/cluster/shards/ClusterShardLimitIT.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Fixing following test cases:
1. InternalEngineTests.testUnreferencedFileCleanUpOnSegmentMergeFailureWithCleanUpEnabled: Right now [merge policy created](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java#L1393) for IndexWriter can create an Alcoholic Merge policy as well. This does not sometimes trigger segment merges. Also using ForceMerge policy to avoid regular merge (triggered due to) closing shard before force merge kicks in.
2. org.opensearch.index.engine.InternalEngineTests.testUnreferencedFileCleanUpOnSegmentMergeFailureWithCleanUpDisabled
3. InternalEngineTests.testUnreferencedFileCleanUpFailsOnSegmentMergeFailureWhenDirectoryClosed:  Right now [merge policy …
> Fix flaky test cases

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/SearchPhaseName.java
- server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
- server/src/main/java/org/opensearch/action/search/WrappingSearchAsyncActionPhase.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
- server/src/test/java/org/opensearch/action/search/CanMatchPreFilterSearchPhaseTests.java
- server/src/test/java/org/opensearch/action/search/MockSearchPhaseContext.java
Add support of special WrappingSearchAsyncActionPhase so the onPhaseStart() will always be followed by onPhaseEnd() within AbstractSearchAsyncAction
Reverts https://github.com/opensearch-project/OpenSearch/pull/12035 and fixes 
> Add support of special WrappingSearchAsyncActionPhase so the onPhaseStart() will always be followed by onPhaseEnd() within AbstractSearchAsyncAction

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- test/framework/src/main/java/org/opensearch/test/MockLogAppender.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Backport 006ba0e6068d18d5523f8975de7c4e1e5e797490 from #12328.
> [Backport 2.x] Fix error in RemoteSegmentStoreDirectory when debug logging is enabled (#12328)

- server/src/internalClusterTest/java/org/opensearch/indexing/IndexActionIT.java
- server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
- server/src/internalClusterTest/java/org/opensearch/ingest/IngestProcessorNotInstalledOnAllNodesIT.java
- server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
- server/src/internalClusterTest/java/org/opensearch/recovery/RecoveryWhileUnderLoadIT.java
- server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/recovery/SimpleRecoveryIT.java
- server/src/internalClusterTest/java/org/opensearch/recovery/TruncatedRecoveryIT.java
- test/framework/src/main/java/org/opensearch/test/ParameterizedStaticSettingsOpenSearchIntegTestCase.java
Identified some of the test modules that are critical to segment replication and enabling them to run with segrep enabled.
```
indexing
ingest
recovery
```
Resolves #11804
> [Segment Replication] Enable test suites to run with segrep

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/PlainHighlighter.java
Currently, the `highlight.max_analyzer_offset` query parameter is ignored when using the `plain` highlighter.
**Note:** At the moment, this includes only a failing test, no actual fix for the problem.
Resolves #10702.
> Fix the "highlight.max_analyzer_offset" request parameter with "plain" highlighter

- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Test failure #8771 shows cases where certain random seeds trigger this case. The bug is clear: the substring() call should happen after the startsWith() check in case the blob name is shorter than the prefix length being used as the start index of the substring call. I don't yet know if/how this manifests in real deployments.
This bug is deterministically reproducible with the following seed, which also verifies the fix:
```
./gradlew ':server:test' --tests "org.opensearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotDeleteAndDeleteIndex" -Dtests.seed=E816C7242330BF50
```
Resolves #8771 …
> Avoid string out of bounds error in snapshot delete

- .github/workflows/wrapper.yml
- CHANGELOG.md
Backport of  https://github.com/opensearch-project/OpenSearch/pull/12367 to `2.x`
> [Backport] [2.x] Bump gradle/wrapper-validation-action from 1 to 2 (#12367)

- server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java
Fixing org.opensearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnHungIOBeyondHealthyTimeout test: Increasing healthy time threshold. Ran the test 5000 times on local
https://github.com/opensearch-project/OpenSearch/issues/7557
> Fix FsHealthServiceTests flaky tests

- server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
This test has been very flaky. Muting it and pointing to the existing issue.
> Mute DeleteSnapshotIT.testDeleteMultipleShallowCopySnapshotsCase1

- .github/workflows/pull-request-checks.yml
Bump `peternied/check-pull-request-description-checklist` from v1 to v1.1
* Ignore items where the checkbox is part of the strike-through by @msfroh
> Bump `peternied/check-pull-request-description-checklist` from v1 to v1.1

- build.gradle
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
When this test fails, it takes [15 minutes to timeout][1]. There are many examples like this. While it generally succeeds after a retry or two, I think it is better to mute this test rather than observe regular failures that extend build times.
[1]: https://build.ci.opensearch.org/job/gradle-check/33937/testReport/
Relates #9191
> Mute RemoteIndexPrimaryRelocationIT

- release-notes/opensearch.release-notes-2.12.0.md
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/CompositeAggIT.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
Disable concurrent segment search for requests containing composite aggregation.
https://github.com/opensearch-project/OpenSearch/issues/12331
~- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
~- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~ …
> Disable concurrent search path for composite aggregations.

- libs/core/src/main/java/org/opensearch/Version.java
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/12393 to `main`
N/A
> [Forwardport] Update Apache Lucene version to 9.10.0 for OpenSearch 2.13.0

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/mapper/MapperService.java
- server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
When migrating from older versions of Elasticsearch/OpenSearch `index.mapper.dynamic` could be present, use the deprecation system to warn about this state and ignore this legacy setting so the index is usable.
- Resolves https://github.com/opensearch-project/OpenSearch/issues/3879
- Related https://github.com/opensearch-project/OpenSearch/issues/12350
> Warn about `index.mapper.dynamic` usage instead of erroring

- libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
The YAML constraints apply to whole document, not just a value of particular key (and it is also in codepoints), it is difficult to get the limit exact, so relaxing constraints a bit.
Closes https://github.com/opensearch-project/OpenSearch/issues/12395
> [BUG] org.opensearch.common.xcontent.XContentParserTests.testString is flaky

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
- server/src/main/java/org/opensearch/index/engine/ReplicaFileTracker.java
This change fixes flakiness with segrep test for scroll requests.  The flakiness was with an assertion that all segments snapshotted by the scroll were deleted from disk after the scroll was cleared.  The failures were caused because the snapshotted segments were still referenced by the latest on-disk commit point that is always preserved.
The test was doing a lot of crazy random merges/deletes etc that made it difficult to follow why those files were sneaking in as part of the latest commit.
To make this easier to reason about I've simplified the test flow to:
1. Index 1 doc
2. Create the scroll
3. Index a few more docs
4. Refresh to create segments
5. Copy out segments
6. force merge to 1 segment
7. Copy out post force merge
8. Assert segments still exist on-disk
9. Clear scroll & …
> Fix flaky SegRep test testScrollCreatedOnReplica

- rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_field_mapping/20_missing_field.yml
This test was muted due to an [intermediate state][1] during type removal. It now passes per my local testing.
[1]: https://github.com/opensearch-project/OpenSearch/issues/2440#issuecomment-1067943238
Resolves #2440
> Unmute get field mapping test

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.12.0.md
This PR was committed on main but not backported to 2.x in time for the 2.12 release.
> Remove PR11626 from 2.12 release notes

- CHANGELOG.md
- modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionFieldScriptTests.java
- modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionNumberSortScriptTests.java
- modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionTermsSetQueryTests.java
- server/src/main/java/org/opensearch/index/query/QueryShardContext.java
- server/src/main/java/org/opensearch/search/lookup/SearchLookup.java
- server/src/test/java/org/opensearch/index/fielddata/IndexFieldDataServiceTests.java
- server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
- server/src/test/java/org/opensearch/search/aggregations/support/ScriptValuesTests.java
- server/src/test/java/org/opensearch/search/lookup/SearchLookupTests.java
- test/framework/src/main/java/org/opensearch/index/mapper/MapperServiceTestCase.java
- test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
Signed-off-by: Oleksandr Koval <kovalidis@gmail.com>
Add `shardId` field for `SearchLookup`.
#1062 
> Shard id awareness of SearchLookup

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.12.0.md
- rest-api-spec/src/main/resources/rest-api-spec/api/search.json
- rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries.yml
- server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexPrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/MatchedQueriesIT.java
- server/src/internalClusterTest/java/org/opensearch/search/functionscore/QueryRescorerIT.java
- server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
- server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java
- server/src/main/java/org/opensearch/search/DefaultSearchContext.java
- server/src/main/java/org/opensearch/search/SearchHit.java
- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
- server/src/main/java/org/opensearch/search/fetch/FetchContext.java
- server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
- server/src/main/java/org/opensearch/search/fetch/subphase/MatchedQueriesPhase.java
- server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
- server/src/main/java/org/opensearch/search/internal/SearchContext.java
- server/src/main/java/org/opensearch/search/internal/SubSearchContext.java
- server/src/test/java/org/opensearch/search/SearchHitTests.java
- test/framework/src/main/java/org/opensearch/test/TestSearchContext.java
- test/framework/src/main/java/org/opensearch/test/hamcrest/OpenSearchAssertions.java
- test/framework/src/main/java/org/opensearch/test/hamcrest/OpenSearchMatchers.java
Opensearch already support labelling the queries, that returns as a list in the returned results, of which query it matched. However one of the use case while doing hybrid search with query text and dense vector is to determine individual scores for each query type. This is very useful in further analysis and building offline model to generate better weights for ranking score. Hence adding this feature that sends the client to add the score for each matched query.
---------
(cherry picked from commit 52b27f47bca5b3ab52cab237542f32c307d203b4) …
> [Backport 2.x] Add support for scored named queries (#11626)

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/admin/cluster/node/tasks/get/TransportGetTaskAction.java
- server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java
- server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TaskManagerTestCase.java
Backport #11531  to 2.x.
https://github.com/opensearch-project/OpenSearch/issues/8655
> [Backport 2.x] Fix get task API does not refresh resource stats (#11531)

- CHANGELOG.md
- modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionFieldScriptTests.java
- modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionNumberSortScriptTests.java
- modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionTermsSetQueryTests.java
- server/src/main/java/org/opensearch/index/query/QueryShardContext.java
- server/src/main/java/org/opensearch/search/lookup/SearchLookup.java
- server/src/test/java/org/opensearch/index/fielddata/IndexFieldDataServiceTests.java
- server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
- server/src/test/java/org/opensearch/search/aggregations/support/ScriptValuesTests.java
- server/src/test/java/org/opensearch/search/lookup/SearchLookupTests.java
- test/framework/src/main/java/org/opensearch/index/mapper/MapperServiceTestCase.java
- test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
Backports 87ac37460c16a5b3cfa1cd85cad2cb7468b430a3 from main from #1063
> [Backport 2.x] Shard id awareness of SearchLookup (#1063)

- server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
- server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
Backport c42ada8e6d63295684303d46492216f3a6f94049 from main to `2.x`
This backport was missed from #9470
> [Backport 2.x] Handle null partSize in OnDemandBlockSnapshotIndexInput (#9470)

- release-notes/opensearch.release-notes-1.3.15.md
> Add release notes for 1.3.15

- server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
Increase suite timeout as parameterization has doubled the number of tests being run.
From the cases where the test does time out the non-concurrent search case is taking ~14 minutes, so bumping the timeout up to 35 to be safe. 
Ref: https://github.com/opensearch-project/OpenSearch/issues/12119#issuecomment-1973937864
Resolves #12119
~- [x] New functionality includes testing.~
~- [x] New functionality has been documented.~
~- [x] New functionality has javadoc added~
~- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))!~
~- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ …
> Increase suite timeout for HighlighterSearchIT

- .github/CODEOWNERS
- MAINTAINERS.md
Moving maintainer kartg to Emeritus, and removing from `CODEOWNERS`
N/A
> Moving maintainer kartg to Emeritus

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
- server/src/main/java/org/opensearch/node/IoUsageStats.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/node/NodeResourceUsageStats.java
- server/src/main/java/org/opensearch/node/NodesResourceUsageStats.java
- server/src/main/java/org/opensearch/node/ResourceUsageCollectorService.java
- server/src/main/java/org/opensearch/node/resource/tracker/AbstractAverageUsageTracker.java
- server/src/main/java/org/opensearch/node/resource/tracker/AverageIoUsageTracker.java
- server/src/main/java/org/opensearch/node/resource/tracker/NodeResourceUsageTracker.java
- server/src/main/java/org/opensearch/node/resource/tracker/ResourceTrackerSettings.java
- server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
- server/src/test/java/org/opensearch/node/IoUsageStatsTests.java
- server/src/test/java/org/opensearch/node/ResourceUsageCollectorServiceTests.java
- server/src/test/java/org/opensearch/node/resource/tracker/AverageUsageTrackerTests.java
- server/src/test/java/org/opensearch/node/resource/tracker/NodeResourceUsageTrackerTests.java
- This change is to track IO Usage Stats and emit these stats as part of `resource_usage_stats`.
- Created AverageIoUsageTracker which uses IO stats from the fsService and evaluate the IO Usage Consumption. 
- Currently we are emitting only IO UsagePercent as part of io_usage_stats and eventually we will add more parameters. 
```
resource_usage_stats: {
Edk086LhT_mu47MpzHgc4g: {
timestamp: 1709545252312,
cpu_utilization_percent: "0.0",
memory_utilization_percent: "1.0",
io_usage_stats: {
max_io_utilization_percent: "99.6"
}
}
}
```
```
resource_usage_stats: {
qi1V9avrSwC_OyRtA2khbA: {
timestamp: 1709544705354,
cpu_utilization_percent: "0.1",
memory_utilization_percent: "35.5"
}
}
```
- Parent PR where we are exposing other resource_usage_stats - #9890
- #8910 
- #9504 …
> Integrate IO Usage Tracker to the Resource Usage Collector Service and Emit IO Usage Stats

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
- server/src/main/java/org/opensearch/cluster/metadata/WeightedRoutingMetadata.java
- server/src/main/java/org/opensearch/cluster/routing/WeightedRouting.java
- server/src/test/java/org/opensearch/cluster/metadata/WeightedRoutingMetadataTests.java
---------
[2.x Backport] Fix for deserialization bug in weighted round robin metadata
https://github.com/opensearch-project/OpenSearch/pull/11679
> [Backport 2.x] Fix for deserilization bug in weighted round robin metadata (#11679)

- server/src/main/java/org/opensearch/node/NodeResourceUsageStats.java
Fixing IoUsage Stats Version Check After Backport
> Fixing IoUsage Stats Version Check After Backport

- .github/ISSUE_TEMPLATE/feature_request.yml
Update feature_request.yml to support Shard Management 
None
> Update feature_request.yml to support Shard Management

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
- server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
(cherry picked from commit 8a22f284a19e986d7e2732762554e6e2fedbd25c)
> [Backport 2.x] Fix issue with float field terms query (#12499)

- server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
- server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
In this PR, we are adding a defensive check which is used for determining the time lag. The time lag can show erroneous value if there is a refresh without any additional data ingested as segments.
No issue created. …
> [Remote Store] Add check for byte lag in time lag calculation

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Signed-off-by: kkewwei <kkewwei@163.com>
`onShardResult` and `onShardFailure` are executed on one shard, which will cause opensearch jvm crashed:（similar to #4143）
```
[2024-01-05T17:06:29,624+0800][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [node0] fatal error in thread [Thread-17309], exiting
java.lang.AssertionError: unexpected higher total ops [21] compared to expected [20]
at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:480) ~[opensearch-2.9.0.jar:2.9.0]
at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:295) ~[opensearch-2.9.0.jar:2.9.0]
```
Resolves #11881 
We can reuse this unit test: `AbstractSearchAsyncActionTests.testExecutePhaseOnShardFailure()` …
> onShardResult and onShardFailure are executed on one shard causes opensearch jvm crashed

- CHANGELOG.md
- server/src/main/java/org/opensearch/bootstrap/Security.java
- server/src/test/java/org/opensearch/bootstrap/SecurityTests.java
- server/src/test/resources/org/opensearch/bootstrap/test-codebases.policy
- server/src/test/resources/org/opensearch/bootstrap/test.policy
The issue came out while integration OpenSearch test scaffolding with `security` plugin. The `org.opensearch.bootstrap.Security` analyzes the classpath and injects the `codebase.*` system property for each JAR entry found (so it could be referenced in security policy files), for example:
```
...
grant codeBase "${codebase.zstd-jni}" {
permission java.lang.RuntimePermission "loadLibrary.*";
};
grant codeBase "${codebase.jna}" {
// for registering native methods
permission java.lang.RuntimePermission "accessDeclaredMembers";
};
...
```
The `codebase.*` suffix is constructed from the JAR file name by stripping the version (and `.jar` extension). However, it causes the issues when there same artifacts with classifiers referenced, for example:
- …
> The org.opensearch.bootstrap.Security should support codebase for JAR files with classifiers

- server/src/main/java/org/opensearch/plugins/PluginInfo.java
- server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
Updated opensearch_version field in PluginInfo json to represent a string of single version as opposed to a list of single version to ensure bwc.
Without this fix
```
/_cluster/stats
"plugins" : [
{
"name" : "analysis-icu",
"version" : "3.0.0-SNAPSHOT",
"opensearch_version" : [
"3.0.0"
],
"java_version" : "11",
"description" : "The ICU Analysis plugin integrates the Lucene ICU module into OpenSearch, adding ICU-related analysis components.",
"classname" : "org.opensearch.plugin.analysis.icu.AnalysisICUPlugin",
"custom_foldername" : "",
"extended_plugins" : [ ],
"has_native_controller" : false
}
],
```
With fix:
```
"plugins" : [
{
"name" : "analysis-icu",
"version" : "3.0.0-SNAPSHOT",
"opensearch_version" : "3.0.0",
"java_version" : "11",
"description" : "The ICU Analysis plugin …
```
> Fix PluginInfo bwc for opensearch_version field

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java
- server/src/main/java/org/opensearch/action/search/PutSearchPipelineTransportAction.java
- server/src/test/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequestTests.java
This commit introduces a breaking change:
NodesInfoRequest does not request all metrics by default.
There are metrics there are not included in the default set of metrics. Right now "search_pipelines" metric is not included in the default set of metrics.
Related issue: #10296
Originally, this change was part of above mentioned PR but during the review it was decided that it needs to be broken into several commits. …
> Do not request "search_pipelines" metrics by default in NodesInfoRequest

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
> [Backport 2.x] onShardResult and onShardFailure are executed on one shard causes opensearch jvm crashed

- CHANGELOG.md
- server/src/main/java/org/opensearch/bootstrap/Security.java
- server/src/test/java/org/opensearch/bootstrap/SecurityTests.java
- server/src/test/resources/org/opensearch/bootstrap/test-codebases.policy
- server/src/test/resources/org/opensearch/bootstrap/test.policy
Backport of https://github.com/opensearch-project/OpenSearch/pull/12586 to `2.x`
> [Backport] [2.x] The org.opensearch.bootstrap.Security should support codebase for JAR files with classifiers (#12586)

- server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
This PR mutes flaky test `testMultiGetWithNetworkDisruption_FailOpenEnabled` until fixed.
https://github.com/opensearch-project/OpenSearch/issues/10755
> Mute flaky test testMultiGetWithNetworkDisruption_FailOpenEnabled

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
- server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/terms/KeywordTermsAggregatorTests.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
- server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Utilize Collector#setWeight to smartly short-circuit certain aggregation paths. Basically cases when weight#count does not returns `-1`: 
- when `weight#count > 0` & `weight#count == maxdocs` in segments -> can leverage reading from termsEnum
Cases accounted for (for which the optimization will not work):
1. Field data not indexed.
2. Doc count explicitly provided in documents.
Resolves #10954 
> Improve string terms aggregation performance using Collector#setWeight

- server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
This line can be safely removed because the two lines following this assert test exactly the same condition.
n/a
- ~[ ] All tests pass~ …
> Remove duplicated assert in test

- CHANGELOG.md
- libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanContext.java
- libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanCreationContext.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/CanMatchPreFilterSearchPhase.java
- server/src/main/java/org/opensearch/action/search/SearchDfsQueryThenFetchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/SearchQueryThenFetchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
- server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
- server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
- server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
- server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
- server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
- server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
- server/src/main/java/org/opensearch/telemetry/tracing/listener/TraceableSearchRequestOperationsListener.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
- server/src/test/java/org/opensearch/action/search/CanMatchPreFilterSearchPhaseTests.java
- server/src/test/java/org/opensearch/action/search/SearchAsyncActionTests.java
- server/src/test/java/org/opensearch/action/search/SearchQueryThenFetchAsyncActionTests.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactoryTests.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerAssertingListener.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerTests.java
- server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- server/src/test/java/org/opensearch/telemetry/tracing/SpanBuilderTests.java
Tracing instrumentation at deep search path
Added spans at: 
1. Coordinator node request
2. Coordinator node search phases
```
% curl -X PUT "localhost:9200/test2?pretty" -H 'Content-Type: application/json' -d'                                                                    
{                                                  
"settings": {
"number_of_shards": 10
}
}'
% curl -X POST "localhost:9200/_bulk?pretty" -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "test2", "_id" : "1" } }
{ "field1" : "value1" }
{ "index" : { "_index" : "test2", "_id" : "2" } }
{ "field2" : "value2" }
'
% curl -XGET 'localhost:9200/_search?pretty&phase_took' -H 'X-Opaque-Id: my-id' -H 'Content-Type: application/json' -d'{
"query": { "match_all": {} }
}'
% curl -XGET …
```
> Tracing for deep search path

- server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
Fix flaky test org.opensearch.search.aggregations.bucket.terms.TermsAggregatorTests.testSimpleAggregationLowCardinality
Setting up no-merge policy explicitly during index-creation to avoid index merge after deletion of documents and to keep the segment stable for consistent search results.
Resolves https://github.com/opensearch-project/OpenSearch/issues/12640
> Add no merge policy in test to avoid index merge

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
- server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/terms/KeywordTermsAggregatorTests.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
- server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
**TLDR:** The PR is a combination of 2 PRs merged in `main`: https://github.com/opensearch-project/OpenSearch/pull/11643 & https://github.com/opensearch-project/OpenSearch/pull/12643
Test automatically merges the index after delete sometimes leading to flaky test. Avoiding that from happening to stabilize test.
Follow-up on https://github.com/opensearch-project/OpenSearch/pull/12628 
Backport https://github.com/opensearch-project/OpenSearch/commit/7dac98c81ae387e5d4782a9599505a4c376a3e74 from https://github.com/opensearch-project/OpenSearch/pull/11643. …
> [Backport 2.x] Improve string terms aggregation performance using Collector#setWeight

- CHANGELOG.md
- libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanContext.java
- libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanCreationContext.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/CanMatchPreFilterSearchPhase.java
- server/src/main/java/org/opensearch/action/search/SearchDfsQueryThenFetchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/SearchQueryThenFetchAsyncAction.java
- server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
- server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
- server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
- server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
- server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
- server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
- server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
- server/src/main/java/org/opensearch/telemetry/tracing/listener/TraceableSearchRequestOperationsListener.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
- server/src/test/java/org/opensearch/action/search/CanMatchPreFilterSearchPhaseTests.java
- server/src/test/java/org/opensearch/action/search/SearchAsyncActionTests.java
- server/src/test/java/org/opensearch/action/search/SearchQueryThenFetchAsyncActionTests.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactoryTests.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerAssertingListener.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerTests.java
- server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- server/src/test/java/org/opensearch/telemetry/tracing/SpanBuilderTests.java
* Tracing for deep search path
Signed-off-by: David Zane <davizane@amazon.com>
* Refactor search phase tracing instrumentation to detach span creation from the SearchRequestOperationsListener
* Close WrappedPhase span
Signed-off-by: David Zane <davizane@amazon.com>
* Add asserting listener class
Signed-off-by: David Zane <davizane@amazon.com>
* Cleanup AbstractSearchAsyncActionTests tests
* Cleanup SearchAsyncActionTests tests
* Cleanup CanMatchPreFilterSearchPhaseTests tests
---------
Signed-off-by: David Zane <davizane@amazon.com> …
> [Backport 2.x] Tracing for deep search path (#12103)

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/SearchQueryCounters.java
- server/src/test/java/org/opensearch/action/search/SearchQueryCategorizerTests.java
The change aims to make the search query counters dynamic to support all query types. 
Initially, we only incremented counters for a select few query types as part of [search query categorization](https://github.com/opensearch-project/OpenSearch/issues/11596). Based on requests in the [following issue](https://github.com/opensearch-project/OpenSearch/issues/5983), we want to cover ALL query types including the query types that might be included as part of plugin code.
To implement this, we create a map that stores the query builder name to Query type Counter. When we encounter a new query type we add the query to the map and create a new associated counter. We then use this counter to increment for all requests coming in for the aforementioned query type. This implementation ensures that …
> Make search query counters dynamic to support all query types

- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Fixing flaky tiered cache test. The issue was basically a typo where we were incorrectly passing weigher(keyValueSize) to underlying onHeap cache.
- Also fixed other issue where we only call removal listener when a item is removed from disk cache as well.
Resolves https://github.com/opensearch-project/OpenSearch/issues/12593
- ~[x] New functionality has been documented.~
- ~[x] New functionality has javadoc added~ …
> [Tiered Caching] Fixing flaky tiered cache test

- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Backports https://github.com/opensearch-project/OpenSearch/pull/12650
- ~[ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog]~(../blob/main/CONTRIBUTING.md#changelog))
> [Backport 2.x] [Tiered Caching] Fixing flaky tiered cache test (#12650)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/time/EpochTime.java
- server/src/test/java/org/opensearch/common/time/DateFormattersTests.java
Fixes https://github.com/opensearch-project/OpenSearch/issues/10253
When sorting a datetime field with `epoch_millis` formatting and putting missing values last (with a descending sort) or first (with ascending sort), the datetime value is `Long.MIN_VALUE`. 
When we try to render that, the formatter tries to emit the negative sign, followed by the absolute value of the original value. Since `Long.MIN_VALUE = -Long.MAX_VALUE - 1`, it is not possible to represent `-Long.MIN_VALUE` as a `long`.
To work around this, my proposed fix introduces an off-by-one error by truncating to `Long.MAX_VALUE`.
Resolves #10253 …
> Avoid overflow when sorting missing last on epoch_millis datetime field

- server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
- server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
- Translog upload success callback can throw unexpected exceptions. 
- Since we are using ActionListener.wrap, we catch all exceptions in onSuccess and call the onFailure callback
- Currently, on failure callback only accepts FileTransferException. 
- if the exception is any other, we throw a ClassCastException and swallow the original exception trace.
- To be able to log the exceptions occurring in onSuccess callbacks, we wrap those exception as FileTransferException 
https://github.com/opensearch-project/OpenSearch/issues/12544
- ~~[ ] New functionality includes testing.~~
- ~~[ ] All tests pass~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] New functionality has javadoc added~~
- ~~[ ] Public documentation issue/PR …
> handle unexpected exception on success callback of translog upload

- CHANGELOG.md
- libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistry.java
- libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/MetricsRegistry.java
- libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/noop/NoopMetricsRegistry.java
- libs/telemetry/src/test/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistryTests.java
- plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/TelemetryMetricsEnabledSanityIT.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetry.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetryTests.java
- test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
> [Backport] [2.x] - Adds support for asynchronous gauge metric type (#12642)

- plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
Supports removal on ehcache disk cache key iterator.
Resolves https://github.com/opensearch-project/OpenSearch/issues/12652
> [Tiered caching] Supporting removal function on EhcacheDiskCache iterator

- CHANGELOG.md
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
This PR introduces following changes
- Introduces IndicesRequestCacheCleanupManager, as a way of refactoring existing cleanup logic into a well structured class. This class also provides cleanup based on a staleness threshold setting.
- Provides IndicesRequestCache its own cleaner in the form of IndicesRequestCacheCleaner
https://github.com/opensearch-project/OpenSearch/issues/12540
> [Tiered Caching] Indices Request cache stalekey management

- CHANGELOG.md
- modules/cache-common/src/main/java/org/opensearch/cache/common/policy/TookTimePolicy.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/policy/package-info.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/policy/TookTimePolicyTests.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
- server/src/main/java/org/opensearch/common/cache/policy/CachedQueryResult.java
- server/src/main/java/org/opensearch/common/cache/policy/package-info.java
- server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
Signed-off-by: Peter Alfonsi <petealft@amazon.com>
Co-authored-by: Peter Alfonsi <petealft@amazon.com>
(cherry picked from commit ccdf3ffb4c5cdce25db0b8c4b90f6a87dc0add95)
**Original PR: https://github.com/opensearch-project/OpenSearch/pull/12542**
This PR adds caching tier policies. In a tiered caching setup, or even for a single-tier cache, we might not want to allow all values into all tiers, so we want to define policies to allow or reject values. For example, we might not want to add values that took a very short time to compute to a disk tier, since the time to recompute them could be shorter than the time to get them back from the disk. 
This PR adds an interface for policies and integrates them to restrict access to the disk tier in the TieredSpilloverCache. Currently the only …
> [Backport 2.x] [Tiered Caching] Cache tier policies (#12542)

- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
- server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
For remote store, segment and translog repo need to be configured. For remote state, cluster state repo is required. But as per current logic either all three repos should be present or none of them should be preesnt. So remote state is tightly coupled with remote store.
This PR decouples the remote state setting so that it can be enabled or disabled as an independent feature.
#9884 
> Decouple remote state configuration

- CHANGELOG.md
- qa/rolling-upgrade/build.gradle
- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
https://github.com/opensearch-project/OpenSearch/issues/12126
https://github.com/opensearch-project/OpenSearch/issues/12126
> Remove fuzzy set from experimental

- server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
This fixes a race condition in the test that leaves th eprimary with an open file ref while shutting down. This happens because we are acquiring file refs inside the resolveCheckpointInfoResponseListener method right after calling beforeIndexShardClosed. BeforeIndexShardClosed will resolve replication listeners immediately and leave a possibility of the test continuing & the primary attempting shut down before those refs are closed. We can resolve this using latches, but this test really doesn't need to simulate a primary response only that the replica is shutting down at this stage.
Also removed an unused variable.
Resolves #12291  …
> Fix flaky test SegmentReplicationWithNodeToNodeIndexShardTests#testReplicaClosesWhileReplicating_AfterGetCheckpoint

- buildSrc/version.properties
- server/src/test/java/org/opensearch/transport/RemoteClusterClientTests.java
Bump mockito & bytebuddy dependencies (skipping changelog since those are test dependencies)
N/A
> Bump mockito & bytebuddy dependencies

- CHANGELOG.md
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
- plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
- server/src/main/java/org/opensearch/common/cache/serializer/BytesReferenceSerializer.java
- server/src/main/java/org/opensearch/common/cache/serializer/Serializer.java
- server/src/main/java/org/opensearch/common/cache/serializer/package-info.java
- server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
- server/src/main/java/org/opensearch/indices/IRCKeyWriteableSerializer.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/common/cache/serializer/BytesReferenceSerializerTests.java
- server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
**Original PR: https://github.com/opensearch-project/OpenSearch/pull/12709**
Signed-off-by: Peter Alfonsi <petealft@amazon.com>
Co-authored-by: Peter Alfonsi <petealft@amazon.com>
(cherry picked from commit 21b28f2a019a8ee538a763453366e6fd4943b768)
As part of tiered caching, adds a Serializer interface and implementations for BytesReference and IndicesRequestCache.Key. Also integrates these with EhcacheDiskCache. This is required for Ehcache to accept non-primitive keys or values. 
Part of the [tiered caching feature. ](https://github.com/opensearch-project/OpenSearch/issues/10024)
~- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ …
> [Backport 2.x] [Tiered Caching] Serializers for ehcache (#12709)

- CHANGELOG.md
- qa/rolling-upgrade/build.gradle
- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
https://github.com/opensearch-project/OpenSearch/issues/12126
https://github.com/opensearch-project/OpenSearch/issues/12126
> [Backport 2.x] Remove fuzzy set from experimental 

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
- server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
- test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
> Election scheduler should be cancelled after cluster state publication

- libs/core/src/main/java/org/opensearch/core/common/bytes/BytesReference.java
- plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
- server/src/main/java/org/opensearch/common/cache/serializer/BytesReferenceSerializer.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
Backport https://github.com/opensearch-project/OpenSearch/pull/12734
> [Backport 2.x][Tiered Caching] Clear up disk cache(ehcache) files during node shutdown

- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhcacheThreadLeakFilter.java
Fixing flaky test within EhcacheDiskCacheTests
https://github.com/opensearch-project/OpenSearch/issues/12758
> Fixing ehcache flaky test

- server/src/test/java/org/opensearch/search/geo/GeoPointShapeQueryTests.java
It fixes the GeoPointShapeQueryTests.testQueryLinearRing which has been failing across multiple PR during gradle-check
Resolves [11688](https://github.com/opensearch-project/OpenSearch/issues/11688)
> Fixing flaky test GeoPointShapeQueryTests.testQueryLinearRing

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
This PR exposes the setting `index.check_pending_flush.enabled` setting to control lucene index writer [checkPendingFlushOnUpdate](https://lucene.apache.org/core/7_6_0/core/org/apache/lucene/index/LiveIndexWriterConfig.html#checkPendingFlushOnUpdate)
Resolves #11628
> Added static setting for checkPendingFlushUpdate functionality of lucene index writer

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
This PR backports changes done in PR #12710
> [backport 2.x] Added static setting for checkPendingFlushUpdate functionality of lucene index writer

- server/src/test/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeRequestTests.java
As discussed in https://github.com/opensearch-project/OpenSearch/pull/12657, we should correct the version field in `ForceMergeRequests.testBwcSerialization()`, use the same version in both streamInput and streamOutput. The issue was fixed in that PR, but it cannot be backported to the 2.x branch because the serialization is different in main and 2.x, so we need to fix the issue in 2.x manually. 
Changelog is not needed.
https://github.com/opensearch-project/OpenSearch/issues/8021
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develope …
> Fix test bwcSerialization issue in ForceMergeRequestTests

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/cluster/state/FetchByTermVersionIT.java
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionRequest.java
- server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionResponse.java
- server/src/main/java/org/opensearch/action/admin/cluster/state/term/TransportGetTermVersionAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/state/term/package-info.java
- server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
- server/src/main/java/org/opensearch/cluster/coordination/ClusterStateTermVersion.java
- server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionIT.java
- server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionTests.java
- server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
- server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerTermCheckTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Cluster State TermVersion Fetch
If the local node has up-to-date cluster-state it can serve Read requests. This issue introduces a transport action to get the term and version of cluster-state from cluster-manager. If the retrieved data matches with local term and version, the subsequent call to retrieve cluster-state is avoided and the local cluster-state is used. This offloads the responsibility of serving read requests of cluster-data to local node there-by reducing the load on cluster-manager.
Resolves #12272 …
> Light weight Transport action to verify local term before fetching cluster-state from remote

- rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/40_wait_for_completion.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/indices.open/30_wait_for_completion.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/50_wait_for_completion.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/40_wait_for_completion.yml
In the PR https://github.com/opensearch-project/OpenSearch/pull/6434, we've added `wait_for_completion` parameter for open&clone&shrink&split&forcemerge APIs, after the PR was merged and backported to 2.x branch, we need to update the supported version in the yaml test file to ensure that change can be covered by yaml test.
The supported version in the [yaml test file](https://github.com/opensearch-project/OpenSearch/blob/f3d2beee637f63e38c8f26dbcee9f2a82f9c87b6/rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/20_wait_for_completion.yml#L7) of forcemerge API has been changed by other PR, this PR only change the version for the remaining APIs.
The wait_for_completion parameter is not serialized/deserialized, so no java code change.
Backport  and changelog is not …
> Update supported version for the wait_for_completion parameter in open&clone&shrink&split APIs

- server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
Signed-off-by: kkewwei [kkewwei@163.com](mailto:kkewwei@163.com)
org.opensearch.search.query.SimpleQueryStringIT.testDocWithAllTypes is flaky.
Resolves #12574
> Fix Flaky SimpleQueryStringIT Tests

- server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
GetTermVersion Transport API is backported to 2.x.
Resolves #12272
> Update the version for local term fetch to 2.13

- buildSrc/version.properties
- libs/core/src/main/java/org/opensearch/Version.java
> Switch 2.x to 2.14.0

- server/src/main/java/org/opensearch/action/search/SearchRequest.java
- server/src/main/java/org/opensearch/action/search/SearchTask.java
- server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
- server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
- server/src/test/java/org/opensearch/search/geo/GeoPointShapeQueryTests.java
Alternative to (just the first two commits) to https://github.com/opensearch-project/OpenSearch/pull/12831.
A user that enables trace-level logging with OpenSearch will run into a serialization error on geo tasks that they otherwise would not run into. It comes from [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/geo/GeoJson.java#L129). This also happens in a test, and https://github.com/opensearch-project/OpenSearch/pull/12783 attempts to ignore the failed serialization error. This PR always returns a task description.
Reproduce with
```
./gradlew ':server:test' --tests "org.opensearch.search.geo.GeoPointShapeQueryTests.testQueryLinearRing" -Dtests.opensearch.logger.level=TRACE
``` 
Closes …
> Catch task description error

- CHANGELOG.md
The 2.13 release notes have been created.
> Clear out 2.x section of changelog

- server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java
The explain itself is coming from Lucene: https://github.com/apache/lucene/blob/a6f70ad2bb0b682eb65feb522358ee6d16cad766/lucene/join/src/java/org/apache/lucene/search/join/ToParentBlockJoinQuery.java#L432-L440
Here's some info on the docIds in lucene:
- A DocId in lucene is not actually unique to the Index but is unique to a Segment. Lucene does this mainly to optimize writing and compression. Since it is only unique to a Segment, how can a Doc be uniquely identified at the Index level? The solution is simple. The segments are ordered. To take a simple example, an Index has two segments and each segment has 100 docs respectively. The DocId's in the Segment are 0-100 but when they are converted to the Index level, the range of the DocId's in the second Segment is converted to 100-200.
- …
> Fix SimpleNestedExplainIT.testExplainMultipleDocs flakiness

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.13.0.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Backports PR #12786 to `2.13`
Resolves #11628
> [Backport 2.13] Added static setting for checkPendingFlushUpdate functionality of lucene index writer

- CHANGELOG.md
- buildSrc/src/main/java/org/opensearch/gradle/precommit/PomValidationPrecommitPlugin.java
Change the publication iteration to all to resolve incompatibility on security plugin. 
I tested locally and it built successfully. 
```
☁  ~/workplace/security[main] ./gradlew assemble
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 8.5
OS Info               : Mac OS X 14.3 (x86_64)
JDK Version           : 21 (Oracle JDK)
JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
Random Testing Seed   : C82B0FF391C689CE
In FIPS 140 mode      : false
=======================================
> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You …
```
> Replace configureEach with all for publication iteration

- .github/workflows/version.yml
Adds the README to the git workflow for version increment automation to update the tag on the top of the README that contains the number of open issues for the next unreleased minor version.
See companion PR in core that updates the currently outdated tag from 2.10.0 -> 2.14.0: https://github.com/opensearch-project/OpenSearch/pull/12895
Tested on my fork here: https://github.com/cwperks/OpenSearch/pull/148
- https://github.com/opensearch-project/OpenSearch/issues/8851
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate …
> [2.x] Add README to version increment automation

- buildSrc/src/testFixtures/java/org/opensearch/gradle/test/GradleThreadsFilter.java
- gradle/wrapper/gradle-wrapper.properties
Update to Gradle 8.7 (https://github.com/gradle/gradle/releases/tag/v8.7)
N/A
> Update to Gradle 8.7

- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
With this plugin enabled I see significant increase in memory usage during ITs. This is due to a [static map](https://github.com/opensearch-project/OpenSearch/blob/4e1022e2e85ce16c8772e76c1e1d857e89b6c08c/test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java#L30) that collects Span entries per write/replication request and is not [cleared](https://github.com/opensearch-project/OpenSearch/blob/b1f8b169c2f195012a08cfc6d79ef5e5a3c7f885/test/framework/src/main/java/org/opensearch/test/OpenSearchTestClusterRule.java#L99) until after the test execution. Tests with higher counts of independent writes are at risk of running oom or experiencing slow down / warnings related to this.
I've run two reported flaky tests on repeat with this disabled #12801 and …
> Disable MockTelemetryPlugin by default for integ tests

- CHANGELOG.md
The 2.13 release notes have been created.
> [Backport 2.13] Clear out 2.x section of changelog

- modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/71_context_api.yml
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
- server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
- server/src/main/java/org/opensearch/index/query/DerivedFieldScript.java
- server/src/main/java/org/opensearch/script/DerivedFieldScript.java
- server/src/main/java/org/opensearch/script/ScriptModule.java
- server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
- test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Derived Fields PR1: 
Contains building block logic for  DerivedFields - 
1. `DerivedFieldScript factory`: This script factory will be used to execute scripts defined against derived fields of any type. 
2. `DerivedFieldValueFetcher`: The value fetcher contains logic to execute script and fetch the value in form of `List<Object>`. It expects `DerivedFieldScript.LeafFactory` as an input and sets the contract with consumer to call `setNextReader()` whenever a segment is switched. 
3.  `DerivedFieldQuery`: This query will be used by any of the derived fields. It expects an input query and `DerivedFieldValueFetcher`. It uses 2-phase iterator approach with approximation iterator set to match all docs. On a match, it creates a lucene MemoryIndex for a given doc, fetches the value of the derived …
> [DerivedFields] PR1 - DerivedFieldScript and query execution logic

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
Fixes an issue where FeatureFlags is not honoring the default value of the feature flag setting when calling `isEnabled`. 
The bug exists because the settings object in the FeatureFlags class is not initialized until initializeFeatureFlags is called and will return false from this [line](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L93) instead of honoring the default value. While a feature guarded by a feature flag should not be enabled by default, this is a bug in the way the feature flags logic is implemented. 
- https://github.com/opensearch-project/OpenSearch/issues/9564
For more information …
> Fix issue with feature flags where default value may not be honored

- CHANGELOG.md
The 2.13 release notes have been created.
> [Backport 2.x] Clear out 2.x section of changelog

- server/src/main/java/org/opensearch/action/search/SearchRequest.java
- server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
- server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
- server/src/test/java/org/opensearch/search/geo/GeoPointShapeQueryTests.java
Backports #12834 to 2.x.
Closes https://github.com/opensearch-project/OpenSearch/issues/11688
Closes https://github.com/opensearch-project/OpenSearch/issues/12324
> [Backport 2.x] Catch task description error (#12834)

- CHANGELOG.md
- buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
- buildSrc/src/main/java/org/opensearch/gradle/precommit/PomValidationPrecommitPlugin.java
- buildSrc/src/main/java/org/opensearch/gradle/precommit/PomValidationTask.java
Backport to 2.x branch for https://github.com/opensearch-project/OpenSearch/pull/12807
https://github.com/opensearch-project/OpenSearch/pull/12876
> Backport to 2.x "Add explicit dependency to validatePom and generatePom tasks"

- server/src/main/java/org/opensearch/common/blobstore/BlobPath.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreDataEnums.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathType.java
https://github.com/opensearch-project/OpenSearch/pull/12872 adds missed API visibility annotations for public APIs and enable the check at the build time. Since https://github.com/opensearch-project/OpenSearch/pull/12822 had clean build and was raised before the 12872 PR, after merge the build has failed. In this PR, we add the missed annotations.
None …
> Add missed API visibility annotations for public APIs

- modules/ingest-common/src/test/java/org/opensearch/ingest/common/CopyProcessorTests.java
- test/framework/src/main/java/org/opensearch/ingest/RandomDocumentPicks.java
When testing CopyProcessorTests#testCopyWithRemoveSource(), even though we use random() to generate field names, but there's a probability that the target field's name conflicts with the existing fields(then the error `target field [] already exists` will be thrown), we need to have a better way to make sure that the target field's name never exists in the document.
Another method `testCopyExistingField()` also has the same issue.
https://github.com/opensearch-project/OpenSearch/issues/12884
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING. …
> Fix flaky tests in CopyProcessorTests

- CHANGELOG.md
- test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/12893 to `2.x`
> [Backport] [2.x] Bump net.minidev:json-smart from 2.5.0 to 2.5.1 in /test/fixtures/hdfs-fixture (#12893)

- server/src/test/java/org/opensearch/cluster/service/TaskBatcherTests.java
Signed-off-by: kkewwei [kkewwei@163.com]
org.opensearch.cluster.service.TaskBatcherTests.testNoTasksAreDroppedInParallelSubmission is flaky
Resolves #12815
> Fix Flaky TaskBatcherTests Tests

- server/src/test/java/org/opensearch/common/settings/SettingTests.java
Rebased version of https://github.com/opensearch-project/OpenSearch/pull/12706.
Closes https://github.com/opensearch-project/OpenSearch/issues/12705
> Rebased version of #12706

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/CompositeAggIT.java
- server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
- server/src/main/java/org/opensearch/search/aggregations/Aggregator.java
- server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java
- server/src/main/java/org/opensearch/search/aggregations/GlobalAggCollectorManager.java
- server/src/main/java/org/opensearch/search/aggregations/MultiBucketConsumerService.java
- server/src/main/java/org/opensearch/search/aggregations/NonGlobalAggCollectorManager.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
- server/src/main/java/org/opensearch/search/internal/SearchContext.java
- server/src/test/java/org/opensearch/search/aggregations/AggregationProcessorTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
In order to address Lucene AssertingCodec failures related to DocValue and SortedFields objects as well as improve aggregation performance, this PR moves the `buildAggregation` component into `postCollection` in order for it to be run concurrently on the `index_searcher` threadpool for concurrent segment search.
There is a separate issue with source scripting for composite aggregations, so we will re-enable concurrent segment search for composite aggregations however we will disable in case any scripts are present. See item 2: https://github.com/opensearch-project/OpenSearch/issues/12331#issuecomment-1974076871
In summary:
1. Move `buildAggregation` to `processPostCollection`. To help do this we save the `InternalAggregation` object as a class field in `Aggregator`.
2. In …
> Perform buildAggregation concurrently and partially support composite aggs

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/CompositeAggIT.java
- server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
- server/src/main/java/org/opensearch/search/aggregations/Aggregator.java
- server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java
- server/src/main/java/org/opensearch/search/aggregations/GlobalAggCollectorManager.java
- server/src/main/java/org/opensearch/search/aggregations/MultiBucketConsumerService.java
- server/src/main/java/org/opensearch/search/aggregations/NonGlobalAggCollectorManager.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
- server/src/main/java/org/opensearch/search/internal/SearchContext.java
- server/src/test/java/org/opensearch/search/aggregations/AggregationProcessorTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Backport 2.x for https://github.com/opensearch-project/OpenSearch/pull/12697
~- [] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~
> [Backport 2.x] Perform buildAggregation concurrently and partially support composite aggs

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/ConvertProcessor.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/ConvertProcessorTests.java
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/330_convert_processor.yml
Backport [#12818](https://github.com/opensearch-project/OpenSearch/pull/12818) to 2.x branch.
https://github.com/opensearch-project/OpenSearch/issues/12532
> [Backport 2.x] Convert ingest processor supports ip type (#12818)

- server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
- server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
Derived Field PR2 
Implementation for all supported types and `DerivedFieldType`. We support following types - 
```
boolean
date
geo_point
ip
keyword
long
double
```
These changes are to be used in subsequent PR3(https://github.com/opensearch-project/OpenSearch/pull/12569) where `DerivedFieldMapper` is defined and used.
Resolves https://github.com/opensearch-project/OpenSearch/issues/12508 …
> [DerivedFields] PR2 - Implementation for all supported types and DerivedFieldType

- server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/index/IndexService.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/main/java/org/opensearch/indices/DefaultRemoteStoreSettings.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/index/IndexModuleTests.java
- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
- server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
- server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
- server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
- Currently, remote store related settings are scattered across various classes and adding a new setting requires defining the setting in IndicesService and pass the supplier to downstream classes.
- But with one new setting, it gets difficult to pass one more parameter to the constructor of `IndexService`, `IndexShard` etc.
- In this PR, we have abstracted out remote store related settings to a new settings class: `RemoteStoreSettings`
> [Remote Store] Add RemoteStoreSettings class to handle remote store related settings

- CHANGELOG.md
- modules/transport-netty4/src/main/java/org/opensearch/http/netty4/ssl/SecureNetty4HttpServerTransport.java
- modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4Plugin.java
- modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureNetty4Transport.java
- modules/transport-netty4/src/test/java/org/opensearch/http/netty4/ssl/SecureNetty4HttpServerTransportConfigurationTests.java
- modules/transport-netty4/src/test/java/org/opensearch/http/netty4/ssl/SecureNetty4HttpServerTransportTests.java
- modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/ssl/SimpleSecureNetty4TransportTests.java
- server/src/main/java/org/opensearch/common/network/NetworkModule.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
- server/src/main/java/org/opensearch/plugins/SecureHttpTransportSettingsProvider.java
- server/src/main/java/org/opensearch/plugins/SecureSettingsFactory.java
- server/src/main/java/org/opensearch/plugins/SecureTransportSettingsProvider.java
- server/src/main/java/org/opensearch/plugins/TransportExceptionHandler.java
- server/src/main/java/org/opensearch/transport/TransportAdapterProvider.java
- server/src/test/java/org/opensearch/common/network/NetworkModuleTests.java
Backport of `https://github.com/opensearch-project/OpenSearch/pull/12907` to `2.x`
> [Backport 2.x] [FEATURE] Broaden SecureSettingsFactory to include http transports (#12907)

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/DefaultSearchContext.java
- server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
From the problem described in https://github.com/opensearch-project/OpenSearch/issues/12951, we need to maintain the threadpool isolation for `system_read` and `search_throttled` search requests. The threadpool used is decided here: https://github.com/opensearch-project/OpenSearch/blob/52b27f47bca5b3ab52cab237542f32c307d203b4/server/src/main/java/org/opensearch/search/SearchService.java#L717-L728
This PR disables concurrent segment search when either system indices or throttled indices are present using the same logic as above.
Resolves #12951
~- [] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~
For more …
> Disable concurrent segment search for system indices and throttled search requests

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
- server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
- server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/SearchOperationListener.java
- server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
- server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
- server/src/test/java/org/opensearch/index/shard/SearchOperationListenerTests.java
- server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
2.x Backport PR for search idle tracking
[Add a counter to node stat api to track shard going from idle to non-idle](https://github.com/opensearch-project/OpenSearch/pull/12768/commits/3a13164906b96d196dfdae22d0552381007ba51f)
> [Backport 2.x] Adding concurrent search versions of query count and time metrics (#9622) 

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/DefaultSearchContext.java
- server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
Backport 2.x for https://github.com/opensearch-project/OpenSearch/pull/12954
> [Backport 2.x] Disable concurrent segment search for system indices and throttled search requests

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
- server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
Fix the version check for search idle metric . This PR is to be merged alongside [[Backport 2.x] Adding concurrent search versions of query count and time metrics (#9622)](https://github.com/opensearch-project/OpenSearch/pull/12969)
> Update version checks for shard search idle metric after backport to 2.x

- .github/workflows/detect-breaking-change.yml
- CHANGELOG.md
- server/build.gradle
Adds a gradle task and github action to check for breaking changes made to the APIs in server by running comparison against most resent snapshot build on sonotype maven repository.
_Only classes with `@PublicApi` are checked for breaking changes._
Uses japicmp to perform the comparison against the jar files, learn more https://siom79.github.io/japicmp/
Workflow failure where a plugin method was removed [[link](https://github.com/peternied/OpenSearch-1/actions/runs/8481604427/job/23239257295)]
```
* What went wrong:
Execution failed for task ':server:japicmp'.
> A failure occurred while executing me.champeau.gradle.japicmp.JApiCmpWorkAction
> Detected binary changes.
- current: opensearch-3.0.0-SNAPSHOT.jar
- baseline: opensearch-3.0.0-SNAPSHOT.jar.
See failure report at …
```
> Detect breaking changes on pull requests v2.0

- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactory.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/store/Store.java
- server/src/main/java/org/opensearch/index/translog/Translog.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
- server/src/test/java/org/opensearch/index/IndexSettingsTests.java
- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Memoize isOnRemoteNode in index settings and refactor as well
> Memoize isOnRemoteNode in index settings and refactor as well

- .github/workflows/gradle-check.yml
Reverts opensearch-project/OpenSearch#12938
Looks broken in new ways, https://github.com/opensearch-project/OpenSearch/issues/13025.
> Revert "Add more identifiers to gradle-check job webhook payload"

- .github/workflows/detect-breaking-change.yml
Fix triggers and disable Gradle build cache (it seems to be problematic)
Closes https://github.com/opensearch-project/OpenSearch/issues/13029
> Fix detect-breaking-change Github action configuration

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/test/java/org/opensearch/index/IndexModuleTests.java
- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
- server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
- In this PR, we make translog transfer timeout configurable using a dynamic cluster setting.
- In certain cases, when configured remote store is slow, translog uploads can take more than the current hardcoded value of 30s. This could result in uploading the same file twice.
- To prevent the re-upload of translog files, we need to change the translog transfer timeout value to request timeout to the remote store.
- As we can configure different types of remote stores, instead of setting up a default value, we made it configurable. …
> [Remote Store] Make translog transfer timeout configurable using dynamic setting

- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
Forward port of the version change in https://github.com/opensearch-project/OpenSearch/pull/13055
N/A
> [Forwardport] [main] Fix bulk API ignores ingest pipeline for upsert (update version)

- modules/lang-painless/src/main/java/org/opensearch/painless/PainlessModulePlugin.java
- modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.derived.txt
- modules/lang-painless/src/test/java/org/opensearch/painless/DerivedFieldScriptTests.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
- server/src/main/java/org/opensearch/script/DerivedFieldScript.java
- server/src/main/java/org/opensearch/script/ScriptEmitValues.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
- server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
- test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Adds support for emitting multiple values when using the script context for derived field scripts.
Required to resolve #12508 
> [Derived Fields] Add support for emitting multiple values in DerivedFieldScripts

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
- server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
- server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
- server/src/main/java/org/opensearch/indices/IndicesModule.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperTests.java
- server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
- test/framework/src/main/java/org/opensearch/index/mapper/MapperServiceTestCase.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Adds a DerivedFieldMapper to support the Derived Fields feature enhancement as well as updating the mapper parsing logic to recognize and currently parse derived fields in the mappings.
---------
Signed-off-by: Mohammad Qureshi <qreshi@amazon.com>
Signed-off-by: Rishabh Maurya <rishabhmaurya05@gmail.com>
Co-authored-by: Rishabh Maurya <rishabhmaurya05@gmail.com>
(cherry picked from commit 8ca3e6ad51d73b6b89cb88eca8f4c759f708e59b)
This is the backport 2.x PR for https://github.com/opensearch-project/OpenSearch/pull/12569 …
> [Backport 2.x] Add DerivedFieldMapper and support parsing it in mappings (#12569)

- modules/lang-painless/src/main/java/org/opensearch/painless/PainlessPlugin.java
- modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.derived.txt
- modules/lang-painless/src/test/java/org/opensearch/painless/DerivedFieldScriptTests.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
- server/src/main/java/org/opensearch/script/DerivedFieldScript.java
- server/src/main/java/org/opensearch/script/ScriptEmitValues.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
- server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
- test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Backport from https://github.com/opensearch-project/OpenSearch/pull/12837.
> [Backport 2.x] [Derived Fields] Add support for emitting multiple values in DerivedFieldScripts

- CHANGELOG.md
- client/rest/src/main/java/org/opensearch/client/nio/HttpEntityAsyncEntityProducer.java
Client with Java 8 runtime and Apache HttpClient 5 Transport fails with java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer
Came out of https://github.com/opensearch-project/opensearch-java/issues/904
> Client with Java 8 runtime and Apache HttpClient 5 Transport fails with java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

- server/src/main/java/org/opensearch/cluster/routing/WeightedRouting.java
WeightedRoutingKey is used as key in the HashMap to retreive the shard routings, for every usage the hash key is computed. WeightedRoutingKey internally uses WeightedRouting. As the number of the shards getting queried increases, the computation cost goes high.
Computing the hash key during object creation as the object is immutable and using it through out the object thus saving on the additional computation.
- ~[ ] Commit changes are listed out in CHANGELOG.md file (See: …
> Pre computing hash code for WeightedRouting to avoid recomputing it

- CHANGELOG.md
- server/build.gradle
- server/src/main/java/org/opensearch/transport/Header.java
- server/src/main/java/org/opensearch/transport/InboundBytesHandler.java
- server/src/main/java/org/opensearch/transport/InboundDecoder.java
- server/src/main/java/org/opensearch/transport/InboundHandler.java
- server/src/main/java/org/opensearch/transport/InboundMessage.java
- server/src/main/java/org/opensearch/transport/InboundPipeline.java
- server/src/main/java/org/opensearch/transport/NativeMessageHandler.java
- server/src/main/java/org/opensearch/transport/ProtocolInboundMessage.java
- server/src/main/java/org/opensearch/transport/ProtocolMessageHandler.java
- server/src/main/java/org/opensearch/transport/TcpTransport.java
- server/src/main/java/org/opensearch/transport/TransportLogger.java
- server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundBytesHandler.java
- server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundMessage.java
- server/src/main/java/org/opensearch/transport/nativeprotocol/package-info.java
- server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
- server/src/test/java/org/opensearch/transport/InboundPipelineTests.java
- server/src/test/java/org/opensearch/transport/OutboundHandlerTests.java
> [Backport 2.x] Adding support for handling multiple transport protocols (#12967)

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
- server/src/main/java/org/opensearch/common/blobstore/BlobPath.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
- server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
- test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
This is one of the tasks to achieve https://github.com/opensearch-project/OpenSearch/issues/12589 as part of the feature request https://github.com/opensearch-project/OpenSearch/issues/12567. This is only an increment step to conclude the optimised prefix path work proposed in the feature request.
In this PR, we are getting following things done -
1. Implement hash functions for the path generation based on the custom data in the index metadata.
2. Made the `hashed_prefix` as the default path type.
3. Added another path type `hashed_infix`. This can be used to keep the data confined for a cluster within the base path supplied by the user.
4. Added multiple tests, updated multiple UTs and ITs.
Resolves #13074
- ~[ ] Commit changes are listed out in CHANGELOG.md file (See: …
> Add implementation for remote store path types

- .github/workflows/pull-request-checks.yml
Skips the CI check `Pull Request Checks / Verify Description Checklist` for PRs from dependabot.
See the CI checks on a dependabot PR like [this](https://github.com/opensearch-project/OpenSearch/pull/13117) where the check fails since it doesn't contain the checklist on the PR template.
> Skip Pull Request Checks / Verify Description Checklist for dependabot

- CHANGELOG.md
- libs/core/src/main/java/org/opensearch/core/common/io/stream/FilterStreamInput.java
- libs/core/src/test/java/org/opensearch/core/common/io/stream/FilterStreamInputTests.java
Signed-off-by: kkewwei [kkewwei@163.com](mailto:kkewwei@163.com)
Implement mark() in class FilterStreamInput 
Resolves #13096 
> implement mark() in class FilterStreamInput

- CHANGELOG.md
- libs/core/src/main/java/org/opensearch/core/common/io/stream/FilterStreamInput.java
- libs/core/src/test/java/org/opensearch/core/common/io/stream/FilterStreamInputTests.java
> [Backport 2.x] implement mark() in class FilterStreamInput 

- client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
- server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
- server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
- server/src/main/java/org/opensearch/index/mapper/DerivedField.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
- server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
- server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
- server/src/main/java/org/opensearch/index/query/QueryShardContext.java
- server/src/main/java/org/opensearch/index/query/VectorGeoPointShapeQueryProcessor.java
- server/src/main/java/org/opensearch/script/DerivedFieldScript.java
- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightPhase.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightUtils.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
- server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
- server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
- server/src/test/java/org/opensearch/search/SearchServiceTests.java
- server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
- server/src/test/java/org/opensearch/search/fetch/subphase/FieldFetcherTests.java
- server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
- test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Adds following capability to derived fields - 
1. Define derived fields in search request - 
There are 2 ways to add derived fields to search path - a) Programatically using a rest client (which makes use of `DerivedField` class and adding to it `SearchSourceBuilder` ) b) through http request, which relies on document parsing. Thus you will see logic for both in `SearchSourceBuilder`. Given, we don't have access to mapper service in these classes, its not possible to create a derived field mapper and type in `SearchSourceBuilder`, thus they are used and are created in `SearchService` and injected into `QueryShardContext`. Once available in `QueryShardContext`, these derived fields mappers from search request can be used in different phases of the query. 
2. Support in fetch phase.
3. …
> [Derived Fields] PR4: Capability to define derived fields in search request

- libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
[BUG] Fix org.opensearch.common.xcontent.XContentParserTests.testString flaky test (YAML codepoint calculation is unreliable).
Closes https://github.com/opensearch-project/OpenSearch/issues/12395
> [BUG] Fix org.opensearch.common.xcontent.XContentParserTests.testString flaky test

- client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
- server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
- server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
- server/src/main/java/org/opensearch/index/mapper/DerivedField.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
- server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
- server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
- server/src/main/java/org/opensearch/index/query/QueryShardContext.java
- server/src/main/java/org/opensearch/index/query/VectorGeoPointShapeQueryProcessor.java
- server/src/main/java/org/opensearch/script/DerivedFieldScript.java
- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightPhase.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightUtils.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
- server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
- server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
- server/src/test/java/org/opensearch/search/SearchServiceTests.java
- server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
- server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
- test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Backport https://github.com/opensearch-project/OpenSearch/commit/645b1f1b6c0738ef2b4a0de364b6bcd42af239b9 from https://github.com/opensearch-project/OpenSearch/pull/12850.
- ~~[ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~~
> [Backport 2.x] [Derived Fields] PR4: Capability to define derived fields in search request

- CHANGELOG.md
- libs/common/src/main/java/org/opensearch/common/Glob.java
- server/src/main/java/org/opensearch/common/regex/Regex.java
- server/src/test/java/org/opensearch/common/GlobTests.java
Changed globMatch from recursive to iterative implementation using the existing code in simpleMatchWithNormalizedStrings by @cwperks as part of  #11060.
Resolves #12065
> Refactoring globMatch using simpleMatchWithNormalizedStrings from Regex

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationSuiteIT.java
- server/src/main/java/org/opensearch/indices/replication/CheckpointInfoResponse.java
- server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
- server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
- server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
- server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
- server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
- server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
- server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
This PR fixes race conditions while shutting down SegmentReplicationSourceService used for node-node segment replication that cause store refs to not close before checks are made. This is the cause for flakiness with SegmentReplicationSuiteIT and a few others.
The issue here is we are creating new replications on the primary after we have cancelled replications but before the shard is closed.  OngoingSegmentReplications has a `prepareForReplications` method that previously would invoke `getCachedCopyState`.  In that method we would first fetch copyState from the map and incref it if it exists.  This left us open to incref the copyState ref even though the shard is shutting down & no longer in indexService.
To fix this this change removes the responsibility of caching CopyState inside of …
> Fix flakiness with SegmentReplicationSuiteIT

- .github/workflows/wrapper.yml
- CHANGELOG.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/13192 to `2.x`
> [Backport] [2.x] Bump gradle/wrapper-validation-action from 2 to 3 (#13192)

- doc-tools/missing-doclet/src/main/java/org/opensearch/missingdoclet/MissingDoclet.java
There are generators (like `protobuf`) which add `@javax.annotation.Generated` to top level classes only. The missing javadoc verification does not support that and fails with the error.
```
@javax.annotation.Generated(value="protoc", comments="annotations:FetchSearchResultProto.java.pb.meta")
public final class FetchSearchResultProto {
public interface FetchSearchResultOrBuilder extends
// ...
}
}
```
Closes https://github.com/opensearch-project/OpenSearch/issues/11913
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifica …
> [BUG] Fix missing javadocs error for nested generated types

- CHANGELOG.md
- modules/cache-common/src/internalClusterTest/java/org.opensearch.cache.common.tier/TieredSpilloverCacheIT.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/policy/TookTimePolicy.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/policy/TookTimePolicyTests.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
- server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/13063
- ~[] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~
> [Backport 2.x] [Tiered Caching] Make took time policy dynamic and add additional integ tests

- .github/workflows/changelog_verifier.yml
- Hardens the check for `CHANGELOG.md` file and ensures a backport label exists if the entry is BwC
N/A
> Enhance changelog workflow to check for missing labels

- .github/CODEOWNERS
- MAINTAINERS.md
We want to recognize the maintainership of @abbashus @setiah @adnapibar and @ryanbogan in this project - I am moving them to Emeritus section of our maintainers documentation.
We are trying to make sure that maintainers that are able to engaged in the project are listed in the active section.  If any any time these emeritus maintainers would like to take up their role again they just need submit a pull request https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#inactivity
- Related https://github.com/opensearch-project/OpenSearch/issues/12970 …
> Update maintainers based on activity since Jan 2024

- CHANGELOG.md
- TRIAGING.md
Triage meetings have moved to Zoom
- Related #13057 
> Triage meetings have moved to Zoom

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
- server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
This is one of the tasks to achieve https://github.com/opensearch-project/OpenSearch/issues/12589 as part of the feature request https://github.com/opensearch-project/OpenSearch/issues/12567. This is only an increment step to conclude the optimised prefix path work proposed in the feature request. 
In this PR, we have introduced a composite encoding for the 64 bits hash value. We use multiple attributes like index uuid, shard id, data category (segment/translog) and data type (data/metadata/lock_files) for generating a 64 bit hash value. Now, based on tests performed during the development, we have found a encoding that works best when the index shard counts or indexing rate increases on a cluster. The encoding uses 1st 6 bits to generate URL safe base 64 character and uses rest of the 14 …
> Add faster scaling composite hash value encoding for remote path

- server/src/test/java/org/opensearch/index/codec/fuzzy/FuzzyFilterPostingsFormatTests.java
…failures
[Fix FuzzyFilterPostingsFormatTests] Suppress sys out checks for test case
Resolves https://github.com/opensearch-project/OpenSearch/issues/13177
> [Fix FuzzyFilterPostingsFormatTests] Suppress sys out checks for test case

- server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
Add warn logs for remote backpressure rejection on per request level. 
Resolves none
> Add warn logs for remote backpressure rejection

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
- server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Reverts opensearch-project/OpenSearch#13155
This pull request breaks the public contract [1] without a changelog entry or associated documentation
```
Comparing source compatibility of  against 
***! MODIFIED ENUM: PUBLIC ABSTRACT STATIC org.opensearch.index.remote.RemoteStoreEnums$PathHashAlgorithm  (field removed)
===  CLASS FILE FORMAT VERSION: 55.0 <- 55.0
---! REMOVED FIELD: PUBLIC(-) STATIC(-) FINAL(-) org.opensearch.index.remote.RemoteStoreEnums$PathHashAlgorithm FNV_1A
+++  NEW FIELD: PUBLIC(+) STATIC(+) FINAL(+) org.opensearch.index.remote.RemoteStoreEnums$PathHashAlgorithm FNV_1A_COMPOSITE_1
+++  NEW FIELD: PUBLIC(+) STATIC(+) FINAL(+) org.opensearch.index.remote.RemoteStoreEnums$PathHashAlgorithm FNV_1A_BASE64
***! MODIFIED CLASS: PUBLIC org.opensearch.indices.IndicesService …
```
> Revert "Add faster scaling composite hash value encoding for remote path"

- server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
This test is flaky because it is incorrectly passing a checkpoint with a higher primary term on the second invocation. This will cancel the first replication and start another.  The test sometimes passes because it is only asserting on processLatestReceivedCheckpoint. If the cancellation quickly completes before attempting second replication event the test will fail, otherwise it will pass.
Fixed this test by ensuring the pterm is the same, but the checkpoint is ahead (higher sis verison).  Also added assertion that replication is not started with the exact ahead checkpoint instead of only processLatestReivedCheckpoint. Tests already exist for ahead primary term "testShardAlreadyReplicating_HigherPrimaryTermReceived".
Resolves https://github.com/opensearch-project/OpenSearch/issues/8928 …
> Fix flaky test SegmentReplicationTargetServiceTests#testShardAlreadyReplicating

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/index/translog/Translog.java
- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
- If we upload the translog files and before uploading translog metadata, process restarts (due to any reason) and the same node gets the shard assigned, the subsequent translog uploads fail with NPE.
- Detailed analysis is provided in https://github.com/opensearch-project/OpenSearch/issues/12554
- In this PR, while downloading translog, if remote does not contain a metadata file, we cleanup non-empty translog files on local.
- https://github.com/opensearch-project/OpenSearch/issues/12554
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md# …
> [Remote Store] Cleanup local-only translog files if no metadata in remote

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
- server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
This is a follow up PR from https://github.com/opensearch-project/OpenSearch/pull/13155#discussion_r1565979927. In this PR, we have moved 2 settings - `cluster.remote_store.index.path.type` and `cluster.remote_store.index.path.hash_algorithm` to the RemoteStoreSettings class.  …
> Add remote path settings to RemoteStoreSettings class

- server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/13260 to `main`
N/A
> [Forwardport] Snapshot _status API to return correct status for partial snapshots (update version)

- server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/13248 to 2.x.
This PR includes two additional changes to bring this file in sync with main.
https://github.com/opensearch-project/OpenSearch/commit/59a62e79e30c183bd46905f8d46a886942518b86 updated localNode definition on 2.x but not on main.
https://github.com/opensearch-project/OpenSearch/commit/e942483e716255b8f801dc1242f909d73019aa70 unmuted this test on main but was not backported.
The rest is the same.
> [Backport 2.x] Fix flaky test SegmentReplicationTargetServiceTests#testShardAlreadyReplicating

- CHANGELOG.md
- TESTING.md
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
- test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java
Backport PR for #13054
Resolves #13054
> [Backport 2.x] enabled mockTelemetryPlugin for IT and fixed OOM (#13054)

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/index/translog/Translog.java
- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/1c208d581aa0597615e98e27894f1f4c2dde8e75 from https://github.com/opensearch-project/OpenSearch/pull/12691.
> [Backport 2.x][Remote Store] Cleanup local-only translog files if no metadata in remote (#12691)

- rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/10_basic.yml
In 2.13.0, we added a new parameter `primary_only` for the force-merge API in this PR:https://github.com/opensearch-project/OpenSearch/pull/11269,  but I found that we omitted updating the supported version in a yaml test file when we updated the version check by this PR: https://github.com/opensearch-project/OpenSearch/pull/12657, so we need to update it.
Backport to 2.x is not needed, and changelog is also not needed.
https://github.com/opensearch-project/OpenSearch/issues/8021
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …
> Update supported version in yaml test file for the primary_only parameter in force-merge API

- .github/workflows/detect-breaking-change.yml
There have been a couple of cases where changes have come into OpenSearch's main branch that are intentionally modifying the @PublicAPI annotated classes.  While it is useful to have a signal about breaking changes, it is important that minimal noise is generated.
Until we have a clear plan for how to create a strong signal for breaking changes on `main` by disabling this workflow.
- Related #13275
> Disabling breaking changes check on main

- CHANGELOG.md
- server/src/main/java/org/opensearch/rest/BaseRestHandler.java
- server/src/main/java/org/opensearch/rest/action/admin/indices/RestForceMergeAction.java
- server/src/test/java/org/opensearch/action/admin/indices/forcemerge/RestForceMergeActionTests.java
- server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
- server/src/test/java/org/opensearch/search/pit/RestDeletePitActionTests.java
Removes the `BaseRestHandler` check for unconsumed content added in https://github.com/opensearch-project/OpenSearch/commit/687978b7d167d4c20a29861b2558b2749c349529 as this check was inadvertently made dead code (when using real HttpRequests and not mocked ones) in https://github.com/opensearch-project/OpenSearch/commit/1cd464d675b3cc3fd478b5b530b2d3a316bc2c6b
Resolves #13011 
Related to https://github.com/opensearch-project/flow-framework/issues/638
- ~[ ] New functionality has been documented.~ (This behavior was undocumented and remains so.)
- ~[ ] New functionality has javadoc added~ (No new functionality)
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ (This behavior was undocumented and remains so.)
By …
> Ignore BaseRestHandler unconsumed content check as it's always consumed

- CHANGELOG.md
- server/src/main/java/org/opensearch/rest/BaseRestHandler.java
- server/src/test/java/org/opensearch/action/admin/indices/forcemerge/RestForceMergeActionTests.java
- server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
- server/src/test/java/org/opensearch/search/pit/RestDeletePitActionTests.java
Backport 0282e64bb25a8485526a1b6bf584ac2b9495f219 from #13290.
> [Backport 2.x] Ignore BaseRestHandler unconsumed content check as it's always consumed (#13290)

- .github/workflows/detect-breaking-change.yml
- CHANGELOG.md
- DEVELOPER_GUIDE.md
- server/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/13292 to `2.x`
> [Backport] [2.x] Reconsider the breaking changes check policy to detect breaking changes against released versions (#13292)

- server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
Fixes flaky test introduced in highlighter test for derived field.
Resolves https://github.com/opensearch-project/OpenSearch/issues/13249
- ~~[ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~~
> Fix the flaky test for derived fields highlighter test

- server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
This is just a refactor. Earlier the callers of `IndexShard.waitForRemoteStoreSync` needed to verify if it is really in sync and throw exception if not . 
With this change, `waitForRemoteStoreSync` will throw an `IOException` , making it easy for the consumers to fail directly . 
Resolves 
> [Remote Store] Throw IOException when remote is not in sync

- CHANGELOG.md
- modules/rank-eval/src/internalClusterTest/java/org/opensearch/index/rankeval/RankEvalRequestIT.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
- server/src/test/java/org/opensearch/cluster/metadata/IndexNameExpressionResolverTests.java
* Improve the error messages for _stats with closed indices
Signed-off-by: srikanth padakanti <srikanth29.9@gmail.com>
---------
Signed-off-by: Srikanth Padakanti <srikanth29.9@gmail.com>
(cherry picked from commit 98009ed9b83d43377e6b3ffa610db7154ff7d200)
Improve the error messages for _stats with closed indices
Resolves #[https://github.com/opensearch-project/OpenSearch/issues/11180]
- [ X] New functionality includes testing.
- [ X] All tests pass
- [ X] Commits are signed per the DCO using --signoff
- [ X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)
By submitting this pull request, I confirm that …
> Improve error messages for `_stats` with closed indices  (#13012)

- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java
* During remote store migration (`MIXED` compatibility mode and `REMOTE_STORE` migration direction), we aim to continuously move forward. 
* To ensure this, in case of a primary shard failover:
* If the primary and one or more replica copies had already migrated to remote nodes, then the new primary must be chosen randomly from the migrated replicas
* If no migrated replica is found, fall back upon the existing priority choosing
* This preference has been implemented as follows:
* `metadata` is used to identify migration conditions
* `activeReplicaOnRemoteNode` makes use of the `failedShard`'s id, to obtain migrated replica copies and randomly returns one 
Resolves #13135
For …
> Prefer remote replicas for primary promotion during migration

- server/src/main/java/org/opensearch/index/shard/ReleasableRetryableRefreshListener.java
- server/src/test/java/org/opensearch/index/shard/ReleasableRetryableRefreshListenerTests.java
- Currently, while scehduling retry of refesh for remote backed index, `OpenSearchRejectedExecutionException` is thrown if the executor is shutdown. This could happen when the node is shutting down.
- This results in flakiness of tests as observed in [#10762](https://github.com/opensearch-project/OpenSearch/issues/10762) and [#11993](https://github.com/opensearch-project/OpenSearch/issues/11993)
- https://github.com/opensearch-project/OpenSearch/issues/10762
- https://github.com/opensearch-project/OpenSearch/issues/11993 …
> [Remote Store] Handle OpenSearchRejectedExecutionException while retrying refresh

- rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml
Skip Search Pipeline integration tests for OpenSearch versions below 2.9.0. For a more detailed explanation, please see issue #13339 .
Resolves #13339
Related to https://github.com/opensearch-project/opensearch-py/pull/726
By …
> Skip Search Pipeline integration tests for OpenSearch versions below 2.9.0

- server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
- server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
(cherry picked from commit 2aad4998af0b20b28fd7dba009fdba4658bb130e)
Backport #13185 to 2.x
> [Backport 2.x] Prevent version upgrade during remote migration (#13185)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
- server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldDataTests.java
Fixed an error `'Preview of field's value: 'null'` that occurred when using flat_object with long field names in OpenSearch version `2.12` and later.
https://github.com/opensearch-project/OpenSearch/issues/13184
> Fix flat_object long field error

- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
- server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Backporting https://github.com/opensearch-project/OpenSearch/pull/13159 to 2.x
Resolves https://github.com/opensearch-project/OpenSearch/issues/13158
> [Backport 2.x - Remote Store - Dual Replication] Create missing Retention Leases for docrep shard copies during failover

- CHANGELOG.md
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
- plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
- server/src/main/java/org/opensearch/common/cache/Cache.java
- server/src/main/java/org/opensearch/common/cache/ICache.java
- server/src/main/java/org/opensearch/common/cache/ICacheKey.java
- server/src/main/java/org/opensearch/common/cache/serializer/ICacheKeySerializer.java
- server/src/main/java/org/opensearch/common/cache/stats/CacheStats.java
- server/src/main/java/org/opensearch/common/cache/stats/CacheStatsHolder.java
- server/src/main/java/org/opensearch/common/cache/stats/ImmutableCacheStats.java
- server/src/main/java/org/opensearch/common/cache/stats/ImmutableCacheStatsHolder.java
- server/src/main/java/org/opensearch/common/cache/stats/package-info.java
- server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
- server/src/main/java/org/opensearch/common/cache/store/builders/ICacheBuilder.java
- server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/common/cache/serializer/ICacheKeySerializerTests.java
- server/src/test/java/org/opensearch/common/cache/stats/CacheStatsHolderTests.java
- server/src/test/java/org/opensearch/common/cache/stats/ImmutableCacheStatsHolderTests.java
- server/src/test/java/org/opensearch/common/cache/stats/ImmutableCacheStatsTests.java
- server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
**Original PR: https://github.com/opensearch-project/OpenSearch/pull/12531**
Signed-off-by: Peter Alfonsi <petealft@amazon.com>
Co-authored-by: Peter Alfonsi <petealft@amazon.com>
(cherry picked from commit cc22310145309b3f3dfca377a84f4e26579611be)
As part of [tiered caching stats](https://github.com/opensearch-project/OpenSearch/issues/12258), changes the common ICache interface to use ICacheKey as its key. This key contains dimensions (for example, shard ID, index name, or tier) that can be used to aggregate stats. Also changes the CacheStats interface to store the necessary cache stats, and to support getting stats either as a total or aggregated by these dimensions. 
Integrates these changes with OpenSearchOnHeapCache and EhcacheDiskCache. The stats implementation for the …
> [Backport 2.x] [Tiered Caching] Stats rework (1/3): Interfaces and implementations for individual tiers

- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
- server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
* This change ensures that when under remote-store/docrep migration, shallow snapshots are not taken as both remote-backed and non-remote-backed indices are present.
* For the `createSnapshot` operation, if the `remote_store_index_shallow_copy` setting is found to be `true` in the repository metadata settings but the cluster is in the `MIXED` compatibility mode, we override this setting to `false`. Thus, we do not honor the shallow snapshot setting and create full snapshots only.
Resolves #13101
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUT …
> Take shallow copy snapshot only when remote store compatibility mode is STRICT

- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java
(cherry picked from commit efa06feeabd336e3d95764d072b116250c01d8f5)
Backport #13136 to 2.x
> [Backport 2.x] Prefer remote replicas for primary promotion during migration (#13136)

- server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
The fix is for flaky test ClusterManagerDisruptionIT#testIsolateClusterManagerAndVerifyClusterStateConsensus where the verification of ClusterStateStats was failing. The test was asserting on the ClusterStats which was retrieved from a random node in cluster. However ClusterStateStats is local to a node and has to be verified on node which was ClusterManager before the disruption was started.
```
2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.discovery.ClusterManagerDisruptionIT.testIsolateClusterManagerAndVerifyClusterStateConsensus" -Dtests.seed=3DFAFA04789EDE1A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-CU -Dtests.timezone=Asia/Katmandu -Druntime.java=21
2> …
```
> flaky test fix -  assert cluster stats on ClusterManager Node

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/SearchQueryCounters.java
- server/src/test/java/org/opensearch/action/search/SearchQueryCategorizerTests.java
(cherry picked from commit abe270f3b54c9e89d9375067509b9696a43d699a)
The change aims to make the search query counters dynamic to support all query types.
Description
Initially, we only incremented counters for a select few query types as part of https://github.com/opensearch-project/OpenSearch/issues/11596. Based on requests in the https://github.com/opensearch-project/OpenSearch/issues/5983, we want to cover ALL query types including the query types that might be included as part of plugin code.
To implement this, we create a map that stores the query builder name to Query type Counter. When we encounter a new query type we add the query to the map and create a new associated counter. We then use this counter to increment for all requests coming in for the aforementioned query type. …
> [Backport 2.x] Make search query counters dynamic to support all query types (#12601)

- server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathResolver.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathType.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/91582e7c25a6f76eeebfa3ab74287178e1986491 from https://github.com/opensearch-project/OpenSearch/pull/12607.
> [Backport 2.x] Introduce remote store path type in customData in IndexMetadata (#12607)

- CHANGELOG.md
- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
- server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/18aa5ad084b3ba0bc0603a84988699e71c461ae8 from https://github.com/opensearch-project/OpenSearch/pull/13389.
> OpenJDK Update (April 2024 Patch releases)

- .github/workflows/assemble.yml
- .github/workflows/precommit.yml
- CHANGELOG.md
Switch to macos-13 runner for precommit and assemble github actions due to macos-latest is now arm64
https://github.com/opensearch-project/OpenSearch/issues/13417
> Switch to macos-13 runner for precommit and assemble github actions due to macos-latest is now arm64

- CHANGELOG.md
- modules/cache-common/src/internalClusterTest/java/org.opensearch.cache.common.tier/TieredSpilloverCacheIT.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCachePluginTests.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/13373
N/A
> [Backport 2.x] [Tiered Caching] Expose a dynamic setting to disable/enable disk cache

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
- server/src/main/java/org/opensearch/common/blobstore/BlobPath.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
- server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
- test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/bad49efab29bd5161458f182b87c5d78d8de3cac from https://github.com/opensearch-project/OpenSearch/pull/13103.
> [Backport 2.x] Add implementation for remote store path types

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
- server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/02f9d74ec7746ebe9f6e71fe86b127813a4e4daa from https://github.com/opensearch-project/OpenSearch/pull/13251.
> [Backport 2.x] Add faster scaling composite hash value encoding for remote path

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/test/java/org/opensearch/index/IndexModuleTests.java
- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
- server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/b7396e1cbaf5d8d10ad2917afbaab54f1d4e2816 from https://github.com/opensearch-project/OpenSearch/pull/12704
> [Backport 2.x] [Remote Store] Make translog transfer timeout configurable using dynamic setting

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreUploadIndexPathIT.java
- server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
- server/src/main/java/org/opensearch/gateway/remote/IndexMetadataUploadListener.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/index/remote/RemoteIndexPath.java
- server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
- server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/repositories/blobstore/BaseBlobStoreFormat.java
- server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
- server/src/main/java/org/opensearch/repositories/blobstore/ConfigBlobStoreFormat.java
- server/src/test/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainerTests.java
- server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteIndexPathTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/3ea0a31f6f613ddd5b7bde0053195d5b212c813d from https://github.com/opensearch-project/OpenSearch/pull/13150.
> [Backport 2.x] Upload remote paths during index creation or full cluster upload

- CONTRIBUTING.md
I accidentally deleted this section of the Contributing.md section and missed it during review
It originally came from @reta : https://github.com/opensearch-project/OpenSearch/pull/10751/files
https://github.com/opensearch-project/OpenSearch/pull/12981#issuecomment-2078179600
> Restore deleted section of Contributing.md

- server/src/internalClusterTest/java/org/opensearch/remotemigration/DocRepMigrationTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/ResizeIndexMigrationTestCase.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Adds more remote migration integ tests 
1. Replica recovery 
2. Failover to docrep copy 
3. End to end testing with refresh/flush , covering primary-replica relocation 
4. Minor refactoring 
Resolves none. 
- [] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
> Add more Remote Migration Integration Tests 

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
- server/src/main/java/org/opensearch/cluster/ClusterModule.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/ExistingShardsAllocator.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
- server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
- server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
- server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
- server/src/test/java/org/opensearch/gateway/ShardBatchCacheTests.java
- test/framework/src/main/java/org/opensearch/test/gateway/TestGatewayAllocator.java
- test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Changes for create/update/delete batches for batch mode for async fetch for both primary & replica. It also added the node scope setting to enable/ disable batch mode.
Signed-off-by: Gaurav Chandani <chngau@amazon.com>
Signed-off-by: Shivansh Arora <hishiv@amazon.com>
Signed-off-by: Aman Khare <amkhar@amazon.com>
(cherry picked from commit a69cd0864a673579a9cb2190da765bc1ebfd0a22 from #8746)
> [Backport 2.x] Async Batch shards changes for GatewayAllocator

- server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
- server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
Updates the version from current to 2.14 corresponding to https://github.com/opensearch-project/OpenSearch/issues/12988. The same shall be backported as well.  …
> [Remote Store] Update version to 2.14 in path type min node version check

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreUploadIndexPathIT.java
- server/src/main/java/org/opensearch/gateway/remote/IndexMetadataUploadListener.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/remote/RemoteIndexPath.java
- server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
- server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
This is a follow up PR after https://github.com/opensearch-project/OpenSearch/pull/13150. In this PR, we are doing the following things -
1. Refactored the IndexMetadataUploadListener to support a more generic hook for index metadata upload.
2.  Add index metadata version and file version in the filename of the remote index path file.
Resolves #13302
> Add version details in remote index path file with code enhancements

- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregationBuilder.java
I added unit tests to verify the multiple orders in the multiple terms aggregation.
Resolves #13375
> Add unit test of multipler orders for multiple terms aggregation.

- CHANGELOG.md
- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
- server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/13406 to `1.x`
> [Backport] [1.x] OpenJDK Update (April 2024 Patch releases) (#13406)

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
- server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
- server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
In https://github.com/opensearch-project/OpenSearch/pull/7470, we added the ability to specify a search pipeline that will execute by default for queries against a single index. 
This PR handles a check to see if all the concrete indices have the same default pipeline and attached it.   
Resolves https://github.com/opensearch-project/OpenSearch/issues/7512
> [Search Pipeline]Handled default search pipeline for multiple indices

- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Fix Flaky test `IndicesRequestCacheIT.testStaleKeysCleanupWithMultipleIndices.` failing with `java.lang.AssertionError: expected:<-665> but was:<665>`
In the below code, memorySizeOfLatestEntryForIndex1 would be negative (-665) if the cacheCleaner ran before the execution of that line resulting in `getRequestCacheStats(client, index1).getMemorySizeInBytes()` to be smaller than `finalMemorySizeForIndex1`
```java 
long memorySizeOfLatestEntryForIndex1 = getRequestCacheStats(client, index1).getMemorySizeInBytes() - finalMemorySizeForIndex1;
.
.
.
assertEquals(memorySizeOfLatestEntryForIndex1, getRequestCacheStats(client, index1).getMemorySizeInBytes())
```
The fix is to not depend on the exact size of the `memorySizeOfLatestEntryForIndex1` and instead make sure the current request cache …
> Fix Flaky test IndicesRequestCacheIT.testStaleKeysCleanupWithMultipleIndices

- server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
- server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
- server/src/main/java/org/opensearch/index/cache/request/ShardRequestCache.java
Follows up to https://github.com/opensearch-project/OpenSearch/pull/13237 and its backport https://github.com/opensearch-project/OpenSearch/pull/13456. In the backport, we changed versions from V_3_0_0 to V_2_14_0, and re-added functions to ShardRequestCache that were required by the breaking-changes test. This PR brings those changes back to main so the two should be aligned. 
Part of https://github.com/opensearch-project/OpenSearch/issues/12258
[] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
[] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ …
> [Tiered Caching] Bump versions for serialization in new cache stats API

- server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java
Fixes flaky test AdmissionForClusterManagerIT#testAdmissionControlResponseStatus
The test [waits](https://github.com/rajiv-kv/OpenSearch/blob/674e3a40ef6920d8752e9ae5e88d4cd2c1b6ac83/server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java#L181) for the response on the latch `waitForResponse`. Since the latch was count down before setitng the response from the client, the waiting thread read null response causing it fail on NPE
Resolves #13045
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CON …
> [Flaky Test] Setting the response before latch countdown

- .github/workflows/links.yml
- CHANGELOG.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/13447 to `2.x`
> [Backport] [2.x] Bump lycheeverse/lychee-action from 1.9.3 to 1.10.0 (#13447)

- CHANGELOG.md
- distribution/packages/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/13440 to `2.x`
> [Backport] [2.x] Bump com.netflix.nebula.ospackage-base from 11.8.1 to 11.9.0 in /distribution/packages (#13440)

- CHANGELOG.md
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
- rest-api-spec/src/main/resources/rest-api-spec/api/bulk.json
- server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
- server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
- server/src/main/java/org/opensearch/common/metrics/OperationMetrics.java
- server/src/main/java/org/opensearch/ingest/CompoundProcessor.java
- server/src/main/java/org/opensearch/ingest/IngestDocumentWrapper.java
- server/src/main/java/org/opensearch/ingest/IngestService.java
- server/src/main/java/org/opensearch/ingest/Pipeline.java
- server/src/main/java/org/opensearch/ingest/Processor.java
- server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java
- server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
- server/src/test/java/org/opensearch/ingest/CompoundProcessorTests.java
- server/src/test/java/org/opensearch/ingest/IngestDocumentPreparer.java
- server/src/test/java/org/opensearch/ingest/IngestDocumentWrapperTests.java
- server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
- server/src/test/java/org/opensearch/ingest/ProcessorTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/1219c568248fafa479d67a1eaa6e3e2d9748701e from https://github.com/opensearch-project/OpenSearch/pull/13306.
This PR is to enable batch ingestion in _bulk API. Please refer to https://github.com/opensearch-project/OpenSearch/issues/12457 for proposal and discussion.
Closes https://github.com/opensearch-project/OpenSearch/issues/12457.
> [Backport 2.x] Support batch ingestion in bulk API (#12457) (#13306)

- .github/workflows/gradle-check.yml
Running gradle check on release notes does not provide any value but instead adds a huge overhead while merging PRs during release cycle. Had to wait for 2+ hours during 2.13.0 while creating RC as release notes if one of the [entrance criteria](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#entrance-criteria-to-start-release-window) to start the release window.
Please let me know if we should include all `.md`files as well `.github` directory to this list as well.
https://github.com/opensearch-project/opensearch-build/issues/4562 …
> Skip running gradle checks on release notes

- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
- server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
- server/src/main/java/org/opensearch/common/cache/ICache.java
- server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/common/cache/stats/ImmutableCacheStatsHolderTests.java
- server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
I introduced CacheStatsAPIIndicesRequestCacheIT in [this recent PR](https://github.com/opensearch-project/OpenSearch/pull/13237) but I have found it to be flaky (example [here](https://build.ci.opensearch.org/job/gradle-check/38005/testReport/junit/org.opensearch.indices/CacheStatsAPIIndicesRequestCacheIT/testNullLevels__p0___opensearch_experimental_feature_pluggable_caching_enabled___true___/)).  I created an issue for this [here](https://github.com/opensearch-project/OpenSearch/issues/13458).
If `levels` is uninitialized in CommonStatsFlags, the String[] `levels` passed into DefaultCacheStatsHolder is usually an empty list. This is the expected behavior. But in some cases, DefaultCacheStatsHolder receives null instead of an empty list, and in this case, the XContent output derived from …
> [Backport 2.14] [Bugfix] Fix flaky test CacheStatsAPIIndicesRequestCacheIT.testNullLevels()

- .github/workflows/gradle-check.yml
Reverts opensearch-project/OpenSearch#13477
We are seeing changes that are stalled because `gradle check` which is required by branch protections isn't being triggered, see stuck PR [1].  While we get an updated solution [2] in place, reverting this change.
- [1] https://github.com/opensearch-project/OpenSearch/pull/13494
- [2] https://github.com/opensearch-project/OpenSearch/pull/13498
> Revert "Skip running gradle checks on release notes"

- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/400_inner_hits.yml
Fix Fix org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/400_inner_hits/Include inner hits in top hits}
Failures observed here: https://build.ci.opensearch.org/job/gradle-check/38180/
> Fix org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/400_inner_hits/Include inner hits in top hits}

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
- server/src/main/java/org/opensearch/search/query/QueryCollectorContext.java
- server/src/main/java/org/opensearch/search/query/QueryPhase.java
- server/src/main/java/org/opensearch/search/query/RescoringQueryCollectorContext.java
- server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
Current implementations of query phase searcher (default and concurrent) alway adds `TopDocsCollector` collector to the collector context. In some scenario it's not the preferred behavior, for instance if in a plugin we're adding custom collector that collects doc scores in a different fashion. With current implementation there will be two collectors in the context, this will create a performance overhead. 
With this change we're not changing core functionality or implementation of query phase searcher. Instead we're adding overloaded `searchWith` method that child query phase search can override and pass empty `QueryPhaseSearcher`.
https://github.com/opensearch-project/OpenSearch/issues/13170 …
> Refactor implementations of query phase searcher, add empty QueryCollectorContext

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/SearchRequest.java
- server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
Add support for deep copying a SearchRequest with roundtriping the request to a stream.
Resolves #869 
> Add support for deep copying SearchRequest

- server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Clear transient cluster setting at the end of the test to ensure test clean up doesn't fail 
Remove check of non zero assertion of time as it is non deterministic
Resolves #11179 , #11221
> [Flaky test] Clear transient cluster setting at the end of the test

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
- server/src/main/java/org/opensearch/common/util/IndexUtils.java
- server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/main/java/org/opensearch/snapshots/SnapshotUtils.java
- server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
- server/src/test/java/org/opensearch/snapshots/SnapshotUtilsTests.java
* Support wildcard/regex for indices param in _remotestore/_restore
Signed-off-by: bansvaru <bansvaru@amazon.com>
(cherry picked from commit 29ebd80fdd6771ccc2023bf432977c38c76bfd55)
> [Backport 2.x] Support wildcard/regex for indices param in _remotestore/_restore (#8922)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/engine/EngineConfig.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
- server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Add `useCompoundFile` setting for the engine
Resolves https://github.com/opensearch-project/OpenSearch/issues/13448
> FEATURE-13448: add use compound file setting

- CHANGELOG.md
- modules/cache-common/src/internalClusterTest/java/org.opensearch.cache.common.tier/TieredSpilloverCacheIT.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolder.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
- plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
- plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
- server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
- server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
- server/src/main/java/org/opensearch/common/cache/store/builders/ICacheBuilder.java
- server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
- server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
As part of [tiered caching stats](https://github.com/opensearch-project/OpenSearch/issues/12258), integrates stats with TieredSpilloverCache. This TieredSpilloverCacheStatsHolder implementation is aware of the tier concept and will support aggregating the TSC's stats by tier as well as any other dimension values that are passed into it. It overrides some incrementing logic from DefaultCacheStatsHolder so it can properly combine heap and disk tier stats into stats for the cache as a whole.
TieredSpilloverCache tracks its own stats, rather than pulling stats from its tiers, because its getOrCompute() implementation can cause double-counting of a single hit or miss. To avoid redundancy, the individual tiers do not track their stats when they're part of TieredSpilloverCache. 
Followup to …
> [Backport 2.14] [Tiered Caching] Adds stats implementation for TieredSpilloverCache

- server/src/internalClusterTest/java/org/opensearch/cluster/ClusterHealthIT.java
Addresses fix for Flaky Test o.o.c.ClusterHealthIT.testHealthOnClusterManagerFailover which is caused in scenarios of master node not being able to bootup within 2 minutes occasionally
This change increases the time limit to 3 minutes which will reduce flakiness.
In 5k runs with previous setting of 2 minutes, saw 5 failures.
In 5k runs with new setting of 3 minutes, saw 0 failures
Resolves #1828 
> Update Cluster Manager Node Timeout to 3mins for flaky test o.o.c.ClusterHealthIT.testHealthOnClusterManagerFailover

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml
- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Manually cut this backport from #13522, just to start the gradle check, reducing wait time
> [Backport 2.14] Support multi ranges traversal when doing date histogram rewrite optimization (#13317)

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml
- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Manual backport because auto backport failed https://github.com/opensearch-project/OpenSearch/pull/13317#issuecomment-2092036765
> [Backport 2.x] Support multi ranges traversal when doing date histogram rewrite optimization (#13317)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
- server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
- server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
- server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java
DATETIME_FORMATTER_CACHING_SETTING experimental feature should not default to 'true'
Closes https://github.com/opensearch-project/OpenSearch/issues/13411 (documentation update to follow shortly)
> DATETIME_FORMATTER_CACHING_SETTING experimental feature should not default to 'true'

- server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
Update the version check for batch shard allocator to v2.14
> Update version for batch shard allocation to 2.14

- CHANGELOG.md
- test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/13557 to `2.x`
> [Backport 2.x] Bump org.apache.commons:commons-text from 1.11.0 to 1.12.0 in /test/fixtures/hdfs-fixture (#13557)

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
- server/src/main/java/org/opensearch/index/cache/request/ShardRequestCache.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
- This solves the bug where RequestStats memory_size metric was going negative in certain scenarios as reported in the issue. 
- It turns out that the issue occurs when an indexShard is deleted and then reallocated on the same node. So whenever stale entries from older shard are deleted, those are accounted for the new shard which has the same shardId. 
We made changes recently as part of 2.12 to make IndicesRequestCache key serializable. Earlier we were storing an actual reference to indexShard in the cache. But with the new change we extract indexShard from shardId which eventually caused the above issue.
Resolves https://github.com/opensearch-project/OpenSearch/issues/13343
- ~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/ …
> Fix negative requestStats memory_size issue

- release-notes/opensearch.release-notes-2.14.0.md
- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
- server/src/main/java/org/opensearch/index/cache/request/ShardRequestCache.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Backports https://github.com/opensearch-project/OpenSearch/pull/13553
> [Backport 2.14] Fix negative requestStats memory_size issue (#13553)

- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
As a follow up to https://github.com/opensearch-project/OpenSearch/pull/13553, this PR fixes the requestCache clean up logic so that we don't end up deleting current indexShard entries.
We are also checking for indexShardHashcode during clean up operation.
Related https://github.com/opensearch-project/OpenSearch/issues/13343
> Fix IndicesRequestCache clean up logic

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/engine/EngineConfig.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
- server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Backports 14cd0e33ebfe6c84fcb09687c060e5a0f047c0a7 from #13478 to `2.x`
> [Backport 2.x] FEATURE-13448: add use compound file setting (#13478)

- .github/pull_request_template.md
Added a TODO in the checklist for contributors to add API Specs when introducing new user APIs
Resolves #13619
> Add TODO for Updating API Spec

- CHANGELOG.md
- server/src/main/java/org/opensearch/transport/InboundHandler.java
- server/src/main/java/org/opensearch/transport/NativeMessageHandler.java
- server/src/main/java/org/opensearch/transport/OutboundHandler.java
- server/src/main/java/org/opensearch/transport/ProtocolMessageHandler.java
- server/src/main/java/org/opensearch/transport/ProtocolOutboundHandler.java
- server/src/main/java/org/opensearch/transport/TcpTransport.java
- server/src/main/java/org/opensearch/transport/TcpTransportChannel.java
- server/src/main/java/org/opensearch/transport/TransportStatus.java
- server/src/main/java/org/opensearch/transport/nativeprotocol/CompressibleBytesOutputStream.java
- server/src/main/java/org/opensearch/transport/nativeprotocol/NativeOutboundHandler.java
- server/src/main/java/org/opensearch/transport/nativeprotocol/NativeOutboundMessage.java
- server/src/main/java/org/opensearch/transport/nativeprotocol/NetworkMessage.java
- server/src/test/java/org/opensearch/transport/InboundDecoderTests.java
- server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
- server/src/test/java/org/opensearch/transport/InboundPipelineTests.java
- server/src/test/java/org/opensearch/transport/NativeOutboundHandlerTests.java
- server/src/test/java/org/opensearch/transport/OutboundHandlerTests.java
- server/src/test/java/org/opensearch/transport/TcpTransportTests.java
- server/src/test/java/org/opensearch/transport/TransportLoggerTests.java
- server/src/test/java/org/opensearch/transport/nativeprotocol/CompressibleBytesOutputStreamTests.java
- server/src/test/java/org/opensearch/transport/nativeprotocol/NativeInboundDecoderTests.java
- server/src/test/java/org/opensearch/transport/nativeprotocol/NativeInboundHandlerTests.java
- server/src/test/java/org/opensearch/transport/nativeprotocol/NativeInboundPipelineTests.java
- server/src/test/java/org/opensearch/transport/nativeprotocol/NativeOutboundMessageTests.java
- server/src/test/java/org/opensearch/transport/nativeprotocol/NativeTransportLoggerTests.java
- test/framework/src/main/java/org/opensearch/transport/TestRequest.java
- test/framework/src/main/java/org/opensearch/transport/TestResponse.java
* Abstracting outbound side of transport
* Making outbound handler protocol dependent via inbound handler
* Fixing precommit
* Addressing comments
* Fixing precommit
* Cleaning up code
* Addressing comments
* Cleaning up
* Addressing comments
* Abstracting InboundHandlerTests
* Abstracting TransportLoggerTests
---------
Backport #13293 to 2.x
> [Backport 2.x] Abstracting outbound side of transport (#13293)

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
- server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
Allow clearing `remote_store.compatibility_mode` setting
Resolves #13634
> Allow clearing `remote_store.compatibility_mode` setting

- .github/workflows/detect-breaking-change.yml
Run breaking changes workflow against latest release only (so the unreleased changes won't be reported as breaking ones). 
N/A
> Run breaking changes workflow against latest release only (so the unreleased changes won't be reported as breaking ones)

- .github/workflows/dependabot_pr.yml
- .github/workflows/pull-request-checks.yml
Coming from https://github.com/orgs/community/discussions/25502 and the issue pointed by @cwperks that Pull Request Checks is being run on this PR: https://github.com/opensearch-project/OpenSearch/pull/13643 raised by `dependabot[bot]`.
But actually for the above PR looks to me like the trigger is coming from different bot https://github.com/opensearch-project/OpenSearch/actions/runs/9063816615 which is `opensearch-trigger-bot[bot]`.
Adding `github.event.pull_request.user.login` to get the author who opened this PR and exclude the check for `dependabot[bot]`. …
> Update `github.actor` with `github.event.pull_request.user.login` for `dependabot[bot]` CI's

- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/GenericStatsMetricPublisher.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3TransferRejectedException.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQ.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolder.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolderTests.java
- server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
- server/src/main/java/org/opensearch/common/blobstore/stream/write/WritePriority.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Backport of PR https://github.com/opensearch-project/OpenSearch/pull/12159
> Backport 12159 to 2.x

- .github/workflows/gradle-check.yml
Fixes the revert in https://github.com/opensearch-project/OpenSearch/pull/13027. 
Solution proposed in https://github.com/opensearch-project/OpenSearch/issues/13025#issuecomment-2043611558
From my test run I can confirm that pr description now does not contains new lines, the new line character is now escaped. 
Sample run and output https://github.com/rishabh6788/OpenSearch/actions/runs/9117260498/job/25067702370. 
- Resolves https://github.com/opensearch-project/opensearch-build/issues/4469
- Resolves https://github.com/opensearch-project/OpenSearch/issues/13025 …
> Add more identifiers to gradle-check job webhook payload

- CHANGELOG.md
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/plugins/TelemetryAwarePlugin.java
- server/src/test/java/org/opensearch/node/NodeTests.java
This change will make available the telemetry instances such as tracer and metrics registry to all the plugins.
Resolves #13635
> Adds support to inject telemetry instances to plugins

- server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
Adding documents in a single chunk in unit test to avoid multiple segments in the unit test. 
The following assertion was failing:
```
assertEquals(expectedCollectCount, aggregator.getCollectCount().get());
```
The number of collect() calls is used to check whether the optimization has kicked in or not. The tests written with tight assertions assuminga single segment. 
In local development, running this test in isolation, it is not feasible to get the test failing as it might be creating a single segment. However, in gradle CI (see linked issue) and running the test with other tests, it may happen that multiple segments are created (multiple commits after individual document addition), which is the only explanation why the collect() count assertion is failing case.
So inspired from …
> TermsAggregatorTests flaky test fix

- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Fix Flaky Test - `org.opensearch.indices.IndicesRequestCacheIT.testInvalidStalenessThresholdUpdateThrowsException`
The test is intended to test an exception being thrown on invalid parameter being passed. We don't have to test the working of the cache in this test since it has been covered very extensive in other tests.
The flakiness is due to relying on cache cleanup intervals which are being removed from this test without changing the main objective of the test. 
Resolves #13638 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develop …
> Fix Flaky Test

- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java
Skip unnecessary string format in ThrottlingAllocationDecider when not in debug mode
Resolves #13743 
- ~[ ] All tests pass~
- ~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~ …
> Skip unnecessary string format in ThrottlingAllocationDecider when not in debug mode

- .github/CODEOWNERS
- MAINTAINERS.md
Jay has accepted the invitation to become a maintainer. Welcome Jay!
Jay is an active contributor of OpenSearch project and has extensively contributed in the concurrent segment search feature to make it GA for the users. Aside from this he proactively contributed to improve the documentations for different aggregations like term, sampler, diversified sampler, etc based on his learnings and is pretty active in the triage meetings and reviewing issues/PRs. Jay has contributed 56 pull requests to the project and reviewed close to 53 PRs. Some of his main contributions are:
**PRs:**
* Enabling parallel buildAggregation with concurrent search to further improve on agg performance https://github.com/opensearch-project/OpenSearch/issues/11673
* Doc count error computation at slice level: …
> Add Jay Deng as a maintainer

- .github/workflows/gradle-check.yml
Coming from https://github.com/opensearch-project/OpenSearch/issues/11217#issuecomment-2118322724, this PR will ensure we have the PR number identified by commitID even for `post_merge_action`. This data will be used in gradle metrics dashboard [OpenSearch Gradle Check Metrics](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083). 
The required jenkinsfile change PR https://github.com/opensearch-project/opensearch-build/pull/4719.
The required library change PR https://github.com/opensearch-project/opensearch-build-libraries/pull/427.
With this change we can get the associated PR for failed tests on `post_merge_action`.
Part of: https://github.com/opensearch-project/OpenSearch/issues/3713
Here is the sample workflow run for `push` action …
> Gradle Check Optimization

- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
Refactor the writable remote index feature flag to include the tiering functionality as well. Considered the following options:
1. TIERED_REMOTE_INDEX
2. TIERED_WRITEABLE_INDEX
3. TIERED_WRITEABLE_REMOTE_INDEX (Preferred)
4. TIERED_WRITEABLE_WARM_INDEX
5. TIERING_EXPERIMENTAL
Resolves #13718 
- [] ~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
- [] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ …
> Refactor writable warm feature flag to include tiering

- .github/workflows/assemble.yml
- .github/workflows/copy-linked-issue-labels.yml
- .github/workflows/dependabot_pr.yml
- .github/workflows/gradle-check.yml
- .github/workflows/maintainer-approval.yml
- .github/workflows/precommit.yml
- .github/workflows/version.yml
- .github/workflows/wrapper.yml
While working on this failed backport https://github.com/opensearch-project/OpenSearch/pull/13786#issuecomment-2125934247, I have noticed majority of the existing workflows are either not backported, synced or updated, I have tried to find what ever I can and updated through this PR.
Part of: https://github.com/opensearch-project/OpenSearch/issues/3713
> Sync GitHub workflows from main branch

- .github/workflows/backport.yml
Coming from initial PR https://github.com/opensearch-project/OpenSearch/pull/13790 and comment https://github.com/opensearch-project/OpenSearch/pull/13790#issuecomment-2127927997, add missing backport workflow to `1.x` to ensure we have 1.3 backports working.
Part of: https://github.com/opensearch-project/OpenSearch/issues/3713
> Add backport workflow to 1.x

- modules/repository-url/src/yamlRestTest/java/org/opensearch/repositories/url/RepositoryURLClientYamlTestSuiteIT.java
* Flaky test `org.opensearch.repositories.url.RepositoryURLClientYamlTestSuiteIT.test` did not get reproduced in local environment even after 6K+ iterations
* Adding TRACE level test logging to the test class `RepositoryURLClientYamlTestSuiteIT` to understand the root cause of failure in next gradle build failure for a PR
Relates to #9117
> Add TestIssueLogging on flaky test - org.opensearch.repositories.url.RepositoryURLClientYamlTestSuiteIT.test

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/main/java/org/opensearch/index/shard/SegmentUploadFailedException.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
* [Remote Store] Add segment transfer timeout dynamic setting
(cherry picked from commit b3049fb5ec860f63fdfe33c5b176869b1e4255e6)
Backport of https://github.com/opensearch-project/OpenSearch/pull/13679
> [Backport 2.x] [Remote Store] Add segment transfer timeout dynamic setting (#13679)

- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
It's a NullPointerException from S3BlobStore.extendedStats() method, where 'genericStatsMetricPublisher' is null. This parameter sets through S3Repository constructor from test and in this test it sets as null. This is the root cause of the issue. If we set valid a GenericStatsMetricPublisher, test works fine without any issue. This was a consistent failure, not a random failure. 
Resolves #10735 
Signed-off-by: Abdul Muneer Kolarkunnu <muneer.kolarkunnu@netapp.com> …
> org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats fails with NullPointerException

- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
> Backport 2.x - Refactor writable warm feature flag to include tiering

- test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/13842 to `2.x`
> [Backport] [2.x] Bump com.google.code.gson:gson in /test/fixtures/hdfs-fixture (#13842)

- .github/workflows/gradle-check.yml
The repository requires the gradle check job status to pass before merging any PR. With `path-ignore` filter, this status check was skipped. However, GitHub does not resolve this conflict or allows to specify the requirement to be optional. See https://github.com/opensearch-project/OpenSearch/pull/13494 still waiting for gradle-check status to be set.
There are multiple discussions on GH community forums https://github.com/orgs/community/discussions/44490 and all of them requires work around as of now. This change adds one more step to gradle-check job to detect the files changed and accordingly decide whether to run the consecutive steps or not. See examples below:
1. Where gradle check runs for change in build.gradle https://github.com/gaiksaya/OpenSearch/pull/10
2. Gradle check steps …
> Check changed files before running gradle check

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.14.0.md
Need to update changelog and release notes for a fix which was already release in 2.14. See this. - https://github.com/opensearch-project/OpenSearch/blob/2.14/release-notes/opensearch.release-notes-2.14.0.md?plain=1#L88
> Update changelog and release notes for 2.x

- .github/workflows/assemble.yml
Attempt to stabilize MacOS GA runner related to Colima / Docker issues
N/A (many issues across many builds)
> Attempt to stabilize MacOS GA runner caused by QEMU / Colima / Docker issues

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
- server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Parent filter is passed to nested query in https://github.com/opensearch-project/OpenSearch/pull/10246 PR. The same parent filter should be passed to inner query so that innerHit can utilize the data for correct innerHit result. Without this PR, the result in innerHit does not align with original query result.
https://github.com/opensearch-project/k-NN/issues/1447
> Pass parent filter to inner hit query

- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
Removing the conflicting fromXContent method from Metadata.Custom which is also getting initialized in it's implementations, which was not getting used anywhere.
> Remove conflicting static method from Metadata.Custom interface

- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
If a BlobStoreRepository is created, but the blobStore() method is never called, then the actual blobStore instance won't be created. This means the repository will always emit non-detailed empty stats. When we would try to merge these stats with another repository that was initialized, it would fail the assertion that they either both have detailed stats or neither did.
This fix looks like it's checking if the blobStore has been initialized, but by calling blobStore(), it's making sure that it gets initialized.
Resolves #10735  …
> Fix flaky test S3BlobStoreRepositoryTests.testRequestStats

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
- server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
This reverts commit db5240e06dc08e7d7d03432595bb4d93b0e2e32d.
Reverting due to flaky test failure. https://github.com/opensearch-project/OpenSearch/issues/13890
> Revert "Pass parent filter to inner hit query (#13770)"

- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Switching to a deterministic merge policy due to [Lucene-8962](https://issues.apache.org/jira/browse/LUCENE-8962)
The tests are also passing with the failed seeds
1. **C75D09DC5A0C3458**
2. **1766E6A3B733A7AA**
3. **1000 Iterations Passed**
Resolves #5364 
> Fix Flaky - testForceMergeWithSoftDeletesRetentionAndRecoverySource #5364

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search/50_multi_match.yml
- server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/GreaterThanAssertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/GreaterThanEqualToAssertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/LessThanAssertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/LessThanOrEqualToAssertion.java
Under specific circumstances, when using `cross_fields` scoring on a `multi_match` query, we can end up with negative scores from the inverse document frequency calculation in the BM25 formula.
Specifically, the IDF is calculated as:
```
log(1 + (N - n + 0.5) / (n + 0.5))
```
where `N` is the number of documents containing the field and `n` is the number of documents containing the given term in the field. Obviously, `n` should always be less than or equal to `N`.
Unfortunately, `cross_fields` makes up a new value for `n` and tries to use it across all fields.
This change finds the minimum (nonzero) value of `N` and uses that as an upper bound for the new value of `n`.
Resolves #7860 …
> Avoid negative scores returned from `multi_match` query with `cross_fields`

- CHANGELOG-3.0.md
- server/src/main/java/org/opensearch/index/mapper/MapperService.java
This reverts commit 983297289325bdd1c832bfe18d105bd3e9727ab5.
Opening a PR to discuss this reversion. Removing this deprecated constant caused issues in the SQL Plugin which references the constant. See https://github.com/opensearch-project/sql/pull/2701 where they are working to adapt.
During Union operations, the SQL plugin relies on this list to differentiate between a metafield and a docfield. Ideally, the sql plugin can use [MapperService.isMetadataField](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/MapperService.java#L703-L709) to determine from the official registry of mappers if a field is a metafield, but getting an instance of the mapper service within a plugin is proving to be tricky.
The security plugin uses Guice, …
> Revert "Remove deprecated constant META_FIELDS_BEFORE_7DOT8 (#13860)"

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
- server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
- server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
- server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheSettings.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Two changes here:
1. fix the issue in #12966;
2. make dynamic setting `DATA_TO_FILE_CACHE_SIZE_RATIO_SETTING` take effect.
Resolves #12966
> Fix NPE on restore searchable snapshot

- DEVELOPER_GUIDE.md
Coming from https://github.com/opensearch-project/OpenSearch/issues/11217#issuecomment-2118322724 and https://github.com/opensearch-project/OpenSearch/issues/11217#issuecomment-2140815607 update the `DEVELOPER_GUIDE.md` to add Gradle Check Metrics Dashboard details.
Part of https://github.com/opensearch-project/OpenSearch/issues/11217
> Update the `DEVELOPER_GUIDE.md` to add Gradle Check Metrics Dashboard details

- CHANGELOG.md
- modules/lang-painless/src/test/java/org/opensearch/painless/WhenThingsGoWrongTests.java
- modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/17_update_error.yml
- server/src/main/java/org/opensearch/script/Script.java
- server/src/main/java/org/opensearch/script/UpdateScript.java
See comment here: https://github.com/opensearch-project/OpenSearch/issues/10561#issuecomment-2138270628
Resolves #10561
> Painless: ensure type "UnmodifiableMap" for params

- .github/workflows/gradle-check.yml
Backport 5441d55ee191ca789ba86b7e477a64eb73398c80 from #13786.
> [Backport] [2.14] Gradle Check Optimization (#13786) (#13787)

- CHANGELOG.md
- modules/lang-painless/src/test/java/org/opensearch/painless/WhenThingsGoWrongTests.java
- modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/17_update_error.yml
- server/src/main/java/org/opensearch/script/Script.java
- server/src/main/java/org/opensearch/script/UpdateScript.java
Backport [`194005e`](https://github.com/opensearch-project/OpenSearch/commit/194005ebcaf79cf4f0f9fecd96d4b9e90ca9d1c0) from #13885.
> [Backport 2.x] Painless: ensure type "UnmodifiableMap" for params

- server/src/main/java/org/opensearch/index/mapper/FieldTypeInference.java
- server/src/test/java/org/opensearch/index/mapper/FieldTypeInferenceTests.java
This class performs type inference by analyzing the _source documents. This will be useful in inferring the type of nested derived field of object type. See https://github.com/opensearch-project/OpenSearch/issues/13143 for more details on requirement. 
It uses a random sample of documents to infer the field type, similar to dynamic mapping type guessing logic. Unlike guessing based on the first document, where field could be missing, this method generates a random sample to make a more accurate inference. This approach is especially useful for handling missing fields, which could be common in nested fields within derived fields of object types.
The sample size should be chosen carefully to ensure a high probability of selecting at least one document where the field is present. However, …
> [Derived Field] Dynamic FieldType inference based on random sampling of documents

- server/src/main/java/org/opensearch/index/mapper/DerivedField.java
- server/src/main/java/org/opensearch/index/mapper/FieldTypeInference.java
- server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
- server/src/test/java/org/opensearch/index/mapper/FieldTypeInferenceTests.java
- server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
Introduces object type definition and following settings - 
```json
<field>: <type>
},
"source_indexed_field": <field_name>
"format": <date-format>
"ignore_malformed": <boolean>
```
`source_indexed_field`: This indexed field should be of type `text` and will be used to filter documents in 2 phased iterator approach before executing the  expensive `DerivedFieldQuery` fetching from source, running script, deriving value, creating memory index. This is to improve the performance for `object` type. 
`properties`: fieldname and field type can be specified explicity to avoid inferring the type of sub fields within object type.
`format`:  date format to be used when type is inferred. Unrelated to object type and applicable to date type for both nested and non-nested fields. …
> [DerivedField] object type support in mappings and new settings for derived field 

- build.gradle
- gradle.properties
- settings.gradle
The Gradle Enterprise plugin has been rebranded as the Develocity Plugin, resulting in a number of settings being deprecated. This commit updates the settings per [this migration guide][1] and removes all warnings from the build.
The following warnings are no longer present after this change:
```
WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin. Run with '-Ddevelocity.deprecation.captureOrigin=true' to see where the deprecated functionality is being used. For assistance with migration, see https://gradle.com/help/gradle-plugin-develocity-migration.
- The deprecated "gradle.enterprise.testretry.enabled" system property has been replaced by "develocity.testretry.enabled"
- The "com.gradle.enterprise" …
```
> Update gradle config for develocity rebranding

- .github/workflows/dco.yml
Looks like the DCO app issue may take some time to get fully fixed https://github.com/dcoapp/app/issues/211#issuecomment-2146301930, for temporary fix we can use  https://github.com/tim-actions/dco to run the DCO checks. We have used this in past for job-scheduler repo https://github.com/opensearch-project/job-scheduler/tree/1.3.16.0/.github/workflows, this should unblock the open PR's with mandatory DCO branch rule.
- Resolves https://github.com/opensearch-project/OpenSearch/issues/13964
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md# …
> Add DCO workflow until dcoapp/app issue is fixed

- build.gradle
- gradle.properties
- settings.gradle
Backports e3d7e9988b643173babe0fbb82a31fe6c6c1eb86 from #13942 to 2.x
> [Backport 2.x] Update gradle config for develocity rebranding (#13942)

- .github/workflows/assemble.yml
Another attempt to stabilize MacOS GA runner caused by QEMU / Colima / Docker issues
N/A (multiple pull request check are failing sporadically)
> Another attempt to stabilize MacOS GA runner caused by QEMU / Colima / Docker issues

- qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/ClusterStateIT.java
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
- server/src/main/java/org/opensearch/cluster/metadata/TemplatesMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/da3ab920fcd0f6a8f5dbfad5c87740261f355f14, 2e497436cf9dd78aa3d06f86285aef897c962cac from https://github.com/opensearch-project/OpenSearch/pull/12190, #13869
> [Backport 2.x] Split the remote global metadata file to metadata attribute files

- modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheIT.java
- modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolder.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
- server/src/internalClusterTest/java/org/opensearch/indices/CacheStatsAPIIndicesRequestCacheIT.java
- server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
- server/src/main/java/org/opensearch/common/cache/service/NodeCacheStats.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
Adds more ITs and UT coverage for cache stats in the tiered spillover cache. Also has 3 small bugfixes which were found during testing: 
- Cache clear API incorrectly wiped hits, misses, and eviction stats 
- Items evicted from the heap tier, but rejected from the disk tier due to policies, incorrectly weren't counted towards the total evictions for the cache
- `request_cache` object in XContent response for the cache stats API was incorrectly at nodes.[node_id].request_cache instead of nodes.[node_id].caches.request_cache
Resolves https://github.com/opensearch-project/OpenSearch/issues/13455 …
> [Backport 2.x] [Tiered Caching] Additional ITs for cache stats 

- CHANGELOG.md
- client/rest/src/main/java/org/opensearch/client/Request.java
- client/rest/src/main/java/org/opensearch/client/RequestOptions.java
- client/rest/src/test/java/org/opensearch/client/RequestOptionsTests.java
Allows adding query parameters to RequestOptions, e.g. to be able to set `?filter-path=<something>` as documented in https://opensearch.org/docs/2.3/opensearch/common-parameters/#filtered-responses.
This is the same PR as #13777, but targeting the 2.x branch.
Resolves #13776.
> [Backport 2.x] 13776: allow adding query parameters to RequestOptions

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search/50_multi_match.yml
- server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/GreaterThanAssertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/GreaterThanEqualToAssertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/LessThanAssertion.java
- test/framework/src/main/java/org/opensearch/test/rest/yaml/section/LessThanOrEqualToAssertion.java
Manual backport of #13829
Under specific circumstances, when using `cross_fields` scoring on a `multi_match` query, we can end up with negative scores from the inverse document frequency calculation in the BM25 formula.
Specifically, the IDF is calculated as:
```
log(1 + (N - n + 0.5) / (n + 0.5))
```
where `N` is the number of documents containing the field and `n` is the number of documents containing the given term in the field. Obviously, `n` should always be less than or equal to `N`.
Unfortunately, `cross_fields` makes up a new value for `n` and tries to use it across all fields.
This change finds the (nonzero) value of `N` for each field and uses that as an upper bound for the new value of `n`.
---------
Signed-off-by: Michael Froh …
> [Backport 2.x] Fix negative scores returned from `multi_match` query with `cross_fields` 

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/common/util/concurrent/AbstractAsyncTask.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Adding b9befaa12524744ffe71d3f12699cb27cb8fca5e added in #13131 back, we are now using dedicated threadpool `remote_purge` for deletion of stale files. 
Ran the test for 1000 times locally to check for flakiness
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.gateway.remote.RemoteClusterStateCleanupManagerIT.testRemoteCleanupDeleteStale" -Dtests.iters=1000 -Dtests.timeoutSuite=6000000!
> Configure project :
========================= WARNING =========================
Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173
===========================================================
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 8.7
OS Info               : Mac OS X …
```
> Optimize remote state stale file deletion

- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Adding checks in `RemoteStoreRefreshListener` to return false for `shouldSync` if the underlying indexShard instance has transitioned to a `CLOSED` state. This would prevent the `shouldRetry` method to schedule refresh retries even after the `IndexShard` instance and it's corresponding Remote directories are closed.
https://github.com/opensearch-project/OpenSearch/issues/13996
> [Remote Store] Add checks to skip remote uploads  after shard is closed

- gradle/ide.gradle
Description:
Replaced CONTRIBUTING.md with DEVELOPER_GUIDE.md
Resolves #13984
> A documentation issue, used CONTRIBUTING.md instead of DEVELOPER_GUIDE.md

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
We introduced ability to run flush automatically based on the number of accumulated translog readers. With this PR, we are `-1` as a permissible value for the setting `cluster.remote_store.translog.max_readers` which would disable this feature.
This is needed to prevent repeated flushes when a large number of translog files get accumulated, especially when a shard copy is relocating to another node and the active primary is getting large number of writes. This also helps during the remotestore migration when the remote seeding process ends up accumulating a lot of translog on the active primary which needs to be replayed after the seeding process is complete. …
> [Remote Store] Add support to disable flush based on translog reader count

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
- server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/SourceFieldMapperTests.java
This change will add the capability where a user can disable the recovery_source, just like user can disable source. Disabling of `_recovery_source` can be done per field by mentioning the field names too in includes and excludes.
```
PUT my-index
{
"settings": {
"index": {
"number_of_shards": 3,
"refresh_interval": "1s"
}
},
"mappings": {
"_source": {
"enabled": false,
"recovery_source_enabled": false
},
"title": {
"type": "text"
}
}
}
}
```
Resolves #13490
Related Issue: https://github.com/opensearch-project/k-NN/issues/1599 …
> Add capability to disable source recovery_source for an index

- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
During remote store migration , we need to update remote store backed replica's checkpoint to the primary . 
Resolves https://github.com/opensearch-project/OpenSearch/issues/13889 
> [Remote Migration] Update checkpoint from remote nodes replicas

- CHANGELOG-3.0.md
- buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
- distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
- gradle/ide.gradle
- server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
- server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
This reverts commit ba0df742037b49dc8c85efcf9ccec98fd3a1d69d.
Reverting https://github.com/opensearch-project/OpenSearch/pull/13988 due to new flaky tests:
```
org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns
Expected: "2019-01-01T01:01:01.001UTC"
but: was "2019-01-01T01:01:01.001م ع و"
at __randomizedtesting.SeedInfo.seed([D64AD5330C8A32D4:38C13EFEC3AE978C]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:964)
at org.junit.Assert.assertThat(Assert.java:930)
at org.opensearch.common.joda.JavaJodaTimeDuellingTests.testIncompatiblePatterns(JavaJodaTimeDuellingTests.java:189)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103 …
```
> Revert "COMPAT locale provider will be removed in a future release (#13988)"

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/terms/StringTermsIT.java
- server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java
Fixes a bug where `postCollection` would be called twice when a `MultiBucketCollector` is present. This was resulting in double counting the docs in the last segment for deferred bucket collectors.
Resolves #14000 
> Fix double invocation of postCollection when MultiBucketCollector is present

- CHANGELOG.md
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/AbstractExporter.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/DebugExporter.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporter.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporter.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactory.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/SinkType.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/package-info.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/DebugExporterTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporterTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactoryTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
This PR implements generic query insights exporters to export insights data into local index and debug log. Also added the export functionality for top n queries service with related configuration endpoints.
Resolves #11296 
> Query insights exporters implementation

- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java
- server/src/main/java/org/opensearch/index/mapper/DerivedField.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldResolver.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldResolverFactory.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
- server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
- server/src/main/java/org/opensearch/index/mapper/NoOpDerivedFieldResolver.java
- server/src/main/java/org/opensearch/index/mapper/ObjectDerivedFieldType.java
- server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
- server/src/main/java/org/opensearch/index/query/QueryShardContext.java
- server/src/main/java/org/opensearch/index/query/VectorGeoPointShapeQueryProcessor.java
- server/src/main/java/org/opensearch/index/search/QueryParserHelper.java
- server/src/main/java/org/opensearch/script/DerivedFieldScript.java
- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightPhase.java
- server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldResolverTests.java
- server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
- server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
- server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
- server/src/test/java/org/opensearch/search/SearchServiceTests.java
- server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
- server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
Support DerivedField object type and integration with Mapper and DerivedField query
* Adds ValueFetcher for DerivedField of object type to parse and fetch nested fields.
* DerivedFieldResolver to resolve DerivedField type on the fly. And `DerivedFieldResolverFactory` to decide between `NoOp` and `Default` implementation.
* Introduction of new support types - `text`, `float` and `object`.
* Use index analyzer for derived fields set in index settings.
* Integrations of properties  - `source_indexed_field`, `properties`, `format `, `ignore_malformed ` introduced in https://github.com/opensearch-project/OpenSearch/pull/13717 to make them functional. 
* Support of derived fields from query string
* Disable feature when allow_expensive_query is set to false.
* Index and cluster level setting …
> [DerivedField] Support DerivedField object type and integration with Mapper

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
Backporting https://github.com/opensearch-project/OpenSearch/pull/14027 to `2.x`
> [Backport 2.x] [Remote Store] Add support to disable flush based on translog reader count

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/cache/Cache.java
- server/src/main/java/org/opensearch/common/cache/RemovalListener.java
Cache currently sends sync removal notifications under a global LRU lock. These removal notifications are then consumed by clients to either update stats(eg: RequestCache) or put the evicted item onto disk cache(in TieredCache).
Doing this under a global lock can make other threads(via get/put calls) wait to get this lock released in case removal notification calls are expensive. So doing this outside lock makes more sense and its non harmful.
Resolves https://github.com/opensearch-project/OpenSearch/issues/14016 …
> [Caching] Move cache removal notifications outside lru lock

- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
Reverts opensearch-project/OpenSearch#13888 
This PR introduced flaky tests that block a lot of 2.15 release items. Reverting it now.
Details:
https://github.com/opensearch-project/OpenSearch/issues/14055
> Revert "[Remote Migration] Update checkpoint from remote nodes replicas"

- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
During remote store migration , we need to update remote store backed replica's checkpoint to the primary .
Also marking multiple `Remote Store Migrations` flaky tests as `AwaitsFix` to unblock the builds. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/13889
> Update checkpoint from remote nodes replicas (#13888)

- CHANGELOG.md
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
- server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
- server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
Manual backport PR for  https://github.com/opensearch-project/OpenSearch/pull/13374
(cherry picked from commit 9d3cf43e7f06d2011c931cf829439e9fba97f18d)
> [Backport 2.x] Add X-Opaque-Id to search request metadata for query insights (#13374)

- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
These are very frequent offenders and are causing a lot of pain in CI.
Related issues:
- https://github.com/opensearch-project/OpenSearch/issues/11374
- https://github.com/opensearch-project/OpenSearch/issues/12308
- https://github.com/opensearch-project/OpenSearch/issues/13540
- https://github.com/opensearch-project/OpenSearch/issues/13503
- https://github.com/opensearch-project/OpenSearch/issues/13711
- https://github.com/opensearch-project/OpenSearch/issues/13949
- https://github.com/opensearch-project/OpenSearch/issues/13437
- https://github.com/opensearch-project/OpenSearch/issues/13600 …
> Mute all flaky IndicesRequestCacheIT tests

- server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableBlobEntity.java
- server/src/main/java/org/opensearch/common/remote/BlobPathParameters.java
- server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityStore.java
- server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntity.java
- server/src/main/java/org/opensearch/common/remote/package-info.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
- server/src/main/java/org/opensearch/gateway/remote/model/package-info.java
* Remote Writable Entity interfaces
Backport https://github.com/opensearch-project/OpenSearch/commit/156eca3433ee0910f7fc21340f0052ada7e7533e from https://github.com/opensearch-project/OpenSearch/pull/13785
(cherry picked from commit 156eca3433ee0910f7fc21340f0052ada7e7533e)
> [Backport 2.x] Remote state interfaces  (#13785)

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
(cherry picked from commit 3de5d3c273e744a76459c88f3a6341ed3173f5a0)
Backport 3de5d3c2 from #13995 
> [Backport 2.x] Optimize remote state stale file deletion (#13995)

- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
- server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
- server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
- server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
Add method in BlobStoreTransferService to upload blob using input stream
NA
> Upload blob from input stream

- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
- server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
- server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
- server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
* Blobstore transfer of cluster metadata from the underlying input stream
Backport https://github.com/opensearch-project/OpenSearch/commit/05af414bb0a4bfe8c3fccd67bb2dd45694a92fe0 from https://github.com/opensearch-project/OpenSearch/pull/13836
> [Backport 2.x] Upload blob from input stream

- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
Backport b06d0b93b7565c577e6e141967defac3dd888696 from #14062.
> [Backport 2.x] Update checkpoint from remote nodes replicas (#13888) (#14062)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
- server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
Make recovery action retry timeout configurable #14022 
> [Backport 2.x] Make recovery action retry timeout configurable (#14022)

- server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityStore.java
- server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntity.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadata.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadataTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadataTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadataTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadataTests.java
Backport 49282c111c593bb2b1ee76b50102c06fa1f2c627 from #13834
> [Backport 2.x] Implementation of RemoteWritableEntity for objects to uploaded to remote store

- server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobContainer.java
- server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobStore.java
- server/src/test/java/org/opensearch/common/blobstore/EncryptedBlobContainerTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreCustomMetadataResolverTests.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
Implement missing methods IsBlobMetadataEnabled(), readBlobWithMetadata() for EncryptedBlobStore and EncryptedBlobContainer.  These methods were introduced as part of https://github.com/opensearch-project/OpenSearch/issues/13091 …
> Implement missing methods for EncryptedBlobStore and EncryptedBlobContainer

- CHANGELOG.md
- server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
- server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
- test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Backport https://github.com/opensearch-project/OpenSearch/commit/66df9303f7979cdb0ee6d4e3073c41883f22b5cb from https://github.com/opensearch-project/OpenSearch/pull/13710.
> [Backport 2.x] De-duping shards in ShardsBatchGatewayAllocator based on ShardId inst… #13775

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/ResizeIndexMigrationTestCase.java
- server/src/main/java/org/opensearch/cluster/ClusterModule.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
- server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
- server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java
Move Remote Store Migration from DocRep to GA and update migration setting names. 
- [] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
> Move Remote Store Migration from DocRep to GA

- server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
- server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java
- server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
Current implementation to inject headers in thread context caused concurrent modification errors since other threads can access the headers at the same time when we delete it. 
```
java.lang.AssertionError: Unexpected ShardFailures: [shard [[6aZksFMiT4WtFkh9Ni-mog][test][7]], reason [RemoteTransportException[[node_t2][127.0.0.1:35247][indices:data/read/search[phase/query/id]]]; nested: NotSerializableExceptionWrapper[concurrent_modification_exception: null]; ], cause [NotSerializableExceptionWrapper[concurrent_modification_exception: null]
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
at java.util.HashMap$EntryIterator.next(HashMap.java:1638)
at java.util.HashMap$EntryIterator.next(HashMap.java:1636)
at org.opensearch.common.util.concurrent.ThreadContext$ThreadContextStruct …
```
> fix concurrent modification exceptions in thread context

- libs/core/src/main/java/org/opensearch/core/compress/CompressorRegistry.java
- server/src/main/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormat.java
- server/src/test/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormatTests.java
Create a class which will serialize and deserialize classes extending Writable interface. This class handles the checksum logic as well.
NA
> Create serde utility for Writable classes

- server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
- server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
- server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
- server/src/main/java/org/opensearch/cluster/coordination/RemotePublishRequest.java
- server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
- server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
- server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateManifestInfo.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
- server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
- server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
- server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
- server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
* Add remote state publication transport call
Backport b769292fe98725d7178b2614a216c1c85f171ad0 from https://github.com/opensearch-project/OpenSearch/pull/13835
> [Backport 2.x]Add remote state publication transport call (#13835)

- CHANGELOG.md
- libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistry.java
- libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/MetricsRegistry.java
- libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/TaggedMeasurement.java
- libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/noop/NoopMetricsRegistry.java
- libs/telemetry/src/test/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistryTests.java
- plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/TelemetryMetricsEnabledSanityIT.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetry.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetryTests.java
- server/src/test/java/org/opensearch/telemetry/TestInMemoryMetricsRegistry.java
- test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
> [Backport-13994] Adds support to provide tags with value in Gauge metric

- CHANGELOG.md
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactory.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/MetricType.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesAction.java
- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecordTests.java
This is a follow up on https://github.com/opensearch-project/OpenSearch/pull/13172/files#diff-916410426108bbd0b06952c34490ca05c7a2a78c1c10f7af28e88ead23a70f24 to consume query level cpu and memory usage in query insights
https://github.com/opensearch-project/OpenSearch/issues/12399
> consume query level cpu and memory usage in query insights

- server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
- server/src/main/java/org/opensearch/index/query/QueryShardContext.java
There were breaking changes introduced in https://github.com/opensearch-project/OpenSearch/pull/14105
> Fix the breaking change check due to Derived fields changes in 2.15

- .github/workflows/dco.yml
- CHANGELOG.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/14126 to `2.x`
> [Backport] [2.x] Bump tim-actions/get-pr-commits from 1.1.0 to 1.3.1 (#14126)

- server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
- server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
There are breaking changes introduced in https://github.com/opensearch-project/OpenSearch/pull/14084/files. 
> fix japicmp check for threadContext

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
- modules/opensearch-dashboards/src/main/java/org/opensearch/dashboards/OpenSearchDashboardsModulePlugin.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpChunk.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpRequest.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingHttpChannel.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingRequestConsumer.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingResponseProducer.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/StreamingHttpContentSender.java
- plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorHttpClient.java
- plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportStreamingTests.java
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/main/java/org/opensearch/common/xcontent/support/XContentHttpChunk.java
- server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
- server/src/main/java/org/opensearch/http/DefaultRestChannel.java
- server/src/main/java/org/opensearch/http/DefaultStreamingRestChannel.java
- server/src/main/java/org/opensearch/http/HttpChunk.java
- server/src/main/java/org/opensearch/http/HttpServerTransport.java
- server/src/main/java/org/opensearch/http/HttpTracer.java
- server/src/main/java/org/opensearch/http/StreamingHttpChannel.java
- server/src/main/java/org/opensearch/rest/BaseRestHandler.java
- server/src/main/java/org/opensearch/rest/RestController.java
- server/src/main/java/org/opensearch/rest/RestHandler.java
- server/src/main/java/org/opensearch/rest/StreamingRestChannel.java
- server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
- server/src/test/java/org/opensearch/rest/action/document/RestBulkStreamingActionTests.java
Enhance RestAction with request / response streaming support
Closes https://github.com/opensearch-project/OpenSearch/issues/9071
> [Streaming Indexing] Enhance RestAction with request / response streaming support

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
- server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/SourceFieldMapperTests.java
Backport of the PR: https://github.com/opensearch-project/OpenSearch/pull/13590
NA
> [Backport 2.x] Add capability to disable source recovery_source for an index (#13590)

- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Pass correct names for snapshot indices
> Use correct names for snapshot indices while updating remote store index settings

- server/src/main/java/org/opensearch/cluster/DiffableUtils.java
- server/src/main/java/org/opensearch/cluster/metadata/DiffableStringMap.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteStateTransferException.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteReadResult.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadata.java
- server/src/test/java/org/opensearch/cluster/block/ClusterBlockTests.java
- server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterBlocksTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustomsTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettingsTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadataTests.java
backport a9d20502ae84148f564da33a82b13ba0f60ec8ac from #14006
> [Backport 2.x] Add POJO classes required for cluster state publication from remote (#14006)

- CHANGELOG-3.0.md
- client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
- client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
Java high-level REST client bulk() is not respecting the bulkRequest.requireAlias(true) method call
Resolves #12958 
> Java high-level REST client bulk() is not respecting the bulkRequest.requireAlias(true) method call

- TRIAGING.md
A couple weeks ago in the core triage meeting we discussed scoping the "untriaged" issue search to component-specific areas, giving each respective component meeting the responsibility to triage new issues. I think it is easier to discuss this change via a PR update to the document that defines this process, so I'm doing that here as opposed to creating an issue. I will not merge this change until I get consensus from all component meeting owners (since they will be taking on a new responsibility here).
/cc @reta @dblock @shwetathareja @Bukhtawar 
---
We have expanded beyond the single "core" triage meeting, but so far the core meeting has looked at all issues. This PR proposes an update to the procedure so that the component-specific meetings now have the responsibility for addressing …
> Define component-based triage meetings

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search/270_wildcard_fieldtype_queries.yml
- server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
- server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
- server/src/main/java/org/opensearch/indices/IndicesModule.java
- server/src/test/java/org/opensearch/index/mapper/WildcardFieldMapperTests.java
- server/src/test/java/org/opensearch/index/mapper/WildcardFieldTypeTests.java
This adds support for the "wildcard" field type that supports efficient execution of wildcard, prefix, and regexp queries by matching first against trigrams (or bigrams or individual characters), then post-filtering by evaluating the original field value against the pattern.
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/13461
> [Backport 2.x] Add support for wildcard field type (#13461)

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
- client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
Backport of  https://github.com/opensearch-project/OpenSearch/pull/14146 to `2.x`
> [Backport] [2.x] Java high-level REST client bulk() is not respecting the bulkRequest.requireAlias(true) method call

- server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Delete stale index routing files. 
Related Issues
Resolves #14162 
Check List
- ~[ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
- ~[ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#changelog))~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate- …
> Delete stale index routing files.

- server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/4c252570ada31ee0b477bb2a09fc84c081598900 from https://github.com/opensearch-project/OpenSearch/pull/13909.
> [Backport 2.x]Delete stale index routing table files resolves #14162 (#13909)

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/search/DefaultSearchContext.java
- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/metrics/InternalCardinality.java
- server/src/main/java/org/opensearch/search/internal/SearchContext.java
- server/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Backport #13821 Manually
The only conflict is in change log.
Resolves #11959
> [Backport 13821] Support Dynamic Pruning in Cardinality Aggregation

- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml
Failed 3 times in gradle check after merging in the change on [5/2](https://github.com/opensearch-project/OpenSearch/pull/13317) [Metric Dashboard Link](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-6M,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2e729590-eb26-11ee-b008-6583d3dd450c',key:test_class,negate:!f,params:(query:ClientYamlTestSuiteIT),type:phrase),query:(match_phrase:(test_class:ClientYamlTestSuiteIT)))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:lucene,query:'test_name:%20*filter*rewrite*info*'),timeRestore:!t,title:'OpenSearch%20Gradle%20Check%20Report',viewMode:view)) …
> [Flaky Test] Set refresh interval to -1 to only have 1 segment

- server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
- server/src/main/java/org/opensearch/search/query/QueryPhase.java
Make sure processPostCollection is still called when early termination kicks in.
Resolves #14198
> Make sure processPostCollection is called in case of early termination

- server/src/main/java/org/opensearch/cluster/RepositoryCleanupInProgress.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
- server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
- server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
- server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
- server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
* Read and write ephemeral objects for remote publication
Backport of #14089
> [Backport 2.x] Read write ephemeral objects for remote publication of cluster state

- CHANGELOG.md
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Fixes issue where request cache tries to clean up entries for deleted indexShard and throws ShardNotFoundException. 
The fix is around returning null in case indexShard is not present and handling it accordingly.
Ran the muted IT tests separately.
Resolves https://github.com/opensearch-project/OpenSearch/issues/14190
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) …
> Fix ShardNotFoundException during request cache clean up

- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
We need to update the version check from `StreamInput` and `StreamOutput` for `ClusterMetadataManifest` as the changes have been backported to 2.15.
> Update version for ClusterMetadataManifest after 2.15 backport

- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
This reverts commit fbe048f2eaaddf0bcb4cf0f07009fff155140b01. Muting these tests was only intended to be temporary to unblock the 2.15 release.
> Revert "Mute all flaky IndicesRequestCacheIT tests (#14077)"

- server/src/main/java/org/opensearch/index/query/SourceFieldMatchQuery.java
- server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Using `indexSearcher.rewrite(delegateQuery)` instead of `delegateQuery.rewrite(indexSearcher);`  can have side effects when `profile` is set to true, as it can start reusing the profile objects created in parent query and can interfere with timers if they were already started. Whereas,` query.rewrite(indexSearcher)` it just uses the lucene APIs and doesn't use the wrapped functionality in OpenSearch. 
In query phase, when rewrite is called
https://github.com/opensearch-project/OpenSearch/blob/5ff50a7e00698b0f448bc4840461c8518500d591/server/src/main/java/org/opensearch/search/query/QueryPhase.java#L127
the `ContextIndexSearch` will start the timer for the query and will start noting the `rewrite()` time for all clauses in the clauses for the complete query tree. 
But if we try to use …
> Fix the rewrite method for MatchOnlyText field query

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.15.0.md
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
https://github.com/opensearch-project/OpenSearch/issues/14032 reported msearches failing with a Concurrent Modification Exception, though they were not able to repro it consistently they were able to attach a debugger and find out the line throwing the exception, which was https://github.com/opensearch-project/OpenSearch/blob/5b93f2e429996f6324248cb0bc5e2dd3a2150dbb/server/src/main/java/org/opensearch/indices/IndicesRequestCache.java#L571
We are using a HashMap (not thread safe) for the inner map of the cleanupKeyToCountMap and hence it throws a Concurrent Modification Exception when the map is getting updated by multiple threads concurrently. 
The fix is to use a thread safe Concurrent Map instead. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/14032 …
> [Tiered Caching] [Bug Fix] Use concurrentMap instead of HashMap to fix Concurrent Modification Exception

- release-notes/opensearch.release-notes-2.15.0.md
Add the match_only_text rewrite fix to release notes 
Resolves https://github.com/opensearch-project/OpenSearch/issues/14156
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cert …
> Add the match_only_text rewrite fix to release notes

- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
Fix sleep time bug during remote store sync . Instead of sleeping for 30 sec, it was sleeping for 30ms unintentionally. This would waste unnecessary CPU cycles and context switches. 
> [Remote Store] Fix sleep time bug during remote store sync

- server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
- server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
- server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
- server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
- server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
This change fixes issues shard allocation in batch batch. Changes in the PR :
1.   Move decision evaluation and execution of decision together for each unassigned shard of a batch to ensure the cluster state is updated before we make decision for another shards
2.  In-order to correctly handle cases where shards have multiple unassigned replicas, evaluation and decisions execution will be done for all replica shards of a shard if the shard is part of the batch that needs to be allocated. This is required as our batches will contain only one entry per shard id. 
Resolves #13702, #13962 …
> Fix unassigned shard allocation for batch mode

- server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
Fix sleep time bug during remote store sync . Instead of sleeping for 30 sec, it was sleeping for 30ms unintentionally. This would waste unnecessary CPU cycles and context switches. 
>  [Remote Store] Fix sleep time bug during remote store sync 

- .github/ISSUE_TEMPLATE/failed_check.md
- .github/workflows/gradle-check.yml
Remove this job `Create Issue On Push Failure` from workflow as we have an automation to detect the Gradle Check flaky failures and auto create an issue. 
Related Jenkins job: https://build.ci.opensearch.org/job/gradle-check-flaky-test-detector 
Library Used: `gradleCheckFlakyTestChecker`
Library Code: https://github.com/opensearch-project/opensearch-build-libraries/pull/436
The AUTOCUT issues created: [link](https://github.com/issues?q=is%3Aissue+label%3Auntriaged+repo%3Aopensearch-project%2Fopensearch+%5BAUTOCUT%5D+Gradle+Check+Flaky+Test+Report+for+in%3Atitle)
Part of https://github.com/opensearch-project/OpenSearch/issues/13950 …
> Update Gradle check workflow to remove the `Create Issue On Push Failure` section.

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteReadResult.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterBlocksTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustomsTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
We see that Cleanup interval setting set before the might not be applied before the interval for assert is over.
Added a check to ensure that setting is updated before checking if files are deleted.
Further, addressing some bugs found after merging #14089 
- Addressing a bug in `getManifestCodecVersion` where if path for files have Delimiter `__` we are throwing an error. 
- Changed that expected object in RemoteReadResult to move away from XContent, as this was decided in #13576 but not updated in #14006
Ran the test 1000 times to ensure that flakiness is not there now.
Resolves #14205
Resolves #13968 …
> Fix flakiness of testRemoteCleanupDeleteStale, bug fix in RemoteMetadataManifest and RemoteReadResult

- server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
- server/src/main/java/org/opensearch/ingest/IngestService.java
- server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
This is to fix a document incorrect order bug with batch ingestion when some docs run into exception.
bug is described here: https://github.com/opensearch-project/OpenSearch/issues/14336
the integration test here https://github.com/opensearch-project/OpenSearch/pull/14335 was also added. 
**Skip changelog** and **backport to 2.x**
- https://github.com/opensearch-project/OpenSearch/issues/14336
- https://github.com/opensearch-project/OpenSearch/pull/14335
> [Bugfix] Fix incorrect document order when there's exception during batch ingest 

- CHANGELOG.md
- buildSrc/build.gradle
Bump org.wiremock:wiremock-standalone from 3.3.1 to 3.6.0
N/A
> Bump org.wiremock:wiremock-standalone from 3.3.1 to 3.6.0

- CHANGELOG-3.0.md
- buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
- distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
- gradle/ide.gradle
- server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
- server/src/test/java/org/opensearch/common/joda/JavaJodaTimeDuellingTests.java
- server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
Description:
From JDK21 onwards a new warning has started to come, "WARNING: COMPAT locale provider will be removed in a future release". So, we have to avoid usage of COMPAT provider. We were setting exlpicitly to COMPAT locale provider in couple of places, this change is to convert COMPAT to CLDR locale provider. After this change, couple of tests started to fail becasue some locale data has minor changes in CLDR compared to COMPAT. For example, day and month short names of GERMAN "de" locale are different in CLDR and COMPAT, just need to add a . in the end for CLDR.
Resolves #11550 …
> COMPAT locale provider will be removed in a future release

- server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
The problem is that this test would decommission one of six nodes. The tear down logic of the test would attempt to assert on the health of the cluster by randomly selecting a node and requesting the cluster health. If this random check happened to select the node that was decommissioned, then the test would fail. The fix is to recommission the node at the end of the test.
Also, the "recommission node and assert cluster health" logic was used in multiple places and could be refactored out to a helper method.
Resolves #14290
Resolves #12197 …
> Fix AwarenessAttributeDecommissionIT.testConcurrentDecommissionAction

- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
This PR addresses the following:
- Cluster state customs should only be uploaded when remote publication is enabled.
- All metadata customs when remote publication is enabled while customs with context as GATEWAY should be uploaded otherwise
- simplify the logic of computing the updated customs
- Fix bug where metadata customs map was being used to remove cluster state customs to be deleted.
- Close input stream while reading blob
NA
> Use remote publication flag to decide which custom objects to upload

- server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
- server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
- server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
- server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
- server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/18c5bb6cd57192ea1bb5cbc772814fa0443659fe from https://github.com/opensearch-project/OpenSearch/pull/13748
> Fix unassigned batch allocation (#13748) (#13748)

- CHANGELOG.md
- buildSrc/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/14361 to `2.x`
> [Backport] [2.x] Bump org.wiremock:wiremock-standalone from 3.3.1 to 3.6.0 (#14361)

- CHANGELOG.md
- test/fixtures/hdfs-fixture/build.gradle
> [Backport] [2.x] Bump commons-net:commons-net from 3.10.0 to 3.11.1 in /test/fixtures/hdfs-fixture (#14396)

- server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
- server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
This PR is to address undone comments from https://github.com/opensearch-project/OpenSearch/pull/14341
- Skip changelog
- backport to 2.x
https://github.com/opensearch-project/OpenSearch/pull/14341
> Remove one unnecessary test and simply some code in a test

- CHANGELOG.md
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/190_script_processor.yml
- server/src/main/java/org/opensearch/ingest/IngestDocument.java
- server/src/test/java/org/opensearch/ingest/IngestDocumentTests.java
PR #11725 added a new deep copy in the ScriptProcessor flow. If a script uses a Short or Byte data type then this new deep copy introduced a regression. This commit fixes that regression.
However, it appears there has been an existing bug where using a Character type in the same way will fail (this failed before PR 11725). The failure is different, and appears to be related to something deeping in the XContent serialization layer. For now, I have fixed the regression but not yet dug into the failure with the Character data type. I have added a test that expects this failure.
Resolves #14379 …
> Add missing data types to IngestDocument deep copy

- server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
- In `IndexShardTests.testCommitLevelRestoreShardFromRemoteStore`, we index some docs, trigger refresh and induce failure in local store by deleting segment files.
- If subsequent refresh or retry of earlier refresh is triggered while segment deletion or shard.close is in progress, it is possible that the segment file is still being referenced by RemoteStoreRefreshListener.
- To avoid this issue, in this PR, we make sure to acquire permits on RemoteStoreRefreshListener.
- The flaky tests mentioned under Related Issues ran successfully for 5000+ times on local with this change.
- Sample stacktrace from the test failures
```
java.lang.RuntimeException: MockDirectoryWrapper: cannot close: there are still 1 open files: {_0.cfs=1}
at __randomizedtesting.SeedInfo.seed([87AFB01F83317A5B:97D1B6F17 …
```
> Fix flaky test IndexShardTests.testCommitLevelRestoreShardFromRemoteStore

- DEVELOPER_GUIDE.md
Update `DEVELOPER_GUIDE.md` to add `gradle-check-flaky-test-detector` automation information
Part of https://github.com/opensearch-project/OpenSearch/issues/13950
> Update `DEVELOPER_GUIDE.md` to add `gradle-check-flaky-test-detector` automation information

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
@andrross  commented on PR - https://github.com/opensearch-project/OpenSearch/pull/14221/files to use ConcurrentHashMap explicitly instead of ConcurrentMap since ConcurrentHashMap gives stronger guarantees than other  implementations of ConcurrentMap. 
Though Like @sohami  pointed out `ConcurrentCollections.newConcurrentMap();` returns a new ConcurrentHashMap, having stronger type safety will guarantee and safeguard against future changes. 
```java
public static <K, V> ConcurrentMap<K, V> newConcurrentMap() {
return new ConcurrentHashMap<>();
}
``` 
Below is the screenshot of the comment - [link](https://github.com/opensearch-project/OpenSearch/pull/14221/files#r1637249218) …
> [Tiered Cache] Use ConcurrentHashMap explicitly in IndicesRequestCache

- buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
- **Skip ComposeBuild task without docker support.**
When running `./gradlew test` composeBuild task is not skipped on systems without docker cli.
> Remove composeBuild fixture tasks when docker support not found

- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
- In `RemoteMigrationIndexMetadataUpdateIT.testRemoteIndexPathFileExistsAfterMigration` test we validate if remote index path file exists on the migrated index on remote node.
- In test, we are first creating a DocRep cluster with 1 cluster manager , 2 Data nodes. After that we add 1 remote cluster manager node and 2 remote nodes.
- So previously in order to elect remote cluster manager as active master we were terminating docRep cluster manager, due to which we were running into issue `NodeClosedException` when other nodes try to join the cluster.
- To avoid the issue we will be using voting config exclusion to elect the remote cluster manager instead of terminating it.
- With the fix, the flaky test ran for 5500+ iterations without failing locally.
Resolves #13939
- ~[ ] Functionality …
> Fix flaky test : RemoteMigrationIndexMetadataUpdateIT.testRemoteIndexPathFileExistsAfterMigration

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/CommunityIdProcessor.java
This is a follow-up PR for [Add community_id ingest processor](https://github.com/opensearch-project/OpenSearch/pull/12121), the new added class CommunityIdProcessor should be final, but in the original PR we neglected that.
Other main classes of the ingest processors don't have this issue.
This PR should be backported to 2.x branch.
https://github.com/opensearch-project/OpenSearch/issues/2787
> Make the class CommunityIdProcessor final

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/CommunityIdProcessor.java
Backport https://github.com/opensearch-project/OpenSearch/pull/14448 to 2.x branch.
> [Backport 2.x] Make the class CommunityIdProcessor final (#14448)

- .github/CODEOWNERS
- MAINTAINERS.md
Hey @tlfeng! I see you haven't been active in this repository in the recent months. Please let me know if you wish to continue to contribute as a maintainer and I'll close this PR. Please note that as emeritus you can come back to active status at any time. Thanks!
> Move maintainer tlfeng to emeritus

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
- client/rest-high-level/src/test/java/org/opensearch/client/IndicesClientIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/RequestConvertersTests.java
- client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/documentation/SearchDocumentationIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/documentation/SnapshotClientDocumentationIT.java
These non-absolute paths (ie. no leading /) are being passed verbatim to the HTTP request which results in a [technically invalid request start-line](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#request_line) of `GET _render/template HTTP/1.1` which should be `GET /_render/template HTTP/1.1`. OpenSearch itself is lenient and happily serves this request, however in cases of stricter intermediaries such as proxies or load-balances as in Amazon OpenSearch Service, this request ends up denied with a 400 Bad Request.
Ideally this would be solved globally in `RestClient` (#14423) however this in the minimal easily backportable fix for now.
Relates to #14423 
For more …
> Correct RHLC searchTemplate & mtermVectors endpoints to have leading slash

- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheCleanupIT.java
This is a followup to https://github.com/opensearch-project/OpenSearch/pull/14369
and has 3 changes
- use setup_index in the test `testCacheWithInvalidation` to keep it consistent with other tests. 
- Increase refresh interval to rule out flakiness by keeping it way high - `TimeValue.timeValueDays(1)`
- Increase max wait time to 5 iteration cycles of cache cleanup cycles to consider for events like GC stop the world that is out of control and runs long. This would not increase the test run time since the backoff in assertBusy is logarithmic and should return after all the asserts passes.  …
> Make IndicesRequestCacheCleanupIT more robust

- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheCleanupIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Backporting https://github.com/opensearch-project/OpenSearch/pull/14369 from main to 2.x
> [Backport 2.x] Fix Indices Request Cache ITs from flaking and timing out (#14369)

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
- client/rest-high-level/src/test/java/org/opensearch/client/IndicesClientIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/RequestConvertersTests.java
- client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/documentation/SearchDocumentationIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/documentation/SnapshotClientDocumentationIT.java
Backport 9675c4f6ec0d412993ef361bce44a8b789bff27b from #14465 
> [Backport 2.x] Correct RHLC searchTemplate & mtermVectors endpoints to have leading slash (#14465)

- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
We are expecting component name for ClusterState.Custom to be of `cluster-state-custom--<custom_name>`. This was missed during refactoring while PR review and there were no test to catch this change. For tests, I am already working on more tests in #14476.
> [Remote State] Fix component name for ClusterState custom

- TESTING.md
Adjusting the gradle commands for running a single test and running the filtered tests.
According a Gradle [docs](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html#sec:multiproject_build_and_test) for multi modules projects.
Below the screenshots of how it worked on my machine: 
1. Without specifying a module name ❌ 
2. With specifying a module name ✅ 
Resolves #14014
> Adjusting TESTING.md for a single test run

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
- server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
- test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
In #7247, we only snapshot the index metadata if the target index is searchable snapshot, so we don't create shard level snapshot metadata under shard blob container (ie. `snap-{uuid}.dat` blob). But this metadata blob needs to be loaded when getting snapshot status or cloning snapshot. Currently, following exception will be thrown if we call snapshot status api and target snapshot contains searchable snapshot.
```
SnapshotMissingException[[test-repo:test-repeated-snap-0] is missing
]
at org.opensearch.repositories.blobstore.BlobStoreRepository.loadShardSnapshot(BlobStoreRepository.java:3418)
at org.opensearch.repositories.blobstore.BlobStoreRepository.getShardSnapshotStatus(BlobStoreRepository.java:3218)
at org.opensearch.action.admin.cluster.snapshots.status.TransportSnapshotsStatusActio …
```
> Write shard level metadata blob when snapshotting searchable snapshot indexes

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
- client/rest-high-level/src/test/java/org/opensearch/client/IndicesClientIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/RequestConvertersTests.java
- client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/documentation/SearchDocumentationIT.java
- client/rest-high-level/src/test/java/org/opensearch/client/documentation/SnapshotClientDocumentationIT.java
Backport a9d806a6c4fa9b10d1a3344f446134d82dece351 from #14465 / #14480 
> [Backport 2.15] Correct RHLC searchTemplate & mtermVectors endpoints to have leading slash (#14465) (#14480)

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregator.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregatorTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Signed-off-by: kkewwei [kkewwei@163.com](mailto:kkewwei@163.com)
The  aggs result of NestedAggregator with sub NestedAggregator may be not accurately, it depends on the face that the parentDocId > childDocId in search, but it may be wrong.
Resolves #13303
> fix: The  aggs result of NestedAggregator with sub NestedAggregator may be not accurately

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
- server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
- test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
Backports 568c193dd817b76b2f0ca4647bc4e01908db709d from #13190 to `2.x`
@bugmakerrrrrr Please review if you get a chance. There was a conflict I had to resolve in SnapshotShardsService due to some legacy code removal on the main branch.
> [Backport 2.x] Write shard level metadata blob when snapshotting searchable snapshot

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/14416 to 2.x
unsignedLongRangeQuery method now returns MatchNoDocsQuery when lower bound > upper bound
Resolves #14404 
> [Backport 2.x] Optimize UnsignedLong range queries to convert to MatchNoDocsQuery when lower > upper bounds

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
- server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
- server/src/main/java/org/opensearch/action/search/ListPitInfo.java
- server/src/test/java/org/opensearch/action/search/PitTestsUtil.java
- server/src/test/java/org/opensearch/search/CreatePitSingleNodeTests.java
Add ListPitInfo::getKeepAlive() getter
Coming from https://github.com/opensearch-project/spring-data-opensearch/pull/218, we forgot to include the getter for `keepAlive` property.
> Add ListPitInfo::getKeepAlive() getter

- CHANGELOG.md
- server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
- server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
Today, the fs info may report a negative available size, which happens when the following conditions are met:
1. A node has both `data` and `search` roles.
2. Some space is reserved for file cache.
3. The file cache space is being used by other files, primarily local indices files.
Related exception:
```
java.lang.IllegalArgumentException: Values less than -1 bytes are not supported: -1781760b
at org.opensearch.core.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:78) ~[classes/:?]
at org.opensearch.core.common.unit.ByteSizeValue.<init>(ByteSizeValue.java:73) ~[classes/:?]
at org.opensearch.monitor.fs.FsInfo$Path.getAvailable(FsInfo.java:141) ~[classes/:?]
at org.opensearch.cluster.InternalClusterInfoService.fillDiskUsagePerNode(InternalClusterInfoService.java:452) ~[classes/:?]
at …
```
> Fix fs info reporting negative available size

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java
[flaky test](https://build.ci.opensearch.org/job/gradle-check/41269/testReport/junit/org.opensearch.painless/LangPainlessClientYamlTestSuiteIT/test__yaml_painless_derived_fields_30_derived_field_search_definition_Test_derived_field_supported_type_using_search_definition_/) was introduced because of a race condition in derived fields when defined within search request.
Since derived fields are created per `QueryShardContext` and `QueryShardContext` instance can be created multiple times for a search request, there is a race condition hitting [here](https://github.com/opensearch-project/OpenSearch/blob/9da6170fc38653284cfeee0e5c1800d41999ba08/server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java#L194). Since we are reusing the parsing logic of mapper for derived …
> Fix a race condition in Derived Field parsing from search request

- .github/workflows/gradle-check.yml
Use `CODECOV_TOKEN` for `codecov/codecov-action`.
Fixes the error `Error: Codecov token not found. Please provide Codecov token with -t flag.` https://github.com/opensearch-project/OpenSearch/actions/runs/9549676092/job/26319805993. Without the Codecov token, the Codecov report is missing for a few commits. For example, the commit 61dbcd0795c9bfe9b81e5762175414bc38bbcadf in this repository is used in [2.15.0 RC](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.15.0/opensearch-2.15.0.yml#L13C10-L13C50). Codecov report for that commit is missing [here](https://app.codecov.io/gh/opensearch-project/opensearch/commit/61dbcd0795c9bfe9b81e5762175414bc38bbcadf). …
> Use `CODECOV_TOKEN` for `codecov/codecov-action`.

- server/src/internalClusterTest/java/org/opensearch/cluster/allocation/ClusterRerouteIT.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Signed-off-by: kkewwei <kkewwei@163.com>
[BUG] org.opensearch.cluster.allocation.ClusterRerouteIT.testDelayWithALargeAmountOfShards test is flaky.
We can see that the shards are rebalanced back and forth:
https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/gradle-check/runs/41527/nodes/18/steps/32/log/?start=0
We can see from the log：
1. 2024-06-22T23:45:36,760:   node_t0 is shut down.
2. 2024-06-22T23:45:37,042: node_t3 is elected as new cluster manager.
3. 2024-06-22T23:45:49,898: all the indices are green.
4. 2024-06-22T23:45:49,898 ~ 2024-06-22T23:47:39,526: the test8][4] and [test4][4] are rebalanced back and forth.
5. 2024-06-22T23:47:39,526: ensureGreen timed out.
It seems to be a very low probability bug, I tried to reproduce several times, but failed. The …
> [Flaky Test] Fix Flaky Test ClusterRerouteIT.testDelayWithALargeAmountOfShards

- TESTING.md
Add doc for how to debug the OpenSearch cluster when running the rest tests
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#de …
> Add doc for debugging rest tests

- server/src/test/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolderTests.java
Fixes flakiness in DefaultCacheStatsHolderTests.testConcurrentRemoval(). The test previously waited 1 ms after starting the removal of a set of dimensions, then added a set of dimensions back to the stats holder. If the removal took >1 ms, the adding could happen before the removal and an assertion would fail. On my machine I was sometimes able to reproduce the failure when the sleep interval was 0, confirming this was the issue. 
Reworked the test to not rely on Thread.Sleep(), and also to do more concurrent removals. Re-adding the set of dimensions after the removals is not necessary. The test now passes when run 10,000 times on my machine.
Resolves https://github.com/opensearch-project/OpenSearch/issues/14301
~- [N/A] API changes companion pull request …
> [Bugfix] Fix flaky DefaultCacheStatsHolderTests

- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Fixes flaky test.
We had added the logic as part of https://github.com/opensearch-project/OpenSearch/pull/14187 to move query recompute logic outside write lock. We used a `Map<Key, Future>` so that the first thread adds a future to the map, loads the value and rest threads wait on the future via `future.get()`. And then we remove the key from the map from the thread which was responsible to load the value.
After this change `testComputeIfAbsentConcurrently` became flaky and fails in certain scenarios where we expected that the value was loaded only once but in actual it was more than more. This happened in below scenario:
1. Thread 1 puts the future into map `completeableFutureMap` for key A
2. Thread 1 loads the value, takes write lock and puts the value onto onHeap cache. Release the …
> Fix flaky test TieredSpilloverCacheTests.testComputeIfAbsentConcurrently

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java
- modules/ingest-common/src/test/java/org/opensearch/ingest/common/IngestCommonModulePluginTests.java
Add a new static setting that lets an operator choose specific ingest processors to enable by name. The behavior is as follows:
- If the allowlist setting is not defined, all installed processors are enabled. This is the status quo.
- If the allowlist setting is defined as the empty set, then all processors are disabled.
- If the allowlist setting contains the names of valid processors, only those processors are enabled.
- If the allowlist setting contains a name of a processor that does not exist, then the server will fail to start with an IllegalStateException listing which processors were defined in the allowlist but are not installed.
- If the allowlist setting is changed between server restarts then any ingest pipeline using a now-disabled processor will fail. This is the same …
> Add allowlist setting for ingest-common processors

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
- server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
- server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/env/NodeRepurposeCommandTests.java
- server/src/test/java/org/opensearch/node/NodeTests.java
- test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
When a search node starts, a file cache is initialized. The size of the file cache is determined by available space of the local storage and the user's config (`Math.min(capacity, availableCapacity)`). However, this approach can cause a issues. For example, if we have a search node with 100GB local storage and config the file cache to be 80GB, after some time, 90% of the file cache is used. if we then restart the node, the available space may be reduced to just 28GB, which means the file cache will also be reduced to 28GB. This can cause further issues as the fs stats will be adjusted based on the file cache size, leading to wired results.
To address this issue, we can use the total space to calculate the size of file cache. User can config the size to be absolute bytes value or a …
> Fix file cache initialization

- .github/CODEOWNERS
- MAINTAINERS.md
I have nominated, and maintainers have agreed to add Ashish Singh (@ashking94) as a co-maintainer, who kindly accepted.
Ashish is an active contributor of OpenSearch project and has extensively contributed in various [remote-backed storage](https://opensearch.org/blog/remote-backed-storage/) features which has been launched successfully for users, with most of his recent works focused on improving performance, resiliency and scalability of the remote store and it’s interactions. Apart from this, he has proactively contributed to identifying critical bugs, resolving them and improving documentations around the same. Ashish is pretty active in the OpenSearch Storage bi-weekly triages and has consistently exercised sound judgement in triaging and prioritising the issues.
Ashish, has …
> Add Ashish Singh as maintainer

- CHANGELOG.md
- libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
- libs/common/src/test/resources/org/opensearch/common/annotation/processor/InternalApiAnnotated.java
- libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiConstructorAnnotatedInternalApi.java
Allow `@InternalApi` annotation on classes not meant to be constructed outside of the OpenSearch core. Just one of the examples where it is useful is `IndexShard`, it has pretty verbose constructor but the instances of `IndexShard` are not supposed to be created outside of core.
The functionality was already implemented [1] but without proper test cases and usage examples.
[1] https://github.com/opensearch-project/OpenSearch/blob/main/libs/common/src/main/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessor.java#L229
Part of https://github.com/opensearch-project/OpenSearch/issues/13308 …
> Allow @InternalApi annotation on classes not meant to be constructed outside of the OpenSearch core

- CHANGELOG.md
- modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
Add a new static setting that lets an operator choose specific search pipeline processors to enable by name. The behavior is as follows:
- If the allowlist setting is not defined, all installed processors are enabled. This is the status quo.
- If the allowlist setting is defined as the empty set, then all processors are disabled.
- If the allowlist setting contains the names of valid processors, only those processors are enabled.
- If the allowlist setting contains a name of a processor that does not exist, then the server will fail to start with an IllegalStateException listing which processors were defined in the allowlist but are not installed.
- If the allowlist setting is changed between server restarts then any ingest pipeline using a now-disabled processor will fail. This is the …
> Add allowlist setting for search-pipeline-common processors

- CHANGELOG.md
- libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
- libs/common/src/test/resources/org/opensearch/common/annotation/processor/InternalApiAnnotated.java
- libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiConstructorAnnotatedInternalApi.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/14575 to `2.x`
> [Backport] [2.x] Allow @InternalApi annotation on classes not meant to be constructed outside of the OpenSearch core (#14575)

- CHANGELOG.md
- modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
- modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
> [Backport 2.x][Tiered Caching]  Moving query recomputation logic outside of write lock

- CHANGELOG.md
- server/build.gradle
Add @InternalApi annotation to japicmp exclusions
Closes https://github.com/opensearch-project/OpenSearch/issues/13308
> Add @InternalApi annotation to japicmp exclusions

- server/src/test/java/org/opensearch/index/get/GetResultTests.java
There is typo in 'From' part of the method name testFomXContentEmbeddedFoundParsingException in GetResultTests.java class. 'Fom' is changed to 'From'.
Resolves https://github.com/opensearch-project/OpenSearch/issues/14620
> Correct typo in method name

- CHANGELOG.md
- libs/core/src/main/java/org/opensearch/core/xcontent/filtering/FilterPath.java
- libs/core/src/test/java/org/opensearch/core/xcontent/filtering/FilterPathTests.java
Refactoring [FilterPath.parse](https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/core/xcontent/filtering/FilterPath.java#L112-L128) by using an iterative approach instead of recursion.
Based on the following PR: https://github.com/opensearch-project/OpenSearch/pull/12131
Resolves #12067
> Refactoring FilterPath.parse by using an iterative approach instead of recursion.

- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
`String.format` is a relatively expensive operation for concatenating strings. Inside `RemoteStoreMigrationAllocationDecider`,  the function calls to `String.format` stands out as the most resource-intensive operation in terms of latency.
This PR improves the latency of RemoteStoreMigrationAllocationDecider by replacing calls to String.format with more efficient StringBuilder for string concatenation.
For initialising 225K shards on 500 nodes, we are observing an improvement of 31 seconds with above change.
391,940.31 ms
360,279.58 ms …
> Removing String format in RemoteStoreMigrationAllocationDecider

- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
`List.removeAll` is a relatively expensive operation. `LocalShardsBalancer` filtering out remote unassigned shards from local unassigned shards while making relocation decisions. In order to achieve this, it first [filters local unassigned shards](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#L784) from given list of total unassigned shards and then [removes (via removeAll call) this new list of local shards](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#L787) with orignal shards to get list of remote unassigned shards. This issue got introduced due to this …
> Removing unnecessary List.removeAll from LocalShardsBalancer to filter remote search shard from relocation decision

- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/index/IndexService.java
- When an instance of Store is created, a `shardlock` is created which is released on closing the instance of store.
- Currently, we create 2 instances of store for remote store backed indices: `store` and `remoteStore`.
- As there can be only one `shardlock` acquired for a given shard, the lock is shared between `store` and `remoteStore`.
- This creates an issue when we are deleting the index as it results in closing both `store` and `remoteStore`.
- In this PR, we create a different lock for remoteStore. As part of https://github.com/opensearch-project/OpenSearch/issues/13075, we want to move away from keeping 2 store instances.
- To reproduce the issue (without the change in this PR), we need to keep following sequence:
- Refresh Started and increased `store.ref`
- Store.close - will …
> Fix assertion failure while deleting remote backed index

- CHANGELOG.md
- test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Fixes an issue seen in alerting's integTests in https://github.com/opensearch-project/alerting/pull/1584. There is a custom warningHandler, but its not working as expected with the implementation. The test is seeing multiple warnings like this:
```
2> org.opensearch.client.WarningFailureException: method [POST], host [http://127.0.0.1:33063], URI [/_refresh?expand_wildcards=open%2Chidden], status line [HTTP/1.1 200 OK]
Warnings: [this request accesses system indices: [.opendistro-alerting-alert-history-2024.07.03-1], but in a future major version, direct access to system indices will be prevented by default, this request accesses system indices: [.opendistro-alerting-alerts], but in a future major version, direct access to system indices will be prevented by default, this request accesses …
```
> Allow system index warning in OpenSearchRestTestCase.refreshAllIndices

- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
When selecting a node on which shard will be allocated, OpenSearch calculates weight of that shard on every node. [Weight](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L440) of a shard represents comparison of the number of shards on this node to the number of shards that should be on each node on average (both taking the cluster as a whole into account as well as shards per index). Calculating the [average shard per node](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#L128) during weight calculation is a resource-intensive operation. To do this, we [sum up the …
> Offline calculation of total shard across all node and caching it for weight calculation inside LocalShardBalancer

- plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
- plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
Currently the top n size can be set to a negative number. We want to limit top size between 1 and `QueryInsightsSettings.MAX_N_SIZE`.
```
curl -X PUT 'localhost:9200/_cluster/settings' -H 'Content-Type: application/json' -d'
{
"persistent" : {
"search.insights.top_queries.latency.top_n_size" : -1
}
}'
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"illegal value can't update [search.insights.top_queries.latency.top_n_size] from [3] to [-1]"}],"type":"illegal_argument_exception","reason":"illegal value can't update [search.insights.top_queries.latency.top_n_size] from [3] to [-1]","caused_by":{"type":"illegal_argument_exception","reason":"Top N size setting for [latency] should be between 1 and 100, was (-1)"}},"status":400}
``` …
> [bug fix] validate lower bound for top n size

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/ClusterModule.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java
- server/src/main/java/org/opensearch/cluster/metadata/QueryGroupMetadata.java
- server/src/main/java/org/opensearch/search/ResourceType.java
- server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
- server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
- server/src/test/java/org/opensearch/cluster/metadata/QueryGroupMetadataTests.java
- server/src/test/java/org/opensearch/cluster/metadata/QueryGroupTests.java
- server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
- server/src/test/java/org/opensearch/search/backpressure/trackers/NodeDuressTrackersTests.java
Backport PR for original PR: https://github.com/opensearch-project/OpenSearch/pull/13669/
> [Backport 2.x] Adding QueryGroup schema (#13669)

- server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateTestUtils.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
- test/framework/src/main/java/org/opensearch/test/TestClusterStateCustom.java
For newly added flows for write of ephemeral objects and read of all cluster state objects in #14089, the PR lacked in coverage. Adding more tests in this flow.
Removed unused parameter from `getClusterStateUsingDiff` method.
Also, fixed a bug where we were reading transient settings from remote store even if includeEphemeral was sent as false, which is not expected here.
> Add unit tests for read flow of RemoteClusterStateService and bug fix for transient settings

- rest-api-spec/src/main/resources/rest-api-spec/test/search/190_index_prefix_search.yml
This is a follow-up PR for https://github.com/opensearch-project/OpenSearch/pull/10959, we need to update the version check in the yml test file after the original PR is backported to 2.x.
Changelog is not needed, backport to 2.x is needed for this PR.
https://github.com/opensearch-project/OpenSearch/issues/9203
<del>- [ ] Functionality includes testing.</del>
<del>- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.</del>
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.</del> …
> Update version check for the bug fix of match_phrase_prefix_query not working on multiple values and index_prefixes

- server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
Removing unnecessary cast to int in test.
Resolves #14694
> Remove unnecessary cast to int from test

- server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
- server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
PrimaryShardsBatchAllocator and ReplicaShardsBatchAllocator both use list data structure to check if a unassigned shard is a shard from the batch being executed. This is in-efficient way and can make recovery significantly slow for clusters with higher shard count. Using set data structure will be more efficient to have constant performance.
Reroute duration reduced by 14.5 minutes for a cluster with 500K unassigned shards
Performance before fix for reroute:
```
[2024-06-24T17:46:18,646][DEBUG][o.o.c.r.a.AllocationService] [c7b768cc312193a718de31bd65dc23c7] ASF-AS reroute started, unassigned shards: 502366, initializing shards: 0, ignored shards: 0
[2024-06-24T18:04:33,158][DEBUG][o.o.c.r.a.AllocationService] [c7b768cc312193a718de31bd65dc23c7] ASF-AS after primaries before replica, …
```
> Use set for shard routings in batch check.

- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
- server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
ComponentPrefix argument is added in UploadedIndexMetadata class in version 2.15. When upgrading from 2.14, this would break as ComponentPrefix is treated as a mandatory argument which will not be remote state serialized using 2.14 version.
So making this argument as optional
NA
> Add versioning for UploadedIndexMetadata

- CHANGELOG.md
- server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
Backport 17b799697e1dbfe65671531f722a1433e646b1bc from #14722.
> [Backport] [1.3] Fix: update help output for _cat (#14722)

- CHANGELOG.md
- server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
Backport 17b799697e1dbfe65671531f722a1433e646b1bc from #14722.
> [Backport] [1.x] Fix: update help output for _cat (#14722)

- test/fixtures/hdfs-fixture/build.gradle
Fix hdfs-fixture hadoop-minicluster dependencies are not being updated / false positive reports on CVEs
Closes https://github.com/opensearch-project/OpenSearch/issues/14636
> Fix hdfs-fixture hadoop-minicluster dependencies are not being updated / false positive reports on CVEs

- CHANGELOG.md
- server/src/main/java/org/opensearch/indices/SystemIndexRegistry.java
- server/src/main/java/org/opensearch/indices/SystemIndices.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/indices/SystemIndicesTests.java
Adds a method called `matchesPluginSystemIndexPattern` to [SystemIndexRegistry](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/SystemIndexRegistry.java) which was added in a recent [PR](https://github.com/opensearch-project/OpenSearch/pull/14415).
This PR relates to another open [PR](https://github.com/opensearch-project/OpenSearch/pull/14630) which introduces a new mechanism for plugins to switch context outside of an authenticated user context. 
This new method takes a plugin's canonical class name and set of index expressions in as params to determine if the request matches system indices registered to that particular plugin.
This PR also changes the method signature to accept a Set which fits the [security use-case …
> Add matchesPluginSystemIndexPattern to SystemIndexRegistry

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/applicationtemplates/ClusterStateSystemTemplateLoader.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplate.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateLoader.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateMetadata.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateRepository.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesPlugin.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesService.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/TemplateRepositoryMetadata.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/package-info.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/cluster/applicationtemplates/ClusterStateSystemTemplateLoaderTests.java
- server/src/test/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesServiceTests.java
- test/framework/src/main/java/org/opensearch/cluster/service/applicationtemplates/TestSystemTemplatesRepositoryPlugin.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
* SPI for loading ABC templates
* Backport for https://github.com/opensearch-project/OpenSearch/pull/14659
> Backport: SPI for loading ABC templates (#14659)

- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
Set version to 2.15 for determining custom metadata during migration to remote store. 
> Set version to 2.15 for determining metadata during migration to remote store

- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
Forward port of https://github.com/opensearch-project/OpenSearch/pull/14776 to `main`
> [Forwardport] Fix bulk upsert ignores the default_pipeline and final_pipeline when the auto-created index matches the index template

- rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_alias/10_basic.yml
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/14756 to `main`
> [Forwardport] [main] Fix create or update alias API doesn't throw exception for unsupported parameters

- .github/CODEOWNERS
- MAINTAINERS.md
Backport of `https://github.com/opensearch-project/OpenSearch/pull/14796` to `1.3`
> [Backport] [1.3] Add Gao Binlong as maintainer (#14796)

- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
Changing the log level of cluster state publication logs to debug based on comment received on https://github.com/opensearch-project/OpenSearch/pull/14089#discussion_r1682621574
> Change RCSS info logs to debug

- .github/benchmark-configs.json
For configs that use snapshots to restore data, `TEST_PROCEDURE` field has to be set to `restore-from-snapshot` else the run will use workload's default test procedure which does full indexing of data instead of restoring from snapshot.  …
> Add restore-from-snapshot test procedure for snapshot run benchmark config

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/InternalHistogram.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/InternalHistogramTests.java
backport https://github.com/opensearch-project/OpenSearch/pull/14754
> [Backport 2.x] Use circuit breaker in InternalHistogram when adding empty buckets (#14754)

- CHANGELOG.md
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
- server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/e288962d2870efa28b3dc67f5bcb7ad1a2f9d57f from https://github.com/opensearch-project/OpenSearch/pull/14790/.
> [Backport 2.x] Add prefix mode verification setting for repository verification

- server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
- server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManager.java
- server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
- server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
- server/src/test/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
Backport b58546914c1191d6364d9afa006a48bba00ef596 from #14671
> [Backport 2.x] Create interface RemoteEntitiesManager

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/action/IndicesRequestIT.java
- server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/get/TransportGetDecommissionStateAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/repositories/get/TransportGetRepositoriesAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportClusterSearchShardsAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/get/TransportGetWeightedRoutingAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/TransportGetStoredScriptAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/tasks/TransportPendingClusterTasksAction.java
- server/src/main/java/org/opensearch/action/admin/indices/alias/get/TransportGetAliasesAction.java
- server/src/main/java/org/opensearch/action/admin/indices/exists/indices/TransportIndicesExistsAction.java
- server/src/main/java/org/opensearch/action/admin/indices/shards/TransportIndicesShardStoresAction.java
- server/src/main/java/org/opensearch/action/admin/indices/template/get/TransportGetComponentTemplateAction.java
- server/src/main/java/org/opensearch/action/admin/indices/template/get/TransportGetComposableIndexTemplateAction.java
- server/src/main/java/org/opensearch/action/admin/indices/template/get/TransportGetIndexTemplatesAction.java
- server/src/main/java/org/opensearch/action/ingest/GetPipelineTransportAction.java
- server/src/main/java/org/opensearch/action/search/GetSearchPipelineTransportAction.java
- server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
- server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeReadAction.java
- server/src/main/java/org/opensearch/action/support/clustermanager/info/TransportClusterInfoAction.java
- server/src/test/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsActionTests.java
This is a follow-up to the issue [12252](https://github.com/opensearch-project/OpenSearch/pull/12252/) to enable term-version check using light-weight transport action before fetching the cluster-state from cluster-manager. This pull request enables the term-version check for the remaining Transport Actions extending `TransportClusterManagerNodeReadAction`
> Enabling term version check on local state for all ClusterManager Read Transport Actions

- CHANGELOG.md
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SplitResponseProcessor.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SplitResponseProcessorTests.java
Adds a new `SearchResponseProcessor` implementation that splits a field, comparable to the Ingest Pipeline [Split Processor](https://opensearch.org/docs/latest/ingest-pipelines/processors/split/).
Part 2 (of 2) of #14758
- https://github.com/opensearch-project/documentation-website/pull/7767
- JSON examples were the result of actual testing of this PR code
- https://github.com/opensearch-project/opensearch-api-specification/pull/440
> Add SplitResponseProcessor to Search Pipelines

- CHANGELOG.md
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SortResponseProcessor.java
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SplitResponseProcessor.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SortResponseProcessorTests.java
- modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/80_sort_response.yml
Adds a new `SearchResponseProcessor` implementation that sorts a field, comparable to the Ingest Pipeline [Sort Processor](https://opensearch.org/docs/latest/ingest-pipelines/processors/sort/#:~:text=The%20sort%20processor%20sorts%20an,input%20is%20not%20an%20array.).
Part 1 (of 2) of #14758
- https://github.com/opensearch-project/documentation-website/pull/7767
- JSON examples were the result of actual testing of this PR code
- https://github.com/opensearch-project/opensearch-api-specification/pull/440
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/C …
> Add SortResponseProcessor to Search Pipelines

- CHANGELOG.md
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SortResponseProcessor.java
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SplitResponseProcessor.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SortResponseProcessorTests.java
- modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/80_sort_response.yml
Backport 5de0c8a7a3a63455758a8bfe24199f4955f29dca from #14785.
> [Backport 2.x] Add SortResponseProcessor to Search Pipelines (#14785)

- CHANGELOG.md
- modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
- modules/analysis-common/src/main/java/org/opensearch/analysis/common/PersianStemTokenFilterFactory.java
- modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
- modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
- test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Lucene provided Persian stem apparently isn't hooked yet and this change is doing that based on what is done for Arabic stem support.
Resolves #14846
> Use Lucene provided Persian stem

- CHANGELOG.md
- modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
- server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
- server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
- server/src/main/java/org/opensearch/ingest/IngestService.java
- server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java
- server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
1. Change default batch size of bulk API to Integer.MAX_VALUE
2. Report deprecation log is batch_size parameter is used.
- **backport to 2.x**
~~Please **ONLY** backport this PR to 2.x after this one https://github.com/opensearch-project/neural-search/pull/832 is merged.~~
https://github.com/opensearch-project/OpenSearch/issues/14283
> Change default batch size of bulk API to Integer.MAX_VALUE

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/service/MasterService.java
- server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java
- server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
- server/src/test/java/org/opensearch/cluster/service/TaskBatcherTests.java
[Backport 2.16] Reduce logging in DEBUG for MasterService:run
Raised manual backport to 2.16.
Related (2.x) https://github.com/opensearch-project/OpenSearch/pull/14864 & (Main) https://github.com/opensearch-project/OpenSearch/pull/14795
> [Backport 2.16] Reduce logging in DEBUG for MasterService:run

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
Scripted queries require elevated permissions to write to a remote snapshot local file cache. Since accessing the file cache can trigger an eviction the AccessController doPrivileged call needs to move up the call stack so we have permissions to perform file deletions for these evictions.
Reproduced and verified fix with OSB StackOverflow workload:
1. Run OSB StackOverflow workload.
2. Create snapshot from so index.
3. Restore from remote snapshot.
4. Query with a scripted field. 
```
curl -X POST "http://localhost:9200/so/_search?pretty" -H 'Content-Type: application/json' -d'
{
"query": {
"match": {
"body": "java"
}
},
"script_fields": {
"combined_field": {
"script": {
"source": "params[\"_source\"][\"user\"] + \" \" + params[\"_source\"][\"body\"]"
}
}
},
"size": 100
}
'
```
```
{ …
```
> Add perms for remote snapshot cache eviction on scripted query

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponse.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/RestWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequest.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringValidationResult.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/package-info.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/indices/tiering/TieringRequestValidator.java
- server/src/main/java/org/opensearch/indices/tiering/package-info.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponseTests.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequestTests.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java
- server/src/test/java/org/opensearch/indices/tiering/TieringRequestValidatorTests.java
Adding rest, transport layer changes for hot to warm tiering
https://github.com/opensearch-project/OpenSearch/issues/14545
Service side changes pr - https://github.com/neetikasinghal/OpenSearch/pull/144
> Add rest, transport layer changes for Tiering

- server/src/main/java/org/opensearch/cluster/ClusterInfo.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
In case disk usage of a particular node is not populated inside ClusterInfo (due to an underlying issue), we use the average usage for all nodes as the usage for this node inside DiskThresholdDecider. For calculating this value, right now we are iterating through all the diskUsages of every node inside DiskThresholdDecider to calculate total sum and divide by the total number of nodes. Since this computation is performed for each node during shard allocation, it becomes computationally expensive.
This PR does an offline calculation of Average total bytes and Average free bytes and cache it inside ```ClusterInfo```.
For initialing 100k shards after master reboot on 1k nodes, we are observing an improvement of about 7 - 8% (63 sec) with the above change.
886184 ms
823801 ms
By submitting …
> Caching avg total bytes and avg free bytes inside ClusterInfo

- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
Backport https://github.com/opensearch-project/OpenSearch/commit/e82b432940be34941c999dd1fe5cdc9fed06f02b from https://github.com/opensearch-project/OpenSearch/pull/14612.
> [Backport 2.x] Removing String format in RemoteStoreMigrationAllocationDecider

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponse.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/RestWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequest.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringValidationResult.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/package-info.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/indices/tiering/TieringRequestValidator.java
- server/src/main/java/org/opensearch/indices/tiering/package-info.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponseTests.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequestTests.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java
- server/src/test/java/org/opensearch/indices/tiering/TieringRequestValidatorTests.java
> Add rest, transport layer changes for Hot to warm tiering - dedicated setup

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
When creating index, if index.number_of_replicas is explicitly set to null, will use default value.
Resolves https://github.com/opensearch-project/OpenSearch/issues/14783
> Use default value when index.number_of_replicas is null

- server/src/main/java/org/opensearch/cluster/ClusterInfo.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/130500218a794f15df522c3ba5a31acbc77209e4 from https://github.com/opensearch-project/OpenSearch/pull/14851.
> [Backport 2.16] Caching avg total bytes and avg free bytes inside ClusterInfo

- server/src/main/java/org/opensearch/cluster/routing/allocation/ConstraintTypes.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
Fix constraint bug which allows more primary shards than average primary shards per index  .
If avg primary shards of an index is 2, the constraint should return true once a node has 2 shards already . At present the constraint returns true only when it will have 3 shards, allowing 1 extra shard of that index on the node. 
> Fix constraint bug which allows more primary shards than average primary shards per index

- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java
HashMap.get function call for a hash map where key is String is a relatively costly operation. AwarenessAllocationDecider makes multiple HashMap.get to
- Check [if this Attribute value is set ](https://github.com/opensearch-project/OpenSearch/blob/ba9bdacc05928c82a4244b06c5c0e8283406dc7d/server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java#L167)for this node.
- Fetch [Awareness attribute value](https://github.com/opensearch-project/OpenSearch/blob/ba9bdacc05928c82a4244b06c5c0e8283406dc7d/server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java#L188) on which allocation of a shard is determined for a node, 
- Calculate [total shard count per …
> Optimising hashmap.get call inside AwarenessAllocationDecider

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIndices.java
- server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodeResponse.java
- server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
- server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequestBuilder.java
- server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
- server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java
- server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodesTests.java
Optimize Cluster Stats Indices to precomute node level stats
PR - https://github.com/opensearch-project/OpenSearch/pull/14426
> [Backport 2.16] Optimized ClusterStatsIndices to precomute shard stats (#14426)

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
- server/src/test/java/org/opensearch/cluster/coordination/PersistedStateStatsTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
[Backport 2.x] Refactor remote routing table service to implement remote objects #14862
> [Backport 2.x] Add integration tests for RemoteRoutingTable Service. (#14631)

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
- server/src/test/java/org/opensearch/cluster/coordination/PersistedStateStatsTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
[Backport 2.16] Add integration tests for RemoteRoutingTable Service. (#14631)
> [Backport 2.16] Add integration tests for RemoteRoutingTable Service. (#14631)

- server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
The test would previously fail if the randomness led to only a single indexing request being included in the bulk payload. This change guarantees multiple indexing requests in order to ensure the batch logic kicks in.
Also replace some unneeded mocks with real classes.
https://build.ci.opensearch.org/job/gradle-check/43150/
> Fix IngestServiceTests.testBulkRequestExecutionWithFailures

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingTableIncrementalDiff.java
- server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteRoutingTableDiff.java
- server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableDiffTests.java
Backport [f85a58f](https://github.com/opensearch-project/OpenSearch/commit/f85a58f64e5aaba76eb519e309881f288aff8fa6) from https://github.com/opensearch-project/OpenSearch/pull/14684
> [Backport 2.x] Implement write and read flow for shard diff file.

- CHANGELOG.md
- modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java
- modules/analysis-common/src/main/java/org/opensearch/analysis/common/PersianStemTokenFilterFactory.java
- modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
- modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java
- modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
- test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Lucene provided Persian stem apparently isn't hooked yet and this change is doing that based on what is done for Arabic stem support.
Following https://github.com/opensearch-project/OpenSearch/pull/14847#issuecomment-2243960516
> [Backport 2.x] Use Lucene provided Persian stem

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/SearchTaskRequestOperationsListener.java
- server/src/main/java/org/opensearch/node/Node.java
Backporting https://github.com/opensearch-project/OpenSearch/pull/14832 to 2.16
Signed-off-by: Siddhant Deshmukh <deshsid@amazon.com>
* [bug fix] fix incorrect coordinator node search resource usages
Signed-off-by: Chenyang Ji <cyji@amazon.com>
* fix bug on serialization when passing task resource usage to coordinator
Signed-off-by: Chenyang Ji <cyji@amazon.com>
* add more unit tests
Signed-off-by: Chenyang Ji <cyji@amazon.com>
* remove query insights plugin related code
Signed-off-by: Chenyang Ji <cyji@amazon.com>
* create per request listener to refresh task resource usage
Signed-off-by: Chenyang Ji <cyji@amazon.com>
* Make new listener API public
Signed-off-by: Siddhant Deshmukh <deshsid@amazon.com>
* Add changelog
Signed-off-by: Siddhant Deshmukh <deshsid@amazon.com>
* Remove wrong …
> [Backport 2.16] Create listener to refresh search thread resource usage (#14832)

- server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
- server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
- server/src/main/java/org/opensearch/repositories/blobstore/ConfigBlobStoreFormat.java
- server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
S3 Multipart upload fails for remote state objects
#14808 
> Create new IndexInput for multi part upload

- server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodeResponse.java
- server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
Updating Cluster Stats Optimisation Versions to 2.16
Reference PR - https://github.com/opensearch-project/OpenSearch/pull/14426
- ~~[] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~~
- ~~[] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTI …
> Updating Cluster Stats Optimisation Versions to 2.16

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingTableIncrementalDiff.java
- server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteRoutingTableDiff.java
- server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableDiffTests.java
Backport [f85a58f](https://github.com/opensearch-project/OpenSearch/commit/f85a58f64e5aaba76eb519e309881f288aff8fa6) from #14684
> [Backport 2.16] Implement write and read flow for shard diff file.

- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
IndicesRoutingDiffPath would be null in diff manifest when there are no updates in routing table. Currently we are not handling null values and it will throw an EOFException if it encounters a null when trying to read/write indicesRoutingDiffPath in/from diff manifest. 
> Fix read/write in stream method for Diff Manifest when shard diff file is null

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
- server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/a252b29c37f36f3ddaae0787b4f4562d2227cfa0 from https://github.com/opensearch-project/OpenSearch/pull/14807
> [Backport 2.x] Fix constant_keyword field type not working

- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Backport [5744eae](https://github.com/opensearch-project/OpenSearch/commit/5744eae80dfe466397f4254acf995794855db370) from https://github.com/opensearch-project/OpenSearch/pull/14938
> [Backport 2.x] Fix read/write in stream method for Diff Manifest when shard diff file is null

- server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Backport [5744eae](https://github.com/opensearch-project/OpenSearch/commit/5744eae80dfe466397f4254acf995794855db370) from https://github.com/opensearch-project/OpenSearch/pull/14938
> [Backport 2.16] Fix read/write stream method for Diff Manifest when shard diff file is null.

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/admin/indices/template/post/TransportSimulateIndexTemplateAction.java
- server/src/main/java/org/opensearch/action/admin/indices/template/post/TransportSimulateTemplateAction.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateMetadata.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesService.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/TemplateRepositoryMetadata.java
- server/src/main/java/org/opensearch/cluster/coordination/OpenSearchNodeCommand.java
- server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
- server/src/main/java/org/opensearch/cluster/metadata/Context.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
- server/src/test/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/14811
> [Backport 2.x] Template creation using context (#14811)

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/admin/indices/template/post/TransportSimulateIndexTemplateAction.java
- server/src/main/java/org/opensearch/action/admin/indices/template/post/TransportSimulateTemplateAction.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateMetadata.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesService.java
- server/src/main/java/org/opensearch/cluster/applicationtemplates/TemplateRepositoryMetadata.java
- server/src/main/java/org/opensearch/cluster/coordination/OpenSearchNodeCommand.java
- server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
- server/src/main/java/org/opensearch/cluster/metadata/Context.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
- server/src/test/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/14811
> [Backport 2.16] Template Creation using Context

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
- server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
backport #14379 , solve the conflict in CHANGELOG.md
> [Backport 2.x] [BUG FIX] Fix the visit of inner query for NestedQueryBuilder 

- server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
- server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
backport https://github.com/opensearch-project/OpenSearch/issues/14379 , solve the conflict in CHANGELOG.md
> [Backport 2.16] [BUG FIX] Fix the visit of inner query for NestedQueryBuilder

- release-notes/opensearch.release-notes-2.16.0.md
- rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
- server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/14807 to 2.16.
https://github.com/opensearch-project/OpenSearch/issues/14638
> [Backport 2.16] fix constant_keyword field type (#14807)

- server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
Fix version check after backport
> Fix version check after backport

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
- server/src/main/java/org/opensearch/gateway/AsyncShardBatchFetch.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
- server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
This change fixes the bug in `hasInitiatedFetching()` where it always returns true in batch mode, causing allocation explain to show `AWAITING_INFO` even for shards for which decider is returning NO.
The idea here is we want to populate shard store information (number of matching bytes per node) IN ADDITION to the decision made by deciders.
This function is meant to check if it is possible to get the above information, without triggering a new asyncFetch.
The intended behaviour is for this function to return true if a fetch has ever happened before, or is ongoing for a batch.
It should return false if there has never been a fetch for this batch.
This is so that it does not trigger a new asyncFetch call, but also uses the data from existing ones or wait for ongoing ones to populate shard …
> [Batch Fetch] Fix for hasInitiatedFetching to fix allocation explain and manual reroute APIs

- .github/workflows/version.yml
- CHANGELOG.md
- Backport onto 2.x of #14997
Bumps [actions/github-script](https://github.com/actions/github-script) from 6 to 7.
- [Release notes](https://github.com/actions/github-script/releases)
- [Commits](https://github.com/actions/github-script/compare/v6...v7)
> [Backport 2.x] Bump actions/github-script from 6 to 7 (#14997)

- CHANGELOG-3.0.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
- server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
Removes `index.store.hybrid.mmap.extensions` setting in OS 3.0.
Follow up to https://github.com/opensearch-project/OpenSearch/pull/8508
Currently OpenSearch code contains an explicit list of file extensions which load using mmap from hybridfs. Other file extensions default to nio. This PR flips the logic to keep a list of nio file extensions while all others default to mmap. This will prevent any future regressions in case Lucene adds new segment file type that should be using mmap.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8297 …
> Remove mmap.extensions setting

- modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/60_derived_field_aggs.yml
Fix derived field tests for percentile ranks.
These tests fail to backport to 2.x becuase 2.x uses a different branch of
tdigest that computes percentiles differently.  Rather than chase these over time,
change the assertions to check for the length of results returned instead of their values.
Resolves N/A - caught while backporting this pr https://github.com/opensearch-project/OpenSearch/pull/15009 to 2.x, will include this commit with the backport after it lands in main.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certif …
> Fix derived field tests for percentile ranks.

- CHANGELOG.md
- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Backport of https://github.com/opensearch-project/OpenSearch/pull/14998 to `2.x`
> [Backport] [2.x] OpenJDK Update (July 2024 Patch releases) (#14998)

- rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
After the PR https://github.com/opensearch-project/OpenSearch/pull/14807 is backported to 2.x, we need to fix the version check in the related yml test to make sure the test case can run against an old version node in a mixed version cluster.
https://github.com/opensearch-project/OpenSearch/issues/14638
<del>- [ ] Functionality includes testing.</del>
<del>- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.</del>
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.</del>
For …
> Fix version check in yml test for the bug fix of constant_keyword field type not working

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
- server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java
Two changes here:
1. Fixes parsing numeric missing value of unsigned long type. When we pass a numeric missing value like 4 to unsigned long field sort, the `ClassCastException` will be thrown(`class java.lang.Integer cannot be cast to class java.math.BigInteger `).
2. Requires the missing value of unsigned long type must not be negative.
> Fix missing value of FieldSort for unsigned_long

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
- server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
- server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
With this https://github.com/opensearch-project/OpenSearch/pull/14848 we added cluster settings for allocator's timeout of which default value is MINUS_ONE. This PR adds a min limit to this setting such that very small values are not added to these settings.
Resolves #14941
- ~[] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
> Add lower limit for primary and replica batch allocators timeout

- server/src/test/java/org/opensearch/core/RestStatusTests.java
This test has a reproducible failure when the highest "failure" status is 100 level. This happens because RestStatus.status treats these as OK.
Resolves https://github.com/opensearch-project/OpenSearch/issues/15008
> Fix test RestStatusTests.testStatusReturnsFailureStatusWhenFailuresExist

- buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
While working on aarch64 distributions for MacOS, @peterzhuamazon reported an issue that Gradle checks fails to run:
```
* What went wrong:                                                                                                                                                                                                                                                                                                                                    
Could not determine the dependencies of task ':qa:full-cluster-restart:v1.3.19#upgradedClusterTest'. …
```
> Fix MacOS Mx (arm64) and Linux (arm64, ppc64le, s390x) checks

- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
Allocation constraints specify conditions which, if breached, reduce the priority of a node for receiving unassigned shard allocations. When [evaluating the cluster constraint on avg primary shards](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/ConstraintTypes.java#L84) across all indices per node, we calculate [total number of primary shards on a node](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L495) by summing up the shard count of all indices on the node. Since this computation is performed for each node during shard allocation, it becomes computationally expensive. As there is only single …
> Caching total number of primary shards per node for evaluating constraints on avg primary shards across all indices per node

- CHANGELOG.md
- server/src/main/java/org/opensearch/client/OriginSettingClient.java
- server/src/main/java/org/opensearch/client/support/AbstractClient.java
- server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
- server/src/main/resources/org/opensearch/bootstrap/security.policy
- server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
- server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
Similar to https://github.com/opensearch-project/OpenSearch/pull/15016, but extends it to more methods in the ThreadContextClass. This PR introduces permissions for stashAndMergeHeaders (used in test context only) and stashWithOrigin.
Related to https://github.com/opensearch-project/OpenSearch/issues/14931
> Add ThreadContextPermission for stashAndMergeHeaders and stashWithOrigin

- CHANGELOG.md
- server/src/main/java/org/opensearch/client/OriginSettingClient.java
- server/src/main/java/org/opensearch/client/support/AbstractClient.java
- server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
- server/src/main/resources/org/opensearch/bootstrap/security.policy
- server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
- server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
Manual backport of #15039 to 2.x that includes a deprecationLogger message to print out to unauthorized callers that access will be removed in next major version.
> [Backport 2.x] Add ThreadContextPermission for stashAndMergeHeaders and stashWithOrigin

- server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
Follow-up to https://github.com/opensearch-project/OpenSearch/pull/15039 to add javadoc on the permissions added to ThreadContext.stashWithOrigin and ThreadContext.stashAndMergeHeaders
> Add javadoc about ThreadContextPermission for stashWithOrigin and stashAndMergeHeaders

- .github/workflows/precommit.yml
Add MacOS aarch64 to assemble / precommit since we rolled out the support for such distribution
Part of https://github.com/opensearch-project/opensearch-build/issues/4670
> Add MacOS aarch64 to precommit since we rolled out the support for such distribution

- TRIAGING.md
Decommission the Core Triage meeting
The end of this series doesn't mean the end of these public forums - we've got four different domain specific meetings to triage and discuss the issues.  All the other meetings are documented in the [TRIAGING.md](https://github.com/opensearch-project/OpenSearch/blob/main/TRIAGING.md) and on the [OpenSearch meetup](https://www.meetup.com/pro/opensearchproject/).
- @krisfreedain for facilitating the series launch and wrangling virtual meeting logistics
- @andrross @reta @dbwiddis @lukas-vlcek @jed326 for their leadership and participation during triage.
- @mch2 @rramachand21 @rwali-aws @ankitkala @dblock for creating and running the additional triage meetings that let me rest easy knowing the project is covered.
- For everyone that attended the triage …
> Decommission the Core Triage meeting

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
- server/src/main/java/org/opensearch/index/mapper/ConstantFieldType.java
- server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldTypeTests.java
Support rangeQuery and regexpQuery in constant_keyword field type
> support rangeQuery and regexpQuery in constant_keyword field type

- server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
If we use async FS Repo , checksum comes null in a flaky way . To stop further build failures, i have set it to not use async FS Repo . This is what we are doing for `RemoteSplitIndexIT` as well and originally done in https://github.com/opensearch-project/OpenSearch/pull/13637 
The tricky thing is i am not able to repro why the checksum could come null even on 2.5k iterations and running . I will keep running this to see if it ever fails .  
Resolves #14292 
For more information on following Developer Certificate …
> Fix RemoteCloneIndex flaky test by using sync FS repo

- README.md
Small PR to update an old reference in the README to point to the latest unreleased minor version 2.17.0.
> Update stale reference in README from 2.14.1 to 2.17.0

- rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_index_template/10_basic.yml
Fix the version check in yml test file after the [PR](https://github.com/opensearch-project/OpenSearch/pull/15080) is backport to 2.x branch.
No need to backport this PR to 2.x because it has been changed yet.
https://github.com/opensearch-project/OpenSearch/issues/9194
<del>- [ ] Functionality includes testing.<del>
<del>- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.<del>
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.<del> …
> Fix version check in yml test for the bug fix of delete index template failed

- rest-api-spec/src/main/resources/rest-api-spec/test/index/115_constant_keyword.yml
This a follow-up PR for https://github.com/opensearch-project/OpenSearch/pull/14711, we need to change the version check to 2.17.0 after the original PR is backported to 2.x branch.
In addition, I found the number prefix of the file `110_constant_keyword.yml` conflicts with `110_strict_allow_templates.yml`, so I renamed `110_constant_keyword.yml` to `115_constant_keyword.yml`.
No issue.
<del>- [ ] Functionality includes testing.<del>
<del>- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.<del>
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.<del> …
> Fix version check for adding rangeQuery and regexpQuery support for constant_keyword field type

- .github/benchmark-configs.json
- .github/workflows/benchmark-pull-request.yml
This PR adds `basline_cluster_config` key to benchmark configs. 
This will correspond to `user-tags.cluster-config` metadata attached to each metric generated by opensearch-benchmark nightly baseline runs to compare against benchmarks on pull requests. https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/benchmark-pull-request.jenkinsfile#L193-L209
This will be used later on finding the latest `test-execution-id` of the respective baseline run, run compare with benchmark on pull request `test-execution-id` and publish compare results as well. 
#14826 
- ~[ …
> Add baseline-cluster-config key to benchmark config

- .github/CODEOWNERS
Adding my own `CODEOWNERS` personalizations. Copying all maintainers under default ownership to the new categories.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …
> CODEOWNERS personalizations for jed326

- CHANGELOG-3.0.md
- CHANGELOG.md
changelog item for https://github.com/opensearch-project/OpenSearch/pull/15054 should not be in `CHANGELOG-3.0.md` as it was backported to `2.x` in https://github.com/opensearch-project/OpenSearch/pull/15129 …
> Fix CHANGELOG for #15054

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/search/ResourceType.java
- server/src/main/java/org/opensearch/wlm/QueryGroupLevelResourceUsageView.java
- server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java
- server/src/main/java/org/opensearch/wlm/tracker/package-info.java
- server/src/test/java/org/opensearch/search/ResourceTypeTests.java
- server/src/test/java/org/opensearch/wlm/QueryGroupLevelResourceUsageViewTests.java
- server/src/test/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerServiceTests.java
Backport - https://github.com/opensearch-project/OpenSearch/pull/13897
> [Backport 2.x] QueryGroup Resource Tracking framework and implementation (#13897)

- .github/CODEOWNERS
- MAINTAINERS.md
I have nominated, and maintainers have agreed to add Varun Bansal (@linuxpi ) as a co-maintainer, who kindly accepted.
Varun  is an active contributor of OpenSearch project and is the proposer/developer of Offline Background Tasks and has extensively contributed to Remote Store and Remote Cluster State features which has been launched successfully for users, with most of his recent works focused on offline background task , remote cluster state and remote store related areas. Apart from this, he has proactively contributed to identifying critical bugs, resolving them and improving documentations around the same. Varun is also an active member of the OpenSearch Storage bi-weekly triages and has consistently exercised sound judgement in triaging and prioritizing the issues. Varun has led 3 …
> Add Varun Bansal as maintainer

- rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_index_template/10_basic.yml
`org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=indices.delete_index_template/10_basic/Delete index template which is not used by data stream but index pattern matches}` is flaky, the reason is that the mixed version cluster has a template with index patterns `*`, so when creating a new index template, the API returns a warning header `index template [test_template_1] has index patterns [test-*]...`. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/15161
<del>- [ ] Public documentation issue/PR …
> Fix yml test {p0=indices.delete_index_template/10_basic} is flaky

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/shard/SearchOperationListener.java
- server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
- server/src/test/java/org/opensearch/index/shard/SearchOperationListenerTests.java
- server/src/test/java/org/opensearch/search/SearchCancellationTests.java
- server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
- server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
- server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
- server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
- test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Add slice level operation listener to `SearchOperationListener` plugin interface. See motivation in #15136.
Resolves #15136 
> Add slice level operation listener methods

- plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
Seems like the timeout of 2 seconds was quite aggressive, bumping it to 5 seconds.
Closes https://github.com/opensearch-project/OpenSearch/issues/14318
> Fix (some_ AzureBlobContainerRetriesTests flaky tests

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/index/120_field_name.yml
- server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
- server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
"." as field name yields `array_index_out_of_bounds_exception`, the reason is that we split the field name by `.` here:
https://github.com/opensearch-project/OpenSearch/blob/49b7cd47b0f0112ca21d1ea3952106f28f8253bb/server/src/main/java/org/opensearch/index/mapper/DocumentParser.java#L208,
, if the field name contains only dot, the split result is an empty array, then yields that exception in this line:
https://github.com/opensearch-project/OpenSearch/blob/0cde7baf438e6ab994114b71dd9fadcacac4e443/server/src/main/java/org/opensearch/index/mapper/DocumentParser.java#L1045.
Since `.` is reserved for object resolution, we can fail the indexing request when the field name contains only dot.
Resolves https://github.com/opensearch-project/OpenSearch/issues/14911 …
> Fix array_index_out_of_bounds_exception when indexing documents with field name containing only dot

- .github/workflows/benchmark-pull-request.yml
There was recent dependabot update for `setup-java` action which updated the version from `v1` to `v4`. See 
https://github.com/opensearch-project/OpenSearch/pull/15104. 
The new version requires `distribution` key to be defined.  …
> add required distribution key in setup-java action

- plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
Fix more AzureBlobContainerRetriesTests flaky tests, specifically this problem:
```
Caused by: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
Suppressed: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 1000ms in 'source(MonoDefer)' (and no fallback has been configured)
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295)
at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280)
at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419)
at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
at …
```
> Fix more AzureBlobContainerRetriesTests flaky tests

- server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
- server/src/main/java/org/opensearch/common/remote/AbstractClusterMetadataWriteableBlobEntity.java
- server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManager.java
- server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityManager.java
- server/src/main/java/org/opensearch/common/remote/RemoteWriteableBlobEntity.java
- server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntityBlobStore.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStore.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadata.java
- server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTable.java
- server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteRoutingTableDiff.java
- server/src/test/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManagerTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Aims to make the remote entity classes more reusable by moving them to commons and removing dependencies around remote cluster state
Resolves #15180
> Refactor remote writeable entity and store to make it more reusable

- .github/workflows/changelog_verifier.yml
Improve breaking change logic for changelog verifier
- Resolves #15155
> Improve breaking change logic for changelog verifier

- libs/core/src/main/java/org/opensearch/core/xcontent/AbstractXContentParser.java
- qa/os/src/test/java/org/opensearch/packaging/util/FileUtils.java
- qa/smoke-test-http/src/test/java/org/opensearch/http/DanglingIndicesRestIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/recovery/DanglingIndicesIT.java
- server/src/main/java/org/opensearch/http/HttpChannel.java
- server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
- server/src/main/java/org/opensearch/snapshots/package-info.java
- server/src/main/java/org/opensearch/transport/TcpChannel.java
- server/src/test/java/org/opensearch/action/admin/cluster/node/info/NodeInfoTests.java
- server/src/test/java/org/opensearch/common/LocalTimeOffsetTests.java
- server/src/test/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerServiceTests.java
I was reading through the code comments and found a typo, so I corrected it.
"the the" -> "the"
none
> Correction of a typo

- server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
- server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
- server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
- server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
With https://github.com/opensearch-project/OpenSearch/pull/14848, we introduced capability to make reroute iteration time-bound. Currently OpenSearch uses two primary allocators - `ExistingShardsAllocator` which is responsible for allocating existing shards, and `BalancedShardsAllocator` which handles the allocation of all unassigned shards. 
This PR adds responsibility check in `ExistingShardsAllocator` such that newly created shards are not added to ignored list.
Resolves #15222 
By …
> Fix responsibility check for existing shards allocator when timed out

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
- server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
- server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
Fixed an issue in the flat_object where array field names were incorrectly removed after processing the first object, leading to inaccurate key-paths in flattened JSON data.
https://github.com/opensearch-project/OpenSearch/issues/13351
> Fix parseToken array popping

- .github/workflows/benchmark-pull-request.yml
This PR fixes the logic to fetch maintainer id list from `CODEOWNERS` file in `benchmark-pull-request` workflow.  …
> Fix logic for getting maintainer ids for benchmark workflow

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
DiscoveryNodes is being uploaded as part of remote cluster state. The remote path for this object is being constructed using stateUUID. Cluster UUID should be used for the path instead.
#15142 
> Use clusterUUID for discovery nodes remote path

- server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
- server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
Current implementation of [`RemoteSegmentTransferTrackerTests.testComputeTimeLagOnUpdate()`](https://github.com/opensearch-project/OpenSearch/blob/2b17902643738f0d2a75ade7c85cbca94d18ce49/server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java#L139) test rely on some assumptions about how fast the testing code will finish in JVM. Moreover it does not precisely control boundaries of the time span, specifically the start of the span because it is determined by internal implementation of [`RemoteSegmentTransferTracker.getTimeMsLag()`](https://github.com/opensearch-project/OpenSearch/blob/2b17902643738f0d2a75ade7c85cbca94d18ce49/server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java#L262) which indirectly makes call to …
> Don't rely on test code execution time span for RemoteSegmentTransferTrackerTests

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemotePinnedTimestamps.java
- server/src/main/java/org/opensearch/gateway/remote/model/RemoteStorePinnedTimestampsBlobStore.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
- server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
- server/src/test/java/org/opensearch/gateway/remote/model/RemotePinnedTimestampsTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- As part of [timestamp pinning ](https://github.com/opensearch-project/OpenSearch/issues/15057), we are adding support of pinning the timestamp for remote backed indices.
- In this PR, we introduce a service which provides APIs to `pin` and `unpin` the timestamp.
- Once the pinned timestamp list is updated, we need to modify in-memory data structure at each node. This is done by a scheduler which runs periodically and updates the local state.
- The periodicity of this scheduler is controlled by a dynamic cluster setting.
- https://github.com/opensearch-project/OpenSearch/issues/15061
- https://github.com/opensearch-project/OpenSearch/issues/15062 …
> Add timestamp pinning service and scheduler to update in-memory state

- CHANGELOG.md
- plugins/workload-management/build.gradle
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/WorkloadManagementPlugin.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupAction.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequest.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupResponse.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportCreateQueryGroupAction.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/package-info.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/package-info.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/RestCreateQueryGroupAction.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/package-info.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceService.java
- plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/package-info.java
- plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/QueryGroupTestUtils.java
- plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequestTests.java
- plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/CreateQueryGroupResponseTests.java
- plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceServiceTests.java
- plugins/workload-management/src/yamlRestTest/java/org/opensearch/plugin/wlm/WorkloadManagementClientYamlTestSuiteIT.java
- plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/api/create_query_group_context.json
- plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/test/wlm/10_create_query_group.yml
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java
- server/src/test/java/org/opensearch/cluster/metadata/QueryGroupMetadataTests.java
- server/src/test/java/org/opensearch/cluster/metadata/QueryGroupTests.java
> Add Create QueryGroup API Logic (#14680)

- CHANGELOG.md
- modules/analysis-common/src/main/java/org/opensearch/analysis/common/MinHashTokenFilterFactory.java
- modules/analysis-common/src/test/java/org/opensearch/analysis/common/MinHashFilterFactoryTests.java
The [MinHash](https://opensearch.org/docs/latest/analyzers/token-filters/index/) token filter has four configurable parameters: bucket_count, hash_count, hash_set_size, and with_rotation. Currently both bucket_count and hash_set_size have no effect, because there appears to be a bug in the code that interfaces with the underlying Lucene class.
Notice the camel-case bucketCount and hashSetSize in the hasValue lines. These should be bucket_count and hash_set_size, since those are the parameter names that would appear (and be fetched on the following lines) from the settings object.
Resolves #15183 …
> fix: MinHash token filter parameters not working

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
- We introduced 2 new cluster settings as part of timestamp pinning in remote store. These settings are present in `RemoteStorePinnedTimestampService` class.
- But we already have a class to consolidate all the remote store related settings: `RemoteStoreSettings`.
- In this PR, we move the timestamp pinning settings to `RemoteStoreSettings`.
- This also helps in avoiding un-necessary injection of `RemoteStorePinnedTimestampService` to lower components.
> Move timestamp pinning settings to RemoteStoreSettings

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/terms/IncludeExcludeTests.java
- server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
If an aggregration specifies includes or excludes based on a regular expression, and the regular expression has a finite expansion followed by .*, then we can optimize the global ordinal filter.
Specifically, in this case, we can expand the matching prefixes, then include/exclude the range of global ordinals that start with each prefix.
Resolves #14368
> Optimize global ordinal includes/excludes for prefix matching

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/360_date_histogram.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml
- server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
- server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java
Backport #15194 
Resolves #15169
> Backport/backport 15194 to 2.x

- MAINTAINERS.md
Updated affiliation for @nknize in MAINTAINERS.md.
@nknize lmk if you prefer to be moved to Emeritus or would like a different affiliation since we haven't seen you here in a while.
> Update affiliation for @nknize.

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/search/DefaultSearchContext.java
- server/src/test/java/org/opensearch/search/SearchServiceTests.java
Adds support for index level slice count setting. This slice count value will take precedence over the cluster level slice count value if set. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/15268 
- [x ] Functionality includes testing.
> Add support for index level slice count setting

- CHANGELOG.md
- modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/IngestGeoIpPlugin.java
- modules/ingest-geoip/src/test/java/org/opensearch/ingest/geoip/IngestGeoIpPluginTests.java
- modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/IngestUserAgentPlugin.java
- modules/ingest-user-agent/src/test/java/org/opensearch/ingest/useragent/IngestUserAgentModulePluginTests.java
- modules/ingest-user-agent/src/test/java/org/opensearch/ingest/useragent/IngestUserAgentPluginTests.java
Backport to 2.x: https://github.com/opensearch-project/OpenSearch/pull/15325
Adding allowlist setting for user-agent, geo-ip.
> [Backport 2.x] Adding allowlist setting for ingest-useragent and ingest-geoip processors

- server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
- server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
Backports https://github.com/opensearch-project/OpenSearch/pull/15327 to 2.x. 
When a cacheable query times out, the IRC lets it enter the cache and then invalidates it in the same search thread. In 2.13, invalidation was changed to require a readerCacheKeyId string. `invalidate()` only got this if the `DirectoryReader` was an `OpenSearchDirectoryReader` and otherwise it was left null. When the reader was an `ExitableDirectoryReader`, this caused an NPE, which was returned to the user. It also means the timed-out query response incorrectly remained in the cache and could be returned the next time the user made the query. 
Fix this by getting `readerCacheKeyId` from `reader.getReaderCacheHelper()` without checking which class `reader` is. This is safe, as it's the same method used in …
> [Backport 2.x] [Bugfix] Fixes IRC NPE bug for timed-out cacheable queries (#15327)

- CHANGELOG.md
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
The `SplitResponseProcessor` for Search Pipelines was correctly added here:
https://github.com/opensearch-project/OpenSearch/pull/14800/files#diff-13c9de4d1b7eaef9dac008ddbff90b83b84e00dc13c2547c6c67484f26efc1e2
However, an incorrect (possibly automated) merge conflict resolution inadvertently removed it from the allowlist (and associated tests) here:
https://github.com/opensearch-project/OpenSearch/pull/14785/files#diff-13c9de4d1b7eaef9dac008ddbff90b83b84e00dc13c2547c6c67484f26efc1e2
This PR puts it back.
Resolves #15229 …
> Add SplitResponseProcessor to allowlist

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/test/java/org/opensearch/action/DynamicActionRegistryTests.java
Fixes an unchecked cast in dynamic action map getter
Resolves #15388 
> Fix unchecked cast in dynamic action map getter

- CHANGELOG.md
- modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
- modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
Backport 2301adf9a0e2921d2fa359c51ee5c87309ca71ad from #15393.
> [Backport 2.x] Add SplitResponseProcessor to allowlist (#15393)

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
- server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
- server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
Fall back to legacy Transport publication if Remote State is disabled. We were earlier trying to use remote publication when remote state was disabled, as the remote state was disabled RemoteClusterStateService instance is null and we were hitting null pointer.
Resolves #15182
> [Remote State] Disable remote publication if remote state disabled

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/test/java/org/opensearch/action/DynamicActionRegistryTests.java
Backport 6152afeef3ceb3fe4f18f6be2d55ac60256bc2db from #15394
> [Backport 2.x] Fix unchecked cast in dynamic action map getter (#15394)

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
- server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
- server/src/test/java/org/opensearch/index/store/BaseRemoteSegmentStoreDirectoryTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryWithPinnedTimestampTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
- As part of shallow snapshot optimisations, we are introducing timestamp based implicit locking support. This feature will be called Timestamp Pinning in remote backed storage. When a timestamp is pinned, remote store garbage collectors will skip deleting data corresponding to the timestamp.
- In this PR, we are making following changes to segment store garbage collection:
- Fetch metadata files in reverse-chronological order
- If timestamp of a metadata file `md1` is > `pinned_timestamp_a` and the timestamp of next metadata file `md2` <= `pinned_timestamp_a`, consider `md2` to be locked by pinned timestamp.
- Skip deletion of metadata files that are locked by pinned timestamps and corresponding data files
- Segment garbage collection will continue to skip locked metadata files for …
> Add support to skip pinned timestamp in remote segment garbage collector

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml
- server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
- server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/15375/
It is valid for a flat_object field to have an explicit value of null. (It's functionally the same as not specifying the field at all.) Prior to this fix, though, we would erroneously advance the context parser to the next token, violating the contract with DocumentParser (which says that a call to parseCreateField with a null value should complete with the parser still pointing at the null value -- it is DocumentParser's responsibility to advance).
* Fix unit test
* Add changelog entry
---------
(cherry picked from commit …
> Do not throw exception when flat_object field is explicitly null

- server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
These methods infinitely recurse as currently implemented. This change makes them throw UnsupportedOperationException similar to many other methods in this class.
Resolves #15387
> Throw UnsupportedOperationException in unused methods

- rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/index/105_partial_flat_object_nested.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml
While fixing a flat_object bug, I noticed that we were skipping all related yamlRestTests on pre-3.0 versions. Since the flat object field type was added in 2.7, that should be the correct skip level for most tests. The bug I fixed is still present in 2.16 and earlier, so the test that covers that fix needs to be skipped pre-2.17.
https://github.com/opensearch-project/OpenSearch/pull/15431
> Update skip versions for flat_object tests

- CHANGELOG.md
- client/rest/src/main/java/org/opensearch/client/RestClient.java
- plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingIT.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
- plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportStreamingTests.java
- server/src/main/java/org/opensearch/common/xcontent/support/XContentHttpChunk.java
- server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/15381 to `2.x`
> [Backport] [2.x] [Streaming Indexing] Introduce bulk HTTP API streaming flavor (#15381)

- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpChunk.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
Fix Netty's ByteBuf leak
```
Expected: an empty collection
but: <[LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
org.opensearch.http.reactor.netty4.ReactorNetty4StreamingRequestConsumer.createChunk(ReactorNetty4StreamingRequestConsumer.java:47)
org.opensearch.http.reactor.netty4.ReactorNetty4StreamingRequestConsumer.accept(ReactorNetty4StreamingRequestConsumer.java:37)
org.opensearch.http.reactor.netty4.ReactorNetty4StreamingRequestConsumer.accept(ReactorNetty4StreamingRequestConsumer.java:23)
```
By submitting this pull request, I confirm that my contribution is made under …
> Fix Netty's ByteBuf leak

- server/src/main/java/org/opensearch/search/ResourceType.java
Fixes the backward incompatibility introduced in https://github.com/opensearch-project/OpenSearch/pull/15473 …
> Fixing backward incompatibility check from #15473

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
* In a regular active recovery, the recovery stats for the `_cat/recovery` call are populated as 
```
index | shard | time | type | stage | source_host | source_node | target_host | target_node | repository | snapshot | files | files_recovered | files_percent | files_total | bytes | bytes_recovered | bytes_percent | bytes_total | translog_ops | translog_ops_recovered | translog_ops_percent
movies | 0 | 117ms | empty_store | done | n/a | n/a | 172.18.0.4 | odfe-node1 | n/a | n/a | 0 | 0 | 0.0% | 0 | 0 | 0 | 0.0% | 0 | 0 | 0 | 100.0%
movies | 0 | 382ms | peer | done | 172.18.0.4 | odfe-node1 | 172.18.0.3 | odfe-node2 | n/a | n/a | 1 | 1 |  100.0% | 1 | 208 | 208 | 100.0% | 208 | 1 | 1 | 100.0%
```
* Information like `bytes_recovered`, `bytes_total`, etc. is obtained from the …
> Populate RecoveryState details for shallow snapshot restore

- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
- Currently, remote translog metadata file has following format:
`metadata__<inverted primary term>__<inverted tranlog generation>__<inverted creation timestamp>__nodeId__<metadata version>`
- Although this works for ordering metadata files in reverse chronological order, just by looking at the metadata file name, it does not provide info on min generation referred.
- To make debugging easy, in this PR, we are adding min translog generation as part of remote translog metadata.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-ce …
> [Remote Store] Add minTranslogGeneration to remote translog metadata filename

- server/src/main/java/org/opensearch/search/ResourceType.java
- server/src/main/java/org/opensearch/wlm/ResourceType.java
Fix ResourceType API annottations and deprecations
Follow up on https://github.com/opensearch-project/OpenSearch/pull/15486
> Fix ResourceType API annotations and deprecations

- server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryWithPinnedTimestampTests.java
- This PR addresses following comments on the earlier PRs:
- https://github.com/opensearch-project/OpenSearch/pull/15017#discussion_r1732636725
- https://github.com/opensearch-project/OpenSearch/pull/15180/files#r1719741169
> Change RemoteSegmentStoreDirectory init at given timestamp to ignore pinned timestamp setting

- rest-api-spec/src/main/resources/rest-api-spec/test/cluster.put_settings/10_basic.yml
This PR fixed the bug of the validation for the cluster level `search_backpressure.mode` setting is missing, we need to update the version check in the yaml test file.
Changelog is not needed, backport 2.x is needed.
No issue.
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable. …
> Update version check for fix the bug of missing validation for the search_backpressure.mode setting

- libs/common/src/main/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessor.java
- libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
- libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiAnnotatedUnparseable.java
- libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiWithDeprecatedApiMethod.java
Enhance OpenSearch APIs annotation processor with OpenSearch version validation
Coming from https://github.com/opensearch-project/OpenSearch/pull/15497
> Enhance OpenSearch APIs annotation processor with OpenSearch version validation

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/index/91_flat_object_null_value.yml
- server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
- server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
- server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Signed-off-by: kkewwei kkewwei@163.com
The pr soloves three cases:
- fix null value case, I have test too many cases about null value, all of the tests are passed.
- deduplication the  value of fieldName, valueList, valueAndPathList, there is no need to store the duplicate values.
- fix infinite loop with null value ([comment](https://github.com/opensearch-project/OpenSearch/pull/13259#issuecomment-2312755190))
Resolves #13880
> Fix null values indexed as "null" strings in flat_object field

- .github/benchmark-configs.json
Adding benchmarking config for concurrent segment search scenarios
Helps to benchmark changes for https://github.com/opensearch-project/OpenSearch/issues/15259
> update benchmark configs with concurrent search scenarios

- CHANGELOG.md
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/wlm/QueryGroupService.java
- server/src/main/java/org/opensearch/wlm/WorkloadManagementTransportInterceptor.java
- server/src/main/java/org/opensearch/wlm/listeners/QueryGroupRequestRejectionOperationListener.java
- server/src/main/java/org/opensearch/wlm/listeners/package-info.java
- server/src/test/java/org/opensearch/wlm/WorkloadManagementTransportInterceptorTests.java
- server/src/test/java/org/opensearch/wlm/WorkloadManagementTransportRequestHandlerTests.java
- server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestRejectionOperationListenerTests.java
Backport 2.x for https://github.com/opensearch-project/OpenSearch/pull/15428
> Backport 2.x for (#15428)

- CHANGELOG-3.0.md
- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
Restricting index template creation if `cluster.remote_store.index.restrict.async-durability` is set to `true` and the incoming index template setting has `index.translog.durability` setting as `async`
https://github.com/opensearch-project/OpenSearch/issues/15493 …
> Adding translog durability validation in index templates

- CHANGELOG.md
- server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
- server/src/main/java/org/opensearch/search/backpressure/settings/SearchShardTaskSettings.java
- server/src/main/java/org/opensearch/search/backpressure/settings/SearchTaskSettings.java
When diving deep into the bug https://github.com/opensearch-project/OpenSearch/issues/15495, I found some unused code in the search backpressure package, we need to remove them.
https://github.com/opensearch-project/OpenSearch/issues/15495
> Remove some unused code in the search backpressure package

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaFeatureFlagIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
- server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
- server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
- server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
- server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/IndexMetadataUpdater.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java
- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/main/java/org/opensearch/index/shard/ReplicationGroup.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
- server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/SearchOnlyReplicaTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/UpdateNumberOfReplicasTests.java
- server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
- test/framework/src/main/java/org/opensearch/cluster/routing/TestShardRouting.java
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/15410 to 2.x line.
This backport resolves merge conflicts and includes one src change - the wire compatibility in ShardRouting is changed from 3_0_0 to 2_17_0.  2.x also does validation differently from main for update settings / create index, and throws IAE instead of a SettingsException, so updated test to reflect that.
N/A
> [Backport 2.x] Initial commit to support a search only replica for RW separation

- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
- server/src/main/java/org/opensearch/node/Node.java
This is a refactor only that separates code that orchestrates replication events from the transport layer service to initiate & report stats. This is in preparation for implementing a task to initiate replication events on an interval via IndexService.
Related https://github.com/opensearch-project/OpenSearch/issues/4577#issuecomment-2116838516
> Extract replicator logic from SegmentReplicationTargetService

- plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4BadRequestIT.java
- server/src/main/java/org/opensearch/rest/RestController.java
Handle unsupported media type properly for streaming requests
Fixes the NPE in `RestBulkStreamingAction` when content type header (media type) is not specified:
```
java.lang.NullPointerException: Cannot invoke "org.opensearch.core.xcontent.MediaType.mediaTypeWithoutParameters()" because "mediaType" is null                    
at org.opensearch.rest.action.document.RestBulkStreamingAction.lambda$prepareRequest$6(RestBulkStreamingAction.java:127) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]                                                                                                                                                                    
at org.opensearch.rest.action.document.RestBulkStreamingAction.lambda$prepareRequest$7(RestBulkStreamingAction.java:213) …
```
> Handle unsupported media type properly for streaming requests

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
Backport https://github.com/opensearch-project/OpenSearch/commit/b2420f24ae5fe6748e89675eebd20560a5473603 from https://github.com/opensearch-project/OpenSearch/pull/15294
Auto backport failed due to conflicts in `ClusterSettings` class.
> [Backport 2.x] Move timestamp pinning settings to RemoteStoreSettings (#15294)

- server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
Suspecting that BWC test failures are because of this version check, testing it
> BWC fix - correcting shard routing version

- server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
The RepositoriesServiceIT.testUpdateRepository had become flaky after the PR #15426. Build failure link - https://build.ci.opensearch.org/job/gradle-check/46080/. In the earlier PR, we had made a change to randomise the shard_path_type for all the existing snapshot ITs. This tests check that if the repository has no changes then the instance of repository should remain the same. Due to the randomness introduced earlier, this lead to different instance of repository before the update and after the update. This is now fixed by ensuring that we don't change the repository settings when it is not expected to.
- ~[ ] Public …
> Fix RepositoriesServiceIT.testUpdateRepository from #15426

- server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteSplitIndexIT.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/index/translog/Translog.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
- server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogWithPinnedTimestampTests.java
- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
- As part of shallow snapshot optimisations, we are introducing timestamp based implicit locking support. This feature will be called Timestamp Pinning in remote backed storage. When a timestamp is pinned, remote store garbage collectors will skip deleting data corresponding to the timestamp.
- Changes to segment store garbage collection are made as part of PR: https://github.com/opensearch-project/OpenSearch/pull/15017
- In this PR, we are making following changes to translog garbage collection:
- Fetch metadata files in reverse-chronological order
- Filter out metadata files that match with pinned timestamp and metadata files that are created post successful fetch of pinned timestamp.
- From the remaining metadata files, read min and max generation and filter out generations by pinned …
> Add support to skip pinned timestamp in remote translog garbage collector

- server/src/internalClusterTest/java/org/opensearch/snapshots/CorruptedBlobStoreRepositoryIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
In the build of main branch after PR merge, saw couple of more tests that have become flaky. Build link - https://build.ci.opensearch.org/job/gradle-check/46090/. In this PR, we are fixing the tests -
1. [org.opensearch.snapshots.RepositoriesIT.testRepositoryCreation](https://build.ci.opensearch.org/job/gradle-check/46090/testReport/junit/org.opensearch.snapshots/RepositoriesIT/testRepositoryCreation/) - In this test, there is a check to validate that the cluster state uuid has not changed since the update repository does not mutate the repository. I have addded a simple check that checks if the metadata settings have changed or not. If not changed, then the cluster state uuid should also not change.
2. [org.opensearch.snapshots.SnapshotStatusApisIT.testExceptionOnMissingShardLevelSnapBlob …
> Fix flaky tests due to hashed prefix path type snapshots

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
With current implementation of shallow snapshot v2, the create api respond with snapshot info details irrespective of value set for `wait_for_completion` in the request.
**Expected Response** 
For shallow snapshots v2, if `wait_for_completion=false`, the api response should be 
```
{
"accepted" : true
}
```
if `wait_for_completion=true`, the api response should be
```
{
"snapshot" : {
"snapshot" : "my_snapshot_3",
"uuid" : "URJArTYOTOmIFtbv6mbSXQ",
"version_id" : 137217827,
"version" : "3.0.0",
"remote_store_index_shallow_copy" : true,
"pinned_timestamp" : 1724855317025,
"indices" : [
"my-index-1"
],
"data_streams" : [ ],
"include_global_state" : true,
"state" : "SUCCESS",
"start_time" : "2024-08-28T14:28:37.025Z",
"start_time_in_millis" : 1724855317025,
"end_time" : …
```
> Modify create snapshot v2 response when wait_for_completion is false

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexResponse.java
- client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexResponseTests.java
- server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateSettingsIT.java
- server/src/main/java/org/opensearch/OpenSearchServerException.java
- server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexClusterStateUpdateRequest.java
- server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
- server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequestBuilder.java
- server/src/main/java/org/opensearch/action/admin/indices/create/TransportCreateIndexAction.java
- server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexRequest.java
- server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
- server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
- server/src/main/java/org/opensearch/cluster/metadata/Context.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/indices/InvalidIndexContextException.java
- server/src/test/java/org/opensearch/ExceptionSerializationTests.java
- server/src/test/java/org/opensearch/action/admin/indices/create/CreateIndexRequestTests.java
- server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexActionTests.java
- server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexRequestTests.java
- server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexResponseTests.java
- server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- test/framework/src/main/java/org/opensearch/action/support/replication/ClusterStateCreationUtils.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
* Create Index using context
Backport https://github.com/opensearch-project/OpenSearch/pull/15290
https://github.com/opensearch-project/OpenSearch/pull/15290
> [Backport-2.x] Create Index using context 

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/3726c52b31e8504e7fcf9cdc1b52a0a404d6c944 from https://github.com/opensearch-project/OpenSearch/pull/15353
Auto backport failed due to import conflicts in `RemoteRestoreSnapshotIT` class.
> [Backport 2.x] Populate RecoveryState details for shallow snapshot restore (#15353)
