CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java, server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java, server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/gateway/GatewayMetaState.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java, server/src/main/java/org/opensearch/gateway/remote/RemoteUploadStats.java, server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java, server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java, server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Backport #15291 into 2.x branch.
---------
Signed-off-by: Arpit Bandejiya <abandeji@amazon.com>
(cherry picked from commit b54e867da0e313513e90872e039717b7595cf6e4)
=> [Backport 2.x][Remote Publication] Add remote download stats (#15291)

server/src/main/java/org/opensearch/OpenSearchServerException.java, server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java, server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
Fix for version check after merging https://github.com/opensearch-project/OpenSearch/pull/15530
[Resolves #[Issue number to be closed when this PR is merged]
](https://github.com/opensearch-project/OpenSearch/issues/14649)
=> Update version check for context to comply with backport

server/src/main/java/org/opensearch/cluster/metadata/TemplatesMetadata.java, server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java, server/src/test/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadataTests.java
`order` field is missing while deserializing TemplatesMetadata object. This is because it is the first field in the serialized content and we are moving to the next token just before deserialization.
NA
=> Fix missing order field in TemplatesMetadata deserialization

server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java, test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
- Mute flaky tests
- Pinned timestamp flag is disabled until we fix the tests.
=> Disable pinned timestamp flag and mute testRemoteStoreCleanupForDeletedIndex

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsActionIT.java, server/src/main/java/org/opensearch/action/ActionModule.java, server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsAction.java, server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsResponse.java, server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsAction.java, server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateRequest.java, server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequest.java, server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsResponse.java, server/src/main/java/org/opensearch/action/search/TransportSearchAction.java, server/src/main/java/org/opensearch/action/support/TimeoutTaskCancellationUtility.java, server/src/main/java/org/opensearch/action/support/broadcast/BroadcastRequest.java, server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeReadRequest.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/ClusterAdminTask.java, server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java, server/src/test/java/org/opensearch/action/admin/indices/shards/CatShardsResponseTests.java
* Support cancellation for admin apis - add implementation for _cat/shards
Signed-off-by: Somesh Gupta <someshgupta987@gmail.com>
(cherry picked from commit 9f814797d0fe57457359a1f8a1b222cea80dc003)
=> [Backport 2.x] Support cancellation for admin apis (#13966)

CHANGELOG.md, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoryFilterUserMetadataIT.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java, server/src/main/java/org/opensearch/repositories/FilterRepository.java, server/src/main/java/org/opensearch/repositories/Repository.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/action/admin/cluster/snapshots/create/CreateSnapshotResponseTests.java, server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsResponseTests.java, server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java, server/src/test/java/org/opensearch/snapshots/SnapshotInfoTests.java, server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java, server/src/test/java/org/opensearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java, test/framework/src/main/java/org/opensearch/index/shard/RestoreOnlyRepository.java, test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java, test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
This PR backports 
- https://github.com/opensearch-project/OpenSearch/pull/15124
- https://github.com/opensearch-project/OpenSearch/pull/15602
=> [Backport 2.x] Support centralize snapshot creation

libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java, server/src/main/java/org/opensearch/action/admin/cluster/allocation/ClusterAllocationExplanation.java, server/src/main/java/org/opensearch/action/support/nodes/BaseNodeResponse.java, server/src/main/java/org/opensearch/cluster/ClusterState.java, server/src/main/java/org/opensearch/cluster/coordination/Join.java, server/src/main/java/org/opensearch/cluster/coordination/JoinRequest.java, server/src/main/java/org/opensearch/cluster/coordination/StartJoinRequest.java, server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java, server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java, server/src/main/java/org/opensearch/cluster/routing/allocation/AbstractAllocationDecision.java, server/src/main/java/org/opensearch/cluster/routing/allocation/NodeAllocationResult.java, server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java, server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java, server/src/main/java/org/opensearch/indices/recovery/StartRecoveryRequest.java, server/src/main/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormat.java, server/src/main/java/org/opensearch/transport/TransportService.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java, server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java, server/src/test/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormatTests.java
A significant amount of compute and memory goes into ser/de during node to node communications for DiscoveryNode containing a bunch of node properties and attributes which are largely static and doesn't need to passed around for most of the node to node communication. Further, in scenarios like NodeStats call or FollowerChecker requests, single master thread needs to broadcast this DiscoveryNode object containing all these attributes to all the nodes of cluster. In case cluster is very large, this becomes a major bottleneck for master transport thread (which handles other critical operation like ClusterStateUpdate, IndexCreate etc,), which remains blocked till DiscoveryNode object is written.
In this PR we propose to optimise this node to node communication by serializing node attributes …
=> Optimising node to node communication by serializing node attribute in DiscoveryNode only in scenarioes where it is required

server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeTests.java
This change allows the search flows to access StarTreeMetadata so that they can make a decision to cache the query or not based on segment max doc and number of star tree documents.
It also removes the assertion when the child node is not found so that we can gracefully handle the scenarios where we dimension value does not exist in the children.
Resolves #15604
=> [Star Tree] Interfaces Fixes for Star Tree Search

server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
This PR changes SnapshotInfo pinned timestamp version to V_2_17_0 for ser/der. The SnapshotInfo changes were introduced in https://github.com/opensearch-project/OpenSearch/pull/15124
=> [SnapshotV2] SnapshotInfo pinned timestamp version change to V_2_17_0

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
Backport for https://github.com/opensearch-project/OpenSearch/pull/15499
=> [Backport 2.x] Modify create snapshot v2 response when wait_for_completion is false

server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
Co-authored-by: Anshu Agarwal <anshukag@amazon.com>
(cherry picked from commit c62626d25430bea94123d6176caef56ae94deb3f)
Backport for https://github.com/opensearch-project/OpenSearch/pull/15616
=> [Backport] SnapshotInfo pinned timestamp version change to V_2_17_0 (#15616)

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringUtils.java, server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java, server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java, server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsTieringAllocationTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/TieringAllocationBaseTestCase.java
This pr adds canRemain method to TargetPoolAllocationDecider to move shards from local to remote pool for hot to warm tiering. Also, makes changes in the LocalShardsBalancer to not skip the shards tiered from hot to warm.
Related PR: https://github.com/opensearch-project/OpenSearch/pull/14891/
=> Add canRemain method to TargetPoolAllocationDecider to move shards from local to remote pool for hot to warm tiering

server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java
Query Group stats was added in https://github.com/opensearch-project/OpenSearch/commit/c0bcacb52155c9114352765c5105a7caa19dc763
I am seeing build failure by OpenSearch API spec annotation:
```
➜  sarat-opensearch git:(main) ✗ ./gradlew run
Executing Gradle on JVM versions 16 and lower has been deprecated. This will fail with an error in Gradle 9.0. Use JVM 17 or greater to execute Gradle. Projects can continue to use older JVM versions via toolchains. Consult the upgrading guide for further information: https://docs.gradle.org/8.10/userguide/upgrading_version_8.html#minimum_daemon_jvm_version
> Configure project :
========================= WARNING =========================
Backwards compatibility tests are disabled!
See https://github.com/opensearch-project/OpenSearch/issues/4173 …
```
=> Fixing Query Group stats OpenSearch API annotation errors

rest-api-spec/src/main/resources/rest-api-spec/test/index/91_flat_object_null_value.yml, test/framework/src/main/java/org/opensearch/test/NotEqualMessageBuilder.java
This test assumed that the order of returned hits will match the order of insertion. That's not generally true, especially if there was a flush partway through, so documents end up in different segments.
This fixes it by explicitly sorting the returned documents to guarantee that they come back in the correct order.
Also, we were getting a NPE when trying to output the failure message because the expected value was intentionally null. I fixed that too.
N/A (I don't believe we have a flaky-test issue for this one. Thanks @mch2 for bringing it to my attention!) …
=> Fix flaky test in 91_flat_object_null_value.yml

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringUtils.java, server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java, server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java, server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsTieringAllocationTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/TieringAllocationBaseTestCase.java
=> [Backport 2.x] Add canRemain method to TargetPoolAllocationDecider to move shards from local to remote pool for hot to warm tiering (#15010)

CHANGELOG.md, client/rest-high-level/src/test/java/org/opensearch/client/SnapshotRequestConvertersTests.java, qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java, rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.status.json, server/src/internalClusterTest/java/org/opensearch/snapshots/RemoteIndexSnapshotStatusApiIT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java, server/src/main/java/org/opensearch/OpenSearchServerException.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequestBuilder.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestSnapshotsStatusAction.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/main/java/org/opensearch/snapshots/TooManyShardsInSnapshotsStatusException.java, server/src/test/java/org/opensearch/ExceptionSerializationTests.java
---------
(cherry picked from commit 925f41b5635aae02b283866832da3aff6f4049b2)
This PR backports the following two changes to `2.x`:
* #15409
* #15624
=> [Backport 2.x] Backport #15409 and #15624 to 2.x

server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/IndexSettings.java, server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexSettings.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java, server/src/main/java/org/opensearch/index/mapper/DocumentParser.java, server/src/main/java/org/opensearch/index/mapper/MapperService.java, server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java, server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java, server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java, server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java, server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java, server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java, server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
=> [Backport 2.x] Star tree index validations (#15533)

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java, server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
This changes the checksum validation setting for remote cluster state to use different modes rather than just enable/disable. Modes added:
1. None: Validation will be disabled.
2. Debug: Validation enabled but only matches checksum and logs failing entities. 
3. Trace: Matches checksum and downloads full cluster state to find diff in failing entities. Only logs failures.
4. Failure: Throws exception on failing validation.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develop …
=> Changing checksum setting to support modes

server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
Fix version check to 2.17 for BWC of Discovery Node serialization.
=> Fix version check for BWC of Discovery Node serialization

server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
We were earlier depending of RemotePublicationEnabled flag on all nodes to Initializing the RemoteRoutingTableService. But, this can cause issues when we are trying to disable or enable the RemotePublication. We should rather just depend on Routing Table Repos only to decide if we want to initialize the InternalRemoteRoutingTableService or NoopRoutingTableService.
=> Initialize RemoteRoutingTableService when we have RoutingTableRepos

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/NodesHotThreadsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java, server/src/main/java/org/opensearch/action/admin/indices/dangling/find/FindDanglingIndexRequest.java, server/src/main/java/org/opensearch/action/admin/indices/dangling/list/ListDanglingIndicesRequest.java, server/src/main/java/org/opensearch/action/search/GetAllPitNodesRequest.java, server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java, server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java, server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java, server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesInfoAction.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java, server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java, server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java, server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java, server/src/test/java/org/opensearch/action/support/nodes/TransportNodesInfoActionTests.java, server/src/test/java/org/opensearch/action/support/nodes/TransportNodesStatsActionTests.java
Continuation to https://github.com/opensearch-project/OpenSearch/pull/14749, we don't required discovery nodes information in most of the transport actions extending TransportNodesActions, hence un-setting the discovery nodes object for such action before sending transport request to individual nodes this will prevent unnecessary serialization/deserialization of the discovery nodes object.
https://github.com/opensearch-project/OpenSearch/issues/14713 …
=> Reset discovery nodes in all transport node actions request.

server/src/main/java/org/opensearch/common/util/BatchRunnableExecutor.java, server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java, server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java, server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java, server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java, server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java, server/src/test/java/org/opensearch/common/util/BatchRunnableExecutorTests.java, server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java, server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java, server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java, test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Backport https://github.com/opensearch-project/OpenSearch/pull/15176 https://github.com/opensearch-project/OpenSearch/pull/15223
=> [Backport 2.x] Optimise unassigned shards iteration after allocator timeout & Fix responsibility check for existing shards allocator when timed out

server/src/main/java/org/opensearch/common/util/BatchRunnableExecutor.java, server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java, server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java, server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java, server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java, server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java, server/src/test/java/org/opensearch/common/util/BatchRunnableExecutorTests.java, server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java, server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java, server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java, test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Backport https://github.com/opensearch-project/OpenSearch/pull/15648
=> [Backport 2.17] Optimise unassigned shards iteration after allocator timeout & Fix responsibility check for existing shards allocator when timed out 

rest-api-spec/src/main/resources/rest-api-spec/test/snapshot.status/10_basic.yml
Mute failing status tests from MixedClusterClientYamlTestSuiteIT
=> Mute failing status tests from MixedClusterClientYamlTestSuiteIT

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java, server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java, server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java, server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java, server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java, server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java, server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java, test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestUtils.java
For Remote Store clusters, there is validation which ensures that remote attributes are either present / absent in all the nodes in cluster. However for clusters where only remote publication is enabled, this need not be enforced. ClusterManager ensures that the remote connecting node has publication enabled before publishing cluster-state updates[#15216 ]. Incase the remote node does not have publication enabled, it falls back to publish the cluster-state via transport …
=> Relax the join validation for Remote State publication 

server/src/main/java/org/opensearch/repositories/IndexId.java, server/src/main/java/org/opensearch/repositories/RepositoryData.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/repositories/IndexIdTests.java
Set Version to 2.17 for hashed prefix snapshots
Related to https://github.com/opensearch-project/OpenSearch/pull/15426
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-o …
=> [Backport 2.x] Set Version to 2.17 for hashed prefix snapshots

CHANGELOG.md, client/rest-high-level/src/test/java/org/opensearch/client/SnapshotRequestConvertersTests.java, qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java, rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.status.json, server/src/internalClusterTest/java/org/opensearch/snapshots/RemoteIndexSnapshotStatusApiIT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java, server/src/main/java/org/opensearch/OpenSearchServerException.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequestBuilder.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestSnapshotsStatusAction.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/main/java/org/opensearch/snapshots/TooManyShardsInSnapshotsStatusException.java, server/src/test/java/org/opensearch/ExceptionSerializationTests.java
Cherry-pick following commits from `2.x`
* #15595 
* #15642 
=> [Backport] Snapshot Status API changes

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search/270_wildcard_fieldtype_queries.yml, server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
Fix terms related query on wildcard field, original implementation didn't correctly parse the binary string value, causing the search result returns nothing
Resolves #15571
=> fix wildcard term & terms query & add YAML REST test

server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java, server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
I noticed while backporting #13788 that some of the tests were flaky due to multiple segments being created and the correctness being harder to evaluate. Making small fixes to address the flakiness of the tests.
=> Fix approximate pointrangequery tests

server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/IndexSettings.java, server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexSettings.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java, server/src/main/java/org/opensearch/index/mapper/DocumentParser.java, server/src/main/java/org/opensearch/index/mapper/MapperService.java, server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java, server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java, server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java, server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java, server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java, server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java, server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
---------
[Backport 2.x] [Star tree] Star tree index validations (#15533) (#15610)
=> [Backport 2.17] [Star tree] Star tree index validations (#15533) (#15610)

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search/370_approximate_range.yml, server/src/main/java/org/opensearch/common/util/FeatureFlags.java, server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java, server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java, server/src/main/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQuery.java, server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java, server/src/main/java/org/opensearch/search/approximate/ApproximateQuery.java, server/src/main/java/org/opensearch/search/approximate/ApproximateScoreQuery.java, server/src/main/java/org/opensearch/search/approximate/package-info.java, server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java, server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java, server/src/test/java/org/opensearch/index/mapper/RangeFieldQueryStringQueryBuilderTests.java, server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java, server/src/test/java/org/opensearch/index/query/MatchPhraseQueryBuilderTests.java, server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java, server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java, server/src/test/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQueryTests.java, server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java, server/src/test/java/org/opensearch/search/approximate/ApproximateScoreQueryTests.java
Backport #13788  to 2.x
---------
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
Co-authored-by: Michael Froh <froh@amazon.com>
(cherry picked from commit 2e9db40a50735eacc95a4fc8926e8bb7042a696a)
=> [Backport 2.x] Introduce ApproximateRangeQuery and ApproximateableQuery (#13788)

CHANGELOG.md, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/WorkloadManagementPlugin.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequest.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportUpdateQueryGroupAction.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupAction.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupRequest.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupResponse.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/RestUpdateQueryGroupAction.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceService.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/QueryGroupTestUtils.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequestTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/GetQueryGroupResponseTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/QueryGroupActionTestUtils.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupRequestTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupResponseTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceServiceTests.java, plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/api/update_query_group_context.json, plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/test/wlm/10_query_group.yml, server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java, server/src/main/java/org/opensearch/wlm/MutableQueryGroupFragment.java, server/src/test/java/org/opensearch/cluster/metadata/QueryGroupMetadataTests.java, server/src/test/java/org/opensearch/cluster/metadata/QueryGroupTests.java, server/src/test/java/org/opensearch/wlm/MutableQueryGroupFragmentTests.java
Backport 2.17 [Add Update QueryGroup API Logic (#14775)](https://github.com/opensearch-project/OpenSearch/pull/14775)
=> [Backport 2.17] Add Update QueryGroup API Logic (#14775)

server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java, server/src/main/java/org/opensearch/indices/NodeIndicesStats.java
2.x has updated to V_2_17_0, forward port to main to fix bwc.
https://github.com/opensearch-project/OpenSearch/pull/15678/files and https://github.com/opensearch-project/OpenSearch/commit/d2ae53eb0767e2e45e4b12e79a7be1c43f61bb4c were updated on current 2.17 branches, this updates 3.0 to the correct version.
my sanity
=> Fix bwc test failures by updating wire compatibility on NodeIndicesStats

server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotV2IT.java
Mute test testRemoteStoreCleanupForDeletedIndexForSnapshotV2. Related https://github.com/opensearch-project/OpenSearch/issues/15692.
I would revert here but this is not a clean revert with multiple changes since it was introduced, so muting for now.
=> Mute test testRemoteStoreCleanupForDeletedIndexForSnapshotV2

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java, server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/main/java/org/opensearch/indices/NodeIndicesStats.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java, server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java, server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/e146f13a69c8bee87a936416e8998710521518a3 from https://github.com/opensearch-project/OpenSearch/pull/14454.
=> [Backport 2.17] Optimize NodeIndicesStats output behind flag

server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java
Throw `CircuitBreakingException` for too many shards in snapshot status API call
=> CircuitBreakingException for too many shards in snapshot status API call

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java, server/src/main/java/org/opensearch/cluster/service/ClusterManagerThrottlingException.java, server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
2.17 Backport to https://github.com/opensearch-project/OpenSearch/pull/15508
=> [Backport 2.17] ClusterManagerTaskThrottler Improvements (#15508)

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationIT.java, server/src/main/java/org/opensearch/index/IndexModule.java, server/src/main/java/org/opensearch/index/IndexService.java, server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java, server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java, server/src/main/java/org/opensearch/node/Node.java, server/src/test/java/org/opensearch/index/IndexModuleTests.java, server/src/test/java/org/opensearch/index/IndexServiceTests.java, server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
=> [Backport 2.x] [RW Separation] Add polling segment replication for search replicas (#15627)

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/NodesHotThreadsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java, server/src/main/java/org/opensearch/action/admin/indices/dangling/find/FindDanglingIndexRequest.java, server/src/main/java/org/opensearch/action/admin/indices/dangling/list/ListDanglingIndicesRequest.java, server/src/main/java/org/opensearch/action/search/GetAllPitNodesRequest.java, server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java, server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java, server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java, server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesInfoAction.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java, server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java, server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java, server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java, server/src/test/java/org/opensearch/action/support/nodes/TransportNodesInfoActionTests.java, server/src/test/java/org/opensearch/action/support/nodes/TransportNodesStatsActionTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/15131 to 2.17
=> Reset discovery nodes in most transport node actions request. (#15131)

server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotITV2.java, server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java, server/src/main/java/org/opensearch/repositories/Repository.java, server/src/main/java/org/opensearch/repositories/RepositoryData.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Backport for https://github.com/opensearch-project/OpenSearch/pull/15256
=> [Backport 2.x] Support pinned timestamp in delete flow

CHANGELOG.md, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/3fc0139ca68a1ff843ec1492c3cd52c2c4c67f02 from https://github.com/opensearch-project/OpenSearch/pull/15568
=> [Backport 2.x] Optimise snapshot deletion to speed up snapshot deletion and creation(#15568)

server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/SearchPlugin.java, server/src/main/java/org/opensearch/search/DefaultSearchContext.java, server/src/main/java/org/opensearch/search/SearchModule.java, server/src/main/java/org/opensearch/search/SearchService.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchRequestDecider.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java, server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java, server/src/test/java/org/opensearch/search/SearchModuleTests.java, test/framework/src/main/java/org/opensearch/node/MockNode.java
Follow up of https://github.com/opensearch-project/OpenSearch/pull/15363 
Modify the way plugins can provide deciders. 
Provide a factory that plugins can implement to create decider objects.
Resolves https://github.com/opensearch-project/OpenSearch/issues/15259
=> Provide factory for pluggable deciders

server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/SearchPlugin.java, server/src/main/java/org/opensearch/search/DefaultSearchContext.java, server/src/main/java/org/opensearch/search/SearchModule.java, server/src/main/java/org/opensearch/search/SearchService.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchRequestDecider.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java, server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java, server/src/test/java/org/opensearch/search/SearchModuleTests.java, test/framework/src/main/java/org/opensearch/node/MockNode.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/15713
=> [Backport 2.x] Provide factory for pluggable deciders

server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesReader.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/Metric.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java, server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java, server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
---------
(cherry picked from commit 71a771e938f5faf5f6d2d00e0ba27e99e170ed88)
[Star tree][Bug] Fix for derived metrics (#15640) (#15686)
=> [Backport 2.17][Star tree][Bug] Fix for derived metrics (#15640) (#15686)

server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/SearchPlugin.java, server/src/main/java/org/opensearch/search/DefaultSearchContext.java, server/src/main/java/org/opensearch/search/SearchModule.java, server/src/main/java/org/opensearch/search/SearchService.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchRequestDecider.java, server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java, server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java, server/src/test/java/org/opensearch/search/SearchModuleTests.java, test/framework/src/main/java/org/opensearch/node/MockNode.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/15713
=> [Backport 2.17] Provide factory for pluggable deciders

CHANGELOG.md, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/index/IndexService.java, server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java, server/src/main/java/org/opensearch/index/query/QueryShardContext.java, server/src/main/java/org/opensearch/search/DefaultSearchContext.java, server/src/main/java/org/opensearch/search/SearchService.java, server/src/main/java/org/opensearch/search/internal/SearchContext.java, server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java, server/src/test/java/org/opensearch/index/search/NestedHelperTests.java, server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java, test/framework/src/main/java/org/opensearch/index/mapper/FieldTypeTestCase.java
* Add new cluster setting for keyword indexordocvalues query
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
* Fix tests
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
---------
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
(cherry picked from commit d64baa6808a14fa021b16972459257b43ac6b7da)
=> [Backport 2.x] Add new cluster setting for keyword indexordocvalues query (#15637)

server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java, server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/index/shard/StoreRecovery.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java, server/src/main/java/org/opensearch/index/translog/TranslogConfig.java, server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java, server/src/main/java/org/opensearch/repositories/Repository.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java, server/src/main/java/org/opensearch/snapshots/RestoreService.java, server/src/test/java/org/opensearch/index/shard/IndexShardTests.java, server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/7a9cb35a461384d05b49e14d028feee09593c69a from https://github.com/opensearch-project/OpenSearch/pull/15462
Conflicts in: `IndexShard` and `StoreRecovery` classes.
Version is changed in `RecoverySource` and `RestoreSnapshotRequest` from CURRENT to 2.17.0
=> [Backport 2.17] Restore snapshot changes for shallow snapshot V2 (#15462)

CHANGELOG.md, server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java, server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
Remote snapshot file_cache does not strictly limit it's disk usage to its configured capacity. This change causes subsequent requests to the file cache to fail when the cache overflows. #11676 for more details.
Mitigation for #11676
=> Mitigation for remote snapshot filecache overflow

server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
- Mute flaky test RemoteFsTimestampAwareTranslogTests.testSimpleOperationsUpload
- https://github.com/opensearch-project/OpenSearch/issues/15731
=> Mute flaky test RemoteFsTimestampAwareTranslogTests.testSimpleOperationsUpload

server/src/main/java/org/opensearch/cluster/ClusterModule.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsAllocator.java, server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java, server/src/main/java/org/opensearch/node/Node.java, server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/allocator/TimeBoundBalancedShardsAllocatorTests.java, server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java, test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Backport #15565 
* Schedule reroute after allocator timed out
(cherry picked from commit 4f50b4d705deaa971d802cd22fb120f75c722517)
=> [Backport 2.x] Schedule reroute after allocator timed out (#15565)

.github/workflows/assemble.yml
Fixing MacOS 13 asseble workflows
Resolves https://github.com/opensearch-project/OpenSearch/issues/15743
=> Fixing MacOS 13 assemble workflows

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
The test turned out to be flaky, so muting this for now. Would have reverted but this would cause conflict in PRs which need to be merged.
#15767
=> Mute flaky test testRemotePublicationDisabledByRollingRestart

release-notes/opensearch.release-notes-2.17.0.md, server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java, server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/cluster/coordination/RemoteStatePublishRequest.java, server/src/main/java/org/opensearch/gateway/GatewayMetaState.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java, server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
cherry-pick cbdcbb7da3d87fdccfca164ac8f6914a55dc19cb from #15145
=> [Backport 2.17] [Remote State] Upload incremental cluster state on master re-election (#15145)

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/cluster/ClusterHealthIT.java, server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java, server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestBuilder.java, server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java, server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java, server/src/main/java/org/opensearch/cluster/health/ClusterIndexHealth.java, server/src/main/java/org/opensearch/cluster/health/ClusterShardHealth.java, server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java, server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java, server/src/test/java/org/opensearch/cluster/health/ClusterIndexHealthTests.java, server/src/test/java/org/opensearch/cluster/health/ClusterShardHealthTests.java, server/src/test/java/org/opensearch/cluster/health/ClusterStateHealthTests.java
https://github.com/opensearch-project/OpenSearch/issues/11684 - on a large cluster the memory allocation of TransportClusterHealthAction is around 33%. Memory/compute requirement of TransportClusterHealthAction is proportional to the number of indices and shards on the cluster. Transport ClusterHealthResponse maintains health objects for individual indices and shards that can increase the memory allocation of this with the growth of indices and shards count.  At rest layer, there is a room for optimization for _cluster/health API when request is at cluster/indices level by performing inline aggregations and not creating and maintaing shard health objects. 
Changes:
- Introducing a flag ```honourClusterHealthLevel``` in ClusterHealthRequest to identify if the request param ```level``` …
=> Health api memory optimisation

server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
Mute flaky test `org.opensearch.remotemigration.RemoteStoreMigrationSettingsUpdateIT.testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode`
Issue created here: #15793
=> Mute testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode

rest-api-spec/src/main/resources/rest-api-spec/test/snapshot.status/10_basic.yml, server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotITV2.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java, server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/index/shard/StoreRecovery.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java, server/src/main/java/org/opensearch/index/translog/TranslogConfig.java, server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java, server/src/main/java/org/opensearch/repositories/Repository.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java, server/src/main/java/org/opensearch/snapshots/RestoreService.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/index/shard/IndexShardTests.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java, server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
- We have 4 2.x backport PRs that are failing due to changes in each other.
- In this PR, we are combining changes from all these PRs
- https://github.com/opensearch-project/OpenSearch/pull/15794
- https://github.com/opensearch-project/OpenSearch/pull/15796
- https://github.com/opensearch-project/OpenSearch/pull/15797
- https://github.com/opensearch-project/OpenSearch/pull/15798
- https://github.com/opensearch-project/OpenSearch/pull/15613
=> Flaky tests fix in 2.x branch

server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java, server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
- Forward port of https://github.com/opensearch-project/OpenSearch/pull/15462
- Change version to 2.17.0 for shallow snapshot V2 restore changes
=> Change version to 2.17.0 for shallow snapshot V2 restore changes

release-notes/opensearch.release-notes-2.17.0.md, server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java, server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/cluster/coordination/RemoteStatePublishRequest.java, server/src/main/java/org/opensearch/gateway/GatewayMetaState.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java, server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
backport cbdcbb7da3d87fdccfca164ac8f6914a55dc19cb from #15145
=> [Backport 2.x] [Remote State] Upload incremental cluster state on master re-election (#15145)

server/src/main/java/org/opensearch/index/query/AbstractGeometryQueryBuilder.java, server/src/main/java/org/opensearch/index/query/BaseTermQueryBuilder.java, server/src/main/java/org/opensearch/index/query/CommonTermsQueryBuilder.java, server/src/main/java/org/opensearch/index/query/DistanceFeatureQueryBuilder.java, server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java, server/src/main/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilder.java, server/src/main/java/org/opensearch/index/query/GeoBoundingBoxQueryBuilder.java, server/src/main/java/org/opensearch/index/query/GeoDistanceQueryBuilder.java, server/src/main/java/org/opensearch/index/query/GeoPolygonQueryBuilder.java, server/src/main/java/org/opensearch/index/query/MatchBoolPrefixQueryBuilder.java, server/src/main/java/org/opensearch/index/query/MatchPhrasePrefixQueryBuilder.java, server/src/main/java/org/opensearch/index/query/MatchPhraseQueryBuilder.java, server/src/main/java/org/opensearch/index/query/MatchQueryBuilder.java, server/src/main/java/org/opensearch/index/query/MultiTermQueryBuilder.java, server/src/main/java/org/opensearch/index/query/SpanNearQueryBuilder.java, server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java, server/src/main/java/org/opensearch/index/query/WithFieldName.java
Backport 2.x https://github.com/opensearch-project/OpenSearch/pull/15705
=> [Backport 2.x] Adding WithFieldName interface for QueryBuilders with fieldName

.github/workflows/version.yml, CHANGELOG.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/15863 to `2.x`
=> [Backport] [2.x] Bump peter-evans/create-pull-request from 6 to 7 (#15863)

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/metadata/MappingMetadata.java, server/src/main/java/org/opensearch/common/compress/CompressedXContent.java, server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
During checksum validation for remote cluster state, for mapping metadata we need to ignore compressed data check.
=> [BUG] Bug fix for checksum validation for mapping metadata

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java, server/src/main/java/org/opensearch/wlm/QueryGroupLevelResourceUsageView.java, server/src/main/java/org/opensearch/wlm/QueryGroupTask.java, server/src/main/java/org/opensearch/wlm/ResourceType.java, server/src/main/java/org/opensearch/wlm/WorkloadManagementSettings.java, server/src/main/java/org/opensearch/wlm/cancellation/MaximumResourceTaskSelectionStrategy.java, server/src/main/java/org/opensearch/wlm/cancellation/QueryGroupTaskCancellationService.java, server/src/main/java/org/opensearch/wlm/cancellation/TaskSelectionStrategy.java, server/src/main/java/org/opensearch/wlm/cancellation/package-info.java, server/src/main/java/org/opensearch/wlm/tracker/CpuUsageCalculator.java, server/src/main/java/org/opensearch/wlm/tracker/MemoryUsageCalculator.java, server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java, server/src/main/java/org/opensearch/wlm/tracker/ResourceUsageCalculator.java, server/src/test/java/org/opensearch/wlm/QueryGroupLevelResourceUsageViewTests.java, server/src/test/java/org/opensearch/wlm/ResourceTypeTests.java, server/src/test/java/org/opensearch/wlm/cancellation/MaximumResourceTaskSelectionStrategyTests.java, server/src/test/java/org/opensearch/wlm/cancellation/QueryGroupTaskCancellationServiceTests.java, server/src/test/java/org/opensearch/wlm/tracker/ResourceUsageCalculatorTests.java, server/src/test/java/org/opensearch/wlm/tracker/ResourceUsageCalculatorTrackerServiceTests.java
Backport 2.x for https://github.com/opensearch-project/OpenSearch/pull/15651
=> [Backport 2.x] Add cancellation framework changes in wlm (#15651)

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateTermVersionIT.java, server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java, server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java, server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionResponse.java, server/src/main/java/org/opensearch/action/support/clustermanager/term/TransportGetTermVersionAction.java, server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java, server/src/main/java/org/opensearch/cluster/service/ClusterApplier.java, server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java, server/src/main/java/org/opensearch/cluster/service/ClusterService.java, server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java, server/src/main/java/org/opensearch/common/util/FeatureFlags.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCache.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java, server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java, server/src/test/java/org/opensearch/action/support/clustermanager/term/ClusterTermVersionIT.java, server/src/test/java/org/opensearch/cluster/coordination/NoOpClusterApplier.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java, server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
On Term-version mismatch,
1) Fallback to the locally cached cluster-state that is committed in cluster but might not be applied locally.
2) If remote is enabled, download the cluster-state from remote based on term and version.
Resolves #15414 
=> Fallback on Term-Version check mismatch - Remote cluster-state

server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java, server/src/main/java/org/opensearch/repositories/RepositoriesService.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
- Shallow snapshot V2 setting is introduced to enable creating snapshot which uses pinned timestamp functionality of remote store.
- As pinned timestamps are created at cluster level, if multiple repositories enable this feature and create snapshots, clean-up of data from remote store on snapshot deletion becomes tricky and we may end up leaving zombie data in the remote store.
- To avoid this, in this PR, we have added a restriction to have only 1 repository with shallow snapshot V2 enabled.
- In order to enable shallow snapshot V2 setting on another repository, we need to disable this setting on the previously enabled repository as well as delete any snapshots that are created with the previous repo.
- We will ease up this restriction in the upcoming releases.
Resolves #[Issue number to …
=> Add restriction to have a single repository with shallow snapshot v2 setting

server/src/main/java/org/opensearch/tasks/TaskCancellationMonitoringService.java
In TaskCancellationMonitoringService, we track long cancelled tasks via hashmap. Once they are completed, we remove such tasks from the tracker. To do so, earlier we used to traverse the whole entrySet, find the taskId and then remove it which is basically a O(n) operation and unnecessary. Changed it to use remove() directly.
As we saw in one occasion, if a domain is facing too many cancellations and tasks are not getting cleared up, this traversal might become heavy on CPU. …
=> Removing task Id using remove() in TaskCancellationMonitoringService

buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
Add the capability to override `indices.breaker.total.use_real_memory` setting for test clusters.
This will allow plugins to run the integTest with heap CB enabled to ensure that their integTests runs with as close of a env which we have in Jenkins. Please read the attached issue for more details
Validated that setting can be override like this:
```
./gradlew :integTest -Dtests.opensearch.indices.breaker.total.use_real_memory=true
```
Resolves https://github.com/opensearch-project/OpenSearch/issues/15849
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/ …
=> Add the capability to override indices.breaker.total.use_real_memory setting for test clusters

CHANGELOG.md, buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/15858 to `2.x`
=> [Backport] [2.x] Bump org.apache.logging.log4j:log4j-core from 2.23.1 to 2.24.0 in /buildSrc/src/testKit/thirdPartyAudit/sample_jars (#15858)

plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Fix flaky org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case
Resolves https://github.com/opensearch-project/OpenSearch/issues/15840
=> Fix flaky org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case

plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/15859 to `2.x`
=> [Backport] [2.x] Fix flaky org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case (#15859)

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search/270_wildcard_fieldtype_queries.yml, server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
fix case insensitive query on wildcard field
Resolves #15855
=> fix case insensitive query on wildcard field

rest-api-spec/src/main/resources/rest-api-spec/test/snapshot.status/10_basic.yml
This reverts commit 48cf5f061094d89aaa564b97667f4965556a8e49 (#15652)
=> Unmute snapshot status tests from #15652

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemoteDownloadStats.java, server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Adding failure stats for checksum validation failure during remote state download. 
```
"remote_full_download" : {
"success_count" : 1,
"failed_count" : 0,
"total_time_in_millis" : 4,
"checksum_validation_failed_count" : 0
},
"remote_diff_download" : {
"success_count" : 2,
"failed_count" : 0,
"total_time_in_millis" : 9,
"checksum_validation_failed_count" : 0
}
```
=> remote publication checksum stats

plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Followup on this comment https://github.com/opensearch-project/OpenSearch/pull/15859#discussion_r1757696763, removal of the `ConnectionClosedException` was premature:
```
java.lang.AssertionError: expectation "expectErrorMatches" failed (predicate failed on exception: org.apache.hc.core5.http.ConnectionClosedException: Connection is closed)
at __randomizedtesting.SeedInfo.seed([7B0D53ACECB8DFD0:E2197F8350CD27C2]:0)
at reactor.test.MessageFormatter.assertionError(MessageFormatter.java:115)
at reactor.test.MessageFormatter.failPrefix(MessageFormatter.java:104)
at reactor.test.MessageFormatter.fail(MessageFormatter.java:73)
```
- https://build.ci.opensearch.org/job/gradle-check/47887/testReport/org.opensearch.rest/ReactorNetty4StreamingStressIT/testCloseClientStreamingRequest/
- …
=> Fix flaky terminaton conditions for org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case

CHANGELOG.md, server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceAggregationBuilder.java, server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java, server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregationBuilderTests.java, server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
Implement WithFieldName interface in ValuesSourceAggregationBuilder & FieldSortBuilder
This is a continuation of https://github.com/opensearch-project/OpenSearch/pull/15705
=> Implement WithFieldName interface in ValuesSourceAggregationBuilder & FieldSortBuilder

plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/15959 to `2.x`
=> Fix flaky terminaton conditions for org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case (#15959)

server/src/main/java/org/opensearch/wlm/ResourceType.java
Fix breaking API changes introduced during the release window
See please https://github.com/opensearch-project/OpenSearch/actions/runs/10914831970/job/30293590729?pr=15969
=> Fix breaking API changes introduced during the release window

.github/workflows/delete_backport_branch.yml
Refactor branch deletion for backports as current workflow has been failing 2 months. 
https://github.com/opensearch-project/OpenSearch/actions/workflows/delete_backport_branch.yml
The author of the currently used action specified that it is no longer maintained. https://github.com/SvanBoxel/delete-merged-branch/issues/257#issuecomment-2182261868
Hence, refactoring to use GH scripts. Works as expected. See https://github.com/gaiksaya/opensearch-build-libraries/actions/runs/10930031518
Resolves https://github.com/opensearch-project/OpenSearch/issues/15984 …
=> Refactor branch deletion for backports

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/410_nested_aggs.yml, server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java, server/src/main/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregator.java, server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
Fix infinite loop in nested agg
Resolves #15914
=> Fix infinite loop in nested agg

rest-api-spec/src/main/resources/rest-api-spec/test/search/370_bitmap_filtering.yml
The bitmap filtering feature is released in 2.17.0, we need to update the supported version to `2.17.0` in the yaml test file.
Backport 2.x is needed.
No issue.
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable. …
=> Update version check in yaml test file for bitmap filtering

.github/workflows/delete_backport_branch.yml
Fixes the indentation in GHA workflow for deleting backport branches.
=> Fix deleting backport branches workflow

rest-api-spec/src/main/resources/rest-api-spec/test/cluster.put_settings/10_basic.yml
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/15969 to `main`
=> [Forwardport] [main] Update version check in yml test file

.github/benchmark-configs.json
The `big5` workload by default uses 8 ingestion clients to ingest the data. 
During our analysis we understood that the order of data based on timestamp is not maintained during ingestion process and this causes skew in query latencies that use time filters. 
We have re-created the snapshots for big5 after ingesting using 1-client to maintain the timestamp order of the 
By submitting …
=> Update big5 workload config to use the ordered documents snapshot

CHANGELOG.md, server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceAggregationBuilder.java, server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java, server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregationBuilderTests.java, server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
2.x Backport of https://github.com/opensearch-project/OpenSearch/pull/15916
=> [Backport 2.x] Implement WithFieldName interface in ValuesSourceAggregationBuilder & FieldSortBuilder

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java, server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
Add successfulSearchShardIndices in searchRequestContext
This list of indices will be used in the Query-Insights plugin for query shape generation.
Related RFC: https://github.com/opensearch-project/query-insights/issues/69
=> Add successfulSearchShardIndices in searchRequestContext

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java, server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
2.x Backport https://github.com/opensearch-project/OpenSearch/pull/15967
=> [2.x Backport] Add successfulSearchShardIndices in searchRequestContext before onRequestEnd

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml, server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
We had logic in flat_object parsing that would:
1. Try parsing a flat object field that is not an object or null.
2. Would see an END_ARRAY token, ignore it, and not advance the parser.
Combined, this would create a scenario where passing an array of strings for a flat_object would parse the string values, then loop infinitely on the END_ARRAY token.
Resolves #15982
=> Avoid infinite loop in flat_object parsing

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml, server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
Avoid infinite loop in flat_object parsing
We had logic in flat_object parsing that would:
1. Try parsing a flat object field that is not an object or null.
2. Would see an END_ARRAY token, ignore it, and not advance the parser.
Combined, this would create a scenario where passing an array of strings for a flat_object would parse the string values, then loop infinitely on the END_ARRAY token.
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/15985
N/A …
=> [Backport 2.x] Avoid infinite loop in flat_object parsing (#15985)

server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java, test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
In this PR, we are adding integration tests that checks that updating repository settings fail if the repository is in use - create snapshot or delete snapshots are ongoing. …
=> Add ITs for disallow repo settings update during repo in use

CHANGELOG.md, plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java, plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/StatsMetricPublisher.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/S3AsyncDeleteHelper.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/S3AsyncDeleteHelperTests.java, server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsAsyncBlobContainer.java, server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamBlobContainer.java, server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainer.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java, server/src/test/java/org/opensearch/snapshots/BlobStoreFormatTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/2b670cc11f52ada701cbf867ce8ad4527d8b6072 from https://github.com/opensearch-project/OpenSearch/pull/15621.
=> [Backport 2.x] Add support for async deletion in S3BlobContainer (#15621)

server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
Fixing flaky testRemoteIndexPathFileExistsAfterMigration IT. We currently have a hard check on remote-index-path file, and this is resulting into flakiness when indexMetadata changes across runs. We can have a bit lighter check and we can check if `indexUUID` exists in path file name instead of `indexUUID#indexMetadataVersion#RemoteIndexPathVersion`. Sample file name : `remote_path_0kxx2-Y3RqGi9KfxXzqd9A#6#1#zB8i07rPTIWMbYZCgHp0Kg`
Resolves [#14295]
=> Fixing flaky test testRemoteIndexPathFileExistsAfterMigration

server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java, test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
This PR fixes the failing test testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode. The fix has been achieved by adding the SNAPSHOT_SHARD_PATH_PREFIX_SETTING to the docrep node as well.
Resolves #15810  …
=> Fix flaky test in RemoteStoreMigrationSettingsUpdateIT

rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml
After this [PR](https://github.com/opensearch-project/OpenSearch/pull/15985) is backport to 2.x branch, we need to update the version check in the yaml test file from `2.99.99` to `2.17.99`.
Backport to 2.x is needed.
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable. …
=> Update version check in yaml test file for the bug fix of avoid infinite loop in flat_object parsing

server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionResponse.java
Change the version to 2.18 after backport https://github.com/opensearch-project/OpenSearch/pull/16059
=> changing the version to 2.18 as term-check fallback is merged to 2.x

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java, server/src/main/java/org/opensearch/gateway/GatewayMetaState.java, server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
When a remote state enabled cluster manager node boots-up, it tries to download the remote state. But if there some issue while downloading like file not present then the download fails with an exception. The OpenSearch process stays active but unresponsive. This PR addresses this by:
- Adding retries to the download to mitigate the issue where the node is trying to download a stale cluster state
- If the retries fail, bail out by throwing an `Error` so that process exists and a new process is spawned.
NA
- [] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- [] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose) …
=> Retry remote state download while bootstrap

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsGarbageCollectionIT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotV2IT.java, server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java, server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
- Added a bunch of optimisations in remote store garbage collection flow to work with pinned timestamps
- If index is deleted and a snapshot containing the index is getting deleted:
- If this is the last snapshot containing the index, delete remote store data (segments + translog)
- else pass pinning entity for the snapshot that is getting deleted. This is required to delete the data specific to snapshot even if pinned timestamp scheduler runs later.
- For remote translog, avoid calling list metadata files if `minRemoteGenReferenced - indexSettings().getRemoteTranslogExtraKeep() <= maxDeletedGenerationOnRemote`
- For remote translog, make sure to keep metadata and generation deletion in sync. With this, if metadata file is present, we can ensure that generations corresponding to it are …
=> Optimize remote store GC flow with pinned timestamps

server/src/main/java/org/opensearch/rest/action/cat/RestAllocationAction.java
=> Making _cat/allocation API use indexLevelStats

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/360_date_histogram.yml
`yaml=search.aggregation/360_date_histogram/Date histogram aggregation w/ shared field range test` is flaky because it assumes there will only be a single segment created for the test index.
Previously fixed for other similar tests but this test is missing changes which guarantee a single segment: 
https://github.com/opensearch-project/OpenSearch/pull/14486
#14408
=> Fix flaky date histo rest test

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java, server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java, server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java, server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java, server/src/test/java/org/opensearch/action/search/SearchRequestTests.java, server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java, server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Added support for msearch API to pass search pipeline name.
With this change a search pipeline name can be provided while making a msearch call
```
{ "index": "test"}
{ "query": { "match_all": {} }, "from": 0, "size": 10, "search_pipeline": "my_pipeline"}
{ "index": "test-1", "search_type": "dfs_query_then_fetch"}
{ "query": { "match_all": {} }, "search_pipeline": "my_pipeline1" }
```
Resolves https://github.com/opensearch-project/OpenSearch/issues/15748
=> Added support for msearch API to pass search pipeline name

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java, server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java, server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java, server/src/test/java/org/opensearch/action/search/SearchRequestTests.java, server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java, server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/15923
=> [Backport-2.x] Added support for msearch API to pass search pipeline name

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java, server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java, server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
Currently in MIXED compatibility mode, a non-remote node of same version can join the Remote cluster. On similar lines, this fix allows node with RemotePublication repositories configured to join Remote cluster in MIXED mode. 
=> Allow RemotePublication configured nodes to join remote cluster in mixed mode

.github/dependabot.yml
Creating this PR to reduce some noise from dependabot. Dependabot has been making PRs that upgrade google-cloud-storage from 1.x to 2.x which cannot be merged since additional code changes need to be made to adopt 2.x.
This PR mutes dependabot to prevent it from making any more PRs on a major version upgrade for this dependency in any of the modules under the `/plugins` folder.
Example PRs which will require additional changes:
- https://github.com/opensearch-project/OpenSearch/pull/16043
- https://github.com/opensearch-project/OpenSearch/pull/15577
- https://github.com/opensearch-project/OpenSearch/pull/13938
You can find the syntax for dependabot.yml here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
By …
=> Ignore google-cloud-storage and google-api-client major version upgrade for dependabot

server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
Updates version to fix BWC for SearchSourceBuilder from https://github.com/opensearch-project/OpenSearch/pull/15923
=> Updates version to fix BWC for SearchSourceBuilder

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteSnapshotIT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotV2IT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsV2IT.java, server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/snapshots/SnapshotsInProgressSerializationTests.java
1. Adding `IN_PROGRESS` cluster state entry for shallow v2 snapshots. Associated clean up with this. This ensure whatever validations we are doing are atomic in nature. 
2. Pinning timestamp before doing finalize snapshot .
3. Blocking concurrent v2 snapshots. 
=> Shallow snapshot v2 - create snapshot validations in a cluster state update

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsGarbageCollectionIT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotV2IT.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- `RemoteFsTimestampAwareTranslog` has different logic for `trimUnreferencedReaders()` when compared to that of `RemoteFsTranslog`. It considers pinned timestamps and makes sure data against pinned timestamp is not deleted from remote translog.
- `RemoteFsTimestampAwareTranslog.trimUnreferencedReaders()` calls `super.trimUnreferencedReaders()` with the intention of cleaning up local translog files.
- But as `RemoteFsTimestampAwareTranslog` extends `RemoteFsTranslog`, this call to super goes to RemoteFsTranslog which is not aware of pinned timestamps.
- In this PR, we make sure to call `Translog.trimUnreferencedReaders()` from `RemoteFsTimestampAwareTranslog`.
- Even though `RemoteFsTimestampAwareTranslog` is inadvertently calling `RemoteFsTranslog.trimUnreferencedReaders` the super method …
=> [Bugfix] Remote translog does not honour pinned timestamp for low value of indexSettings().getRemoteTranslogExtraKeep()

server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
Post the backport https://github.com/opensearch-project/OpenSearch/pull/16102 , we need to make version 2.18 instead of Current (3.0)
=> [Snapshot V2] Correct the version post backport to 2.18 instead of current for Snapshot Entry SerDe

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/indices/shards/TransportIndicesShardStoresAction.java, server/src/main/java/org/opensearch/cluster/ClusterManagerMetrics.java, server/src/main/java/org/opensearch/cluster/ClusterModule.java, server/src/main/java/org/opensearch/gateway/AsyncShardBatchFetch.java, server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java, server/src/main/java/org/opensearch/gateway/AsyncShardFetchCache.java, server/src/main/java/org/opensearch/gateway/GatewayAllocator.java, server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java, server/src/test/java/org/opensearch/gateway/AsyncShardFetchTests.java, server/src/test/java/org/opensearch/gateway/ShardBatchCacheTests.java, server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java, test/fixtures/azure-fixture/docker-compose.yml
This change adds failure count and success count OTel metrics for async shard fetch
=> Add success and failure count OTel metrics for async shard fetch

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/indices/shards/TransportIndicesShardStoresAction.java, server/src/main/java/org/opensearch/cluster/ClusterManagerMetrics.java, server/src/main/java/org/opensearch/cluster/ClusterModule.java, server/src/main/java/org/opensearch/gateway/AsyncShardBatchFetch.java, server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java, server/src/main/java/org/opensearch/gateway/AsyncShardFetchCache.java, server/src/main/java/org/opensearch/gateway/GatewayAllocator.java, server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java, server/src/test/java/org/opensearch/gateway/AsyncShardFetchTests.java, server/src/test/java/org/opensearch/gateway/ShardBatchCacheTests.java, server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Backport [`8ddb3ee`](https://github.com/opensearch-project/OpenSearch/commit/8ddb3eeee00978913fedd5aa49a84e718538ddae) from #15976
=> [Backport 2.x] Add success and failure count OTel metrics for async shard fetch 

server/src/main/java/org/opensearch/repositories/Repository.java
- With snapshot V2 changes, create flow introduced a new overloaded method of `Repository.finalizeSnapshot`
- But this new method does not have default implementation. Due to this, external repository implementations can fail with compiler error.
- In this PR, we provided a default implementation for the new method.
=> Add default implementation to new finalizeSnapshot() in Repository

release-notes/opensearch.release-notes-2.17.1.md
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/16105 to `main`
=> [Forwardport] [main] Add 2.17.1 release notes (#16104) (#16105)

server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
The following two tests started failing repeatedly from 8/27 to 9/4 and stopped afterwards 
* `org.opensearch.snapshots.SnapshotStatusApisIT.testStatusAPICallForShallowCopySnapshot`
* `org.opensearch.snapshots.SnapshotStatusApisIT.testExceptionOnMissingShardLevelSnapBlob`
[Dashboard](https://metrics.opensearch.org/_dashboards/app/dashboards#/view/e5e64d40-ed31-11ee-be99-69d1dbc75083?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-08-25T18:00:31.813Z',to:'2024-09-05T18:56:20.651Z'))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),query:(language:kuery,query:SnapshotStatusApisIT),timeRestore:!t,title:'OpenSearch%20Gradle%20Check%20Report',viewMode:view))
Both the tests failed with `SnapshotMissingException`. The failures were …
=> Fix flaky tests in SnapshotStatusApisIT

release-notes/opensearch.release-notes-2.17.0.md, server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java, server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/8f34ce5ca3849687d509205bfe4378e1183eb6fb from https://github.com/opensearch-project/OpenSearch/pull/15077.
Mitigation for https://github.com/opensearch-project/OpenSearch/issues/11676
=> [Backport 2.x] Mitigation for remote snapshot filecache overflow

server/src/main/java/org/opensearch/gateway/remote/ClusterStateChecksum.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java, server/src/test/java/org/opensearch/gateway/remote/ClusterStateChecksumTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Backport for PR https://github.com/opensearch-project/OpenSearch/pull/16046
=> [Backport 2.x] Optimize checksum creation for remote cluster state (#16046)

CHANGELOG.md, plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingIT.java, server/src/main/java/org/opensearch/rest/RestController.java
Streaming bulk request hangs
Closes https://github.com/opensearch-project/OpenSearch/issues/16035
=> [BUG] Streaming bulk request hangs

CHANGELOG.md, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
The automated backport failed due to conflicts in the `ChangeLog.md` raised the PR after fixing the conflict.
Signed-off-by: Arpit Bandejiya <abandeji@amazon.com>
(cherry picked from commit 908fefeed32ce205e7b6128a5a344bbf333a5e62)
Backport #15978
=> [Backport 2.x] Change default retry mechanism of s3 client to Standard Mode (#15978)

server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
This PR changes the version checks from `Version.CURRENT` to `Version.V_2_18_0` for the changes introduced in #15611
=> Change version checks from CURRENT to 2.18 in #15611

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java, server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java, server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java, server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java, server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java, test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Currently we have references to `isRemoteStateEnabled` and `isRemotePublicationEnabled` methods at multiple places. We want to create different methods `isRemoteStateConfigured` and `isRemotePublicationConfigured`, which will return true if node attributes are present on the node. 
=> Separate Remote State and Publication enabled and configured methods

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
We update pinned timestamps before finalizing the snapshot . In case post pinning timestamp, finalizing snapshot can fail . This leads to orphan pinned timestamps. This will leak data in remote store. 
In this change, post every create snapshot operation, we find the orphan pinned timestamps and then unpin it . 
=> [Snapshot V2] Remove orphan timestamps post create snapshot completion

CHANGELOG.md, gradle/missing-javadoc.gradle, libs/core/src/main/java/org/opensearch/core/common/Strings.java, libs/core/src/test/java/org/opensearch/core/common/StringsTests.java, plugins/analysis-phonenumber/build.gradle, plugins/analysis-phonenumber/licenses/libphonenumber-8.13.45.jar.sha1, plugins/analysis-phonenumber/licenses/libphonenumber-LICENSE.txt, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalysisPlugin.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzer.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerProvider.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizer.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizerFactory.java, plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java, plugins/analysis-phonenumber/src/test/resources/org/opensearch/analysis/phone/phone_analysis.json, plugins/analysis-phonenumber/src/yamlRestTest/java/org/opensearch/analysis/phone/PhoneNumberAnalysisClientYamlTestSuiteIT.java, plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/10_basic.yml, plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/20_search.yml
this is largely based on [elasticsearch-phone] and internally uses
[libphonenumber].
this intentionally only ports a subset of the features: only `phone` and
`phone-search` are supported right now, `phone-email` can be added
if/when there's a clear need for it.
using `libphonenumber` is required since parsing phone numbers is a
non-trivial task (even though it might seem trivial at first glance!),
as can be seen in the list [falsehoods programmers believe about phone
numbers][falsehoods].
this allows defining the region to be used when analysing a phone
number. so far only the generic "unkown" region (`ZZ`) had been used
which worked as long as international numbers were prefixed with `+` but
did not work when using local numbers (e.g. a number stored as
`+4158...` was not matched against …
=> Implement phone number analyzer

server/build.gradle
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/16141 to `main`
=> [Forwardport] [main] Fix japicmp configuration by treating abstract-to-default method changes as non-breaking

server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java, server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
- Add more unit tests for code flows that are missing test coverage.
=> Add more unit tests for RemoteStoreUtils and RemoteFsTimestampAwareTranslog

CHANGELOG.md, gradle/missing-javadoc.gradle, libs/core/src/main/java/org/opensearch/core/common/Strings.java, libs/core/src/test/java/org/opensearch/core/common/StringsTests.java, plugins/analysis-phonenumber/build.gradle, plugins/analysis-phonenumber/licenses/libphonenumber-8.13.45.jar.sha1, plugins/analysis-phonenumber/licenses/libphonenumber-LICENSE.txt, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalysisPlugin.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzer.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerProvider.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizer.java, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizerFactory.java, plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java, plugins/analysis-phonenumber/src/test/resources/org/opensearch/analysis/phone/phone_analysis.json, plugins/analysis-phonenumber/src/yamlRestTest/java/org/opensearch/analysis/phone/PhoneNumberAnalysisClientYamlTestSuiteIT.java, plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/10_basic.yml, plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/20_search.yml
cherry-pick of #15915
see commit messages (or other PR) for details.
Resolves #11326
=> implement phone number analyzer (cherry-pick to 2.x)

CHANGELOG.md, plugins/repository-s3/build.gradle, plugins/repository-s3/licenses/log4j-slf4j-impl-2.21.0.jar.sha1
Fixes an issue in the repository-s3 plugin which prints warnings on startup related to slf4j:
```
[2024-10-01T14:20:57,070][WARN ][stderr                   ] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2024-10-01T14:20:57,071][WARN ][stderr                   ] SLF4J: Defaulting to no-operation (NOP) logger implementation
[2024-10-01T14:20:57,071][WARN ][stderr                   ] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
This PR is based on a similar PR done in the security plugin: https://github.com/opensearch-project/security/pull/2564
Verified that the messages appear w/o this change and disappear on startup after this change.
Resolves https://github.com/opensearch-project/OpenSearch/issues/16152 …
=> Fix warnings from SLF4J on startup when repository-s3 is installed

server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
- As part of shallow snapshot V2 restore, we introduced `source_remote_translog_repository` field in the `RestoreSnapshotRequest` in order to restore snapshot from one cluster to another.
- But using `source_remote_translog_repository` fails with unknown parameter error:
```
% curl -X POST "localhost:9200/_snapshot/backup-snapshot/S_1/_restore?pretty" -H 'Content-Type: application/json' -d'
{
"indices": "my-index-1",
"source_remote_store_repository": "backup-segment",
"source_remote_translog_repository": "backup-translog"
}
'
{
"error" : {
{
"type" : "illegal_argument_exception",
"reason" : "Unknown parameter source_remote_translog_repository"
}
],
"type" : "illegal_argument_exception",
"reason" : "Unknown parameter source_remote_translog_repository"
},
"status" : 400
} …
```
=> [Bugfix] Fix unknown parameter `source_remote_translog_repository` bug

server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsV2IT.java
Muting snapshot v2 test as observing flakyness in them in https://github.com/opensearch-project/OpenSearch/pull/16191 
=> Mute snapshot v2 flaky tests

CHANGELOG.md, server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregator.java, server/src/test/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregatorTests.java
This PR aims to introduce the following improvements : 
- Reduces the latency of Multi Term Aggregation queries by 7-10 seconds
- Reduces the memory footprint of multi term aggregation queries by decreasing its allocations. 
Testing was done on a `c5.9xlarge` with 20GB of JVM heap and store type as `mmapfs` to ensure any affect of EBS Latencies doesn't affect the result much. The same was verified using `lsof` on the OS pid to ensure all index files are m-mapped ( `mem` is the type in such cases )
The numbers below are averaged after 20 iterations of each type of query with and w/o changes. 
| Workload | Field1 | Field2 | WithoutChanges | WithChanges |
| ------------- | ------------- |------------- | ------------- |------------- |
| big5 | agent_name | host_name | 236 secs | 226 secs | 
| …
=> Latency improvements to Multi Term Aggregations 

CHANGELOG.md, server/src/main/java/org/opensearch/action/ActionModule.java, server/src/main/java/org/opensearch/common/Table.java, server/src/main/java/org/opensearch/rest/RestHandler.java, server/src/main/java/org/opensearch/rest/RestRequest.java, server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java, server/src/main/java/org/opensearch/rest/action/cat/RestTable.java, server/src/main/java/org/opensearch/rest/action/list/AbstractListAction.java, server/src/main/java/org/opensearch/rest/action/list/RestIndicesListAction.java, server/src/main/java/org/opensearch/rest/action/list/RestListAction.java, server/src/main/java/org/opensearch/rest/action/list/package-info.java, server/src/main/java/org/opensearch/rest/pagination/IndexPaginationStrategy.java, server/src/main/java/org/opensearch/rest/pagination/PageParams.java, server/src/main/java/org/opensearch/rest/pagination/PageToken.java, server/src/main/java/org/opensearch/rest/pagination/PaginationStrategy.java, server/src/main/java/org/opensearch/rest/pagination/package-info.java, server/src/test/java/org/opensearch/rest/action/cat/RestIndicesActionTests.java, server/src/test/java/org/opensearch/rest/action/cat/RestTableTests.java, server/src/test/java/org/opensearch/rest/pagination/IndexPaginationStrategyTests.java
* Implementing pagination for _cat/indices
Backporting https://github.com/opensearch-project/OpenSearch/pull/14718
Additionally also fixed the RestHandlerWrapper, which was backported as part of this https://github.com/opensearch-project/OpenSearch/pull/16161 but since this PR is getting merged later in 2.x, added this explicitly:
```
@Override
public boolean isActionPaginated() {
return delegate.isActionPaginated();
}
``` …
=> Implementing pagination for _cat/indices API (#14718)

server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsV2IT.java
Add more concurrent Snapshot V2 Integ Tests #15938 
Correct bug url to the failing test .  
=> Add more concurrent Snapshot V2 Integ Tests

server/src/main/java/org/opensearch/node/Node.java
- `RemoteStorePinnedTimestampService` internally manages an async scheduler.
- If not closed properly, integ tests sometimes fail with following exception:
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=6639, name=opensearch[node_t1][scheduler][T#1], state=RUNNABLE, group=TGRP-RemoteStorePinnedTimestampsGarbageCollectionIT]
at __randomizedtesting.SeedInfo.seed([401E5CF6CD0D4727:9C0BCAD1CF20D2F6]:0)
Caused by: org.opensearch.core.concurrency.OpenSearchRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@143262f2[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2866748[Wrapped task = …
```
=> Close RemoteStorePinnedTimestampService on Node.close()

CHANGELOG.md, test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/16135 to `2.x`
=> [Backport] [2.x] Bump org.jline:jline from 3.26.3 to 3.27.0 in /test/fixtures/hdfs-fixture (#16135)

.github/workflows/delete_backport_branch.yml
Attempt to delete backport branches only for OpenSearch repo. Looks like it is attempting to delete branches of the forks as well that starts with `backport/` https://github.com/opensearch-project/OpenSearch/actions/workflows/delete_backport_branch.yml
Related https://github.com/opensearch-project/OpenSearch/issues/15984
=> Attempt to delete backport branches only for OpenSearch repo

CHANGELOG.md, modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheBaseIT.java, modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheIT.java, modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java, modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java, modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java, modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java, modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java, modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java, plugins/cache-ehcache/src/main/java/org/opensearch/cache/EhcacheDiskCacheSettings.java, plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java, plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java, server/src/main/java/org/opensearch/common/cache/Cache.java, server/src/main/java/org/opensearch/common/cache/CacheBuilder.java, server/src/main/java/org/opensearch/common/cache/settings/CacheSettings.java, server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java, server/src/main/java/org/opensearch/common/cache/store/builders/ICacheBuilder.java, server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java, server/src/main/java/org/opensearch/indices/IndicesRequestCache.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/test/java/org/opensearch/common/cache/CacheTests.java, server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java, server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
=> [Backport 2.x] [Tiered Caching] Segmented cache changes  

server/src/main/java/org/opensearch/common/cache/Cache.java
Fixing Cache breaking change.
We made changes in Cache.java which is a publicApi and renamed below field . This change adds it back.
Related - https://github.com/opensearch-project/OpenSearch/pull/16229. Failing with below 
Status | Modifier | Type | Field | Compatibility Changes:
-- | -- | -- | -- | --
REMOVED (!) | public static final | int (!) | NUMBER_OF_SEGMENTS | ChangeFIELD_REMOVED | Change | FIELD_REMOVED …
=> Fix Cache breaking change

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java, server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
Signed-off-by: David Zane <davizane@amazon.com>
Signed-off-by: Ankit Jain <akjain@amazon.com>
(cherry picked from commit 5279d21f8c85e78a91159af6e17e52789355f2a4)
2.x Backport https://github.com/opensearch-project/OpenSearch/pull/16110
=> Change successfulSearchShardIndices to Set<Index> (#16110)

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml, rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml, rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml, rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/360_date_histogram.yml, rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml
Several aggregation rest tests assert on the number of optimized segments.
`  - match: { profile.shards.0.aggregations.0.debug.optimized_segments: 1 }`
For these tests to be consistent our index can only have a single segment. As such we configure out test indices with 1 shard and no refresh interval to ensure a single segment.
```
settings:
number_of_shards: 1
number_of_replicas: 0
refresh_interval: -1
```
We also force merge in these cases:
```
- do:
indices.forcemerge:
index: <index>
max_num_segments: 1
```
These two operations are redundant so this pr removes the force merge step for these cases.
[Inciting comment
](https://github.com/opensearch-project/OpenSearch/pull/16083#discussion_r1777559595)
By submitting this pull request, I confirm that my contribution is made under the terms …
=> Remove redundant force merge in rest tests

CHANGELOG.md, client/rest-high-level/build.gradle, server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
The `protobuf-java` leaks through client library dependencies
Closes https://github.com/opensearch-project/OpenSearch/issues/16253
=> The protobuf-java leaks through client library dependencies

server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
In RecoveryFromGatewayIT test, the created indices may be not started yet, but is used immediately, which will cause unexpected exception. when it throws the exception, the scene is as follows:
Resolves #14304
=> Fix Flaky Test RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction

server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java, server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
Reverting the name of method from `isRemoteStatePublicationConfigured` to `isRemoteStatePublicationEnabled` since DiscoveryNode is marked as PublicAPI and so the renaming of method would be a breaking change.
The original change was pushed here : https://github.com/opensearch-project/OpenSearch/pull/16080
NA
=> Revert remote publication method renaming in DiscoveryNode

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
- Today, if we try to pin the timestamp that is older than `now() - Lookbak Interval`, we throw `IllegalArgumentException`
- But as `RemoteStorePinnedTimestampService.pinTimestamp` is async, on any failure, `listener.onFailure()` should be called.
https://github.com/opensearch-project/OpenSearch/blob/acf209fc2a23d4f7220b1480c9e407e6cf3d8c55/server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java#L132-L140
- Due to this, caller will keep waiting on listener.
- In this PR, we make sure to call listener.onFailure on each type of failure
- https://github.com/opensearch-project/OpenSearch/issues/16247 …
=> BugFix: call listener.onFailure on failure to pin the timestamp

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryPluginTests.java, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Configuring the thread pool for remote state read and write in order to increase the thread count.
https://github.com/opensearch-project/OpenSearch/issues/16055
=> Reconfigure remote state thread pool count

server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/SnapshotShardPaths.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
In this PR, we are changing the name pattern of the file where we keep the paths for shard blobs for snapshots. This is done to align with the naming pattern we have followed with remote store index shard paths file as well.  …
=> Add snapshot_path prefix to snapshot shards path file on remote store

CHANGELOG.md, server/src/main/java/org/opensearch/action/ActionModule.java, server/src/main/java/org/opensearch/action/admin/cluster/wlm/TransportWlmStatsAction.java, server/src/main/java/org/opensearch/action/admin/cluster/wlm/WlmStatsAction.java, server/src/main/java/org/opensearch/action/admin/cluster/wlm/WlmStatsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/wlm/WlmStatsResponse.java, server/src/main/java/org/opensearch/action/admin/cluster/wlm/package-info.java, server/src/main/java/org/opensearch/client/ClusterAdminClient.java, server/src/main/java/org/opensearch/client/support/AbstractClient.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestWlmStatsAction.java, server/src/main/java/org/opensearch/wlm/QueryGroupService.java, server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java, server/src/main/java/org/opensearch/wlm/stats/WlmStats.java, server/src/test/java/org/opensearch/action/admin/cluster/wlm/WlmStatsResponseTests.java, server/src/test/java/org/opensearch/action/support/nodes/TransportWlmStatsActionTests.java, server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestOperationListenerTests.java, server/src/test/java/org/opensearch/wlm/stats/WlmStatsTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/15777
=> Backport 2.x [Workload Management] QueryGroup Stats API Logic

.github/workflows/precommit.yml, buildSrc/build.gradle, buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java, buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java, buildSrc/version.properties, gradle/code-coverage.gradle, libs/grok/src/main/java/org/opensearch/grok/GrokCaptureConfig.java, plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2DiscoveryTests.java, plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2RetriesTests.java, plugins/repository-hdfs/build.gradle, server/src/main/java/org/opensearch/common/lucene/search/MultiPhrasePrefixQuery.java, server/src/main/java/org/opensearch/index/search/MatchQuery.java, server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java, test/framework/src/main/java/org/opensearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java
Support JDK-23 (build time and runtime)
Part of https://github.com/opensearch-project/OpenSearch/issues/16255
=> Support JDK-23 (build time and runtime)

server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
- Currently, remote store restore cluster state update has NORMAL priority.
- Given that remote store restore is triggered when cluster has unassigned shards, it becomes important to trigger restore as soon as possible.
- Due to NORMAL priority, it is possible that other HIGH/URGENT priority tasks will delay the restore process.
- In this PR, we are changing the remote store restore cluster state update priority from NORMAL to URGENT.
By …
=> Change remote store restore cluster state priority to URGENT

CHANGELOG.md, buildSrc/version.properties, plugins/discovery-gce/build.gradle, plugins/discovery-gce/licenses/grpc-api-1.57.2.jar.sha1, plugins/discovery-gce/licenses/grpc-api-1.68.0.jar.sha1, plugins/repository-gcs/build.gradle, plugins/repository-gcs/licenses/grpc-api-1.57.2.jar.sha1, plugins/repository-gcs/licenses/grpc-api-1.68.0.jar.sha1
Backport of https://github.com/opensearch-project/OpenSearch/pull/16213 to `2.x`
=> [Backport] [2.x] Bump io.grpc:grpc-api from 1.57.2 to 1.68.0 in /plugins/discovery-gce (#16213)

server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
Skip unnecessary string format in RemoteStoreMigrationAllocationDecider when not in debug mode
Master hot thread - 
```
app//org.opensearch.cluster.routing.allocation.decider.RemoteStoreMigrationAllocationDecider.getDecisionDetails(RemoteStoreMigrationAllocationDecider.java:196)
app//org.opensearch.cluster.routing.allocation.decider.RemoteStoreMigrationAllocationDecider.canAllocate(RemoteStoreMigrationAllocationDecider.java:94)
app//org.opensearch.cluster.routing.allocation.decider.AllocationDeciders.canAllocate(AllocationDeciders.java:94)
app//org.opensearch.cluster.routing.allocation.allocator.LocalShardsBalancer.decideAllocateUnassigned(LocalShardsBalancer.java:980)
app//org.opensearch.cluster.routing.allocation.allocator.LocalShardsBalancer.allocateUnassigned(LocalShardsBalancer.java:8 …
```
=> Skip unnecessary string format in RemoteStoreMigrationAllocationDecider when not in debug mode

CHANGELOG.md, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/snapshots/SnapshotsServiceTests.java
In this PR, we have improved the logic for snapshot clone operations for full cluster incremental snapshots. The overall logic stays the same. There is no existing coverage for the snapshot clone operation. At this point, it is going to be huge effort to write unit tests for this flow. 
Resolves #16295 …
=> Optimise clone operation for incremental full cluster snapshots

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Determine pinned timestamp before cluster state update and pin it there itself. 
If we determine it too early and cluster state update to put snapshot in progress itself takes more than 1 min , the timestamp pinning fails "Timestamp to be pinned is less than current timestamp - value of cluster.remote_store.pinned_timestamps.lookback_interval" . Due to this snapshot also fails.
This fix will prevent the above failure , when cluster state update takes whatever amount of time.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cert …
=> [Snapshot V2] Move timestamp pinning before cluster state update

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml, rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml, server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
The pr mainly support the two features: 
1.flat object field use IndexOrDocValuesQuery to optimize query.
2.flat object field delegate to keyword field to reduce code duplication.
Resolves #11635 #11537
=> Flat object field use IndexOrDocValuesQuery to optimize query

.github/benchmark-configs.json
We have guarded the experimental query approximation framework behind a feature flag. In order to easily measure the impact of approximation on big5 benchmarks, it would be nice to have a benchmark config.
This config just copies `id_5`, but adds the feature flag to enable range query approximation.
N/A
=> Add new benchmark config for query approximation

CHANGELOG.md, modules/lang-mustache/src/main/java/org/opensearch/script/mustache/MultiSearchTemplateResponse.java, modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateResponse.java, modules/lang-mustache/src/test/java/org/opensearch/script/mustache/MultiSearchTemplateResponseTests.java, modules/lang-mustache/src/test/java/org/opensearch/script/mustache/SearchTemplateResponseTests.java, modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/50_multi_search_template.yml
Backport https://github.com/opensearch-project/OpenSearch/pull/16265 to 2.x.
=> [Backport 2.x] Fix multi-search with template doesn't return status code (#16265)

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
Coordination metadata contains accepted voting configuration and committed voting configuration.
When the voting configuration changes, the changed accepted voting configuration is sent in publish phase. The follower nodes apply this publish phase cluster state on the `lastSeen` cluster state in PublicationTransportHandler. In the commit phase, each node set the committed voting configuration using the accepted voting configuration by themselves.
When the next cluster state is published, it does not contain any diff in the voting configuration. This next cluster state update uses `lastSeen` again to apply the diff due to which the committed voting configuration is still set to an older value.
With local cluster state publication, this issue does not occur as the entire coordination …
=> Update last seen cluster state in commit phase

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/cluster/settings/ClusterSettingsIT.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/threadpool/ThreadPoolTests.java
Adds capability to change thread pool sizes for all threadpools defined in core
=> Add support to dynamically resize threadpools size

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/cluster/settings/ClusterSettingsIT.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/threadpool/ThreadPoolTests.java
Backport 35c366ddc794e0600184cf406c06ae65061e28ce from [#16269](https://github.com/opensearch-project/OpenSearch/pull/16236)
=> Add support to dynamically resize threadpools size (#16236)

server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java, server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
- This PR is making change `RemoteFsTranslog` and `RemoteFsTimestampAwareTranslog` to ensure following:
- Deletion permits are released when no longer required
- More than `REMOTE_DELETION_PERMITS` are not available at any given point …
=> Fix deletion permits flow in RemoteFsTimestampAwareTranslog

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml, rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml, server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/9ddee61b1b4eafebe9b4d30e997b40178c939a5e from #14383
=> [Backport 2.x] Flat object field should delegate to keyword field for most query types

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/indices.create/10_basic.yml, server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java, server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
When creating an index with setting `index.number_of_routing_shards` to `null`, it fallbacks to a wrong default value which equals to the `number_of_shards`, the default value should be same to the value when the setting is not set when creating index.
https://github.com/opensearch-project/OpenSearch/issues/16327
=> Fix wrong default value when setting index.number_of_routing_shards to null on index creation

distribution/src/config/jvm.options
JDK-23: Mitigation for https://bugs.openjdk.org/browse/JDK-8341127 issue (performance regression)
Part of https://github.com/opensearch-project/OpenSearch/issues/16255
=> JDK-23: Mitigation for https://bugs.openjdk.org/browse/JDK-8341127 issue (performance regression)

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsGarbageCollectionIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java, server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
- If snapshot is created between last fetch of pinned timestamps and index deletion and last metadata file is created before the last fetch, the restore of snapshot will restore data corresponding to previous snapshot
- Consider following set of events:
```
09:58 - second last metadata file
10:00 - S1
10:30 - last metadata file
10:55 - last refresh of pinned timestamp
11:00 - S2
11:05 - Index deleted
```
- Here, restoring S2 will restore data corresponding to snapshot S1.
- In this PR, we make sure to not delete latest metadata file if pinned timestamps are enabled.
- When the last snapshot that has reference to the deleted index gets deleted, the remote data will be cleaned up.
- https://github.com/opensearch-project/OpenSearch/issues/16339
By submitting this pull request, I confirm that …
=> Bugfix in snapshot V2 restore flow

CHANGELOG.md, distribution/tools/keystore-cli/src/test/java/org/opensearch/bootstrap/BootstrapTests.java, server/src/main/java/org/opensearch/bootstrap/Bootstrap.java, server/src/main/resources/org/opensearch/bootstrap/security.policy
root cause:
1. Observability plugin creates system index during cluster startup: [link](https://github.com/opensearch-project/observability/blob/2.x/src/main/kotlin/org/opensearch/observability/ObservabilityPlugin.kt#L96), and if cluster has index block state persisted, during the node startup this block will be applied to cluster state and index creation fails, then this exception is been [thrown](https://github.com/opensearch-project/observability/blob/main/src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt#L110).
2. OpenSearch starts cluster in this [method](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/bootstrap/Bootstrap.java#L339) and the error will be thrown again util the OpenSearch …
=> fix cluster not able to spin up issue when disk usage exceeds threshold

server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotV2IT.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
While cloning v2 snapshot, we need to use  metadata from source snapshot. Earlier we were using cluster state metadata which would not have metadata for deleted indices. 
=> [Snapshot V2] Use metadata from source snapshot while cloning snapshot V2

CHANGELOG.md, modules/percolator/src/main/java/org/opensearch/percolator/QueryAnalyzer.java
Fixed inefficient Stream API call chains ending with count()
=> Fixed inefficient Stream API call chains ending with count()

server/src/main/java/org/opensearch/common/util/ByteArrayBackedBitset.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractDocumentsFileManager.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentBitSetUtil.java, server/src/test/java/org/opensearch/common/util/ByteArrayBackedBitsetTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentBitSetUtilTests.java
1. Optimize metrics in off heap
Currently we initialize metric readers for all metric stats, thereby duplicating field value for each of the stats, when we write star tree document in off heap method.
If we initialize metric readers per metric field instead, we can write and read only the actual field values and when we read and initialize the star tree document, we can set the field's value to all metric stats.
2. Buffer complete star tree document instead of writing individual dimension / metrics to IndexOutput
We can buffer each starTreeDocument in memory and write bytes to indexOutput.
https://github.com/opensearch-project/OpenSearch/issues/16218 …
=> [Star tree] Performance optimizations during flush flow

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java, server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java, server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java, server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java, server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java, server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
cherry-pick 0c3e3c009ae85943460bcc26805c1cf57b195b91 from #15937
=> [Backport 2.x] Make Remote Publication a dynamic setting (#15937)

libs/core/src/main/java/org/opensearch/core/xcontent/MediaTypeRegistry.java
Less intrusive optimization solving the same problem as #16073
Resolves #15979
=> Skip media type parsing for known string values

server/src/main/java/org/opensearch/search/SearchService.java
Fixed assignment to catch block parameter
=> Fixed assignment to catch block parameter

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/ClusterModule.java, server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
This change enables QueryGroupMetadata type to be persistable. To make a `Metadata.Custom` type persistable in `ClusterState`, we need to register the new `Custom` type in `ClusterModule`  at two places
1. `ClusterModule#getNamedXWriteables`
2. `ClusterModule#getNamedWriteables`
We were missing the 1 step in this, hence it was being saved onto the disk but not getting reloaded since `XContentRegistry` did not had any information about this `Custom` type. …
=> make QueryGroups durable

libs/core/src/main/java/org/opensearch/core/common/io/stream/Writeable.java, libs/core/src/test/java/org/opensearch/core/common/io/stream/WriteableTests.java
Added unit test.
Previous PR was prematurely closed https://github.com/opensearch-project/OpenSearch/pull/15367 without letting me react upon the comment.
=> Removed suspicious call of getClass() on instance of Class, which erased type info

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/ClusterModule.java, server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
Backport 2.x for https://github.com/opensearch-project/OpenSearch/pull/16370
=> [Backport 2.x] Make query groups persistent across process restarts (#16370)

CHANGELOG.md, distribution/tools/keystore-cli/src/test/java/org/opensearch/bootstrap/BootstrapTests.java, server/src/main/java/org/opensearch/bootstrap/Bootstrap.java
Revert #15258 to figure out a better approach to fix the issue.
#15258 
=> Revert #15258 to figure out a better approach to fix the issue.

server/src/main/java/org/opensearch/repositories/RepositoriesService.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
When we update a repository-v2 , it fails with 
```
{"error":{"root_cause":[{"type":"repository_exception","reason":"[repo] setting shallow_snapshot_v2 cannot be enabled as this setting can be enabled only on one repository  and one or more repositories in the cluster have the setting as enabled"}],"type":"repository_exception","reason":"[repo] setting shallow_snapshot_v2 cannot be enabled as this setting can be enabled only on one repository  and one or more repositories in the cluster have the setting as enabled"},"status":500}%
```
This is because of bug in `repositoryWithShallowV2Exists` check which doesn't exclude itself while doing the check .
Now we are excluding the repository-v2 which is getting updated . 
By submitting …
=> [Snapshot v2] Fix bug in snapshot update check for multiple v2 repo

server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Currently we do orphan timestamp clean up after sending ack to the client . In between leaving  the repo loop and entering the loop again , if there is a snapshot , we delete the non-orphan time stamp as well . This is because the `repositoryData` which `cleanOrphanTimestamp` has becomes stale.
To simplify this, I intend to do  `cleanOrphanTimestamp`  when we are still in the `repo loop` which means that `repositoryData`  will not change during this .  …
=> [Snapshot V2] Do orphan timestamp cleanup before completing the snapshot

CHANGELOG.md, modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureNetty4Transport.java, server/src/main/java/org/opensearch/plugins/DefaultSecureTransportParameters.java, server/src/main/java/org/opensearch/plugins/SecureTransportSettingsProvider.java
Companion PR in the Security plugin: https://github.com/opensearch-project/security/pull/4820
Fixes an issue with SSL Dual mode where the settings provider relies on the static node settings without taking dynamic cluster settings into account. This PR and companion Security PR fixes a regression introduced in https://github.com/opensearch-project/security/pull/4119
Before 2.14, this setting was coming from the Security plugins [SSLConfig class](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/ssl/transport/SSLConfig.java#L35-L47) which originally gets the value from the node settings, but also registers a cluster settings listener to listen for dynamic updates to this setting.
For instance an operator can run:
```
curl -XPUT …
```
=> Add method to return dynamic SecureTransportParameters from SecureTransportSettingsProvider interface

CHANGELOG.md, server/src/main/java/org/opensearch/action/resync/ResyncReplicationRequest.java, server/src/test/java/org/opensearch/action/resync/ResyncReplicationRequestTests.java
…de(). Added unit test
Previous reincarnation of this PR https://github.com/opensearch-project/OpenSearch/pull/15383
=> Fix array hashCode calculation in ResyncReplicationRequest

server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java, server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
- In https://github.com/opensearch-project/OpenSearch/pull/16332, we provided a solution to always keep last metadata file even if index is deleted.
- But this still does not solve a problem with following scenario:
```
Metadata 1 - 10:30
Pin Timestamp Fetch - 11:00
Snapshot 1 - 11:30
Snapshot 2 - 12:30
Metadata 2 - 13:10
Snapshot 3 - 13:30
DELETE INDEX
```
- In this case, with the existing solution, we will make sure not to delete `Metadata 2` but Metadata 1 will be deleted creating data loss issues for `Snapshot 1` and `Snapshot 2`.
- To solve this problem completely, we need to understand which metadata files need to be kept based on timestamp of pinned timestamps fetch and snapshot timestamp.
- We have following three scenarios:
```
// Scenario 1
Pin Timestamp Fetch
Metadata 1 …
```
=> Treat last fetch timestamp of pinned timestamp as one of the pinned timestamps

server/src/main/java/org/opensearch/snapshots/SnapshotsService.java, server/src/test/java/org/opensearch/snapshots/SnapshotsServiceTests.java
Snapshot UUID itself can have `__` . While extracting Snapshot UUID from pinned entity, we need to factor it in as well . 
=> BugFix - Extract snapshot UUID from pinned entity correctly

server/src/main/java/org/apache/lucene/index/DocValuesProducerUtil.java, server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesReader.java, server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesWriter.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java, server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeDocValuesFormatTests.java
When there are delete operations in the index, there are segments where `SegmentDocValuesProducers` is present which contains `List<DocValuesProducers>` contrary to segments in index where no deletes are present.
So one change is to pick `DocValuesProducer` in the list where `StarTreeValues` is present - usually I see that one field is present only in one of the `DocValuesProducer` - even `SegmentDocValuesProducer` has a map of `FieldInfo` to `DocValuesProducer` which confirms the same.
Secondly there are issues because of `segmentSuffix` missing in the custom write state and read state. So have added the same.
Also including fixes from https://github.com/opensearch-project/OpenSearch/pull/16124 
Resolves https://github.com/opensearch-project/OpenSearch/issues/16381 …
=> [Star tree] Handle delete cases for star tree

server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestSnapshotsStatusAction.java
* In #15409, 
* We added changes to impose an upper limit on the number of shards that can be included in the snapshot status API's response with the help of `snapshot.max_shards_allowed_in_status_api` dynamic cluster setting.
* We also added a variant of the API to pass a comma-separated list of index names (for a singular snapshot only) to manage the shard count in its response
* We also need to extend the same to the shards contributed by running snapshots in the APIs response. 
* While calculating the total number of required shards in the response, the shards of running snapshots must also be accounted for.
* Similarly, users should be able to pass an index list for a running snapshot and get status for only the relevant indices in the response   
* Added stricter checks for when to …
=> Snapshot _status API: Include in-progress snapshots in total shard count and index filter

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/TasksIT.java, server/src/main/java/org/opensearch/tasks/TaskResultsService.java, server/src/test/resources/org/opensearch/tasks/missing-fields-task-index-mapping.json
Resolves #16060
<br>
* Click the image to view it in full size.
| Before | After |
|--------|-------|
| ![before](https://github.com/user-attachments/assets/be929930-24f2-4175-988e-3cebec6b22a4) | ![after](https://github.com/user-attachments/assets/efe95b8c-85a6-4681-b6c7-881454bd2e5c) |
|`StrictDynamicMappingException` occurred|not occurred|
- When applying and then deleting the auto follow rule in the `CCR Plugin`(cross-cluster-replication), the `.tasks` index is properly updated without `StrictDynamicMappingException`.
- OpenSearch allows a Follower Cluster to replicate indexes from a Leader Cluster through the [Opensearch CCR Plugin](https://github.com/opensearch-project/cross-cluster-replication).
- However, when cancelling the `auto follow` rule in the CCR Plugin, a …
=> [BUGFIX] Fix missing fields to resolve Strict Dynamic Mapping issue when saving task result

CHANGELOG.md, server/src/main/java/org/opensearch/action/resync/ResyncReplicationRequest.java, server/src/test/java/org/opensearch/action/resync/ResyncReplicationRequestTests.java
Backport 0f7d572da1d2dec4c2b83c6ae2c9e47ce38edd00 from #16378
=> [Backport 2.x] Fix array hashCode calculation in ResyncReplicationRequest (#16378)

server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java
Fixes the usage of inline javadocs in paginationStrategy interface causing build failures on older jdk versions.
Resolves https://github.com/opensearch-project/OpenSearch/issues/16374
=> Fixing inline javadocs usage in PaginationStrategy

CHANGELOG.md, qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/ClusterStatsIT.java, server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIndices.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequestBuilder.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsResponse.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java, server/src/main/java/org/opensearch/index/cache/query/QueryCacheStats.java, server/src/main/java/org/opensearch/index/fielddata/FieldDataStats.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java, server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsResponseTests.java, server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsActionTests.java
* URI path filtering support in cluster stats API
(cherry picked from commit 19824275fe78014249143724c5b84a6211e6e642)
Backport https://github.com/opensearch-project/OpenSearch/pull/15938 to 2.x
=> URI path filtering support in cluster stats API (#15938)

CHANGELOG.md, modules/percolator/src/main/java/org/opensearch/percolator/QueryAnalyzer.java
Backport 1a7018abf1884a287d05681358efa600471c810b from #15386
=> [Backport 2.x] Fixed inefficient Stream API call chains ending with count() (#15386)

server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java, server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java, server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java, server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
This PR fixes a bug with node-node pull based replication where store refs are left open. If the replica does not know the DiscoveryNode of its primary we would fail late only after replication is started and a ref is not cleaned up. Push based replication already handled this case by catching any error and closing the SegmentReplicationTarget, which holds the ref. This update ensures the validation is done before constructing our PrimaryShardReplicationSource, before any target object is created in both cases push and pull.
Resolves https://github.com/opensearch-project/OpenSearch/issues/15812 …
=> Fix unclosed store references with SearchOnlyReplicaIT

buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java, buildSrc/version.properties
Update JDK to 23.0.1
Part of https://github.com/opensearch-project/OpenSearch/issues/16354
=> Update JDK to 23.0.1

CHANGELOG.md, server/src/main/java/org/opensearch/wlm/QueryGroupService.java, server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
Backport 2.x for https://github.com/opensearch-project/OpenSearch/pull/16417
=> [Backport 2.x] Improve the rejection logic for soft mode query groups during node duress (#16417)

CHANGELOG.md, gradle/missing-javadoc.gradle, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequest.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportCreateQueryGroupAction.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportUpdateQueryGroupAction.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupRequest.java
WLM create/update REST APIs were not setup correctly since the APIs need to execute a clusterManager operation hence corresponding classes should extend `TransportClusterManagerNodeAction` class. This change is to fix it.
previously when these two apis were resulting into an error like following when accessed using either cluster endpoint or non-cluster-manager node
```
{
"error" : {
{
"type" : "not_cluster_manager_exception",
"reason" : "no longer cluster-manager. source: [query-group-persistence-service]"
}
],
"type" : "not_cluster_manager_exception",
"reason" : "no longer cluster-manager. source: [query-group-persistence-service]"
},
"status" : 500
}
```
After the fix it goes through and looks like following
```
{
"_id": "nvhPln8WReOXuinM1gmMzw",
"name": "dpp", …
```
=> Wlm create/update REST API bug fix

CHANGELOG.md, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequest.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportCreateQueryGroupAction.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportUpdateQueryGroupAction.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupRequest.java
Backport 2.x for https://github.com/opensearch-project/OpenSearch/pull/16422
=> [Backport 2.x] Wlm create/update REST API bug fix (#16422)

server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsV2IT.java, server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Earlier we were accepting deletes while a create/clone v2 operation was going on . Post create/clone, we did a `runNextQueuedOperation` to run the queued operation . However , `runNextQueuedOperation` creates a pending task of `NORMAL` priority . In cases where pending tasks are high , this will starve. Meanwhile , the new create/clone v2 snapshots also can't start as it won't get the repo lock .
To solve for this, we are not accepting deletes when a create/clone v2 operation is going on and have now removed the `runNextQueuedOperation`. 
```
% curl localhost:9200/_cat/pending_tasks
374716  3.7s HIGH   cluster_reroute(reroute after balanced shards allocator timed out)
374646 24.1m NORMAL Run ready deletions
```
By submitting this pull request, I confirm that my contribution is made under …
=> Disallow snapshot deletion while a v2 snapshot is in progress

modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureNetty4Transport.java
Small PR to add a logline back in that was inadvertently removed in https://github.com/opensearch-project/OpenSearch/pull/16387
=> Add log message if SSL dual mode is enabled

buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java, buildSrc/version.properties
Update JDK to 11.0.25
Part of https://github.com/opensearch-project/OpenSearch/issues/16354
=> Update JDK to 11.0.25

CHANGELOG.md, server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
This PR addresses an issue in the `testApproximateRangeWithSizeOverDefault` method of `ApproximatePointRangeQueryTests`, where the test would occasionally fail due to how Lucene handles total hits.
By default, `search()` in Lucene's `IndexSearcher` provides an accurate count for up to 1000 hits.
Beyond this threshold, Lucene may return a lower bound using GREATER_THAN_OR_EQUAL_TO for performance reasons (refer to the [Lucene IndexSearcher documentation](https://lucene.apache.org/core/9_11_0/core/org/apache/lucene/search/IndexSearcher.html).)
In `testApproximateRangeWithSizeOverDefault`, the search range includes 12,001 documents, and the test would sometimes fail when `GREATER_THAN_OR_EQUAL_TO` occurred during the search.
Changes:
- If totalHits.relation is `EQUAL_TO`, the test checks for …
=> Fix flaky test in testApproximateRangeWithSizeOverDefault by adjusting totalHits assertion logic

server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsResponse.java, server/src/main/java/org/opensearch/action/pagination/PageParams.java, server/src/test/java/org/opensearch/action/admin/cluster/shards/CatShardsRequestTests.java
Updating version to 2.18.0 for `CatShardsRequest` and `CatShardsResponse` which were added as 3.0.0 as part of https://github.com/opensearch-project/OpenSearch/pull/14641
=> Update version to 2.18.0 for CatShards request and response

server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
Downgrade version to 2.18.0 for serialization/deserialization of new parameters of RequestRequest added in [PR #16292](https://github.com/opensearch-project/OpenSearch/pull/16292) since [it has been back ported into that version](https://github.com/opensearch-project/OpenSearch/pull/16447).
=> Downgrade version to 2.18.0 for ser/de of new parameters of RequestRequest

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/gateway/GatewayMetaState.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java, server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java, server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
When cluster is upgraded from 2.16 or lower to 2.17, the new cluster manager nodes are not able to join the cluster due to deserialization failure while downloading the manifest. The stacktrace is below:
```
FailedToCommitClusterStateException[publishing failed]; nested: XContentParseException[[-1:616] [cluster_metadata_manifest] failed to parse field [indices]]; nested: XContentParseException[[-1:599] [uploaded_index_metadata] unknown field [component_prefix]];
at org.opensearch.cluster.coordination.Coordinator.publish(Coordinator.java:1397)
at org.opensearch.cluster.service.MasterService.publish(MasterService.java:384)
at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:366)
at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:228)
at …
```
=> Revert uploading of remote cluster state manifest using min codec version

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java, server/src/main/java/org/opensearch/cluster/routing/allocation/Constraint.java, server/src/main/java/org/opensearch/cluster/routing/allocation/ConstraintTypes.java, server/src/main/java/org/opensearch/cluster/routing/allocation/RebalanceConstraints.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
Add new setting to control the weight added by primary constraints in weight during allocation and rebalance.
Resolves #16470 
=> Add Setting to adjust the primary constraint weights

rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_settings/40_number_of_routing_shards.yml
After this [PR](https://github.com/opensearch-project/OpenSearch/pull/16294) is backported to 2.x branch, we need to correct the version check in the yaml test file.
Change los and backport 2.x are not needed.
No issue.
=> Update version check in yaml test file for the bug fix for get index settings API

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java, server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java, server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
When a node with publication repositories are configured, cluster-manager updates the repositories metadata in cluster-state after validation.
Resolves #[16363](https://github.com/opensearch-project/OpenSearch/issues/16363)
=> create publication repos during join task execution

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/SearchTaskRequestOperationsListener.java, server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java, server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java
This PR (https://github.com/opensearch-project/OpenSearch/pull/13172) introduced shard-level resource usage tracking by adding task resource usage objects to the node response headers. However, by default, all headers from the thread context are added to the response header: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/http/DefaultRestChannel.java#L156
This behavior could lead to excessive headers being sent to the client, potentially impacting latency. To address this, we now explicitly remove task-related headers before sending the response to the client.
before the changes, run an opensearch cluster and insert some document. Do search and get response headers.
```
➜  OpenSearch git:(main) ✗ curl -v -X GET …
```
=> Remove resource usages object from search response headers

CHANGELOG.md, server/src/main/java/org/opensearch/index/fielddata/plain/SortedNumericIndexFieldData.java, server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
Implement the `LeafFieldData#getLeafValueFetcher` method for unsigned long field to support retrieving doc values.  Previously, attempting to use the `docvalue_fields` parameter to access doc values would result in a UOE being thrown.
=> Support retrieving doc values of unsigned long field

server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java
Doing the type check before the string comparison makes it much faster to resolve derived fields.
=> Improve performance for resolving derived fields

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/indices/alias/TransportIndicesAliasesAction.java, server/src/main/java/org/opensearch/action/admin/indices/rollover/TransportRolloverAction.java, server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java, server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java, server/src/test/java/org/opensearch/cluster/block/ClusterBlocksTests.java
Backports 4c35a2b418aa4cf14b8f49d7639d386b96752ae8 from #16483 to `2.x`
=> [Backport 2.x] fix rollover alias supports restored searchable snapshot index (#16483)

buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
There were a few issues here: the '-x64' suffix was being unconditionally appeneded, debian uses underscores not hyphens, and the rpm target uses the '.86_64' suffix.
This feels like a hack, but the `./gradlew distribution:bwc:minor:buildBwc` task now succeeds with this commit, whereas previously several of the targets failed. I've tested this on Intel Linux, Arm Linux, and Apple Silicon Mac. I think during a normal `check` run only the target that corresponds to the platform doing the building is executed, which is why the other targets were broken but no one had noticed. I'll happily entertain any suggestions on how to add a test for this!
Resolves #16535
For more …
=> Fix non-x64 bwc build targets

server/build.gradle
The `japicmp` plugin was configured to fail only on binary incompatible changes (which new interface method isn't), making checks strick by failing on source  incompatible changes.
Closes https://github.com/opensearch-project/OpenSearch/issues/16175
=> Detect Breaking Changes check does not fail on new method added to an @PublicApi interface

CHANGELOG.md, server/src/main/java/org/opensearch/env/NodeEnvironment.java, server/src/main/java/org/opensearch/index/store/IndexStoreListener.java, server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java, server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
I have a use case where I have a custom file cache implementation and in order to not have dangling entries in my fc I need to implement `IndexStoreListener` to clean up my file cache when shards move off a node. Today that is not possible as `IndexStoreListener` is an `@opensearch.internal` interface and not pluggable, which this PR changes.
Long term I think the solution is to make the FileCache itself pluggable, but that is much more complicated and anyways would require us to expose this interface as pluggable, so I believe this is a useful intermediary step.
The other thing to note is in `Node.java` I am now creating the `CompositeIndexStoreListener` regardless of if it `isSearchNode()` or not as it should be up to the specific listener implementations to determine how/when to …
=> Make IndexStoreListener a pluggable interface

server/src/test/java/org/opensearch/action/admin/cluster/shards/CatShardsRequestTests.java
One of the version changes from https://github.com/opensearch-project/OpenSearch/pull/16455/files was missed when it was manually backported in https://github.com/opensearch-project/OpenSearch/pull/16396.
The test in question is intended to check for a previous version that does not read the array of null strings.  By leaving it at `Version.CURRENT` it bumped to 2.18.1 where 2.18.0 was the previous version and incorrectly tried to read that array.
Resolves #16580 …
=> [2.18] Fix NPE in CatShardsRequestTests on version bump

modules/search-pipeline-common/src/internalClusterTest/java/org/opensearch/search/pipeline/common/SearchPipelineCommonIT.java
Adds Integration Tests for Search Pipeline
=> Adds Integration Tests for Search Pipeline

CHANGELOG.md, server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java, server/src/main/java/org/opensearch/index/query/QueryShardContext.java, server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Add a flag in QueryShardContext to differentiate inner hit query and normal query.
For k-NN nested fields, the query currently searches for the nested field document with the highest score for each parent document, returning only a single nested field document in the inner hit block. We want to modify this query behavior to retrieve all nested field documents in the inner hit block, rather than just the one with the highest score. To implement this, we need to identify whether the current query request is targeting an inner hit block or not.
* One alternatives is using stack trace to see if the query is made inside `NestedInnerHitContextBuilder`. This will increase query latency.
* Another alternative is making the k-NN nested query behavior to be same regardless it is for inner hit block …
=> Add a flag in QueryShardContext to differentiate inner hit query

CHANGELOG.md, server/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/16614 to `2.x`
=> [Backport] [2.x] Bump me.champeau.gradle.japicmp from 0.4.4 to 0.4.5 in /server (#16614)

CHANGELOG.md, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Currently, snapshot repository data is not cached if its compressed size exceeds 500KB.
This static limit causes repeated downloads in operations like clone, restore, and status checks, increasing latency.
The limit has not been adjusted for larger heap sizes, impacting repositories with numerous snapshots.
It doesn’t adjust with vertical or horizontal scaling. This restricts caching efficiency, even with enhanced system resources.
***
The new setting, `opensearch.snapshot.cache.threshold`, allows users to adjust the cache limit as a percentage of heap size. To maintain consistency in how cache sizes are set across OpenSearch, I referenced existing configurations like [indices.requests.cache.size and indices.fielddata.cache.size](https://opensearch.org/docs/latest/install-and-configure/con …
=> Add vertical scaling and SoftReference for snapshot repository data cache

CHANGELOG.md, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java, server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/16489 to `2.x`
=> [Backport] [2.x] feat: add vertical scaling and SoftReference for snapshot repository data cache (#16489)

CHANGELOG.md, modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java, modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymGraphTokenFilterFactory.java, modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java, modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java, modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java, server/src/main/java/org/opensearch/indices/analysis/AnalysisModule.java, server/src/main/java/org/opensearch/plugins/AnalysisPlugin.java, server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java, test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/16488.
Part of https://github.com/opensearch-project/OpenSearch/issues/16263 and https://github.com/opensearch-project/OpenSearch/issues/16530.
=> [Backport 2.x] Add a new configuration setting `synonym_analyzer` for `synonym_graph` and synonym

server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/SnapshotShardPaths.java, test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
If the index name has `.` period in it, then the stale index deletion fails as the period character interferes with the delimiter (which is also period character) by giving more parts than expected during the `String.split(".")` operation while interpreting the snapshot shards path file. The fix is to handle the variables after the index name as relative from last than from 0. This fixes the problem. …
=> Fix stale index deletion in snapshots for hashed prefix path type

CHANGELOG.md, distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java, distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
Support installing plugin SNAPSHOTs with SNASPHOT distribution
```
/opensearch-2.19.0-SNAPSHOT$ ./bin/opensearch-plugin install transport-reactor-netty4
-> Installing transport-reactor-netty4                                                                                                                                     
-> Downloading transport-reactor-netty4 from opensearch                                                                                                                    
[=================================================] 100%                                                                                                                   
```
Part of https://github.com/opensearch-project/opensearch-build/issues/5096, addresses …
=> Support installing plugin SNAPSHOTs with SNASPHOT distribution

DEVELOPER_GUIDE.md
Update DEVELOPER_GUIDE.md instructions for JDK-11, fixes the annoying deprecation failure:
```
Executing Gradle on JVM versions 16 and lower has been deprecated. This will fail with an error in Gradle 9.0. Use JVM 17 or greater to execute Gradle. Projects can continue to use older JVM versions via toolchains. Consult the upgrading guide for further information: https://docs.gradle.org/8.10.2/userguide/upgrading_version_8.html#minimum_daemon_jvm_version
> Configure project :
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 8.10.2
OS Info               : Linux 6.11.0-9-generic (amd64)
JDK Version           : 11 (Ubuntu JDK)
JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
Random Testing Seed   : AE535EC00EACC589
In FIPS 140 mode …
```
=> Update DEVELOPER_GUIDE.md instructions for JDK-11

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
Update the version check from `3.0.0` to `2.13.0` as the change in this  [PR](https://github.com/opensearch-project/OpenSearch/pull/11499) was released in 2.13.0.
Change log is not needed, backport to 2.x is needed.
No issue.
=> Update version check in yaml test file for allowing composite aggregation to run under a parent filter aggregation

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml, server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/IpFieldTypeTests.java
it fixes an edge case when docvalues-only (index:false) IP field is queried via IP mask (1.2.3.4/22 syntax). Now such query is ignored, this change makes it work. 
relate #11508 
- [v] Functionality includes testing.
=> Search dv only IP masks

CHANGELOG.md, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
When remote cluster state publication is enabled, cluster state custom objects get uploaded to remote store. The stale file deletion logic deletes stale remote state files. But the cluster state custom files are not getting deleted.
This PR fixes the logic for stale cluster state custom file deletion.
NA
=> Fix stale cluster state custom file deletion

build.gradle, buildSrc/src/main/groovy/org/opensearch/gradle/test/TestWithDependenciesPlugin.groovy, buildSrc/src/main/java/org/opensearch/gradle/LoggedExec.java, buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java, buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java, gradle/missing-javadoc.gradle, gradle/wrapper/gradle-wrapper.properties, libs/build.gradle, modules/lang-painless/build.gradle
Update to Gradle 8.11 (https://github.com/gradle/gradle/releases/tag/v8.11.0)
N/A
=> Update Gradle to 8.11

server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/indices/IndicesRequestCache.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
Followup to https://github.com/opensearch-project/OpenSearch/pull/16484. @kkhatua pointed out we may want to set some maximum size for a query to enter the cache, rather than just allowing or not allowing all size > 0 queries. For example, sizes as large as 10,000 are sometimes used, and letting them in may take up too much cache space. Also, queries with extremely large sizes spend more time in the fetch phase, so they benefit less from the request cache. 
This PR changes the new setting to be an int, which is the maximum size allowed into the cache. The default value is 0, so the earlier behavior is still maintained. 
Based on benchmarking so far, a reasonable non-zero value for this setting might be around 200, but benchmarks of very large sizes are still ongoing. 
Since the original …
=> Change setting allowing size > 0 queries in request cache to be an int threshold

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemoteDownloadStats.java, server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java, server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Backport for https://github.com/opensearch-project/OpenSearch/pull/16682
Automated backport failing with codecov, adding more tests in this PR.
=> [Backport 2.x] Backport remote publication stats

CHANGELOG.md, buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle
---------
Manual backport: https://github.com/opensearch-project/OpenSearch/pull/16718
=> [Backport 2.x] Bump org.apache.logging.log4j:log4j-core from 2.24.1 to 2.24.2 in /buildSrc/src/testKit/thirdPartyAudit

server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWithRandomExceptionsIT.java
As the index refresh may fail, so the translog in the index will be not flushed, and `TranslogWriter.buffer` is not null, which causes arrays not been released, so we need to close the index to release the arrays.
Why `TransportSearchFailuresIT.testFailedSearchWithWrongQuery` is successfully is the refreshing index is successful.
Resolves #15828
=> [Flaky Test] Fix Flaky Test SearchWithRandomExceptionsIT.testRandomExceptions

modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/75_update.yml
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/16756 to `main`
=> [Forwardport][main] Deprecate performing update operation with default pipeline or final pipeline

modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/75_update.yml
In this [PR](https://github.com/opensearch-project/OpenSearch/pull/16712), we have some yaml tests to verify that the update API can return deprecation warning header under some condition, but by accident, I found that the [`allowed_warnings` command in the second test case](https://github.com/opensearch-project/OpenSearch/blob/ac456430d6159a21a8899a95bc64208f6f4c9eb5/modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/75_update.yml#L89) in 75_update.yml takes no effect, change  the warning message to a random string and even remove the `allowed_warnings`, the test case still passes, after diving deep into this, I found the reason is that we only log the deprecation log and return the warning header [once](https://github.com/opensearch-project/OpenSearch/blob/ac45643 …
=> Fix allowed_warnings takes no effect for the yaml test in 75_update.yml

CHANGELOG.md, server/src/main/java/org/opensearch/common/logging/DeprecatedMessage.java, server/src/main/java/org/opensearch/common/logging/DeprecationLogger.java, server/src/test/java/org/opensearch/common/logging/DeprecationLoggerTests.java
Backports b1bf72f26e2681e4dbe726bc9605209675f6ab38 from #16724
=> [Backport 2.x] Bound the size of cache in deprecation logger (#16724)

buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java, buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
Refactor Docker Compose version detection to predictably pick v2 only if v1 is not available. At the moment, if V1 and V2 are installed, the V1 is checked but ignored, with no option to be picked up.
Followup on https://github.com/opensearch-project/OpenSearch/pull/16049
=> Refactor Docker Compose version detection to predictably pick v2 only if v1 is not available

CHANGELOG.md, release-notes/opensearch.release-notes-1.3.20.md
=> [1.3] Add 1.3.20 Release Notes

plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java, plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureRepositorySettingsTests.java, plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java
Consolidate cleanup for Azure blob tests
Followup on https://github.com/opensearch-project/OpenSearch/pull/16778
=> Consolidate cleanup for Azure blob tests

CHANGELOG.md, server/src/main/java/org/opensearch/common/time/DateUtils.java, server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java, server/src/test/java/org/opensearch/common/time/DateUtilsTests.java, server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java, server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
Coming from https://github.com/opensearch-project/OpenSearch/issues/16709#issuecomment-2525359848 added a precaution to handle extreme date values during sorting to prevent `arithmetic_exception: long overflow`.
https://github.com/opensearch-project/OpenSearch/issues/16709 and https://github.com/opensearch-project/OpenSearch/issues/5713.
=> Overflow prevention when handling date values

test/fixtures/hdfs-fixture/build.gradle
Forces the transitive dependency on commons-io to a non-impacted version.
Fixes CVE-2024-47554
Note: as a transitive dependency, no SHAs, and the version bump (#16780) is already included in release notes for the OpenSearch bump
=> [1.3] Force commons-io transitive dependency version

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java, server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java, server/src/main/java/org/opensearch/repositories/RepositoriesService.java, server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java, test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java, test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/pull/16763 to 2.x
=> [Backport 2.x] Skip remote-repositories validations for node-joins when RepositoriesService is not in sync with cluster-state

server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java, server/src/main/java/org/opensearch/cluster/service/ClusterService.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
This PR addresses issue #16830, where snapshot repository registration fails in clusters with mixed OpenSearch versions, specifically when nodes running OS 2.17 are present alongside nodes running earlier 1.x or 2.x versions.
Problem:
- Repository registration fails due to different handling of test paths in OS 2.17 compared to earlier versions.
- This issue occurs during version upgrades, causing snapshot functionality to break.
Solution:
- Implement version-aware logic for handling test paths.
- Ensure backward compatibility with earlier OpenSearch versions.
- Add checks to use the appropriate test path handling method based on the minimum node version in the cluster.
Changes:
1. Modified code to include version checks.
2. Updated test path handling logic to accommodate mixed version …
=> Fix snapshot repository registration failure in mixed OpenSearch version setups

CHANGELOG.md, server/src/main/java/org/opensearch/action/support/clustermanager/term/TransportGetTermVersionAction.java, server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
In clusters with large number of indices, fetch of full cluster-state would incur downloading too many files from remote. Further if cluster-state updates frequently, it would cause the remote threadpool to be occupied for downloading the state on term mismatch. This might prevent the cluster-state updates from cluster-manager to be propagated slowly and there-by causing the node to lag.
Introduce a setting `cluster.remote_state.download.serve_read_api.enabled` to disable download of full cluster state from remote on term mismatch.
Documentation PR :- https://github.com/opensearch-project/documentation-website/issues/8957 …
=> introduce a setting to disable download of full cluster state from remote on term mismatch

server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java, server/src/main/java/org/opensearch/cluster/service/ClusterService.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Backports https://github.com/opensearch-project/OpenSearch/commit/d37cc9b32600faef17b3c898f8c86b0fd7640d72 from https://github.com/opensearch-project/OpenSearch/pull/16831
=> Handle version during repository registration for prefix mode verification

server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java, server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Remote state read thread pool is of Scaling type. So if for any reason multiple full cluster state downloads are attempted, it will keep filling up the queue and can cause other issues. So changing Remote state read thread pool to Fixed type with limit as queue size as 120,000. The queue size is chosen asssuming that there can be max of 50k indices. So total number of files will be around 100k (50k for index metadata and 50k for routing table). Adding some buffer to 100k and making it 120k.
Also, adding some more logs to understand when full state is downloaded.
NA …
=> Change Remote state read thread pool to Fixed type

libs/core/src/main/java/org/opensearch/Version.java
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/16870 to `2.x`
=> [Forward] [2.x] Update Apache Lucene to 9.12.1 for 2.18.1 (#16846) (#16870)

libs/core/src/main/java/org/opensearch/Version.java
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/16869 and https://github.com/opensearch-project/OpenSearch/pull/16876 to `main`
=> [Forwardport] [main] Update Apache Lucene to 9.12.1 for 2.x and 2.18.1 (#16846) (#16870)

server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java, server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java, server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/8aa3185e18bc725c1aa74ee55dcdf3c0cdc512e3 from https://github.com/opensearch-project/OpenSearch/pull/16850.
=> [Backport 2.x] Change Remote state read thread pool to Fixed type (#16850)

server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
When numDocs=1000:
1. The `testSimpleTimeout` will cost several  minutes, when scoring each doc, it will cost 500ms, it's a long time to iterating all the doc in `queryphase`.
https://github.com/opensearch-project/OpenSearch/blob/5aa65096ff3ca3aec8eb563a8ac52c5e42bf5009/server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java#L138
2. `ReaderContext` is created before executing `queryphase` and released after the `fetchphase`.
3. the life time of `ReaderContext` is 1min(determined by `search.keep_alive_interval`)
4. If `queryPhase` costs too much time, the `ReaderContext` may be released before `fetchphase`, so the `fetch/Id` will be failed, which hit the case.
Resolves #16056 #9401 …
=> [Flaky Test] Fix Flaky Test SearchTimeoutIT.testSimpleTimeout

buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
The `thirdPartyAudit` task writes all dependency metadata to the same base directory of `build/precommit/thirdPartyAudit/thirdPartyAudit/META-INF`. When two separate dependencies attempt to write a file and directory at the same location the task fails with an error.
See #16840.
This PR handles collisions by appending a counter to duplicates.
i.e. dup-1.txt, dup-2.txt, ...
Resolves #16840
=> Create sub directories for ThirdPartyAudit dependency metadata

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml, server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java, server/src/main/java/org/opensearch/index/mapper/DocValueFetcher.java, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Added ability to retrieve value from DocValues in a flat_object filed
Resolves #16742
=> Retrieve value from DocValues in a flat_object filed

.github/workflows/benchmark-pull-request.yml
`benchmark-pull-request.yml` Workflow  Improvements.
- Restrict the workflow to `opensearch-project/OpenSearch` repo.
- Avoid using substring match with JSON-encoded, ensuring robustness in parsing and processing with an exact match to an element in the array.
NA: Workflow  Improvements.
=> `benchmark-pull-request.yml` Workflow  Improvements.

server/src/main/java/org/opensearch/plugins/PluginInfo.java
Small PR to change the version from V_3_0_0 to V_2_19_0 in PluginInfo after the backport of https://github.com/opensearch-project/OpenSearch/pull/16909 was merged to 2.x.
=> Change version in PluginInfo to V_2_19_0 after backport to 2.x merged

.github/benchmark-configs.json
Add new benchmark config for [nested](https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/nested) workload. 
Mainly used for benchmarking nested queries with inner-hits.  …
=> Add new benchmark config for nested workload

CHANGELOG.md, server/src/main/java/org/opensearch/index/mapper/MatchOnlyTextFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/MatchOnlyTextFieldMapperTests.java, server/src/test/java/org/opensearch/index/mapper/MatchOnlyTextFieldTypeTests.java
In some cases, when we create a term query over a `match_only_text` field, it may still try to compute scores, which prevents early termination. We should *always* use a constant score query when querying `match_only_text`, since we don't have the statistics required to compute scores.
N/A
We've seen benchmark latency on the Big5 `query-string-on-message` operation, which we can attribute to this.
=> Always use constant_score query for match_only_text

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/repositories/FilterRepository.java, server/src/main/java/org/opensearch/repositories/Repository.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java, server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java, server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java, server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java, test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
We observed for a remote-store backed index, if the index get’s closed, the shallow snapshot fails for the shard with error : 
`java.nio.file.NoSuchFileException: Metadata file is not present for given primary term <X> and generation <Y> `. 
On root causing the issue we found : 
* There is difference in last segment generation on local node directory & remote store directory. Where remote store lags by 1 generation.
* The shallow_v1 snapshot tries to find the latest segment generation on remote store, which was failing since it never got uploaded.
* The last segment_N file while closing the index got uploaded to the remote store.
* But post successful close, we open a read_only engine for the index, which performs the recovery and creates a new segment_N file, but since it will not be …
=> Fix Shallow copy snapshot failures on closed index

server/src/main/java/org/opensearch/http/HttpTracer.java, server/src/test/java/org/opensearch/http/AbstractHttpServerTransportTests.java
This PR adds response status number like `200` for `OK` response in the Http Trace Logs.
Current Http Response Logs when Trace is enabled:
```
[runTask-0] [2][null][OK][application/json; charset=UTF-8][442] sent response to [Netty4HttpChannel{localAddress=/local:9200, remoteAddress=/remote:1}] success [true]
```
PR changes Http Response Logs when Trace is enabled to:
```
[runTask-0] [2][null][OK][200][application/json; charset=UTF-8][442] sent response to [Netty4HttpChannel{localAddress=/local:9200, remoteAddress=/remote:1}] success [true]
``` …
=> Add Response Status Number in Http Trace Logs.

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml, rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java, server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
Support searching from doc_value using `termQueryCaseInsensitive`/`termQuery` in flat_object/keyword field, even if `index`=false
Resolves #16973
=> Support searching from doc_value using termQueryCaseInsensitive/termQuery in flat_object/keyword field

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java, server/src/main/java/org/opensearch/action/search/SearchPhaseController.java, server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java
=> use the correct type to widen the sort fields when merging top docs

CHANGELOG.md, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizer.java, plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java, plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/20_search.yml
see the individual commit messages for further details.
n/a
=> `phone-search` analyzer: don't emit sip/tel prefix, int'l prefix, extension & unformatted input

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml, rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java, server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
Backport a6945d1226809048c8f914d7ff40a5a5423227e9 from #16974
=> [Backport 2.x] support termQueryCaseInsensitive/termQuery can search from doc_value in flat_object/keyword field

server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
The second loop is useless, we can merge it into the first loop. The exist it/ut can cover the changed, I don't know whether I should add additional test about it.
=> Delete useless loop in TransportBulkAction$BulkOperation.doRun()

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/70_adjacency_matrix.yml, server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregationBuilder.java, server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregatorFactory.java, server/src/test/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregationBuilderTests.java, server/src/test/java/org/opensearch/search/aggregations/metrics/AdjacencyMatrixTests.java
Re-release of a [previous PR](https://github.com/opensearch-project/OpenSearch/pull/10226) that did not correctly sign the commit
Show only intersecting buckets to the Adjacency matrix aggregation
The [Adjacency matrix aggregation](https://opensearch.org/docs/latest/query-dsl/aggregations/bucket/adjacency-matrix/) will compute and return all buckets related to any of the combinations of the filters specified, including hits on a single filter. However, sometimes a user would want to return only the buckets related to an intersection and not for a single filter. An optional show_only_intersecting parameter would stop buckets resulting from a single filter being hit to be created.
https://github.com/opensearch-project/OpenSearch/issues/8832 …
=> Show only intersecting buckets to the Adjacency matrix aggregation

CHANGELOG.md, plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizer.java, plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java, plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/20_search.yml
cherry-pick of #16993 with #17016 squashed into it.
CC @reta 
n/a
=> [Backport 2.x] `phone-search` analyzer: don't emit sip/tel prefix, int'l prefix, extension & unformatted input

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/api/search_shards.json, rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/20_slice.yml, server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportClusterSearchShardsAction.java, server/src/main/java/org/opensearch/action/fieldcaps/TransportFieldCapabilitiesIndexAction.java, server/src/main/java/org/opensearch/action/search/TransportSearchAction.java, server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterSearchShardsAction.java, server/src/main/java/org/opensearch/search/slice/SliceBuilder.java, server/src/test/java/org/opensearch/action/search/TransportSearchActionTests.java, server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
Prior to this commit, a sliced search would fan out to every shard, then apply a MatchNoDocsQuery filter on shards that don't correspond to the current slice. This still creates a (useless) search context on each shard for every slice, though. For a long-running sliced scroll, this can quickly exhaust the number of available scroll contexts.
This change avoids fanning out to all the shards by checking at the coordinator if a shard is matched by the current slice. This should reduce the number of open scroll contexts to max(numShards, numSlices) instead of numShards * numSlices.
Related to https://github.com/opensearch-project/OpenSearch/issues/16289 …
=> Filter shards for sliced search at coordinator

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/70_adjacency_matrix.yml, server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregationBuilder.java
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/17006 to `main`
=> Update version checks for backport

modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/50_wait_for_active_shards.yml, modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/60_wait_for_active_shards.yml, modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/update_by_query/50_consistency.yml, server/src/internalClusterTest/java/org/opensearch/action/support/WaitActiveShardCountIT.java, server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java, server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java, server/src/main/java/org/opensearch/action/update/UpdateHelper.java
Remove user data from logs when not in debug/trace mode.
NA
=> Remove user data from logs when not in debug/trace mode

CHANGELOG.md, plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java, plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/Netty4GrpcServerTransport.java, plugins/transport-grpc/src/test/java/org/opensearch/transport/grpc/Netty4GrpcServerTransportTests.java, server/src/main/java/org/opensearch/bootstrap/Security.java, server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
1. Rename [AUX_TRANSPORT_PORT](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/NetworkPlugin.java#L82-L86) setting from `aux.transport.experimental-transport-grpc.ports` to `aux.transport.experimental-transport-grpc.port` for consistency with the [http.port](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/http/HttpTransportSettings.java#L114) cluster setting. 
2. Fix lingering HTTP terminology in [Netty4GrpcServerTransport.java](https://github.com/opensearch-project/OpenSearch/blob/main/plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/Netty4GrpcServerTransport.java#L141-L148) (`httpBindHost`-> `grpcBindHost`, `httpPublishHost` -> `grpcPublishHost`) 
3. Add a debug log …
=> Fix GRPC AUX_TRANSPORT_PORT and SETTING_GRPC_PORT settings and remove lingering HTTP terminology 

MAINTAINERS.md
Following the process at https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer, I have nominated and other maintainers have agreed to add Craig Perkins (@cwperks) as a co-Maintainer of the OpenSearch repository. Craig has kindly accepted the invitation.
Craig has been a long-time and consistent contributor to OpenSearch since 2022. Out of a raw total of 157 PRs I tried to filter out backports, merges, version bumps, and minor changes and still have almost 50 substantive contributions. 
Most recently, he fixed a longstanding pet peeve of mine: his very first PR to the project was a CVE-fixing version bump (https://github.com/opensearch-project/OpenSearch/pull/3772) that dependabot missed. He followed through on that in exploring and committing a …
=> Add Craig Perkins as OpenSearch Maintainer

CHANGELOG.md, test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/17060 to `2.x`
=> [Backport] [2.x] Bump com.squareup.okio:okio from 3.9.1 to 3.10.2 in /test/fixtures/hdfs-fixture (#17060)

libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java, libs/common/src/test/java/org/opensearch/common/annotation/processor/CompilerSupport.java
Fix the compiler task status reporting for annotation processor. The Java compiler was reporting failures previously only because the `SecurityManager` was preventing the writing of class files into `build` folder. This was not very important because the annotation processing was always happening before (and this is what tests were checking). The change fixes the issue by outputting class files into temporary folder.
Follow up on https://github.com/opensearch-project/OpenSearch/pull/16962
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md# …
=> Fix the compiler task status reporting for annotation processor

CHANGELOG.md, build.gradle, server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilderTests.java, server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java, server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryWithPinnedTimestampTests.java, server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
Reverts opensearch-project/OpenSearch#17058, the plugin is unstable:
```
* What went wrong:
Execution failed for task ':distribution:tools:java-version-checker:spotlessJava'.
> Cannot fingerprint input property 'stepsInternalEquality': value 'com.diffplug.spotless.ConfigurationCacheHackList@d5fd99d3' cannot be serialized.
```
[1] https://build.ci.opensearch.org/job/gradle-check/52379/console
[2] https://github.com/equodev/equo-ide/issues/188
[3] https://github.com/diffplug/spotless/issues/2331
=> Revert "Bump com.diffplug.spotless from 6.25.0 to 7.0.2"

CHANGELOG-3.0.md, CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/nodes.info/50_nodes_total_indexing_buffer_format.yml, server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoResponse.java
Fix format interchange between `total_indexing_buffer_in_bytes` and `total_indexing_buffer` fields in nodes API response.
- `total_indexing_buffer_in_bytes` should display raw bytes (e.g. 53687091)
- `total_indexing_buffer` should display human readable format (e.g. 51.1mb)
Resolves #16910 
I considered this change to be a breaking change and implemented it to take effect starting from version 3.0.0.
Would it be appropriate to apply this change to the 2.x versions as well?
If so, I would consider implementing it as follows:
```java
Version currentVersion = Version.CURRENT;
if (currentVersion.onOrAfter(Version.V_3_0_0)) {
builder.humanReadableField("total_indexing_buffer_in_bytes", "total_indexing_buffer", nodeInfo.getTotalIndexingBuffer());
} else { …
```
=> Fix interchanged formats of total_indexing_buffer_in_bytes and total_indexing_buffer

CHANGELOG.md, server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java, server/src/main/java/org/opensearch/search/query/BitmapDocValuesQuery.java, server/src/main/java/org/opensearch/search/query/BitmapIndexQuery.java, server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java, server/src/test/java/org/opensearch/search/query/BitmapDocValuesQueryTests.java, server/src/test/java/org/opensearch/search/query/BitmapIndexQueryTests.java
This change adds a new bitmap index query that solves existing performance issue described in the related issue below. In short, the time spent in constructor and cost estimation.
Bitmap index query takes advantage of the index structure or points of the numeric field, and traverse points to return an iterator of matching doc ids. Matching doc here means its value is inside the bitmap.
The main reason bitmap index query is needed is to support IndexOrDocValuesQuery.
IndexOrDocValuesQuery can decide which query, index or doc value, to supply scorer at the runtime depending on the comparison between cost of the chosen lead iterator (c_lead) and the index query (c_iq). For example, we have a term filter that matches **1%** of the total documents, and a numeric range IndexOrDocValuesQuery …
=> Improve performance of the bitmap filtering

CHANGELOG.md, server/src/main/java/org/opensearch/index/mapper/DocumentMapper.java, server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java, server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
During I experimentation with concurrent execution in the innerhit phase, I discovered another logic that requires optimization.
It is known that TermQuery is never cached in QueryCache, but innerhit phase extensively utilizes TermQuery, resulting in inefficient(https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/UsageTrackingQueryCachingPolicy.java#L57). The following improvements can be made:
- In findNestedObjectMapper, if context is stance of InnerHitSubContext, we are able to rapidly identify the ObjectMapper, thus reducing the number of TermQuery executions.
- In getInternalNestedIdentity, childFilter, which is a simple TermQuery, will be cached by bitsetFilterCache, which
can also help reduce redundant query executions.   Similar usage can be …
=> Optimize innerhits query performance

.github/workflows/assemble.yml, .github/workflows/precommit.yml
Add ubuntu-24.04-arm to Github actions workflow, see please https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
N/A
=> Add ubuntu-24.04-arm to Github actions workflow

buildSrc/version.properties
Bump 3.0.0 version with alpha qualifier.
So we can test the new alpha version on Jenkins earlier and mitigate issues.
https://github.com/opensearch-project/opensearch-build/issues/3747 …
=> Bump 3.0.0 version with alpha qualifier

modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/50_wait_for_active_shards.yml, modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/60_wait_for_active_shards.yml, modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/update_by_query/50_consistency.yml, server/src/internalClusterTest/java/org/opensearch/action/support/WaitActiveShardCountIT.java, server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java, server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java, server/src/main/java/org/opensearch/action/update/UpdateHelper.java
* Remove user data from logs when not in debug/trace mode
Backport https://github.com/opensearch-project/OpenSearch/pull/17007
=> [Backport 2.x] Remove user data from logs when not in debug/trace mode

server/src/main/java/org/opensearch/action/support/replication/ReplicationRequest.java, server/src/test/java/org/opensearch/action/bulk/BulkShardRequestTests.java
Add BulkShardRequest Serialization Test 
=> Add BulkShardRequest Serialization Test

.github/workflows/publish-maven-snapshots.yml
Fix JDK version for publish-maven-snapshots GA workflow
Follow up on https://github.com/opensearch-project/OpenSearch/pull/16366
=> Fix JDK version for publish-maven-snapshots GA workflow

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/SearchResponse.java, server/src/main/java/org/opensearch/action/search/SearchResponseSections.java, server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java, server/src/main/java/org/opensearch/search/SearchHits.java, server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java, server/src/main/java/org/opensearch/search/internal/InternalSearchResponse.java, server/src/main/java/org/opensearch/search/pipeline/Pipeline.java, server/src/main/java/org/opensearch/search/pipeline/PipelineProcessingContext.java, server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java, server/src/main/java/org/opensearch/search/pipeline/ProcessorExecutionDetail.java, server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java, server/src/main/java/org/opensearch/search/pipeline/TrackingSearchRequestProcessorWrapper.java, server/src/main/java/org/opensearch/search/pipeline/TrackingSearchResponseProcessorWrapper.java, server/src/test/java/org/opensearch/action/search/SearchResponseTests.java, server/src/test/java/org/opensearch/search/GenericSearchExtBuilderTests.java, server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java, server/src/test/java/org/opensearch/search/pipeline/ProcessorExecutionDetailTests.java, server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java, server/src/test/java/org/opensearch/search/pipeline/TrackingSearchRequestProcessorWrapperTests.java, server/src/test/java/org/opensearch/search/pipeline/TrackingSearchResponseProcessorWrapperTests.java
Jan 16 revision: 
1. Add two new fields: status and error
- status: Represents the execution status of the processor, with possible values such as SUCCESS and FAIL.
- error: Captures the error message or details if the processor encounters an issue during execution. If no error occurs, this field remains empty.
2. When verbose pipeline is enabled, errors in a processor will not interrupt the search but will document the error and continue searching
When the verbose pipeline mode is enabled, if a processor encounters an error during execution, the search process will not be interrupted. Instead, the error will be documented in the processor's execution details (e.g., in ProcessorExecutionDetail) and the remaining search process will proceed as normal.
```
{
"processor_name": …
```
=> Add verbose pipeline parameter to output each processor's execution details

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
=> Fix exists queries on nested flat_object fields throws exception

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/SearchResponse.java, server/src/main/java/org/opensearch/action/search/SearchResponseSections.java, server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java, server/src/main/java/org/opensearch/search/SearchHits.java, server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java, server/src/main/java/org/opensearch/search/internal/InternalSearchResponse.java, server/src/main/java/org/opensearch/search/pipeline/Pipeline.java, server/src/main/java/org/opensearch/search/pipeline/PipelineProcessingContext.java, server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java, server/src/main/java/org/opensearch/search/pipeline/ProcessorExecutionDetail.java, server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java, server/src/main/java/org/opensearch/search/pipeline/TrackingSearchRequestProcessorWrapper.java, server/src/main/java/org/opensearch/search/pipeline/TrackingSearchResponseProcessorWrapper.java, server/src/test/java/org/opensearch/action/search/SearchResponseTests.java, server/src/test/java/org/opensearch/search/GenericSearchExtBuilderTests.java, server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java, server/src/test/java/org/opensearch/search/pipeline/ProcessorExecutionDetailTests.java, server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java, server/src/test/java/org/opensearch/search/pipeline/TrackingSearchRequestProcessorWrapperTests.java, server/src/test/java/org/opensearch/search/pipeline/TrackingSearchResponseProcessorWrapperTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/e15f71265e1da74d89025373ec96980fffb93640 from https://github.com/opensearch-project/OpenSearch/pull/16843.
Update version check to onOrAfter(Version.V_2_19_0)
Perform the BWC process:
1. Do this on main with onOrAfter(Version.V_3_0_0)). Get it merged.
2. You'll need a manual backport to 2.x, where you do onOrAfter(Version.V_2_19_0). Don't get it merged right away.
3. Before merging the backport to 2.x, open another PR on main to change it to onOrAfter(Version.V_2_19_0).
4. Merge the backport PR.
5. Merge the main version update PR. …
=> [Backport 2.x] Add verbose pipeline parameter to output each processor's execution

server/src/main/java/org/opensearch/action/search/SearchResponseSections.java, server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java, server/src/main/java/org/opensearch/search/internal/InternalSearchResponse.java
Will merge this PR after https://github.com/opensearch-project/OpenSearch/pull/17097 got merged 
To perform the BWC process:
1. Do this on main with onOrAfter(Version.V_3_0_0)). Get it merged.
2. You'll need a manual backport to 2.x, where you do onOrAfter(Version.V_2_19_0). Don't get it merged right away.
3. Before merging the backport to 2.x, open another PR on main to change it to onOrAfter(Version.V_2_19_0).
4. Merge the backport PR.
5. Merge the main version update PR. …
=> Updates version  to fix BWC for SearchSourceBuilder

CHANGELOG.md, server/src/main/java/org/opensearch/index/fieldvisitor/CustomFieldsVisitor.java, server/src/main/java/org/opensearch/index/fieldvisitor/FieldsVisitor.java, server/src/main/java/org/opensearch/search/fetch/FetchPhase.java, server/src/test/java/org/opensearch/index/mapper/StoredNumericValuesTests.java, server/src/test/java/org/opensearch/search/fetch/FetchPhaseTests.java
The change is to propagate the source includes and source excludes fields that are present in the `FetchSourceContext`. 
This is as part of the open questions in this RFC https://github.com/opensearch-project/k-NN/issues/2377 
PR is part of [#2377](https://github.com/opensearch-project/k-NN/issues/2377) 
as part of the Derived source feature for k-NN. 
=> Propagate includes and excludes from fetchSourceContext to FieldsVisitor

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml, server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java, server/src/main/java/org/opensearch/index/mapper/DocValueFetcher.java, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Backport cf497171c15debd465e217113b43cc4688380176 from #16802
=> [Backport 2.x] Retrieve value from DocValues in a flat_object filed

rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml, rest-api-spec/src/main/resources/rest-api-spec/test/index/105_partial_flat_object_nested.yml, rest-api-spec/src/main/resources/rest-api-spec/test/index/91_flat_object_null_value.yml, server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
The current implementation of exists query for subfield uses an inverted index under `<field name>` to perform the query, this inverted index create mapping for each level of subfields. Taking a field `field1` with `flat_object` type and a doc with value `{"field1": {"field2" : {"field3": "a"}}}`, the inverted index under `field1` field contains terms `field1.field2` and `field1.field3`, when we run the query `{"query": {"exists": {"field": "field1.field2.field3"}}}`, it turns into term query `"field1": "field1.field2.field3"`, there is no match term obviously.
Since `PathAndValue` field contains `<full path>=<value>` term or doc values, we can use the user specified field name append `=` symbol as prefix to run the query, which equals to range query with both `lowerTerm` and `upperTerm` …
=> Fix exists query for flat object

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java, server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java, server/src/main/java/org/opensearch/common/settings/Setting.java, server/src/main/java/org/opensearch/snapshots/RestoreService.java, server/src/test/java/org/opensearch/common/settings/ScopedSettingsTests.java, server/src/test/java/org/opensearch/common/settings/SettingTests.java
This PR adds a new Setting property UnmodifiableOnRestore to prevent customers from updating certain settings on restore snapshot. The motivation behind this change is to prevent customers from updating index.knn setting when restoring a snapshot. The PR is related to another PR (https://github.com/opensearch-project/k-NN/pull/2348) which fixes a bug by making index.knn setting immutable after index creation. However, that PR doesn't cover the case for snapshots, so this PR adds Setting property UnmodifiableOnRestore so that index.knn will be immutable when restoring an index from a snapshot.
Resolves Issue 2334 in KNN repository: https://github.com/opensearch-project/k-NN/issues/2334
#17019  …
=> [Backport 2.x] Added new Setting property UnmodifiableOnRestore to prevent updating settings on restore snapshot

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/TransportMultiSearchAction.java, server/src/test/java/org/opensearch/action/search/TransportMultiSearchActionTests.java
Prior to this fix, the _msearch API would keep running search requests even after being canceled. With this change, we explicitly check if the task has been canceled before kicking off subsequent requests.
Resolves https://github.com/opensearch-project/OpenSearch/issues/17004
=> Stop processing search requests when _msearch is canceled

server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
- In `RemoteSegmentTransferTrackerTests.testGetInflightUploadBytes`, we get random value for started, succeeded and failed bytes with following logic:
https://github.com/opensearch-project/OpenSearch/blob/46f852a5f5b984623f2a6d377d4bfed912c4fee6/server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java#L261-L263
- Here, the expectation is, `started >= failed + succeeded`. We assert with following check:
https://github.com/opensearch-project/OpenSearch/blob/46f852a5f5b984623f2a6d377d4bfed912c4fee6/server/src/main/java/org/opensearch/index/remote/RemoteTransferTracker.java#L257-L268
- But while assigning random value, it is possible to assign following values which breaks the above assertion:
- started = 10200
- succeeded = 9900
- failed = 8000
- To make sure …
=> Fix flaky test RemoteSegmentTransferTrackerTests.testGetInflightUploadBytes

CHANGELOG.md, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java, server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java, server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java, server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
Custom Metadata is serialized `writeTo` and deserialized using the `readFrom` method or a constructor with stream input.
For example - `ComposableIndexTemplate` is serialized using [ComposableIndexTemplate.writeTo](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java#L238-L254) and deserialized using the [stream input constructor](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java#L175-L192).
Consider a case where a new attribute is added in a version. For example `context` is [added](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTempl …
=> Add opensearch version info while deserialization

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java, server/src/main/java/org/opensearch/index/mapper/DocumentParser.java, server/src/main/java/org/opensearch/index/mapper/MapperService.java, server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java, server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
---------
Backport of #16728 resolving conflicts in CHANGELOG.md
=> [Backport 2.x] Support object fields in star-tree index (#16728)

CHANGELOG.md, modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java, modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java, modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java, modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java, plugins/cache-ehcache/src/main/java/org/opensearch/cache/EhcacheDiskCacheSettings.java, plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java, plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java, server/src/main/java/org/opensearch/common/cache/service/CacheService.java, server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java, server/src/main/java/org/opensearch/common/cache/store/settings/OpenSearchOnHeapCacheSettings.java, server/src/main/java/org/opensearch/indices/IndicesRequestCache.java, server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java, server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java, server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/a43607677517d84804d223e54d824753d0646f23 from https://github.com/opensearch-project/OpenSearch/pull/16636.
=> [Backport 2.x] [Bugfix] Fix cache maximum size settings not working properly with pluggable caching

CHANGELOG.md, server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java, server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java, server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java, server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java, server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
Backport 3032bef54d502836789ea438f464ae0b1ba978b2 from #16494
=> [Backport 2.x] Add opensearch version info while deserialization (#16494)

CHANGELOG.md, libs/core/src/main/java/org/opensearch/core/index/AppendOnlyIndexOperationRetryException.java, server/src/internalClusterTest/java/org/opensearch/action/bulk/AppendOnlyIndicesIT.java, server/src/main/java/org/opensearch/action/bulk/BulkPrimaryExecutionContext.java, server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/engine/InternalEngine.java, server/src/test/java/org/opensearch/action/bulk/BulkPrimaryExecutionContextTests.java
Adding support for Append only indices where we are disabling any form of updates and deletes on the index. We are also preventing passing a custom doc id for bulk indexing requests. Append only indices will be supported through a configurable setting. If this setting is enabled, all update and delete operations on the index (UPDATE, DELETE, UPSERT, UPDATE BY QUERY, DELETE BY QUERY, etc,) will be blocked.
https://github.com/opensearch-project/OpenSearch/issues/12886 …
=> Add support for append only indices

server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java, server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesReader.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionDataType.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionType.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/ReadDimension.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/UnsignedLongDimension.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/StarTreeWriter.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/DimensionConfig.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataWriter.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorter.java, server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java, server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java, server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeDocValuesFormatTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BuilderTestsUtils.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuildMetricTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderFlushFlowTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderMergeFlowTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderTestCase.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorterTests.java, server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
This change handles the comparison and sorting of unsigned long values during Indexing [flush and merge] operations. Since unsigned long values are stored as Java Long (and values greater than Long.MAX_VALUE turn negative), Long.compareUnsigned is used to ensure correct sorting and comparison of unsigned long dimensions. This ensures that unsigned long values are properly handled and sorted during Indexing [flush and merge] operations
Resolves Issue - [Handle unsigned long during flush and merge operations](https://github.com/opensearch-project/OpenSearch/issues/16645) …
=> Add Star Tree unsigned-long indexing changes

server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java, server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesReader.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionDataType.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionType.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/ReadDimension.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/UnsignedLongDimension.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/StarTreeWriter.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/DimensionConfig.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataWriter.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorter.java, server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java, server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java, server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeDocValuesFormatTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BuilderTestsUtils.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuildMetricTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderFlushFlowTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderMergeFlowTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderTestCase.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorterTests.java, server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Backport of #17156 
Resolves Issue - [Handle unsigned long during flush and merge operations](https://github.com/opensearch-project/OpenSearch/issues/16645)
=> [Backport 2.x] Add Star Tree unsigned-long indexing changes (#17156)

CHANGELOG.md, server/src/main/java/org/opensearch/common/Rounding.java, server/src/main/java/org/opensearch/search/DocValueFormat.java, server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java, server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregatorTests.java, test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
The auto date histogram agg contains an optimization which skips traditional doc collection and instead examines the "pre-aggregated" doc counts contained in the BKD tree of each segment. Several conditions need to be true before this optimization can execute for a given segment. One such condition is we must be able to determine a set of ranges (or rounding) for the segment under consideration before optimizing.
Normally ranges for the auto date histogram aggregation are updated as needed over the course of collecting documents but the filter rewrite optimization will [update](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java#L193) the `preparedRounding` of the agg in …
=> Fix auto date histogram rounding assertion bug

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/TransportSearchScrollAction.java, server/src/main/java/org/opensearch/wlm/QueryGroupTask.java, server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java, server/src/test/java/org/opensearch/wlm/tracker/QueryGroupTaskResourceTrackingTests.java, server/src/test/java/org/opensearch/wlm/tracker/ResourceUsageCalculatorTrackerServiceTests.java
This change mitigates the **warn** level logs from `QueryGroupTask#getQueryGroupId` method when the `queryGroupId` is `null`.  Currently all APIs which use `SearchTask` or `SearchShardTask` for task level resource tracking have to call the `setQueryGroupId` method otherwise this results in generating the log mentioned in the related issues.  
Resolves https://github.com/opensearch-project/OpenSearch/issues/16874
=> [WLM] add wlm support for scroll API

CHANGELOG.md, server/src/main/java/org/opensearch/common/Rounding.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/DateDimension.java, server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeQueryHelper.java, server/src/main/java/org/opensearch/search/aggregations/StarTreeBucketCollector.java, server/src/main/java/org/opensearch/search/aggregations/StarTreePreComputeCollector.java, server/src/main/java/org/opensearch/search/aggregations/bucket/BucketsAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorFactory.java, server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregator.java, server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java, server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/DateHistogramAggregatorTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/StarTreeFilterTests.java, test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/pull/17150 to 2.x
(automatic [backport](https://github.com/opensearch-project/OpenSearch/pull/17150) failed)
=> [Backport 2.x] [Star Tree] [Search] Resolving Date histogram with metric aggregation using star-tree

CHANGELOG.md, gradle/formatting.gradle
Coming from https://github.com/diffplug/spotless/issues/1783#issuecomment-2560785949, fix failing CI's with `Failed to load eclipse jdt formatter`. 
Sample Failing workflow https://github.com/opensearch-project/OpenSearch/actions/runs/13022093445/job/36324715880?pr=17153
=> Fix failing CI's with `Failed to load eclipse jdt formatter`.

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/TransportSearchScrollAction.java, server/src/main/java/org/opensearch/wlm/QueryGroupTask.java, server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java, server/src/test/java/org/opensearch/wlm/tracker/QueryGroupTaskResourceTrackingTests.java, server/src/test/java/org/opensearch/wlm/tracker/ResourceUsageCalculatorTrackerServiceTests.java
This change is taken from the PR: https://github.com/opensearch-project/OpenSearch/pull/16981 which fixes the https://github.com/opensearch-project/OpenSearch/issues/16874 bug.
=> [WLM] Fix the QueryGroupTask logging bug

server/src/main/java/org/opensearch/index/engine/InternalEngine.java, server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Fail the engine incase of any update operation on Engine for append only indices.
=> Throwing exception for any update call for Append only indices

modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java, server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java, server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java, server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java, server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/AbstractStarTreeDVFormatTests.java, server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java, server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java, server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
Enforcing append only setting for star tree index
=> Enforcing append only setting for star-tree index

modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java, server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java, server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java, server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java, server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/AbstractStarTreeDVFormatTests.java, server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java, server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java, server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
=> [Backport 2.x] Enforcing append only setting for star-tree index (#17180)

modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java, modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy, plugins/transport-reactor-netty4/src/main/java/org/opensearch/transport/reactor/SharedGroupFactory.java, plugins/transport-reactor-netty4/src/main/plugin-metadata/plugin-security.policy, server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java, server/src/main/resources/org/opensearch/bootstrap/security.policy
So far I have only seen it during the server shutdown procedure:
```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")                                                                       
at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:488) ~[?:?]                                                              
at java.base/java.security.AccessController.checkPermission(AccessController.java:1085) ~[?:?]                                                                     
at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411) ~[?:?]                                                                            
at java.base/java.lang.ClassLoader.checkClassLoaderPermission(Class …
```
=> Fix java.security.AccessControlException during OpenSearch server shutdown cycle

CHANGELOG.md
Compared to original PR #16981, scroll API changes were reverted from 2.x to maintain the backward compat. Updating changelog to reflect that
=> Correcting the changelog description

CHANGELOG.md, gradle/formatting.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/17172.
Part of https://github.com/opensearch-project/OpenSearch/issues/16516
=> [Backport 2.x] Fix failing CI's with Failed to load eclipse jdt formatter

server/src/test/java/org/opensearch/action/search/TransportMultiSearchActionTests.java
I recently added this test, but incorrectly placed a CountDownLatch#await call on the test thread. With this change, we actually kick off the request, return control to the test thread, cancel the request, then continue executing.
=> Fix flaky TransportMultiSearchActionTests.testCancellation

server/src/main/java/org/opensearch/search/aggregations/AggregatorBase.java, server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregator.java, server/src/main/java/org/opensearch/search/startree/StarTreeQueryHelper.java
We've had a series of aggregation speedups that use the same strategy: instead of iterating through documents that match the query one-by-one, we can look at a Lucene segment and compute the aggregation directly (if some particular conditions are met).
In every case, we've hooked that into custom logic that hijacks the getLeafCollector method and throws CollectionTerminatedException. This creates the illusion that we're implementing a custom LeafCollector, when really we're not collecting at all (which is the whole point).
With this refactoring, the mechanism (hijacking getLeafCollector) is moved into AggregatorBase. Aggregators that have a strategy to precompute their answer can override `tryPrecomputeAggregationForLeaf`, which is expected to return true if they managed to precompute. …
=> Unify precomputation of aggregations behind a common API

plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaUtils.java
@yupeng9 Looks like we missed one usage of shaded immutable map.
=> Replace usage of transitive shaded dependency

modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java, modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy, server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java, server/src/main/resources/org/opensearch/bootstrap/security.policy
Backport of https://github.com/opensearch-project/OpenSearch/pull/17183 to `1.x`
=> [Backport] [1.x] Fix java.security.AccessControlException during OpenSearch server shutdown cycle (#17183)

modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java, modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy, server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java, server/src/main/resources/org/opensearch/bootstrap/security.policy
Backport of https://github.com/opensearch-project/OpenSearch/pull/17183 to `1.3`
=> [Backport] [1.3] Fix java.security.AccessControlException during OpenSearch server shutdown cycle (#17183)

CHANGELOG.md, server/src/main/java/org/opensearch/common/Rounding.java, server/src/main/java/org/opensearch/search/DocValueFormat.java, server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java, server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregatorTests.java, test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/de59264d70878455be2b98ac2eea4e46753e0944 from https://github.com/opensearch-project/OpenSearch/pull/17023.
Additionally update `isUTC` to be non-abstract. Breaks backward compatibility with 2.x.
Remove unused `ZoneId` getter from DocValueFormat.java.
=> [Backport 2.x] Fix auto date histogram rounding assertion bug

buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
The linked issue was closed in 2019 (pre-fork) so I'm going to remove these log levels. If anyone complains about missing logs in test environments we can add them again.
=> Remove DEBUG log level from test cluster node

CHANGELOG.md, server/src/main/java/org/opensearch/common/Rounding.java, server/src/main/java/org/opensearch/search/DocValueFormat.java, server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java, server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregatorTests.java, test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/de59264d70878455be2b98ac2eea4e46753e0944 from https://github.com/opensearch-project/OpenSearch/pull/17023.
Additionally update `isUTC` to be non-abstract. Breaks backward compatibility with 2.x.
Remove unused `ZoneId` getter from DocValueFormat.java.
=> [Backport 2.19] Fix auto date histogram rounding assertion bug

buildSrc/version.properties, gradle/libs.versions.toml, libs/core/src/main/java/org/opensearch/Version.java
Update 2.x to 2.20.0
Part of https://github.com/opensearch-project/OpenSearch/issues/16516
=> Update 2.x to 2.20.0

CHANGELOG.md, test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/17231 to `2.x`
=> [Backport] [2.x] Bump dnsjava:dnsjava from 3.6.2 to 3.6.3 in /test/fixtures/hdfs-fixture (#17231)

server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
Fix in date aggregator where date field was [hard-coded](https://github.com/opensearch-project/OpenSearch/pull/16674). Fixed that to fetch from value-source if available.
This fix was included in https://github.com/opensearch-project/OpenSearch/pull/17165/ but the PR is missed for 2.19 so creating a separate PR to only include the bug fix to be pushed to 2.19 branch as feature inclusion is blocked for now in 2.19
Will rebase https://github.com/opensearch-project/OpenSearch/pull/17165 after this PR gets merged.
Fix date field hard-coding introduced in https://github.com/opensearch-project/OpenSearch/pull/16674 - this is required to correctly fetch date field in Date Aggregation using star-tree …
=> Fix date hardcoding in date aggregator

CHANGELOG-3.0.md, modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpRequest.java, plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpRequest.java, server/src/main/java/org/opensearch/http/HttpRequest.java
Add HTTP/2 protocol support to HttpRequest.HttpVersion
N/A
=> Add HTTP/2 protocol support to HttpRequest.HttpVersion

server/src/main/java/org/opensearch/action/admin/indices/alias/TransportIndicesAliasesAction.java, server/src/main/java/org/opensearch/action/admin/indices/close/TransportCloseIndexAction.java, server/src/main/java/org/opensearch/action/admin/indices/create/AutoCreateAction.java, server/src/main/java/org/opensearch/action/admin/indices/create/TransportCreateIndexAction.java, server/src/main/java/org/opensearch/action/admin/indices/delete/TransportDeleteIndexAction.java, server/src/main/java/org/opensearch/action/admin/indices/mapping/put/TransportPutMappingAction.java, server/src/main/java/org/opensearch/action/admin/indices/open/TransportOpenIndexAction.java, server/src/main/java/org/opensearch/action/admin/indices/readonly/TransportAddIndexBlockAction.java, server/src/main/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverService.java, server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java, server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java, server/src/main/java/org/opensearch/action/admin/indices/upgrade/post/TransportUpgradeSettingsAction.java, server/src/main/java/org/opensearch/cluster/AckedClusterStateUpdateTask.java, server/src/main/java/org/opensearch/cluster/ack/AckedRequest.java, server/src/main/java/org/opensearch/cluster/ack/ClusterStateUpdateRequest.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateDataStreamService.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexStateService.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
=> Remove master term from AckedRequest

.github/dependabot.yml
Add explicit registry to Gradle package manager so dependabot should be able to update the dependencies:
```
+------------------------------------------------------------------------------------------------------------------------------------+
updater | |                                                Changes to Dependabot Pull Requests                                                 |
updater | +---------+--------------------------------------------------------------------------------------------------------------------------+
updater | | created | org.jruby.joni:joni ( from 2.2.1 to 2.2.3 )                                                                              |
updater | | created | org.locationtech.spatial4j:spatial4j ( from 0.7 to 0.8 ) …
```
=> Add Gradle registries for dependabot

CHANGELOG-3.0.md, libs/core/src/main/java/org/opensearch/core/util/ConfigurationUtils.java, libs/core/src/test/java/org/opensearch/core/util/ConfigurationUtilsTests.java, plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaSourceConfig.java
- Inspired by the ConfigurationUtil in the ingest package, introduce a ConfigurationUtil to the common util (and later can consolidate with the one in ingest package). 
- used this configurationUtil for configuration parsing in KafkaSourceConfig
=> [Pull-based Ingestion] use ConfigurationUtil for KafkaSourceConfig

server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java, test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
The case is as follows:
1. When the `node_t1` is excluded from the vote config, and the cluster starts a new leader election, but the the node `node_t2` hasn't been elected as the new leader.
2. At the moment, we send request to get the ClusterManager, we first get ClusterManager name, and leads to the NullPointerException.
`internalCluster().nonClusterManagerClient()`-> ......->`getClusterManagerName()`
https://github.com/opensearch-project/OpenSearch/blob/f0ea056a93383c4ca7cac361fdf8c73e8afc3941/test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java#L2171
Resolves #15944 #16015  …
=> Fix Flaky Test SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes

modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java, plugins/transport-reactor-netty4/src/main/java/org/opensearch/transport/reactor/SharedGroupFactory.java, server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
Remove priviledged thread factory (fix integrated into latest Netty 4.1.118.Final)
Follow up on https://github.com/opensearch-project/OpenSearch/pull/17320
=> Remove priviledged thread factory (fix integrated into latest Netty 4.1.118.Final)

CHANGELOG.md, server/src/main/java/org/opensearch/threadpool/ThreadPool.java, server/src/test/java/org/opensearch/threadpool/ThreadPoolTests.java
Currently force merge threads are bounded to size of 1 , irrespective of total cores available. This makes the force merges very slow and doesn't scale it with number of cores
This PR increases the thread count to 1/8th of the total cores, thereby making the force merges to run faster, still capped at 12.5% of overall CPU available. 
=> Making force merge threadpool 1/8th of total cores

server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java, server/src/main/java/org/opensearch/common/blobstore/fs/FsBlobContainer.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
`getRemoteDirectory().deleteStaleSegments` will not delete last metadata when pinned timestamps are enabled . Hence we need to use `getRemoteDirectory().delete();` which does the clean up comprehensively . 
=> [Remote Store] Using RemoteDirectory#delete to clear all segments during migration

CHANGELOG-3.0.md, distribution/src/config/opensearch.yml, server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java, server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/tasks/PendingTasksBlocksIT.java, server/src/internalClusterTest/java/org/opensearch/action/admin/indices/exists/IndicesExistsIT.java, server/src/internalClusterTest/java/org/opensearch/gateway/RecoverAfterNodesIT.java, server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/gateway/GatewayService.java, server/src/test/java/org/opensearch/gateway/GatewayServiceTests.java
The following settings were deprecated in ES 7.7 prior to the fork:
- gateway.expected_nodes
- gateway.expected_master_nodes
- gateway.recover_after_nodes
- gateway.recover_after_master_nodes
This commit removes the deprecated settings and replaces their usages in tests with `expected_data_nodes` or `recover_after_data_nodes`.
Resolves #3117
=> Remove deprecated settings to defer cluster recovery

server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Fixes segment Replication stats throwing NPE when shards are unassigned or are in delayed allocation phase
Resolves #11945
=> Segment Replication stats throwing NPE when shards are unassigned or are in delayed allocation phase

CHANGELOG-3.0.md, qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/40_wildcard.yml, qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/40_wildcard.yml, qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/40_wildcard.yml, server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java, server/src/test/java/org/opensearch/index/mapper/WildcardFieldMapperTests.java, server/src/test/java/org/opensearch/index/mapper/WildcardFieldTypeTests.java
Accorrding the test result of #17099 , change wildcard field to only index 3-gram of the input data, instead of 1-3 gram, to reduce the overall index size caused by long positing list of single and double charaters, which is not really helpful when search. And also help to increase the write speed.
Resolves #17099
=> Wildcard field use only 3-gram to index

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/SearchPhase.java, server/src/main/java/org/opensearch/action/search/SearchRequestStats.java, server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java, server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerTests.java, server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java, server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/16781 to 2.x. 
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.
=> [Backport 2.x] [Bugfix] Fix IllegalArgumentException thrown when creating a PIT

CHANGELOG-3.0.md, test/fixtures/hdfs-fixture/build.gradle
Jetty version bump
Resolves https://nvd.nist.gov/vuln/detail/CVE-2024-8184
=> Bump jetty version in hdfs-fixture to 9.4.57.v20241219

CHANGELOG.md, test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/17395
=> [Backport-2.19] Bump jetty version in hdfs-fixture to 9.4.57.v20241219

CHANGELOG.md, test/fixtures/hdfs-fixture/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/17395
=> [Backport 2.x] Bump jetty version in hdfs-fixture to 9.4.57.v20241219

CHANGELOG.md, modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java, modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpServerTransportTests.java
Excluding `zstd` from the list of default supported compressors: although `zstd-jni` is on the classpath, `ZstdEncoder` requires direct buffers supports and which by default `NettyAllocator` does not provide.
```
Caused by: java.lang.UnsupportedOperationException: Direct buffers not supported
at org.opensearch.transport.NettyAllocator$NoDirectBuffers.directBuffer(NettyAllocator.java:289) ~[transport-netty4-client-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
at io.netty.handler.codec.compression.ZstdEncoder.handlerAdded(ZstdEncoder.java:182) ~[netty-codec-4.1.118.Final.jar:4.1.118.Final]
at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130) [netty-transport-4.1.118.Final.jar:4.1.118.Final]
at …
```
=> HTTP API calls hang with 'Accept-Encoding: zstd'

CHANGELOG.md, modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java, modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpServerTransportTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/17408 to `2.19`
=> [Backport] [2.19] HTTP API calls hang with 'Accept-Encoding: zstd' (#17408)

CHANGELOG.md, modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java, modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpServerTransportTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/17408 to `2.x`
=> [Backport] [2.x] HTTP API calls hang with 'Accept-Encoding: zstd' (#17408)

CHANGELOG-3.0.md, server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java, server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
Signed-off-by: kkewwei <kewei.11@bytedance.com>
Signed-off-by: kkewwei <kkewwei@163.com>
Fix missing bucket in terms aggregation with missing value
Resolves #17391
=> Fix missing bucket in terms aggregation with missing value

CHANGELOG.md, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregationBuilder.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorSupplier.java, server/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorTests.java, test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/pull/17312 to 2.19
There's another PR for 2.x: https://github.com/opensearch-project/OpenSearch/pull/17419
Also need to backport the documentation https://github.com/opensearch-project/documentation-website/pull/9224
Resolves #[16837]
=> Introduce `execution_hint` for Cardinality aggregation (#17312) - backport to 2.19

MAINTAINERS.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/17430 to `2.x`
=> [Backport] [2.x] Update Andriy Redko (https://github.com/reta) affiliation (#17430)

MAINTAINERS.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/17431 to `1.3`
=> [Backport] [1.3] Update Andriy Redko (https://github.com/reta) affiliation (#17430) (#17431)

CHANGELOG-3.0.md, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java, plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java, plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaSourceConfig.java, plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaPartitionConsumerTests.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/IngestionShardConsumer.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java, server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java, server/src/test/java/org/opensearch/index/engine/FakeIngestionSource.java, server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
This PR supports starting the ingestion from a user-specified timestamp or offset when creating the new index.
- added two new ResetState: `REWIND_BY_OFFSET` and `REWIND_BY_TIMESTAMP`
- added new setting `ingestion_source.pointer.init.reset.value` to `IndexMetadata`, controls the rewind offset or timestamp in millis
- added corresponding integration tests
Resolves #17318 
=> [Pull-based Ingestion] Offset management, support rewind by offset or timestamp

server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
The `isStored` flag of wildcard field type is incorrectly set to true.
=> Correct the isStored flag for wildcard field type

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
* In the original test, we needed to make sure that the cluster had more no. of data nodes than the number of shard copies but it was not actually a guarantee leading to the flaky nature of tests.
* We are now pre-generating the random index/shard counts and then spawning the data nodes accordingly.
* Also decreased the upper limit on number of indices because original limit would have caused spawning of as high as 60 data nodes (`10 * 2 * (1 + 2)`) which was causing transport related failures unrelated to the scope of the test.
* Tested the new changes with ~3.4K consecutive IT runs without any failures
```
BUILD SUCCESSFUL in 18s
60 actionable tasks: 1 executed, 59 up-to-date
[2025-02-22 23:19:08] : ===================================================================
[2025-02-22 …
```
=> Fix flaky tests from`SegmentReplicationAllocationIT`

server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
- In `RemoteFsTimestampAwareTranslog.trimUnreferencedReaders`, in order to update file tracker to reflect local translog state, we fetch the minimum generation across all readers and delete all generations from `FileTransferTracker` that are less than the min generation.
https://github.com/opensearch-project/OpenSearch/blob/34ef1462abd55e931961c08d21b1dfa5855b8121/server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java#L128-L141 
- But `readers` is ArrayList, that means without locking readers if we try to read the list contents, we will get `ConcurrentModificationException` if a other thread is writing to readers.
- This was revealed by flaky test https://github.com/opensearch-project/OpenSearch/issues/15818 where test is failing with following stack trace: …
=> Fix ConcurrentModificationException in RemoteFsTimestampAwareTranslog.trimUnreferencedReaders

CHANGELOG.md, release-notes/opensearch.release-notes-2.19.1.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/17468 to `2.x`
=> [Backport] [2.x] Add 2.19.1 release notes (#17468)

CHANGELOG.md, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregationBuilder.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorSupplier.java, server/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorTests.java, test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/pull/17312 to 2.x
Backport to 2.19 is already done: https://github.com/opensearch-project/OpenSearch/pull/17420/files
Also need to backport the documentation https://github.com/opensearch-project/documentation-website/pull/9224
Resolves #[16837]
=> Introduce `execution_hint` for Cardinality aggregation (#17312) - backport to 2.x

.github/benchmark-configs.json, .github/workflows/benchmark-pull-request.yml
This PR:
* Removes non-usable configs for 2.x line as the workflow only gets triggered for default branch, which is mainline. 
* Refreshes the snapshot repository details and uses latest snapshots created on 3.0.0-alpha1 version. 
* Deprecated `http_logs` search only runs in favor of `big5`.  
* Adds `alpha1` qualifier to version being passed on to jenkins job.  …
=> Refresh benchmark configs to use 3.0.0-alpha1 version

CHANGELOG.md, release-notes/opensearch.release-notes-2.19.1.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/17469 to `main`
=> Add 2.19.1 release notes (#17468)

.github/workflows/benchmark-pull-request.yml
Add alpha1 qualifier to assemble command in benchmark workflow
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate …
=> add alpha1 qualifier to assemble command in benchmark workflow

CHANGELOG-3.0.md, server/src/main/java/org/opensearch/index/query/AbstractQueryBuilder.java, server/src/main/java/org/opensearch/index/query/BoolQueryBuilder.java, server/src/main/java/org/opensearch/index/query/ConstantScoreQueryBuilder.java, server/src/main/java/org/opensearch/index/query/QueryBuilder.java, server/src/main/java/org/opensearch/index/query/SpanNearQueryBuilder.java, server/src/test/java/org/opensearch/index/query/BoolQueryBuilderTests.java, server/src/test/java/org/opensearch/index/query/ConstantScoreQueryBuilderTests.java, server/src/test/java/org/opensearch/index/query/SpanMultiTermQueryBuilderTests.java, test/framework/src/main/java/org/opensearch/test/AbstractQueryTestCase.java
The filter function will combine a filter with the query builder. If the query builder itself has a filter we will combine the filter and return the query builder itself. If no we will use a bool query builder to combine the query builder and the filter and then return the bool query builder.
Resolves #17409
=> Add filter function for AbstractQueryBuilder, BoolQueryBuilder, ConstantScoreQueryBuilder

plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java, server/src/main/java/org/opensearch/action/admin/indices/stats/ShardStats.java, server/src/main/java/org/opensearch/action/admin/indices/stats/TransportIndicesStatsAction.java, server/src/main/java/org/opensearch/index/engine/Engine.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java, server/src/main/java/org/opensearch/indices/pollingingest/PollingIngestStats.java, server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java, server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java, server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodesTests.java, server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsResponseTests.java, server/src/test/java/org/opensearch/action/admin/indices/rollover/TransportRolloverActionTests.java, server/src/test/java/org/opensearch/action/admin/indices/shards/CatShardsResponseTests.java, server/src/test/java/org/opensearch/action/admin/indices/stats/IndicesStatsResponseTests.java, server/src/test/java/org/opensearch/cluster/DiskUsageTests.java, server/src/test/java/org/opensearch/index/shard/IndexShardTests.java, server/src/test/java/org/opensearch/indices/pollingingest/PollingIngestStatsTests.java, server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
This PR adds the basic NodeStats metrics to pull-based ingestion.
- Added total polled and total processed message count metrics, as part of IndexShardStats.
- Tested in the Kafka integration test
- TODO: add metrics for error handling and consume lag.
Resolves #17077 
=> [Pull-based Ingestion] add basic NodeStats metrics

CHANGELOG-3.0.md, server/src/internalClusterTest/java/org/opensearch/explain/ExplainActionIT.java, server/src/main/java/org/opensearch/action/explain/TransportExplainAction.java
There is an exception when call explain in "by_doc_id" mode. Response looks like this:
```
{
"error": {
"root_cause": [
{
"type": "query_shard_exception",
"reason": "failed to create query: async actions are left after rewrite",
"index": "my-nlp-index-1",
"index_uuid": "I6_pzGG3QBWw0B6KeOJ1pA"
}
],
"type": "query_shard_exception",
"reason": "failed to create query: async actions are left after rewrite",
"index": "my-nlp-index-1",
"index_uuid": "I6_pzGG3QBWw0B6KeOJ1pA",
"caused_by": {
"type": "illegal_state_exception",
"reason": "async actions are left after rewrite"
}
},
"status": 400
}
```
The error were caught from `TransportExplainAction -> Rewriteable.java` because there still be asyncActions left when the flag `assertNoAsyncTasks` returned as true.
The conflict is down to:
1.  The …
=> fix explain action on query rewrite

CHANGELOG-3.0.md, plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/IngestionShardConsumer.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/indices/pollingingest/BlockIngestionErrorStrategy.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/main/java/org/opensearch/indices/pollingingest/DropIngestionErrorStrategy.java, server/src/main/java/org/opensearch/indices/pollingingest/IngestionErrorStrategy.java, server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java, server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java, server/src/test/java/org/opensearch/index/engine/FakeIngestionSource.java, server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
This PR is a follow up for [pull-based-ingestion](https://github.com/opensearch-project/OpenSearch/pull/16958) to add error handling support. We introduce the following two strategies:
1. DROP: Drop errors and proceed with remaining updates in the ingestion source.
2. BLOCK: Block on any errors, preventing further writes.
This PR adds the drop/block support along with required interfaces. A follow up PR will add metric emission and record the errors.
When using Block strategy, we need a way to allow users to resume ingestion. Ingestion management APIs will be added to allow users more flexibility as part of https://github.com/opensearch-project/OpenSearch/issues/17442
Resolves #17085 …
=> [Pull-based Ingestion] Add error handling strategy to pull-based ingestion

.github/workflows/precommit.yml
Adds Windows 2025 + JDK 21 combination to the Precommit build matrix.
See https://github.blog/changelog/2024-12-19-windows-server-2025-is-now-in-public-preview/
Marked as experimental as the GitHub image is in public preview. …
=> Add Windows 2025+Java 21 combination to build matrix

server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
The check of comparing the max seq no and global checkpoint during bootstrap of ReadOnlyEngine for remote store enabled index is not required since the global checkpoint does not play a role with remote store. With a similar PR (https://github.com/opensearch-project/OpenSearch/pull/15990), changes were made to track the global checkpoint that has been updated as part of the successful translog upload to remote store. There are still cases where the global checkpoint appears to be changing locally but not getting updated on remote store. 
- ~[ ] Public documentation issue/PR …
=> Fix red index on close for remote enabled clusters

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java, server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexRemoteStoreSegmentReplicationIT.java, server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java, server/src/main/java/org/opensearch/cluster/routing/allocation/IndexMetadataUpdater.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java, server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/index/store/CompositeDirectory.java, server/src/main/java/org/opensearch/index/store/remote/utils/FileTypeUtils.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java, server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java, server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
This PR aims to implement the Replica Replication and Recovery flow for indices with partial store locality (also known as writable warm indices), which were introduced with the composite directory in PR #12782. It builds upon and addresses comments received on the pending PR #14670.
For writable indices, where primary shards now consist of both localDirectory and remoteDirectory, we've implemented file uploads to remote storage and maintain an LRU fileCache on the node instead of storing all files locally.
We've made several changes to the replication and recovery processes:
1. During replication events on replicas, we now only update the NRTReplicationReaderManager with the latest CheckpointInfoResponse, avoiding unnecessary downloads of actual file diffs on replica.
2. For index close, …
=> Writable warm replica replication/recovery

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java, server/src/main/java/org/opensearch/index/store/RemoteDirectory.java, server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java, test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java
- As part of https://github.com/opensearch-project/OpenSearch/pull/15333, read context in RemoteStoreRefreshListener is changed from `DEFAULT` to `READONCE`.
- But this fails with `java.lang.WrongThreadException: Attempted access outside owning thread`. 
```
Caused by: java.lang.WrongThreadException: Attempted access outside owning thread
at java.base/jdk.internal.foreign.MemorySessionImpl.wrongThread(MemorySessionImpl.java:315) ~[?:?]
at java.base/jdk.internal.misc.ScopedMemoryAccess$ScopedAccessError.newRuntimeException(ScopedMemoryAccess.java:113) ~[?:?]
at java.base/jdk.internal.foreign.MemorySessionImpl.checkValidState(MemorySessionImpl.java:219) ~[?:?]
at java.base/jdk.internal.foreign.ConfinedSession.justClose(ConfinedSession.java:83) ~[?:?]
at …
```
=> Change IOContext from READONCE to DEFAULT to avoid WrongThreadException

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java, server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
This PR addresses flakiness in remote store download stats correctness tests by improving test reliability and consistency.
The existing remote store download stats tests (`testDownloadStatsCorrectnessSinglePrimarySingleReplica` and `testDownloadStatsCorrectnessSinglePrimaryMultipleReplicaShards`) were experiencing intermittent failures due to:
- Race conditions in stats retrieval
- Inconsistent replication state
- Lack of robust waiting mechanisms
- Added `waitForReplication()` method to ensure consistent replication state
- Improved assertion logic to handle potential timing variations
- Enhanced logging and error tracking
- Refactored common test logic to reduce code duplication
- Improved stats validation methods
Resolves https://github.com/opensearch-project/OpenSearch/issues/14310
- …
=> Fix flaky tests in RemoteStoreStatsIT

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
During the build of backport PR https://github.com/opensearch-project/OpenSearch/pull/17543 (backport of https://github.com/opensearch-project/OpenSearch/pull/17535), the compilation is failing due to usage of methods introduced in jdk 16 & 21. In this PR, we have moved back to supported methods already being used.
For more …
=> Fix compilation issue for #17535 backport PR

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java, server/src/main/java/org/opensearch/index/store/RemoteDirectory.java, server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java, test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java
Backport https://github.com/opensearch-project/OpenSearch/commit/588f46d731587bebd54511dc2df21a2f4ffb9f32 from https://github.com/opensearch-project/OpenSearch/pull/17502
=> Change IOContext from READONCE to DEFAULT to avoid WrongThreadException (#17502)

server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
This PR adds a unit test for handling the case of choosing the correct metadata file when there are metadata files created by stale writer which has higher timestamp than correct writer (which has higher primary term) but below the pinned timestamp. This test checks that the timestamp picked is always the one with highest primary term. 
Accidentally closed https://github.com/opensearch-project/OpenSearch/pull/17536 and created this PR. …
=> Add test for stale writer correctness with pinned timestamp snapshots

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java, server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
Backport c48efd0fd59e598c983b59d952f41f7b69341812 from #17535 and 6b4597275fee56b28891272c2c8a216768687ed0 from #17546.
=> [Backport 2.x] Fix flaky tests in RemoteStoreStatsIT

CHANGELOG.md, distribution/src/config/opensearch.yml, modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheBaseIT.java, modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java, modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCachePluginTests.java, modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java, plugins/cache-ehcache/src/internalClusterTest/java/org/opensearch/cache/EhcacheDiskCacheIT.java, plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java, server/src/internalClusterTest/java/org/opensearch/indices/CacheStatsAPIIndicesRequestCacheIT.java, server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java, server/src/main/java/org/opensearch/common/cache/service/CacheService.java, server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java, server/src/main/java/org/opensearch/common/util/FeatureFlags.java, server/src/main/java/org/opensearch/indices/IndicesRequestCache.java, server/src/test/java/org/opensearch/common/cache/service/CacheServiceTests.java, server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java, server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Backports https://github.com/opensearch-project/OpenSearch/pull/17344 to 2.x. 
I wasn't sure what to do with the changelog - the original PR added an entry for CHANGELOG-3.0.md and for this one I put the same entry in CHANGELOG.md. Let me know if this isn't correct. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/17343
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTR …
=> [Backport 2.x] [Tiered Caching] Remove PLUGGABLE_CACHE feature flag

CHANGELOG.md, server/src/main/java/org/opensearch/wlm/QueryGroupService.java, server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
This change is to address the bug when search backpressure service is gathering the node stats and there are `QueryGroupTask`s in the system which doesn't have the **queryGroupId** set. In this case there will be a NPE thrown for node stats due to this [line](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/wlm/QueryGroupService.java#L334).
But this will only happen for 2.x versions since they don't have the scroll API changes for setting the **queryGroupId** https://github.com/opensearch-project/OpenSearch/pull/17169. We had to remove the API change because of the backward compatibility failure which was blocking the merge but later maintainers removed the check for internalApi annotated classes since they are not meant to be used outside of …
=> Add search backpressure service check for query group tasks

server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
Give more time for relocation to complete . Ran it for 500 times w/o failure , still running it . 
Resolves https://github.com/opensearch-project/OpenSearch/issues/17364
=> [Flaky test fix] Give more time for relocation to complete

CHANGELOG-3.0.md, server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/WritableWarmIT.java, server/src/main/java/org/opensearch/action/ActionModule.java, server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringUtils.java, server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java, server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java, server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java, server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/common/util/FeatureFlags.java, server/src/main/java/org/opensearch/index/IndexModule.java, server/src/main/java/org/opensearch/index/IndexService.java, server/src/main/java/org/opensearch/index/IndexSettings.java, server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java, server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java, server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsTieringAllocationTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/TieringAllocationBaseTestCase.java
- We currently only have tiering implementation for warm indices.
- The current nomenclature for feature flags and settings are too generic and cant differentiate between hot and warm indices.
- Since we want to implement tiering for hot indices as well in near future; we would want to update the nomenclature to be extensible and easy to understand, this PR present the nomenclature changes.
Resolves #[[17489](https://github.com/opensearch-project/OpenSearch/issues/17489)]
Meta Issue https://github.com/opensearch-project/OpenSearch/issues/13149
- [NA] Functionality includes testing.
- [NA ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [NA] Public documentation issue/PR …
=> Updated nomenclature to differentiate between hot and warm tiering implementation.

plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/KafkaIngestionBaseIT.java, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/indices/pollingingest/BlockIngestionErrorStrategy.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/main/java/org/opensearch/indices/pollingingest/DropIngestionErrorStrategy.java, server/src/main/java/org/opensearch/indices/pollingingest/IngestionErrorStrategy.java, server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java, server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java, server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
1. This PR is a follow up for #17427 to add support for dynamically updating ingestion error strategy using [update_settings](https://opensearch.org/docs/latest/api-reference/index-apis/update-settings/) API. 
2. Message processor will indefinitely retry failed messages after a wait time, if a BLOCK error strategy is used. Updating to DROP strategy will skip the failed messages.
3. Additionally, the PR includes minor fixes - fixes initial global checkpoint in p2p segRep mode which is validated by flows such as CloseIndex API and handle race condition on flush before poller is initialized completely.
This PR forms the base on which subsequent PRs will build on for adding pause/resume APIs.
Resolves part of #17442. Subsequent PRs will add pause/resume APIs.
By submitting this pull request, …
=> [Pull-based Ingestion] Add support for dynamically updating ingestion error handling strategy with minor fixes

CHANGELOG.md, server/src/main/java/org/opensearch/wlm/QueryGroupService.java, server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/8ee5eebc3728a19487c0604d9828f92770fcd7ec from https://github.com/opensearch-project/OpenSearch/pull/17576.
=> [Backport 2.19]Add search backpressure service check for query group tasks (#17576)

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
The test case org.opensearch.remotestore.RemoteRestoreSnapshotIT.testClusterManagerFailoverDuringSnapshotCreation is flaky.
```
RemoteRestoreSnapshotIT > testClusterManagerFailoverDuringSnapshotCreation FAILED
java.lang.NullPointerException: Cannot invoke "org.opensearch.snapshots.SnapshotInfo.snapshotId()" because "snapshotInfo[0]" is null
at __randomizedtesting.SeedInfo.seed([17FD038E1B5EBC1C:75687A3B8DF56E57]:0)
at org.opensearch.remotestore.RemoteRestoreSnapshotIT.testClusterManagerFailoverDuringSnapshotCreation(RemoteRestoreSnapshotIT.java:1486)
```
The test allows snapshot creation to fail and, if it does, verifies that the repository does not include its ID. In this scenario, the snapshot is not created - its snapshot info will be `null` - which leads to an NPE.
Resolves …
=> Fix flakiness of RemoteRestoreSnapshotIT.testClusterManagerFailoverDuringSnapshotCreation

plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RemoteStoreIT.java
This PR mutes the test class S3RemoteStoreIT as there is some flakiness observed in the tests. The test run time is high due to actual calls being made to S3. I am planning to fix the tests in a follow up PR and run the tests for 1000+ iterations. I have notice each iteration take around 10-15 mins with my setup. For now, this will mute the tests in S3RemoteStoreIT class.
By submitting this pull request, I confirm that my contribution is made …
=> Mute flaky tests - S3RemoteStoreIT

server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
Fixes ordering change of pre-computation steps in Max/Min aggregator which was accidentally changed in https://github.com/opensearch-project/OpenSearch/pull/16733/
For match-all cases, max/min aggregation without any parent/child aggregations can be precomputed faster than star-tree, so that's why it was prioritized over star-tree pre-computation. This ordering was modified accidentally in the [above](https://github.com/opensearch-project/OpenSearch/pull/16733/) refactoring change, so making this change back.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/ …
=> [bug fix] fix precompute ordering in max & min aggregator

CHANGELOG.md, qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Resolves integTest bug on deb to check for `opensearch:adm`
Resolves #17614 
=> Resolve integTest bug on deb to check for opensearch:adm

server/src/test/java/org/opensearch/index/fielddata/ordinals/MultiOrdinalsTests.java
Lucene 10 makes it illegal to call `SortedSetDocValues#nextOrd()` more than#docValueCount() times for the currently-positioned doc. This was causing flakiness in `MultiOrdinalsTests` as encountered in PR https://github.com/opensearch-project/OpenSearch/pull/17446 with failure https://build.ci.opensearch.org/job/gradle-check/54686/testReport/junit/org.opensearch.index.fielddata.ordinals/MultiOrdinalsTests/testRandomValues/
https://github.com/apache/lucene/blob/e7f9bc837e419672d9bfc829d01e643df667e9d4/lucene/core/src/java/org/apache/lucene/index/SortedSetDocValues.java#L36
We need to address this throughout the codebase thus created https://github.com/opensearch-project/OpenSearch/issues/17628
https://github.com/opensearch-project/OpenSearch/issues/17628 
~~- [ ] API changes companion pull …
=> Fix flaky test due to incorrect use of SSDV.nextOrd()

CHANGELOG.md, plugins/repository-azure/build.gradle, plugins/repository-azure/licenses/azure-storage-blob-12.29.1.jar.sha1, plugins/repository-azure/licenses/azure-storage-blob-12.30.0.jar.sha1
Backport of https://github.com/opensearch-project/OpenSearch/pull/17667 to `2.x`
=> [Backport] [2.x] Bump com.azure:azure-storage-blob from 12.29.1 to 12.30.0 in /plugins/repository-azure (#17667)

CHANGELOG.md, server/src/main/java/org/apache/lucene/util/UnsignedLongHashSet.java, server/src/main/java/org/opensearch/index/document/SortedUnsignedLongDocValuesSetQuery.java, server/src/test/java/org/opensearch/lucene/util/DocValuesUnsignedLongHashSetTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/17207 to `2.x`
=> [Backport] [2.x] Fix Bug - Handle unsigned long in sorting order assertion of LongHashSet (#17207)

libs/agent-sm/agent-policy/build.gradle, libs/agent-sm/agent-policy/src/test/java/org/opensearch/secure_sm/policy/PolicyParserTests.java
Follow on to #17663. Adding a basic unit test of the policy parsing logic.
=> Add simple PolicyParser unit test

.github/workflows/gradle-check.yml
https://github.com/opensearch-project/OpenSearch/pull/17688 seems to be working fine. Forwarding the change to gradle check workflow.
Add credentials to retrieve jenkins data as we plan to switch from anonymous read-only access to authenticated users. Associated PR that has script changes: https://github.com/opensearch-project/opensearch-build/pull/5425 (needs to go in first).
=> Authenticate jenkins calls for gradle check

plugins/ingestion-kinesis/src/internalClusterTest/java/org/opensearch/plugin/kinesis/IngestFromKinesisIT.java
There's some flakiness of Kinesis integration tests, likely due to the fact that in LocalStack, the message propagation or availability might not be immediate. So when we immediately attempt to consume it, it might not be fully "visible" depending on timing, especially with a rewind to a precise AT_SEQUENCE_NUMBER. Tweaked the test with some more produced messages, and longer sleep so the records are committed and readable.
Ran the same tests 5 times locally, and test all passed.
=> attempt to fix flaky test in IngestFromKinesisIT

server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
The explain api `POST _cluster/allocation/explain`, explains how an allocation decision is made, but during the calculation of `currentWeight` in 
https://github.com/opensearch-project/OpenSearch/blob/399188f3034936f237bd9d43e40cf7528d8f5c40/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#L209
, it uses original `weight` function which does not consider allocation/rebalance constraint:
https://github.com/opensearch-project/OpenSearch/blob/399188f3034936f237bd9d43e40cf7528d8f5c40/server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java#L234-L238
However the following calculation uses the new `weightWithRebalanceConstraints`, which is correct …
=> Fix weight calculation of decideRebalance when explain

CHANGELOG.md, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/common/util/concurrent/AbstractAsyncTask.java, server/src/main/java/org/opensearch/index/IndexModule.java, server/src/main/java/org/opensearch/index/IndexService.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/test/java/org/opensearch/index/IndexModuleTests.java, server/src/test/java/org/opensearch/index/IndexServiceTests.java
Added fixed interval scheduling capability for refresh tasks to ensure consistent intervals between refreshes. Key changes:
1. Introduced new setting `cluster.index.refresh.fixed_interval_scheduling.enabled` (default: false)
2. Enhanced `AbstractAsyncTask` to track last run time and calculate dynamic sleep durations
3. Added staggered start times for initial refreshes to prevent concurrent refreshes across shards
Meta issue: https://github.com/opensearch-project/OpenSearch/issues/17776 …
=> Implement fixed interval refresh task scheduling

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerProtectionDomainChainExtractor.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/AgentTestCase.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/AgentTests.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SocketChannelInterceptorTests.java
The optimization of using a Stream instead of a Collection caused problems with class not found and/or illegal access errors when using the lambda function in the `Stream::forEach` call in the intercept method.
FYI @RajatGupta02 
=> Fix socket interceptor and add unit test

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/RuntimeHaltInterceptor.java, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerClassChainExtractor.java, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SystemExitInterceptor.java, libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/AgentPolicy.java
Fix StackCallerClassChainExtractor and respectively RuntimeHaltInterceptor, SystemExitInterceptor
See please https://github.com/opensearch-project/OpenSearch/pull/17784 
=> Fix StackCallerClassChainExtractor and respectively RuntimeHaltInterceptor, SystemExitInterceptor

libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SocketChannelInterceptorTests.java
Adds some additional tests for Socket Channel Interceptor
Resolves #17664 
=> Add some additional tests for SocketChannelInterceptor

CHANGELOG.md, server/src/main/java/org/opensearch/ingest/IngestService.java, server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java, server/src/test/java/org/opensearch/ingest/IngestServiceTests.java, server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Improve validation for ingest and search pipeline id length to 20.
Resolves https://github.com/opensearch-project/OpenSearch/issues/17766
=> Introduce 512 byte limit to search and ingest pipeline IDs 

gradle/ide.gradle
I set up a new laptop with a fresh install of IntelliJ this week.
When I tried importing OpenSearch, it failed to do the IDE setup, because we check the `.idea/gradle.xml` file for Gradle-specific JVM configuration (forcing Gradle to use the project JVM). It looks like IntelliJ has stopped creating the `gradle.xml` file under the project by default, so I got a `FileNotFoundException`.
To fix it / work around, I checked for existence of the file before trying to modify it. I think this is worth doing anyway and doesn't hurt. Maybe other new contributors will run into the same problem and this will help them.
N/A …
=> Check for gradle.xml before trying to modify it

CHANGELOG.md, server/src/main/java/org/opensearch/tasks/BaseSearchTaskCancellationStats.java, server/src/main/java/org/opensearch/tasks/SearchShardTaskCancellationStats.java, server/src/main/java/org/opensearch/tasks/SearchTaskCancellationStats.java, server/src/main/java/org/opensearch/tasks/TaskCancellationMonitoringService.java, server/src/main/java/org/opensearch/tasks/TaskCancellationStats.java, server/src/test/java/org/opensearch/tasks/SearchTaskCancellationStatsTests.java, server/src/test/java/org/opensearch/tasks/TaskCancellationMonitoringServiceTests.java, server/src/test/java/org/opensearch/tasks/TaskCancellationStatsTests.java
This PR addes tracking logic for SearchTask to monitor rogue queries at the coordinator level. Previously, the service only tracked SearchShardTask (queries at the shard level) that were cancelled but continued running. 
https://github.com/opensearch-project/OpenSearch/issues/17719
=> Add tracking for long running SearchTask post cancellation

.github/CODEOWNERS, MAINTAINERS.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/17805.
=> [Backport 2.x] Remove dblock@ from maintainers.

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java
Fix FileInterceptor to deduct the access level from the list of OpenOption
N/A
=> Fix FileInterceptor to deduct the access level from the list of OpenOption

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/FileInterceptorIntegTests.java
Fix FileInterceptor to properly check read / write sides path separation
N/A
=> Fix FileInterceptor to properly check read / write sides path separation

server/src/main/java/org/opensearch/index/reindex/WorkerBulkByScrollTaskState.java
Fix possible NPE in rethrottling requests.
No tests were run, i think this is useless here
Resolves #17839 
=> Fix possible NPE in WorkerBulkByScrollTaskState.java

libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java
This PR adds a cache of protection domain mapped to a Permission collection. Such a caching is useful to fasten the ```implies``` call (from socket and file interceptor) to avoid re-evaluation of permissions in every call. 
=> [Java Agent] Implement protection domain caching

server/src/internalClusterTest/java/org/opensearch/action/admin/indices/scale/searchonly/ScaleIndexIT.java
Fix ScaleIndexIT `testFullSearchOnlyReplicasFullLifecycle` flaky test. Seen failures in:
- https://build.ci.opensearch.org/job/gradle-check/55829/testReport/junit/org.opensearch.action.admin.indices.scale.searchonly/ScaleIndexIT/testFullSearchOnlyReplicasFullLifecycle/
- https://build.ci.opensearch.org/job/gradle-check/55781/testReport/junit/org.opensearch.action.admin.indices.scale.searchonly/ScaleIndexIT/testFullSearchOnlyReplicasFullLifecycle/
I was not able to re-produce the error, but looking at the code using `ensureYellow` is better that a manual `YELLOW` assert. The `ensureYellow` also has a timeout value, so the line `internalCluster().stopRandomNode(InternalTestCluster.nameFilter(findNodesWithSearchOnlyReplicas()[0]));` should stop the node, leave the search replica unassigned …
=> Fix ScaleIndexIT `testFullSearchOnlyReplicasFullLifecycle` flaky test

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java, server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
As `IngestionSource` takes more arguments, it's better to change the constructor to a builder pattern
=> Add a builder to ingestion source

CHANGELOG.md, libs/core/src/main/java/org/opensearch/ExceptionsHelper.java, server/src/main/java/org/opensearch/OpenSearchServerException.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/index/engine/IngestionEngineException.java, server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java, server/src/test/java/org/opensearch/ExceptionSerializationTests.java, server/src/test/java/org/opensearch/index/engine/IngestionEngineTests.java
The indexing API call will fail for ingestion engine. For example
```
curl -X PUT -H 'Content-Type: application/json' http://localhost:9200/my-index/_doc/1 --data '
{
"name": "John Doe",
"age": 24
}
'
```
returns
```
{"error":{"root_cause":[{"type":"unsupported_operation_exception","reason":"push-based indexing is not supported in ingestion engine, use streaming source instead"}],"type":"unsupported_operation_exception","reason":"push-based indexing is not supported in ingestion engine, use streaming source instead"},"status":400}%
```
https://github.com/opensearch-project/OpenSearch/issues/16930 …
=> [Pull-based Ingestion] disable push-API for indexing in ingestionEngine

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/AgentTestCase.java, libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/AgentPolicy.java
Add the support of trusted file systems to AgentPolicy. The security checks where part of the `FileSystem` implementations (JDK) but we do use mock file systems (like Jimfs) in tests. Since we made checks global now, adding the support of trusted file systems (similarly to trusted hosts) to the `AgentPolicy`
N/A
=> Add the support of trusted file systems to AgentPolicy

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java, server/src/main/java/org/opensearch/action/bulk/BulkRequest.java, server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java, server/src/main/java/org/opensearch/ingest/IngestService.java, server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java, server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java, server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
=> Remove deprecated batch_size parameter from _bulk

server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationAndRecoveryIT.java, server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaRestoreIT.java, server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java, server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/test/java/org/opensearch/cluster/metadata/SearchOnlyReplicaTests.java, server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
Rename search_only_replica settings to search_replica
Resolves #https://github.com/opensearch-project/OpenSearch/issues/17845
=> Rename search_only_replica settings to search_replica

server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateNumberOfReplicasIT.java, server/src/main/java/org/opensearch/cluster/metadata/AutoExpandReplicas.java, server/src/test/java/org/opensearch/cluster/metadata/AutoExpandReplicasTests.java
Adjust the `getAutoExpandReplicaChanges` logic to honor search_only mode.
- https://github.com/opensearch-project/OpenSearch/issues/17864
- RW Separation META Issue: https://github.com/opensearch-project/OpenSearch/issues/15306
- Scale to zero (search only mode): https://github.com/opensearch-project/OpenSearch/issues/16720
=> Adjust the `getAutoExpandReplicaChanges` logic to honor `search_only` mode.

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
Allow maxPollSize and pollTimeout in IngestionSource to be configurable
=> [Pull-based ingestion] make maxPollSize and pollTimeout in IngestionSource configurable

CHANGELOG.md, modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldTypeTests.java, server/src/main/java/org/opensearch/common/util/FeatureFlags.java, server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java, server/src/main/java/org/opensearch/index/search/NestedHelper.java, server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java, server/src/main/java/org/opensearch/search/approximate/ApproximateScoreQuery.java, server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java, server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java, server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java, server/src/test/java/org/opensearch/index/mapper/RangeFieldQueryStringQueryBuilderTests.java, server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java, server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java, server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java, server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java, server/src/test/java/org/opensearch/search/approximate/ApproximateScoreQueryTests.java
We introduced `ApproximatePointRangeQuery` as an experimental feature flag in #13788, we're going to GA this approximate query in OS 3.0 and hence removing the feature flag.
=> Remove feature flag for ApproximatePointRangeQuery

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
In the SegmentReplicationIT.testReplicaAlreadyAtCheckpoint test, we are creating three nodes with one primary node and two replica nodes. After ingesting documents to the primary shard, we are not checking if the segment replication to both replica 1 and 2 has finished. Without verifying this, we are stopping the primary node. This behavior leads to the test being flaky when the replication has not completed.
```
1> org.opensearch.transport.NodeDisconnectedException: [node_t0][127.0.0.1:41957][disconnected] disconnected
1> [2025-01-15T22:22:47,061][INFO ][o.o.c.c.FollowersChecker ] [node_t0] FollowerChecker{discoveryNode={node_t1}{jpNpHksYQ7-Fb8W2sTp8Sg}{RSZGRaXJQfWjT8jbA4p4iA}{127.0.0.1}{127.0.0.1:42245}{d}{shard_indexing_pressure_enabled=true}, failureCountSinceLastSuccess=0, …
```
=> Fix flaky test SegmentReplicationIT.testReplicaAlreadyAtCheckpoint

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java
Fix FileInterceptor's delete calls for Unix Domain Sockets on Windows
See please https://github.com/opensearch-project/custom-codecs/actions/runs/14370198700/job/40291704566?pr=235
=> Fix FileInterceptor's delete calls for Unix Domain Sockets on Windows

gradle/ide.gradle
Taking the summary from my conversation with Claude to fix this:
1. We needed afterEvaluate to ensure the project was fully configured before accessing its properties
2. The correct path was in build/distributions rather than build/libs
3. We had to properly handle Gradle's Provider API when constructing the path
4. The jar name needed to include both the archivesName and the project version
Resolves https://github.com/opensearch-project/OpenSearch/issues/17883 …
=> Fix javaagent arg when running in IntelliJ

libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java
A quick fix to unblock load of PA plugins which defines Attach Permissions in its policy.
Fixes: https://github.com/opensearch-project/performance-analyzer/issues/795
=> [Java Agent Policy Parser] Skip evaluation of AttachPermission

server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java
There was a possibility of a null pointer exception error when the BooleanScorer passes in a null document. The document is assumed to not be null, and while that might be true for the DefaultBulkScorer, it is not checked in the BooleanScorer.
Resolves #17739
=> Cardinality Aggregation dynamic pruning null pointer exception catch

buildSrc/src/main/java/org/opensearch/gradle/agent/JavaAgent.java, buildSrc/src/main/resources/META-INF/gradle-plugins/opensearch.java-agent.properties, buildSrc/src/test/java/org/opensearch/gradle/agent/JavaAgentTests.java
To Support phasing off SecurityManager usage in favor of Java Agent a custom Gradle plugin from core should help leverage the java agent. 
Coming from https://github.com/opensearch-project/custom-codecs/pull/235#discussion_r2036383205 created a custom java agent plugin that can be applied as required.  The plugins can use as `apply plugin: 'opensearch.java-agent'`. With this we can remove the duplicate code across plugins.
I have tested by adding `apply plugin: 'opensearch.java-agent'` to job-scheduler and now able to run the tests depend on java agent.
Part of https://github.com/opensearch-project/OpenSearch/issues/16634 and https://github.com/opensearch-project/OpenSearch/issues/16753
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Custom Gradle plugin to leverage java agent 

server/src/test/java/org/opensearch/index/mapper/BytesRefsCollectionBuilderTests.java, server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
I wasn't clear in communication under #17714. Let's sweep these tests.   
=> FIX BytesRefsCollectionBuilderTests.testBuildSortedNotSorted; Followup for #17714: Remove redundant tests

gradle/ide.gradle
Small debug artifact from #17886.
N/A
~~- [ ] Functionality includes testing.~~
~~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~~
=> Remove ide.gradle debug artifact.

plugins/repository-azure/src/internalClusterTest/java/org/opensearch/repositories/azure/AzureBlobStoreRepositoryTests.java
- Due to the default `SUITE` scope on AzureBlobStoreRepositoryTests, the number of documents indexed with each test gets added and huge number of documents and segments created as part of this takes time for snapshot to create and eventually times out the test suite.
- We can reproduce this issue with following:
```
/gradlew ':plugins:repository-azure:internalClusterTest' --tests "org.opensearch.repositories.azure.AzureBlobStoreRepositoryTests"  -Dtests.seed=773F78819373DA07
```
- As part of this PR, we change the scope to `TEST`.
- https://github.com/opensearch-project/OpenSearch/issues/14291 …
=> Fix flaky test AzureBlobStoreRepositoryTests

distribution/packages/build.gradle
Fixes the issue where DEB/RPM of OS Core does not include the `agent` folder as in Tar/Zip
- #17914 
=> [FIX] Add agent files in deb/rpm

server/src/test/java/org/opensearch/common/util/concurrent/AbstractAsyncTaskTests.java
This PR adds a simple UT to validate that the getSleepDuration does not thrown exception when doing refresh for the first time. 
=> Add UT for getSleepDuration in AbstractAsyncTask

server/src/test/java/org/opensearch/index/query/BoolQueryBuilderTests.java
This PR is trying to fix a flakey test `org.opensearch.index.query.BoolQueryBuilderTests.testToQuery`.
Resolves #[[17943](https://github.com/opensearch-project/OpenSearch/issues/17943)]
=> Fix flaky test BoolQueryBuilderTests.testToQuery

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/indices/create/TransportCreateIndexAction.java, server/src/main/java/org/opensearch/action/admin/indices/mapping/put/TransportPutMappingAction.java, server/src/main/java/org/opensearch/action/admin/indices/template/put/TransportPutComponentTemplateAction.java, server/src/main/java/org/opensearch/action/admin/indices/template/put/TransportPutComposableIndexTemplateAction.java, server/src/main/java/org/opensearch/action/admin/indices/template/put/TransportPutIndexTemplateAction.java, server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java, server/src/main/java/org/opensearch/cluster/metadata/Template.java, server/src/main/java/org/opensearch/index/mapper/MappingTransformer.java, server/src/main/java/org/opensearch/index/mapper/MappingTransformerRegistry.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/MapperPlugin.java, server/src/test/java/org/opensearch/action/admin/indices/create/TransportCreateIndexActionTests.java, server/src/test/java/org/opensearch/action/admin/indices/mapping/put/TransportPutMappingActionTests.java, server/src/test/java/org/opensearch/action/admin/indices/template/put/TransportPutComponentTemplateActionTests.java, server/src/test/java/org/opensearch/action/admin/indices/template/put/TransportPutComposableIndexTemplateActionTests.java, server/src/test/java/org/opensearch/action/admin/indices/template/put/TransportPutIndexTemplateActionTests.java, server/src/test/java/org/opensearch/index/mapper/MappingTransformerRegistryTests.java, server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java, server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
In this PR we introduce the mapping transformer to the core to allow transforming the mapping during index create/update and index template create/update. We want to do this because we have a use case in neural search plugin where we want to auto generate the semantic fields(e.g. knn_vector or rank_feature) in the mappings based on the model id defined in the semantic field(A new field type introduced by neural search plugin). In this way we can simplify the neural search set up.
Potentially in future this feature can be leveraged by other plugins to auto transform the mapping based on the certain config defined by users.
Resolves [#[17500]](https://github.com/opensearch-project/OpenSearch/issues/17500) - Proposal to introduce the mapping transformer into core. …
=> Introduce mapping transformer to allow transform mappings during index create/update or index template create/update

plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java, plugins/ingestion-kinesis/src/internalClusterTest/java/org/opensearch/plugin/kinesis/IngestFromKinesisIT.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java, server/src/main/java/org/opensearch/indices/pollingingest/PollingIngestStats.java, server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java, server/src/test/java/org/opensearch/indices/pollingingest/MessageProcessorTests.java, server/src/test/java/org/opensearch/indices/pollingingest/PollingIngestStatsTests.java
- add metric of skipped messages in pull-based ingestion processing
- use record class for the PollingIngestStats
=> add metric of skipped messages in pull-based ingestion processing

server/src/test/java/org/opensearch/search/aggregations/startree/RangeAggregatorTests.java
```
./gradlew ':server:test' --tests "org.opensearch.search.aggregations.startree.RangeAggregatorTests.testRangeAggregation" -Dtests.seed=A5CF5DD34EE06092 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=nl -Dtests.timezone=Asia/Ust-Nera -Druntime.java=21
```
Able to consistently reproduce failure locally and the test fixes after change. 
https://github.com/opensearch-project/OpenSearch/issues/17928
=> Closing the directory reader to fix test

server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
This PR fixes the flaky test `org.opensearch.indices.replication.SegmentReplicationTargetServiceTests#testStartReplicationListenerSuccess`.
Reproduce method command reference [gradle check](https://build.ci.opensearch.org/job/gradle-check/53583/testReport/junit/org.opensearch.indices.replication/SegmentReplicationTargetServiceTests/testStartReplicationListenerSuccess/).
```
./gradlew ':server:test' --tests "org.opensearch.indices.replication.SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess" -Dtests.seed=67540127BBCFAD6A -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=fr-CA -Dtests.timezone=Africa/Casablanca -Druntime.java=21
```
This test cannot be reproduced stably, and there may be `1` error …
=> Fix flaky test SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess

build.gradle, gradle.properties, settings.gradle
To fix the deprecation warnings in #13942 I believe I should have just removed the gradle enterprise plugin all together as I think it is unused. This commit goes back to using the open-source test-retry Gradle plugin and removes develocity.
This should not change the functionality of the test retry logic in any way.
=> Use test-retry plugin in place of develocity

plugins/transport-grpc/README.md, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/GrpcPlugin.java, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/Netty4GrpcServerTransport.java, plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/GrpcPluginTests.java
Additional settings for experimental gRPC transport plugin.
Particularly settings related to managing client connection lifetimes.
`grpc.netty.max_concurrent_connection_calls`
Limit concurrent in flight requests per client connection.
`grpc.netty.max_connection_age`
Set timeout for persistent connections.
`grpc.netty.max_connection_idle`
Set timeout for idle connections.
`grpc.netty.keepalive_timeout`
Set timeout for connection keepalive pings.
Resolves #17783
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …
=> Additional settings for gRPC experimental transport.

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/Agent.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SocketChannelInterceptorTests.java, modules/repository-url/src/test/resources/org/opensearch/bootstrap/test.policy, plugins/discovery-ec2/src/test/resources/org/opensearch/bootstrap/test.policy, plugins/repository-s3/src/test/resources/org/opensearch/bootstrap/test.policy
=> Intercept java.net.Socket::connect

server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
There's a compile error due to the both change in the DefaultStreamPoller class in the latest 2 PRs https://github.com/opensearch-project/OpenSearch/pull/17995/files#diff-f8b0b74e29348e27ce7f607a570e6fe30656f008a5296f637597aad55edbb293R218 and https://github.com/opensearch-project/OpenSearch/pull/17995/files#diff-f8b0b74e29348e27ce7f607a570e6fe30656f008a5296f637597aad55edbb293R218, need to replace the two parameters with the local variables.
No issue.
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), …
=> Resolve compile error in DefaultStreamPoller

server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java, test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
If `HASHED_PREFIX` or `HASHED_INFIX` is used in this test then it frequently fails. @ashking94 Can you take a look here? I'm guessing there might be a bug with snapshot cleanup for the new remote store path types. This is really more of a short-term work-around to avoid the new path types for this particular test case, but it does seem to resolve the flakiness of the test.
Resolves #15806
=> Use 'FIXED' path type in DedicatedClusterSnapshotRestoreIT

plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Fix flaky ReactorNetty4StreamingStressIT
Closes https://github.com/opensearch-project/OpenSearch/issues/15840
=> Fix flaky ReactorNetty4StreamingStressIT

CHANGELOG.md, server/src/main/java/org/opensearch/index/mapper/BytesRefsCollectionBuilder.java, server/src/main/java/org/opensearch/index/mapper/IdFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java, server/src/main/java/org/opensearch/index/mapper/TermBasedFieldType.java, server/src/test/java/org/opensearch/index/mapper/BytesRefsCollectionBuilderTests.java, server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
=> backport sorted BytesRef to TermInSet #17714 to 2.x

server/src/main/java/org/opensearch/index/query/ConstantScoreQueryBuilder.java, server/src/main/java/org/opensearch/index/query/DisMaxQueryBuilder.java, server/src/main/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilder.java
This PR contains changes to iterate subquery builder recursively.
[17829](https://github.com/opensearch-project/OpenSearch/issues/17829)
[1269](https://github.com/opensearch-project/neural-search/issues/1269)
[1251](https://github.com/opensearch-project/neural-search/issues/1251)
=> Visit the subquery builder recursively

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
=> fix simultaneously creating a snapshot and updating the repository can potentially trigger an infinite loop

server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java
Just adds a new instance type for new Query type. Ran this for 1500+ iterations with no failures
Resolves #17934
=> Fix flaky multimatchquerybuildertests

CHANGELOG.md, server/src/main/java/org/opensearch/http/HttpTransportSettings.java
Our current default max header size is `8KB`.
related osd issues
- https://github.com/opensearch-project/security-dashboards-plugin/issues/1311#issuecomment-1474074780
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9572
When using JWT token-based authentication, an 8KB header size is insufficient.
Elasticsearch encountered the same issue and has increased the default value to 16KB.
see : https://github.com/elastic/elasticsearch/pull/88725
Unless there are any particular concerns, I suggest we do the same and change our default to `16KB` as well.
Resolves #18022  …
=> Increase default http.max_header_size to `16kb`

.github/workflows/detect-breaking-change.yml
We'll need to come back and update this after the 3.0 release but for now we should not be enforcing breaking changes against 3.0.
=> Ignore 3.0 branch for breaking changes check

libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerProtectionDomainChainExtractor.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/StackCallerProtectionDomainExtractorTests.java
Parallel backport of fix from #17894
=> [Backport 3.0] Limit stack walking to frames before AccessController.doPrivileged

distribution/tools/java-version-checker/src/main/java/org/opensearch/tools/java_version_checker/JavaVersionChecker.java
Manually tested this:
```
% JAVA_HOME=~/.sdkman/candidates/java/11.0.27-tem ./bin/opensearch
OpenJDK 64-Bit Server VM warning: Shared spaces are not supported in this VM
OpenSearch requires Java 21; your Java version from [/Users/andrross/.sdkman/candidates/java/11.0.27-tem] does not meet this requirement
```
=> Update JavaVersionChecker to enforce min of JDK21

CHANGELOG.md, plugins/transport-grpc/src/internalClusterTest/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransportIT.java, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/GrpcPlugin.java, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransport.java, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/package-info.java, plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/GrpcPluginTests.java, plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransportTests.java, plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/ssl/SecureSettingsHelpers.java
Files were misplaced under `org.opensearch.transport.grpc` instead of `org.opensearch.plugin.transport.grpc`. 
https://github.com/opensearch-project/OpenSearch/issues/16787
=> Remove package org.opensearch.transport.grpc and replace with org.opensearch.plugin.transport.grpc

plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaUtils.java
We've seen multiple failures where the 3 second timeout was breached. This happens in the test setup of many different tests so multiple individual test failures have been reported.
Also replace deprecated method in Kafka API and simplify a couple other code paths.
Resolves #17215
=> Increase Kafka topic polling time in test to 10 seconds

.github/workflows/benchmark-pull-request.yml, .github/workflows/publish-maven-snapshots.yml, CHANGELOG.md, distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/InstallPluginCommand.java
Bump OpenSearch Core main branch to 3.0.0 and update key id for native plugin checks
https://github.com/opensearch-project/opensearch-build/issues/3747
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CON …
=> Bump OpenSearch Core main branch to 3.0.0 and update key id for native plugin checks

CHANGELOG.md, server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/NodesHotThreadsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/reload/NodesReloadSecureSettingsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java, server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/wlm/WlmStatsRequest.java, server/src/main/java/org/opensearch/action/admin/indices/dangling/find/FindDanglingIndexRequest.java, server/src/main/java/org/opensearch/action/admin/indices/dangling/list/ListDanglingIndicesRequest.java, server/src/main/java/org/opensearch/action/search/GetAllPitNodesRequest.java, server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java, server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java, server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java, server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java, server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java, server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java
Unset discovery nodes for every transport node actions request (#17682)
- Backporting #17682 to 3.0
Resolves #17008 
=> [Backport 3.0] Unset discovery nodes for every transport node actions request (#17682)

.github/workflows/benchmark-pull-request.yml, .github/workflows/publish-maven-snapshots.yml, CHANGELOG.md, distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/InstallPluginCommand.java
[Backport 3.0] Bump OpenSearch Core main branch to 3.0.0 and update key id for native plugin checks
Backport #18039 …
=> [Backport 3.0] Bump OpenSearch Core main branch to 3.0.0 and update key id for native plugin checks

.ci/java-versions.properties
My understanding is that BwcSetupExtension.java uses this Java version to compile this code when another branch checks out this branch to use in backward compatibility tests. This needs to be JDK21 in order for this code to compile correctly.
I believe #18043 is failing because this version is wrong.
=> Set Java version to 21 for use in bwc tests

CHANGELOG.md, plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaMessage.java, plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java, plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaMessageTests.java, plugins/ingestion-kinesis/src/main/java/org/opensearch/plugin/kinesis/KinesisMessage.java, plugins/ingestion-kinesis/src/main/java/org/opensearch/plugin/kinesis/KinesisShardConsumer.java, plugins/ingestion-kinesis/src/test/java/org/opensearch/plugin/kinesis/KinesisMessageTests.java, server/src/main/java/org/opensearch/index/Message.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/main/java/org/opensearch/indices/pollingingest/PollingIngestStats.java, server/src/test/java/org/opensearch/index/engine/FakeIngestionSource.java, server/src/test/java/org/opensearch/indices/pollingingest/PollingIngestStatsTests.java
Emit lag metric for pull-based ingestion poller
Also update the API of message to return the timestamp of the message
=> [Pull-based ingestion] Emit lag metric for pull-based ingestion poller

server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java, server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java, server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java, server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java, server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsTieringAllocationTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/TieringAllocationBaseTestCase.java, server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java
This PR adds following changes.
- Changes in TargetPoolAllocationDecider - If shards exists in REMOTE_POOL node and shard pool changes for these shards. Decider should make sure these can no longer remain on the REMOTE_POOL nodes.
- Changed INDEX_STORE_LOCALITY_SETTING setting occurrences to IS_WARM_INDEX setting 
=> Add remote to local pool change handling in TargetPoolAllocationDecider

server/src/internalClusterTest/java/org/opensearch/index/ClusterMaxMergesAtOnceIT.java
=> Mute ClusterMaxMergesAtOnceIT

CHANGELOG.md, modules/aggs-matrix-stats/src/yamlRestTest/resources/rest-api-spec/test/stats/30_single_value_field.yml, modules/aggs-matrix-stats/src/yamlRestTest/resources/rest-api-spec/test/stats/40_multi_value_field.yml, server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java, server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java, server/src/main/java/org/opensearch/index/IndexSettings.java, server/src/main/java/org/opensearch/search/DefaultSearchContext.java, server/src/main/java/org/opensearch/search/SearchService.java, server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java, test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java, test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/pull/17978
=> [Backport 3.0] Enable concurrent_segment_search auto mode by default

server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java
On a different PR I observed this flaky test -- https://build.ci.opensearch.org/job/gradle-check/56357/testReport/junit/org.opensearch.index.query/MultiMatchQueryBuilderTests/testToQuery/
=> Fix flaky multi match query test

server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
I observed a failure in local testing due to this issue. The code previously was assuming it would observe a yellow cluster after restarting a node, but the node could restart and re-join the cluster before the assertion causing a failure. The `onNodeStopped` callback lets the test execute code before the node is restarted, so it should fix this issue.
FYI @mch2 @vinaykpud 
=> Fix race condition in SearchOnlyReplicaIT

CHANGELOG.md, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/IndexModule.java, server/src/main/java/org/opensearch/index/IndexService.java, server/src/main/java/org/opensearch/index/store/CompositeDirectory.java, server/src/main/java/org/opensearch/index/store/DefaultCompositeDirectoryFactory.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java, server/src/test/java/org/opensearch/index/store/DefaultCompositeDirectoryFactoryTests.java
Adds CompositeDirectoryFactory and makes it pluggable so that plugins can utilize this and implement their own composite directory factory.
Resolves #[[17982](https://github.com/opensearch-project/OpenSearch/issues/17982)]
=> Add composite directory factory

buildSrc/src/main/groovy/org/opensearch/gradle/test/StandaloneRestTestPlugin.groovy, buildSrc/src/main/java/org/opensearch/gradle/precommit/TestingConventionsTasks.java, buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestApiTask.java, buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestTestsTask.java, buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java, gradle/wrapper/gradle-wrapper.properties
Update to Gradle 8.14 (see please https://github.com/gradle/gradle/releases/tag/v8.14.0)
N/A 
=> Update to Gradle 8.14

CHANGELOG.md, server/src/main/java/org/opensearch/search/approximate/ApproximateMatchAllQuery.java, server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java, server/src/test/java/org/opensearch/search/approximate/ApproximateMatchAllQueryTests.java, server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/18017
Part of https://github.com/opensearch-project/OpenSearch/issues/14406
=> [Backport 3.0] Skip approximation when `track_total_hits` is set to `true`

server/src/main/java/org/opensearch/search/lookup/SearchLookup.java, server/src/test/java/org/opensearch/script/ScriptServiceTests.java
This PR includes changes to retrieve SourceLookup based on the current thread id. See https://github.com/opensearch-project/OpenSearch/issues/17743#issuecomment-2770454716 for more details.
This PR includes new test coverage on the cache case, as well as the existing scripting tests passing.
More broadly we need to invest in better perf testing related to scripting: https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/362
Relates https://github.com/opensearch-project/OpenSearch/issues/17743
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/n …
=> Create thread id to SourceLookup map

server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
Loading global ordinals is expensive. So loading up global ordinals only when **absolutely** required and ensuring that the search request does not loads up global ordinals multiple times.
Resolves https://github.com/opensearch-project/OpenSearch/issues/17979
=> [Bug-fix] Fix redundant loading of global ordinals

distribution/packages/src/common/systemd/opensearch.service
Adds /dev/shm/perfomanceanalyzer to ReadWritePaths in systemd unit file.
- https://github.com/opensearch-project/OpenSearch/issues/18083#issuecomment-2836324239
=> Add shared memory access

qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Disable the testSystemCallFilter test for now (Pending fix)
- https://github.com/opensearch-project/OpenSearch/issues/18083#issuecomment-2836097605
=> Remove testSystemCallFilter temporarily

distribution/packages/src/common/systemd/opensearch.service
Fix systemd configs in main
- Closes https://github.com/opensearch-project/OpenSearch/issues/18083#
=> Fix systemd configs in main

CHANGELOG.md, libs/core/src/main/java/org/opensearch/OpenSearchException.java, server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java, server/src/main/java/org/opensearch/action/support/TransportActions.java, server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
This reverts commit eba12faff9a84cc15b083c77e9ecda5f939787f6 from PR #17370
I was able to get a mostly reliable reproduction with the following command:
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.recovery.RecoveryWhileUnderLoadIT" -Dtests.method='testRecoverWhileUnderLoadAllocateReplicasRelocatePrimariesTest' -Dtests.iters=20 -Dtests.seed=C5861E9C93984071 --rerun
```
Using `git bisect` I was able to find this commit as the culprit to the recent flakiness in RecoveryWhileUnderLoadIT.
FYI @msfroh @kkewwei 
Resolves #14509 …
=> Revert "Avoid invalid retries on multiple replicas when querying"

plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
I believe the test tear down is racing with the thread leak detector because the `shutdown()` method does not actually wait for all the threads to stop. The fix here is to use `ThreadPool::terminate` which does the proper shutdown and ensures are threads are stopped before returning from the tearDown method.
Resolves #17551
=> Gracefully tear down S3BlobContainerRetriesTests

distribution/packages/src/common/systemd/opensearch.service
Add syscalls for merge operation error
Resolves https://github.com/opensearch-project/OpenSearch/issues/18083
```
[2025-04-29T18:29:29,191][WARN ][o.o.i.c.IndicesClusterStateService] [node_name_9200] [security-auditlog-2025.04.29][0] marking and sending shard failed due to [shard failure, reason [merge failed]]
org.apache.lucene.index.MergePolicy$MergeException: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
```
=> Add syscalls for merge operation error

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
I believe it's a mistake to assume that an operation will take more than zero milliseconds. We don't necessarily know the resolution of the clocks on the test machines, and a sufficently fast download in the test environment can be truncated to zero millis.
I've observed this failure in my local testing (see #18108) and it's easy to reproduce, but I haven't observed it fail in CI.
=> Fix assertion in RemoteStatePublicationIT

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java, server/src/main/java/org/opensearch/cluster/routing/allocation/ExistingShardsAllocator.java, server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java, server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationServiceTests.java, server/src/test/java/org/opensearch/index/SearchSlowLogTests.java
Enabled Async Shard Batch Fetch by default
- Updated default values for `primary_allocator_timeout` and `replica_allocator_timeout` to 20s.
Resolves #17713
Known issues - https://github.com/opensearch-project/OpenSearch/issues/18098
=> Enabled Async Shard Batch Fetch by default

qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Adds systemd tests to check if seccomp is enabled and reboot call is blocked
=> Add Seccomp and Reboot call tests

server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java, server/src/test/java/org/opensearch/index/remote/RemoteStoreCustomMetadataResolverTests.java
1. The default value for `cluster.remote_store.index.path.type` has been changed from `FIXED` to `HASHED_PREFIX`. This setting determines the path type used for data stored in the remote store. The `HASHED_PREFIX` option provides better distribution of keys and has been known to scale better with growing data size.
2. The default value for `shard_path_type` has been changed from `FIXED` to `HASHED_PREFIX`. This setting determines the path type used for shard files in the blob store repository. Similar to the remote store settings, the `HASHED_PREFIX` option provides better distribution of shard files.
These changes are intended to improve the default performance and reliability of remote store and snapshot functionality in OpenSearch.
Let me know if you would like me to modify or expand …
=> Make HASHED_PREFIX as the default path type for remote store and snapshot

server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
This commit reduces the runtime of the test from over 6 minutes to about 10 seconds. The current code attempts to do a flush after a node has dropped, resulting in waiting on the [replication timeout][1] of 1 minute. The change here is to ensure the flush happens before any nodes are stopped.
[1]: https://github.com/opensearch-project/OpenSearch/blob/7977446398fda5d553f39e2db32a395e917b9c78/server/src/main/java/org/opensearch/action/support/replication/ReplicationRequest.java#L64
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …
=> Reduce runtime of PitMultiNodeIT by 6 minutes

CHANGELOG.md, server/src/main/java/org/opensearch/action/explain/TransportExplainAction.java, server/src/main/java/org/opensearch/index/query/QueryCoordinatorContext.java, server/src/main/java/org/opensearch/search/SearchService.java, server/src/test/java/org/opensearch/index/query/QueryCoordinatorContextTests.java
Add target indices info to the QueryCoordinatorContext. 
This is needed to support a new feature in neural plugin: [#[1211]](https://github.com/opensearch-project/neural-search/issues/1211)
In the new feature when we rewrite the query on coordinator node we need to know the target indices to decide how to do the rewrite based on the index configuration.
=> Allow to get the search request from the QueryCoordinatorContext

server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
Previously if the delete call failed then the test would block indefinitely on the latch as nothing would count it down. The test would then hit the overall timeout and report thread leak failures. This change captures the exception and fails immediately in the test thread if the delete call fails.
I'm not totally sure this is where the test is occasionally failing, but here is a case where the overall test timeout was reached: https://github.com/opensearch-project/OpenSearch/issues/14312#issuecomment-2843139457 …
=> Fail fast if initial delete call fails in CreateIndexIT

server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java
This is a new test that is pretty flaky. Muting it now while the feature is still under development.
@gbbafna @skumawat2025 Please take a look. If there's a quick fix we can discard this PR, but otherwise I'd prefer to merge this in the meantime to stabilize the tests.
Related to #18157
=> Mute WarmIndexSegmentReplicationIT

server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/ShardsLimitAllocationDeciderRemoteStoreEnabledIT.java
This integration test was recently added in #17295. Multiple test cases are now flaky (see #17931). @linuxpi @pandeydivyansh1803 Please take a look. If there's a quick fix we can discard this PR, but otherwise I'd prefer to merge this in the meantime to stabilize the tests.
=> Mute ShardsLimitAllocationDeciderRemoteStoreEnabledIT

release-notes/opensearch.release-notes-3.0.0.md
Adding new permission for _cat/shard action to 3.0 release notes.
https://github.com/opensearch-project/OpenSearch/pull/17203
=> Adding new permission for _cat/shard action to 3.0 release notes.

CHANGELOG.md, libs/core/src/main/java/org/opensearch/ExceptionsHelper.java, rest-api-spec/src/main/resources/rest-api-spec/test/search/30_limits.yml, server/src/test/java/org/opensearch/ExceptionsHelperTests.java
The Jackson [InputCoercionException](https://fasterxml.github.io/jackson-core/javadoc/2.11/com/fasterxml/jackson/core/exc/InputCoercionException.html) is thrown for a "valid but incompatible input value"
> Exception type for read-side problems that are not direct decoding ("parsing") problems (those would be reported as [JsonParseException](https://fasterxml.github.io/jackson-core/javadoc/2.11/com/fasterxml/jackson/core/JsonParseException.html)s), but rather result from failed attempts to convert specific Java value out of valid but incompatible input value. One example is numeric coercions where target number type's range does not allow mapping of too large/too small input value.
As an exception caused by user input, a 400 (Bad Request) REST status is appropriate.  Currently parsing …
=> Use Bad Request status for InputCoercionException

server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
=> Fix flaky RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop

qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Fix test that checks if Seccomp is enabled
```
Suite: Test class org.opensearch.systemdinteg.SystemdIntegTests
2> May 01, 2025 9:36:29 PM org.apache.lucene.internal.vectorization.VectorizationProvider lookup
2> WARNING: C2 compiler is disabled; Java vector incubator API can't be enabled
2> java.lang.AssertionError: Seccomp should be enabled
at __randomizedtesting.SeedInfo.seed([69E4FBFD7BE9AE21:3DC557472D5D715]:0)
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.opensearch.systemdinteg.SystemdIntegTests.testSeccompEnabled(SystemdIntegTests.java:141)
2> NOTE: reproduce with: gradlew test --tests SystemdIntegTests.testSeccompEnabled -Dtests.seed=69E4FBFD7BE9AE21 -Dtests.locale=vun-Latn-TZ …
```
=> Fix systemd seccomp test

CHANGELOG.md, server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
This logging message is relevant to experimental feature that is not yet turned on by default. When this code runs in production then this logging message is confusing OPS because there is nothing they can do to address this WARN level message.
Resolves #18137 …
=> Change single shard assignment log message from warn to debug

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search/50_multi_match.yml, server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java, server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
Adds a check for a null value before getting text on a field name, which would otherwise throw an `IllegalStateException`.  This results in a (useful) Parsing exception and 400 rest status describing the error, rather than a 500 error.
Fixes  #18131 (together with #18161) …
=> Null check field names in QueryStringQueryBuilder

CHANGELOG.md, buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java, distribution/archives/integ-test-zip/src/test/resources/plugin-security.policy, libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/Agent.java, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/FileInterceptorIntegTests.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/FileInterceptorNegativeIntegTests.java, qa/logging-config/src/test/resources/plugin-security.policy, qa/unconfigured-node-name/src/test/resources/plugin-security.policy
Increased the scope o File Interceptor to intercept methods from FileSystemProvider.class and modified the i conditions to catch args baded on theit class types
=> Increased the scope of File Interceptor to intercept methods from FileSystemProvider.class

plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java, plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaUtils.java
A few pull-based ingestion IT tests are marked flaky. Majority of these are due to timeout errors creating Kafka topic. Though unable to reproduce any of these in local at this time, this PR increases the wait time for topic creation. Also adds a check in pause/resume API call to make sure pause/resume is complete before proceeding. This PR will be merged and observe for further reported flaky tests, if any.
Resolves #17693
=> Fix flaky pull-based ingestion tests

CHANGELOG.md, libs/core/src/main/java/org/opensearch/ExceptionsHelper.java, rest-api-spec/src/main/resources/rest-api-spec/test/search/30_limits.yml, server/src/test/java/org/opensearch/ExceptionsHelperTests.java
Backport 4ce638c06fe5a937bee30321f3c609927089de16 from #18161
=> [Backport 2.19] Use Bad Request status for InputCoercionException (#18161)

CHANGELOG.md, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
I don't have a great answer for how to implement a test here. I don't think there is a way to get the current code to produce a snapshot metadata entry that does not have this `remote_store_index_shallow_copy` field. It seems like we're missing some more comprehensive backward compatibility testing for snapshots.
Resolves #18187
=> Avoid NPE if on SnapshotInfo if 'shallow' boolean not present

plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/18193 to `2.19`
=> [Backport] [2.19] Fixing Flaky ReactorNetty4StreamingStressIT test case (another attempt) (#18193)

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search/50_multi_match.yml, server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java, server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
Backport 379e4643fe13740f6ef7075de98de53fe05902c8 from #18194
=> [Backport 2.19] Null check field names in QueryStringQueryBuilder (#18194)

client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
After enabling the concurrent segment search by default, the variance result from matrix stats starts to flaky around the asserting value a little bit which seems coming from precision loss of float data. 
The parallel search and randomness of segment layout are considered to be the cause of this flaky.
A quick look into how variance is calculated and a conversation with AI say "floating-point arithmetic not being perfectly associative", (A + B) + (C + D) `slices group` may not be same as A + B + C + D `default sequential segment`. Seem reasonable to me.
Tolerance is choosed based on the failed tests. Mismatch happens at the last digit
0.0000000000002
So choose
0.000000000001 to be the tolerance.
Resolves #18129 
By submitting this pull request, I confirm that my contribution is made …
=> Add tolerance for matrix stats agg variance value assertion

libs/common/src/main/java/org/opensearch/common/recycler/Recyclers.java, modules/lang-expression/src/main/java/org/opensearch/script/expression/PerThreadReplaceableConstDoubleValueSource.java, server/src/main/java/org/opensearch/monitor/jvm/HotThreads.java, server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfiler.java, server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java, server/src/main/java/org/opensearch/threadpool/TaskAwareRunnable.java, server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java, server/src/test/java/org/opensearch/tasks/TaskResourceTrackingServiceTests.java
Replaces deprecated usages of `Thread::getId()` with `Thread::threadId()` introduced in Java 19. This change ensures compatibility with newer Java versions and eliminates deprecation warnings. The updates are scoped to actual `Thread` usage and do not affect domain-specific `getId()` calls on objects like `Task`, `Node`, etc.
Resolves #18205
=> Replaced Thread::getId() with Thread::threadId()

MAINTAINERS.md
Following the [nomination process][1], I have nominated and other maintainers have agreed to add Yupeng Fu (@yupeng9) as a co-maintainer of the OpenSearch repository. Yupeng has kindly accepted the invitation.
---
Yupeng has been an active contributor to OpenSearch, most notably spearheading the introduction of pull-based ingestion into the 3.0 release. Overall, he has [authored 9 issues](https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aissue%20author%3Ayupeng9%20), [merged 10 PRs](https://github.com/opensearch-project/OpenSearch/issues?q=state%3Aclosed%20is%3Apr%20author%3Ayupeng9), and [provided feedback on 23 PRs](https://github.com/opensearch-project/OpenSearch/issues?q=%20is%3Apr%20commenter%3Ayupeng9%20).
For the pull-based ingestion feature, Yupeng created the initial …
=> Add @yupeng9 as a maintainer

server/src/main/java/org/opensearch/action/ActionModule.java, server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java
Unregister rest and transport action handlers for HotToWarmTIering. We will add later when features complete implementation in finalised. 
=> Unregister rest and transport action handlers for HotToWarmTiering

server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java, server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
~Fix `SimpleSearchIT.doTestSimpleTerminateAfterTrackTotalHitsUpTo` flaky test, coming from https://github.com/opensearch-project/OpenSearch/issues/16851#issuecomment-2860630841 rather than updating the approximation code with `+1` to get the `relation": "gte"`, this PR is an attempt to fix the test with approximation behavior on long fields.~
Falling back to `+1` based on analysis part of https://github.com/opensearch-project/OpenSearch/issues/16851#issuecomment-2861649436
Coming from the PR https://github.com/opensearch-project/OpenSearch/pull/18018 `+1` is added and which was removed in this PR https://github.com/opensearch-project/OpenSearch/pull/18189 to honor the approximation behavior. 
Coming from https://github.com/opensearch-project/OpenSearch/issues/16851#issuecomment-2860612257 …
=> Fix `SimpleSearchIT.doTestSimpleTerminateAfterTrackTotalHitsUpTo` flaky test 

server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
The [default](https://github.com/opensearch-project/OpenSearch/blob/cc875c6f8cc966538945687662bf1a6334c5cb44/server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java#L85) ctor for ShardRouting has currentNodeId before relocatingNodeId.  A new ctor to add support for the search only flag was added with this order swapped.  There is no actual bug surfaced because it then passes the relocating as the current. Further there is only one caller of this ctor [here](https://github.com/opensearch-project/OpenSearch/blob/cc875c6f8cc966538945687662bf1a6334c5cb44/server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java#L670), that passes the current as the relocated... anyway this cleans it up.
N/A
By submitting this pull request, I confirm that my contribution is made under …
=> Fix incorrect constructor param ordering in ShardRouting

server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java, server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java, server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTestCase.java
Expose method for getting reference count of entry in FileCache 
Resolves #[18258](https://github.com/opensearch-project/OpenSearch/issues/18258)
=> Expose method for getting reference count of entry in FileCache 

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
The Default aws client might create its own ScheduledExecutorService which is closed via ExecutorService.shutdown() when the client is closed. Calling shutdown might not ensure that all threads are gone when ThreadLeakControl is ran.
Provide our own ScheduledExecutorService during this test so that it runs thrown our tearDown method which calls ThreadPool#terminate waiting for 5 seconds.
Seen in build https://build.ci.opensearch.org/job/gradle-check/57676/:
```
2> May 05, 2025 12:38:10 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
2> WARNING: Will linger awaiting termination of 2 leaked thread(s).
2> May 05, 2025 12:38:16 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
2> SEVERE: 1 thread leaked from SUITE scope at …
```
=> Attempt to fix ThreadLeakControl issues in S3BlobContainerRetriesTests

server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
Add polling to test case that can briefly return non-zero PIT stats when a PIT request is rejected.
I could manually force the race condition to happen by adding a sleep for a couple seconds here: https://github.com/opensearch-project/OpenSearch/blob/f2cc3d8ea314b2d49a8b6ea5f57de5b6aff4faf9/server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java#L189
I validated this fix causes the test to pass reliably even with the sleep injected.
Resolves #14525 …
=> Fix flaky failures in PitMultiNodeIT

.github/workflows/gradle-check.yml
Today for a post merge action the running gradle check CI runs are terminated with the concurrency setting. 
Here is an example https://github.com/opensearch-project/OpenSearch/actions/runs/14934871450/job/41959850100 where the operation was cancelled by the Github. This can happen when a new PR is merged while for the previous PR post merge run is still running. I assume this is because `${{ github.event.pull_request.number }}` shows null for a post merge actions.
But notice this dint actually stop the triggered Jenkins job https://build.ci.opensearch.org/job/gradle-check/57901/. This concurrency setting only terminates at the Github level.
Today for Jenkins this is already handled (https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/gradle/gradle-check.jenkinsfile#L1 …
=> Update concurrency setting for gradle check to exclude cancellation of the post_merge runs

plugins/repository-azure/src/internalClusterTest/java/org/opensearch/repositories/azure/AzureBlobStoreRepositoryTests.java, plugins/repository-gcs/src/internalClusterTest/java/org/opensearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java, plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java, test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchMockAPIBasedRepositoryIntegTestCase.java
I run test with `tests.seed=9D496123288AF73F` in `S3BlobStoreRepositoryTests. testSnapshotAndRestore `, and find that every request will retry 3 times, and `sleep` with `backoff policy`, it will cost too much time, which will lead to flaky tests.
```
[2025-05-14T16:15:21,549][DEBUG][s.a.a.request            ] [node_t0] Retryable error detected. Will retry in 52ms. Request attempt number 1
......
[2025-05-14T16:15:21,647][DEBUG][s.a.a.request            ] [node_t0] Retryable error detected. Will retry in 145ms. Request attempt number 2
```
Request is as follows:
`GET /bucket?list-type=2&delimiter=%2F&prefix=index-`
`PUT /bucket/r10011100011010/indices/Hfd8LcIaQmu_nAtfzC7YJg/5/__Qf9SKHinSJWqsxDYO2Qrpw`
Resolves #14291 #14299 #11493 …
=> Fix flaky tests in GoogleCloudStorageBlobStoreRepositoryTests, S3BlobStoreRepositoryTests, AzureBlobStoreRepositoryTests

CHANGELOG.md, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/KafkaIngestionBaseIT.java, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java, server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java, server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionState.java, server/src/main/java/org/opensearch/index/IndexService.java, server/src/main/java/org/opensearch/index/engine/EngineConfig.java, server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/index/shard/IndexShard.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/GetIngestionStateResponseTests.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionStateTests.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportGetIngestionStateActionTests.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportUpdateIngestionStateActionTests.java, server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java, server/src/test/java/org/opensearch/index/engine/IngestionEngineTests.java, server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java, test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java, test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
This PR adds support for cluster write blocks in pull-based ingestion flow. The stream poller is enhanced to listen to cluster state changes and the poller is paused when a write block is active, and resumed when the write block is removed. 
GetIngestionState API is also enhanced to reflect the write block status of the poller.
Resolves #18279
=> [Pull-based Ingestion] Support cluster write blocks

server/src/main/java/org/opensearch/index/store/CompositeDirectory.java, server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
In composite directory for deleteFile method, we currently throw a NoSuchFileException if the file is not found in the directory.
In this PR we are adding a modification that instead of throwing a NoSuchFileException we simply fail silently.
This is needed because we can run into scenarios where stale files are evicted locally (zero refCount in FileCache) and not present in remote as well (due to metadata refresh). In such scenarios listAll() of composite directory will not show the file and operations such as refresh/merge where we calling this deleteFile method will fail. …
=> Composite Directory - silently fail instead of throwing error for non-existent file in deleteFile() call

server/src/test/java/org/opensearch/search/SearchServiceTests.java
Previously the default value was false, it had nothing to do with aggregation. Now default value is auto in case mode setting is not set, it is also decided by aggregationSupportsConcurrent, We should take aggregationSupportsConcurrent into account.
Resolves #18238
=> [Flaky Test] Fix Flaky SearchServiceTests.testConcurrentSegmentSearchWithRandomizedModeSettings

CHANGELOG.md, distribution/packages/src/common/systemd/opensearch.service
Adds `seccomp` in SystemCallFilter in opensearch.service systemd unit file.
- https://github.com/opensearch-project/OpenSearch/issues/18273
=> Add seccomp in systemd config

CHANGELOG.md, gradle/libs.versions.toml, modules/ingest-geoip/build.gradle, modules/lang-painless/build.gradle
This PR continues to convert more modules to using the gradle version catalog. Its important to have references to libraries in the version catalog because then dependabot can monitor for version updates.
=> Switch ingest-geoip and lang-painless modules to use the gradle version catalog

CHANGELOG.md, server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Backports c32262dce18edd850793a753b3fda894eec23ee0 from #18218 to `2.19`
=> [Backport 2.19] Avoid NPE if on SnapshotInfo if 'shallow' boolean not present (#18218)

server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java
There was a race condition in testResizeQueueDown() where depending on
random parameters we could submit up to 1002 tasks into an executor with
a queue size of 900. That introduced a race condition where if the tasks
didn't execute fast enough then a rejected execution exception could
happen and fail the test. The fix is to resize down to a queue size of
1500 to ensure there is enough capacity even if all tasks are submitted
before any can be executed.
And finally I refactored the tests to reduce duplication of code and
ensure the executor gets shutdown properly even in case of a test
failure. This will avoid the spurious thread leak failure if a test case
exits because of a failure.
Resolves #14297 …
=> Fix QueueResizableOpenSearchThreadPoolExecutorTests

server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteSplitIndexIT.java
`testCreateSplitIndex`
The test creates split indices and tests whether:
- Documents can be correctly split from a source index into indices with more shards (e.g., 2->4->8 shards)
- All documents remain searchable and retrievable after splits
- New writes to the split indices work properly
- The split operation maintains data consistency across source and target indices while using remote storage
Based on the failure logs from recent PR builds ([examples]
[https://build.ci.opensearch.org/job/gradle-check/54304/testReport/junit/org.opensearch.action.admin.indices.create/RemoteSplitIndexIT/testCreateSplitIndex/](url)
, we can see that the test used to fail occasionally with
java.lang.AssertionError: expected:<0> but was:<103>
at __randomizedtesting.SeedInfo.seed([93C08AFB8B2D718E:EB805C4187 …
=> Fix Flaky RemoteSplitIndexIT (#15107)

CHANGELOG.md, plugins/mapper-annotated-text/src/test/java/org/opensearch/search/fetch/subphase/highlight/AnnotatedTextHighlighterTests.java, rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/10_unified.yml, server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java, server/src/main/java/org/opensearch/lucene/search/uhighlight/CustomFieldHighlighter.java, server/src/main/java/org/opensearch/lucene/search/uhighlight/CustomUnifiedHighlighter.java, server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java, server/src/test/java/org/opensearch/lucene/search/uhighlight/CustomUnifiedHighlighterTests.java
This option was silently ignored when running the unified highlighter. Since lucene 10 it is now possible to pass a list of additional fields to fetch matches from and blend into the snippets.
Resolves #18164 
=> Add support for matched_fields with the unified highlighter

plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
Similar to #18201 but applied via the TestPlugin used in S3BlobStoreRepositoryTests.
Resolves #14299
=> Attempt to fix ThreadLeakControl issues in S3BlobStoreRepositoryTests

.github/benchmark-configs.json
Coming from https://github.com/opensearch-project/OpenSearch/issues/18341 and https://github.com/opensearch-project/OpenSearch/issues/18313#issuecomment-2887636353, we should have an ability to test the search performance against `http_logs` dataset.
Part of https://github.com/opensearch-project/OpenSearch/issues/18341 and https://github.com/opensearch-project/OpenSearch/issues/18313#issuecomment-2887636353
=> Add `http_logs` search only test procedure

test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
This assertion is failing in #18071. I can't reproduce it but improving the message on failure may help debug it.
Related #18071
=> Improve failure message in AbstractSimpleTransportTestCase

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/SearchPhase.java, server/src/main/java/org/opensearch/action/search/SearchRequestStats.java, server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java, server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerTests.java, server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java, server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/16781 to 2.19.x. 
https://github.com/opensearch-project/OpenSearch/issues/16750
- [N/A] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [N/A] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.
=> [Backport 2.19] [Bugfix] Fix IllegalArgumentException thrown when creating a PIT

CHANGELOG.md, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/S3AsyncDeleteHelper.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java, plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/utils/SseKmsUtil.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java, plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
This PR makes 3 main changes
As of January 5, 2023, S3 now applies SSE-S3 as the base level of encryption (the `AES256` encryption type), and there is no way to disable this. This means regardless of whether or not this setting is set or whatever value the setting is set to, it makes no difference in how objects are uploaded to S3. 
For more details, see: https://docs.aws.amazon.com/AmazonS3/latest/userguide/serv-side-encryption.html
Fortunately, repository settings are fully backwards compatible ever after being removed, which means that even after removing the setting, I can still register a repository like so:
```
curl -XPUT "http://localhost:9200/_snapshot/vector-repo" -H 'Content-Type: application/json' -d'                                            
{
"type": "s3",
"settings": { …
```
=> Add support for SSE-KMS and bucket owner verification

server/src/test/java/org/opensearch/index/IndexServiceTests.java, test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
As far as I can tell these test cases have never been working as intended. They appear to have been created as a copy-paste error from `testIllegalFsyncInterval`. They passed because the createIndex call was failing due to setting the translog sync interval to an invalid value, which is what the try-catch was expecting. After removing the invalid setting the tests did not work properly for multiple reasons. I believe I have fixed the tests back to the original intent.
The reason for digging into this test was to remove the deprecated `createIndex` calls from OpenSearchSingleNodeTestCase which take the now removed type parameter. I will follow up with a separate PR to do that work, as this was a significant enough change to stand on its own.
Related to #10045 …
=> Fix IndexServiceTests sort field test cases

server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
This change will make sure that the MetricAggregatorTests does not fail on the range query. What happened was that in the test, the range query was applied on a terms, but the difference between the expected aggregation and the actual aggregation was not zero. On a field called "keyword_field", the boolean query had 2 should queries (range from 18 to 0) and (exact match of 37). 
In the expected aggregation, only the documents which matched on 37 were added together, but in the actual aggregation, more documents which somehow satisfied the range from 18 to 0 were added together. I think what happened was that the "keyword_field" was a string value, and in the range query, the values are interpreted as mapped ordinals in the star tree filters …
=> Flaky MetricAggregatorTests

.github/workflows/wrapper.yml
The wrapper-validation-action has been superceded by gradle/actions/wrapper-validation.
https://github.com/gradle/wrapper-validation-action?tab=readme-ov-file
=> Replace wrapper-validation-action GitHub action

.github/benchmark-configs.json
Update `big5` (`id_4`) to test against Lucene 10.2.1
Coming from https://github.com/opensearch-project/OpenSearch/pull/17961 and to test the regression reported here https://github.com/opensearch-project/OpenSearch/issues/18313
=> Update `big5` (`id_4`) to test against Lucene 10.2.1

CHANGELOG.md, server/src/main/java/org/opensearch/index/store/CompositeDirectory.java, server/src/main/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStats.java, server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java, server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/AggregateRefCountedCacheStats.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/DefaultStatsCounter.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/FileStatsCounter.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/IRefCountedCacheStats.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/RefCountedCacheStats.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/StatsCounter.java, server/src/test/java/org/opensearch/cluster/ClusterInfoTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java, server/src/test/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDeciderTests.java, server/src/test/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStatsTests.java, server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java, server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Add changes to support pinning in FileCache
-  resolves https://github.com/opensearch-project/OpenSearch/issues/13648
- Meta Issue https://github.com/opensearch-project/OpenSearch/issues/13149
- [Y ] Functionality includes testing.
- [NA] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [NA] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable. …
=> Add changes to support pinning in FileCache

CHANGELOG.md, modules/parent-join/src/main/java/org/opensearch/join/query/ParentChildInnerHitContextBuilder.java, server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java, server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/BestDocsDeferringCollector.java, server/src/main/java/org/opensearch/search/aggregations/metrics/TopHitsAggregator.java, server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
Replace the deprecated construction method of TopScoreDocCollectorManager with the new method in Lucene 10.1.0.
Resolves https://github.com/opensearch-project/OpenSearch/issues/18394.
=> Replace the deprecated construction method of TopScoreDocCollectorManager with the new method in Lucene

rest-api-spec/src/main/resources/rest-api-spec/test/indices.simulate_index_template/10_basic.yml
- fix indices.simulate_index_template test spec
=> fix indices.simulate_index_template test spec

plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
An attempt to fix flaky ReactorNetty4StreamingStressIT (new failure mode)
Closes https://github.com/opensearch-project/OpenSearch/issues/15840
=> An attempt to fix flaky ReactorNetty4StreamingStressIT (new failure mode)

CHANGELOG.md, test/framework/src/main/java/org/opensearch/fips/FipsMode.java
This PR resolves an error seen in the security plugin here: https://github.com/opensearch-project/security/actions/runs/15408478290/job/43355642640?pr=5370
The error is really a timing issue as the security plugin has not yet converted to BCFIPS jars because of [incompatibility with OpenSAML](https://github.com/opensearch-project/security/issues/4915) which is a library used for SAML authentication. 
The existing check has a catch block for NoSuchClassDef, but in the case of the security plugin the class exists, but the method does not.
Resolves https://github.com/opensearch-project/security/actions/runs/15408478290/job/43355642640?pr=5370 …
=> Update FipsMode check to catch NoSuchMethodError

server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregator.java, server/src/test/java/org/opensearch/search/aggregations/startree/KeywordTermsAggregatorTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/NumericTermsAggregatorTests.java
**TLDR**: DFS flow in keyword terms was returing empty buckets, this PR fixes the flow for DFS case.
**Detailed Explanation of Changes:**
The existing strategy where we fetch which bucketOrd to update:
```
long bucketOrd = collectionStrategy.globalOrdToBucketOrd(0, ord);
```
For DenseGlobalOrds (used by breadth-first flow) implementation: would return the bucket in for correctly
```
@Override
long globalOrdToBucketOrd(long owningBucketOrd, long globalOrd) {
assert owningBucketOrd == 0;
return globalOrd;
}
```
For RemapGlobalOrds (used by depth-first flow) implementation: was returning `-1` when it was trying to find a bucket, and hence bucket was not getting initialized properly with correct values.
```
@Override
long globalOrdToBucketOrd(long owningBucketOrd, long globalOrd) {
return …
```
=> Support/fix for star-tree keyword aggregation dfs mode

.github/benchmark-configs.json
Add `nyc_taxis` search only test-procedure to test with Lucene 10.2.1
This is to test the `nyc_taxis` dataset query improvements on PR https://github.com/opensearch-project/OpenSearch/pull/18439.
=> Add `nyc_taxis` search only test-procedure to test with Lucene 10.2.1

CHANGELOG.md, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/autotagging/Rule.java, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/storage/DefaultAttributeValueStore.java, modules/autotagging-commons/common/src/test/java/org/opensearch/rule/action/GetRuleRequestTests.java, modules/autotagging-commons/common/src/test/java/org/opensearch/rule/action/GetRuleResponseTests.java, modules/autotagging-commons/common/src/test/java/org/opensearch/rule/autotagging/RuleTests.java, modules/autotagging-commons/common/src/test/java/org/opensearch/rule/utils/RuleTestUtils.java, modules/autotagging-commons/src/main/java/org/opensearch/rule/InMemoryRuleProcessingService.java, modules/autotagging-commons/src/test/java/org/opensearch/rule/InMemoryRuleProcessingServiceTests.java, plugins/workload-management/build.gradle, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/WorkloadManagementPlugin.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/RefreshBasedSyncMechanism.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/detect/AddRuleEvent.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/detect/DeleteRuleEvent.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/detect/RuleEvent.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/detect/RuleEventClassifier.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/detect/UpdateRuleEvent.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/detect/package-info.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/package-info.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/AutoTaggingActionFilterTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/WorkloadManagementPluginTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/rule/sync/RefreshBasedSyncMechanismTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/rule/sync/detect/RuleEventClassifierTests.java
This change adds a periodically running thread to refresh the current in-memory `Rule`s view from `RULES` system index.
https://github.com/opensearch-project/OpenSearch/issues/16797#issuecomment-2594284060%3E
https://github.com/opensearch-project/OpenSearch/issues/13341
=> [Rule based auto-tagging] add rule sync service

libs/agent-sm/agent/build.gradle
Re-submitting #18429 with a proper branch
Since there's no way to remove an `AgentPolicy` once it set, the only way to avoid conflicts described in #18428 is to fork a new JVM per test
Resolves #18428
=> Execute `:libs:opensearch-agent-sm:agent` tests in separate JVMs

plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/FlightService.java, plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/FlightStreamPlugin.java, plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/ServerComponents.java, plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/FlightStreamPluginTests.java, plugins/transport-grpc/src/internalClusterTest/java/org/opensearch/plugin/transport/grpc/GrpcTransportBaseIT.java, plugins/transport-grpc/src/internalClusterTest/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransportIT.java, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/GrpcPlugin.java, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/Netty4GrpcServerTransport.java, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransport.java, plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/GrpcPluginTests.java, plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/ssl/SecureSettingsHelpers.java, server/src/main/java/org/opensearch/bootstrap/Security.java, server/src/main/java/org/opensearch/common/network/NetworkModule.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/NetworkPlugin.java, server/src/main/java/org/opensearch/plugins/SecureAuxTransportSettingsProvider.java, server/src/main/java/org/opensearch/transport/AuxTransport.java
Adds a few changes with the goal of making AuxTransport settings more easily configured/extended.
- Moves `AuxTransport` out of `NetworkPlugin` into `org.opensearch.transport.AuxTransport`.
Minor refactor. All other transport base classes are in this package and AuxTransport a bit out of place in `NetworkPlugin`.
- Adds a `settingKey` accessor to AuxTransport.
Forward looking change for plugins which want to identify the namespace of AuxTransports.
(https://github.com/opensearch-project/security/pull/5375)
- Bugfix for `FlightStreamPlugin` which registers the `FlightService` AuxTransport under key `aux.transport.types`.
Moved this to `experimental-transport-arrow-flight-rpc` which users will need to include under `aux.transport.types` setting to enable this transport.
N/A
By submitting …
=> Standardize setting key for aux transports

server/src/main/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDecider.java, server/src/test/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDeciderTests.java
Minor fixes in WarmDiskThresholdDecider
=> Minor fixes in WarmDiskThresholdDecider

CHANGELOG.md, server/src/main/java/org/opensearch/index/query/RangeQueryBuilder.java, server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java, server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java, server/src/main/java/org/opensearch/search/startree/StarTreeTraversalUtil.java, server/src/main/java/org/opensearch/search/startree/filter/DimensionFilter.java, server/src/main/java/org/opensearch/search/startree/filter/DimensionFilterMergerUtils.java, server/src/main/java/org/opensearch/search/startree/filter/ExactMatchDimFilter.java, server/src/main/java/org/opensearch/search/startree/filter/MatchAllFilter.java, server/src/main/java/org/opensearch/search/startree/filter/MatchNoneFilter.java, server/src/main/java/org/opensearch/search/startree/filter/RangeMatchDimFilter.java, server/src/main/java/org/opensearch/search/startree/filter/StarTreeFilter.java, server/src/main/java/org/opensearch/search/startree/filter/provider/BoolStarTreeFilterProvider.java, server/src/main/java/org/opensearch/search/startree/filter/provider/DimensionFilterMapper.java, server/src/main/java/org/opensearch/search/startree/filter/provider/StarDateFieldMapper.java, server/src/main/java/org/opensearch/search/startree/filter/provider/StarTreeFilterProvider.java, server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeSearchTests.java, server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/BoolStarTreeFilterProviderTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/DateHistogramAggregatorTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/DateRangeQueryTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterAndMapperTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterMergerUtilsTests.java, server/src/test/java/org/opensearch/search/aggregations/startree/RangeAggregatorTests.java
In existing aggregations supported by star-tree, this PR adds support for date range query to be used with supported aggregations. The query will be converted to a DimensionFilter and will be handled as part of star-tree traversal logic.
Resolves #17443
=> [Star Tree] [Search] Support of Date Range Queries in Aggregations

plugins/arrow-flight-rpc/README.md, plugins/arrow-flight-rpc/src/internalClusterTest/java/org/opensearch/arrow/flight/ArrowFlightServerIT.java, plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/FlightStreamPlugin.java, plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/FlightStreamPluginTests.java
`arrow-flight-rpc` plugin provides the `FlightService` through both `createComponent` as well as `getAuxTransports`. These two instances collide when Node.java dependency injection framework binds them both to `FlightService.class`.
Removing the `createComponent` instance to resolve this conflict. `createComponent` does not respect aux transport enable settings or port range settings.
Error:
```
»  uncaught exception in thread [main]
»  org.opensearch.common.inject.CreationException: Guice creation errors:
»
»  1) A binding to org.opensearch.arrow.flight.bootstrap.FlightService was already configured at _unknown_.
»    at _unknown_
»
»  1 error
»       at <<<guice>>>
»       at org.opensearch.node.Node.<init>(Node.java:1591)
»       at org.opensearch.node.Node.<init>(Node.java:464)
» …
```
=> Bugfix arrow-flight-rpc plugin dependency injection collision

CHANGELOG.md, TESTING.md, gradle/code-coverage.gradle
- Ability to run code coverage locally.
- Run code coverage for integrationTest, test and javaRestTest (coming from this https://github.com/opensearch-project/OpenSearch/pull/18376 looks like javaRestTest is not added)
- Run for specific Gradle module.
- Run for specific test class and method.
While I'm working on this PR https://github.com/opensearch-project/OpenSearch/pull/18358, I noticed that GitHub reports code coverage only after the Gradle Check workflow passes. Being able to run coverage reports locally using Gradle can help test and improve coverage earlier in the development cycle. Although IntelliJ provides some insights, using Gradle with the JaCoCo plugin ensures consistency with the coverage reported by GitHub.
By submitting this pull request, I confirm that my contribution …
=> Ability to run Code Coverage locally with Gradle

DEVELOPER_GUIDE.md, gradle/libs.versions.toml, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/Agent.java, libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SubjectInterceptor.java, libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SubjectTests.java, plugins/repository-hdfs/build.gradle, server/src/main/resources/org/opensearch/bootstrap/security.policy
Update bundled JDK to JDK-24
Blockers so far:
- https://issues.apache.org/jira/browse/HADOOP-19486
Closes https://github.com/opensearch-project/OpenSearch/issues/17661
=> Update bundled JDK to JDK-24

plugins/transport-grpc/README.md
Document how the GRPC settings should be used and add the missing `grpc.netty.max_msg_size` setting to the README. 
A corresponding PR in the documentation-webste repo will be created later on as well to reflect these changes. 
https://github.com/opensearch-project/OpenSearch/issues/16787
=> Document GRPC settings and default values in README

server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java, server/src/internalClusterTest/java/org/opensearch/remotestore/WritableWarmIT.java, server/src/main/java/org/opensearch/common/cache/RemovalReason.java, server/src/main/java/org/opensearch/env/NodeEnvironment.java, server/src/main/java/org/opensearch/env/NodeRepurposeCommand.java, server/src/main/java/org/opensearch/index/store/CompositeDirectory.java, server/src/main/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStats.java, server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java, server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java, server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java, server/src/main/java/org/opensearch/index/store/remote/utils/FileTypeUtils.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java, server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java, server/src/main/java/org/opensearch/node/Node.java, server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java, server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java, server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java, test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
This PR:
- Implements local file scanning to warm up fileCache during node startup, reducing remote store downloads
- Logic to cleans up index and shard paths during warm index deletion. Reference [PR](https://github.com/opensearch-project/OpenSearch/pull/11443).
- Fixes flaky tests in WarmIndexSegmentReplicationIT
Resolves https://github.com/opensearch-project/OpenSearch/issues/17526, https://github.com/opensearch-project/OpenSearch/issues/18157
=> Initialize FileCache for warm index on node boot-up/restart

server/src/main/resources/org/opensearch/bootstrap/security.policy
Allow READ access to `/sys/fs/cgroup/memory.swap.current`.
See https://github.com/opensearch-project/OpenSearch/pull/18085#discussion_r2153517660
=> [ref #18085] Allow READ access to `/sys/fs/cgroup/memory.swap.current`

CHANGELOG.md, server/src/main/java/org/opensearch/plugins/DefaultSecureHttpTransportParameters.java, server/src/main/java/org/opensearch/plugins/SecureHttpTransportSettingsProvider.java, server/src/main/java/org/opensearch/plugins/SecureTransportSettingsProvider.java
Introduce `SecureHttpTransportParameters` experimental API (to complement `SecureTransportParameters` counterpart). The way we configure SSL Context in Reactor Netty 4 transport is not very clean and turned out to be fragile. By introducing  `SecureHttpTransportParameters` (similarly with  `SecureTransportParameters`), the transport could be configured in straightforward way.
Towards https://github.com/opensearch-project/OpenSearch/issues/18559
=> Introduce SecureHttpTransportParameters experimental API (to complement SecureTransportParameters counterpart)

CHANGELOG.md, libs/common/src/main/java/org/opensearch/common/CheckedRunnable.java, plugins/identity-shiro/src/main/java/org/opensearch/identity/shiro/ShiroPluginSubject.java, server/src/main/java/org/opensearch/identity/Subject.java, server/src/main/java/org/opensearch/identity/noop/NoopPluginSubject.java, server/src/test/java/org/opensearch/identity/noop/NoopPluginSubjectTests.java
Small PR to update the Subject interface to use CheckedRunnable. The return value of the Callable is never used and it propagates a generic Exception which would be cleaner to get the specific exception type instead.
A bit of cleanup to https://github.com/opensearch-project/OpenSearch/pull/14630
=> Update Subject interface to use CheckedRunnable

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreMetadataIT.java, server/src/main/java/org/opensearch/action/ActionModule.java, server/src/main/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataAction.java, server/src/main/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataRequest.java, server/src/main/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataRequestBuilder.java, server/src/main/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataResponse.java, server/src/main/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreShardMetadata.java, server/src/main/java/org/opensearch/action/admin/cluster/remotestore/metadata/TransportRemoteStoreMetadataAction.java, server/src/main/java/org/opensearch/action/admin/cluster/remotestore/metadata/package-info.java, server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java, server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java, server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java, server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java, server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRemoteStoreMetadataAction.java, server/src/main/java/org/opensearch/transport/client/ClusterAdminClient.java, server/src/main/java/org/opensearch/transport/client/support/AbstractClient.java, server/src/test/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataRequestBuilderTests.java, server/src/test/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataRequestTests.java, server/src/test/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataResponseTests.java, server/src/test/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataTestHelper.java, server/src/test/java/org/opensearch/action/admin/cluster/remotestore/metadata/RemoteStoreMetadataTests.java, server/src/test/java/org/opensearch/action/admin/cluster/remotestore/metadata/TransportRemoteStoreMetadataActionTests.java
Added Remote Store Metadata API to fetch segment and translog metadata
This PR adds a new cluster-level API that enables users to retrieve remote store metadata, including segment and translog details, for specific indices and shards. This functionality enhances observability and debugging capabilities for indices backed by remote storage.
1. Transport Layer: `TransportRemoteStoreMetadataAction`:
- Executes on the Data node.
- Collects and parses segment and translog metadata files for each shard.
- Handles shard-level errors gracefully.
2. Core Action Classes
- `RemoteStoreMetadataRequest`: Supports input parameters: index name and optional shard ID(s).
- `RemoteStoreMetadataResponse`: Contains per-shard metadata along with success/failure info
- `RemoteStoreMetadata`: Holds the parsed …
=> Created an API to fetch remote store metadata

CHANGELOG.md, client/rest-high-level/src/test/java/org/opensearch/client/RequestConvertersTests.java, modules/lang-mustache/src/internalClusterTest/java/org/opensearch/script/mustache/SearchTemplateIT.java, modules/lang-mustache/src/main/java/org/opensearch/script/mustache/RestMultiSearchTemplateAction.java, modules/lang-mustache/src/main/java/org/opensearch/script/mustache/RestSearchTemplateAction.java, modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateRequest.java, modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateRequestBuilder.java, modules/lang-mustache/src/test/java/org/opensearch/script/mustache/MultiSearchTemplateRequestTests.java, modules/lang-mustache/src/test/java/org/opensearch/script/mustache/SearchTemplateRequestXContentTests.java, modules/lang-mustache/src/test/resources/org/opensearch/script/mustache/simple-msearch-template.json, server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java
Add support for search pipeline in msearch template
```
{"index":"my-nlp-index1"}
{"id":"search_template_1","params":{"play_name":"hello","from":0,"size":1}, "search_pipeline": "my_pipeline2"}
{"index":"my-nlp-index1"}
{"id":"search_template_2","params":{"play_name":"zoo","from":0,"size":1}, "search_pipeline": "my_pipeline1"}
```
search template
```
{
"id": "search_template_2",
"params": {
"play_name": "zoo",
"from": 0,
"size": 1
},
"search_pipeline": "my_pipeline1"
}
```
Resolves https://github.com/opensearch-project/OpenSearch/issues/18508 …
=> Add support for search pipeline in search and msearch template

CHANGELOG.md, plugins/ingestion-fs/README.md, plugins/ingestion-fs/build.gradle, plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileConsumerFactory.java, plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileMessage.java, plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileOffset.java, plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FilePartitionConsumer.java, plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FilePlugin.java, plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileSourceConfig.java, plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/package-info.java, plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileBasedIngestionSingleNodeTests.java, plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileMessageTests.java, plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileOffsetTests.java
This PR introduces a new pull-based ingestion plugin, for indexing documents from the file system. More details can be found in the attached issue. This is only meant for local testing purpose, with the motivation to enable users to index documents from their local machine without having to setup Kafka or Kinesis.
Resolves #18590
=> [Pull-based Ingestion] Create ingestion-fs plugin for simpler local testing

.github/workflows/version.yml
Coming from https://github.com/opensearch-project/OpenSearch/pull/18544, an attempt to fix the workflow to continue with the version increment automation.
Since we eliminated `.x` branch, we only need 2 PR's upon tag creation, example when `3.1.0` tag is created:
- PR on 3.1 branch: [AUTO] Increment version to 3.1.1.
- PR on main branch: [AUTO] [main] Add bwc version 3.1.1.
=> Fix the version increment workflow with the branching strategy update

server/src/main/java/org/opensearch/cluster/ClusterInfo.java
Commit d404f332 has incorrect version guards which are manifesting as flaky failures in MixedClusterClientYamlTestSuiteIT.
See https://github.com/opensearch-project/OpenSearch/pull/18480#issuecomment-3005610126 for more details
Resolves #14294
=> Fix serialization failure due to wrong version

server/src/main/java/org/opensearch/ingest/IngestService.java
Fix flaky test `IngestServiceTests#testExecuteBulkRequestInBatchWithExceptionAndDropInCallback_requestsWithMatchingChildSlots`.
Related [gradle test](https://build.ci.opensearch.org/job/gradle-check/59694/testReport/junit/org.opensearch.ingest/IngestServiceTests/testExecuteBulkRequestInBatchWithExceptionAndDropInCallback_requestsWithMatchingChildSlots/).
Resolves #[[18622](https://github.com/opensearch-project/OpenSearch/issues/18622)]
=> Fix flaky test in IngestServiceTests

CHANGELOG.md, plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java, plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ssl/SslUtils.java, plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorHttpClient.java, plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportTests.java, plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ssl/SecureReactorNetty4HttpServerTransportTests.java
When an OpenSearch cluster is setup up http.type as reactor-netty-secure, the curl invocation of any endpoints fails. The reason is the client(curl) and the server try to communicate via http2. When http1.1 is forced we do not see the error, indicating the server fails to support http2 when reactor netty is enabled.
Closes https://github.com/opensearch-project/OpenSearch/issues/18559
=> [BUG] Cannot communicate with http2 when reactor-netty is enabled

CHANGELOG.md, modules/parent-join/src/main/java/org/opensearch/join/query/HasChildQueryBuilder.java, modules/parent-join/src/main/java/org/opensearch/join/query/HasParentQueryBuilder.java, modules/parent-join/src/test/java/org/opensearch/join/query/HasChildQueryBuilderTests.java, modules/parent-join/src/test/java/org/opensearch/join/query/HasParentQueryBuilderTests.java
In #13837 AND #14739 i see it fixed many scenarios queries, but we still need Join Query Builder to visit query builders. especially for neural search can visit embedding or other field
=> [BUG FIX] Fix the visit of sub queries for HasParentQuery and HasChildQuery

.github/workflows/trigger-manifest-generation.yml
Adds a workflow to immediately trigger (instead of waiting for the cronjob to schedule the workflow run) manifest generation workflow that needs OpenSearch version bump PR to be merged. Since `buildSrc/version.properties` only contains OpenSearch version, it seemed like a right trigger for this job. 
See the related issue for more details. 
https://github.com/opensearch-project/opensearch-build/issues/4225
=> Add workflow to automatically trigger manifest generation process

CHANGELOG.md, plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransport.java, plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/ssl/SecureSettingsHelpers.java, server/src/main/java/org/opensearch/plugins/SecureAuxTransportSettingsProvider.java
Similar to `SecureAuxTransportSettingsProvider::buildSecureAuxServerTransportContext`, `SecureAuxTransportSettingsProvider::parameters` must be provided the `AuxTransport` instance so it knows which transport to fetch security settings for.
Prerequisite for introducing security plugin settings for aux transports:
https://github.com/opensearch-project/security/pull/5375
=> Provide aux transport to SecureAuxTransportSettingsProvider

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java, server/src/main/java/org/opensearch/index/query/RegexpQueryBuilder.java, server/src/test/java/org/opensearch/index/query/RegexpQueryBuilderTests.java
Coming from @msfroh suggestion https://github.com/opensearch-project/OpenSearch/issues/18397#issuecomment-2950840604 I can see the issue where the `COMPLEMENT` is dropped and `sanitisedSyntaxFlag` returns as 0. With this change I see the value as 65536 (`0x10000`) which works as expected.
Added an IT test as I assume we cannot test this with existing unit tests in `RegexpQueryBuilderTests`.
Background, the `COMPLEMENT(RegExp.DEPRECATED_COMPLEMENT),` is updated as part of https://github.com/opensearch-project/OpenSearch/pull/16366
When we upgrade to Lucene 11 (OpenSearch 4.0), we should:
- Remove `COMPLEMENT(RegExp.DEPRECATED_COMPLEMENT)`, from OpenSearch `RegexpFlag` class.
- Handle the `RegexpQueryBuilder.java`
- Update Documentation …
=> [Bug Fix] Fix the backward compatibility regression with `COMPLEMENT` for Regexp queries introduced in OpenSearch 3.0

CHANGELOG.md, server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java, server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java, server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
Fix replication lag computation
This change fixes a bug with replication lag computation to correctly use epoch reference point with Instant.now() and DateUtils. This change also fixes pruning logic to correctly remove the latest synced to checkpoint from tracking.  Previously we would only prune up to the latest.  This ensures that when a new checkpoint is eventually received we aren't incorrectly computing lag from the synced-to checkpoint.
Resolves https://github.com/opensearch-project/OpenSearch/issues/18437#issuecomment-2964468170 …
=> Fix bugs in replication lag computation

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java, server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
This fixes an issue in segrep flow which causes infinite segrep loop. The analysis is present in the issue - https://github.com/opensearch-project/OpenSearch/issues/18605. 
Resolves #18605
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING …
=> Fix checkpoint handling to prevent segment replication infinite loop

server/src/main/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInput.java, server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java, server/src/test/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInputTests.java, server/src/test/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInputTests.java
Remove clone holder and add Cleaner logic to clean up clones in FullFileCachedIndexInput
Resolves #18659 
=> Remove clone holder and add Cleaner logic to clean up clones in FullFileCachedIndexInput

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java, server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Backports https://github.com/opensearch-project/OpenSearch/commit/46a0045a2301b3bc51e2da9c5e853f69ac6342c2 from https://github.com/opensearch-project/OpenSearch/pull/18636/
=> [Backport 2.19] Fix checkpoint handling to prevent segment replication infinite loop

libs/core/src/main/java/org/opensearch/semver/SemverRange.java, libs/core/src/main/java/org/opensearch/semver/expr/Range.java, libs/core/src/test/java/org/opensearch/semver/SemverRangeTests.java, libs/core/src/test/java/org/opensearch/semver/expr/RangeTests.java
This PR fixes the SemverRange implementation to properly handle version range expressions and comparisons. The changes include:
1. Proper implementation of range parsing and validation
2. Correct handling of inclusive/exclusive bounds in version ranges
4. Added proper validation for invalid inputs
5. Ensured correct version comparisons within ranges
Resolves #18554 
N/A
=> Added support for range version support in semver

CHANGELOG.md, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/autotagging/Rule.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/package-info.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/package-info.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/WorkloadGroupPersistenceService.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/package-info.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/WorkloadManagementPluginTests.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/service/WorkloadGroupPersistenceServiceTests.java, server/src/main/java/org/opensearch/wlm/MutableWorkloadGroupFragment.java, server/src/main/java/org/opensearch/wlm/WorkloadGroupService.java, server/src/main/java/org/opensearch/wlm/WorkloadGroupsStateAccessor.java, server/src/main/java/org/opensearch/wlm/WorkloadManagementSettings.java, server/src/main/java/org/opensearch/wlm/stats/WorkloadGroupState.java, server/src/main/java/org/opensearch/wlm/stats/WorkloadGroupStats.java, server/src/main/java/org/opensearch/wlm/stats/package-info.java, server/src/main/java/org/opensearch/wlm/tracker/CpuUsageCalculator.java, server/src/main/java/org/opensearch/wlm/tracker/MemoryUsageCalculator.java, server/src/main/java/org/opensearch/wlm/tracker/ResourceUsageCalculator.java, server/src/test/java/org/opensearch/wlm/WorkloadGroupServiceTests.java, server/src/test/java/org/opensearch/wlm/tracker/WorkloadGroupTaskResourceTrackingTests.java
Renamed all remaining instances of QueryGroup to WorkloadGroup in code comments, Javadocs, and identifiers where applicable, to align with the current naming convention used in the workload management feature.
=> [Workload Management] Rename QueryGroup to WorkloadGroup

MAINTAINERS.md
Following the [nomination process](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer), I have nominated and other maintainers have agreed to add [prudhvigodithi](https://github.com/prudhvigodithi) as a co-maintainer of the OpenSearch repository. He has kindly accepted the invitation.
Prudhvi has been an excellent steward of the OpenSearch Project as a whole through his work on engineering efficiency and has been trusted as an admin for the project for the last few years. More recently, Prudhvi has been contributing in significant ways to the core repo through code contributions, reviews, opening up issues and engaging with the OpenSearch community on issues.
Prudhvi has been a contributor since 2022 and has 48 PRs merged into the core repo …
=> Add Prudhvi Godithi (GH: prudhvigodithi) as a maintainer

CHANGELOG.md, server/src/main/java/org/opensearch/wlm/WorkloadGroupService.java
This PR updated the rejection reason logging in rejectIfNeeded to dynamically include the actual resiliency mode (SOFT or ENFORCED) from the WorkloadGroup object, instead of hardcoding "ENFORCED". 
=> [Workload Management] Modify logging message in WorkloadGroupService

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java, server/src/main/java/org/opensearch/index/shard/RemoteStoreUploader.java, server/src/main/java/org/opensearch/index/shard/RemoteStoreUploaderService.java, server/src/test/java/org/opensearch/index/shard/RemoteStoreUploaderServiceTests.java
The PR aims to highlight the changes on how to segregate the syncing segments to Remote Store which is highly coupled to the Refresh workflow. 
The segregation of the code will help to sync the segments at any action. Some are listed below
1. Syncing the segments as soon as it is merged to the remote store.
2. Syncing the segments after the refresh is triggered.
The overall purpose of the above mentioned feature to make the segments available as soon as possible reducing the search latency since the ingestion of the document. …
=> Changes for the Upload Workflow for merged segments

server/src/main/java/org/opensearch/common/lucene/Lucene.java
Initially this default if-else code was identified by @expani. The existing `readFieldDoc` and `readSortValue` are used at the transport layer. This code change when compiled creates a `tableswitch` which Jumps directly to the corresponding code location.
Not modifying the `writeSortValue` to pattern matching switch as from my understanding `tableswitch` only works with integer primitives.
N/A.
=> `Lucene.java` Code Improvement

server/src/main/java/org/opensearch/index/store/CompositeDirectory.java, server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
Fix sync method to account for block files in Composite Directory
Resolves #18657 
=> Fix sync method to account for block files in Composite Directory

CHANGELOG.md, server/src/main/resources/org/opensearch/bootstrap/security.policy
The logs rolling triggered AccessControlException, and the log files access permission are not   `rw-r-----`.  More and more users get this error, although it is not a fatal issue, it is a issue that we will encounter when out-of-the-box,so i think we should fix it.
Resolves #18594 #9609
The test Result is expected behavior
=> fix the bug of Access denied error when rolling log files

CHANGELOG.md, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/action/CreateRuleRequest.java, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/autotagging/RuleValidator.java, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/service/IndexStoredRulePersistenceService.java, modules/autotagging-commons/common/src/test/java/org/opensearch/rule/autotagging/RuleValidatorTests.java, modules/autotagging-commons/src/main/java/org/opensearch/rule/rest/RestGetRuleAction.java, modules/autotagging-commons/src/test/java/org/opensearch/rule/rest/RestGetRuleActionTests.java, plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/sync/RefreshBasedSyncMechanism.java, plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/rule/sync/RefreshBasedSyncMechanismTests.java
This PR contains several bug fix/improvements for the rule-based auto tagging feature. 
- Refines the extraction of attribute parameters from `RestRequest` in `RestGetRuleAction`. The previous approach filtered out a few known non-attribute/system params, but it relied on a fixed exclusion list. It could still include other unrelated or unintended params if they weren’t explicitly listed, especially any automatically added query params from the system. 
```
final Set<String> excludedKeys = Set.of(FEATURE_TYPE, ID_STRING, SEARCH_AFTER_STRING, "pretty");
final List<String> requestParams = request.params().keySet().stream().filter(key -> !excludedKeys.contains(key)).toList();
```
This current change whitelists only keys that are explicitly defined as allowed attributes for the given …
=> [Rule-based auto tagging] Bug fix and improvements

server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java, server/src/internalClusterTest/java/org/opensearch/indices/state/RemoteCloseIndexIT.java
Fix flaky RemoteCloseIndexIT test
=> Fix flaky RemoteCloseIndexIT test

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java, server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheSettings.java, server/src/main/java/org/opensearch/monitor/MonitorService.java, server/src/main/java/org/opensearch/monitor/fs/FsServiceProvider.java, server/src/main/java/org/opensearch/monitor/fs/WarmFsService.java, server/src/main/java/org/opensearch/node/Node.java, server/src/test/java/org/opensearch/monitor/fs/WarmFsServiceTests.java
FS stats for warm nodes based on total addressable space
Resolves #18768 
=> FS stats for warm nodes based on addressable space

CHANGELOG.md, server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
Backport https://github.com/opensearch-project/OpenSearch/pull/18802 to 2.19
=> [Backport 2.19] Use ScoreDoc instead of FieldDoc when creating TopScoreDocCollectorManager to avoid unnecessary conversion

CHANGELOG.md, server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java, server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java, server/src/main/java/org/opensearch/index/engine/NoOpEngine.java, server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java, server/src/test/java/org/opensearch/index/engine/LeafSorterOptimizationTests.java, server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java
Timestamp sort optimisations (leafSorter) were not working consistently across all engine types. While InternalEngine (primary shards) correctly applied leafSorter, other engine types like ReadOnlyEngine (searchable snapshots) and NRTReplicationEngine (segment replication) were not passing leafSorter when opening DirectoryReader instances.
This caused inconsistent performance for time-series workloads:
- Primary shards: Fast time-series queries (segments ordered by timestamp)
- Searchable snapshots: Slower time-series queries (segments in arbitrary order)
- Segment replication replicas: Slower time-series queries (segments in arbitrary order)
**Solution**
Apply leafSorter optimisation consistently across all engine types by ensuring `DirectoryReader.open()` calls include the leafSorter …
=> Fix leafSorter optimization for ReadOnlyEngine and NRTReplicationEngine

CHANGELOG.md, modules/ingest-common/src/internalClusterTest/java/org/opensearch/ingest/common/HierarchicalRoutingProcessorIT.java, modules/ingest-common/src/main/java/org/opensearch/ingest/common/HierarchicalRoutingProcessor.java, modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java, modules/ingest-common/src/test/java/org/opensearch/ingest/common/HierarchicalRoutingProcessorTests.java, modules/ingest-common/src/test/java/org/opensearch/ingest/common/IngestCommonModulePluginTests.java, modules/search-pipeline-common/src/internalClusterTest/java/org/opensearch/search/pipeline/common/HierarchicalRoutingSearchProcessorIT.java, modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/HierarchicalRoutingSearchProcessor.java, modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java, modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/HierarchicalRoutingSearchProcessorTests.java, modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
Implements ingest and search pipeline processors to co-locate related
documents based on hierarchical paths (e.g., folder structures). Documents
with same path prefix are routed to same shard, enabling efficient
search within hierarchies.
- HierarchicalRoutingProcessor: Routes documents during indexing
- HierarchicalRoutingSearchProcessor: Routes queries to relevant shards
- Consistent MurmurHash3-based routing between ingest and search
- Configurable anchor depth, path separators, and field mapping
=> Add hierarchical routing processors for document co-location

plugins/repository-s3/README.md, plugins/repository-s3/build.gradle, plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
Issue #18796
Describe the bug
[Repository s3 plugin test S3RepositoryThirdPartyTests.java does not have an option to override path_style_access and endpoint for integration tests, this helps to test for different possible s3 settings.
With the fix we will be able to test any changes with above 2 settings variations ,
Current integration test is, AWS_REGION=us-west-2 amazon_s3_access_key=$AWS_ACCESS_KEY_ID amazon_s3_secret_key=$AWS_SECRET_ACCESS_KEY amazon_s3_base_path=path amazon_s3_bucket=dblock-opensearch ./gradlew :plugins:repository-s3:s3ThirdPartyTest
With this chaange, we will also pass custom path_style_access and endpoint.
- [ x] Functionality includes testing. …
=> [BUG] Repository s3 plugin test S3RepositoryThirdPartyTests.java does not have an option to override path_style_access and endpoint #18796

CHANGELOG.md, modules/ingest-common/src/internalClusterTest/java/org/opensearch/ingest/common/AclRoutingProcessorIT.java, modules/ingest-common/src/main/java/org/opensearch/ingest/common/AclRoutingProcessor.java, modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java, modules/ingest-common/src/test/java/org/opensearch/ingest/common/AclRoutingProcessorTests.java, modules/ingest-common/src/test/java/org/opensearch/ingest/common/IngestCommonModulePluginTests.java, modules/search-pipeline-common/src/internalClusterTest/java/org/opensearch/search/pipeline/common/AclRoutingSearchProcessorIT.java, modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/AclRoutingSearchProcessor.java, modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java, modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/AclRoutingSearchProcessorTests.java, modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
Introduces two new processors to enable document routing based on ACL metadata:
- AclRoutingProcessor (ingest pipeline):
* Extracts ACL field value and generates deterministic routing using MurmurHash3
* Configurable options: acl_field, target_field (default: _routing), 
ignore_missing, override_existing
* Ensures documents with same ACL values colocate on same shard
- AclRoutingSearchProcessor (search pipeline):  
* Automatically extracts ACL values from term/terms/bool queries
* Sets routing on search requests to target specific shards
* Supports nested bool query traversal (must/filter/should clauses)
* Configurable extraction with extract_from_query flag
Implementation details:
- Both processors use identical MurmurHash3.hash128() with Base64 encoding
for consistent routing value …
=>  Add ACL-aware routing processors for multi-tenant document routing

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java, server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
This change addresses a bug which appears when a custom preference string is included with a query while awareness attributes are present on the cluster.
In this scenario it can seem as if the custom preference string included with query is not being honored. This is due to how awareness attributes preference shards which share an attribute with the coordinating node when routing a search request. Awareness attributes take priority and the custom string preference is only applied after this step. A search request with the same custom string preference can then be routed differently depending on which node is acting as coordinator.
All other preference types[ exit early and ignore awareness attributes](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opens …
=> Ignore attribute awareness when custom preference is set

CHANGELOG.md, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java, plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaSingleNodeTests.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java, server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
Transient consumer errors (such as kafka connection issues) fail shard/engine initialization today, resulting in possibility of cascading failures, where all the primary and replica shards can go down. This PR moves the consumer initialization logic into the poller with retries in case of transient errors.
Follow up for #16929 
=> [Pull-based Ingestion] Prevent shard initialization failures due to transient consumer errors

server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java, server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
I found this flakey test in #[18890](https://github.com/opensearch-project/OpenSearch/pull/18890)'s [gradle test](https://build.ci.opensearch.org/job/gradle-check/61454/).
I investigated the cause and fixed it.
```
java.lang.AssertionError: unexpected exception type thrown; expected:<java.io.IOException> but was:<java.lang.AssertionError>
at __randomizedtesting.SeedInfo.seed([6A2AFF70E0EFA082:D601FF6FAC77A86]:0)
at org.junit.Assert.assertThrows(Assert.java:1020)
at org.junit.Assert.assertThrows(Assert.java:981)
at org.opensearch.index.store.remote.utils.TransferManagerTestCase.testOverflowDisabledAsynchronous(TransferManagerTestCase.java:205)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at …
```
=> Fix flakey test testOverflowDisabledAsynchronous

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRepositoryRegistrationIT.java
This PR adds comprehensive negative test cases to RemoteStoreRepositoryRegistrationIT to improve test coverage for remote store functionality. The added tests verify proper error handling and validation during node join scenarios that should fail.
1. testNodeJoinFailureWithDifferentRemoteStoreRepositoryAttributes - Tests incompatible remote store configurations
2. testNodeRejoinFailureWithChangedRemoteStoreAttributes - Tests node rejoin failure with changed attributes
3. testNodeJoinFailureWithMissingRemoteStoreAttributes - Tests missing remote store attributes
4. testRepositoryVerificationFailureDuringNodeJoin - Tests repository verification failure with invalid repository types
These negative test cases enhance the robustness of remote store functionality by ensuring proper validation …
=> Issue #9675: [Remote Store] Add negative test cases and improve cluster stability validation in RemoteStoreRepositoryRegistrationIT

CHANGELOG.md, modules/transport-grpc/README.md, modules/transport-grpc/build.gradle, modules/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/Netty4GrpcServerTransport.java, modules/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransport.java
Remove the "experimental" designation from all transport-grpc settings, in preparation for the upcoming 3.2 GRPC GA 
Corresponding public doc fixes will be made in https://github.com/opensearch-project/documentation-website/pull/10651/files 
Part of https://github.com/opensearch-project/OpenSearch/issues/16787
=> [GRPC] Remove `experimental` designation from transport-grpc settings

CHANGELOG.md, server/src/main/java/org/opensearch/ingest/IngestService.java, server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Reset isPipelineResolved to false to resolve the system ingest pipeline again. If we don't reset it as false we simply skip resolving the pipeline.
Resolves #18909
=> Reset isPipelineResolved to false to resolve the system ingest pipeline again.

modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java
Fix a compilation bug after gRPC plugin moved to module. The secure gRPC transport always invokes its constructor as all extension points are called for modules. This is problematic as this extension point has side effects and constructs the transport. It should instead provide a lambda to construct the transport which is only invoked when the transport is configured in settings with `aux.transport.types`.
N/A
=> Fix gRPC initialized even without aux type registered

CHANGELOG.md, modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java, modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/GrpcPluginTests.java
Correcting a previous mistake when adding SETTING_GRPC_MAX_MSG_SIZE. This setting is not included in GrpcPlugin `getSettings`. This causes the max size setting to be rejected if set with opensearch.yml.
N/A
=> Expose SETTING_GRPC_MAX_MSG_SIZE to settings service

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java
Fix flaky tests in CloseIndexIT
Several tests in CloseIndexIT were failing intermittently due to cluster
state synchronization issues during node operations. The main problems
were timing-related race conditions and inconsistent node count tracking
during restarts.
Key fixes:
- Store cluster size before node restart operations to avoid inconsistent counts
- Add retry logic to assertIndexIsClosed for eventual consistency
- Include explicit timeouts on close/open operations
- Add cluster state convergence checks after dynamic operations
- Reduce race conditions in concurrent tests with small random delays
All originally failing tests now pass consistently across 100+ iterations
with concurrent segment search disabled.
=> Fix CloseIndexIT test

distribution/packages/src/common/systemd/opensearch.service, server/src/main/resources/org/opensearch/bootstrap/security.policy
Update permission for read in /sys/fs/cgroup/system.slice/- path.
If running in docker the folder location changed compares to #18975:
```
/sys/fs/cgroup/system.slice/<>.service/memory.max
becomes
/sys/fs/cgroup/system.slice/docker-89906b83d995faf977d24e8d25bc465a5df6c0eb0a51deedb9aae6b929b85ce1.scope/system.slice/opensearch.service/memory.max
```
Follow up #18975
=>  Update permission for read in /sys/fs/cgroup/system.slice/- path

CHANGELOG.md, modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java, modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java, server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Within tiered cache, when a query runs into exceptions [here](https://github.com/opensearch-project/OpenSearch/blob/main/modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java#L380) around timeouts, or parent task cancels it etc, it causes the NPE to be thrown [here](https://github.com/opensearch-project/OpenSearch/blob/main/modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java#L351) which though is swallowed eventually but this internally causes the query/key to not be removed from the temporary map [here](https://github.com/opensearch-project/OpenSearch/blob/main/modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java#L372)  which is responsible to handle concurrent …
=> [Tiered Caching] Handle query execution exception

test/fixtures/hdfs-fixture/build.gradle
Cherry picked a90f864b8524bc75570a8461ccb569d2a4bfed42 from #18795
=> [Backport 3.2] Exclude commons-beanutils from dep on hadoop-miniclusters

CHANGELOG.md, server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
IndexStatsIT.testConcurrentIndexingAndStatsRequests sometimes fails with the following NPE:
```
IndexStatsIT > testConcurrentIndexingAndStatsRequests {p0={"cluster.indices.replication.strategy":"SEGMENT"}} FAILED
java.lang.AssertionError:
Expected: an empty collection
but: <[[test][3] failed, reason [BroadcastShardOperationFailedException[operation indices:monitor/stats failed]; nested: NullPointerException[Cannot invoke "java.util.Map$Entry.getValue()" because "highestEntry" is null]; ]]>
at __randomizedtesting.SeedInfo.seed([B56C9D0503BD16AE:2FDF6CC817B0190]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:964)
at org.junit.Assert.assertThat(Assert.java:930)
at org.opensearch.indices.stats.IndexStatsIT.testConcurrentIndexingAnd …
```
=> Fix NPE in segment replicator

test/fixtures/hdfs-fixture/build.gradle
Cherry picked a90f864b8524bc75570a8461ccb569d2a4bfed42 from #18795
=> [Forwardport main] Exclude commons-beanutils from dep on hadoop-miniclusters

server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
I reproduced this test locally. The exception information is as follows:
```
ClusterManagerNotDiscoveredException[cluster-manager not discovered
]
at __randomizedtesting.SeedInfo.seed([CA32ECE92650D7B6:4E02F48BD9CA9FCF]:0)
at org.opensearch.action.admin.cluster.health.TransportClusterHealthAction.executeHealth(TransportClusterHealthAction.java:284)
at org.opensearch.action.admin.cluster.health.TransportClusterHealthAction.clusterManagerOperation(TransportClusterHealthAction.java:158)
at org.opensearch.action.admin.cluster.health.TransportClusterHealthAction.clusterManagerOperation(TransportClusterHealthAction.java:81)
at org.opensearch.action.support.clustermanager.TransportClusterManagerNodeAction$AsyncSingleAction.lambda$doStart$0(TransportClusterManagerNodeAction.java:262)
at …
```
=> fix flaky WeightedRoutingIT

server/src/test/java/org/opensearch/index/autoforcemerge/AutoForceMergeManagerTests.java
This commit removes a non-deterministic sleep and properly asserts that the AutoForceMergeManager completes quickly when interrupted. The previous test logic had a race condition where it checked the interrupt status of the thread, but that could return false if the thread was in the process of catching the InterruptException but had not yet reset the interrupt flag of the thread. The new logic is to set the delay to be the maximum of 60 seconds and assert that the test thread exits more quickly than that due to being interrupted.
Resolves #18820 …
=> Fix faulty assertion in AutoForceMergeManagerTests

server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java
(cherry picked from commit a23bbc4a9990de28c3b5fa3f9b0b84c202c7655e)
Manual backport of #18946
=> [Backport 2.19] Fix CloseIndexIT test (#18946)

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/index/111_false_allow_templates.yml, rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_mapping/all_path_options.yml, server/src/main/java/org/opensearch/index/mapper/DocumentParser.java, server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java, server/src/test/java/org/opensearch/index/mapper/CopyToMapperTests.java, server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java, server/src/test/java/org/opensearch/index/mapper/DynamicMappingTests.java
This PR adds the `dynamic: false_allow_templates` option to the schema. This creates mappings for any field that matches `properties` or `dynamic_templates`, and ignores any fields that do not (as opposed to rejecting altogether).
Example from linked issue, the usage is:
1. Create the index:
```
{
"url": { "type": "keyword" },
},
"dynamic": "false_allow_templates",
"dynamic_templates": [
{
"dates": {
"match": "date_*",
"mapping": {
"type": "date",
},
},
}
]
}
```
2. `url` matches an explicit property and the fields `date_timestamp` and `date_timezone` math the dynamic template:
```
POST index1/_doc/1
{
"url": "www.example.com",
"date_timestamp": "...",
"date_timezone": "...",
"misc_field": "..."
}
```
3. Produces the mapping:
```
{
"url": { "type": …
```
=> Add `false_allow_templates` as a dynamic mapping option

rest-api-spec/src/main/resources/rest-api-spec/test/search/400_max_score.yml
The version check in 400_max_score.yml is not correct, the bug is fixed in 3.2.0, so the skip version should be 3.1.99 rather than 3.2.0 which causes that yaml test is skipped.
No issue.
=> Fix the version check in 400_max_score.yml

server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java, server/src/main/java/org/opensearch/search/startree/StarTreeQueryHelper.java
- Reverts intended changes from https://github.com/opensearch-project/OpenSearch/pull/18671 where accidentally made a private method in IpFieldMapper as public: https://github.com/opensearch-project/OpenSearch/pull/18671/files#diff-daa7078975bbb300cf8b6a7be32603d1c3092303720b102c873c57d02f90d12bL240
- Minor refactoring/cleanup in [StarTreeQueryHelper.java](https://github.com/opensearch-project/OpenSearch/compare/main...sandeshkr419:OpenSearch:ip?expand=1#diff-5e33f49395fd147e45fcc577678d2c8f591a50a82fd0f754283785691020bf16) …
=> Reverts accidental access changes in IpFieldMapper parser util

server/src/test/java/org/opensearch/index/engine/CompletionStatsCacheTests.java
The test had a race condition where threads were calling start() twice
on the CyclicBarrier - once inside getStats() and once from the main
thread. This caused inconsistent synchronization and intermittent failures.
Fixed by separating barrier synchronization from stats retrieval. Threads
now explicitly call start() to wait on the barrier, then call getStatsOnly()
to retrieve stats without additional synchronization.
Fixes #18682
Signed-off-by: Atri Sharma <atri.jiit@gmail.com> …
=> Fix flaky CompletionStatsCacheTests.testCompletionStatsCache

server/src/main/java/org/opensearch/index/store/RemoteDirectory.java, server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java, server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
- In multipart upload flow, we open IndexInput for each part and this can cause exhaustion of virtual memory for the OpenSearch process.
- In this PR, instead of creating new IndexInput instance, we clone the original IndexInput instance. Cloned IndexInput instance makes sure not to create a separate map entry in the virtual memory.
=> Clone index input in multipart upload flow

CHANGELOG.md, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/IndexModule.java, server/src/main/java/org/opensearch/index/IndexService.java, server/src/main/java/org/opensearch/index/store/Store.java, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/main/java/org/opensearch/node/Node.java, server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java, server/src/test/java/org/opensearch/index/IndexModuleTests.java, server/src/test/java/org/opensearch/plugins/IndexStorePluginTests.java
This enables plugins to provide custom Store implementations per index.
- Extend IndexStorePlugin interface with StoreFactory and getStoreFactories() method  
- Add `INDEX_STORE_FACTORY_SETTING` to allow plugins to provide custom Store factories
- Update `IndexService` to use pluggable `StoreFactory` for shard Store creation
- Make `Store.LoadedMetadata` and `Store.OnClose` public API for custom store plugin developers
- Support factory selection via `index.store.factory` setting with fallback to default Store
Will have a PR later to actually implement the Store plugin, which would have a custom store implementation to handle files outside the default store `index` directory.
Resolves #19090  …
=> Add StoreFactory plugin interface for custom Store implementations

modules/mapper-extras/src/javaRestTest/java/org/opensearch/index/mapper/ScaledFloatDerivedSourceIT.java, server/src/main/java/org/opensearch/index/mapper/FieldMapper.java
When enabling scaled_float field, due to different ClassLoader being used for module, and core, ScaledFloatFieldMapper is unable to access package-protected methods. This is leading to process being killed due to the fatal error. This commit fixes the same.
```
java.lang.IllegalAccessError: class org.opensearch.index.mapper.ScaledFloatFieldMapper tried to access method 'void org.opensearch.index.mapper.FieldMapper.checkStoredAndDocValuesForDerivedSource()' (org.opensearch.index.mapper.ScaledFloatFieldMapper is in unnamed module of loader java.net.FactoryURLClassLoader @16b57f2; org.opensearch.index.mapper.FieldMapper is in unnamed module of loader 'app')
```
NA
For more …
=> Fix access specifier for FieldMapper method to allow usage by plugins 

rest-api-spec/src/main/resources/rest-api-spec/test/search/400_max_score.yml
The skip version in 400_max_score.yml is not correct, that causes the tests are skipped, this PR fixes the version and also fixes the test failure.
No issue.
=> [Backport 3.2] Fix max_score yaml test is skipped

distribution/docker/build.gradle
Followup to comments on [this commit](https://github.com/opensearch-project/OpenSearch/commit/eae84a49d9052eb09e18c167f3aeaf1cf4467941) to update error messages and comments.
=> Update comments and errors messages for: Replace centos:8 with almalinux:8

CHANGELOG.md, server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java, server/src/main/java/org/opensearch/index/translog/LocalTranslog.java, server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java, server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java, server/src/main/java/org/opensearch/index/translog/Translog.java, server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java, server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java, server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java, server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java, server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java, test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Adds a channel factory parameter to translog constructor which was earlier always defaulted to `FileChannel::open`. This enables us to pass our own channel factory which was not possible by overriding otherwise.
Related:
- https://github.com/opensearch-project/opensearch-storage-encryption/pull/39
=> Add Channel Factory parameter to Translog

modules/analysis-common/src/test/java/org/opensearch/analysis/common/DisableGraphQueryTests.java, modules/lang-painless/src/test/java/org/opensearch/painless/NeedsScoreTests.java, modules/lang-painless/src/test/java/org/opensearch/painless/action/PainlessExecuteApiTests.java, modules/percolator/src/test/java/org/opensearch/percolator/PercolatorQuerySearchTests.java, plugins/mapper-size/src/internalClusterTest/java/org/opensearch/index/mapper/size/SizeMappingTests.java, server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java, server/src/internalClusterTest/java/org/opensearch/search/aggregations/FiltersAggsRewriteIT.java, server/src/test/java/org/opensearch/action/termvectors/GetTermVectorsTests.java, server/src/test/java/org/opensearch/index/analysis/PreBuiltAnalyzerTests.java, server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java, server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java, server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java, server/src/test/java/org/opensearch/index/mapper/UpdateMappingTests.java, server/src/test/java/org/opensearch/index/search/NestedHelperTests.java, server/src/test/java/org/opensearch/index/search/nested/NestedSortingTests.java, server/src/test/java/org/opensearch/index/similarity/SimilarityTests.java, server/src/test/java/org/opensearch/index/termvectors/TermVectorsServiceTests.java, server/src/test/java/org/opensearch/search/aggregations/AggregatorBaseTests.java, server/src/test/java/org/opensearch/search/aggregations/support/ValuesSourceConfigTests.java, server/src/test/java/org/opensearch/search/fetch/subphase/FieldFetcherTests.java, server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java, server/src/test/java/org/opensearch/search/geo/GeoShapeQueryTests.java, server/src/test/java/org/opensearch/search/suggest/completion/CategoryContextMappingTests.java, server/src/test/java/org/opensearch/search/suggest/completion/GeoContextMappingTests.java, test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
The deprecated versions of this method take a type parameter, support for which was removed back in 2.0. The parameter is not used. I have kept the deprecated methods so as to not break downstream components that may be using them but changed all the code in server to stop passing in a type parameter.
=> Replace usage of deprecated createIndex() method in tests

server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
The cancellation tests could deadlock when threads are delayed by OS
scheduling. If cancellation triggers before all threads start, late
threads may hit a code path where batchReduceSize causes the latch
callback to be deferred to a MergeTask. Under certain timing conditions,
these callbacks never execute, causing latch.await() to hang indefinitely.
Ensure latch.countDown() is always called by wrapping consumeResult in
try-catch. This guarantees test completion regardless of cancellation
timing or exceptions.
Fixes #19094 …
=> Fix deadlock in SearchPhaseControllerTests cancellation tests

CHANGELOG.md, rest-api-spec/src/main/resources/rest-api-spec/test/search/110_field_collapsing.yml, server/src/main/java/org/apache/lucene/search/grouping/CollapseTopFieldDocs.java, server/src/main/java/org/opensearch/action/search/SearchPhaseController.java, server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java, server/src/test/java/org/opensearch/lucene/grouping/CollapsingTopDocsCollectorTests.java, server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
In Lucene 9.0.0, this [change](https://github.com/apache/lucene-solr/pull/757) was introduced that removes the ability of TopDocs.merge to set shard indices, and we adopted the change in 2.0.0, but [CollapseTopFieldDocs.merge()](https://github.com/opensearch-project/OpenSearch/blob/0cc83a97fa6f5e71036c88e08bf05682495af5ea/server/src/main/java/org/apache/lucene/search/grouping/CollapseTopFieldDocs.java#L177) still supports setting shard indices, that should also be removed.
As a result, when collapsing search results with concurrent segment search enabled, the shardIndex of the top docs are set twice in both [queryPhase](https://github.com/opensearch-project/OpenSearch/blob/8f310f5e37c65f9c3116c05685a6713eb5e68886/server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java …
=> Remove the setShardIndex parameter in CollapseTopFieldDocs.merge()

CHANGELOG.md, gradle/formatting.gradle
Seeing https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md#eclipse-jdt Attempt to fix the jdt formatter error which is seen failing on recent open PR's.
https://github.com/opensearch-project/OpenSearch/actions/runs/17335154878/job/49219860173?pr=19188
```
* What went wrong:
A problem occurred configuring project ':build-tools'.
> Could not create task ':build-tools:spotlessJava'.
> java.io.IOException: Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketException: Network is unreachable
```
The issue started because the https://mirror.umd.edu/eclipse/eclipse/updates/4.29 mirror is not accessible.
Seeing on all open PR's https://github.com/opensearch-project/OpenSearch/pull/19188
By submitting this pull request, I confirm that my contribution …
=> Attempt to fix the jdt formatter error

CHANGELOG.md, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java, server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
Ingestion state was persisted in the cluster state on calling Pause API but the poller was not considering this on replica promotion. Initialize the poller state correctly by considering the initial state passed by the engine. This should avoid the pollers resuming ingestion on replica promotion, and also fix flaky tests.
Resolves #17693
=> [Pull-based Ingestion] Fix ingestion pause state initialization on replica promotion

MAINTAINERS.md
Following the [nomination process](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer), I have nominated and other maintainers have agreed to add Atri Sharma (@atris ) as a co-maintainer of the OpenSearch repository. He has gratiously accepted the invitation.
---
Atri has become a very active contributor to OpenSearch. He implemented [temporal-based routing processors](https://github.com/opensearch-project/OpenSearch/issues/18920) that allows for temporal locality at a shard level for time-based workloads. He leveraged existing primitives (search and ingest processors) to implement the feature which allows users to enable it with no client-side changes. He also implemented two other enhancements to document routing for [ACL-based …
=> Add Atri Sharma as a maintainer

server/src/main/java/org/opensearch/index/autoforcemerge/AutoForceMergeManager.java
Async task initialization added to doStart method as the task is throwing null pointer exception when called within the time interval where autoForceMerge manager object is initialized and started. 
=> [Auto Force Merge] Async task initialization fix

modules/lang-painless/src/test/java/org/opensearch/painless/DerivedFieldScriptTests.java, server/src/main/java/org/opensearch/script/DerivedFieldScript.java
This change addresses a bug in DerivedFieldScript where emitting Float values was not supported, even though the official OpenSearch documentation lists Float as a valid type for derived field scripts.
Issue: The getObjectByteSize method in DerivedFieldScript only accounted for Double, Integer, Long, Boolean, String, and Tuple types. Emitting a Float previously caused an IllegalArgumentException.
Fix: Added support for Float in getObjectByteSize so that scripts emitting Float values are handled correctly without errors.
Tests: A new test testEmittingFloatField has been added in DerivedFieldScriptTests to verify that Float values can be emitted successfully. Existing tests for Double, GeoPoint, multiple values, and byte-size limit continue to pass.
Resolves #19271 …
=> Issue 19271: Fix DerivedFieldScript to support emitting Float type

server/src/main/java/org/opensearch/search/query/rewriters/BooleanFlatteningRewriter.java, server/src/test/java/org/opensearch/search/query/QueryRewriterRegistryTests.java, server/src/test/java/org/opensearch/search/query/rewriters/BooleanFlatteningRewriterTests.java, server/src/test/java/org/opensearch/search/query/rewriters/MatchAllRemovalRewriterTests.java, server/src/test/java/org/opensearch/search/query/rewriters/MustNotToShouldRewriterTests.java, server/src/test/java/org/opensearch/search/query/rewriters/MustToFilterRewriterTests.java, server/src/test/java/org/opensearch/search/query/rewriters/TermsMergingRewriterTests.java
Resolve #19266 by fixing double-negation under MUST_NOT introduced by #19060 When parent is must_not and nested bool has only must_not clauses, rewrite to a positive OR:
not(bool(must_not:[X1..Xn])) => filter(bool(should:[X1..Xn], minimum_should_match=1))
Use FILTER (not MUST) to preserve non-scoring semantics of must_not
Leave other flattenings unchanged; only trigger on pure must_not nested bool
Add unit test: testDoubleNegationConvertedToPositiveMustShould
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …
=> Fix regression: preserve not(not X) in BooleanFlatteningRewriter

modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/121_grok_capture_all_matches.yml
The version check section in the new added 121_grok_capture_all_matches.yml file is missing, may cause compatibility test to fail.
No issue.
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTIN …
=> Add version check in 121_grok_capture_all_matches.yml

CHANGELOG.md, plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileBasedIngestionSingleNodeTests.java, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java, plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java, plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaSingleNodeTests.java, plugins/ingestion-kinesis/src/internalClusterTest/java/org/opensearch/plugin/kinesis/IngestFromKinesisIT.java, server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/GetIngestionStateResponse.java, server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionState.java, server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportGetIngestionStateAction.java, server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportUpdateIngestionStateAction.java, server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java, server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java, server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java, server/src/main/java/org/opensearch/index/engine/IngestionEngine.java, server/src/main/java/org/opensearch/indices/pollingingest/IngestionEngineFactory.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/GetIngestionStateResponseTests.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionStateTests.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportGetIngestionStateActionTests.java, server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportUpdateIngestionStateActionTests.java, server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java, server/src/test/java/org/opensearch/index/engine/IngestionEngineTests.java
Pull-based ingestion today only supports segment replication. This PR adds an all-active mode where the replica also indexes the documents. This is done by having the replica shards ingest from the streaming source independently and process the messages when the all-active ingestion mode is enabled. The replicas will continue to use the peer recovery mode during shard reinitialization. Note that there is no replication or coordination between the primary and replicas in this mode, as each of them will ingest and index independently.
This mode can be expected to support better throughput in comparison to traditional doc-rep, and also provide better freshness as there is no replication delays.
The GetIngestionState API is enhanced to include primary and node name in the response to …
=> [Pull-based Ingestion] Support all-active mode in pull-based ingestion

CHANGELOG.md, modules/transport-grpc/build.gradle, modules/transport-grpc/licenses/failureaccess-1.0.2.jar.sha1, modules/transport-grpc/licenses/failureaccess-LICENSE.txt
Change failureaccess from compileOnly to runtimeOnly to bundle it with transport-grpc
- This fixes NoClassDefFoundError for InternalFutureFailureAccess in plugins that use Guava concurrency features
- Resolves classloader isolation issues between transport-grpc and plugin dependencies
=> Add failureaccess dependency to transport-grpc module

CHANGELOG.md, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/storage/AttributeValueStore.java, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/storage/DefaultAttributeValueStore.java, modules/autotagging-commons/common/src/test/java/org/opensearch/rule/storage/AttributeValueStoreTests.java, modules/autotagging-commons/src/main/java/org/opensearch/rule/InMemoryRuleProcessingService.java
In this PR, we restructured the in-memory rule tries so that values are stored as a set instead of a single string.
The reason is that as we add more attributes into the system, a single attribute key may correspond to multiple valid labels.
For example:
```
Rule 1: index_pattern: [a], label: label1
Rule 2: index_pattern: [a], username: [b], label: label2
```
These two rules are not duplicates—both should be stored. In the trie for index_pattern, the key a would map to:
```
a → { label1, label2 }
```
By switching from a string to a set, we can correctly represent multiple labels for the same attribute key without overwriting or losing data.
More documentation on the feature is here: https://docs.opensearch.org/latest/tuning-your-cluster/availability-and-recovery/rule-based-autotagging/auto …
=> [Rule-based Auto-tagging] restructure the in-memory trie to store values as a set

plugins/engine-datafusion/build.gradle, plugins/engine-datafusion/jni/Cargo.toml, plugins/engine-datafusion/jni/src/lib.rs, plugins/engine-datafusion/jni/src/util.rs, plugins/engine-datafusion/src/main/java/org/opensearch/datafusion/DataFusionPlugin.java, plugins/engine-datafusion/src/main/java/org/opensearch/datafusion/DataFusionService.java, plugins/engine-datafusion/src/main/java/org/opensearch/datafusion/DatafusionEngine.java, plugins/engine-datafusion/src/main/java/org/opensearch/datafusion/ErrorUtil.java, plugins/engine-datafusion/src/main/java/org/opensearch/datafusion/ObjectResultCallback.java, plugins/engine-datafusion/src/main/java/org/opensearch/datafusion/RecordBatchStream.java, plugins/engine-datafusion/src/main/java/org/opensearch/datafusion/core/SessionContext.java, server/src/main/java/org/opensearch/index/engine/SearchExecutionEngine.java, server/src/main/java/org/opensearch/plugins/SearchEnginePlugin.java, server/src/main/java/org/opensearch/search/aggregations/SearchResultsCollector.java
This PR focuses on the methods in JNI layer and implementations in rust to execute the substratit plan in DF in rust.
Also defined interfaces in Core, but this doesn't have the code which actually uses it in the query phase.
=> [Feauture Branch] Add JNI layer and rust methods to execute substrait plan

CHANGELOG.md, buildSrc/build.gradle
This version of the plugin is compatible with Gradle 9. Note there is a new major version of this plugin with some breaking changes, so for now I'm doing the minimal update to unblock downstream repos that use this plugin.
=> Update shadow-gradle-plugin to 8.3.9

server/src/test/java/org/opensearch/search/aggregations/bucket/terms/StreamStringTermsAggregatorTests.java
- I replaced RandomIndexWriter to plain IndexWriter to avoid unexpected segments in test which are unable to handle more than single segment
- for other test I've added explicit segmenting. TODO It needs to be reviewed.
- Perhaps StreamingTermsAggregator should reject second segment via assert or there should be a proper publish/reset flow. TODO, WIP
so far this commit fixes the known reason for flackines (I belive) …
=> fix StreamStringTermsAggregatorTests by replacing RandomIndexWriter with plain IndexWriter #18956 WIP

CHANGELOG.md, buildSrc/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Something in Gradle 9 broke the assemble workflow such that the tarballs are not being generated. This is a minimal revert of #19329 to go back to using Gradle 8.14.3 which fixes the assemble workflow.
=> Revert back to Gradle 8.14.3

CHANGELOG.md, server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java, server/src/main/java/org/opensearch/common/xcontent/support/XContentMapValues.java, server/src/main/java/org/opensearch/indices/SystemIndices.java
This PR does a minor change to migrate usages of deprecated Lucene Operations#union to a non-deprecated version, preserving the original behaviour.
Migrate usages of `org.apache.lucene.util.automaton.Operations#union(Automaton, Automaton)` to `org.apache.lucene.util.automaton.Operations#union(Collection<Automation>)`
None …
=> Migrate deprecated usages of Operations#union

DEVELOPER_GUIDE.md, gradle/run.gradle
In trying to test some changes to sql and OpenSearch I found it annoying to have to re-assemble and manually install a plugin every time I made a change to OpenSearch.
This change allows us to install and test plugins that are not shipped with OpenSearch core with gradlew run. You can use it by only specifying the plugin name or adding a specific version to test patches or a released version.
Example :
`./gradlew run -PinstalledPlugins['opensearch-job-scheduler']` which will look for `opensearch-job-scheduler:<current-opensearch-version>0-SNAPSHOT`
or 
`./gradlew run -PinstalledPlugins['opensearch-job-scheduler:3.2.x.x]`
it works fine along with existing plugins:
```
./gradlew run --debug-server-jvm -PinstalledPlugins="['opensearch-job-scheduler', 'opensearch-sql-plugin', …
```
=> Update gradle run to be able to fetch and run external plugins

CHANGELOG.md, server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/index/search/QueryStringQueryParser.java, server/src/main/java/org/opensearch/search/SearchService.java
This introduces a new cluster wide setting `search.query.max_query_string_length` which can be used to limit the max length of simple, Lucene-style query strings. This provides a simple but robust way to control inputs from potentially untrusted sources.
=> Introduced new setting search.query.max_query_string_length

CHANGELOG.md, modules/autotagging-commons/common/src/main/java/org/opensearch/rule/RuleUtils.java
This PR implements a bug fix for the Update Rule API used in rule-based auto-tagging.
Previously, if a rule had two attributes and an update request was sent with only one attribute, both existing attributes would be replaced. With this fix, only the specified attribute will be updated, while the others remain unchanged.
For example, 
the previous rule is 
```
{
"description": "test1",
"principal": {"username": ["alice"]},"index_pattern": ["my-index"],
"workload_group": "x5_wjV3lRjWRO5tG1fydgw"
}'
```
and we only update the field `index_pattern`, the result will still have the original principal entry
```
{
"description": "test1",
"index_pattern": ["my-indexxx"],
"workload_group": "x5_wjV3lRjWRO5tG1fydgw"
}'
{"id":"83e89252-7d30-30ab-8e07-082817115c08","description":"test1","index_pattern" …
```
=> [Rule-based Auto-tagging] bug fix on Update Rule API with multiple attributes

CHANGELOG.md, modules/opensearch-dashboards/src/main/java/org/opensearch/dashboards/OpenSearchDashboardsModulePlugin.java, server/src/main/java/org/opensearch/action/ActionModule.java, server/src/main/java/org/opensearch/action/search/StreamSearchTransportService.java, server/src/main/java/org/opensearch/common/settings/ClusterSettings.java, server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java, server/src/main/java/org/opensearch/common/util/FeatureFlags.java, server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java, server/src/test/java/org/opensearch/rest/action/search/RestSearchActionTests.java
This PR updates the feature flag introduced in #19373 to cluster setting which can be dynamic update at runtime without restarting the cluster.
=> Change stream search feature flag to cluster setting

CHANGELOG.md, server/src/main/java/org/opensearch/action/search/QueryPhaseResultConsumer.java, server/src/main/java/org/opensearch/action/search/StreamQueryPhaseResultConsumer.java, server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
This PR is meant for harden the circuit breaker logic in query result consumer. The main logic change is only at one place, `addEstimateAndMaybeBreak(aggsSize)` in `consumeResult` before actually perform any real "consume logic".
On the other hand, considering this is a important but spaghetti code, and possibly need to be improved in the future, some refactoring works are also done.
Circuit breaker `addEstimateBytesAndMaybeBreak` are used twice
1. before `consume`: query result received at coordinator transport layer, and will be handled by query result consumer. We estimate the heap size of the query result, and check if it breaks the REQUEST circuit breaker.
2. during `tryExecuteNext`: before doing partial reduce on the buffered query results, we estimate the extra heap size that will …
=> Harden the circuit breaker and failure handle logic in query result consumer

CHANGELOG.md, plugins/arrow-flight-rpc/src/internalClusterTest/java/org/opensearch/streaming/aggregation/SubAggregationIT.java, server/src/main/java/org/opensearch/search/aggregations/AggregatorBase.java, server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java, server/src/main/java/org/opensearch/search/aggregations/metrics/StreamCardinalityAggregator.java, server/src/test/java/org/opensearch/search/aggregations/metrics/StreamCardinalityAggregatorTests.java
Expands streaming aggregations to cardinality aggregator. This PR ensures that we only use the Ordinals Collector while streaming and resets the value after each new batch.
Resolves #19515 
=> Expand streaming Aggregations to  Cardinality Aggregator

CHANGELOG.md, server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java, server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java, server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
Reverts derived field rewrite and chooses to rewrite queries based on the type of query
Resolves #19337 
=> Fix derived query rewrite

CHANGELOG.md, server/src/main/java/org/opensearch/indices/IndicesService.java, server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java, server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java, server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java, server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java, server/src/main/java/org/opensearch/search/profile/aggregation/ProfilingAggregator.java, server/src/main/java/org/opensearch/search/streaming/FlushModeResolver.java, server/src/test/java/org/opensearch/search/aggregations/metrics/MaxAggregatorTests.java, server/src/test/java/org/opensearch/search/aggregations/metrics/MinAggregatorTests.java
When request is streaming aggregation, we should refrain from caching it due to lack of better solution at present.
Independent of this issue, there are couple of other issues with streaming aggregation which are follow up of https://github.com/opensearch-project/OpenSearch/pull/19484 -
Need to check flush mode as null or per segment before deciding on StreamCardinalityAggregator in CardinalityAggregatorFactory.
Minor - When profilingAggregator is enabled, flushMode decision doesn't work as expected.
Min, Max aggregator should be Streamable.
Resolves https://github.com/opensearch-project/OpenSearch/issues/19518
~~- [ ] …
=> Disable request cache for streaming and other fixes

CHANGELOG.md, test/fixtures/hdfs-fixture/build.gradle
Exclude commons-lang and org.jsonschema2pojo from hadoop-miniclusters to address brining in transitive deps with known CVEs. This miniclusters dependency keeps on giving :/
=> Exclude commons-lang and org.jsonschema2pojo from hadoop-miniclusters

MAINTAINERS.md
Following the [nomination process](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer), I have nominated and other maintainers have agreed to add Karen Xu (@karenyrx) as a co-maintainer of the OpenSearch repository. She has graciously accepted the invitation.
---
Karen has spearheaded the project to add gRPC APIs to OpenSearch over the past 6 months. This includes working on the core changes to add the gRPC and Protobuf dependencies, and integrating with the existing transport layer. 
To date, Karen has:
* authored [23 PRs](https://github.com/opensearch-project/OpenSearch/pulls?q=+is%3Apr+author%3Akarenyrx+). (all relatively large PRs w/ hundreds/thousands line of changes)
* reviewed [27 …
=> Add karenyrx as a maintainer
