opensearch-project/OpenSearch

CHANGELOG.md
server/src/main/java/org/opensearch/plugins/SearchPlugin.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/main/java/org/opensearch/search/aggregations/AggregationPhase.java
server/src/main/java/org/opensearch/search/aggregations/InternalAggregation.java
server/src/main/java/org/opensearch/search/aggregations/InternalAggregations.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/AvgBucketPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketMetricsPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketScriptPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketSelectorPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/CumulativeSumPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/DerivativePipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/ExtendedStatsBucketPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/MaxBucketPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/MinBucketPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/MovAvgPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/MovFnPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/PercentilesBucketPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/PipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/SerialDiffPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/SiblingPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/StatsBucketPipelineAggregator.java
server/src/main/java/org/opensearch/search/aggregations/pipeline/SumBucketPipelineAggregator.java
server/src/main/java/org/opensearch/search/query/QuerySearchResult.java
server/src/test/java/org/opensearch/search/SearchModuleTests.java
server/src/test/java/org/opensearch/search/aggregations/InternalAggregationsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/SignificanceHeuristicTests.java
test/framework/src/main/java/org/opensearch/test/InternalAggregationTestCase.java

Removes the deprecated readTo/writeFrom serialization logic from piepline aggs that is no longer used as of Legacy version 7.8.

[Remove] Deprecated serialization logic from pipeline aggs

---

CHANGELOG.md
DEVELOPER_GUIDE.md

Have a permalink to explain to contributors what to do when they encounter a flakey test.

Added a section of how to deal with flakey tests to the developer guide.

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/search/190_index_prefix_search.yml

This feature was backported in #4219 and will only be present in version 2.4 and newer. The test must be skipped for mixed cluster cases with nodes older than 2.4.
#4831

Skip uppercase regex tests before 2.4.0

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/RegisterTransportActionsRequest.java
server/src/test/java/org/opensearch/extensions/RegisterTransportActionsRequestTests.java
server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java

Signed-off-by: mloufra <mloufra@amazon.com>
Add unbounded wildcard for RegisterTransportActionsRequest constructor to clean up compiler warning
Equivalent PR on OpenSearch-sdk-java:  https://github.com/opensearch-project/opensearch-sdk-java/pull/195
https://github.com/opensearch-project/opensearch-sdk-java/issues/130

[Feature/extensions]Enforce type safety for RegisterTransportActionsRequest

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java

* Introduce Remote translog feature flag
* Limit combinations of remote segment and translog store to valid ones
(cherry picked from commit a469a3cbcb7a7294a81bf7e4122968c2a9b32ca4)

[Backport 2.x] Introduce Remote translog feature flag (#4158)

---

CHANGELOG.md
qa/mixed-cluster/build.gradle
qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
server/src/main/java/org/opensearch/action/get/MultiGetResponse.java

There is a compatibility issue with `/_mget` API: RHLC 2.x connected to OpenSearch Cluster 1.x, which basically renders the API unusable in certain cases, ending up with `NullPointerException`.
```
Exception in thread "main" java.io.IOException: Unable to parse response body for Response{requestLine=POST /_mget HTTP/1.1, host=http://localhost:9200, response=HTTP/1.1 200 OK}
at org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1777)
at org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1724)
at org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1692)
at org.opensearch.client.RestHighLevelClient.mget(RestHighLevelClient.java:7 …
```

Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x

---

CHANGELOG.md
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
buildSrc/src/test/resources/pluginzip/allProjectsGroup.gradle
buildSrc/src/test/resources/pluginzip/groupPriorityLevel.gradle

This is back-port of #4772 
(cherry picked from commit eb3301554ec7e1a07866508ffc390b8651dc3394)

[Backport 2.x] Add groupId value propagation tests for ZIP publication task

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/index/80_geo_point.yml
server/src/main/java/org/opensearch/common/geo/GeoPoint.java
server/src/main/java/org/opensearch/common/geo/GeoUtils.java
server/src/main/java/org/opensearch/index/mapper/AbstractPointGeometryFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/GeoPointFieldMapperTests.java
server/src/test/java/org/opensearch/index/search/geo/GeoPointParsingTests.java
server/src/test/java/org/opensearch/index/search/geo/GeoUtilsTests.java

* Support of GeoJson Point for GeoPoint field
See https://github.com/opensearch-project/geospatial/issues/152
(cherry picked from commit a282d399225247226d5abc3e3cd903462c973877)

[Backport 2.x]Support of GeoJson Point for GeoPoint field (#4597)

---

.github/pull_request_template.md
CHANGELOG.md

Add commented tips in pull request template 
N/A

Update pull request template to include tips

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/index/80_geo_point.yml

Skip geojson test for version below 2.4
https://github.com/opensearch-project/OpenSearch/issues/4852

Skip geojson test for version below 2.4

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/snapshots/blobstore/SlicedInputStream.java
server/src/test/java/org/opensearch/index/snapshots/blobstore/SlicedInputStreamTests.java

Per the contract of InputStream#read(byte[], int, int):
If len is zero, then no bytes are read and 0 is returned
SlicedInputStream had a bug where if a zero length was passed then it would drain all the underlying streams and return -1. This was uncovered by using InputStream#readAllBytes in new code under development. The only existing usage of SlicedInputStream should not be vulnerable to this bug.
I've also added a check for invalid arguments and created tests to ensure the proper exceptions are thrown per the InputStream contract. In the test I've replaced a "readFully" method with an equivalent "readNBytes" that was introduced in Java 11. …

Fix bug in SlicedInputStream with zero length

---

CHANGELOG.md
qa/mixed-cluster/build.gradle
qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
server/src/main/java/org/opensearch/action/get/MultiGetResponse.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4812 to `2.3`

[Backport] [2.3] Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x (#4812)

---

CHANGELOG.md
qa/mixed-cluster/build.gradle
qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
server/src/main/java/org/opensearch/action/get/MultiGetResponse.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4812 to `2.x`

[Backport] [2.x] Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x (#4812)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

Updating bundled JDK to 11.0.16.1+1 and 8u345-b01
N/A

Updating bundled JDK to 11.0.16.1+1 and 8u345-b01

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

PR link to main: https://github.com/opensearch-project/OpenSearch/pull/4318
NA

[Backport 2.x] [Remote Store] Change behaviour in replica recovery for remote translog enabled indices (#4318)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java

Replicas are bootstrapped using the recovery path, as opposed to the restore path used for creating the primary shard. This has been broken in the initial implementation of searchable snapshots. The fix here is to put in the appropriate checks to avoid failing during recovery.
I've also updated the integration test to ensure the recovery path is always exercised during testing.
(cherry picked from commit 6ac0c7cd2054da9a6492c76011d1dcd2e0f518b8)
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTIN …

[Backport 2.x] Fix recovery path for searchable snapshots (#4813)

---

.github/workflows/gradle-check.yml
CHANGELOG.md

Backport of https://github.com/opensearch-project/OpenSearch/pull/4872.

[Backport] Add a link to the flakey test dev guide.

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/mapper/AbstractPointGeometryFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/GeoPointFieldMapperTests.java

With this commit, appropriate exception is thrown when an array of four values are provided for point type field.
https://github.com/opensearch-project/OpenSearch/pull/4597 introduced a bug which accept an array of four values for point type field. This PR resolve the issue.
Current behavior:
```
PUT testindex1/_doc/4
{
"point": [1.1, 1.2, 1.3, 1.4] 
}
200 OK
```
Expected behavior after this commit:
```
PUT testindex1/_doc/4
{
"point": [1.1, 1.2, 1.3, 1.4] 
}
400 [geo_point] field type does not accept more than 3 values
```
N/A …

Fix a bug on handling an invalid array value for point type field

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/mapper/AbstractPointGeometryFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/GeoPointFieldMapperTests.java

With this commit, appropriate exception is thrown when an array of four values are provided for point type field.
(cherry picked from commit 0f477a2d0aae4d75313a7f26407cda8594bd981e)
Backport of https://github.com/opensearch-project/OpenSearch/pull/4900
See https://github.com/opensearch-project/OpenSearch/pull/4900

[Backport] [2.x] Fix a bug on handling an invalid array value for point type field (#4900)

---

CHANGELOG.md
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoGridAggregationBuilder.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoGridAggregator.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoHashGridAggregator.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoTileGridAggregator.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoGrid.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoGridBucket.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoHashGrid.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoTileGrid.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/ParsedGeoGrid.java

Change access modifier from default to protected. 
This will help to build new geo based aggregation
outside OpenSearch, by keeping GeoGrid Classes as base class.
Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>

Update GeoGrid base class access modifier to support extensibility

---

.github/workflows/gradle-check.yml
CHANGELOG.md
DEVELOPER_GUIDE.md

After a bit of googling, I believe the correct definition is "flaky". Will rename labels as well.

Renamed to "flaky" test.

---

.github/workflows/gradle-check.yml
CHANGELOG.md
DEVELOPER_GUIDE.md

Backport https://github.com/opensearch-project/OpenSearch/pull/4912

[Backport][2.x] Backport #4912, renamed flaky tests

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequestBuilder.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestDecommissionAction.java
server/src/test/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequestTests.java
server/src/test/java/org/opensearch/rest/action/admin/cluster/RestDecommissionActionTests.java

Signed-off-by: pranikum <109206473+pranikum@users.noreply.github.com>
We need to allow delay_timeout to be set as parameter for decommission request
[[List any issues this PR will resolve]](https://github.com/opensearch-project/OpenSearch/issues/4930)

Add delay timeout for decommission request

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/io/stream/NamedWriteableRegistryParseRequest.java
server/src/main/java/org/opensearch/common/io/stream/NamedWriteableRegistryResponse.java
server/src/main/java/org/opensearch/extensions/ExtensionNamedWriteableRegistry.java
server/src/main/java/org/opensearch/extensions/NamedWriteableRegistryResponseHandler.java
server/src/test/java/org/opensearch/extensions/ExtensionsOrchestratorTests.java

Signed-off-by: mloufra <mloufra@amazon.com>
Add generic type for `categoryClass` in `NamedWriteable RegistryParseRequest`, `NamedWriteableRegistryResponse`, `ExtensionNamedWriteableRegistry`, `NamedWriteableRegistryResponseHandler` and `ExtensionsOrchestratorTests` 
Equivalent PR on OpenSearch-sdk-java: https://github.com/opensearch-project/opensearch-sdk-java/pull/203
https://github.com/opensearch-project/opensearch-sdk-java/issues/130

[Feature/extensions]Enforce type safety for NamedWriteableRegistryParseRequest

---

CHANGELOG.md
server/src/main/java/org/opensearch/Version.java

Fix for failing VerifyVersionConstantsIT tests on gradle check. Caused by lucene version mismatch after lucene version upgrade. 
Resolves #4945 

Fix failing test: VerifyVersionConstantsIT

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java
buildSrc/src/test/java/org/opensearch/gradle/precommit/ForbiddenPatternsTaskTests.java
modules/lang-painless/src/main/java/org/opensearch/painless/antlr/Walker.java
modules/reindex/src/test/java/org/opensearch/index/reindex/RoundTripTests.java
plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
qa/die-with-dignity/src/javaRestTest/java/org/opensearch/qa/die_with_dignity/DieWithDignityIT.java
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
sandbox/plugins/concurrent-search/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/MultiTermsIT.java
server/src/main/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponse.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/index/engine/Segment.java
server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java
server/src/main/java/org/opensearch/ingest/IngestMetadata.java
server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
server/src/test/java/org/opensearch/action/admin/indices/rollover/RolloverRequestTests.java
server/src/test/java/org/opensearch/cluster/coordination/NoClusterManagerBlockServiceTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/common/joda/JavaJodaTimeDuellingTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
server/src/test/java/org/opensearch/index/translog/TranslogTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

I realised there is a bunch of private/package private unused methods... 
Since they are private and unused this is a PR to remove them

Remove unused private methods

---

CHANGELOG.md
client/rest-high-level/src/test/java/org/opensearch/client/HighLevelRestClientCompressionIT.java
modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
server/src/main/resources/org/opensearch/bootstrap/test-framework.policy

Fixed compression support for h2c protocol (upgrade handler). There were 2 issues (quite nasty ones, to be fair):
- the `decoder_compress` handler was run after `aggregator` and was not able to decode the request
- the `encoder` is not needed, it is already present in the `HttpServerCodec` configured before
Why our tests did not catch it:  the default `CloseableHttpAsyncClient` does not support compression out of the box so that applies to RestClient and RestHighLevelClient which are used for all kind of tests.
To check the compression works on both sides, crafting the request using `CloseableHttpClient` instead which uses compression by default (or 3rd party clients like https://github.com/opensearch-project/opensearch-go).
Closes …

Fixed compression support for h2c protocol

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java

This is a fix for failing windows gradle check tasks as part of providing windows CI support. This focuses on 3 groups of failing tasks - checkExtraction, checkLicense and checkNotice tasks.
Resolves #4925, #4939, #4940

Fix for failing checkExtraction, checkLicense and checkNotice tasks for windows gradle check

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This PR backports https://github.com/opensearch-project/OpenSearch/pull/4928
Resolves https://github.com/opensearch-project/OpenSearch/issues/4927

Backport [2.x] [Segment Replication] Fix bug of replica shard's translog not purging on index

---

.github/workflows/backport.yml
CHANGELOG.md

- Fixes the issues caused by CHANGELOG merge conflicts when using the backport GHA
- #4936 

Fix backport issues for CHANGELOG.md file

---

CHANGELOG.md
buildSrc/build.gradle
buildSrc/version.properties
test/fixtures/hdfs-fixture/build.gradle

* Upgrading`jetty-server` (which brings in `jetty-http`) due to GHSA-cj7v-27pg-wf7q which is brought in by `hadoop-minicluster`.
* Upgrading `kotlin-stdlib` which is brought in through `hadoop-minicluster`. See GHSA-cqj8-47ch-rvvq.
* Upgrading `snakeyaml` which is brought in by `com.avast.gradle:gradle-docker-compose-plugin`. See GHSA-98wm-3w3q-mw94

Fix dependencies

---

CHANGELOG.md
scripts/build.sh

the build script should be located in this repository instead of centrally in [opensearch-build][] to allow per-branch specific builds (newer versions might have newer requirements, which currently cannot be reflected).
the file was copied 1:1 from `scripts/components/OpenSearch/build.sh` as of commit 9e1aa38 in the [opensearch-build][] repository.
this is part of opensearch-build#99 and needs to be backported to all active branches because the file here will only be used by the build once the central one in opensearch-build has been removed which in turn can only happen when all active branches have the `build.sh`.
[opensearch-build]: https://github.com/opensearch-project/opensearch-build
Signed-off-by: Ralph Ursprung …

[Backport 2.3] copy `build.sh` over from opensearch-build

---

CHANGELOG.md
scripts/build.sh

with commit e3572464859 the `build.sh` has been moved to this repository and with commit dfa1118eee8 the missing no-jdk builds have been added. with these preliminary works done we can now start building the no-jdk distributions as part of the release build so that they can then be published.
this is part of opensearch-project/opensearch-build#99.
Co-authored-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>
(cherry picked from commit 8c9ca4e858e6333265080972cf57809dbc086208) …

[Backport 2.x] build no-jdk distributions as part of release build

---

CHANGELOG.md
scripts/build.sh

the build script should be located in this repository instead of centrally in [opensearch-build][] to allow per-branch specific builds (newer versions might have newer requirements, which currently cannot be reflected).
the file was copied 1:1 from `scripts/components/OpenSearch/build.sh` as of commit 9e1aa38 in the [opensearch-build][] repository.
this is part of opensearch-build#99 and needs to be backported to all active branches because the file here will only be used by the build once the central one in opensearch-build has been removed which in turn can only happen when all active branches have the `build.sh`.
[opensearch-build]: https://github.com/opensearch-project/opensearch-build
Signed-off-by: Ralph Ursprung …

[Backport 1.x] copy `build.sh` over from opensearch-build

---

CHANGELOG.md
buildSrc/build.gradle
buildSrc/version.properties
test/fixtures/hdfs-fixture/build.gradle

* Upgrading kotlin-stdlib and excluding jetty-http
* Upgrading indirect snakeyaml dependency
* Update CHANGELOG
* Using snakeyaml version from version file
* Upgrading jetty-http instead of excluding since it is used
* Extracting kotlin version
Backport #4963 to 1.x …

[Backport 1.x] Fix dependencies (#4963)

---

CHANGELOG.md
buildSrc/build.gradle
buildSrc/version.properties
test/fixtures/hdfs-fixture/build.gradle

* Upgrading kotlin-stdlib and excluding jetty-http
* Upgrading indirect snakeyaml dependency
* Update CHANGELOG
* Using snakeyaml version from version file
* Upgrading jetty-http instead of excluding since it is used
* Extracting kotlin version
Backport #4963 to 2.x …

[Backport 2.x] Fix dependencies (#4963)

---

CHANGELOG.md
scripts/build.sh

the build script should be located in this repository instead of centrally in [opensearch-build][] to allow per-branch specific builds (newer versions might have newer requirements, which currently cannot be reflected).
the file was copied 1:1 from `scripts/components/OpenSearch/build.sh` as of commit 9e1aa38 in the [opensearch-build][] repository.
this is part of opensearch-build#99 and needs to be backported to all active branches because the file here will only be used by the build once the central one in opensearch-build has been removed which in turn can only happen when all active branches have the `build.sh`.
[opensearch-build]: https://github.com/opensearch-project/opensearch-build
Signed-off-by: Ralph Ursprung …

[Backport 1.3] copy `build.sh` over from opensearch-build

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

OpenJDK 19.0.1, 17.0.5, 11.0.17, and 8u351 are released.
Closes https://github.com/opensearch-project/OpenSearch/issues/4956

OpenJDK Update (October 2022 Patch releases)

---

CHANGELOG.md
buildSrc/src/integTest/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTarIT.java

Skip SymbolicLinkPreservingTarIT when running on Windows.  This test creates symlinks which requires admin privileges to succeed on Windows.  The assemble task will only build a zip when performed on Windows, so these tests are not required.
https://github.com/opensearch-project/OpenSearch/issues/4924

Skip SymbolicLinkPreservingTarIT when running on Windows.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/cluster/ClusterModule.java
server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java
server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
server/src/test/java/org/opensearch/cluster/routing/AllocationIdTests.java
server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java
server/src/test/java/org/opensearch/cluster/routing/ShardRoutingTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsAllocateUnassignedTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsMoveShardsTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsRebalanceShardsTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java
test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

- Adds a remote allocator for searchable snapshots
- #4777 

Add remote shards allocator for searchable snapshots

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

Backport of https://github.com/opensearch-project/OpenSearch/pull/4998 to `1.3`

[Backport] [1.3] OpenJDK Update (October 2022 Patch releases) (#4998)

---

buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

[Backport] [2.0] OpenJDK Update (October 2022 Patch releases) (#4997)

---

buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

[Backport] [2.1] OpenJDK Update (October 2022 Patch releases) (#4997)

---

buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

[Backport] [2.2] OpenJDK Update (October 2022 Patch releases) (#4997)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

[Backport] [2.3] OpenJDK Update (October 2022 Patch releases) (#4997)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

[Backport] [2.4] OpenJDK Update (October 2022 Patch releases) (#4997)

---

.github/workflows/gradle-check.yml
CHANGELOG.md

Remove gradle-check dependency on precommit

---

CHANGELOG.md
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java

Fixes the version check for decommission metadata and exceptions related to decommission
Backport PR for decommission - https://github.com/opensearch-project/OpenSearch/pull/4970

Fix version check for 2.x release for awareness attribute decommission

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/EdgeNGramTokenizerTests.java

`edgeNGram` analyzer name was deprecated in legacy versions. In preparation for removal in the next major opensearch version, 
an IAE is thrown. This commit adds a test to ensure the IAE logic remains intact until removal.

[Test] Add IAE test for deprecated edgeNGram analyzer name

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/action/admin/indices/rollover/RolloverIT.java
server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateNumberOfReplicasIT.java
server/src/internalClusterTest/java/org/opensearch/indices/template/SimpleIndexTemplateIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
server/src/main/java/org/opensearch/cluster/metadata/AutoExpandReplicas.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
server/src/main/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalance.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalanceTests.java

Backporting the changes merged in #4994.

[Backport 2.x] Add AutoExpandReplica in the validation of replica count enforcement

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/TransportDecommissionAction.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionStatus.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingService.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestDecommissionAction.java
server/src/test/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequestTests.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java
server/src/test/java/org/opensearch/rest/action/admin/cluster/RestDecommissionActionTests.java

Backports following PRs - 
1. https://github.com/opensearch-project/OpenSearch/pull/4839
2. https://github.com/opensearch-project/OpenSearch/pull/4586
3. https://github.com/opensearch-project/OpenSearch/pull/4931
4. https://github.com/opensearch-project/OpenSearch/pull/4715

Backport Graceful Decommission and Integ Tests

---

CHANGELOG.md
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java

Windows registers a cpu tick at a default of ~15ms which is slightly slower than other OSs.  In CI and in most local runs the runnables in this test often complete in under that time and return a 0 value from
ThreadMXBean.getThreadCpuTime. To reduce flakiness in this test accept 0 as a value on Windows.
closes #5063

Fix flaky test ResourceAwareTasksTests on windows.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
server/src/main/java/org/opensearch/index/store/remote/utils/BlobFetchRequest.java

- Fixes length calculation for on demand block fetching
- N/A

Fix length calculation for block based fetching

---

CHANGELOG.md
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java

Add Changelog entry.
Revert unintentional removal of memory assertion.

[Backport 2.4] Fix flaky test ResourceAwareTasksTests on windows. (#5077)

---

CHANGELOG.md
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java

Add Changelog entry.
Revert unintentional removal of memory assertion.

[Backport 2.x] Fix flaky test ResourceAwareTasksTests on windows. (#5077)

---

release-notes/opensearch.release-notes-2.4.0.md

The CHANGELOG was a bit of a mess. I've tried to fix it up. Please review and let me know what you think. Ultimately I intend to copy this content to a `release-notes/opensearch.release-notes-2.4.0.md`. Then maybe the CHANGELOG file should be emptied out since it would then track changes _after_ the 2.4 release?
---
There are a few changes in this commit:
- For new features (e.g. Point in Time Search), I've replaced all the incremental commits with a single line pointing to the main GitHub issue describing the feature.
- The 2.x section was mostly wrong with either duplicates or incorrect entries. I've consolidated it into the main 2.4 section (which was previously labeled as 'unreleased')
- All changes related to flaky test fixes, GitHub workflows, etc have been removed as they are not …

Update CHANGELOG for 2.4 release

---

CHANGELOG.md
server/src/main/java/org/opensearch/OpenSearchException.java

Modify the change from this comment (https://github.com/opensearch-project/OpenSearch/pull/4708#discussion_r990501062)
[4669](https://github.com/opensearch-project/OpenSearch/pull/4669)

Change the output error message back to use OpenSearchException in the cause chain

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

- Add allocation tests for searchable snapshot remote shards
- #4962 

Add allocation tests for searchable snapshot remote shards

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java

Engine AlreadyClosedException exception takes place when replication is finalized on replica shard and when translog generation rollover takes place at which point we see the engine has already been closed. 
We want to make sure we only update the segments when the engine is open. Added an integration test for the same.
Resolves #4530 

[Segment Replication] Fix for AlreadyClosedException for engine

---

.github/workflows/changelog_verifier.yml

- Add support for skipping changelog verifier when labelled with `skip-changelog`
- N/A

Add support for skipping changelog

---

.github/workflows/gradle-check.yml
.github/workflows/precommit.yml
CHANGELOG.md

This reverts commit 2139e804158c34bceeb581ac01c5b562dc734485.
This change is causing issues on main - see https://github.com/opensearch-project/OpenSearch/pull/5127#issuecomment-1306588426.  Reverting until those problems are resolved.

Revert "Run precommit before gradle check (#5066)"

---

CHANGELOG.md
buildSrc/build.gradle

Bump nebula-publishing-plugin from v4.4.4 to v4.6.0.
4.4.4 relies on nebula-core 3.0.0 which is not in maven central.  v4.6.0 depends on nebula-core 4.0.1 which is present.
closes #5121

Bump nebula-publishing-plugin from v4.4.0 to v4.6.0.

---

CHANGELOG.md
buildSrc/build.gradle

This is a manual backport of https://github.com/opensearch-project/OpenSearch/pull/5127.  that pr fails gradle check's bwc tests that clone this branch.  This branch (and likely others will fail without bumping this version).

[Backport 2.3] Bump nebula-publishing-plugin from v4.4.0 to v4.6.0.

---

CHANGELOG.md
buildSrc/build.gradle

[Backport 2.4] Bump nebula-publishing-plugin from v4.4.0 to v4.6.0

---

buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java

Upgrade com.netflix.nebula:nebula-publishing-plugin to 4.6.0 and gradle-docker-compose-plugin to 0.14.12.
Part of https://github.com/opensearch-project/OpenSearch/issues/5121.

Upgrade com.netflix.nebula:nebula-publishing-plugin to 4.6.0 and gradle-docker-compose-plugin to 0.14.12.

---

buildSrc/build.gradle

Upgrade com.netflix.nebula:nebula-publishing-plugin to 4.6.0.
Because this ships in 2.4, skipping CHANGELOG on 2.x.
Part of https://github.com/opensearch-project/OpenSearch/issues/5121.

Upgrade com.netflix.nebula:nebula-publishing-plugin to 4.6.0.

---

.github/workflows/backport.yml

In #5143 the backport workflow ran because I added a `skip-changelog` label.

Only run backport workflow it a backport label was added.

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/HyphenationCompoundWordTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterGraphTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/BaseWordDelimiterTokenFilterFactoryTestCase.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuCollationTokenFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiPartOfSpeechFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiTokenizerFactory.java
plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriAnalyzerProvider.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriPartOfSpeechStopFilterFactory.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriTokenizerFactory.java
release-notes/opensearch.release-notes-2.4.0.md
server/src/main/java/org/opensearch/index/analysis/Analysis.java
server/src/main/java/org/opensearch/index/analysis/CustomMappingRuleParser.java
server/src/main/java/org/opensearch/index/analysis/MappingRule.java
server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
server/src/test/java/org/opensearch/index/analysis/AnalysisTests.java
server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
server/src/test/java/org/opensearch/indices/analyze/HunspellServiceTests.java

On top of https://github.com/opensearch-project/OpenSearch/pull/5139, raise error on malformed CSV.

[Backport 2.4] Raise error on malformed CSV

---

modules/analysis-common/src/main/java/org/opensearch/analysis/common/HyphenationCompoundWordTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterGraphTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/BaseWordDelimiterTokenFilterFactoryTestCase.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuCollationTokenFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiPartOfSpeechFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiTokenizerFactory.java
plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriAnalyzerProvider.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriPartOfSpeechStopFilterFactory.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriTokenizerFactory.java
release-notes/opensearch.release-notes-2.4.0.md
server/src/main/java/org/opensearch/index/analysis/Analysis.java
server/src/main/java/org/opensearch/index/analysis/CustomMappingRuleParser.java
server/src/main/java/org/opensearch/index/analysis/MappingRule.java
server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
server/src/test/java/org/opensearch/index/analysis/AnalysisTests.java
server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
server/src/test/java/org/opensearch/indices/analyze/HunspellServiceTests.java

Fix error handling while reading analyzer mapping rules.
Porting #5123 and #5141 to 2.x.
This ships in 2.4, so no CHANGELOG for 2.5.

[Backport 2.x] Fix error handling while reading analyzer mapping rules.

---

CHANGELOG.md
build.gradle
buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java
buildSrc/version.properties
gradle/wrapper/gradle-wrapper.properties
test/framework/build.gradle
test/framework/src/main/java/org/opensearch/cluster/coordination/MockSinglePrioritizingExecutor.java

Update to Gradle 7.6 and JDK-19
Closes https://github.com/opensearch-project/OpenSearch/issues/4637

Update to Gradle 7.6 and JDK-19

---

server/src/internalClusterTest/java/org/opensearch/clustermanager/ClusterManagerTaskThrottlingIT.java

The test creates a latch = number of requests, then every time a request finishes decrements the latch. For all failures it increments a counter. When the latch is at zero, it checks the counter. The counter was incremented after the latch was released, before the counter had a chance to be incremented one last time. 
Closes #5083.

Fix: org.opensearch.clustermanager.ClusterManagerTaskThrottlingIT is flaky.

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/HyphenationCompoundWordTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterGraphTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/BaseWordDelimiterTokenFilterFactoryTestCase.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuCollationTokenFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiPartOfSpeechFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiTokenizerFactory.java
plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriAnalyzerProvider.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriPartOfSpeechStopFilterFactory.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriTokenizerFactory.java
server/src/main/java/org/opensearch/index/analysis/Analysis.java
server/src/main/java/org/opensearch/index/analysis/CustomMappingRuleParser.java
server/src/main/java/org/opensearch/index/analysis/MappingRule.java
server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
server/src/test/java/org/opensearch/index/analysis/AnalysisTests.java
server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
server/src/test/java/org/opensearch/indices/analyze/HunspellServiceTests.java

backport 6d20423 to 1.x
Add new parseWordList method that takes a parser as a parameter. It reads custom rules from settings or a file, parses and handles errors. Make error messages less verbose for rules files outside config directory.

[Backport 1.x] Fix error handling while reading analyzer mapping rules

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/HyphenationCompoundWordTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterGraphTokenFilterFactory.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/BaseWordDelimiterTokenFilterFactoryTestCase.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuCollationTokenFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiPartOfSpeechFilterFactory.java
plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiTokenizerFactory.java
plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriAnalyzerProvider.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriPartOfSpeechStopFilterFactory.java
plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriTokenizerFactory.java
server/src/main/java/org/opensearch/index/analysis/Analysis.java
server/src/main/java/org/opensearch/index/analysis/CustomMappingRuleParser.java
server/src/main/java/org/opensearch/index/analysis/MappingRule.java
server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
server/src/test/java/org/opensearch/index/analysis/AnalysisTests.java
server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
server/src/test/java/org/opensearch/indices/analyze/HunspellServiceTests.java

backport 6d20423 to 1.3
Add new parseWordList method that takes a parser as a parameter. It reads custom rules from settings or a file, parses and handles errors. Make error messages less verbose for rules files outside config directory.

[Backport 1.3] Fix error handling while reading analyzer mapping rules

---

plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiTokenizerFactory.java
plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java

Fix: raise error on malformed CSV.
This ships in 2.4, so no CHANGELOG needed.

Fix: raise error on malformed CSV.

---

CHANGELOG.md
build.gradle
distribution/src/config/jvm.options

Allow mmap to use new preview JDK-19 APIs in Apache Lucene 9.4+. When `--enable-preview` is not present:
```
[2022-11-08T14:03:56,502][WARN ][o.a.l.s.MMapDirectory    ] [runTask-0] You are running with Java 19. To make full use of MMapDirectory, please pass '--enable-preview' to the Java command line.
```
With `--enable-preview`:
```
[2022-11-08T14:10:36,009][INFO ][o.a.l.s.MemorySegmentIndexInputProvider] [runTask-0] Using MemorySegmentIndexInput with Java 19
```
Final part of https://github.com/opensearch-project/OpenSearch/issues/4637 …

Allow mmap to use new preview JDK-19 APIs in Apache Lucene 9.4+

---

server/src/test/java/org/opensearch/index/analysis/AnalysisTests.java

The test used an absolute path which is incorrect as it made a platform dependent assumption. This change fixes that.
Resolves #5156

Fix test to use a file from another temp directory

---

CHANGELOG.md
CONTRIBUTING.md

This also removes a Jackson dependency update from the changelog because it was backported all the way back to 2.4 so therefore is not unreleased here any more.

Backport CHANGELOG instructions from #5092

---

server/src/internalClusterTest/java/org/opensearch/clustermanager/ClusterManagerTaskThrottlingIT.java

Missed this one. It failed in https://github.com/opensearch-project/OpenSearch/pull/5153

Fix race condition in testThrottlingForSingleNode.

---

server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java

This updates the boundary condition in an assertion in two tests in ShardIndexingPressureConcurrentExecutionTests. I could reliably reproduce errors here by running:
```
./gradlew ':server:test' -Dtests.iters=10000 --tests "org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.testReplicaThreadedUpdateToShardLimits"
```
On every error the value that failed was exactly 0.95 and failed the less than check. The change here is to accept 0.95, and also refactor the test to give a better error message on failure.
Closes #2241
Closes #4215 …

Fix boundary condition in indexing pressure test

---

buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
gradle/runtime-jdk-provision.gradle

The internal plugin incorrectly assumes binaries for Windows (the issue was always present but only recently started to manifest itself because if https://github.com/gradle/gradle/commit/75eb1b77d03a2c83f4aaf7852f2b652daa945df9
Closes https://github.com/opensearch-project/OpenSearch/issues/5181

[BUG] Gradle Check Failed on Windows due to JDK19 pulling by gradle

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java

This change explicitly sets JVM options to  allow security manager.
Resolves #5193 

Add jvm option to allow security manager

---

server/src/test/java/org/opensearch/index/store/StoreTests.java

Backport of flaky test fix #4544 to 2.x.
https://github.com/opensearch-project/OpenSearch/issues/4859

[Backport 2.x] Ignore lock file when testing cleanupAndPreserveLatestCommitPoint (#4544)

---

buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java

This updates #5194 to check for JDK versions before setting the option.

Check for JDK version while setting java.security.manager option

---

server/build.gradle
server/src/main/java/org/opensearch/search/aggregations/metrics/HyperLogLogPlusPlus.java

The large data tables necessitating this exclusion were refactored away a long time ago.

Remove spotless exclusion for HyperLogLogPlusPlus

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RefreshVersionInClusterStateIT.java
server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/main/java/org/opensearch/transport/TransportService.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java

This change removes code that was written to support rolling upgrade from Elasticsearch 7.10.2 to OpenSearch 1.x, as part of PR #865

Remove changes for legacy mixed-cluster support

---

server/src/main/java/org/opensearch/index/mapper/AbstractPointGeometryFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/GeoPointFieldMapperTests.java

The change made in AbstractPointGeometryFieldMapper class with commit 050389736599e40c49278e900d5060f75b959282 introduced a performace degradation during point data indexing. Reverting it therefore.
The change is about consolidating array format parsing code for point type in a single place to acheive following benefits.
1. Allow plugins to override array parsing logic. Plugins can add its own parsing logic for point field by providing object parser. However, it cannot override array format. Therefore, plugin have to use whatever implemented in AbstractPointGeometryFieldMapper class.
2. Enhanced code quality by removing duplicated code
There is no change in functionality because 1. There is no change in functionality in OpenSearch and 2. No plugins have its own parsing logic for point …

Revert changes in AbstractPointGeometryFieldMapper

---

server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java

Few tests in AwarenessAttributeDecommissionIT fails transiently as while making the client request if a `viaNode` is not specified it uses a `RandomizingClient` which can let the request land up on a decommissioned node and then we see exception that cluster manager is not discovered which is not the case. This PR aims to always pick a active node to route the request. 
#5220
#5221 
#5189 

Fix AwarenessAttributeDecommissionIT flaky tests

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/util/FeatureFlags.java

Adds a feature flag for the functionality of extensions.
[3851](https://github.com/opensearch-project/opensearch/issues/3851)

Add feature flag for extensions

---

.github/workflows/gradle-check.yml

Display test failures in the gradle check status report. 
I tested this by hard-coding a few failed build URIs, so hopefully this doesn't break everything, but to actually open the PR we need a pull request target to work.

Display test failures in the gradle check status report.

---

buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java

This switch is removed in JDK version 17. JEP https://openjdk.org/jeps/403

Add condition to check JVM version for illegal-access switch

---

.github/workflows/gradle-check.yml

With the test-retry plugin we can get a successful result when tests fail but the succeed on a retry. This change ensures that the PR comment lists the flaky failures even when the overall run is a success.

Report test failures on 'flaky' success

---

CHANGELOG.md
test/framework/src/main/java/org/opensearch/test/rest/yaml/ClientYamlTestClient.java

The `sendBodyAsSourceParam` method determines whether it should send the body as a url parameter. It used to check the content length of the entity which in some cases (e.g. regex expression) is much shorter than the encoded-url and may result in a TooLongHttpLineException.
This commit makes an additional check on the length of the url-encoded string. To avoid unnecessary computation it is only checked when the RandomizedTest.rarely() returns true.
Resolves #4899 #5197 …

Fix test failing due to too long http line exception

---

test/framework/src/main/java/org/opensearch/test/rest/yaml/ClientYamlTestClient.java

[Backport 2.x] Fix test failing due to too long http line exception (#5278)

---

server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java

With #5252 we attempted to make client requests more deterministic by picking up a node which will not be decommissioned. In that PR we missed to make similar changes when instead of client we request the cluster service from the `internalCluster`.  This PR add changes which will always specify a activeNode before routing request.

Make viaNode more deterministic for AwarenessAttributeDecommissionIT tests

---

server/src/test/java/org/opensearch/search/aggregations/AggregationsTests.java

Based on the seed, the recursive `createTestInstance` method generates too many aggregations resulting in an exception. This change reduces the number of generated aggregations.
#4969

Fix flaky test AggregationsTests.testFromXContent

---

.github/workflows/gradle-check.yml

Don't display an empty section when no test failures. 
Screenshots from https://github.com/dblock/OpenSearch/pull/113.
The message about flaky tests that was added recently is incorrect. You can have legit test failures in this list, and some that were retried and still failed.

Prettify test failures.

---

CHANGELOG.md
buildSrc/src/integTest/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTarIT.java

[Backport 1.x] Skip SymbolicLinkPreservingTarIT when running on Windows.

---

CHANGELOG.md
buildSrc/src/integTest/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTarIT.java

[Backport 1.3] Skip SymbolicLinkPreservingTarIT when running on Windows

---

.github/workflows/gradle-check.yml

Missed this in https://github.com/opensearch-project/OpenSearch/pull/5290.

Fix test failures display.

---

server/src/main/java/org/opensearch/Version.java

Versions.java contains 2.x versions that are not released (https://opensearch.org/lines/2x.html ). The only unreleased versions must be the last major, last minor and current release's patch.
N/A

Remove invalid unreleased versions

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java
server/src/test/java/org/opensearch/action/bulk/BulkRequestParserTests.java

Reject bulk requests that contain invalid actions.
Resolves #5299 

Reject bulk requests with invalid actions

---

test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This fixes a race condition in segment replication specific test code where a CountDownLatch would complete before replication.  If the latch completes before the actual replication event the replica state is unpredictable.  This change removes the latch's wait limit of 1 second.
closes #5232

Fix flaky test testReplicaReceivesGenIncrease.

---

modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java
modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java

The randomly-generated input for this test may contain non-URL-safe characters (such as `%`) so it needs to be URL encoded as well.
Closes #5327

Fix URLDecodeProcessor random test failure

---

build.gradle

Retrying all tests by default is not great when developing tests. This behavior could be missed by a developer and result in new flakiness being introduced. This change will only enable retries when the "CI" environment variable is present.
I've tested this prevents retries in a dev environment, and I've tested that if I set the `CI` environment variable then it does retry, but I haven't actually tested it in the real Jenkins environment. However, the code here was copied straight from the retry plugin's README, and [this Jenkins page](https://build.ci.opensearch.org/env-vars.html/) does suggest that the environment variable is set. …

Retry tests only on CI server

---

CHANGELOG.md
server/src/main/java/org/opensearch/ExceptionsHelper.java
server/src/test/java/org/opensearch/rest/RestControllerTests.java

Changed http code on create index API with bad input raising NotXContentException to 400
#2756

Changed http code on create index API with bad input raising NotXContentException to 400

---

server/src/main/java/org/opensearch/Version.java

Update OpenSearch 2.5.0 version to Apache Lucene 9.4.2 (see please https://github.com/opensearch-project/OpenSearch/pull/5354)
N/A

Update OpenSearch 2.5.0 version to Apache Lucene 9.4.2

---

build.gradle

Use BuildParams.isCi() instead of checking env var

---

build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/5368 to `1.x`

[Backport] [1.x] Use BuildParams.isCi() instead of checking env var (#5368)

---

build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/5368 to `2.4`

[Backport] [2.4] Use BuildParams.isCi() instead of checking env var (#5368)

---

build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/5368 to `2.x`

[Backport] [2.x] Use BuildParams.isCi() instead of checking env var (#5368)

---

build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/5368 to `1.3`

[Backport] [1.3] Use BuildParams.isCi() instead of checking env var (#5368)

---

build.gradle

This dependency has been updated twice on main so manually updating it here.

[2.x] Bump test-retry from 1.3.2 to 1.4.1

---

server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java

This skips test `OnDemandBlockSnapshotIndexInputTests.testVariousBlockSize` when running on Windows.  See #5396 for more context.
related to https://github.com/opensearch-project/OpenSearch/issues/5396 and https://github.com/opensearch-project/OpenSearch/issues/1448

Skip Test OnDemandBlockSnapshotIndexInputTests.testVariousBlockSize on Windows.

---

server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

Fix IndexShardTests.testRestoreShardFromRemoteStore on Windows.
Windows has buggy File delete logic where AccessDeniedExceptions are thrown when there is an open file handle on a particular file. [FSDirectory](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/store/FSDirectory.java#LL344) attempts to resolve this with hacks by swallowing the exceptions and moving the file to a pending delete state to retry in the future while being filtered from listAll invocations.
However, this logic is also buggy and after the first delete attempt we are left in a state where the file is still on disk and not pending delete.  This is because FSDirectory#maybeDeletePendingFiles will execute and attempt to delete the …

Fix IndexShardTests.testRestoreShardFromRemoteStore on Windows.

---

CHANGELOG.md
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java
server/src/main/java/org/opensearch/tasks/TaskResultsService.java
server/src/main/resources/org/opensearch/tasks/task-index-mapping.json

When the new 'cancelled' field was introduced it was a miss not to increment the version number on the mapping definitions for the .tasks index. This commit fixes that oversight, as well as modifies the existing backward compatiblity test to ensure that it will catch future mistakes like this one.
Closes #5376

Fix 1.x compatibility bug with stored Tasks

---

CHANGELOG.md
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java
server/src/main/java/org/opensearch/tasks/TaskResultsService.java
server/src/main/resources/org/opensearch/tasks/task-index-mapping.json

When the new 'cancelled' field was introduced it was a miss not to increment the version number on the mapping definitions for the .tasks index. This commit fixes that oversight, as well as modifies the existing backward compatiblity test to ensure that it will catch future mistakes like this one.
Closes #5376

[Backport 2.x] Fix 1.x compatibility bug with stored Tasks (#5412)

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy

Failure on windows for the InternalDistributionArchiveSetupPluginFuncTest is unexpected. Fails with "registered distribution provides archives and directory variant".
This is because -
- tar task execution is skipped on windows.
- plain copy task execution doesn't execute on windows since source files will not be present.
To get the test passing again, we check for expected conditions on windows and non-windows machines.
Resolves #5324 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#deve …

Fix for windows failure InternalDistributionArchiveSetupPluginFuncTest

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy

Failure on windows for the InternalDistributionArchiveSetupPluginFuncTest is unexpected. Fails with "registered distribution provides archives and directory variant".
This is because -
tar task execution is skipped on windows.
plain copy task execution doesn't execute on windows since source files will not be present.
To get the test passing again, we check for expected conditions on windows and non-windows machines.
Resolves #5324 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develope …

Fix windows failure on InternalDistributionArchiveSetupPluginFuncTest

---

CHANGELOG.md
release-notes/opensearch.release-notes-1.3.7.md

Signed-off-by: owaiskazi19 <owaiskazi19@gmail.com>
Add release notes for patch release 1.3.7

Added release notes for 1.3.7

---

CHANGELOG.md
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java
server/src/main/java/org/opensearch/tasks/TaskResultsService.java
server/src/main/resources/org/opensearch/tasks/task-index-mapping.json

When the new 'cancelled' field was introduced it was a miss not to increment the version number on the mapping definitions for the .tasks index. This commit fixes that oversight, as well as modifies the existing backward compatiblity test to ensure that it will catch future mistakes like this one.
(cherry picked from commit 4616dfac5382062a5149c799554dda4ff601369f)

[Backport 2.4] Fix 1.x compatibility bug with stored Tasks (#5412)

---

server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java

This PR fixes flaky tests #4212 and #5157 by adding conditional/optional null check instead of compulsory null check. More details can be found in this [comment](https://github.com/opensearch-project/OpenSearch/issues/4212#issuecomment-1335798199)
Resolves #4212 and #5157

Fix Flaky Tests testReplicaThreadedUpdateToShardLimitsAndRejections  and testCoordinatingPrimaryThreadedUpdateToShardLimitsAndRejections

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/query/QueryStringIT.java
server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
server/src/main/java/org/opensearch/index/mapper/StringFieldType.java
server/src/main/java/org/opensearch/index/search/QueryStringQueryParser.java
server/src/test/java/org/opensearch/index/query/PrefixQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java

Fixes the `wildcard` query to not normalize the pattern when `case_insensitive` is set by the user. This is achieved by creating a new normalizedWildcardQuery method so that query_string queries (which do not support case sensitivity) can still normalize the pattern when the default analyzer is used; maintaining existing behavior.
closes #5461

[Bug] fix case sensitivity for wildcard queries

---

CHANGELOG.md
modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4NioServerSocketChannel.java
modules/transport-netty4/src/main/java/org/opensearch/transport/NettyAllocator.java
server/src/main/java/org/opensearch/common/bytes/BytesReference.java
server/src/test/java/org/opensearch/common/bytes/ByteBuffersBytesReferenceTests.java

The issue(s) came out of https://github.com/opensearch-project/security/issues/2208 and basically revealed that `Netty4Transport` does not work with default Netty allocator, because:
- default Netty allocator prefers `DirectByteBuffer`s and `BytesReference` does not support that 
- the `NettyAllocator::getServerChannelType` does not return the `ServerChannel` type which works with `ServerChannelInitializer` that expects instance of `Netty4NioSocketChannel`.
Closes https://github.com/opensearch-project/security/issues/2208 …

Support OpenSSL Provider with default Netty allocator

---

scripts/build.sh

This reverts commit 8c9ca4e858e6333265080972cf57809dbc086208.
It seems that this wasn't entirely the correct way and is currently blocking us from removing the `build.sh` from the `opensearch-build` repository (i.e. this `build.sh` here is not yet being used). See the discussion in opensearch-project/opensearch-build#2835 for further details.
n/a

[backport 2.4] Revert "build no-jdk distributions as part of release build (#4902)"

---

scripts/build.sh

This reverts commit 8c9ca4e858e6333265080972cf57809dbc086208.
It seems that this wasn't entirely the correct way and is currently blocking us from removing the `build.sh` from the `opensearch-build` repository (i.e. this `build.sh` here is not yet being used). See the discussion in opensearch-project/opensearch-build#2835 for further details.
n/a

Revert "build no-jdk distributions as part of release build (#4902)"

---

scripts/build.sh

This reverts commit 8c9ca4e858e6333265080972cf57809dbc086208.
It seems that this wasn't entirely the correct way and is currently blocking us from removing the `build.sh` from the `opensearch-build` repository (i.e. this `build.sh` here is not yet being used). See the discussion in opensearch-project/opensearch-build#2835 for further details.
n/a

[backport 2.x] Revert "build no-jdk distributions as part of release build (#4902)"

---

CHANGELOG.md
client/rest-high-level/src/main/java/org/opensearch/client/indices/ResizeRequest.java
client/rest-high-level/src/test/java/org/opensearch/client/IndicesRequestConvertersTests.java
rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/40_max_shard_size.yml
server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/ShrinkIndexIT.java
server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
server/src/test/java/org/opensearch/action/admin/indices/shrink/TransportResizeActionTests.java

Backport [953a3d](https://github.com/opensearch-project/OpenSearch/commit/953a3d6851632c9b09c8dc15dbff02c8aafac6c1) from #5229 

[Backport 2.x] Add max_shard_size parameter for Shrink API

---

.github/CODEOWNERS
MAINTAINERS.md

- List CODEOWNERS to match MAINTAINERS to match security permissions in this repo.
- Removed @opensearch-project/opensearch-core from maintainer which had 21 people in it.
- Moved @abbashus to emeritus as he moved on from the org.

Sync CODEOWNERS with MAINTAINERS.

---

server/src/internalClusterTest/java/org/opensearch/action/bulk/BulkIntegrationIT.java

The test BulkIntegrationIT.testDeleteIndexWhileIndexing is failing intermittently whenever a thread that's indexing documents does not terminate in the timeout interval provided by the join method and is still alive failing an assertion (seen in the stacktrace of the linked issue). 
9 failures were seen in the last 2 months: (3607,3757,3789,3839,4952,6624,6635,6723,6979)
Resolves #5162 

Fix flaky test BulkIntegrationIT.testDeleteIndexWhileIndexing

---

CHANGELOG.md
modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4NioServerSocketChannel.java
modules/transport-netty4/src/main/java/org/opensearch/transport/NettyAllocator.java
server/src/main/java/org/opensearch/common/bytes/BytesReference.java
server/src/test/java/org/opensearch/common/bytes/ByteBuffersBytesReferenceTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/5460 to `2.4`

[Backport] [2.4] Support OpenSSL Provider with default Netty allocator (#5460)

---

CHANGELOG.md
modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4NioServerSocketChannel.java
modules/transport-netty4/src/main/java/org/opensearch/transport/NettyAllocator.java
server/src/main/java/org/opensearch/common/bytes/BytesReference.java
server/src/test/java/org/opensearch/common/bytes/ByteBuffersBytesReferenceTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/5460 to `2.x`

[Backport] [2.x] Support OpenSSL Provider with default Netty allocator (#5460)

---

release-notes/opensearch.release-notes-2.4.1.md

Add release notes for version 2.4.1

Add release notes for 2.4.1

---

server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java

PR https://github.com/opensearch-project/OpenSearch/pull/5397 skipped this test in @Before block but still frequently throws a TestCouldNotBeSkippedException - CI run https://build.ci.opensearch.org/job/gradle-check/7840/testReport/junit/org.opensearch.index.store.remote.file/OnDemandBlockSnapshotIndexInputTests/testVariousBlockSize/.  This is caused by the after block still executing and throwing  an exception while cleaning the directory created at the path in @Before.  Moving the assumption to the individual test prevents this exception by ensuring the path exists.
Validated manually on Windows 10.
related https://github.com/opensearch-project/OpenSearch/issues/5396 …

Properly skip OnDemandBlockSnapshotIndexInputTests.testVariousBlockSize on Windows

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java

This PR Backports #5332 
Resolves #5313 

[Backport 2.x] [Segment Replication] Trigger a round of replication for replica shards during peer recovery when segment replication is enabled

---

server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
server/src/main/java/org/opensearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/configuration/TransportClearVotingConfigExclusionsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/configuration/VotingConfigExclusionsHelper.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionHelper.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
server/src/test/java/org/opensearch/action/admin/cluster/configuration/VotingConfigExclusionsHelperTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionHelperTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java

…nding action (#5093)
* Atomically update the cluster state with decommission status and its corresponding action in the same execute call
Backport - https://github.com/opensearch-project/OpenSearch/pull/5093

[Backport-2.x]Atomically update cluster state with decommission status and corresponding action

---

CHANGELOG.md
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequest.java
server/src/main/java/org/opensearch/cluster/routing/UnsupportedWeightedRoutingStateException.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingService.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java
server/src/test/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequestTests.java
server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java

Pre conditions check to allow weight updates for non decommissioned attribute
Backport https://github.com/opensearch-project/OpenSearch/pull/4955

[Backport-2.x]Pre conditions check before updating weighted routing metadata (#4955)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/query/MultiMatchQueryIT.java
server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
server/src/main/java/org/opensearch/common/unit/Fuzziness.java
server/src/main/java/org/opensearch/index/query/MatchBoolPrefixQueryBuilder.java
server/src/main/java/org/opensearch/index/query/MatchQueryBuilder.java
server/src/main/java/org/opensearch/index/query/MultiMatchQueryBuilder.java
server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java
server/src/test/java/org/opensearch/common/unit/FuzzinessTests.java
server/src/test/java/org/opensearch/index/query/MatchBoolPrefixQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/MatchQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java

Refactor fuzziness interface on query builders (#5433)
(cherry picked from commit d3f6dfab89720df155ee9cb4789aa642c2238057)
Signed-off-by: noCharger <lingzhichu.clz@gmail.com>
[Backport-2.x] Refactor fuzziness interface on query builders (#5433)

[Backport-2.x] Refactor fuzziness interface on query builders (#5433)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

- As part of [remote store feature](https://opensearch.org/docs/latest/opensearch/remote) that was introduced in OpenSearch 2.3, segments are uploaded to remote store post each refresh. 
- This means remote segment store contains segments that were part of last refresh.
- But the `_remotestore/_restore` API only supports commit level durability.
- This feature will add refresh level durability support to the restore API.
- We upload `SegmentInfosSnapshot` during each refresh and keep the information of the uploaded file in the metadata file.
- During restore, if `SegmentInfosSnapshot` is present, we use it as a `SegmentInfos` file and trigger a commit.
- As the snapshot file does not contain latest processed checkpoint (as it is a snapshot of previous `SegmentInfos` file), we pass …

[Remote Store] Add support for refresh level durability

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
server/src/main/java/org/opensearch/cluster/service/MasterService.java
server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java

Signed-off-by: Dhwanil Patel <dhwanip@amazon.com>
Backporting of minor bug fix of cluster manager throttling settings.
Original PR: #5524 
#479 

[Backport 2.x] Minor bug fix related to cluster manager throttling settings

---

CHANGELOG.md
TESTING.md
buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Backport fe8fd67884160e346def8c8503d09fb4b5eb5363 from #5348.

[Backport 2.4] Add CI bundle pattern to distribution download

---

server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java

Signed-off-by: Dhwanil Patel <dhwanip@amazon.com>
Cluster manager throttling is releasing with 2.5 version, earlier it was planned to release with 2.4 version so we had 2.4 version check for throttling threshold settings.
Changing this version check to 2.5 version.
#479 

Change version check for cluster manager throttling setting to 2.5

---

release-notes/opensearch.release-notes-2.4.0.md

There were two changes to the 2.4.0 release notes file that were made on the 2.4 branch that were not included in the release notes file on main. This commit was made using the following command:
```
git checkout upstream/2.4 release-notes/opensearch.release-notes-2.4.0.md
```

Reconcile 2.4.0 release notes

---

server/src/main/java/org/opensearch/common/blobstore/fs/FsBlobStore.java
server/src/main/java/org/opensearch/common/io/stream/BytesStreamInput.java
server/src/main/java/org/opensearch/index/translog/BufferedChecksumStreamInput.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/LocalTranslog.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/Translog.java
server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
server/src/test/java/org/opensearch/index/translog/TestTranslog.java
server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

This is the first PR for remote translog support in OpenSearch . 
The scope of the PR is just uploading translog files - tlog and ckp .  
https://github.com/opensearch-project/OpenSearch/issues/5477

[Remote Translog] Introduce remote translog with upload functionality

---

CHANGELOG.md
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java

Signed-off-by: Dhwanil Patel <dhwanip@amazon.com>
* Changed version of the ClusterManagerThrottlingException.
* BWC for thresholds set via static setting
When throttling threshold setting is set via static setting (yml) file, it can be updated and feature can throttle the task even when older nodes are present in cluster.
Added check on task submission of configured task for throttling to check for version check. If older nodes are present, it will not perform throttling to provide backward compatibility. 
Once all nodes are higher than 2.5.0, it will start throttling based on threshold and wont be disabled again.
#479 
For more information on following Developer Certificate …

Add version check during task submission for bwc for static threshold setting

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/gateway/QuorumGatewayIT.java

Signed-off-by: Joshua Palis <jpalis@amazon.com>
`testQuorumRecovery` is a flaky test that is not reproducible. The test performs a restart upgrade on a 3 node cluster and confirms that the cluster health recovers, using a 30-second timeout. The instances for which this test failed are due to exceeding this time limit. Since this may be just a transient error, increasing the timeout to 90 seconds.  
https://github.com/opensearch-project/OpenSearch/issues/1908
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …

Increasing timeout of testQuorumRecovery to 90 seconds from 30

---

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/20_terms.yml

The "string profiler via global ordinals" rest test assumes all documents are in the same segment.  The four commits occasionally are entered into multiple segments.  PR #2226 by @penghuo attempted to fix this using a force merge, which reduced the frequency of these failures but did not eliminate them (reproduced once in 1000 runs).
Setting the `flush` boolean to `true` in this force merge completely resolves these failures (no repro in 2000 runs).
Fixes #1817
Improves fix of #2176
~- [ ] New functionality includes testing.~
~- [ ] All tests pass~
~- [ ] Commit changes are listed out in CHANGELOG.md file (See: …

Fix flaky test case - string profiler via global ordinals

---

CHANGELOG.md
test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java

The `BootstrapForTesting` class can read the value of an optional `tests.config` system property.  If this property is not set, it returns null.
While there is already a null check, the property is fetched again from the JDK.  If any other test is manipulating this property in the same JVM it could return a different result.  See at least two rare failures:
- [#1096 (comment)](https://github.com/opensearch-project/OpenSearch/pull/1096#issuecomment-1018841935)
- [#2726 (comment)](https://github.com/opensearch-project/OpenSearch/pull/2726#issuecomment-1086957605) 
This change makes the null check more robust to any other property manipulation in the JVM.
Fixes #2893
~- [ ] New functionality includes testing.~
~- [ ] All tests pass~
~- [ ] New …

Improve tests.config property thread safety

---

server/src/test/java/org/opensearch/search/PitMultiNodeTests.java

#4030 introduced a Point In Time Node Stats API and added stats validation to many PitMultiNodeTests.
Thorough debugging of flaky `testCreatePitWhileNodeDropWithAllowPartialCreationFalse()` revealed that the transLog consistently had a pending commit when the test failed (repro 1/500 runs)
Flushing the index prior to collecting/validating stats resolves this failure (tested 1000 runs) and probably prevents other flaky test results.
_Flushing frequently should be considered a best practice for test hygiene._
Fixes #4259 (which was previously closed associated with an unrelated fix).
Fixes comments https://github.com/opensearch-project/OpenSearch/issues/4089#issuecomment-1311129076 although the issue itself was fixed by a different PR.
By …

Fix flaky PitMultiNodeTests including testCreatePitWhileNodeDropWithAllowPartialCreationFalse

---

server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java

[`Thread.sleep()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#sleep(long)) does not sleep for precise amounts:
> Causes the currently executing thread to sleep (temporarily cease execution) for the specified number of milliseconds, **subject to the precision and accuracy of system timers and schedulers**.
Tests in the `SearchCancellationIT` class relied on sleeping for exactly the cancellation timeout, which creates potential race conditions and occasional test failures.
This PR adds an extra 100ms of sleep time before checking the cancellation status.
Fixes #2242 
Fixes #2311
Fixes #2763 …

Fix flaky SearchCancellationIT tests to avoid race condition

---

CHANGELOG.md

Removing the CHANGELOG entry for unreleased changes.
Follow up on https://github.com/opensearch-project/OpenSearch/pull/5642#pullrequestreview-1232051240

Removing the CHANGELOG entry for unreleased changes

---

CHANGELOG.md
MAINTAINERS.md

I nominated Gaurav Bafna (@gbbafna) to be a co-maintainer for Opensearch through our [nomination process](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#nomination). The maintainers have agreed, and Gaurav has kindly accepted.
Gaurav is the [lead](https://github.com/opensearch-project/cross-cluster-replication/pulls?page=1&q=is%3Apr+gbbafna) author and maintainer of [Cross Cluster Replication Feature](https://github.com/opensearch-project/cross-cluster-replication) and reviewed/approved significant core contributions like Zonal decommissioning, Weighted shard routing, Master Task Throttling and Remote Store. He personally has also contributed [5 PRs](https://github.com/opensearch-project/OpenSearch/pulls/gbbafna) …

Adding @gbbafna to OpenSearch maintainers

---

server/src/test/java/org/opensearch/index/IndexServiceTests.java

This PR fixes flaky test  org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex by increasing the translog retention check interval.
Resolves #5414 

Fix Flaky test org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex

---

CHANGELOG.md
buildSrc/build.gradle

[Backport 2.x] Bump apache-rat from 0.13 to 0.15

---

CHANGELOG.md

This PR adds Dependency Upgrade changes to CHANGELOG.md for following PR's: #5600, #5675, #5676.

Add Dependecy upgrades changes in changelog.md

---

server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequest.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingService.java
server/src/test/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequestTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java

This PR aims to change following things in Routing Weights API and Decommission Action - 
1. Consider only routing node's attribute for validation instead of all nodes
2. Ensure no more than 50% node has weight zero
3. Removal of decommission action's direct dependence on force zone awareness

Validate attributes of routing nodes for Routing Weights API

---

CHANGELOG.md
MAINTAINERS.md

* Adding @gbbafna to Opensearch maintainers

[Backport 2.x] Adding @gbbafna to OpenSearch maintainers (#5668)

---

server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequest.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingService.java
server/src/test/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequestTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java

[Backport 2.x] Validate attributes of routing nodes for Routing Weights API

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

- Add support to download `.tlg` and `.ckp` files from remote translog.
- Also integrated the download flow with restore API.

[Remote Translog] Add support for downloading files from remote translog

---

qa/remote-clusters/src/test/java/org/opensearch/cluster/remote/test/RemoteClustersIT.java

The current logging is not sufficient to fix flaky test failures for `testHAProxyModeConnectionWorks` . The failure occurs due to the number of connected sockets being 0.  However, the `RemoteConnectionInfo` containing this data is obtained through a transport request, so the cause of the sockets not connecting is unknown.  Since the error is non-reproducible, this PR adds additional logging when there are no connected sockets, printing out the cluster health at the time of failure.  If the flaky test failure occurs again, there will be more logged information that can hopefully lead to a solution. …

Add additional logging for future debugging of HA proxy mode flaky test

---

CHANGELOG.md
distribution/src/config/opensearch.yml
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/main/java/org/opensearch/common/util/FeatureFlags.java
server/src/main/java/org/opensearch/node/Node.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

This change introduces a static store "settings"
in FeatureFlags.java file to enable the isEnabled method to fetch flag settings defined in opensearch.yml.
This PR addresses issue #4102, wherein, it allows FeatureFlags to be fetched from opensearch.yml and not from the environment variable or system property.
[#4102]

Added support for feature flags in opensearch.yml

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java

https://github.com/opensearch-project/OpenSearch/pull/4959 started triggering SR tests with each gradle check.  Muting tests that have already been flagged as flaky - tracking here: https://github.com/opensearch-project/OpenSearch/issues/5669. 

Muting flaky SegmentReplication ITs.

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/DiscoveryExtensionNode.java
server/src/main/java/org/opensearch/extensions/ExtensionDependencyResponse.java
server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java

Signed-off-by: Frank Lou <mloufra@amazon.com>
Create a feature to have an extension query to OpenSearch to obtain a list of initialized extensions and determine whether a particular extension is initialized.
Equivalent PR on OpenSearch-sdk-java : https://github.com/opensearch-project/opensearch-sdk-java/pull/300 
fixes https://github.com/opensearch-project/opensearch-sdk-java/issues/149

[Extensions]Add query for initialized extensions

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

Mutes flaky test SegmentReplicationIT.testStartReplicaAfterPrimaryIndexesDocs.  Similar to https://github.com/opensearch-project/OpenSearch/pull/5700, this test was recently enabled as part of check and introduced flakiness.
check failure on PR: https://github.com/opensearch-project/OpenSearch/pull/5704#issuecomment-1372301014

Mute flaky test testStartReplicaAfterPrimaryIndexesDocs.

---

CHANGELOG.md
buildSrc/build.gradle
buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
distribution/archives/integ-test-zip/build.gradle
modules/build.gradle
server/build.gradle

Update nebula-publishing-plugin to 19.2.0
Closes https://github.com/opensearch-project/OpenSearch/issues/5702

Update nebula-publishing-plugin to 19.2.0

---

server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java

Existing gradle checks failures([example](https://github.com/opensearch-project/OpenSearch/pull/5722)),  are happening due to recent change from PR https://github.com/opensearch-project/OpenSearch/pull/5610, which overrides older ClusterService state and does not consider previously added DiscoveryNodes nodes [added here](https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/test/ClusterServiceUtils.java#L176) into consideration while rebuilding clusterService state. These local nodes are used in tests. This change takes existing discovery nodes for building the cluster state. 
NA …

Fix TransportReplicationActionTests

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java

Revealed in https://github.com/opensearch-project/OpenSearch/pull/5737, muting flaky test. 
NA

[Segment Replication] Mute flaky tests

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

Fix flaky SegmentReplicationIT test testStartReplicaAfterPrimaryIndexesDocs.
This test was failing because we are validating post recovery if a shard is able to perform segrep while also performing validation of a passed in checkopint.  In the post recovery scenario this checkpoint is passed as empty, yet the shard will be ahead of this empty checkpoint after docs are indexed and fail validation.  This change differentiates shard validation from checkpoint validation and only performs the former post recovery.
This PR also introduces validation of the engine type before SR is invoked.  This is to ensure NRTReplicationEngine is properly loaded on the replica.  Without this SR would continue and blow up at a later stage with an index …

Fix flaky Segment Replication test testStartReplicaAfterPrimaryIndexesDocs.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/get/ClusterGetWeightedRoutingResponse.java
server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/get/TransportGetWeightedRoutingAction.java
server/src/test/java/org/opensearch/cluster/action/shard/routing/weighted/get/ClusterGetWeightedRoutingResponseTests.java
server/src/test/java/org/opensearch/cluster/action/shard/routing/weighted/get/TransportGetWeightedRoutingActionTests.java

The local weights don't add much value since weights are relative and having just the local value gives no indication of how traffic would get distributed.
Discovered master is helpful to understand cases where after weights are set and also that the node is unable to connect to the leader either due to
Master not discovered -- This might happen to newly launched after decommission or even otherwise
Decommissioned -- The node was decommissioned …

[Weighted Routing] Add support for discovered master and remove local weights in the response

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/pit/DeletePitMultiNodeIT.java
server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java

We get intermittent failures where 'RestCancellableNodeClient' channels are left behind by rest tests and the PIT integration tests fail.
Renaming tests to IT will make sure they're run in separate JVM where the number of channels are 0.
Signed-off-by: Bharathwaj G <bharath78910@gmail.com>
This PR fixes intermittent test failures

[Test] Renaming PIT tests to IT to fix intermittent test failures

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This PR combines following PRs in order to backport to 2.x
- https://github.com/opensearch-project/OpenSearch/pull/5253
- https://github.com/opensearch-project/OpenSearch/pull/5579
- https://github.com/opensearch-project/OpenSearch/issues/5251
- https://github.com/opensearch-project/OpenSearch/issues/4578

[Backport 2.x] Add support for refresh level durability using remote segment store

---

.github/CODEOWNERS

[Backport 2.x] Adding @gbbafna to code owners (#5695)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

- Backports https://github.com/opensearch-project/OpenSearch/pull/5749

[Backport 2.5] Add support for refresh level durability

---

release-notes/opensearch.release-notes-2.4.0.md

Adds CVE-2022-41917 to the release notes for 2.4.0.
N/A

Updated the release notes to include the fix for CVE-2022-41917.

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/translog/BufferedChecksumStreamInput.java
server/src/main/java/org/opensearch/index/translog/Checkpoint.java
server/src/main/java/org/opensearch/index/translog/TranslogReader.java
server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/FileTransferException.java
server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TransferSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/package-info.java
server/src/main/java/org/opensearch/index/translog/transfer/package-info.java
server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

* Introduce remote translog transfer support
- Backports https://github.com/opensearch-project/OpenSearch/pull/4480

[Backport 2.5] [Remote Translog] Introduce remote translog transfer support (#4480)

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/Translog.java
server/src/main/java/org/opensearch/index/translog/TranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

After any segment uploaded to remote store , we will update `minSeqNoRequired` for `Translog`.  This is implemented only for `RemoteFSTranslog` . 
`minSeqNoRequired` will be used to preserve generations to be trimmed till it is uploaded to remote store. 
Once uploaded , post trimming, remote translog will be cleaned up as well along with local tlog files. 
https://github.com/opensearch-project/OpenSearch/issues/5567
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of- …

[Remote Translog] Trimming based on remote segment upload and cleaning older tlog files 

---

server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java

- RemoteFSTranslogTests.testConcurrentWriteViewsAndSnapshot fails if number of operations are very high.
- As this test picks random number of operations, if the number is high, test fails and if it is low, test passes.
- To avoid this flakiness, this change reduce the range of number of operations.
- https://build.ci.opensearch.org/job/gradle-check/9162/testReport/junit/org.opensearch.index.translog/RemoteFSTranslogTests/testConcurrentWriteViewsAndSnapshot/
- This is not a proper solution though. With buffering and garbage collection (https://github.com/opensearch-project/OpenSearch/pull/5662) in place, we should not see this problem. …

[Remote Translog] Reduce number of operations in testConcurrentWriteViewsAndSnapshot

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequestBuilder.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionHelper.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionHelperTests.java
server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataSerializationTests.java
server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataTests.java
server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataXContentTests.java
server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java

* Control concurrency and handle retries during decommissioning of awareness attributes
Backport #5542 

[Backport 2.x] Gracefully handle concurrent zone decommission action (#5542)

---

server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java

As part of https://github.com/opensearch-project/OpenSearch/pull/5282, we introduced a boolean flag in CheckpointState class inside ReplicationTracker. Consider the case when bwc tests ran in 2.x branch. 
This fails on `2.x` because `Version.CURRENT` in `in.getVersion().onOrAfter(Version.CURRENT)` returns 2.5.0 (2.5 Current is `2.5.0` and 2.x has `2.6.0`) which means it always goes in `else` condition. BUT, the write to outputstream is unconditional which means the minor version (2.5.0 already containing https://github.com/opensearch-project/OpenSearch/pull/5282 change) does write it to output stream. The correct fix here is:
1. Replace Version.CURRENT with specific version. Version.CURRENT changes with branch.
2. Update output stream write to be conditional so that it writes only when it …

[Bug] Send replicated boolean on supported versions

---

server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java

As part of https://github.com/opensearch-project/OpenSearch/pull/5282, we introduced a boolean flag in `CheckpointState` inside ReplicationTracker with incorrect serialization/deserialization logic. 
The bwc tests (using on `CheckpointState` for transport communication e.g. RecoveryHandoffPrimaryContextRequest) fails on `2.x` because of `in.getVersion().onOrAfter(Version.CURRENT) (2.5.0) < Version.Current (2.6.0)`; resulting in `else` block execution. BUT, the write to outputstream is unconditional which means the minor version (2.5.0 containing https://github.com/opensearch-project/OpenSearch/pull/5282 change) writes to output stream. 
The correct fix here is:
1. Replace Version.CURRENT with specific version. Version.CURRENT changes with branch.
2. Update output stream write to be …

[Bug] Update logic on CheckpointState around serialization/deserialization

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.5.0.md

- Add release notes for v2.5.0
- N/A

Add v2.5.0 release notes

---

server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java

Coming from https://github.com/opensearch-project/OpenSearch/pull/5811, the test is failing because of recent change where additional field was added in ClusterHealthResponse https://github.com/opensearch-project/OpenSearch/pull/5788. This also needs changes in the unit test which generates random version above 1.0.0 and fails when generated version >= `2.5.0`
The test fails due to [extra byte](https://github.com/opensearch-project/OpenSearch/blob/2.x/server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java#L411) written into the output stream though [assertion](https://github.com/opensearch-project/OpenSearch/blob/2.5/server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java#L199) doesn't takes that into …

[Bug] Update test to consider OS version > 2.5.0 where extra field added into BytesStreamOutput

---

IDENTITY_USE_CASES.md

Adding details uses cases for identity, this is going to get long!

[Feature/Identity] Identity use cases

---

CHANGELOG.md
sandbox/modules/identity/src/internalClusterTest/java/org/opensearch/identity/HttpSmokeTestCaseWithIdentity.java
sandbox/modules/identity/src/internalClusterTest/java/org/opensearch/identity/SecurityPluginCompatibilityIT.java
sandbox/modules/identity/src/internalClusterTest/java/org/opensearch/identity/UserPersistenceIT.java
server/src/main/java/org/opensearch/action/ActionModule.java
server/src/main/java/org/opensearch/rest/RestController.java
server/src/test/java/org/opensearch/rest/RestControllerTests.java

The identity module uses the same `getRestHandlerWrapper` extension point as the security plugin to wrap rest requests and perform authentication. Currently, there is a limit of one wrapper to ensure that only the security plugin uses the extension point. This PR increases it to 2 and merges the list of wrappers together to perform as one when applying.

[Feature/Identity] Ensure compatibility with Security Plugin by accepting up to two rest handler wrappers

---

CHANGELOG.md

- Updates changelog for 2.x post 2.5.0 release
- N/A

Update changelog for 2.x post release

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
server/src/main/java/org/opensearch/cluster/service/ClusterManagerThrottlingStats.java
server/src/main/java/org/opensearch/cluster/service/MasterService.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
server/src/test/java/org/opensearch/cluster/service/ClusterManagerThrottlingStatsTests.java
test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

Backport throttling stats PR to 2.x.
Original PR : https://github.com/opensearch-project/OpenSearch/pull/5790/commits
#479 

[Backport 2.x] Add cluster manager throttling task stats in nodes stats API

---

server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java
server/src/test/java/org/opensearch/index/translog/transfer/FileSnapshotTests.java

- Currently, we use [Channels.newInputStream](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java#L70) while uploading translog files.
- But as per the documentation of [method](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/channels/Channels.html#newInputStream(java.nio.channels.AsynchronousByteChannel)), it does not support mark and reset methods of InputStream.
- This creates issues during upload of the translog files, if upload fails and remote store client tries to retry the upload, it fails as resetting the stream is not possible.
- Solution is to pass InputStream that supports mark and reset while uploading the translog and checkpoint files.
- …

[Remote Translog] Use InputStream that supports mark and reset while uploading translog files

---

server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java

Signed-off-by: Mani <singh.mani1231@gmail.com>
Removed unnecessary use of Long.toString from BlobStoreRepository.

Removed unnecessary use of Long.toString from BlobStoreRepository.

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/search/MatchQuery.java
server/src/test/java/org/opensearch/index/query/MatchQueryBuilderTests.java

Manual create backport 1.x PR due to merge conflict at [#5665](https://github.com/opensearch-project/OpenSearch/pull/5665)
* fix graph filter out of bound error
Signed-off-by: Mingshi Liu <mingshl@amazon.com>
* add changelog
Signed-off-by: Mingshi Liu <mingshl@amazon.com>
Signed-off-by: Mingshi Liu <mingshl@amazon.com>
(cherry picked from commit 6a7a9a1b2472f8d4a496d5b976ae16be87893b0e) …

[Backport 1.x]Fix Graph Filter Error in Search (#5665)

---

server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java

Solves #5795 & #5844.
Solves #5795 & #5844

Handle translog upload during primary relocation for remote-backed indexes

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
server/src/main/java/org/opensearch/cluster/routing/PreferenceBasedSearchNotAllowedException.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java

Disallow search requests with preference parameter in case of strict weighted routing
https://github.com/opensearch-project/OpenSearch/issues/5873

Disallow search request with preference parameter when weighted routing enabled

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/DiscoveryExtensionNode.java
server/src/main/java/org/opensearch/extensions/ExtensionDependencyResponse.java
server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java

Create a feature to have an extension query to OpenSearch to obtain a list of initialized extensions and determine whether a particular extension is initialized.
Equivalent PR on OpenSearch-sdk-java : https://github.com/opensearch-project/opensearch-sdk-java/pull/300 
Backport of https://github.com/opensearch-project/OpenSearch/pull/5658
fixes https://github.com/opensearch-project/opensearch-sdk-java/issues/149

[Backport 2.x] Add query for initialized extensions

---

server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/test/java/org/opensearch/repositories/IndexMetadataGenerationsTests.java

This PR backports two small improvements in #5812 to the `2.x` branch:
* Unit tests for `IndexMetadataGenerations`
* Fixes the javadoc of `IndexSettings#getExtendedCompatibilitySnapshotVersion` to correctly note that the default return value is not null.
N/A

Backporting unit tests for IndexMetadataGenerations and a javadoc fix from #5812

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

Mutes `SegmentReplicationIT.testCancelPrimaryAllocation` flaky test. 
NA

[Segment Replication] Mute flaky SegmentReplicationIT.testCancelPrimaryAllocation

---

server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java

This PR fixes strict weighted routing integration test
```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.search.SearchWeightedRoutingIT.testPreferenceSearchWithWeightedRouting" -Dtests.seed=2211E75A1B84F237 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ar-AE -Dtests.timezone=Indian/Mahe -Druntime.java=19
2> java.lang.IllegalArgumentException: no data nodes with criteria [node_t1] found for shard: [test][6]
at __randomizedtesting.SeedInfo.seed([2211E75A1B84F237:FB5601FF9ED37C9F]:0)
at org.opensearch.cluster.routing.IndexShardRoutingTable.onlyNodeSelectorActiveInitializingShardsIt(IndexShardRoutingTable.java:606)
at …
```

Fix strict weighted routing integ test failure

---

.gitignore

Add artifacts from benchmarks to .gitignore, I keep seeing files under the ./benchmarks/bin and ./benchmarks/build-eclipse-default folders which look like they are associated with a pre-processing annotation.
<details><summary>Detailed list of files that were not ignored</summary>
<p>
```
% git status -uall                                                                                                                                                                             ~/git/opensearch
On branch core-identity
Untracked files:
(use "git add <file>..." to include in what will be committed)
benchmarks/bin/generated-sources/annotations/org/opensearch/benchmark/time/jmh_generated/DateFormatterFromBenchmark_benchmarkFrom_jmhTest.java …
```

Add artifacts from benchmarks to .gitignore

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java

Previously this test required the feature flag to be set as a system property, otherwise the test did nothing. This change programmatically sets the feature flag to allow the test to run during all builds. I ran the following command overnight (probably at least a couple thousand iterations) on a dev machine and saw no failures, so I have confidence this test is not flaky:
```
run-one-until-failure ./gradlew ':server:internalClusterTest' --tests "org.opensearch.snapshots.SearchableSnapshotIT"
```
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBU …

Enable SearchableSnapshotIT to run during build

---

CHANGELOG.md
distribution/src/config/opensearch.yml
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/main/java/org/opensearch/common/util/FeatureFlags.java
server/src/main/java/org/opensearch/node/Node.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Backport https://github.com/opensearch-project/OpenSearch/commit/241bd42ab4d0bff0c6d232df0076d2568e326667 from #4958

[Backport 2.x] Added support for feature flags in opensearch.yml (#4959)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

This commit applies any feature flags specified by a child class override of the featureFlagSettings() method by default. The result is that test implementations do not have to manually specify the featureFlagSettings when creating test nodes.
@dreamer-89 @mch2 Does this make sense?

Apply OpenSearchIntegTestCase::featureFlagSettings by default

---

CHANGELOG.md

The `[Unreleased 3.0]` section of the CHANGELOG on main had lots of entries for items that were backported and released in 2.5. This commit attempts to fix all these issues so that the `[Unreleased 3.0]` section only contains items that have not been backported.

Fix CHANGELOG on main

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This PR backports 6 segrep PRs from main missing from 2.x and resolves conflicts. See commits for each PR - all of these are test muting other than [Fix flaky Segment Replication test testStartReplicaAfterPrimaryIndexe…](https://github.com/opensearch-project/OpenSearch/commit/93ea33738fb5d00594412501fe1ccf1ac4ec7e38).
There are a few PRs still missing backport that are larger and should go separately:
https://github.com/opensearch-project/OpenSearch/commit/44aabe9bb57e33716fbafcc81d29c5385a55f34f - remote xlog
https://github.com/opensearch-project/OpenSearch/commit/d56965c59636b18450a48378668f6e2f0f0529e9

[Backport 2.x] Backport SegmentReplication test muting missing from 2.x.

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Backport 7a511dd9ac7989d27d0b4aa7a0b0bf43fb36a91a from #5940

[Backport 2.x] Apply OpenSearchIntegTestCase::featureFlagSettings by default (#5940)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java

Allow search related settings to be updated for searchable snapshots.
Resolves #4966

Add update settings allowlist for searchable snapshot

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryFailedException.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryListener.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationFailedException.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationListener.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Related to improvement in Segment replication, this change backports https://github.com/opensearch-project/OpenSearch/pull/4725 into 2.x

Use ReplicationFailedException instead of OpensearchException in ReplicationTarget

---

CHANGELOG.md

Fixes the location of changelog entry after backport of https://github.com/opensearch-project/OpenSearch/pull/4725 into 2.x in https://github.com/opensearch-project/OpenSearch/pull/5955
NA

Moves PR #4725 changelog entry to unreleased 2.x post backport

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/ForceSyncRequest.java
server/src/main/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
test/framework/src/main/java/org/opensearch/indices/recovery/AsyncRecoveryTarget.java

[Segment Replication] Update peer recovery logic for segment replication

---

CHANGELOG.md

Somehow an entirely misplaced section was put at the top of the file. Additionally two changes had been backported to 2.x but were in the wrong section.

Fix CHANGELOG errors on main

---

.github/workflows/dependabot_pr.yml

- Fixes version for dependabot changelog helper plugin on main
- N/A

Fix dependabot changelog plugin version

---

CHANGELOG.md

I think this is the last entry that was in the wrong section. It has been [backported to 2.x][1].
[1]: https://github.com/opensearch-project/OpenSearch/blob/4542319c6cf6d6e1136f03f84ec589538daded30/CHANGELOG.md#L26

Move changelog entry that was backported to 2.x

---

CHANGELOG.md

I feel like I'm tilting at windmills here, but this brings the 2.x CHANGELOG mostly in line with what is on main. There are a couple changes on main that pending backports to 2.x, but those entries will go here only when the changes are actually backported.

Fix CHANGELOG errors on 2.x

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/main/java/org/opensearch/extensions/action/ExtensionTransportActionsHandler.java
server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java

Removes latches and CompletableFuture .get() calls to make requests asynchronous
Backport of https://github.com/opensearch-project/OpenSearch/pull/5646
https://github.com/opensearch-project/opensearch-sdk-java/issues/292

[Backport 2.x] Replace latches with CompletableFutures for extensions

---

.github/ISSUE_TEMPLATE/failed_check.md
.github/workflows/gradle-check.yml

Creates an issue if a gradle check run triggered by a push fails.  Tested this out from a test repo [here](https://github.com/mch2/TestActions/blob/main/.github/workflows/test.yml).
closes https://github.com/opensearch-project/OpenSearch/issues/5799

Create an issue if an on push gradle check fails.

---

.github/workflows/backport.yml

This brings our backport workflow script in line with the script from the [tibdex/backport][1] github action implementation.
[1]: https://github.com/tibdex/backport/blob/b1bb2aaf611d9f2e5d1900c06493769b9f102a45/.github/workflows/backport.yml#L12-L22

Add condition that PRs are merged in backport workflow

---

build.gradle
modules/lang-painless/build.gradle
server/src/main/java/org/opensearch/index/fielddata/ScriptDocValues.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

`javadoc` warnings not causing failures
Closes https://github.com/opensearch-project/OpenSearch/issues/5995

[BUG] javadoc warnings not causing failures

---

.github/workflows/backport.yml

This brings our backport workflow script in line with the script from the [tibdex/backport][1] github action implementation.
[1]: https://github.com/tibdex/backport/blob/b1bb2aaf611d9f2e5d1900c06493769b9f102a45/.github/workflows/backport.yml#L12-L22
(cherry picked from commit 715ff72c1bf1ca31e861639faa664f92f6115501)

[Backport 2.x] Add condition that PRs are merged in backport workflow (#5997)

---

CHANGELOG.md

This commit fixes the changelog entry placement error in #5646

Move changelog entry that was backported

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java

This change fixes flakiness with segment replication ITs. It does this by updating the wait condition used to ensure replicas are up to date to wait until a searched docCount is reached instead of output of the Segments API that can change if there are concurrent refreshes.
It also does this by updating the method used to assert segment stats to wait until the assertion holds true rather than at a point in time.  This method is also updated to assert store metadata directly over API output.  In doing so I've moved the method used to compute store metadata on top of IndexShard.
I've run this about ~1k times on the file locally and not seeing any issues, will open this and run a few times to test from CI. …

Fix flaky SegmentReplicationITs.

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

- Currently, `Engine` class does not expose a method which provides max sequence number that was part of last refresh.
- Remote segment store, as part of providing refresh level durability, needs this info.
- `InternalEngine.lastRefreshedCheckpoint()` does not guarantee to provide sequence number that is part of refreshed segments.
- This creates issues like: https://github.com/opensearch-project/OpenSearch/issues/5971
- `_seq_no` field is part of each indexed document. We can use this to query refreshed segments and fetch the last sequence number.
- We need to test the performance overhead though. As a part of this PR, I will run nyc_taxis workload from opensearch-benchmark and compare the performances.
- …

Add method to Engine to fetch max seq no of given SegmentInfos

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java

There are 2 changes made in this PR.
- Creating remote store backed index fails with [AssertionError](https://github.com/opensearch-project/OpenSearch/issues/4718).
- The failing assertion checks for type of failing thread and only allows threads from GENERIC or SNAPSHOT threadpools.
- As being discussed in the parent issue, `BlobStoreRepository.blobStore()` does not access any remote store resources and only involves creating instance of `BlobStore`.
- It is safe to call `BlobStoreRepository.blobStore()` from create index flow as it is not an expensive operation.
- Deleting remote store backed index fails with [AssertionError](https://github.com/opensearch-project/OpenSearch/issues/5919)
- When an instance of `Store` is created, a shardlock is created which is released on closing the …

Fix assertion failures in creation and deletion of remote store backed index

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
server/src/main/java/org/opensearch/cluster/routing/PreferenceBasedSearchNotAllowedException.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java

This is a backport PR
- https://github.com/opensearch-project/OpenSearch/pull/5874
- https://github.com/opensearch-project/OpenSearch/pull/5931

[Weighted Routing] [Backport 2.x]  Disallow search request with preference parameter when weighted routing enabled 

---

server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java

Signed-off-by: Rishav Sagar <rissag@amazon.com>
Test cases added for guardrail for applying index create block when all nodes are breaching high disk watermark were flaky. Reallocation on index created during integ test run was causing some race conditions scenarios. This PR fixes these test cases by disabling relocation on the indices created during integ tests.
https://github.com/opensearch-project/OpenSearch/issues/5956

Fix flaky test cases for DiskThresholdDeciderIT

---

.github/workflows/dependabot_pr.yml
CHANGELOG.md

The dependabot changelog helper did not previously work with newlines between sections. This has been fixed in [v2.2][1], which is the version currently pointed to by the [v2 tag][2].
[1]: https://github.com/dangoslen/dependabot-changelog-helper/blob/v2/CHANGELOG.md?plain=1#L9
[2]: https://github.com/dangoslen/dependabot-changelog-helper/releases/tag/v2

Fix CHANGELOG dependencies section and update dependabot

---

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java

This change logs the diff.different files for debugging purpose. Coming from https://github.com/opensearch-project/OpenSearch/issues/5701#issuecomment-1406508482

[Segment Replication] Log diff.different files for debuggability

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
test/framework/src/main/java/org/opensearch/indices/recovery/AsyncRecoveryTarget.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

This change fixes the primary relocation path with segrep. This changes:
- Segment replication to happen synchronously. This has side effects of writes happening on older primary and segment replication to timeout due to parallel writes on older primary and round of segment replication from older primary to target.
- Remove `StepListener` listener post above change. This needed corresponding changes in function definitions & unit test changes. 
- Updates existing integration test to reduce flakyness
- Verified newly added tests are not flaky
https://github.com/opensearch-project/OpenSearch/issues/5848 …

[Segment Replication] Update force segment replication round to be synchronous

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
test/framework/src/main/java/org/opensearch/indices/recovery/AsyncRecoveryTarget.java

Backports #6015 and #5898 to 2.x

[Segment Replication] Backport PRs from main

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/settings/Setting.java
server/src/main/java/org/opensearch/common/util/concurrent/AsyncIOProcessor.java
server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java

Translog sync takes care of local fsync and translog upload onto remote store. Currently, there is implicit buffering that happens as the remote store upload is a time consuming operation. However, every upload adds extra cost of network interaction along with the actual file upload. If we can buffer for a pareto-optimal duration, then we can save on the additional network interaction costs and overall achieve lower latencies and higher indexing throughput in comparison to non-buffered approach. There is also a delay optimisation in place that make sure that if the upload took considerable time, then schedule the next run with a decreased interval maintaining the overall buffer interval in check.
Credits for some of the code - Ashwin Pankaj, Laxman Muttineni 
This solves #5692
By …

Batch translog sync/upload per x ms for remote-backed indexes

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/decommission/NodeDecommissionedException.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestTests.java
server/src/test/java/org/opensearch/cluster/health/ClusterStateHealthTests.java
server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthActionTests.java

Cluster health call to throw decommissioned exception for local decommissioned nodes
* Backport - https://github.com/opensearch-project/OpenSearch/pull/6008

[Backport -2.x] Cluster health call to throw decommissioned exception for local decommissioned node

---

server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java

Fixes minor comment on variable naming - https://github.com/opensearch-project/OpenSearch/pull/5854#discussion_r1086211289
Fixes minor comment on variable naming - https://github.com/opensearch-project/OpenSearch/pull/5854#discussion_r1086211289

Refactor buffer interval code for remote-backed indexes

---

server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java

* Upload translog only if primaryMode is true
Original PR - https://github.com/opensearch-project/OpenSearch/pull/5804
Solves https://github.com/opensearch-project/OpenSearch/issues/5795 & https://github.com/opensearch-project/OpenSearch/issues/5844.
Original PR - https://github.com/opensearch-project/OpenSearch/pull/5804
Solves https://github.com/opensearch-project/OpenSearch/issues/5795 & https://github.com/opensearch-project/OpenSearch/issues/5844.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONT …

[Backport 2.x] Handle translog upload during primary relocation for remote-backed indexes (#5804)

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/settings/Setting.java
server/src/main/java/org/opensearch/common/util/concurrent/AsyncIOProcessor.java
server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java

* Batch translog upload per x ms to allow high index throughput
Co-authored-by: Ashwin Pankaj <appankaj@amazon.com>
Co-authored-by: Laxman Muttineni <muttil@amazon.com>
Original PR - https://github.com/opensearch-project/OpenSearch/pull/5854
This solves https://github.com/opensearch-project/OpenSearch/issues/5692

[Backport 2.x] Batch translog sync/upload per x ms for remote-backed indexes (#5854)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

OpenJDK Update (January 2023 Patch releases)
Closes https://github.com/opensearch-project/OpenSearch/issues/6073

OpenJDK Update (January 2023 Patch releases)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/6075 to `2.5`

[Backport] [2.5] OpenJDK Update (January 2023 Patch releases) (#6075)

---

CHANGELOG.md
buildSrc/version.properties
client/rest/build.gradle
client/sniffer/build.gradle

Bumps Mockito from 4.7.0 to 5.1.0, ByteBuddy from 1.12.18 to 1.12.22
N/A

Bumps Mockito from 4.7.0 to 5.1.0, ByteBuddy from 1.12.18 to 1.12.22

---

.github/ISSUE_TEMPLATE/failed_check.md

There were multiple GC failures post merge over the weekend. - Example: https://github.com/opensearch-project/OpenSearch/actions/runs/4028023871/jobs/6924435585.  The recently introduced workflow to autocut an issue failed because of formatting.  Also added [AUTOCUT] to beginning of the issue title.
closes https://github.com/opensearch-project/OpenSearch/issues/6085

Fix broken template for issue autocuts on GH failure.

---

CHANGELOG.md
buildSrc/version.properties
client/rest/build.gradle
client/sniffer/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/6076 to `2.5`

[Backport] [2.5] Bumps Mockito from 4.7.0 to 5.1.0, ByteBuddy from 1.12.18 to 1.12.22 (#6076)

---

CHANGELOG.md
buildSrc/version.properties
client/rest/build.gradle
client/sniffer/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/6076 to `2.x`

[Backport] [2.x] Bumps Mockito from 4.7.0 to 5.1.0, ByteBuddy from 1.12.18 to 1.12.22 (#6076)

---

.github/ISSUE_TEMPLATE/failed_check.md

Fix failing autocut on gc failure workflow caused by our >test-failure label.
Tested this on personal branch here - https://github.com/mch2/TestActions/issues/27
closes https://github.com/opensearch-project/OpenSearch/issues/6085

Fix autocut on GC failure caused by >test-failure label.

---

buildSrc/version.properties
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

Updating the JDK version (followup to https://github.com/opensearch-project/OpenSearch/pull/6077)

[Backport] [1.x] OpenJDK Update (January 2023 Patch releases)

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/action/ExtensionActionRequest.java

Signed-off-by: Joshua Palis <jpalis@amazon.com>
Changes ExtensionActionRequest streaminput constructor to be public, for use in tests
Part of https://github.com/opensearch-project/opensearch-sdk-java/issues/309
- [ X] Commits are signed per the DCO using --signoff
- [ X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

[Extensions] Changing ExtensionActionRequest streaminput constructor to be public

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/6077 to `1.3`

[Backport] [1.3] OpenJDK Update (January 2023 Patch releases) (#6077)

---

.github/workflows/gradle-check.yml
.github/workflows/links.yml
.github/workflows/version.yml

Signed-off-by: sashashura <aleksandrosansan@gmail.com>
Signed-off-by: sashashura <aleksandrosansan@gmail.com>
(cherry picked from commit d266a732aea4cf87781acf93e92c56ad3f1d0913)
This is a backport of #4587 to 2.x
N/A

[Backport 2.x] build: harden worfklows permissions (#4587)

---

CHANGELOG.md
buildSrc/version.properties
server/licenses/joda-time-2.10.12.jar.sha1
server/licenses/joda-time-2.12.2.jar.sha1
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/6083 to `2.x`

[Backport] [2.x] Update Joda to 2.12.2 (#6083)

---

CHANGELOG.md
buildSrc/version.properties
server/licenses/joda-time-2.10.12.jar.sha1
server/licenses/joda-time-2.12.2.jar.sha1
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/6083 to `2.5`

[Backport] [2.5] Update Joda to 2.12.2 (#6083)

---

.github/ISSUE_TEMPLATE/failed_check.md

Fixes yet another issue with failed_check.md.  I tested the exact same template from test repo -  Example issue: https://github.com/mch2/TestActions/issues/30  Created with template: https://raw.githubusercontent.com/mch2/TestActions/main/.github/ISSUE_TEMPLATE/failed_check.md
Error message is misleading the problem is in the added [AUTOCUT] label.
closes https://github.com/opensearch-project/OpenSearch/issues/6085
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of …

Fix AUTOCUT title formatting in failed_check.md

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java

This change mutes all SegmentReplicationRelocationITs which are still flaky on CI. Though, failure is not reproducible locally with failing seed. Test passes 500/500.
https://github.com/opensearch-project/OpenSearch/issues/6112
https://github.com/opensearch-project/OpenSearch/issues/6065

[Segment Replication] Mute SegmentRelocationITs failing/flaky on CI

---

CHANGELOG.md
buildSrc/version.properties
server/licenses/joda-time-2.10.12.jar.sha1
server/licenses/joda-time-2.12.2.jar.sha1
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/6083 to `1.3`

[Backport] [1.3] Update Joda to 2.12.2 (#6083)

---

CHANGELOG.md
buildSrc/version.properties
server/licenses/joda-time-2.10.12.jar.sha1
server/licenses/joda-time-2.12.2.jar.sha1
server/src/test/java/org/opensearch/common/time/DateUtilsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/6083 to `1.x`

[Backport] [1.x] Update Joda to 2.12.2 (#6083)

---

server/src/main/java/org/opensearch/Version.java

Fix Apache Lucene version for 2.6.0
Follow up on https://github.com/opensearch-project/OpenSearch/pull/6116 backport

Fix Apache Lucene version for 2.6.0

---

server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java

This PR fixes weighted routing stats version. Currently, the version is set to `CURRENT` but should be `2_6`

Fix weighted routing stats version

---

server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceConfig.java

Fixes an incorrect IllegalStateException message - the check for `valid()` does the following logic, and should refer to this as `unmapped` and not `unwrapped`:
```
return fieldContext != null || script != null || unmapped;
```
https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceConfig.java#L382

Fix incorrect exception message for ValuesSourceConfig

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java

This change disables query cache when internally querying for operation uid. This code path is executed only when assertions are enabled to check if an op already exists in the index. The current code fetches the searcher using acquireSearcher, which reuses the queryCache and conflicts with tests on the cache.
See #2501 for more.
closes #2501 

Fix flaky test IndexStatsIT.testFilterCacheStats.

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This change is a clean up and improvement during peer recovery with segment replication. The change was originally introduced in https://github.com/opensearch-project/OpenSearch/pull/5332. This change performs
- Untie `IndicesClusterStateService` from `SegmentReplicationTargetService`
- Fail fast during recovery. 
- Updates `SegmentReplicationSourceHandlerTests` to use correct engine factory and updates existing unit test classes to consider replica recovery
- Adds one integration test `testNewlyAddedReplicaIsUpdated` which verifies happy path scenario. The change moves this test along with `testAddNewReplicaFailure` to `SegmentReplicationRelocationIT` which is more natural class for these ITs. Both tests are muted as they tend to fail on CI. These relocation test failures are tracked in …

[Segment Replication] For replica recovery, force segment replication sync from peer recovery source

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/750bfc6216e1b67f865595bb37123d29d659ac2f from https://github.com/opensearch-project/OpenSearch/pull/5970.

[Backport 2.x] Add method to Engine to fetch max seq no of last refresh

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/store/StoreTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java

This change updates IndexShard#getlatestSegmentInfos to include the latest max seqNo from the primary's segmentInfos snapshot.  It also updates the method to return a Tuple so that both can be fetched. This change also updates replicas to not bump their SegmentInfos version when performing a commit.
closes #6121

Update replicationCheckpoint to include accurate seqNo from SegmentInfos.

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/store/StoreTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java

Manual backport of [#6122](https://github.com/opensearch-project/OpenSearch/pull/6122) to 2.x.

[Backport 2.x] Backport #6122 to 2.x

---

.github/ISSUE_TEMPLATE/failed_check.md
.github/workflows/gradle-check.yml

This is a backport of updates to the gradle check workflow to  autocut an issue when check fails on push.

[Backport 2.x] Backport workflow to autocut issue on push failure.

---

libs/common/src/main/java/org/opensearch/common/collect/Triplet.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
server/src/main/java/org/opensearch/common/TriConsumer.java
server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/settings/Setting.java
server/src/main/java/org/opensearch/search/aggregations/support/MultiTermsValuesSourceConfig.java
server/src/main/java/org/opensearch/search/aggregations/support/MultiValuesSourceFieldConfig.java
server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
server/src/test/java/org/opensearch/common/settings/SettingTests.java
server/src/test/java/org/opensearch/search/aggregations/metrics/SumAggregatorTests.java

This change introduces the mechanism to balance primary shards across cluster
- Introduce new weight factor `PRIMARY_BALANCE_FACTOR_SETTING` setting which defines the constant for primary shards; used to calculate the weight on node. This factor defines the tendency to balance the primary shards; higher the value more chances of even distribution. This setting's default is initially set to `0.0f` to avoid rebalance disruption in existing clusters. The other settings used in weight calculation are `INDEX_BALANCE_FACTOR_SETTING` govern shards/node specific to index and SHARD_BALANCE_FACTOR_SETTING shards/node. 
- This needed changes in utilities classes ModelIndex, ModelNode; used for weight calculation.
- It changes existing `TriConsumer` to conform to existing Java Consumer interface …

[Segment Replication] Introduce primary weight factor for primary shards distribution

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/IndexMetadataUpdater.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

- Add integration tests for remote store restore flow.
- Few changes discovered as part of integ test runs.
- https://github.com/opensearch-project/OpenSearch/issues/5872

[Remote Store] Get SeqNo from Segment Info and integ tests for restore flow

---

.github/workflows/version.yml

Change commit message and PR title to imperative mood

---

README.md

- Update tracking version for badge post 2.5 release
- N/A

Update badge version post release

---

.github/workflows/auto-release.yml

Backporting auto release workflow to 1.x
This workflow automates github releases based on tag, see: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

[Backport 1.3] Backporting auto release workflow to 1.3

---

.github/workflows/version.yml

This backports both #2572 and #6177. This was created by doing:
```
git checkout upstream/main .github/workflows/version.yml
```

Backport version.yml to 2.x

---

.github/workflows/auto-release.yml

Backporting auto release workflow to 1.x
This workflow automates github releases based on tag, see: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

[Backport 1.x] Backporting auto release workflow to 1.x

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/shards/ClusterShardLimitIT.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/indices/ShardLimitValidator.java
server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java

Signed-off-by: Rishav Sagar <rissag@amazon.com>
We have observed that as shard count on the cluster increases, it becomes more prone to instability and availability. We have observed multiple instances where user had issues in the past because of too many shards on their cluster.
As of now, OpenSearch allows us to restrict the number of shards per node using setting ```cluster.max_shards_per_node``` inside ```ShardLimitValidator```. The maximum number of shards that can be present on the cluster is determined by ```maxShardsPerNode * nodeCount```. Issue here is, we can increase this total shard limit on the cluster just by increasing the number of node. There is no way we can control the maximum number of shards on an entire cluster.
I would suggest to add a similar setting inside …

Add a guardrail to limit maximum number of shard on the cluster

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/54ce4237e01b55f7b861e5b3cdf4d36999b671f9 from https://github.com/opensearch-project/OpenSearch/pull/6086.

[Backport 2.x] Purge remote translog basis the latest metadata for remote-backed indexes

---

.github/CODEOWNERS

A couple changes to this file were not backported. This commit was made via:
```
git checkout upstream/main .github/CODEOWNERS
```

[Backport 1.x] Sync CODEOWNERS from main to 1.x

---

.github/CODEOWNERS

A couple changes to this file were not backported. This commit was made via:
```
git checkout upstream/main .github/CODEOWNERS
```

[Backport 1.3] Sync CODEOWNERS from main to 1.3

---

server/src/main/java/org/opensearch/extensions/ExtensionsManager.java

@ryanbogan @saratvemulapalli Can you verify if this okay? For reference, a similar change was made here: https://github.com/opensearch-project/security-analytics/pull/198

Use SafeConstructor() instead of Constructor()

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java
server/src/main/java/org/opensearch/action/search/SearchShardTask.java
server/src/main/java/org/opensearch/action/search/SearchTask.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/search/backpressure/CancellationSettingsListener.java
server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureState.java
server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java
server/src/main/java/org/opensearch/search/backpressure/settings/SearchTaskSettings.java
server/src/main/java/org/opensearch/search/backpressure/stats/SearchBackpressureStats.java
server/src/main/java/org/opensearch/search/backpressure/stats/SearchTaskStats.java
server/src/main/java/org/opensearch/search/backpressure/trackers/CpuUsageTracker.java
server/src/main/java/org/opensearch/search/backpressure/trackers/ElapsedTimeTracker.java
server/src/main/java/org/opensearch/search/backpressure/trackers/HeapUsageTracker.java
server/src/main/java/org/opensearch/search/backpressure/trackers/TaskResourceUsageTracker.java
server/src/main/java/org/opensearch/tasks/SearchBackpressureTask.java
server/src/main/java/org/opensearch/tasks/TaskCancellation.java
server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
server/src/test/java/org/opensearch/search/backpressure/settings/SearchBackpressureRenamedSettingsTests.java
server/src/test/java/org/opensearch/search/backpressure/stats/SearchBackpressureStatsTests.java
server/src/test/java/org/opensearch/search/backpressure/stats/SearchTaskStatsTests.java
server/src/test/java/org/opensearch/search/backpressure/trackers/CpuUsageTrackerTests.java
server/src/test/java/org/opensearch/search/backpressure/trackers/ElapsedTimeTrackerTests.java
server/src/test/java/org/opensearch/search/backpressure/trackers/HeapUsageTrackerTests.java
server/src/test/java/org/opensearch/tasks/TaskCancellationTests.java

Cancellation of in-flight SearchTasks based on resource consumption.
This feature aims to identify and cancel resource intensive SearchTasks if they have breached certain
thresholds. This will help in terminating problematic queries which can put nodes in duress and degrade the
cluster performance.
1. For resource tracking of SearchTasks, we will use the existing thresholds used for SearchShardTask but with different thresholds.
2. Introduced new dynamic settings for defining thresholds for SearchTask cancellation.
3. Added `search_task` stats in the response body of `_nodes/stats/search_backpressure`.
#5173 …

[Backport] [2.x] Add search backpressure cancellation at the coordinator level (#5605)

---

server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java
server/src/main/java/org/opensearch/search/backpressure/settings/SearchTaskSettings.java
server/src/main/java/org/opensearch/search/backpressure/stats/SearchBackpressureStats.java
server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
server/src/test/java/org/opensearch/tasks/TaskCancellationTests.java

Changing Search Backpressure version to 2.6 and other minor refactoring.
#5173
Signed-off-by: PritLadani <pritkladani@gmail.com>

Changing SearchBP version to 2_6_0

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

- `Engine.getMaxSeqNoFromSegmentInfos()` does not provide maxSeqNo always. It returns sequence number of last indexed doc. In case of concurrent writes, it is possible that last indexed doc will not have max seq number among the indexed doc.
- This PR provides fix to this issue by changing SortField to `SortField(SeqNoFieldMapper.NAME, SortField.Type.LONG, true)`
- In this change, we are also muting `RemoteStoreIT.testRemoteTranslogRestore` as it is [reported](https://github.com/opensearch-project/OpenSearch/issues/6188) flaky.  Need to investigate further on the flakiness of the test.
- https://github.com/opensearch-project/OpenSearch/issues/6229 …

Fix sort order in getMaxSeqNoFromSegmentInfos and mute testRemoteTranslogRestore

---

client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/CreateIndexRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/PutIndexTemplateRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/PutMappingRequest.java
client/rest-high-level/src/test/java/org/opensearch/client/indices/PutMappingRequestTests.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/MediaType.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentBuilder.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentFactory.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentGenerator.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContentGenerator.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
server/src/main/java/org/opensearch/action/ingest/PutPipelineRequest.java
server/src/main/java/org/opensearch/common/settings/Settings.java
server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
server/src/main/java/org/opensearch/index/reindex/ReindexRequest.java
server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
server/src/test/java/org/opensearch/action/search/SearchPhaseExecutionExceptionTests.java
server/src/test/java/org/opensearch/common/xcontent/BaseXContentTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java

Refactors various REST requests to use MediaType instead of XContentType to abstract media format from the REST interfaces.
relates #5910

[Refactor] Requests to use MediaType instead of XContentType

---

distribution/archives/build.gradle
settings.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/5950 to `2.x`

[Backport] [2.x] power changes for building with and without jdk

---

distribution/archives/build.gradle
settings.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/5950 to `2.x`

[Backport] [1.x] power changes for building with and without jdk

---

CHANGELOG.md

Move ppec6le changelog entry after backport

---

rest-api-spec/src/main/resources/rest-api-spec/api/cat.segment_replication.json
server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java

This PR mutes flaky test testSegmentReplicationStatsWithTimeout() found in #6255 and adds segment_replication.json as experimental coming from [comment](https://github.com/opensearch-project/OpenSearch/pull/5718#discussion_r1100729132)
#6255 

[Segment Replication] Mute Flaky Test and add segment_replication.json as experimental

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
server/src/test/java/org/opensearch/common/lucene/LuceneTests.java

- In `RemoteStoreIT.testRemoteSegmentStoreRestore` test, if we index X documents and primary goes down without refresh, as we are using only remote segment store, restore operation creates as empty index.
- Indexing new doc on the restored index is treated as the first doc and response contains seqNo as 0 (for the first doc).
- The seqNo initialization to 0 instead of -1 was failing the test which is fixed with this change.
- https://github.com/opensearch-project/OpenSearch/issues/6248 …

[Remote Store] Fix flaky test RemoteStoreIT.testRemoteSegmentStoreRestore

---

server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

Remove timestamp from the translog metadata filenames. The pair of primary term and generation is supposed to be unique for failovers and relocation. For failovers, the primary terms bumps by 1. For relocation, the generation increases while the primary term remaining the same. The invariant, however, is that the combination of primary term and generation would not be overridden on remote store. 
This solves #5677 - Metadata file naming. The cleanup of metadata file is present in #6239 and PR is created already #6238. …

Remove timestamp from translog metadata filename for remote-backed indexes

---

distribution/archives/build.gradle
settings.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/5950 to `1.3`

[Backport] [1.3] power changes for building with and without jdk

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java

This change adds the changelog entry for PR #6017 which introduces a dynamic setting exposed to end user and thus deserves entry in changelog.
This PR also uses this opportunity to fix one issue in allocation test to use `replicaCount` for number of replicas instead of constant. 

[Segment Replication] Add changelog entry and fix allocation test

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java

Fixes the flaky testSnapshotOnSegRep_RestoreOnSegRepDuringIngestion. It does this by
- Replacing BackgroundIndexer with simple for loop as test was performing indexing operations twice which has chance of doc ids conflict
- Wait for replica shard to catch up with primary before doc count assertion in the end 
- Assert on green state post snapshot restore
Test passes 500/500 locally
#5669 

[Segment Replication] Fix flaky testSnapshotOnSegRep_RestoreOnSegRepDuringIngestion test

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

Unmute segrep test testPrimaryStopped_ReplicaPromoted.  This test was muted with PR: https://github.com/opensearch-project/OpenSearch/pull/5739/files# and fixed with https://github.com/opensearch-project/OpenSearch/issues/6015 that waits until replicas have done a sync until asserting doc count.
#5669

Fix flaky segrep test testPrimaryStopped_ReplicaPromoted

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdSettings.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java

OpenSearch controls (applies and remove)```create_index``` block (when all node are breaching high disk watermark) inside ```DiskThresholdMonitor```. Now, if the user tries to apply this block from their end, it may be possible that ```DiskThresholdMonitor``` removes it (```create_index``` gets removed if any of the node is not breaching high disk watermark). This makes this block to be usable only by OpenSearch monitors. User cannot control when these blocks get applied or removed.
We would suggest to add a configurable setting which will control when these blocks will be removed. This will ensure that when set to false, both user and OpenSearch monitor applies the respective blocks, but removal of the block is controlled by user. …

Add a setting to control auto release of OpenSearch Monitors managed index creation block

---

modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoHashGridIT.java
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/GeoShapeCellValues.java

Fixing the GeoShapes GeoHash and GeoTile Aggregations Integration tests to make them more robust.
Signed-off-by: Navneet Verma <navneev@amazon.com>
The issue was happening few random seeds. For GeoHash aggregations on shape we are getting ArrayIndexOut of bounds exception because we were not resetting the values of SortedNumericDocs leading to access of memory area not initialized by the vectors.
* Fixed the ArrayIndexOutOfBoundsException.
* Reduced the precision for GeoShapes Aggregation IT testing.
For improving the testing for bounded geoshape aggregation I am creating a new Github issue. https://github.com/opensearch-project/OpenSearch/issues/6251
#6187, #6222
Done using the failed gradle flows in the issues.
```
(base) 12:03 /Volumes/workplace/OpenSearch main$ ./gradlew …
```

[#6187, #6222] Fixing the GeoShapes GeoHash and GeoTile Aggregations Integration tests to make them more robust.

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java

- This change mutes flaky test RemoteStoreIT.testRemoteStoreRestoreFromRemoteSegmentStore
- https://github.com/opensearch-project/OpenSearch/issues/6291

Mute integ test RemoteStoreIT.testRemoteStoreRestoreFromRemoteSegmentStore

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/6298 to `2.x`

[Backport] [2.x] Bump org.apache.ant:ant from 1.10.12 to 1.10.13 (#6298)

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

As discussed in #6214, during relocation certain documents indexed on the older primary were not seen on the new primary upon search. This was happening as recoverFromTranslog was recovering upto last known global checkpoint while it should be done upto `Long.Max` for cases where remote translog store is enabled.
https://github.com/opensearch-project/OpenSearch/blob/49d9a90b52d5451e0eda95ce03dfb94dd505a905/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L4314-L4317
When remote translog is enabled, then remote store acts as the source of truth for storing translogs. During relocation we reset engine to writeable engine. When this happens, we initialise the RemoteFsTranslog which downloads all the translogs from remote store. …

Recover all translogs during relocation handoff for remote-backed indexes

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java

Manual backport of #6280 to 2.x

Backport/backport 6280 to 2.x

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

Original PR - https://github.com/opensearch-project/OpenSearch/pull/6314
Original Issue - https://github.com/opensearch-project/OpenSearch/issues/6214

[Backport 2.x] Recover all translogs during relocation handoff for remote-backed indexes

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Currently, during segment merge (both during auto merge and force merge), OpenSearch creates multiple temporary files while merging individual segment components. Once individual components of the segments are merged, IndexWriter creates a Compound file (*.cfs) containing all the Lucene components for a segment. At the end, OpenSearch deletes these temporary files.
Now, in case these temporary files consume all the space on the node (because enough amount of space is unavailable for segment merge to go through), segment merge will fail. Also, the files which got created during segment merge do not get cleaned up and it continues to occupy space on the node. This can cause FSHealthService checks to fail for this node, ultimately causing these nodes to be removed from cluster.
In case Force …

Clean up temporary files created during segment merge incase force segment merge fails

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/RunTask.java

During the development, ability to run OpenSearch with debugger from time to time is quite handy. I am suggesting to add a new option` --debug-server-jvm` (to differentiate from `--debug-jvm`):
```
./gradlew run --debug-server-jvm
```
```
2023-02-16T14:48:28.895574Z] [BUILD] Creating opensearch keystore with password set to []                                                                                                    
[2023-02-16T14:48:29.806201Z] [BUILD] Starting OpenSearch process                                                                                                                             
Listening for transport dt_socket at address: 5005 …
```

Add support to Gradle run task to spawn OpenSearch instances in debug mode

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

Similar to https://github.com/opensearch-project/OpenSearch/pull/6314, when we flip to a writeable engine with SR we do not want to limit to the global checkpoint and rather recover all ops.
Related to flaky tests, these tests are still muted until WAIT_UNTIL issue has been fixed.
https://github.com/opensearch-project/OpenSearch/issues/6065
https://github.com/opensearch-project/OpenSearch/issues/5946
https://github.com/opensearch-project/OpenSearch/issues/5669
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …

Segment Replication - Recover all translog ops when flipping to able engine

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
server/src/test/java/org/opensearch/index/store/remote/file/CleanerDaemonThreadLeakFilter.java
server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInputLifecycleTests.java
server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java

As detailed [in this issue][1], Lucene does not close the cloned IndexInput instances, so we are using the Cleaner mechanism from the JDK to close any unclosed clones.
A single static Cleaner instance to ensure any unclosed clone of an IndexInput is closed. This instance creates a single daemon thread on which it performs the cleaning actions. For an already-closed IndexInput, the cleaning action is a no-op. For an open IndexInput, the close action will decrement a reference count.
[1]: https://github.com/opensearch-project/OpenSearch/issues/5243#issuecomment-1399037364
Closes #5243 …

[Searchable Snapshot] Use java.lang.ref.Cleaner to close cloned IndexInputs

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java

This change fixes the flakyness in `testSegmentReplicationStatsResponse` happening due to race condition where segment replication does not complete before fetching `SegmentReplicationStatsResponse` response. The change waits for segment replication to complete before assertions. The change also removes deprecated `assertThat`.
Sample unstable gradle check: https://build.ci.opensearch.org/job/gradle-check/11323/  
https://github.com/opensearch-project/OpenSearch/issues/5669 …

[Segment Replication] Wait for segment replication to be completed and marked done before assertion

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java

- Currently, restoring an index with no data in remote segment store fails.
- Ideally, restore should create an empty index if there is no data in remote segment store.
- https://github.com/opensearch-project/OpenSearch/issues/6291

[Remote Store] Create empty lucene index during restore if remote segment store is empty

---

CHANGELOG.md
build.gradle

Backport 36f5cfe807584177dd4842810734e04a5f7bd4ae from #6212

[Backport 2.x] Remove deprecated org.gradle.util.DistributionLocator usage

---

CHANGELOG.md
build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/6379 to `2.x`

[Backport] [2.x] Bump com.diffplug.spotless from 6.11.0 to 6.15.0 (#6379)

---

server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java

In PR #6345 I did remove a duplicate clone, however this resulted in cloning the IndexInput in the wrong place. When requesting a file that needs to be downloaded, we have a mechanism to ensure that concurrent calls do not end up duplicating the download, which results in multiple threads being given the same instance. The clone must happen _after_ this point to ensure that each thread gets its own clone.
I've added a unit test that will reliably fail without the fix.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate …

[Searchable Snapshots] Correctly clone IndexInputs to avoid race

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java

This change fixes broken SegmentReplicationRelocationITs and unmutes them.  The cause of the flaky tests is WAIT_UNTIL requests blocking relocation of primary shards because replicas have not refreshed.  The issue is that primary shards cannot publish their checkpoints because PublishCheckpointAction is a ReplicationOperation, that first hits the primary and acquires a permit.  Given we are blocking operations, the permit is delayed and the request never succeeds.  This fixes the issue by ensuring PublishCheckpoint requests are not sent to the primary, and only to replicas within the replication group directly.
closes https://github.com/opensearch-project/OpenSearch/issues/6065 …

Skip performOnPrimary step when executing PublishCheckpoint.

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json

This PR updates the REST API spec for cluster health API since we updated the param as part of this PR - https://github.com/opensearch-project/OpenSearch/pull/6232

Update API spec for cluster health API

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingUtils.java

This PR fixes inconsistent cluster state with ensure_weighed_in param while make cluster health api call.
Also adds support for weighed away health check only for data nodes.

Fix inconsistent cluster state and ensure weigh away exception check only for data nodes

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

This fixes #6398
This fixes #6398

[Remote Translog] Allow only one remote generation deletion

---

server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4246

[Backport 2.x] Handles the status code for . properties

---

.github/workflows/publish-maven-snapshots.yml

Adds workflow to publish snapshots to maven
gist of what snapshots publication will look like:
```
find snapshots | sort
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/client
snapshots/org/opensearch/client/client-benchmarks
snapshots/org/opensearch/client/client-benchmarks/3.0.0-SNAPSHOT
snapshots/org/opensearch/client/client-benchmarks/3.0.0-SNAPSHOT/client-benchmarks-3.0.0-20230220.235219-1-javadoc.jar
snapshots/org/opensearch/client/client-benchmarks/3.0.0-SNAPSHOT/client-benchmarks-3.0.0-20230220.235219-1-javadoc.jar.md5
snapshots/org/opensearch/client/client-benchmarks/3.0.0-SNAPSHOT/client-benchmarks-3.0.0-20230220.235219-1-javadoc.jar.sha1
snapshots/org/opensearch/client/client-benchmarks/3.0.0-SNAPSHOT/client-benchmarks-3.0.0-20230220.235219-1-javadoc.ja …
```

Add workflow to publish maven snapshots

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/Setting.java
server/src/main/java/org/opensearch/common/settings/WriteableSetting.java
server/src/test/java/org/opensearch/common/settings/SettingTests.java

Signed-off-by: Frank Lou <mloufra@amazon.com>
Create writeable implementations for parser that implement both Function<String, T> and Writeable interfaces for all existing setting implementations that use parsers.
Fixes https://github.com/opensearch-project/opensearch-sdk-java/issues/349

[Extensions] Create writeable implementations for parser

---

CHANGELOG.md
plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/ConfigPathSupport.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java

Allow to specify the identity web token file relatively to the `config` folder location (configured by `OPENSEARCH_PATH_CONFIG` so it would be possible to use soft links to access it):
```
ln -s $AWS_WEB_IDENTITY_TOKEN_FILE "${OPENSEARCH_PATH_CONFIG}/aws-web-identity-token-file"
```
And refer to it in `opensearch.yml`:
```
s3.client.default.identity_token_file: aws-web-identity-token-file
```
Closes https://github.com/opensearch-project/OpenSearch/issues/6312
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …

Opensearch repository-s3 plugin cannot read ServiceAccount token

---

CHANGELOG.md
plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/ConfigPathSupport.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/6390 to `2.x`

[Backport] [2.x] Opensearch repository-s3 plugin cannot read ServiceAccount token (#6390)

---

server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java

DiskThresholdMonitor was resetting last runtime millisecond every time high disk watermark breaches on all nodes. This change ensure that last runtime millisecond is reset only in the first iteration.
https://github.com/opensearch-project/OpenSearch/issues/4456

[Fix] Fix last runtime millisec reset when applying index create block

---

client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/CreateIndexRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/PutIndexTemplateRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/PutMappingRequest.java
client/rest-high-level/src/test/java/org/opensearch/client/indices/PutMappingRequestTests.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/MediaType.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentBuilder.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentFactory.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentGenerator.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContentGenerator.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
server/src/main/java/org/opensearch/action/ingest/PutPipelineRequest.java
server/src/main/java/org/opensearch/common/settings/Settings.java
server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
server/src/main/java/org/opensearch/index/reindex/ReindexRequest.java
server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
server/src/test/java/org/opensearch/action/search/SearchPhaseExecutionExceptionTests.java
server/src/test/java/org/opensearch/common/xcontent/BaseXContentTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java

Backport 1f4cdd2f75ca5e98bd81f3226566d263ec00455c from #6218.

[Backport 2.x] [Refactor] Requests to use MediaType instead of XContentType (#6218)

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.6.0.md

(cherry picked from commit 01466a6a04e280267f013aeb14dff1f20dc7a77a)
* Add release notes for v2.6.0
This change also includes cleanup of the CHANGELOG file to only capture unreleased changes.
* Minor language updates in v2.6.0 release notes and Changelog
relates #6443 and #6360 

[Backport 2.x] Add release notes for v2.6.0 (#6443)

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.6.0.md

(cherry picked from commit 01466a6a04e280267f013aeb14dff1f20dc7a77a) (cherry picked from commit 03a31294c40ecb9691c250e5d42a213468c848c3)
* Add release notes for v2.6.0
This change also includes cleanup of the CHANGELOG file to only capture unreleased changes.
* Minor language updates in v2.6.0 release notes and Changelog
relates #6447 and #6360
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#de …

[Backport 2.6] Add release notes for v2.6.0 (#6443) (#6447)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/6366 to 2.x.

[Backport 2.x] Skip performOnPrimary step when executing PublishCheckpoint. (#6366)

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/backpressure/trackers/HeapUsageTracker.java

Bug-fix in Search Backpressure's HeapUsageTracker.
#5173
Signed-off-by: PritLadani <pritkladani@gmail.com>

Fix a bug in Search Backpressure

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java

This change fixes flaky test testNewlyAddedReplicaIsUpdated by using ensureYellowAndNoInitializingShards that waits for 30s for a replica to be initialized over the existing 2s timeout.
closes #6459

Fix flaky test testNewlyAddedReplicaIsUpdated

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

Follow up to the #5641. This change exposes the file cache stats as part the node stats API response. The file cache was added as part of searchable snapshot in #5641. ~In addition this also adds an index event listener to clean up cache entries when a remote store index is deleted.~
Resolves #5982 

Include file cache stats in node stats api response

---

CHANGELOG.md
sandbox/modules/identity/src/main/java/org/opensearch/identity/IdentityPlugin.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/SecurityRestFilter.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/IdentityRestConstants.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/user/UserService.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/user/resetpassword/ResetPasswordAction.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/user/resetpassword/ResetPasswordRequest.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/user/resetpassword/ResetPasswordResponse.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/user/resetpassword/ResetPasswordResponseInfo.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/user/resetpassword/RestResetPasswordAction.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/user/resetpassword/TransportResetPasswordAction.java
sandbox/modules/identity/src/main/java/org/opensearch/identity/utils/ErrorType.java
sandbox/modules/identity/src/test/java/org/opensearch/identity/remotecluster/IdentityRestTestCase.java
sandbox/modules/identity/src/test/java/org/opensearch/identity/remotecluster/RestPermissionsIT.java
sandbox/modules/identity/src/test/java/org/opensearch/identity/remotecluster/UserIT.java

Signed-off-by: Ryan Liang <jiallian@amazon.com>
Internal users are able to reset password by using this API.
* Resolve #6311 

[Feature/Identity] Reset Password API

---

server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
server/src/main/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizer.java
server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
server/src/test/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizerTests.java
server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java

There is potential for a deadlock if work is submitted using the same executor as provided to ConcurrentInvocationLinearizer. This commit changes the behavior of that class to not implement any concurrency itself, therefore avoiding any potential for deadlock. The purpose of this class is to share the result when concurrent threads ask for the same resource, not provide concurrency itself, so I think the change is appropriate.
I've also removed the future from the TransferManager API as the only caller of it immediately blocked on the result. We may need to implement asynchronous logic here in the future, but I think it will be better to design that when there is a use case and a synchronous method makes things simpler now. I've also added logic to ensure exceptions get properly unwrapped …

Fix potential deadlock in ConcurrentInvocationLinearizer

---

server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java

InputStream#transferTo has been available since Java 9 and provides a built in method to drain an InputStream to an OutputStream without requiring loading the entire contents of the stream into memory.

Use InputStream#transferTo instead of readAllBytes

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/ShardPath.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
server/src/main/java/org/opensearch/monitor/fs/FsService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
server/src/test/java/org/opensearch/index/shard/ShardPathTests.java
server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
test/framework/src/main/java/org/opensearch/test/NodeRoles.java

- This PR focuses on adding a reservation logic for the cache introduced as a part of searchable snapshots
- The design was defined as a part of #4964 where a user can define the cache size using `node.search.cache.size` configuration for the node 
- This value is persisted as a part of the `NodePath` for the first data path configured on the node, and defaults to `100 MB` otherwise. 
- Resolves #5508 

Add cache reservation logic

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/ShardPath.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
server/src/main/java/org/opensearch/monitor/fs/FsService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
server/src/test/java/org/opensearch/index/shard/ShardPathTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java
server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
test/framework/src/main/java/org/opensearch/test/NodeRoles.java

- Backports #6333  and #6350 
- N/A

[Backport 2.x] Add file cache stats, reservation logic

---

.github/workflows/dependabot_pr.yml

Version 3 now uses the imperative mood ('Bump' vs 'Bumps') by default, which matches the preferred style used throughout the changelog.
See: https://github.com/dangoslen/dependabot-changelog-helper/releases/tag/v3.0.0

Update dependabot changelog helper to v3

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
server/src/main/java/org/opensearch/indices/IndicesService.java

This change adds a listener to index events so that when a remote index is deleted it's corresponding cached files are de-referenced and deleted from  the file cache.
Resolves #5981

Add event listener to prune file cache on index deletion

---

README.md

Corrects the link in the `README` to the OSI blog - the [existing link](https://opensource.org/node/1099) is now a 404 and the page appears to have moved [here](https://blog.opensource.org/the-sspl-is-not-an-open-source-license/). This change also fixes spelling error in "licence" 😄 
closes #6487 

Correct link to OSI blog in README

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
server/src/main/java/org/opensearch/index/mapper/ParseContext.java
server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java

Added a depth level check within the document parser context. The depth level is incremented for each nested object parsing and decremented when parsing is done. If the depth level crosses a threshold, document parser throws a parsing exception and an error is returned in the response, stating the reason of the failure
Closes issue (#5195)

Adding depth check in doc parser for deep nested document

---

server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/index/shard/ShardPath.java
server/src/test/java/org/opensearch/index/shard/ShardPathTests.java

- Fixes file cache path calculation logic
- Gets rid of the necessity of having a shard data path configuration which exists for custom data path on indices
- N/A

Fix file cache data path computation

---

CHANGELOG.md
buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle

[Backport 2.x] Bump org.apache.logging.log4j:log4j-core from 2.19.0 to 2.20.0 in /buildSrc/src/testKit/thirdPartyAudit/sample_jars

---

CHANGELOG.md

The `log4j-core` and `azure-storage-common` dependency bumps in #6490 and #6492 are being backported to the `2.x` branch in #6503 and #6504. This PR corrects the `CHANGELOG` entry to live under the "Unreleased 2.x` section rather than `Unreleased 3.0` in response to this comment - https://github.com/opensearch-project/OpenSearch/pull/6503#discussion_r1119521641
N/A

Fixup changelog by moving dependency bumps to 2.x section

---

CHANGELOG.md

- Fix changelog divergence for `Unreleased 2.x` between main and 2.x
- N/A

Fix changelog divergence

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java

This PR fixes bug of _cat/segment_replication API giving incorrect results. TransportSegmentReplicationStatsAction  Class is a Singleton so we cannot do a global state update of singleIndexWithSegmentReplicationDisabled, which on concurrent request might incorrectly fail
#5718 

[Segment Replication ]Remove state update of singleIndexWithSegmentReplicationDisabled in TransportSegmentReplicationStatsAction  Class

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
server/src/main/java/org/opensearch/index/mapper/ParseContext.java
server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java

* Adding depth check in doc parser for deep nested document
Fixing the issue (#5195)
Signed-off-by: Nikhil Kumar <nikhkumn@amazon.com>
(cherry picked from commit 950b86ae697d95db537e7809f2675ebdf2b0dc10)
Added a depth level check within the document parser context. The depth level is incremented for each nested object parsing and decremented when parsing is done. If the depth level crosses a threshold, document parser throws a parsing exception and an error is returned in the response, stating the reason of the failure
Closes issue (https://github.com/opensearch-project/OpenSearch/issues/5195) …

[Banckport 2.x] Adding depth check in doc parser for deep nested document (#5199)

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

The current default of 8KiB is tiny, and with the current design of each block represented as a unique file on disk leads to an explosion of files for non-trivial data sizes. Also object stores are generally not optimized for fetching small bits of data.

Change default block size to 8MiB

---

server/src/main/java/org/opensearch/extensions/RegisterTransportActionsRequest.java
server/src/main/java/org/opensearch/extensions/action/ExtensionTransportActionsHandler.java
server/src/test/java/org/opensearch/extensions/RegisterTransportActionsRequestTests.java
server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java

Companion PR: https://github.com/opensearch-project/opensearch-sdk-java/pull/524 
(PRs must be merged together, this one first.)
`o.o.extensions.RegisterTransportActionsRequest` was incorrectly attempting to store a map with a compiled class available only to the SDK and not to OpenSearch. 
This PR changes the request to track only the set of action names (exactly equivalent to the `.keySet()` of the prior map implementation), which was all that was being used by the handler anyway.
The SDK will maintain a map of name to actual compiled/executable action.
[SDK #484](https://github.com/opensearch-project/opensearch-sdk-java/issues/484)
~- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~ (No change log, bug fix to prerelease …

[Extensions] Only store names of extension transport actions

---

server/src/main/java/org/opensearch/bootstrap/Security.java

FeatureFlags are instantiated later in the game and which is why directory permissions for `extensions` folder is results into read access exceptions. This change removes the feature flag as adding permissions for extensions directory is not invasive.
```
java.security.AccessControlException: access denied ("java.io.FilePermission" "<OPENSEARCH_HOME>/distribution/opensearch-3.0.0-SNAPSHOT/extensions" "read")
```
Closes https://github.com/opensearch-project/opensearch-sdk-java/issues/390
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#de …

Adding permissions for extensions directory

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/DocValueFormat.java
server/src/test/java/org/opensearch/search/DocValueFormatTests.java

Implements  `equals` and `hashCode` methods for the named inner class `DocValueFormat.DateTime`. 
Per the contract as described in the `Writeable` interface, any class implementing `equals`/`hashcode` must ensure that a copy made be serializing and deserializing must be equal. As `InternalDateHistogram` /  `InternalHistogram` implement `equals`/`hashcode` and are `Writable` classes, this requires that `DateTime` also implement `equals` and `hashcode` , as the `DateMathParser` will otherwise cause it to fail equivalence.  …

Implement equals/hashcode for named DocValueFormat inner classes

---

build.gradle

Remove the JUnit test framework workaround for JarHell issue, fixed in Gradle 8.0.2
N/A

Remove the JUnit test framework workaround for JarHell issue, fixed in Gradle 8.0.2

---

CHANGELOG.md

- Adds missing `Unreleased 2.x` entry into main

Fix changelog divergence for Unreleased 2.x on main

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java

This change removes the seqNo field from ReplicationCheckpoint.  This seqNo is only used on the replica to mark the `setLocalCheckpointOfSafeCommit` used to mark at which point the xlog can be deleted and advance the processed seqNo.  This logic was incorrectly attempting to fetch a max by querying the SegmentInfos directly, which would be incorrectly set after delete operations to a lower value.
Rather than relying on this seqNo, we can safely use the max seqNo of the previous commit point to advance both operations.  For xlog purge, we will continue to purge after a commit is received from the primary and only purge up to the max, which is guaranteed to be in the set of fsynced segments.  For the processed seqno, this ensures that if the replica is promoted primary it continues to …

Segment Replication - Remove seqNo field from ReplicationCheckpoint and use UserData to transfer state.

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java

- Add support to restore the file cache on node bootstrap
- Resolves #5980 

Add file cache restore logic

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java

…nd use UserData to transfer state. (#6594)
* Segment Replication - Fix incorrect maxSeqNo computation.
This change updates getLatestSegmentInfos to only return the max seqNo from the previous commit point.  This is the only way to guarantee that up to this seqNo has made it into the commit point.
* Remove unnecessary seqNo field from ReplicationCheckpoint.
Backport #6594

[Backport 2.x] Remove seqNo field from ReplicationCheckpoint and use UserData to transfer state.

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/pit/10_basic.yml
server/src/main/java/org/opensearch/action/search/DeletePitResponse.java
server/src/test/java/org/opensearch/search/DeletePitResponseTests.java

Fix for the issue due to which 404 was returned when no PITs were present.
Backport to 2.x branch failed https://github.com/opensearch-project/OpenSearch/pull/6544
https://github.com/opensearch-project/OpenSearch/issues/5938

[Backport] [2.x] Removed NOT_FOUND for empty results. (#6544)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java

Prevent round of force segment replication during recovery for ineligible targets. This was identified for closed indices whose shards remain allocated to nodes with `NoOpEngine` type. 
Changes:
1. Change `IndexShardState.POST_RECOVERY` to  `IndexShardState.RECOVERING` inside `isSegmentReplicationAllowed` as segment replication is now performed during recovery finalization step as part of https://github.com/opensearch-project/OpenSearch/pull/5746
2. Use `isSegmentReplicationAllowed` inside force segment replication on target service.
#6608  …

[Segment Replication] Prevent segment replication for ineligible targets during recovery

---

server/src/main/resources/org/opensearch/bootstrap/test-framework.policy

I'm a big user of the 'run until failure' option on the IDEA test runner for finding bugs. I just upgraded to the newest version of IDEA and it moved its JUnit runner, so we need a modified permission setting for that option to work.

Allow newer versions of IDEA to control test iterations

---

CHANGELOG.md
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/env/NodeRepurposeCommand.java
server/src/test/java/org/opensearch/env/NodeRepurposeCommandTests.java

- Add repurpose command support for search node reutilization

Add search node repurpose commands

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/6647 to `2.x`

[Backport] [2.x] Bump com.avast.gradle:gradle-docker-compose-plugin from 0.15.2 to 0.16.11 (#6647)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java

This change avoids the failing the replica shard on target on failures during round of segment replication. The replica shard is only marked failed when local store differs from primary (get files step), corruption/Index issues (finalize step). 
#6578 

[Segment Replication] Prevent unnecessary shard failure on replication target

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/SegmentReplicationPerGroupStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/main/java/org/opensearch/index/SegmentReplicationShardStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/SegmentReplicationCheckpointPublisher.java
server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTest.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This PR is a re-cut of https://github.com/opensearch-project/OpenSearch/pull/6520 that includes implementing backpressure and removes the addition of these metrics to NodeStats API.  This is to make it easier to see in this PR how this will be used to implement pressure.  The metrics additions will be in a separate change.
This PR adds backpressure for index operations when Segment Replication is enabled.
This PR implements backpressure mechanisms for segment replication to prevent lagging
replicas from falling too far behind. Writes will be rejected under the following conditions:
1. More than half (default setting) of the replication group is 'stale'.  Defined by setting MAX_ALLOWED_STALE_SHARDS.
2. A replica is stale if it is behind more than MAX_INDEXING_CHECKPOINTS, default 4 AND its …

Implement Segment replication Backpressure

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/SegmentReplicationPerGroupStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/main/java/org/opensearch/index/SegmentReplicationShardStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/SegmentReplicationCheckpointPublisher.java
server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/6563 to 2.x.

[Backport 2.x] Implement Segment replication Backpressure

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java

Mute below two tests from `SegmentReplicationPressureIT` class.
1. testAddReplicaWhileWritesBlocked
2. testWritesRejected
This change also piggyback updating the logging condition inside `OngoingSegmentReplications` which create un-necessary noise on cluster state update events.
#6671 

[Segment Replication] Mute segment replication pressure ITs

---

buildSrc/version.properties

Bump Mockito to 5.2.0 and ByteBuddy to 1.14.2 (skipping changelog since those are only test dependencies)
N/A

Bump Mockito to 5.2.0 and ByteBuddy to 1.14.2

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java
server/src/main/java/org/opensearch/cluster/routing/allocation/Constraint.java
server/src/main/java/org/opensearch/cluster/routing/allocation/ConstraintTypes.java
server/src/main/java/org/opensearch/cluster/routing/allocation/RebalanceConstraints.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java

This change is a follow up of https://github.com/opensearch-project/OpenSearch/pull/6422 where constraint based per index primary balance was introduced. This change adds a new constraint `isPrimaryShardsPerNodeBreached` which is marked breached if a node contains more than average number of primary shards across all indices. This is intentionally applied for allocation and will be applied for rebalancing as fast follow up tracked in https://github.com/opensearch-project/OpenSearch/issues/6642
#6210 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONT …

[Segment Replication] Add global primary shard balance constraint during allocation

---

server/src/test/java/org/opensearch/discovery/InitializeExtensionRequestTests.java

Adding a new Class named InitializeExtensionRequestTests.java to test InitializeExtensionRequest.java 
#6638 

[Extensions] Adding testclass for InitializeExtensionRequest.java

---

server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java

Prevent failures on duplicate segrep request from replica. 
With https://github.com/opensearch-project/OpenSearch/pull/6636, replica shard handles failures from source node gracefully and clears up its local state without failing replica shard. The primary though can still publish a checkpoint, will trigger replica will start a new round of segrep. With this change, primary first cleans up existing state and create a new one based on request parameters. 
#6578  …

[Segment Replication] Override segment replication handler for duplicate request from replica

---

release-notes/opensearch.release-notes-1.3.9.md

With the latest Netty [PR](https://github.com/opensearch-project/OpenSearch/pull/6684) merged to `1.3`. Updating the release doc to include the new version. Will backport this PR to `1.x` and `1.3`

Updated 1.3.9 release note to include latest version of Netty

---

server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java

- Fixes shard allocation for local indices and shards when the node is a dedicated `search` node
- Resolves #6418 

Fix shard allocation scenario with dedicated search nodes

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationShardStatsResponse.java
server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsResponse.java
server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
server/src/main/java/org/opensearch/index/SegmentReplicationPerGroupStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/main/java/org/opensearch/index/SegmentReplicationShardStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
server/src/test/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationActionTests.java

This change updates the existing /_cat/segment_replication API to include backpressure metrics. It does this by returning stats from primary shards for its tracked replication group and merging it with metrics returned from replicas. Primary captured  metrics will now appear by default, with replica per sync events showing when detailed=true is set.
#4478

Segment Replication - Update /_cat/segment_replication API with backpressure metrics.

---

rest-api-spec/src/main/resources/rest-api-spec/api/cat.segment_replication.json
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequest.java
server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java

This PR removes completed_only query parameter from _cat/segment_replication API. By default we will show any on-going segrep events on API if any replication is in progress if not we will show the last completed segrep event metrics.
#6704 

[Segment Replication] Remove completed_only query parameter from _cat/segment_replication API

---

distribution/src/config/opensearch.yml

Tired of looking up `opensearch.experimental.feature.extensions.enabled: true` to develop and test extensions. 
Adding it to the list of experimental features. 

[Extensions] Adding extensions to experimental list of features in opensearch.yml

---

rest-api-spec/src/main/resources/rest-api-spec/api/cat.segment_replication.json
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequest.java
server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java

This PR backports #6725 to 2.x branch

[Backport 2.x] [Segment Replication] Remove completed_only query parameter from _cat/segment_replication API

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java

This change restricts the force round of segment replication (during recovery) for closed indices. It removes the previously added check in https://github.com/opensearch-project/OpenSearch/pull/6611 which allows segment replication during recovery, which is not intended. 

[Segment Replication] Fix segrep compatibility check for closed indices

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

As part of https://github.com/opensearch-project/OpenSearch/pull/6563, primary tracks the target replication checkpoint of target while responding `get_segment_files` call. But, during primary relocation this breaks as primary is not in active primary mode and fails `assertPrimaryMode()` assertion leading to test failures. During primary handoff, the target shard is [activated with primary context](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java#L1718).
Primary shard routing before and after relocation is started. 
```
[2023-03-20T14:19:20,164][INFO ][o.o.i.r.SegmentReplicationSourceService] [node_t7] --> oldRouting [test][44], node[FIVJG3pnRaa-irH_1SjJkg], [P], s[STARTED], a[id=o8B_jOT1QO-XF4JmOSGZLw] …
```

[Segment Replication] Handle update target cp for relocating primary

---

CHANGELOG.md

- Fixes changelog divergence for `Unreleased 2.x` on main once #6763 is merged in.
- N/A

Fix changelog divergence for 2.x on main

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/6754

[Backport 2.x] Bump org.apache.zookeeper:zookeeper from 3.8.0 to 3.8.1

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/6753

[Backport 2.x] Bump org.apache.maven:maven-model from 3.6.2 to 3.9.1

---

server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java

This change fixes a bug in which index create block gets applied when there are no healthy data nodes. In case when there is no healthy data nodes, DiskThresholdMonitor (running on ClusterManager nodes) applies index create block as all nodes (0) are above high watermark (0). This change fixes this issue by not applying index create block when there is no healthy data nodes.

[BUG] Fix index create block getting applied when there is no data nodes healthy

---

.github/workflows/github-merit-badger.yml

Coming from the [build](https://github.com/opensearch-project/opensearch-build/pull/3305) repo. I liked the idea of having merit badges to pull requests that come in the repository.
Tested here: [Sample Job](https://github.com/owaiskazi19/OpenSearch/actions/runs/4421563834/jobs/7752499295)
Will look like this:
Open to discussion about this workflow.

Added github-merit-badger for OpenSearch

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java

- Uses the standard methods defined within `SearchableSnapshotIT` to perform index creation, doc creation and green checks for `testCacheFilesAreClosedAfterUse`
- Current implementation led to incorrect green checks because of missing shard and replica configs 
- Resolves #6686 

Fix document creation process for testCacheFilesAreClosedAfterUse IT

---

server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java

Changes
1. Store decRef handling. Inside finalize step, sometimes the call to fetch [store](https://github.com/opensearch-project/OpenSearch/blob/f40fa82e3667825fd0ba8d4bb17b6959ff7cc4f1/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java#L218) reference fails due to various reasons (ReplicationTarget refCounts to 0 - segrep cancelleation, store already closed - close/delete index etc). This results in skipping the incRef() on ontained store reference. The subsequent call to [decRef](https://github.com/opensearch-project/OpenSearch/blob/f40fa82e3667825fd0ba8d4bb17b6959ff7cc4f1/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java#L262) inside finalize block thus results in extra decRef call on store object, causing failures …

[Segment Replication] Handling resource close

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java

- Fixes test requirement for node type since local writable index is created which requires `data` node capabilities
- Resolves #6738 

Fix node requirement for testPruneFileCacheOnIndexDeletion

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java

Remove feature flag check from `SegmentReplicationSnapshotIT` tests run which prevents these tests run under gradle check. This was missed in https://github.com/opensearch-project/OpenSearch/pull/5941 while backporting https://github.com/opensearch-project/OpenSearch/pull/4959 into `2.x`
#6761 

[Segment Replication] Remove deprecated feature flag check preventing SegmentReplicationSnapshotIT tests run

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java

Mutes `testAllocationWithDisruption` test until it is fixed. Tracked in https://github.com/opensearch-project/OpenSearch/issues/6565
https://github.com/opensearch-project/OpenSearch/issues/6565

[Segment Replication] Mute testAllocationWithDisruption flaky test

---

server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java

Fix testAllConstraints test by using Math.ceil around mocked return values similar to what is used in code. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/6809

[Segment Replication] Fix testAllConstraints test

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/node/DiscoveryNodeRoleIT.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleSettingTests.java

Using `node.master: true` configures both `cluster_manager` and `master` role to a node which is not correct, only one of them should be assigned.
Reference in cdk where it uses legacy settings to bootstrap nodes: https://github.com/opensearch-project/opensearch-cluster-cdk/blob/main/lib/opensearch-config/multi-node-base-config.yml
Allowing only one of the both roles to be attached instead of both - 'master' which is deprecated as part of change of 'master' nomenclature: https://github.com/opensearch-project/OpenSearch/issues/472 - since both the legacy setting `node.master` and `master` role are deprecated - so we need to keep the initial behavior only with deprecated roles and settings. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/6103
The change modifies the role …

Remove 'cluster_manager' role attachment when using 'node.master' deprecated setting

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java

In the previous tests for segmentReplicationPressureIT, the tests covered situations where it expected replicas to be stale and fail behind. However, it didn't take automatic background refreshes that take place at a refresh interval into account. Therefore, in certain situations where we expected the replica to be only 1 or 2 checkpoints behind due to indexing docs, it was actually 3 or 4 checkpoints behind due to checkpoints being sent on automatic refresh as well. 
This caused all the replicas to turn stale and the tests to fail intermittently. By turning off the automatic refresh, we now control when we expect the refreshes to take place which fixes the issue. Ran the tests over 2000 times to check with no failures. 
Resolves #6671  …

[Segment Replication] Fix flaky tests in SegmentReplicationPressureIT

---

modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/UserAgentProcessor.java
modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/20_useragent_processor.yml
plugins/mapper-annotated-text/src/internalClusterTest/java/org/opensearch/index/mapper/annotatedtext/AnnotatedTextFieldMapperTests.java
rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/TypeParsers.java
server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/KeywordFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
server/src/test/java/org/opensearch/rest/action/admin/indices/RestResizeHandlerTests.java
test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4719 to `1.3`

[Backport] [1.3] fix for updating version numbers for deprecation messages (#4719)

---

modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/UserAgentProcessor.java
modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/20_useragent_processor.yml
plugins/mapper-annotated-text/src/internalClusterTest/java/org/opensearch/index/mapper/annotatedtext/AnnotatedTextFieldMapperTests.java
rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/TypeParsers.java
server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/KeywordFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
server/src/test/java/org/opensearch/rest/action/admin/indices/RestResizeHandlerTests.java
test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java

Backport 16797d658125a8c28ddf49413222f30675352dd6 from #4719 to `1.x`

[Backport] [1.x] fix for updating version numbers for deprecation messages (#4719)

---

benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java

The current implementation of the FileCache uses some hand-rolled data structures that would be nice to replace with library implementations. This benchmark will be useful to compare the performance of any future replacements.
Sample results (AWS EC2 Ubuntu machine with 32 vCPUs and 64GB of RAM):
```
Benchmark                   (concurrencyLevel)  (maximumNumberOfEntries)   Mode  Cnt      Score   Error   Units
FileCacheBenchmark.get                       1                     65536  thrpt        2243.092          ops/ms
FileCacheBenchmark.get                       1                   1048576  thrpt         950.818          ops/ms
FileCacheBenchmark.get                       8                     65536  thrpt        5651.150          ops/ms
FileCacheBenchmark.get                       8 …
```

Implement microbenchmark for FileCache

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java

Mute SearchableSnapshotIT.testCacheFilesAreClosedAfterUse pending fix

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
server/src/main/java/org/opensearch/cluster/routing/FailAwareWeightedRouting.java
server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingUtils.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/FailAwareWeightedRoutingTests.java
server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java

Enhance search preference for Weighed Round Robin shard routing
- https://github.com/opensearch-project/OpenSearch/issues/6857
- https://github.com/opensearch-project/OpenSearch/issues/6858
- https://github.com/opensearch-project/OpenSearch/issues/6862

Enhance search preference based routing for WRR

---

buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
buildSrc/src/testKit/thirdPartyAudit/build.gradle

The new version was released a minute ago: https://github.com/policeman-tools/forbidden-apis/wiki/Changes#version-35-released-2023-03-27
Summary of relevant changes for Opensearch:
- Faster startup time as Gradle plugin initialization was compiled statically and is part of JAR file
- Support for Java 20 signatures and bytecode of Java 21

Upgrade forbiddenapis to 3.5.1

---

server/src/main/java/org/opensearch/extensions/rest/ExtensionRestResponse.java
server/src/main/java/org/opensearch/rest/RestRequest.java
server/src/test/java/org/opensearch/extensions/rest/ExtensionRestResponseTests.java

Companion PRs (this one must be merged first of three):
- SDK: https://github.com/opensearch-project/opensearch-sdk-java/pull/623
- AD: https://github.com/opensearch-project/anomaly-detection/pull/848
Extensions do not use all the internal components of a `RestRequest` and initial implementation double-purposed the `ExtensionsRestRequest` object used in transport as the object that Extensions would need to handle.  However, increasing use of the methods on this object are ending up duplicating a lot of code.  It makes a lot more sense to just recreate a `RestRequest` object from the parameters passed in this request.
While this is marked api, it is only used behind feature-flagged code and will not break any BWC.
Part of [SDK #431](https://github.com/opensearch-project/opensearch-sdk-java/ …

[Extensions] Update ExtensionRestResponse to handle RestRequest object

---

server/src/main/java/org/opensearch/indices/flush/SyncedFlushService.java

Followup on 35e6389be49654fed8acb09af51f68b51d889f55 since `SyncedFlushService` was removed in `2.x` and later

[Backport] [1.3] fix for updating version numbers for deprecation messages (SyncedFlushService)

---

buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
buildSrc/src/testKit/thirdPartyAudit/build.gradle

Backport https://github.com/opensearch-project/OpenSearch/pull/6840 to `2.x`

[Backport] [2.x] Upgrade forbiddenapis to 3.5.1 (#6840)

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java

- Fixes `testCacheFilesAreClosedAfterUse` to check all the `search` nodes for cache locations
- There are two checks - one which happens after restore and another which happens after deletions
- Ensures that the index exists on cache when restored and cache folder for the location is cleared when index is deleted
- Resolves #6888 

Fix testCacheFilesAreClosedAfterUse for Searchable Snapshots

---

server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java

This expands on #6914 a bit to include the full cache access. Adding an entry to the cache can result in an eviction, and the subsequent file deletion needs the elevated permissions as well.

Include all file cache access in privileged section

---

client/rest-high-level/src/test/java/org/opensearch/client/documentation/IndicesClientDocumentationIT.java
rest-api-spec/src/main/resources/rest-api-spec/test/indices.flush/10_basic.yml

Missed that Gradle check was unstable, fixing tests for https://github.com/opensearch-project/OpenSearch/pull/6918

[Backport] [1.3] fix for updating version numbers for deprecation messages (tests)

---

server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java

There was a regression after merging #6424. Basically, we lost ability to merge different numeric types sort results.
i.e. if Index-1 has field mapping Int, but Index-2 has field mapping Long, earlier it was supported to sort across these two indices. That's the exact problem we tried to solve in #6424, but that worked only on single node cluster. For multi node clusters, since SortedNumericSortField is getting serialized as SortField only, while merging results from different shards, we are not able to determine correctly if wider numeric type should be applied or not.
This PR fixes that.
This issue is caught by @reta while adding integ tests for this scenario #6901 . Huge thanks to reta for it. …

Fix sort in case of different numeric field types between indices

---

buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java

The `destructiveDistroTest.docker` task was already registered here:
https://github.com/opensearch-project/OpenSearch/blob/c85d33e2e487242eb5ad60b64567ca2ec14fc88f/buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java#L245
Which is called here:
https://github.com/opensearch-project/OpenSearch/blob/c85d33e2e487242eb5ad60b64567ca2ec14fc88f/buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java#L107
Which causes duplicate registration here:
https://github.com/opensearch-project/OpenSearch/blob/c85d33e2e487242eb5ad60b64567ca2ec14fc88f/buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java#L124
This fixes the `TODO` by adding a test whether a task is already registered in place of the exception catch/warning.
Fixes #1640 (you're welcome).
By …

Don't register destructiveDistroTest.docker twice

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_mixed.yml
server/src/main/java/org/opensearch/action/search/SearchPhaseController.java

Fixing SortField comparison to use equals instead of reference equality
N/A

Fixing SortField comparison to use equals instead of reference equality

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/IndicesQueryCache.java
server/src/test/java/org/opensearch/indices/IndicesQueryCacheTests.java

In the edge case where shardStats is an empty map (caused by removing the last document from an index through a means other than clearing the index), the stats map is also empty. However this case also leads to divide-by-zero calculation which gives a weight of `Double.POSITIVE_INFINITY`.  This rounds to `Long.MAX_VALUE` for additionalRamBytesUsed for the shard.
Then later in calculating total memory, the max long value is added to other fields, resulting in overflow.
Fixes #4474
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …

Avoid negative memory result in IndicesQueryCache stats calculation

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
server/src/main/java/org/opensearch/cluster/routing/FailAwareWeightedRouting.java
server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingUtils.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/FailAwareWeightedRoutingTests.java
server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java

(cherry picked from commit d8d6e7324adb4be088cab8e1fa5833e18ef19109)
Backport of https://github.com/opensearch-project/OpenSearch/pull/6834
NA

[Backport to 2.x] Enhance search preference based routing for WRR (#6834)

---

server/src/main/java/org/opensearch/common/io/VersionedCodecStreamWrapper.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java

While reading segment metadata files, we validate header and footer. Currently, reading the footer was failing intermittently. We are reading the footer separately now to avoid issues. 
https://github.com/opensearch-project/OpenSearch/issues/6824

Validate checksum in footer separately for segment metadata files

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java

- `_cat/recovery` API provide details of progress of recovery. This helps in getting insight especially when shards are bigger in size.
- While restoring remote store backed index, entry is created but there is no data shown under `_cat/recovery`.
- This feature request adds the support of tracking segment download progress.
- https://github.com/opensearch-project/OpenSearch/issues/6821

[Remote Store] Add file details to recoveryState while downloading segments from remote store

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

- When remote translog is enabled for an index, replication operation is limited to primary term validation and does not update local checkpoint at replica, so the local checkpoint at replica can be less than globalCheckpoint.
- This fails the assertion at following code:
https://github.com/opensearch-project/OpenSearch/blob/1856090a87e86b64f87aff81f2be4bc3879fb4b9/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L3071-L3088
- https://github.com/opensearch-project/OpenSearch/issues/6193
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CON …

Fix assertion failure in updateGlobalCheckpointOnReplica() with remote translog

---

modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/UserAgentProcessor.java
modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/20_useragent_processor.yml
plugins/mapper-annotated-text/src/internalClusterTest/java/org/opensearch/index/mapper/annotatedtext/AnnotatedTextFieldMapperTests.java
qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/TypeParsers.java
server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/KeywordFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java

(cherry picked from commit 16797d658125a8c28ddf49413222f30675352dd6)
Backport to 2.6 since 2.x BWC tests fail:
```
java.lang.AssertionError: Failure at [indices.split/30_copy_settings:38]: got unexpected warning header [
299 OpenSearch-2.6.1-SNAPSHOT-5bbb99a68463779301eb9c34be1add1d6d1d4614 "parameter [copy_settings] is deprecated and will be removed in 8.0.0"
]
```
See please https://build.ci.opensearch.org/job/gradle-check/13326/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_indices_split_30_copy_settings_Copy_settings_during_split_index_/ …

[Backport] [2.6] fix for updating version numbers for deprecation messages (#4719) (#6848)

---

server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java

- Currently, we have a separate `RemoteDirectoryFactory` interface to create an instance of `RemoteDirectory`.
- This was created as it required a separate `Repository` instance as an input. But in https://github.com/opensearch-project/OpenSearch/pull/3703, we changed the parameter type from `Repository` to `String` (repository name).
- As repository name is part of index settings and as index settings is one of the parameters to `DirectoryFactory` interface, `RemoteDirectoryFactory` becomes redundant.
- https://github.com/opensearch-project/OpenSearch/issues/6929 …

Use DirectoryFactory interface to create remote directory

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

Fixes the flakyness of this test by waiting for cluster to process the replica shard failure. Without this wait, doc ingestion & shard cancellation run in parallel. The test also uses existing utilities used for doc count assertion which waits for a longer time i.e. `1 minute`.  Ran test with fix 100 times without failure. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/6885

[Segment Replication] Fix flaky testReplicaHasDiffFilesThanPrimary test

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This change aims to fail segment replications between the primary and replica if they are utilizing differing lucene codec versions. This is to avoid the current behavior of failing the replica shard in such situations.
Resolves #6616 

[Segment Replication] Compatibility check for differing lucene codec versions

---

benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/monitor/MonitorService.java
server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
server/src/main/java/org/opensearch/monitor/fs/FsService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
server/src/test/java/org/opensearch/node/NodeTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

- Adds circuit breaker logic for file cache
- The logic re-utilizes one of the child circuit breakers to check if the parent has gone over the threshold defined as a part of [HierarchyCircuitBreakerService](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java#L92-L104)
---
Two possible solutions were assessed - 
1. Add a new [child memory breaker](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/breaker/ChildMemoryCircuitBreaker.java#L48) which will keep track of memory usage by the file cache
2. Use a pre-existing child breaker to keep track of total memory usage (tracked by the parent breaker)
Approach 1 would be ideal if there was a fixed …

Add circuit breaker support for file cache

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
server/src/main/java/org/opensearch/index/store/ReplicaFileTracker.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java

Backports https://github.com/opensearch-project/OpenSearch/pull/6765 to `2.x`

[Segment Replication] Add PIT/Scroll compatibility with Segment Replication

---

benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/monitor/MonitorService.java
server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
server/src/main/java/org/opensearch/monitor/fs/FsService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
server/src/test/java/org/opensearch/node/NodeTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

(cherry picked from commit 06128a904964ce43813ebc8164417a5633d414a2)
- Backports #6591 to 2.x
- N/A

[Backport 2.x] Add circuit breaker support for file cache (#6591)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java

This PR fixes the flaky test SegmentReplicationStatsIT.testSegmentReplicationStatsResponse.
Found this test failing, when running locally:
```
REPRODUCE WITH: ./gradlew 'null' --tests "org.opensearch.indices.replication.SegmentReplicationStatsIT.testSegmentReplicationStatsResponse" -Dtests.seed=37F84E12C985FFEF -Dtests.locale=ar -Dtests.timezone=Pacific/Gambier -Druntime.java=14
java.lang.NullPointerException
at __randomizedtesting.SeedInfo.seed([37F84E12C985FFEF:7E31C0204D86B829]:0)
at org.opensearch.indices.replication.SegmentReplicationStatsIT.lambda$testSegmentReplicationStatsResponse$0(SegmentReplicationStatsIT.java:76)
at org.opensearch.test.OpenSearchTestCase.assertBusy(OpenSearchTestCase.java:1048)
at org.opensearch.indices.replication.SegmentReplicationStatsIT.testSegmentReplicati …
```

[Segment Replication]Fix flaky test SegmentReplicationStatsIT.testSegmentReplicationStatsResponse

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

This PR backports https://github.com/opensearch-project/OpenSearch/pull/6850
Resolves https://github.com/opensearch-project/OpenSearch/issues/6606

[Backport 2.x] [Segment Replication]Add background async task to fail stale replica shards.

---

CHANGELOG.md
distribution/src/bin/opensearch-env
distribution/src/bin/opensearch-env.bat

Right now it is not possible to set a fixed OPENSEARCH_HOME directory.
This is required for Nix packaging as the OpenSearch files lives inside the nix store (/nix/store/random-string-opensearch/bin/opensearch). [Therefore we needed to patch this to allow us to set a custom directory.](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/search/opensearch/opensearch-home-fix.patch) 
If you need maybe more background to understand we setup a own empty Opensearch home and symlink required files: https://github.com/NixOS/nixpkgs/blob/fc46a9d1e2b30321a2497e413eb1562c9cfda5b6/nixos/modules/services/search/opensearch.nix#L185-L217

feat: allow overwrite opensearch home

---

server/src/main/java/org/opensearch/indices/IndicesService.java

When we are restoring snapshot with storage type as REMOTE_SNAPSHOT we should use ReadOnlyEngine. But currectly we are wiring up a NRTReplicationEngineFactor instead of `ReadOnlyEngine`.
This PR moves up the `isRemoteSnapshot()` check on index setting before we check if `isSegRepEnabled()`.  This way be wire `ReadOnlyEngine` when using remote snapshot.
Resolves #7034 

[Segment Replication] Fix SearchableSnapshotIT tests failing with segment replication enabled indices

---

server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java

The cleaner was too aggresive with cleaning up the cache and would delete the entire index directory within the cache when a shard was removed. This is not correct when multiple shards for a given index are on the same node.
Closes #6996

Do not delete entire index cache on shard removal

---

CHANGELOG.md
build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7067 to `1.x`

[Backport] [1.x] Bump org.gradle.test-retry from 1.5.1 to 1.5.2 (#7067)

---

CHANGELOG.md

Fixes the changelog of https://github.com/opensearch-project/OpenSearch/pull/6956

fix: move changelog to 2.x

---

modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/30_search.yml
rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml

Fix Auto Backport ticket #7052: Update version to 2.7.0 version in IT tests
https://github.com/opensearch-project/OpenSearch/issues/1018

Extend the version range to run flat-object field REST Yaml test on 2.7.0 

---

CHANGELOG.md
build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7067 to `2.x`

[Backport] [2.x] Bump org.gradle.test-retry from 1.5.1 to 1.5.2 (#7067)

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
server/src/test/java/org/opensearch/env/NodeRepurposeCommandTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java

So in this issue, i removed the duplicate <node-lock-id> that was present in the cache path generated.
Closes #7059

Removed duplicated 'nodeId' in cache path #7059

---

CHANGELOG.md
build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7067 to `1.3`

[Backport] [1.3] Bump org.gradle.test-retry from 1.5.1 to 1.5.2 (#7067)

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7070 to `1.x`

[Backport] [1.x] Bump org.apache.hadoop:hadoop-minicluster from 3.3.4 to 3.3.5 in /test/fixtures/hdfs-fixture (#7070)

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Using an `ImmutableOpenMap` in `o.o.index.engine.SegmentsStats#filesSizes` is overkill since all we care about is public facing API not leaking the `filesSizes` collection. To remove all of the unnecessary temporary object copies saddled with using `ImmutableOpenMap` internally, this PR refactors the SegmentsStats#filesSizes variable from an `ImmutableOpenMap` to an unmodifiable java.util.Map. It also refactors the internal only used `FILE_DESCRIPTIONS` static variable to an unmodifiable java.util.Map in order to completely remove `SegmentsStats` dependency on hppc based `ImmutableOpenMap`.
relates #5910

[Refactor] SegmentsStats#filesSizes from ImmutableOpenMap to java.util.Map

---

server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java

- Fixes improper ref count for objects within file cache on cache restore
- Resolves #7097 

Fix file cache active usage on restore

---

CHANGELOG.md
plugins/repository-gcs/build.gradle

Adds this PR to changelog and updates `plugins/repository-gcs/build.gradle` to user checker-qual 3.32.0 when compiling to prevent RequireNonNull error

Dependabot/gradle/plugins/repository gcs/com.google.cloud google cloud storage 2.20.2

---

CHANGELOG.md
distribution/src/bin/opensearch-env
distribution/src/bin/opensearch-env.bat

Manual cherry pick of https://github.com/opensearch-project/OpenSearch/pull/6956 to 1.x branch

feat: allow overwrite opensearch home to 1.x

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7070 to `1.3`

[Backport] [1.3] Bump org.apache.hadoop:hadoop-minicluster from 3.3.4 to 3.3.5 in /test/fixtures/hdfs-fixture (#7070)

---

CHANGELOG.md
distribution/src/bin/opensearch-env
distribution/src/bin/opensearch-env.bat

Manual cherry pick of https://github.com/opensearch-project/OpenSearch/pull/6956 to 2.x branch

feat: allow overwrite opensearch home to 2.x

---

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java

Close MultiFileWriter on segment replication cancellation. 
This bug appears rarely and happen during failover where promoted replica [cleans up](https://github.com/opensearch-project/OpenSearch/blob/0db20d99d4e06ddb261429466a8072501cc15941/server/src/main/java/org/opensearch/index/store/Store.java#L948) its store while having multiple file copy operations in progress. The clean up deletes temporary replication files which conflict with one of file copy thread's validation. Existing cancellation skips writer close as target ref count does not goes to `0` when there are multiple file copy operations is in progress. Target is [inc'ref](https://github.com/opensearch-project/OpenSearch/blob/0db20d99d4e06ddb261429466a8072501cc15941/server/src/main/java/org/opensearch/indices/replication/common/ …

[Segment Replication] Close writer on segment replication cancellation

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/IndicesQueryCache.java
server/src/test/java/org/opensearch/indices/IndicesQueryCacheTests.java

Backport c0a8cf8823341cf92b932fe3d12909d427090a2f from #6917.

[Backport 1.3] Avoid negative memory result in IndicesQueryCache stats calculation

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/GlobalIT.java
server/src/main/java/org/opensearch/search/aggregations/AggregationPhase.java

For the case when profile is enabled the check for GlobalAggregator operator will fail as it gets wrapped in the Profiling Aggregator. To fix this the check considers both the cases with profile enabled/disabled and verifies if the unwrapped aggregator instance is of Global type or not.
https://github.com/opensearch-project/OpenSearch/issues/7088

GlobalAggregation with profile option enabled returns incorrect result

---

CHANGELOG.md
server/src/main/java/org/opensearch/rest/BaseRestHandler.java

BaseRestExtensionHandler in opensearch-sdk needs to use unrecognized method of BaseRestHandler. Therefore to follow DRY principle I have added a new method unrecognizedStrings in BaseRestHandler and then copied the definition of current unrecognized method in it. Then I called unrecognizedString method from unrecognized method. 
From BaseRestExtensionHandler I will just call the unrecognizedMethod. This change is done so that if in future there is some change in unrecognized method then it reflects for extensions also. …

[Extensions] Increased visibility of BaseRestHandler’s `unrecognized` method using a new public `unrecognizedStrings` method

---

CHANGELOG.md
server/src/main/java/org/opensearch/rest/BaseRestHandler.java

Backport [9453ca3](https://github.com/opensearch-project/OpenSearch/commit/9453ca3906e6a2163051208b6dd011e0e0ddfc9e) from [7125](https://github.com/opensearch-project/OpenSearch/pull/7125)

[Backport 2.x] Increased visibility of BaseRestHandler’s `unrecognized` method using a new public `unrecognizedStrings` method.

---

server/src/main/java/org/opensearch/extensions/rest/RegisterRestActionsRequest.java
server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java
server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java

Companion PR on SDK: https://github.com/opensearch-project/opensearch-sdk-java/pull/666
Adds the ability to handle Deprecated and Replaced Routes to the ExtensionRestHandler.  This will permit (nearly) identical syntax for plugin migration, and provide backwards compatibility to extension users.
- Routes were already registered.
- Deprecated routes are just a wrapper around Routes, which add a log message.
- Replaced routes are a fancy user interface to simultaneously register Routes and Deprecated Routes.
The OpenSearch integration adds a new list to the existing registration request.  In addition to the method and path sent for routes, deprecated routes have a deprecationMessage included.  This is included in a separate list where the message immediately follows the method/path.
Fixes …

[Extensions] Handle Deprecated and Replaced Routes in Extension Rest Handlers

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/bulk/BackoffPolicy.java
server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java

Backporting PR for making throttling retry setting as dynamic setting.
Original PR: https://github.com/opensearch-project/OpenSearch/pull/6998

[Backport 2.x] Make cluster manager throttling retry delay as dynamic setting

---

server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodeInfo.java
server/src/main/java/org/opensearch/action/search/SearchRequest.java

The search pipelines code should be available starting in OpenSearch 2.7, so compatibility checks should start from that version.
Note that the Gradle checks for this PR may fail until https://github.com/opensearch-project/OpenSearch/pull/7075 is merged.
Follow-on from https://github.com/opensearch-project/OpenSearch/pull/7075, which is a backport of https://github.com/opensearch-project/OpenSearch/pull/6587, which resolves https://github.com/opensearch-project/search-processor/issues/97.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md# …

[SearchPipelines] Lower compatibility version to 2.7

---

benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
server/src/main/java/org/opensearch/index/store/remote/filecache/CachedIndexInput.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java

As detailed in #7031, we should not guard the download operations with the cache lock as it is too coarse-grained. This refactoring moves the long running operation outside of the cache operations.
Resolves #7031

Download block after adding cache entry

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
server/src/main/java/org/opensearch/cluster/ClusterModule.java
server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/util/FeatureFlags.java
server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
server/src/test/java/org/opensearch/node/NodeTests.java

- Removes feature flag for searchable snapshots
- Resolves #7115 

Remove feature flag for searchable snapshots

---

server/src/main/java/org/opensearch/index/seqno/GlobalCheckpointSyncAction.java
server/src/test/java/org/opensearch/index/seqno/GlobalCheckpointSyncActionTests.java

Currently there are two uploads on every write. The second upload contains no operations and just updates global ckp. This ckp is not used in restore/recovery/failover
(https://github.com/opensearch-project/OpenSearch/issues/7025)

Avoid Syncing Translog on Global Ckp Sync for Remote Translog

---

server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java

Fixes flaky integ tests
https://github.com/opensearch-project/OpenSearch/issues/7128

Fix flaky integ tests - CreateRemoteIndexIT,CreateRemoteIndexTranslogDisabledIT,CreateRemoteIndexClusterDefaultDocRep

---

server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java

Some cosmetic changes here to make the stat names consistent with [RequestCacheStats][1] and [QueryCacheStats][2] that already exist in the API.
I've also removed the 'replaced' and 'removed' stats. These are internal cache details that I don't think will be useful to a user. We can always add them back later if needed.
Note this is backward incompatible, but this is okay as this will get in ahead of the next release which removes the feature flag from searchable snapshots.
[1]: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/cache/request/RequestCacheStats.java
[2]: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/cache/query/QueryCacheStats.java …

Make file cache stats consistent with other APIs

---

server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java

(cherry picked from commit 632eb44a541b28ef16ed261904b45d74b84f3b9f)
Backport for https://github.com/opensearch-project/OpenSearch/pull/7141
NA

Fix flaky integ remote store settings integ tests  (#7141)

---

CHANGELOG.md
gradle/missing-javadoc.gradle
libs/core/src/main/java/org/opensearch/core/ParseField.java
plugins/events-correlation-engine/build.gradle
plugins/events-correlation-engine/src/internalClusterTest/java/org/opensearch/plugin/correlation/EventsCorrelationPluginTransportIT.java
plugins/events-correlation-engine/src/javaRestTest/java/org/opensearch/plugin/correlation/EventsCorrelationPluginRestIT.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/EventsCorrelationPlugin.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/IndexCorrelationRuleAction.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/IndexCorrelationRuleRequest.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/IndexCorrelationRuleResponse.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/model/CorrelationQuery.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/model/CorrelationRule.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/model/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/resthandler/RestIndexCorrelationRuleAction.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/resthandler/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/transport/TransportIndexCorrelationRuleAction.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/transport/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/settings/EventsCorrelationSettings.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/settings/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/utils/CorrelationRuleIndices.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/utils/IndexUtils.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/utils/package-info.java
plugins/events-correlation-engine/src/main/resources/mappings/correlation-rules.json
plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/EventsCorrelationPluginTests.java

add correlation rule layer for events-correlation-engine
#6854 

add correlation rule layer for events-correlation-engine

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_mixed.yml

Change assertion to use value match instead of array match to eliminate the client/language specific mismatches  (see please https://github.com/opensearch-project/opensearch-rs/pull/149). 
```
'free::search::_260_sort_mixed::search_across_indices_with_mixed_long_and_double_numeric_types' panicked at 'assertion failed: `(left == right)`
left: `Array [Number(1.22337203685477581E18)]`,
right: `Array [Number(1.2233720368547758e18)]`: expected value json["hits"]["hits"][0]["sort"] to match Array [Number(1.2233720368547758e18)] but was Array [Number(1.22337203685477581E18)]', yaml_test_runner/tests/free/search/_260_sort_mixed.rs:77:5
```
The array based comparisons (in Rust at least) uses string based approach but we should compare numbers instead.
N/A
By submitting this pull request, I confirm …

Change assertion to use value match instead of array match

---

server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

Unmuting TranslogTransferManagerTests for Windows. Tested [here](https://github.com/opensearch-project/OpenSearch/issues/5923#issuecomment-1469138437)
Fixes https://github.com/opensearch-project/OpenSearch/issues/5923

Unmuting TranslogTransferManagerTests for Windows

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java

This PR enables segment replication back pressure setting `SEGMENT_REPLICATION_INDEXING_PRESSURE_ENABLED` by default.
Resolves #7182 

[Segment Replication] Enable Segment Replication Backpressure setting by default.

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java

Change the logic of IndexShard.getLatestReplicationCheckpoint to actually read local commit (if any) and return the current checkpoint instead of returning empty checkpoint when index is closed. 
Resolves #6828 

[Segment Replication] Handle IndexShard.getLatestReplicationCheckpoint for closed indices

---

modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java

Fixing the GeoTileIT#testMultivaluedGeoPointsAggregation testcase
The issue was happening because we encode the GeoPoint as long and error comes in the precision due to that encoding. The error was not taken care while generating the exepected tiles count for expected output. The error was happening for a tile: 13/1627/7465
The idea to fix this is simple enough, while generating the expected buckets for geo-points I will encode and decode the lat-lon values. This will make sure that the precision loss comes in during the Tile creation, as showed in the below snippet. 
Code ref: https://github.com/opensearch-project/OpenSearch/blob/9386cde55a55d8b4779a0c58ba9a6240d04cbe2c/modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java#L160-L166
``` …
```

[#7101] Fixing the GeoTileIT#testMultivaluedGeoPointsAggregation testcase

---

server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

This PR adds primary mode check before calling setLatestReplicationCheckpoint() to avoid assertion failure.
```
апр 17, 2023 1:28:46 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[opensearch[node_t5][refresh][T#1],5,TGRP-IndexPrimaryRelocationIT]
java.lang.AssertionError
at __randomizedtesting.SeedInfo.seed([C06CAB01F9EA9D4A]:0)
at org.opensearch.index.seqno.ReplicationTracker.setLatestReplicationCheckpoint(ReplicationTracker.java:1214)
at org.opensearch.index.shard.IndexShard.onCheckpointPublished(IndexShard.java:1771)
at org.opensearch.indices.replication.checkpoint.SegmentReplicationCheckpointPublisher.publish(SegmentReplicationCheckpointPublisher.java:37)
at …
```

[Segment Replication] Fix Assertion failure on primary mode.

---

server/src/main/java/org/opensearch/common/unit/Fuzziness.java
server/src/test/java/org/opensearch/common/unit/FuzzinessTests.java

Building on #5805. After checking back on my previous PR for `Fuzziness`, I noticed that negative values (both integers and floats) were not validated correctly (as per [the official documentation](https://opensearch.org/docs/latest/query-dsl/full-text/#fuzzy-query-options), only positive values are allowed. Floating point values kept in for [this test](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/java/org/opensearch/common/unit/FuzzinessTests.java#L49)). I've added a negative value check for both integers and floats in `Fuzziness.java` and included some values in the unit tests to reflect the changes.
Sample behavior:
```
$ curl -XGET 'http://localhost:9200/_search?pretty' -d '{"query":{"match_bool_prefix":{"date":{"query":"1972-07-04 00:00:00", …
```

Adding more validation for fuzzy queries

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java

Prevent cancellation of allocation ids which are marked in-sync inside replication tracker. More details in https://github.com/opensearch-project/OpenSearch/issues/7213
https://github.com/opensearch-project/OpenSearch/issues/7213
RecoveryWhileUnderLoadIT.testRecoverWhileRelocating passes 500 times without failure. 

[Segment Replication] Prevent cancellation of ReplicationTracker's in-sync allocation ids

---

server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java

This is a common case and info level logging will result in a ton of unhelpful log entries.

Tweak log level to avoid spamming log

---

server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
server/src/main/java/org/opensearch/tasks/TaskManager.java
server/src/main/java/org/opensearch/tasks/consumer/TopNSearchTasksLogger.java
server/src/test/java/org/opensearch/tasks/consumer/TopNSearchTasksLoggerTests.java

We introduced Task Resource Consumer to log task resource information at a specified interval as a part of https://github.com/opensearch-project/OpenSearch/pull/2293. However, newly introduced dynamic settings `cluster.task.consumers.top_n.size` and `cluster.task.consumers.top_n.frequency` are not registered under ClusterSettings.BUILT_IN_CLUSTER_SETTINGS and hence not recognised when trying to change the value. We need to register them in ClusterSettings.BUILT_IN_CLUSTER_SETTINGS to make them dynamic. Making this change to fix the issue.
https://github.com/opensearch-project/OpenSearch/issues/6708 …

Add TopNSearchTasksLogger settings to Cluster Settings

---

server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
server/src/main/java/org/opensearch/tasks/TaskManager.java
server/src/main/java/org/opensearch/tasks/consumer/TopNSearchTasksLogger.java
server/src/test/java/org/opensearch/tasks/consumer/TopNSearchTasksLoggerTests.java

We introduced Task Resource Consumer to log task resource information at a specified interval as a part of https://github.com/opensearch-project/OpenSearch/pull/2293. However, newly introduced dynamic settings `cluster.task.consumers.top_n.size` and `cluster.task.consumers.top_n.frequency` are not registered under ClusterSettings.BUILT_IN_CLUSTER_SETTINGS and hence not recognised when trying to change the value. We need to register them in ClusterSettings.BUILT_IN_CLUSTER_SETTINGS to make them dynamic. Making this change to fix the issue.
https://github.com/opensearch-project/OpenSearch/issues/6708 …

Add TopNSearchTasksLogger settings to Cluster Settings (#6716)

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java

Two changes here: First, when snapshotting a searchable snapshot index (or snapshotting a full cluster that contains searchable snapshot indices) then we will snapshot the index metadata which includes the pointer to the original snapshot, but skip copying the data since it already exists in the source snapshot. Second, when restoring an index from a snapshot that is itself a searchable snapshot index, then it must be handled as such and restored as a searchable snapshot index.
Resolves #7204
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING …

Fix snapshotting searchable snapshot indexes

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7188 to 2.x

[Backport] [2.x] Bump com.netflix.nebula:gradle-info-plugin from 12.0.1 to 12.1.0 (#7188)

---

sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecPlugin.java
sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java

OpenSearch supports: `default`, `lucene_default`, `best_compression`, and `ZSTD` compression codecs. This PR changes `ZSTD` to `zstd` to maintain consistency in naming compression codecs. 
A follow up to PR: https://github.com/opensearch-project/OpenSearch/pull/7171.

Use lowercase letters for zstd, zstdnodict compression codecs.

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/main/java/org/opensearch/indices/IndicesModule.java

This PR makes SegmentReplicationPressureService a Singleton class. This way we will only have one instance of SegmentReplicationPressureService per node.
This PR will resolve the bug of `rejected_requests` column not getting updated in  `_cat/segment_replication` API.
-> Initially we were having two instances of SegmentReplicationPressureService. One intstance being used by backpressure mechanism and another instance being used by SegmentReplicationStatsAction class (used by _cat/segment_replication API).
-> As we were having two instances of SegmentReplicationStatsAction class, the changes made by backpressure mechanism are not updated to another instance, so the value of `rejected_requests` is always being 0 and never getting updated.
-> The solution here would be to make …

[Segment Replication] Make SegmentReplicationPressureService a Singleton class and fix bug of rejected_requests reporting incorrect value

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java

This PR Reverts #7183 enabling Segment Replication Backpressure as default setting. By Enabling this setting by default we are impacting the throughput of document replication.
Resolves #7293 

Revert Enabling Segment Replication Backpressure setting by default

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java

- Restoring searchable snapshots with indices backed up with the setting `index.store.type` leads to wrong ordering for store type settings, causing the restore to be of the original configuration set on the index at backup which can be `fs` / a local restored index instead. (Sample code which does [that with benchmarks here](https://github.com/search?q=repo%3Aopensearch-project%2Fopensearch-benchmark-workloads%20%22index.store.type%22&type=code))
- This PR fixes the ordering of the settings to enable searchable snapshot index restore with the appropriate store type, irrespective of the original store type configuration for the index.
- N/A …

Fix store type settings ordering for searchable snapshots

---

client/rest-high-level/src/main/java/org/opensearch/client/indices/IndexTemplateMetadata.java
client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexTemplatesResponseTests.java
server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
server/src/main/java/org/opensearch/action/admin/indices/resolve/ResolveIndexAction.java
server/src/main/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverService.java
server/src/main/java/org/opensearch/cluster/DiffableUtils.java
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
server/src/main/java/org/opensearch/gateway/DanglingIndicesState.java
server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
server/src/main/java/org/opensearch/snapshots/EmptySnapshotsInfoService.java
server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/main/java/org/opensearch/snapshots/SnapshotShardSizeInfo.java
server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
server/src/test/java/org/opensearch/cluster/metadata/IndexTemplateMetadataTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
server/src/test/java/org/opensearch/cluster/serialization/DiffableTests.java
server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java

Refactors usage of ImmutableOpenMap in IndexMetadata to java.util.Map. This continues the removal of the HPPC dependency in core.
relates #5910

[Refactor] ImmutableOpenMap to j.u.Map in IndexMetadata

---

.github/dependabot.yml
CHANGELOG.md
build.gradle
buildSrc/build.gradle
distribution/build.gradle
distribution/docker/build.gradle

Loudly disables bwc tests when running build on Mac. If we wanted to support a proper Mac distribution we would need to produce bwc artifacts for testing, which I believe means making a manual build once to get bootstrapped, then we would get rid of the `> Project :qa:full-cluster-restart declares a dependency from configuration 'opensearch_distro_extracted_testclusters-qa-full-cluster-restart-v2.1.1-1-2.1.1-' to configuration 'expanded-darwin-arm64-tar' which is not declared in the descriptor for project :distribution:bwc:bugfix.` error.
```
$ ./gradlew build
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
> Configure project :
========================= WARNING =========================
Backwards compatibility tests are disabled!
See …
```

Enable ./gradlew build on MacOS (M1) by loudly disabling bwc tests.

---

CHANGELOG.md
distribution/tools/plugin-cli/build.gradle
distribution/tools/plugin-cli/licenses/commons-compress-1.23.0.jar.sha1
distribution/tools/plugin-cli/licenses/commons-compress-LICENSE.txt
distribution/tools/plugin-cli/licenses/commons-compress-NOTICE.txt
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java

More details about the vulenrability can be found on https://github.com/snyk/zip-slip-vulnerability
ZipInputStream can cause a potential [zipslip vulnerability](https://github.com/snyk/zip-slip-vulnerability). This PR aims at fixing the vulnerability by replacing it with ZipFile class.
-

Replaces ZipInputStream with ZipFile to fix Zip Slip vulnerability

---

.github/pull_request_template.md

GitHub requires a magic word to properly link a PR to an issue so that the issue is automatically closed when the PR is merged.

Add keyword to auto-close issue in PR template

---

server/src/test/java/org/opensearch/search/aggregations/metrics/MedianAbsoluteDeviationAggregatorTests.java

This change addresses an inappropriate/incorrect error bound on TDigest estimates on medians used in MedianAbsoluteDeviationAggregatorTests. TDigest algorithm's error is proportional to q*(1-q) where q is the percentile and is at worst in the middle (median). 0.1 is more appropriate for 90 percentile (q = 0.9).
#4789 
- [ x] Commits are signed per the DCO using --signoff

Fix flakiness of testQueryFiltering due to error bound

---

release-notes/opensearch.release-notes-2.7.0.md

moves flat object from the changed to added section. didn't think this was notable enough for CHANGELOG.
N/A
- [  x ] Commits are signed per the DCO using --signoff
- [  ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

moved flat object from changed to added b/c it's new 

---

test/framework/src/main/java/org/opensearch/test/rest/RestActionTestCase.java

According to the comment, verifier should return either a subclass of ActionResponse or null. With previous signature, it can only return null. This commit allows the verifier to return a subclass of ActionResponse so that test case can return a desired ActionResponse.
N/A

Make verifier return type as ActionResponse

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7311 to `2.x`

[Backport] [2.x] Bump com.netflix.nebula:nebula-publishing-plugin from 20.2.0 to 20.3.0 (#7311)

---

CHANGELOG.md
distribution/packages/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7310/files to `2.x`

[Backport] [2.x] Bump com.netflix.nebula.ospackage-base from 11.2.0 to 11.3.0 in /distribution/packages (#7310)

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7340 to `2.x`

[Backport] [2.x] Bump gradle.plugin.com.github.johnrengelman:shadow from 7.1.2 to 8.0.0 (#7340)

---

CHANGELOG.md
distribution/tools/plugin-cli/build.gradle
distribution/tools/plugin-cli/licenses/commons-compress-1.23.0.jar.sha1
distribution/tools/plugin-cli/licenses/commons-compress-LICENSE.txt
distribution/tools/plugin-cli/licenses/commons-compress-NOTICE.txt
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java

[Backport 2.x] Replaces ZipInputStream with ZipFile to fix Zip Slip vulnerability (#7230)

---

server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java

- Fixes flakiness for `getNodeRoles` based tests
- Calling `client()` randomizes the clients across nodes and can lead to a difference sequence of node outputs when checking for node roles
Resolves #7327 
Ran the tests with offending seeds and it seems to pass now. 

Fix flakiness for getNodeRoles based tests

---

CHANGELOG.md
server/build.gradle
server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
server/src/main/java/org/opensearch/extensions/rest/RegisterRestActionsRequest.java
server/src/main/proto/extensions/ExtensionIdentityProto.proto
server/src/main/proto/extensions/ExtensionRequestProto.proto
server/src/main/proto/extensions/RegisterRestActionsProto.proto
server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/7302
Part of https://github.com/opensearch-project/opensearch-sdk-java/issues/348
Also moves the needle for https://github.com/opensearch-project/opensearch-sdk-java/issues/702

[Backport 2.x] Adding versioning support for registering Rest actions

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

This version bump includes mitigations for CVE-2023-26048 and CVE-2023-26049 see https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.51.v20230217.
N/A

Bump jetty-server from 9.4.49.v20220914 to 9.4.51.v20230217 in hdfs-fixture.

---

.github/workflows/dependabot_pr.yml

- This change aims to update the section utilized for changelog entries from dependabot
- The idea behind this is since we are backporting version upgrades to 2.x, it will re-enable backport workflows without causing conflicts, while also keeping `2.x` up to date with the latest versions 
- N/A

Update section for changelog entries

---

test/fixtures/hdfs-fixture/build.gradle

https://github.com/opensearch-project/OpenSearch/pull/7405 bumped jetty-server to 9.4.51*, however there are additional jetty dependencies brought in by hadoop-hdfs that are still using 9.4.48* not replaced with that change.
This change explicitly defines a version of org.eclipse.jetty.websocket:javax-websocket-server-impl which transitively covers the remaining dependencies.
```
./gradlew dependencies
...
|    |    |    +--- org.apache.hadoop:hadoop-yarn-server-nodemanager:3.3.5
|    |    |    |    +--- org.eclipse.jetty.websocket:javax-websocket-server-impl:9.4.48.v20220622
|    |    |    |    |    +--- org.eclipse.jetty:jetty-annotations:9.4.48.v20220622
|    |    |    |    |    |    +--- org.eclipse.jetty:jetty-plus:9.4.48.v20220622
|    |    |    |    |    |    |    \--- …
```

Upgrade all jetty dependencies to 9.4.51.v20230217.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/coordination/RareClusterStateIT.java
server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWhileCreatingIndexIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/MatchedQueriesIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/RandomScoreFunctionIT.java
server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequestBuilder.java
server/src/main/java/org/opensearch/action/get/GetRequest.java
server/src/main/java/org/opensearch/action/get/GetRequestBuilder.java
server/src/main/java/org/opensearch/action/get/MultiGetRequest.java
server/src/main/java/org/opensearch/action/get/MultiGetShardRequest.java
server/src/main/java/org/opensearch/action/search/SearchRequest.java
server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsShardRequest.java
server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequest.java
server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequestBuilder.java
server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
server/src/main/java/org/opensearch/cluster/routing/Preference.java
server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java
test/framework/src/main/java/org/opensearch/test/client/RandomizingClient.java

- Adds back primary shard preference for queries
Resolves #6046 

Add back primary shard preference for queries

---

server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

- We want to test various scenarios involving replica promotion, peer recovery, index close and re-open with remote store.
- These scenarios are already being tested in various [integ tests](https://github.com/opensearch-project/OpenSearch/tree/main/server/src/internalClusterTest/java/org/opensearch/indices/replication) of Segment Replication.
- In this change, we re-use the same tests by enabling remote store settings.
- https://github.com/opensearch-project/OpenSearch/issues/6195
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develop …

Add support to run SegRep integ tests using remote store settings

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

OpenJDK Update (April 2023 Patch releases): 17.0.7+7 / 11.0.19+7
Resolves #[7252]

OpenJDK Update (April 2023 Patch releases)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

Backport of https://github.com/opensearch-project/OpenSearch/pull/7448 to `2.7`

[Backport] [2.7] OpenJDK Update (April 2023 Patch releases) (#7448)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

Backport of https://github.com/opensearch-project/OpenSearch/pull/7449 to `1.3`

[Backport] [1.3] OpenJDK Update (April 2023 Patch releases) (#7449)

---

CHANGELOG.md
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml
server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
test/framework/src/main/java/org/opensearch/search/RandomSearchRequestGenerator.java

This change allows a search pipeline to be defined within a search request body. This will take precedence over any other search pipeline, and allows ad hoc testing of pipeline configurations before persisting the pipeline definition in cluster state.
The new search source field is gated behind the search pipelines feature flag. Also, serialization of the field is gated behind a 3.0 version check. I don't think we should backport to the 2.x branch before we release 2.7. I think we'll want to update that version check to 2.8.
https://github.com/opensearch-project/OpenSearch/issues/6717 …

[Search Pipelines] Support ad hoc pipelines

---

modules/mapper-extras/src/main/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapper.java

This change removes the builder instance variable from SearchAsYouTypeFieldMapper class. This builder object was consuming a lot of memory. Now the builder will be initialized only when needed. This change is similar to the optimization done for text field mapper here : https://github.com/opensearch-project/OpenSearch/pull/7159 
#7001 

Remove builder instance from SearchAsYouTypeFieldMapper

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7462 to `2.x`

[Backport] [2.x] Bump org.apache.commons:commons-compress from 1.22 to 1.23.0 in /test/fixtures/hdfs-fixture (#7462)

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/ExtensionsProperties.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestExtensionsList.java

In order to run integration testing for the SDK and future extensions, the OpenSearch gradle plugin needs to be able to run both extensions and plugins at the same time.  This PR adds the capability to run extensions from the gradle plugin, while leaving all existing plugin functionality untouched.
Backport of https://github.com/opensearch-project/OpenSearch/pull/7235
https://github.com/opensearch-project/opensearch-sdk-java/issues/589

[Backport 2.x] Add extensions to gradle plugin

---

test/fixtures/hdfs-fixture/build.gradle

This change excludes the version of protobuf-java included with hadoop-minicluster. Without this change 1.x versions of OpenSeach will include protobuf-java version 2.5.0 on the test classpath with `./gradlew :plugins:repository-hdfs:dependencies`.  This version is flagged for vulnerabilities.
This change will have no impact on main/2.x versions. other than reading version from version.properties.
N/A

Exclude protobuf-java version included with hadoop-minicluster

---

server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/main/java/org/opensearch/extensions/NoopExtensionsManager.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

ExtensionsManager has a whole lot of functionality that shouldn't be exposed to external classes, marked much of this package protected for a cleaner interface.  Then updated the Noop version to override all public functions to remove extraneous feature flag checks.
Note; I didn't go so far to remove all getters/setters that were unused but that could be a good follow up in the future.
(cherry picked from commit 3687d0106230186afec58dd5e7b0a58c80f6f7d1)
- Related #7374 …

[Backport 2.x] Cleanup interfaces around ExtensionManager (#7374)

---

buildSrc/version.properties
test/fixtures/hdfs-fixture/build.gradle

This PR manually backports various commits to bump dependencies in hdfs-fixture. This excludes guava, netty, and jackson dependencies that are included with hadoop-minicluster.
Commits backported:
https://github.com/opensearch-project/OpenSearch/pull/5666 - partial
https://github.com/opensearch-project/OpenSearch/commit/36138810ffb34213a3d6000aa5cc15eec9b972e3

Manual backport of guava, netty, jetty version bumps in hdfs-fixture to 1.x.

---

server/build.gradle
server/src/main/java/org/opensearch/extensions/action/ExtensionActionRequest.java
server/src/main/java/org/opensearch/extensions/action/ExtensionHandleTransportRequest.java
server/src/main/java/org/opensearch/extensions/action/TransportActionRequestFromExtension.java
server/src/main/proto/extensions/HandleTransportRequestProto.proto
server/src/test/java/org/opensearch/extensions/action/ExtensionActionRequestTests.java
server/src/test/java/org/opensearch/extensions/action/ExtensionHandleTransportRequestTests.java
server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java
server/src/test/java/org/opensearch/extensions/action/TransportActionRequestFromExtensionTests.java

Adding cross version support for transport actions for Extensions.
- Moved `byte []` to `ByteString` which protobuf understands. The only difference is `ByteString` is bounded which is more safe. 
- Didn't update change log as the changes are covered with a meta entry from previous PRs.
Part of #7402 

[Extensions] Moving transport action API to support cross versions

---

buildSrc/version.properties
test/fixtures/hdfs-fixture/build.gradle

Manual backport of 7469 to 1.x line.

[Backport 1.x] Exclude protobuf-java version included with hadoop-minicluster

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7460 to `2.x`

[Backport] [2.x] Bump com.networknt:json-schema-validator from 1.0.78 to 1.0.81 (#7460)

---

buildSrc/version.properties
test/fixtures/hdfs-fixture/build.gradle

[Backport 1.3] Manual backport of guava, netty, jetty version bumps in hdfs-fixture to 1.x. (#7472)

---

buildSrc/version.properties
test/fixtures/hdfs-fixture/build.gradle

Manual backport of #7480 to 1.3

[Backport 1.3] Exclude protobuf-java version included with hadoop-minicluster (#7480)

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java

Companion PR in the security plugin: https://github.com/opensearch-project/security/pull/2749
Adds a public method to lookup extension settings placed in `extensions.yml` by the extension unique id. There was a recent issue with extension handshake and the security plugin where the only available method exposed looks up initialized extensions which is not populated at the time of initial handshake: https://github.com/opensearch-project/security/issues/2747
This new method is utilized in the security plugin to ensure that the unique id exists in `extensions.yml` so that it can permit the transport requests that an extension uses to bootstrap
Resolves https://github.com/opensearch-project/security/issues/2747 …

Adds ExtensionsManager.lookupExtensionSettingsById

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/store/RemoteBufferedIndexOutput.java
server/src/main/java/org/opensearch/index/store/RemoteBufferedOutputDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteIndexOutput.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/lockmanager/FileLockInfo.java
server/src/main/java/org/opensearch/index/store/lockmanager/LockInfo.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreCommitLevelLockManager.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManager.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactory.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerUtils.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java
server/src/main/java/org/opensearch/index/store/lockmanager/package-info.java
server/src/test/java/org/opensearch/index/store/RemoteBufferedIndexOutputTests.java
server/src/test/java/org/opensearch/index/store/RemoteBufferedOutputDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/lockmanager/FileLockInfoTests.java
server/src/test/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactoryTests.java
server/src/test/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManagerTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

… for longer duration.
Changes for Lock Manager in Remote Segment Store to keep data for longer duration and prevent their deletion from Garbage Collection.  
Manually Tested Feature End to end on an opensearch cluster.
https://github.com/opensearch-project/OpenSearch/issues/6691
https://github.com/opensearch-project/OpenSearch/issues/6688

[Remote Store] Add Lock Manager in Remote Segment Store to persist data

---

libs/core/src/main/java/org/opensearch/Version.java

Update Apache Lucene version for OpenSearch 2.8.0 as per https://github.com/opensearch-project/OpenSearch/pull/7510
N/A

Update Apache Lucene version for OpenSearch 2.8.0

---

CHANGELOG.md
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml
server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
test/framework/src/main/java/org/opensearch/search/RandomSearchRequestGenerator.java

Backport https://github.com/opensearch-project/OpenSearch/pull/7253 to 2.x (since auto-backport failed).

[Backport 2.x][Search Pipelines] Support ad hoc pipelines #7253

---

server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java

- Clean up tests for recently added `primary` search preference (#7375)
- N/A

Clean up test cases for primary search preference

---

DEVELOPER_GUIDE.md

The Maven ecosystem requires specific naming convention for snapshots, with a (case-sensitive) `-SNAPSHOT` suffix.
The "Lucene Snapshots" produced by the [lucene-snapshots.yml](.github/workflows/lucene-snapshots.yml) workflow do not conform to this convention, and are thus considered "releases" by build systems.  This produces surprising/confusing behavior.
For example, using a Gradle [repository filter](https://docs.gradle.org/current/userguide/declaring_repositories.html#maven_repository_filtering) these snapshots are excluded from `snapshotsOnly()` and included in `releasesOnly()`.  In a Maven-based build, [artifact repository policies](https://maven.apache.org/ref/3.6.3/maven-artifact/apidocs/org/apache/maven/artifact/repository/ArtifactRepositoryPolicy.html) such as update/refresh …

[Docs] Clarify that Lucene Snapshot artifacts are releases, not snapshots

---

server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java

The threadpool size in the main source code and the expected size in test code were different causing flaky test. This PR fixes the expected size in the test code.
Resolves #7530

Fix flaky ScalingThreadPoolTests.testScalingThreadPoolConfiguration test

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheBlocksIT.java
server/src/main/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheAction.java
server/src/test/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheActionTests.java

- From the findings on https://github.com/opensearch-project/OpenSearch/pull/7498/files#r1191759700, the clear fieldsdata/request/query cache paths do not seem to be affected by metadata write blocks
- Lowering the block level to `METADATA_READ` to enable cache clearing with write blocks as it will help relieve resources within the system. 
- #7498

Change block check type for index clear cache APIs

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheBlocksIT.java
server/src/main/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheAction.java
server/src/test/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheActionTests.java

(cherry picked from commit 58edd186ae60773745513926779a593e4e0239d3)
- Backports #7538 to 2.x
N/A

[Backport 2.x] Change block check type for index clear cache APIs (#7538)

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cluster.put_settings/10_basic.yml
server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureMode.java
server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java
server/src/test/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettingsTests.java

ClusterState updates of SearchBackpressureMode are persisted without validation which causes the entire cluster to become unstable or corrupted when a cluster tries to load invalid mode.
This fixes #6832 that causes cluster state corruption due to a lack of validation of SearchBackpressureMode.
Resolves #6832 
- [x ] Commits are signed per the DCO using --signoff

Reject invalid SearchBackpressureMode (#6832)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

This change adds a hook to publish the notification to replicas when a segments are uploaded to the remote store. 
This change also gates this behind a new feature flag for Segment Replication with remote store.. 
https://github.com/opensearch-project/OpenSearch/issues/5578

SegRep with Remote: Add hook for publishing checkpoint notifications after segment upload to remote store

---

libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java

Provide mechanism to configure XContent parsing constraints (after update to Jackson 2.15.0 and above)
Resolves #[7549](https://github.com/opensearch-project/OpenSearch/issues/7549)

Provide mechanism to configure XContent parsing constraints (after update to Jackson 2.15.0 and above)

---

CHANGELOG.md
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml
qa/mixed-cluster/build.gradle
rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

Once users have defined and tested a search pipeline, they may want to apply it by default to all queries hitting a given index.
Users should be able to bypass the default pipeline for the index by explicitly specifying `search_pipeline=_none` in the URL parameter of their search request.
Resolves #6719 

[Search Pipelines] Add default_search_pipeline index setting

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

Fix flaky test SegmentReplicationIT.testScrollWithOngoingSegmentReplication
This test has flaky failures for two reasons:
1. Fetches list of temporary files on disk starting with ".replication" before the replica has time to 
flush received chunks to disk. Fixed by wrapping the assertion that a tmp file exists with assertBusy.
2. Asserts that the count of tmp files is exactly the same before/after a scroll request is cleared. However,
it is possible that additional tmp files have been written to disk concurrently, causing a count mismatch. Fixed
by removing the size assertion.  For the sake of this test we don't care if this is the case, as long as the tmp files 
originally fetched remain after a scroll query is cleared.
resolves #7569  …

Fix flaky test SegmentReplicationIT.testScrollWithOngoingSegmentReplication

---

CHANGELOG.md
client/rest-high-level/src/main/java/org/opensearch/client/IndicesRequestConverters.java
client/rest-high-level/src/test/java/org/opensearch/client/IndicesRequestConvertersTests.java
rest-api-spec/src/main/resources/rest-api-spec/api/indices.clear_cache.json
server/src/internalClusterTest/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheBlocksIT.java
server/src/main/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheRequest.java
server/src/main/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheAction.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
server/src/main/java/org/opensearch/rest/action/admin/indices/RestClearIndicesCacheAction.java
server/src/test/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheActionTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTestCase.java

- Adds a new parameter `file` support to clear out filecache for indices using the clear indices cache API
- This PR replaces #7323 
Resolves #6030 

Add filecache support in clear indices cache API

---

server/src/main/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheRequest.java

- Update backwards compatibility version for file cache API to `V_2_8_0`
- Post merge for #7595

Update compatibility version for file cache API

---

server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java

Changed the hyphen to an underscore as discussed in issue #6448 
Resolves: probably #3032 in [documentation-website](https://github.com/opensearch-project/documentation-website)

Fixed typo

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/AbstractTasksIT.java
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/ConcurrentSearchTasksIT.java
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/TasksIT.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/RecordingTaskManagerListener.java
server/src/test/java/org/opensearch/tasks/TaskResourceTrackingServiceTests.java

Change the INDEX_SEARCHER threadpool type to [`QueueResizableOpenSearchThreadPoolExecutor`](https://github.com/opensearch-project/OpenSearch/blob/5eac54d4ade73f6d0ed80b0f2408a104a98e3232/server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java#L206) to support task resource tracking for concurrent segment search.
* Added new `ConcurrentSearchTasksIT` test to validate that multiple threads are reporting resource stats for the same task with concurrent search enabled. Note that this is separate from #7440.
* Added new UT `testStartingTrackingHandlesMultipleThreadsPerTask` to `TaskResourceTrackingServiceTests` to check that `TaskResourceTrackingService` properly handles multiple threads per task.
We already have existing tests for passing thread context between …

Change INDEX_SEARCHER threadpool to resizable to support task resource tracking

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7563 to `2.x`

[Backport] [2.x] Bump org.apache.commons:commons-compress from 1.22 to 1.23.0 (#7563)

---

CHANGELOG.md
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml
qa/mixed-cluster/build.gradle
rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

* [Search Pipelines] Add default_search_pipeline index setting
Once users have defined and tested a search pipeline, they may want to apply it by default to all queries hitting a given index.
Users should be able to bypass the default pipeline for the index by explicitly specifying `search_pipeline=_none` in the URL parameter of their search request.
* Rename default search pipeline setting and add getter/setter
Also change version check for ad hoc pipeline to 2.8
* Add tests for new IndexSettings methods
* Update test to reflect change to FeatureFlagSetter
---------
Signed-off-by: Michael Froh …

[Backport 2.x][Search Pipelines] Add default_search_pipeline index setting (#7470)

---

rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml

As @reta pointed out, these tests should be skipped for versions less than 2.7.0, but the skip version ranges are inclusive. So, the upper bound of the range should be 2.6.99.
This brings a change made for
https://github.com/opensearch-project/OpenSearch/pull/7589 onto the main branch.
Related to https://github.com/opensearch-project/OpenSearch/pull/7589

Fix version check for search pipelines REST test

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cluster.put_settings/10_basic.yml
server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureMode.java
server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java
server/src/test/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettingsTests.java

* Reject invalid SearchBackpressureMode (#6832)
ClusterState updates of SearchBackpressureMode are persisted without validation which causes the entire cluster to become unstable or corrupted when a cluster tries to load invalid mode.
Signed-off-by: Austin Lee <austin.t.lee@gmail.com>
(cherry picked from commit ba35781610b52daa852d93fb037bb10d9096177a)

[Backport 2.x] Reject invalid SearchBackpressureMode (#6832) (#7541)

---

CHANGELOG.md

Removes CHANGELOG entries from Unreleased 3.0 that are planned to be released in the next minor 2.x release and already present in the CHANGELOG on the 2.x branch here: https://github.com/opensearch-project/OpenSearch/blob/2.x/CHANGELOG.md?plain=1#L10-L17

Remove changelog entries under unreleased 3.0 that will be released in 2.x

---

libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java

Fix flaky org.opensearch.common.xcontent.XContentParserTests.testString test case
```
com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 3145728 code points.
at [Source: (byte[])"---
yaMBb: "㾘䲙䞆䮪㵺㽮㣭䟋㚾㨻㼃㓷㭛䎭䲤䍉䖻䇸䡁㟯䢂䄺㩰䏠㝯䟫㤩䦗䛎䥽㫼㔲䨞䦀䀇㮩䌒㢇䝩㣝㦹䩇㠛㷡㠐䮈㟪㜵䰈䕉㦕㦣㒷㭻㞾㲁䦔㿪㜗䚇㷧㥃䶢䁅䛸䤕䦘䏣䵚㮶㷔㙶䕼䬜\
䊹䞠䰧䧨䏉㒤㞆䊶㰿䪵䡆䪗䗳䖴㓗㒄䗌䙫㴇䑞䌃䂩㐄䀓䐤䰸䂫㧼㘗䈜䔦㡬㚋㓒䟄䫨㮷䩐㡎䵾䏈㟜㦺䙪㦹㨔㩨䄚䒂䫷䍺䴈㻥䊵䑅㯚㚏䂲㿽㟵䎃䗃㜥㕿䓤䔈㫋㼟䮳䒓㦗䚉䟾䤼䩻㙟㬣䕔䵞㟦\
㑉䐫㪢䟦㸏䄷"[truncated 9568407 bytes]; line: 39218, column: 73]
```
Resolves #[7615]
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#devel …

Fix flaky org.opensearch.common.xcontent.XContentParserTests.testString test case

---

server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java

We are observing flaky tests in `SegmentReplicationRemoteStoreIT` class. Few examples: https://github.com/opensearch-project/OpenSearch/issues/7643, https://github.com/opensearch-project/OpenSearch/issues/7592
Muting this test class until tests are fixed

Mute SegmentReplicationRemoteStoreIT

---

CHANGELOG.md

- Removes a duplicate entry from the CHANGELOG
- N/A

Remove duplicated changelog entry

---

CHANGELOG.md
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/10_basic.yml
server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
server/src/main/java/org/opensearch/search/pipeline/Processor.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineInfo.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/nodesinfo/NodeInfoStreamingTests.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineInfoTests.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

In the initial search pipelines commit, I threw request and response processor factories into one combined map. I think that was a mistake.
We should embrace type-safety by making sure that the kind of processor is clear from end to end. As we add more processor types (e.g. search phase processor), throwing them all in one big map would get messier.
As a bonus, we'll be able to reuse processor names across different types of processor.
Resolves #7576 

[Search Pipelines] Split search pipeline processor factories by type

---

server/src/main/java/org/opensearch/common/lucene/Lucene.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/test/java/org/opensearch/common/lucene/LuceneTests.java

Lucene 9.6.0 includes changes to make the "expert" readLatestCommit API public, so [the current code workaround](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/lucene/Lucene.java#L139-L145) using DirectoryReader is no longer required.
Resolves #7084

Remove workaround to access Lucene's "expert" readLatestCommit API

---

CHANGELOG.md
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/10_basic.yml
server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
server/src/main/java/org/opensearch/search/pipeline/Processor.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineInfo.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/nodesinfo/NodeInfoStreamingTests.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineInfoTests.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/eb51f2b73a68b6f6886e2aefff0dccb32f1a323b from https://github.com/opensearch-project/OpenSearch/pull/7597.
Added a commit to update the version check (and remove the TODO talking about updating the version check).

[Backport 2.x] [Search Pipelines] Split search pipeline processor factories by type

---

server/src/main/java/org/opensearch/common/lucene/Lucene.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/test/java/org/opensearch/common/lucene/LuceneTests.java

Manual backport of 47d4f38eef90687943214e7c8847a3dacd968b1a from #7671 

[Manual backport 2.x] Remove workaround to access Lucene's "expert" readLatestCommit API

---

server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java

This backports #7539
Resolves #7530

[Backport 2.x] Fix flaky ScalingThreadPoolTests.testScalingThreadPoolConfiguration test (#7539)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

This backports #7361 & #7654.
Resolves #6195, https://github.com/opensearch-project/OpenSearch/issues/7643, https://github.com/opensearch-project/OpenSearch/issues/7592

[Backport 2.x] Add support to run SegRep integ tests using remote store settings & Mute flaky test

---

server/src/main/java/org/opensearch/search/pipeline/SearchPipelineInfo.java

Now that we've backported the SearchPipelineInfo serialization change to 2.x ahead of the 2.8 release, we need to update the compatibility check from <=2.8 to <2.8, as mentioned in the previous TODO (see https://github.com/opensearch-project/OpenSearch/pull/7597).
This change should be merged (immediately) after
https://github.com/opensearch-project/OpenSearch/pull/7669.
Follows from https://github.com/opensearch-project/OpenSearch/pull/7597 and https://github.com/opensearch-project/OpenSearch/pull/7669.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/ …

Update SearchPipelineInfo backcompat check

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7660 to `2.x`

[Backport] [2.x] Bump net.minidev:json-smart from 2.4.10 to 2.4.11 in /test/fixtures/hdfs-fixture (#7660)

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

I nominated Dan Widdis (@dbwiddis) to be a co-maintainer for Opensearch through our [nomination process](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer). The maintainers have agreed, and Dan has kindly accepted.
Dan is already a maintainer of [opensearch-sdk-java](https://github.com/opensearch-project/opensearch-sdk-java) and working actively on Extensibility. Dan has authored several PRs on OpenSearch repo. Few of them got merged to `feature/extensions` branch and then later to `main`. 
1. [Add DynamicActionRegistry to ActionModule](https://github.com/opensearch-project/OpenSearch/pull/6734)
2. [Update ExtensionRestResponse to handle RestRequest object](https://github.com/opensearch-project/OpenSearch/pull/6874)
3. [Only store names of …

Added @dbwiddis to OpenSearch maintainers

---

CHANGELOG.md
client/rest-high-level/src/test/java/org/opensearch/client/core/tasks/GetTaskResponseTests.java
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/TasksIT.java
server/src/main/java/org/opensearch/tasks/CancellableTask.java
server/src/main/java/org/opensearch/tasks/Task.java
server/src/main/java/org/opensearch/tasks/TaskInfo.java
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TaskTests.java
server/src/test/java/org/opensearch/tasks/ListTasksResponseTests.java
server/src/test/java/org/opensearch/tasks/TaskInfoTests.java

Backports - https://github.com/opensearch-project/OpenSearch/pull/7445
https://github.com/opensearch-project/OpenSearch/pull/7445

[Backport 2.x] Adding task cancellation timestamp in task API

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

* SegRep with Remote: Add hook for publishing checkpoint notifications after segment upload to remote store
* Added changelog
* Fix the test
* gradle check
* Addressed PR comments
* Addressing PR comments 2
* Addressed comments 3
* Fix Changelog entry
---------
This backports #7394
Resolves #5578

[Backport 2.x] SegRep with Remote: Add hook for publishing checkpoint notifications after segment upload to remote store (#7394)

---

server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureService.java
server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettings.java
server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/indices/IndicesModule.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettingsTests.java
server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentTrackerTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java

This backports #7459
Resolves #7424

[Remote segments] Add backpressure in write path on segments lag between local and remote store (#7459)

---

server/src/main/java/org/opensearch/tasks/TaskInfo.java

Fixing version guard for https://github.com/opensearch-project/OpenSearch/pull/7445
Backport 2.x PR - https://github.com/opensearch-project/OpenSearch/pull/7711
https://github.com/opensearch-project/OpenSearch/issues/6953

Task cancellation API version guard fix

---

server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentTrackerTests.java

Since the actual timestamps populated are not the actual system epoch, changing the stats api to return the lag. In future we'll work on adding the actual timestamps as well

Add remote refresh lag in millis from local refresh

---

modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml

Remvoe flaky match conditions in script processor yaml test
https://github.com/opensearch-project/OpenSearch/issues/7716

Remove flaky match conditions in script processor yaml test

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java

Moving forward, we want to perform version checks to ascertain if incoming checkpoints can be processed rather than relying on string matching of codec names. By knowing which version we are on, we will also know which lucene codecs it supports. 
Resolves #7742

[Segment Replication] Remove codec name string match check for checkpoints

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7655 to `2.x`

[Backport] [2.x] Bump org.apache.maven:maven-model from 3.9.1 to 3.9.2 (#7655)

---

CHANGELOG.md
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml
server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

Thanks to @noCharger for reporting a failing negative test case.
Since we were rethrowing exceptions when resolving search pipelines and processing search requests, that could end up killing the listener thread.
Also, we want to make sure that any exception thrown from search pipelines are wrapped in SearchPipelineProcessingException.
N/A
- ~~[ ] New functionality includes testing.~~
- ~~[ ] All tests pass~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] New functionality has javadoc added~~
- ~~[ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~~
For more information on following Developer Certificate …

[Bugfix] Better exception handling in search pipelines

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/Setting.java
server/src/main/java/org/opensearch/extensions/ExtensionScopedSettings.java
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/main/java/org/opensearch/extensions/ExtensionsSettings.java
server/src/main/java/org/opensearch/extensions/NoopExtensionsManager.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/plugins/ExtensionAwarePlugin.java
server/src/main/java/org/opensearch/plugins/IdentityPlugin.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java

Backport of #7526 to 2.x
This backport also includes changes from https://github.com/opensearch-project/OpenSearch/pull/6922

[Backport 2.x] [Extensions] Add ExtensionAwarePlugin extension point to add custom settings for extensions (#7526)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/AbstractTasksIT.java
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/ConcurrentSearchTasksIT.java
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/TasksIT.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/RecordingTaskManagerListener.java
server/src/test/java/org/opensearch/tasks/TaskResourceTrackingServiceTests.java

Backports #7502 
Concurrent segment search has been backported to 2.x so we also need to backport  #7502 so that we are not missing out on resource tracking whenever concurrent search is GA.
Since `Resizable` threadpool type does not exist in 2.x, we will use the same auto queue threadpool type that search threadpool uses in 2.x.
Ref #7613
Resolves #7743

[Backport 2.x] Change INDEX_SEARCHER threadpool to auto queue to support task resource tracking

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

This change mutes the recently introduces backward compatible tests for segment replication indices. The test currently fails for two different reasons:
1. Targeted shard search request failures. This is posibly due to stale {index}/_stats results, where shard allocation is not correct. 
```
org.opensearch.client.ResponseException: method [POST], host [http://127.0.0.1:35875], URI [/test-index-segrep/_search?rest_total_hits_as_int=true&filter_path=hits.total&preference=_shards%3A1%7C_only_nodes%3A8kJEQo6ASOaPpQE9rnJFRQ], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no data nodes with criteria [8kJEQo6ASOaPpQE9rnJFRQ] found for shard: [test-index-segrep][1]"}],"type":"illegal_argument_exception","reason":"no data nodes with …
```

[Segment Replication] Mute testIndexingWithSegRep flaky test failure

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

1. Use replica shards's ReplicationCheckpoint for replication events. This is a bug because RC is sent to primary which uses it to compare replica shard specific attributes.
2. Use codec defined in engine config instead of default codec. This will break for cases where primary shard is not on default Lucene codec (e.g. Lucene95, Lucene94 etc).
3. Driven from [review comment](https://github.com/opensearch-project/OpenSearch/pull/7732#discussion_r1204845061): Removed `ReplicationCheckpoint` param from SegmentReplicationTarget ctor and SegmentReplicationTargetService.startReplication method.
Resolves: https://github.com/opensearch-project/OpenSearch/issues/7733
Related: #3881  …

[Segment Replication] Use engine codec and replica shard ReplicationCheckpoint for replication events

---

CHANGELOG.md
buildSrc/reaper/build.gradle
buildSrc/version.properties
doc-tools/missing-doclet/build.gradle
doc-tools/missing-doclet/src/main/java/org/opensearch/missingdoclet/MissingDoclet.java
server/build.gradle
server/licenses/jboss-annotations-api_1.2_spec-1.0.2.Final.jar.sha1
server/licenses/jboss-annotations-api_1.2_spec-LICENSE.txt
server/licenses/jboss-annotations-api_1.2_spec-NOTICE.txt

It can be tedious and error prone to have to specify individual source files of generated code that does not follow OpenSearch standards.
Allow wildcard expressions in missingJavadoc.
Resolves #7264 
- [x ] Commits are signed per the DCO using --signoff
- [ x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

Add support for ignoring missing Javadoc on generated code using annotation (# 7264)

---

CHANGELOG.md
buildSrc/version.properties
doc-tools/missing-doclet/build.gradle
doc-tools/missing-doclet/src/main/java/org/opensearch/missingdoclet/MissingDoclet.java
server/build.gradle
server/licenses/jboss-annotations-api_1.2_spec-1.0.2.Final.jar.sha1
server/licenses/jboss-annotations-api_1.2_spec-LICENSE.txt
server/licenses/jboss-annotations-api_1.2_spec-NOTICE.txt

Backport of https://github.com/opensearch-project/OpenSearch/pull/7604 to `2.x`

[Backport] [2.x] Add support for ignoring missing Javadoc on generated code using annotation (# 7264) (#7604)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

This PR will move CLUSTER_REPLICATION_TYPE_SETTING out of experimental feature flag and make it generally available for the users.
Resolves #6656 , Related to #7420 

[Segment Replication] Move CLUSTER_REPLICATION_TYPE_SETTING out of experimental feature flag

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java

The `backpressure_rejection_count` field in the `_remotestore/stats/{index}` api response was coming to be zero always. The issue is narrowed to the missing code of incrementing the global rejection counter when the remote segment backpressure framework rejects a write request. In the PR, we have fixed the issue.
Resolves #7774

[Remote Store] Fix stats api rejection count response

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Remote store stats api returns no response if coordinator node does not contain remote enabled shard
If lets say we have 3 nodes - N1, N2 and N3 and there is remote store enabled index index1 with 1 shard (on N1) and 0 replica, then if we call remotestore stats api on N1, it returns the stats. If we call the api on N2 or N3, it returns empty result.
In this PR, we check the index setting by reading the cluster state since the indicesService does not hold the shards that don't reside on underlying coordinator node. 
Resolves #7738 …

[Remote Store] Fix shards condition in stats api

---

libs/core/src/main/java/org/opensearch/Build.java
server/src/test/java/org/opensearch/BuildTests.java

Expect Build class to be in `opensearch-core-{version}.jar` not `opensearch-{version}.jar`.
Fixes breakage introduced in #7328, causing `GET /` to return "unknown" for build hash and date.

[Bug] Fix Build Metadata 

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java

This PR fixes failing flaky test `testSnapshotRestoreOnIndexWithSegRepClusterSetting` found in [build run](https://build.ci.opensearch.org/job/gradle-check/16399/)

[Segment Replication] Fix failing flaky test in SegmentReplicationSnapshotIT

---

.github/workflows/publish-maven-snapshots.yml

Updates the branches that `publish-maven-snapshots` github workflow is run with. It now uses a regex to match any released of unreleased branches. I noticed that the .NET client was using the same patterns: https://github.com/opensearch-project/opensearch-net/blob/main/.github/workflows/test-jobs.yml#L16-L17
Resolves https://github.com/opensearch-project/OpenSearch/issues/7705

Run publish maven snapshots on all branches matching pattern

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

This backports #7739 & #7775
Resolves #7738 & #7774

[Backport 2.x] [Remote Store] Fix stats api bugs (#7739) & (#7774)

---

CHANGELOG.md
distribution/tools/keystore-cli/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7811 to `2.x`

[Backport] [2.x] Bump com.google.guava:guava from 31.1-jre to 32.0.0-jre in /distribution/tools/keystore-cli (#7811)

---

CHANGELOG.md
sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java
sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressionMode.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/7681 to `2.x`

[Backport] [2.x] Reduce memory copy in zstd compression (#7681)

---

server/src/main/java/org/opensearch/common/settings/Setting.java

Re-order the Setting enum to add Extension scope setting at the bottom. There was a break in extensions backward compatibility as extensions relies on the order of the enum when sending settings from node <-> extension.
I will open up a separate PR against main to backport to 2.x.
See more details: https://github.com/opensearch-project/opensearch-sdk-java/issues/792

[2.8] Reorder Setting enum to add Extension scope at bottom

---

server/src/main/java/org/opensearch/common/settings/Setting.java

Re-order the Setting enum to add Extension scope setting at the bottom. There was a break in extensions backward compatibility as extensions relies on the order of the enum when sending settings from node <-> extension.
See more details: https://github.com/opensearch-project/opensearch-sdk-java/issues/792

Reorder Setting enum to add Extension scope at bottom

---

server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java

Fixes flaky test org.opensearch.remotestore.RemoteStoreRefreshListenerIT.testRemoteRefreshRetryOnFailure. For the fix, we have increased the timeout to 90s. 
Resolves #7703

[Remote Store] Fix flaky test - closes #7703

---

CHANGELOG.md
distribution/tools/upgrade-cli/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7807 to `2.x`

[Backport] [2.x] Bump com.google.guava:guava from 31.1-jre to 32.0.0-jre in /distribution/tools/upgrade-cli (#7807)

---

CHANGELOG.md
distribution/tools/plugin-cli/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7808 to `2.x`

[Backport] [2.x] Bump com.google.guava:guava from 31.1-jre to 32.0.0-jre in /distribution/tools/plugin-cli (#7808)

---

CHANGELOG.md
build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/7810 to `2.x`

[Backport] [2.x] Bump org.gradle.test-retry from 1.5.2 to 1.5.3 (#7810)

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandler.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java

- Currently, we upload 2 files in addition to segment files per refresh (we upload these files even if there are no segments to upload - that will be fixed by https://github.com/opensearch-project/OpenSearch/issues/7443)
- These 2 files are metadata file and `SegmentInfosSnapshot` file. In order to avoid explosion of number of files in the remote store, we use the same name of metadata and snapshot file per commit.
- But the assumed invariant is: there is 1:1 mapping between metadata and SegmentInfosSnapshot file. 
- This does not work if while reading we read metadata file and by the time we read snapshot file, remote store has new snapshot file with the same name.
- To avoid this race condition, this change combines these 2 files. metadata file will have one more field: …

[Remote Segment Store] Combine metadata and snapshot files

---

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java

Currently in afterRefresh method of RemoteStoreRefreshListener, we upload metadata file even if the local and remote store has not difference in segment files. We need to skip the upload if there are no differences in segment files on local and remote store. With this PR, we are not creating / uploading the metadata file if there are no differences in the segments files in local primary store and remote store.  
Resolves #7443

[Remote Store] Optimize segments metadata upload

---

CHANGELOG.md
plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java

Fixing error: adding a new/forgotten parameter to the configuration for checking the config on startup.
The error fixes the situation that arises when configuring a proxy for accessing the S3 service. When setting up the proxy, the proxy.type is required, but this parameter causes an error upon node startup. This change rectifies the current situation and ensures behavior as described in the documentation.
This modification has already been tested on our systems.
#2160  
s3.client.default.proxy.type
repository-s3
- [?] Commits are signed per the DCO using --signoff
- [ x ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog)) …

Fixing error: adding a new/forgotten parameter to the configuration for checking the config on startup in plugins/repository-s3

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

This change fixes the flakyness of recently introduced segment replication bwc test. For doc count assertion, this test first makes API call to `index/_stats` to build map of shardId to nodeID (`[index][1] -> abcdXXX`) (separate maps for primary and replica). Once map is built, a targeted search request is made which asserts same doc count for both primary and replica shards. The existing flakyness exists due to shard relocations which completes by the time search query hits the speicfic shard (now moved away to a different node). The fix here is to wait for relocations to complete before verifying doc count.
Resolves https://github.com/opensearch-project/OpenSearch/issues/7679 …

[Segment Replication] Wait for shard relocation before building node to shard allocation map

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java

This PR updates remote translog store path to be consistent with segment.
- `s3://remote-store-perf-test/cluster-1/zqQpla0QS_mFK3Q42FbQ0A/<shardid>/segments/data/`
- `s3://remote-store-perf-test/cluster-1/zqQpla0QS_mFK3Q42FbQ0A/<shardid>/segments/metadata/`
- `s3://remote-store-perf-test/cluster-1/zqQpla0QS_mFK3Q42FbQ0A/<shardid>/<primaryterm>/(*.tlog|*.ckp)`
- `s3://remote-store-perf-test/cluster-1/zqQpla0QS_mFK3Q42FbQ0A/<shardid>/metadata`
- `s3://remote-store-perf-test/cluster-1/zqQpla0QS_mFK3Q42FbQ0A/<shardid>/translog/data/<primaryterm>/(*.tlog|*.ckp)`
- `s3://remote-store-perf-test/cluster-1/zqQpla0QS_mFK3Q42FbQ0A/<shardid>/translog/metadata`
Addresses #1 in https://github.com/opensearch-project/OpenSearch/issues/3589#issuecomment-1534329922 …

Make remote translog store path consistent to remote segment store

---

CHANGELOG.md
buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/precommit/ValidateJsonAgainstSchemaTask.java

Manual backport of #7933: bump com.networknt:json-schema-validator dependency from 1.0.81 to 1.0.83

Manual backport of #7933: bump com.networknt:json-schema-validator dependency from 1.0.81 to 1.0.83

---

plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/AwsEc2ServiceImpl.java
plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/Ec2ClientSettings.java
plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2DiscoveryPluginTests.java

Defaults discovery-ec2 plugin default region to none. According to https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html this _should_ automatically determine the Region from the environment. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/7959.

Default discovery-ec2 region to none.

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/profile/query/CollectorResult.java
server/src/main/java/org/opensearch/search/profile/query/InternalProfileCollector.java
server/src/main/java/org/opensearch/search/profile/query/InternalProfileCollectorManager.java
server/src/main/java/org/opensearch/search/profile/query/ProfileCollector.java
server/src/test/java/org/opensearch/search/profile/query/CollectorResultTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfileShardResultTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

(cherry picked from commit c58dc1ade9096ab70e22024e91eecd79fe2416e8)
Backport of https://github.com/opensearch-project/OpenSearch/pull/7898 to `2.x` branch.
To show high-level concurrent execution details, we bring `min_slice_time_in_nanos`, `max_slice_time_in_nanos`, and `slice_count` etc. fields into the query response. With these new fields, users can quickly determine query performance and skew issues.
`name`: A more friendly representation of the collector's class name.
`reason`: A "hint" to help provide some context about this collector.
`time_in_nanos`: The total elapsed time for this collector. In the concurrent search case, this is the total time across all slices (i.e. `max(slice_end_time) - min(slice_start_time)`)
`children`: A list of children collectors "embedded" inside this …

[Backport] [2.x] [Concurrent Segment Search]: Add new query profile collector fields with concurrent search execution (#7898)

---

server/src/main/java/org/opensearch/search/profile/query/CollectorResult.java

https://github.com/opensearch-project/OpenSearch/pull/7975
Resolves https://github.com/opensearch-project/OpenSearch/issues/7355
https://github.com/opensearch-project/OpenSearch/pull/7975/files/fa83dc5a5e65953ce8a87e4adbee0f4ca2f2e230#r1223642855

Update version guards to deal for new query profile collector fields

---

server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/main/java/org/opensearch/search/query/QueryPhaseSearcher.java
server/src/test/java/org/opensearch/search/SearchModuleTests.java

As part of https://github.com/opensearch-project/OpenSearch/pull/7956, we would new to move off from static to contextual aggregation processor instantiation, refactoring QueryPhaseSearcher to allow such possibility.

Refactor QueryPhaseSearcher to support contextual aggregation processors at query phase

---

buildSrc/src/test/java/org/opensearch/gradle/plugin/OptionalDependenciesPluginTests.java
buildSrc/src/test/resources/plugin/optional-dependencies.gradle

Add test case for OptionalDependenciesPlugin (com.netflix.nebula:gradle-extra-configurations-plugin plugin migration)
N/A

Add test case for OptionalDependenciesPlugin (com.netflix.nebula:gradle-extra-configurations-plugin plugin migration)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/MergePolicyConfig.java

Adjust the range and default value for deletes_pct_allowed in merge policy for more control and optimal disk usage (#7360)
This change is to align the default value of deletesPctAllowed in merge policy with Lucene. This change will help in optimal usage of disk and reduce the deleted docs in an index. Search performance would also be better if there are less deleted docs in an index.
Resolves #7360

Align range and default value for deletes_pct_allowed in merge policy

---

.github/CODEOWNERS
MAINTAINERS.md

I have nominated and maintainers have agreed to invite Sachin Kale (@sachinpkale) to be a co-maintainer. Sachin has kindly accepted.
Sachin has led the design and implementation of the remote backed storage feature in OpenSearch. This feature was introduced as experimental in OpenSearch 2.3 and is planned for general availability in 2.9. Some significant issues and PRs authored by Sachin for this effort are as follows:
Feature proposal: https://github.com/opensearch-project/OpenSearch/issues/1968
Upload segments to remote store post refresh: https://github.com/opensearch-project/OpenSearch/pull/3460
Add rest endpoint for remote store restore: https://github.com/opensearch-project/OpenSearch/pull/3576
Add RemoteSegmentStoreDirectory to interact with remote segment store: …

Add @sachinpkale as an OpenSearch maintainer

---

CHANGELOG.md
distribution/src/config/opensearch.yml
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
server/src/main/java/org/opensearch/search/query/QueryPhaseSearcherWrapper.java
server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
server/src/test/java/org/opensearch/search/SearchModuleTests.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java
server/src/test/java/org/opensearch/search/aggregations/AggregationSetupTests.java
server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

Add dynamic index and cluster setting for concurrent segment search (#7956)
* Add dynamic index and cluster setting for concurrent segment search
* Use feature flagged settings map
Resolves #7356 

[Backport 2.x] Add dynamic index and cluster setting for concurrent segment search

---

server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadataHandler.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferMetadataHandlerTests.java

Refactor Translog metadata upload/download to write/read header and footer via `VersionedCodecStreamWrapper` introduced in #5917
Resolves #7228

Refactor Translog metadata upload/download to write/read header and footer via VersionedCodecStreamWrapper

---

qa/smoke-test-http/src/test/java/org/opensearch/http/SearchRestCancellationIT.java

This PR seeks to correct a flaky test `SearchRestCancellationIT.testAutomaticCancellationMultiSearchDuringFetchPhase`.
In the test, a multisearch REST request is created and then cancelled. The test sometimes fails on a runner because the latch had not been set to await for its countdown. By adding the `latch.await(2, Seconds)` statement the latch should force the following block 
```
CountDownLatch latch = new CountDownLatch(1);
AtomicReference<Exception> error = new AtomicReference<>();
Cancellable cancellable = getRestClient().performRequestAsync(searchRequest, new ResponseListener() {
@Override
public void onSuccess(Response response) {
latch.countDown();
}
@Override
public void onFailure(Exception exception) {
error.set(exception);
latch.countDown();
}
});
latch.await(2, SECONDS); …
```

Fix flaky test `SearchRestCancellationIT.testAutomaticCancellationMultiSearchDuringFetchPhase`

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/coordination/CompressedStreamUtils.java
server/src/main/java/org/opensearch/common/compress/CompressedXContent.java
server/src/main/java/org/opensearch/common/compress/CompressorFactory.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/main/java/org/opensearch/transport/CompressibleBytesOutputStream.java
server/src/main/java/org/opensearch/transport/TransportDecompressor.java
server/src/main/java/org/opensearch/transport/TransportLogger.java
server/src/test/java/org/opensearch/index/mapper/BinaryFieldMapperTests.java
server/src/test/java/org/opensearch/transport/CompressibleBytesOutputStreamTests.java
server/src/test/java/org/opensearch/transport/TransportDecompressorTests.java

The aim of this PR is to remove a deprecated `COMPRESSOR` variable from
`CompressorFactory` and use `DEFLATE_COMPRESSOR` instead.

Remove COMPRESSOR variable from CompressorFactory

---

.github/CODEOWNERS
MAINTAINERS.md

Note, I made this backport by doing `git checkout upstream/main MAINTAINERS.md .github/CODEOWNERS` to bring these files inline with what is on main. The MAINTAINERS.md file had formatting changes on main.
---
I have nominated and maintainers have agreed to invite Sachin Kale (@sachinpkale) to be a co-maintainer. Sachin has kindly accepted.
Sachin has led the design and implementation of the remote backed storage feature in OpenSearch. This feature was introduced as experimental in OpenSearch 2.3 and is planned for general availability in 2.9. Some significant issues and PRs authored by Sachin for this effort are as follows:
Feature proposal: https://github.com/opensearch-project/OpenSearch/issues/1968
Upload segments to remote store post refresh: …

[Backport 2.x] Add @sachinpkale as an OpenSearch maintainer (#8019)

---

server/src/internalClusterTest/java/org/opensearch/index/shard/GlobalCheckpointListenersIT.java
server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManager.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/Translog.java
server/src/main/java/org/opensearch/index/translog/TranslogManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/test/java/org/opensearch/index/engine/NoOpEngineRecoveryTests.java
server/src/test/java/org/opensearch/index/replication/RecoveryDuringReplicationTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryStatusTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Upon Index deletion, we delete Remote Translog and delete files in Remote Segments which are not referenced by any snapshots. 
Index level folders are still not deleted . We are only cleaning shard level folders in this change . Will be creating an issue for same. 
Make Remote Segment Deletion Async - Current implementation will increase index deletion time . But we already plan to make it async .  
Resolves https://github.com/opensearch-project/OpenSearch/issues/3511  …

[Remote Store] Deletion of Remote Segments and Translog upon Index Deletion

---

server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

During segment upload, we created local files for snapshot info and segment metadata, then upload these to remote store. If anything failed after snapshot info upload or metadata upload. The local files were not cleaned up in all the cases. 
This lead to retries to fail with `FileAlreadyExistsException`
This change ensures we cleanup local files in all failure scenarios to avoid `FileAlreadyExistsException` during retries
Resolves https://github.com/opensearch-project/OpenSearch/issues/7388
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.m …

[Remote Store] Ensure metadata file is deleted from local fs store during metadata upload failures

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/main/java/org/opensearch/search/rescore/RescoreProcessor.java
server/src/main/java/org/opensearch/search/suggest/SuggestProcessor.java

Renamed `SuggestPhase` and `RescorePhase` to `SuggestProcessor` and `RescoreProcessor` to be consistent with `AggregationProcessor`
#7854 

Rename QueryPhase actors like Suggest, Rescore to be processors rather than phase

---

CHANGELOG.md
distribution/tools/upgrade-cli/build.gradle

This is a manual backport of #8011 - Bump com.google.guava:guava in /distribution/tools/upgrade-cli
Bumps [com.google.guava:guava](https://github.com/google/guava) from 32.0.0-jre to 32.0.1-jre.
- [Release notes](https://github.com/google/guava/releases)
- [Commits](https://github.com/google/guava/commits)
---
updated-dependencies:
- dependency-name: com.google.guava:guava dependency-type: direct:production update-type: version-update:semver-patch ...
Signed-off-by: dependabot[bot] <support@github.com>
* Update CHANGELOG
---------
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Kartik Ganesh …

[Backport 2.x] [Manual backport] Bump com.google.guava:guava from 32.0.0-jre to 32.0.1-jre in /distribution/tools/upgrade-cli (#8011)

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/main/java/org/opensearch/search/rescore/RescoreProcessor.java
server/src/main/java/org/opensearch/search/suggest/SuggestProcessor.java

Backport of #8025 to 2.x
Resolves #8025 
- [] New functionality has been documented.
- [] New functionality has javadoc added

[Backport] [2.x] Rename QueryPhase actors like Suggest, Rescore to be processors rather than phase

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/main/java/org/opensearch/tasks/SearchShardTaskCancellationStats.java
server/src/main/java/org/opensearch/tasks/TaskCancellationMonitoringService.java
server/src/main/java/org/opensearch/tasks/TaskCancellationMonitoringSettings.java
server/src/main/java/org/opensearch/tasks/TaskCancellationStats.java
server/src/main/java/org/opensearch/tasks/TaskManager.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/CancellableTasksTests.java
server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
server/src/test/java/org/opensearch/tasks/SearchShardTaskCancellationStatsTests.java
server/src/test/java/org/opensearch/tasks/TaskCancellationMonitoringServiceTests.java
server/src/test/java/org/opensearch/tasks/TaskCancellationMonitoringSettingsTests.java
server/src/test/java/org/opensearch/tasks/TaskCancellationStatsTests.java
test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

Backport https://github.com/opensearch-project/OpenSearch/pull/7642

[Backport 2.x] Task cancellation monitoring service

---

server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java

Changing version check to 2.9.
Related backport PR - https://github.com/opensearch-project/OpenSearch/pull/8046

[TaskCancellationMonitoringService] Changing version check to 2.9

---

server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
server/src/main/java/org/opensearch/cluster/routing/WeightedRouting.java

When a node is restarted after deleting the shard routing weights, the node fails to come up due to NPE encountered while reading WRR metadata. This PR fixes the bug

Fix bug with delete shard routing weights on node restart

---

CHANGELOG.md
server/src/main/java/org/opensearch/transport/RemoteClusterService.java
server/src/main/java/org/opensearch/transport/TransportService.java
server/src/test/java/org/opensearch/transport/RemoteClusterClientTests.java
server/src/test/java/org/opensearch/transport/RemoteClusterServiceTests.java

* Establish seed node connection setup in async
Backporting https://github.com/opensearch-project/OpenSearch/pull/8038/

[Backport 2.x] Establish seed node connections in async during node bootstrap (#8038)

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
server/src/main/java/org/opensearch/common/compress/CompressedXContent.java
server/src/main/java/org/opensearch/common/compress/CompressorFactory.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/main/java/org/opensearch/transport/CompressibleBytesOutputStream.java
server/src/main/java/org/opensearch/transport/TransportDecompressor.java
server/src/main/java/org/opensearch/transport/TransportLogger.java
server/src/test/java/org/opensearch/index/mapper/BinaryFieldMapperTests.java
server/src/test/java/org/opensearch/transport/CompressibleBytesOutputStreamTests.java
server/src/test/java/org/opensearch/transport/TransportDecompressorTests.java

Manual Backport  1b833b17d2576f8a6072ce68a6c750e6028fdcde from https://github.com/opensearch-project/OpenSearch/pull/7907

[Backport 2.x] [Manual backport] Remove COMPRESSOR variable from CompressorFactory (#7907)

---

server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
server/src/test/java/org/opensearch/snapshots/SnapshotsInProgressSerializationTests.java

Version Checks were kept against 3.0 for shallow copy snapshot changes, to avoid bwc test failures. Now as the changes are backported to 2.x, changing version checks from 3.0 to 2.9.

[Snapshot Interop] Change Version Checks from 3.0 to 2.9

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/SecureSetting.java
server/src/test/java/org/opensearch/common/settings/InsecureSettingTests.java

To address discussion points in the following issues and PRs in common-utils and security plugin:
* https://github.com/opensearch-project/common-utils/issues/334
* https://github.com/opensearch-project/security/pull/2296
This change adds override options to SecureSetting.insecureString such that migrating from legacy insecure settings to secure variants can be achieved without breaking existing cluster deployments and having to set `opensearch.allow_insecure_settings`. Instead usage of deprecated insecure settings are logged (warn level) with a note as to the new secure variant of the setting too.
If approved, changes can be made to common-utils and security plugin to utilize this new code

Added insecureString options to allow to easier migration to secure setting variants

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/50_char_filters.yml
server/src/main/java/org/opensearch/index/analysis/Analysis.java

Fix the mapping `char_filter` to allow mapping hashtags, example:
```python
from elasticsearch_dsl import analyzer, char_filter
STD_WITH_SPECIAL_CHARS: Final = analyzer(
'std_with_hashtag_chars',
type='custom',
tokenizer='standard',
filter=['lowercase'],
char_filter=char_filter(
'hashtag_char_filter',
type='mapping',
mappings=[
'# => _hashsign_',
],
),
)
```
More details in the issue below.
Resolves: https://github.com/opensearch-project/OpenSearch/issues/7308
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …

Fix mapping char_filter when mapping a hashtag

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/SecureSetting.java
server/src/test/java/org/opensearch/common/settings/InsecureSettingTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/5496 to `2.x`
Signed-off-by: Chris White <chriswhite199@gmail.com>
(cherry picked from commit 0b775e79f637c7225ae908e368f1a62ce9ece011)

[Backport 2.x] [Manual] Added insecureString options to allow to easier migration (#5496)

---

plugins/repository-s3/build.gradle
plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java
plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/20_repository_permanent_credentials.yml
plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/30_repository_temporary_credentials.yml
plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/40_repository_ec2_credentials.yml
plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/50_repository_ecs_credentials.yml
plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/60_repository_eks_credentials.yml

According to https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html, in case the region configuration is not provided to a client, it should be resolved from the environment, which is currently not happening since we are always sending a default region from the plugin end.
- Resolves #7866 
- Closes https://github.com/opensearch-project/OpenSearch/pull/7974.

Remove default s3 region

---

plugins/discovery-ec2/README.md
plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/Ec2NameResolver.java
plugins/repository-s3/README.md

This is a start for documenting testing for discovery-ec2 and repository-s3.
- https://github.com/opensearch-project/OpenSearch/pull/7372#issuecomment-1570531667
- https://github.com/opensearch-project/OpenSearch/issues/7867
- https://github.com/opensearch-project/OpenSearch/issues/7866
- https://github.com/opensearch-project/OpenSearch/pull/7974

Document testing of discovery-ec2 and repository-s3.

---

CHANGELOG.md
buildSrc/build.gradle

This patches CVE-2020-15250
N/A

Bump spock-core from 1.3-groovy-2.5 to 2.1-groovy-2.5

---

CHANGELOG.md
buildSrc/build.gradle

Manual backport of #5315 to bump the minor version of `spock-core`
N/A

Bump spock-core from 2.1-groovy-3.0 to 2.3-groovy-3.0

---

CHANGELOG.md
buildSrc/build.gradle

Manual backport of #8119
* Bump spock-core from 1.3-groovy-2.5 to 2.3-groovy-2.5
This patches CVE-2020-15250
* Added CHANGELOG
---------
(cherry picked from commit 70aa15b7756bf61d2330725b962d9b3f75103a88)
N/A

[Backport 1.3] [Manual] Bump spock-core from 1.3-groovy-2.5 to 2.3-groovy-2.5 (#8119)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/profile/aggregation/AggregationProfilerIT.java
server/src/main/java/org/opensearch/search/query/QueryPhase.java

Avoid adding redundant multi collector wrapper when only global agg is present in the search request
Resolves #8097

With only GlobalAggregation in request causes unnecessary wrapping with MultiCollector

---

CHANGELOG.md
buildSrc/build.gradle

Manual backport of #8141 to the `2.x` branch
* Bump com.networknt:json-schema-validator in /buildSrc
Bumps [com.networknt:json-schema-validator](https://github.com/networknt/json-schema-validator) from 1.0.83 to 1.0.84.
- [Release notes](https://github.com/networknt/json-schema-validator/releases)
- [Changelog](https://github.com/networknt/json-schema-validator/blob/master/CHANGELOG.md)
- [Commits](https://github.com/networknt/json-schema-validator/compare/1.0.83...1.0.84)
---
updated-dependencies:
- dependency-name: com.networknt:json-schema-validator dependency-type: direct:production update-type: version-update:semver-patch ...
Signed-off-by: dependabot[bot] <support@github.com>
* Update changelog
Signed-off-by: dependabot[bot] <support@github.com>
---------
Signed-off-by: …

[Backport 2.x] [Manual] Bump com.networknt:json-schema-validator from 1.0.83 to 1.0.84 in /buildSrc (#8141)

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/50_char_filters.yml
server/src/main/java/org/opensearch/index/analysis/Analysis.java

Signed-off-by: Nathan Myles <myles.n.a@gmail.com>
Issue: https://github.com/opensearch-project/OpenSearch/issues/7308 (cherry picked from commit e049338c714db77517c5e8bb94b6b24a7b0a3281)

Fix mapping char_filter when mapping a hashtag (#7591)

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/8139 to `2.x`

[Backport] [2.x] Bump com.netflix.nebula:gradle-info-plugin from 12.1.3 to 12.1.4 (#8139)

---

CHANGELOG.md

Multiple changes were incorrectly placed in the "Unreleased 3.0" section on main and then backported. This brings the changelog on main in line with 2.x for changes that have been backported.

Fix changelog divergence with 2.x

---

CHANGELOG.md
buildSrc/build.gradle

This mitigates downstream dependencies to patch the CVE-2020-13956 vulnerability.
N/A

Bump versions of gradle-info-plugin and nebula-publishing-plugin

---

CHANGELOG.md
buildSrc/build.gradle

Manual backport of #8150 
* Bump versions of gradle-info-plugin and nebula-publishing-plugin
This mitigates downstream dependencies to patch the CVE-2020-13956 vulnerability.
* Added changelog entry
N/A

[Backport 1.3] [Manual] Bump versions of gradle-info-plugin and nebula-publishing-plugin (#8150)

---

CHANGELOG.md

As a followup to #8152, this fixes some minor differences with the `2.x` changelog
N/A

Minor fixes to CHANGELOG

---

CHANGELOG.md

Backport of #8179 
This fixes some minor differences with the 2.x changelog
(cherry picked from commit e6fd76ccd5f02b20ef308aab8aa2472cc1340de4)
N/A

[Backport 2.x] [Manual] Minor fixes to CHANGELOG (#8179)

---

server/src/main/java/org/opensearch/rest/extensions/RestSendToExtensionAction.java

`RestRequest` objects track the parameters and content, indented to provide users with more helpful error messages for incorrect API syntax.
When a Rest Request forwarded to an Extension fails, the `onResponse()` handler method never executes, and these "helpful" error messages end up giving the wrong reason for failure, hiding the actual exceptions.
This PR consumes all params and content to prevent this confusion, allowing the actual exception (often a timeout) to be sent to the user.
Resolves https://github.com/opensearch-project/opensearch-sdk-java/issues/587 …

Consume all params and content on extension Rest Request exception

---

CHANGELOG.md
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/plugins/ClusterPlugin.java
server/src/test/java/org/opensearch/plugins/ClusterPluginTests.java

Manually backports #7919 to 2.x

[Backport 2.x] Pass localNode info to all plugins on node start

---

.github/workflows/stalled.yml

This action labels PRs as "stalled" after 30 days, then closes them 7 days later if no follow up.
The following choices here were all fairly arbitrary and open for discussion:
- When to run: every morning, Pacific Time
- What label to use: `stalled`, because it already exists in the repo but appears to be unused
- Inactivity period to label as stalled: 30 days
- Period after stalled before closing: 7 days
Resolves #8093

Add action to label and close stalled PRs

---

build.gradle
buildSrc/build.gradle
buildSrc/src/main/groovy/org/opensearch/gradle/CheckCompatibilityTask.groovy

This change adds a gradle task to check the compatibility with any child projects/components. The task is dependent on `publishToMavenLocal` as it publishes the core engine to maven local and then clones the remote project in temporary directory and runs `./gradlew assemble`.
The task takes 2 inputs:
1. repositoryUrls: a comma separated git url of the components. Defaults to https://raw.githubusercontent.com/opensearch-project/opensearch-plugins/main/plugins/.meta
2. ref: branch or reference to checkout. Defaults to `main`
Run with specific components:
```
./gradlew checkCompatibility
> Task :checkCompatibility
Incompatible components: [git@github.com:opensearch-project/k-nn.git, git@github.com:opensearch-project/asynchronous-search.git, …
```

Add a gradle task to check compability with child components

---

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_empty.yml
server/src/main/java/org/opensearch/search/aggregations/AggregatorFactories.java

Whenever `"aggs"` is passed into the request body, even if it is empty (ex. `"aggs": {},`), then this line will evaluate to true:
https://github.com/opensearch-project/OpenSearch/blob/8eea7b986453271cd227a7b98ee09e70d5e28634/server/src/main/java/org/opensearch/action/search/QueryPhaseResultConsumer.java#L117
Causing us to go down the wrong path and hit the NPE.
This behavior exists from before #7514 and was handled by various checks for the aggregators, for example like here: https://github.com/opensearch-project/OpenSearch/blob/2.8/server/src/main/java/org/opensearch/search/aggregations/AggregationPhase.java#L68-L74 where collectors are not added if the aggregators length is not 0.
Resolves #8115 …

Return null for aggregations factory even if empty aggs is present in search source

---

server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
server/src/test/java/org/opensearch/index/IndexServiceTests.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java

This PR attempts to make the remote translog upload buffer interval setting dynamic to allow changes even after index creation.
Resolves #8172 

[Remote translog] Make translog buffer interval setting dynamic

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/coordination/CompressedStreamUtils.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
server/src/test/java/org/opensearch/cluster/coordination/CompressedStreamUtilsTests.java
server/src/test/java/org/opensearch/cluster/coordination/JoinHelperTests.java
server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java

[Backport 2.x] Compress and cache cluster state during validate join request (#7321)
