- DEVELOPER_GUIDE.md
> Update Developers guide

- README.md
Update README with getting started instructions
Signed-off-by: Jonah Kowall <jkowall@kowall.net>
> Update README with getting started

- DEVELOPER_GUIDE.md
Ongoing changes to DEVELOPER_GUIDE.md
> [WIP] Developer guide updates

- .github/ISSUE_TEMPLATE/bug_template.md
This PR intends to add multiple labels for the issue template to better categorize the issues.
> Update issue template for multiple labels

- server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
backport of #629 
Changes the behavior of the recursive deletion function `executeOneStaleIndexDelete()` stop
condition to be when the queue of `staleIndicesToDelete` is empty -- also in the error flow.
Otherwise the GroupedActionListener never responds and in the event of a few exceptions the
deletion task gets stuck.
Alters the test case to fail to delete in bulk many snapshots at the first attempt, and then
the next successful deletion also takes care of the previously failed attempt as the test
originally intended.
SNAPSHOT threadpool is at most 5. So in the event we get more than 5 exceptions there are no
more threads to handle the deletion task and there is still one more snapshot to delete in the
queue. Thus, in the test I made the number of extra snapshots be one more than the max …
> [1.x] Fix snapshot deletion task getting stuck in the event of exceptions (#629)

- CONTRIBUTING.md
- README.md
Updating README and CONTRIBUTING guide to reflect real links and get ready for beta1.
We have couple of options:
1. Wait until the beta links are live and merge the PR.
2. Merge the PR and take the hit, i.e community running into broken links. 
> Updating README and CONTRIBUTING guide to get ready for beta1 release.

- server/src/main/java/org/opensearch/common/settings/Setting.java
- server/src/test/java/org/opensearch/common/settings/SettingTests.java
> [1.x][Backport] Create group settings with fallback. (#743)

- TESTING.md
**Backport** #689
Add clear instructions on how to run OpenSearch with debugging mode in IntelliJ. 
Fixed a few minor typos and grammars.
> [1.x] Update instructions on debugging OpenSearch. (#689)

- .github/ISSUE_TEMPLATE/bug_template.md
Backport #668
This PR intends to add multiple labels for the issue template to better categorize the issues.
> [1.x] Update issue template for multiple labels

- CONTRIBUTING.md
- README.md
Backport #672
Updating README and CONTRIBUTING guide to reflect real links and get ready for beta1.
We have couple of options:
1. Wait until the beta links are live and merge the PR.
2. Merge the PR and take the hit, i.e community running into broken links. 
> [1.x] Updating README and CONTRIBUTING guide to get ready for beta1 release.

- rest-api-spec/src/main/resources/rest-api-spec/test/cat.health/10_basic.yml
- server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
- server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
- server/src/main/java/org/opensearch/rest/action/cat/RestHealthAction.java
- server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java
- server/src/test/java/org/opensearch/cluster/health/ClusterStateHealthTests.java
Signed-off-by: Mohit Godwani <mgodwan@amazon.com>
Add discovered_master attribute to cluster health API response
https://github.com/opensearch-project/OpenSearch/issues/485
> Apply fix for health API response to distinguish no master

- server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java
- server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequestBuilder.java
- server/src/main/java/org/opensearch/action/support/broadcast/BroadcastRequest.java
- server/src/main/java/org/opensearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java
- server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java
- server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesInfoAction.java
- server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndicesStatsAction.java
- server/src/main/java/org/opensearch/rest/action/cat/AbstractCatAction.java
- server/src/main/java/org/opensearch/rest/action/cat/RestAllocationAction.java
- server/src/main/java/org/opensearch/rest/action/cat/RestCatRecoveryAction.java
- server/src/main/java/org/opensearch/rest/action/cat/RestNodeAttrsAction.java
- server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
- server/src/main/java/org/opensearch/rest/action/cat/RestPluginsAction.java
- server/src/main/java/org/opensearch/rest/action/cat/RestThreadPoolAction.java
- server/src/test/java/org/opensearch/action/support/broadcast/node/TransportBroadcastByNodeActionTests.java
Signed-off-by: Dhwanil Patel <dhwanip@amazon.com>
Backport of #552 
> [1.x] Add timeout on cat/stats API

- buildSrc/src/main/groovy/org/opensearch/gradle/NoticeTask.groovy
> [1.x] [Bug] Fix gradle build on Windows failing from a recent change

- server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardConstraintDeciderOverlapTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardHotSpotTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsLimitAllocationTests.java
- test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationWithConstraintsTestCase.java
Signed-off-by: Ashwin Pankaj <appankaj@amazon.com>
An allocation constraint mechanism, that de-prioritizes nodes from getting picked for allocation if they breach certain constraints
#487
> An allocation constraint mechanism, that de-prioritizes nodes from getting picked for allocation if they breach certain constraints

- release-notes/opensearch.release-notes-1.0.0-rc1.md
Adding release notes for OpenSearch 1.0.0-rc1.
This is generated using the tool: https://github.com/ariatemplates/git-release-notes
#789 
> Adding release notes for 1.0.0-rc1

- build.gradle
This PR enables the BWC checks in OpenSearch. The existing issues were fixed by the following PRs
- #764 
- #708 
- #775
- #797 
The following issues can be resolved.
- #669 
- #417 
- #113 
~- [ ] New functionality includes testing.~
> Enable BWC checks

- build.gradle
> [1.x] Enable BWC checks (#796)

- TESTING.md
Document running individual tests.
> Document running individual tests.

- rest-api-spec/src/main/resources/rest-api-spec/test/cat.health/10_basic.yml
- server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
- server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
- server/src/main/java/org/opensearch/rest/action/cat/RestHealthAction.java
- server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java
- server/src/test/java/org/opensearch/cluster/health/ClusterStateHealthTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/656
Signed-off-by: Mohit Godwani <mgodwan@amazon.com>
> [1.x] Apply fix for health API response to distinguish no master

- ADMINS.md
- MAINTAINERS.md
- README.md
- RELEASING.md
- SECURITY.md
Beginning of standardizing processes across the org for branching, admins, maintainers. Added security.
Partly #95.
> Updated READMEs on releasing, maintaining, admins and security.

- buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
- qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
- test/framework/src/main/java/org/opensearch/test/VersionUtils.java
- test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
This PR fixes up the version framework to ensure a smooth version bump across releases.
> [BUG] Fix versioning issues discovered through version bump

- buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
- qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
- test/framework/src/main/java/org/opensearch/test/VersionUtils.java
- test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
This PR fixes up the version framework to ensure a smooth version bump
across releases.
> [1.x] Fix versioning issues discovered through version bump (#884)

- buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
> Backport [1.x] - Add URL for lucene snapshots (858)

- release-notes/opensearch.release-notes-1.0.0.md
Updates release notes for OpenSearch 1.0.0 (GA) with new commits and removes #547
This is generated using the tool: https://github.com/ariatemplates/git-release-notes
#789 
> Update release note for GA 1.0

- ADMINS.md
- MAINTAINERS.md
- README.md
- RELEASING.md
- SECURITY.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/853 to 1.x.
Resolves #948 for 1.x. 
> [Backport-1.x] Updated READMEs on releasing, maintaining, admins and security. (#853)

- server/src/main/java/org/opensearch/rest/action/RestActionListener.java
When BytesRestResponse ctor throws exception construct new response based on the exception and send it instead of not sending response at all
> Fail fast when BytesRestResponse ctor throws exception

- server/src/main/java/org/opensearch/search/SearchService.java
- server/src/test/java/org/opensearch/search/SearchServiceTests.java
… on max scroll limit breach
Signed-off-by: Bukhtawar Khan bukhtawa@amazon.com
#1053 
> Max scroll limit breach to throw a OpenSearchRejectedExecutionException

- buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
- buildSrc/src/main/java/org/opensearch/gradle/plugin/PluginPropertiesExtension.java
- buildSrc/src/main/resources/plugin-descriptor.properties
- distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
- distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/ListPluginsCommand.java
- distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/PluginHelper.java
- distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/RemovePluginCommand.java
- distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
- distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/ListPluginsCommandTests.java
- distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/RemovePluginCommandTests.java
- server/src/main/java/org/opensearch/plugins/PluginInfo.java
- server/src/main/java/org/opensearch/plugins/PluginsService.java
- server/src/test/java/org/opensearch/nodesinfo/NodeInfoStreamingTests.java
- server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
- server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
> [Backport-1.x] Allowing custom folder name for plugin installation (#848)

- server/src/test/java/org/opensearch/search/SearchServiceTests.java
> [Backport-1.x] Reduce iterations to improve test run time (#1168)

- NOTICE.txt
- README.md
- buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPluginFuncTest.groovy
- buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPlugin.java
- distribution/packages/build.gradle
Signed-off-by: Minal Shah <minalsha@amazon.com>
Fixed copyright to OpenSearch
Closes #1056 
> Fixed copyright to OpenSearch

- DEVELOPER_GUIDE.md
Signed-off-by: Anas Alkouz <aalkouz@amazon.com>
Add more details into how to install and configure get secrets 
https://github.com/opensearch-project/OpenSearch/issues/1196 
> Add more instructions how to install/configure git secrets

- DEVELOPER_GUIDE.md
Guidelines for Eclipse developers
None
> Added Eclipse import instructions to DEVELOPER_GUIDE.md

- server/src/main/java/org/opensearch/index/engine/Engine.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
- server/src/main/java/org/opensearch/index/engine/MissingHistoryOperationsException.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/translog/Translog.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
- server/src/test/java/org/opensearch/index/translog/TranslogTests.java
- test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Changes to support retrieval of operations from translog based on specified range
https://github.com/opensearch-project/OpenSearch/issues/1100
> Changes to support retrieval of operations from translog based on specified range

- release-notes/opensearch.release-notes-1.1.0.md
Updates release notes for OpenSearch 1.1.0 
This is generated using the tool: https://github.com/ariatemplates/git-release-notes
#1229
> Generate release notes for 1.1

- server/src/main/java/org/opensearch/index/engine/Engine.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
- server/src/main/java/org/opensearch/index/engine/MissingHistoryOperationsException.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/translog/Translog.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
- server/src/test/java/org/opensearch/index/translog/TranslogTests.java
- test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Changes to support retrieval of operations from translog based on specified range
- Cherry picked from https://github.com/opensearch-project/OpenSearch/pull/1210
N/A
> [Backport] Changes to support retrieval of operations from translog based on specified range

- DEVELOPER_GUIDE.md
Signed-off-by: CEHENKLE <henkle@amazon.com>
Updating DEVELOPER_GUIDE to include component labels.  
I've recently started adding component labels to issues in the repo.   It's a housekeeping task to group like sets of work together, but I thought it'd be useful to explain what they were some where in case folks were curious and/or had suggestions on how to refine/improve them.  :)
> adding components to DEVELOPER_GUIDE

- TESTING.md
Add documentation for generating code coverage report, according to the code enhancement in https://github.com/opensearch-project/OpenSearch/pull/1236
#1237
> [DOCS] Add guide for generating code coverage report in TESTING.md

- buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy
- buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
- distribution/docker/build.gradle
- distribution/packages/build.gradle
Backport of #1251 to 1.1 branch.
> [Backport] Rename artifact produced by the build to include -min (#1251)

- buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
> [Backport] [1.x] Fix gradle check fail due to renameing -min

- server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
It seems like in very rare conditions, the snapshot kicks in **after** the data node is restarted, not before. Because of that, it succeeds right away instead of ending up in partial state. The suggested fix is just to wait a bit till the snapshot in question appears in the list of the snapshots which are in progress, and only than restart the data node.
https://github.com/opensearch-project/OpenSearch/issues/1272
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of …
> [BUG] ConcurrentSnapshotsIT#testAssertMultipleSnapshotsAndPrimaryFailOver fails intermittently

- server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
Backporting https://github.com/opensearch-project/OpenSearch/pull/1311 to 1.x
https://github.com/opensearch-project/OpenSearch/issues/1272
> [Backport] [1.x] [BUG] ConcurrentSnapshotsIT#testAssertMultipleSnapshotsAndPrimaryFailOver fails intermittently (#1311)

- buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java
- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Update bundled JDK distribution to 17.0.1+12
N/A
> Update bundled JDK distribution to 17.0.1+12

- build.gradle
> [BWC] Diable BWC tests until branch versions are synced

- qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartSettingsUpgradeIT.java
* Made changes.
Signed-off-by: Megha Sai Kavikondala <kavmegha@amazon.com>
* Signed-off-by: Megha Sai Kavikondala <kavmegha@amazon.com>
Changes made by deleting the TestSettingsIT file and adding new lines in FullClusterRestartSettingsUpgradeIT.java
Signed-off-by: Megha Sai Kavikondala <kavmegha@amazon.com>
Description
An Integration test which checks for the settings upgrade by setting the legacy settings for the previous version of ODFE/ES in the old cluster and after upgrading it to the new version, checks if the settings fallback to the previously set settings.
Issues Resolved
#670
Check List
New functionality includes testing.
All tests pass
New functionality has been documented.
New functionality has javadoc added
Commits are signed per the DCO …
> Integration test that checks for settings upgrade  (#1482)

- MAINTAINERS.md
- plugins/repository-hdfs/licenses/avro-NOTICE.txt
- qa/os/README.md
Updated links for linkchecker
#1515 
> Updated links for linkchecker

- .github/workflows/precommit.yml
- .github/workflows/wrapper.yml
Backport of https://github.com/opensearch-project/OpenSearch/pull/1664
> Move Gradle wrapper and precommit checks into OpenSearch repo. (#1664)

- release-notes/opensearch.release-notes-1.2.2.md
Adding release notes for 1.2.2
> Adding release notes for 1.2.2

- release-notes/opensearch.release-notes.1.2.3.md
Added release notes for 1.2.3.
> Added release notes for 1.2.3.

- gradle/wrapper/gradle-wrapper.properties
> Update to Gradle 7.3.3

- MAINTAINERS.md
Signed-off-by: CEHENKLE <henkle@amazon.com>
Updates to MAINTAINERS.md from Q4 2021
> Catching Maintainers up for Q4 2021 new additions/removals

- TESTING.md
Fixes some typos. Creating this PR to test the auto-backport workflow from PR #1845 
> Fixing typo in TESTING.md

- .github/dependabot.yml
Update the open pull requests limit for dependabot to allow creating PRs for version updates. Reference: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit
> Updating dependabot open pr limits

- DEVELOPER_GUIDE.md
Added instructions to help build various distributions and local distro.
> Added help to build distributions in docs

- server/src/main/java/org/opensearch/plugins/SearchPlugin.java
Add and clarify some search plugin point documentation.
#1905 
> Expand SearchPlugin javadocs.

- server/src/main/java/org/opensearch/transport/InboundHandler.java
- server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/1885 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/624
> [Backport] [1.x] [BUG] Serialization bugs can cause node drops (#1885)

- release-notes/opensearch.release-notes-1.2.4.md
> Add release notes for 1.2.4

- server/src/internalClusterTest/java/org/opensearch/index/ShardIndexingPressureSettingsIT.java
Signed-off-by: Suraj Singh surajrider@gmail.com
Backports [PR](https://github.com/opensearch-project/OpenSearch/pull/1939) to 1.x
1843
> Timeout fix backport to 1.x

- buildSrc/version.properties
> Update Mockito to 4.3.1

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Update bundled JDK distribution to 17.0.2+8
Release notes: https://jdk.java.net/17/release-notes
N/A
> Update bundled JDK distribution to 17.0.2+8

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Backport of https://github.com/opensearch-project/OpenSearch/pull/2007 to 1.x
N/A
> [Backport] [1.x] Update bundled JDK distribution to 17.0.2+8 (#2007)

- .github/workflows/version.yml
Fixing indentation in `version.yml` from PR #2157. I introduced an incorrect indentation which is leading to invalid workflow file errors https://github.com/opensearch-project/OpenSearch/actions/runs/1861424013 :woman_facepalming:
> Fixing the indentation in version.yml

- rest-api-spec/src/main/resources/rest-api-spec/test/search/230_interval_query.yml
- server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
Update the bwc versions for #2237 since it was backported to 1.3.
> Update bwc verions for (#2237)

- distribution/tools/java-version-checker/build.gradle
Fixing `java-version-checker` build
Fixes https://github.com/opensearch-project/OpenSearch/pull/2352
> Fix java-version-checker source/target compatibility settings

- README.md
Adds trademark notice to README
n/a
> Add trademark notice

- README.md
Signed-off-by: Kyle J. Davis <kyledvs@amazon.com>
Backports changes to README
#2476
> adds trademark to README

- .github/workflows/version.yml
Backport https://github.com/opensearch-project/OpenSearch/pull/2157 https://github.com/opensearch-project/OpenSearch/pull/2163 https://github.com/opensearch-project/OpenSearch/pull/2572
> Backporting changes for version workflow

- server/src/main/java/org/opensearch/bootstrap/Security.java
- server/src/main/java/org/opensearch/discovery/PluginRequest.java
- server/src/main/java/org/opensearch/discovery/PluginResponse.java
- server/src/main/java/org/opensearch/env/Environment.java
- server/src/main/java/org/opensearch/extensions/DiscoveryExtension.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/plugins/PluginsOrchestrator.java
- server/src/main/java/org/opensearch/transport/TransportService.java
Adding initial support for extensions
> [Feature branch: extensions] Adding initial support for extensions

- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/indices/ShardLimitValidator.java
- server/src/main/java/org/opensearch/indices/SystemIndices.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
- server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java
- server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
Excluding the system indices from max shard limit validation
#2824 
> Excluding system indices from max shard limit validator

- modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
- modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
Scaled float field mapper returns an error when Json parsing fails even though `ignoreMalformed` setting is set to true.
This PR fixes the problem to pass through and index only when `ignoreMalformed` is set.
1. Index:
```
curl -XPUT localhost:9200/test -H "Content-Type:application/json" --data ' 
{                  
"mappings": {                    
"amount": {
"type": "scaled_float",
"ignore_malformed": true,
"scaling_factor": 100.0
}
}
},
"settings": {
"index.mapping.ignore_malformed": "true"
}
}'
```
2. Search:
```
curl -XPOST "localhost:9200/test/_doc?pretty" --data '{                    
"amount": false
}' -H "Content-Type:application/json"
{
"error" : {
{
"type" : …
```
> Fixing Scaled float field mapper to respect ignoreMalformed setting

- modules/mapper-extras/src/main/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapper.java
- sandbox/plugins/concurrent-search/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
- server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java
- server/src/main/java/org/opensearch/index/mapper/StringFieldType.java
- server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
- server/src/main/java/org/opensearch/index/query/RegexpQueryBuilder.java
- server/src/main/java/org/opensearch/index/search/MatchQuery.java
- server/src/main/java/org/opensearch/index/search/QueryStringQueryParser.java
- server/src/test/java/org/opensearch/deps/lucene/VectorHighlighterTests.java
- server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
> Remove usages of MultiTermQuery.setRewriteMethodsetRewriteMethod

- release-notes/opensearch.release-notes-1.3.1.md
Adding in the release notes for 1.3.1 release 
https://github.com/opensearch-project/OpenSearch/releases/tag/1.3.1 
> Add release notes for 1.3.1

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Update bundled JDKs to addresses recently disclosed/found CVEs
Part of https://github.com/opensearch-project/OpenSearch/issues/3026
> Update bundled JDK to 11.0.15+10

- server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java
- server/src/main/java/org/opensearch/index/IndicesModuleNameResponse.java
- server/src/main/java/org/opensearch/index/IndicesModuleRequest.java
- server/src/main/java/org/opensearch/index/IndicesModuleResponse.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/plugins/PluginsOrchestrator.java
- server/src/main/java/org/opensearch/plugins/PluginsService.java
- server/src/main/java/org/opensearch/transport/TransportService.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Adding support for first example extension point and some refactoring.
This change is for feature/extensions branch.
> [Feature/extensions] Adding extension framework support for first extension point 

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Backport of #3100
Part of #3026 
> [Backport to 1.3] Update bundled JDK to 11.0.15+10 (#3100)

- MAINTAINERS.md
Fixes emeritus table formatting in Maintainers document.
> Fix Emeritus Table in MAINTAINERS.md

- release-notes/opensearch.release-notes-1.3.2.md
> Add release notes for 1.3.2

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Update bundled JDKs to addresses recently disclosed/found CVEs
Part of https://github.com/opensearch-project/OpenSearch/issues/3026
> Update bundled JDK to 17.0.3+7

- server/src/main/java/org/opensearch/extensions/package-info.java
> Added missing package-info.java file

- server/src/main/java/org/opensearch/extensions/package-info.java
> [Feature/extensions] Resolved javadoc error

- plugins/repository-s3/build.gradle
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
- plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/60_repository_eks_credentials.yml
- test/fixtures/s3-fixture/Dockerfile.eks
- test/fixtures/s3-fixture/docker-compose.yml
- test/fixtures/s3-fixture/src/main/java/fixture/s3/S3HttpFixtureWithEKS.java
Took me a while but finally succeeded with adding a YAML Rest Test case to verify use of IRSA for `repository-s3` plugin credentials (typically used with Amazon EKS).
Test case for https://github.com/opensearch-project/OpenSearch/issues/2999
> Added YAML Rest Test case to verify use of IRSA for repository-s3 plugin credentials. 

- release-notes/opensearch.release-notes-1.3.3.md
> Add release notes for 1.3.3

- release-notes/opensearch.release-notes-2.0.1.md
- Add release notes for 2.0.1
- Part of [2165](https://github.com/opensearch-project/opensearch-build/issues/2165)
> Add release notes for version 2.0.1

- .github/workflows/gradle-check.yml
[Backport 2.0] Update github action gradle-check to use pull_request_target for accessing token
https://github.com/opensearch-project/opensearch-build/issues/851
> [Backport 2.0] Update github action gradle-check to use pull_request_target for accessing token

- .github/workflows/gradle-check.yml
- .github/workflows/wrapper.yml
This is a combination of 3 commits to backport the latest gradle check updates to the 1.3 branch.
https://github.com/opensearch-project/OpenSearch/commit/60f3e5bf34d71dd645634bc0afa2e773bf36f4f1
https://github.com/opensearch-project/OpenSearch/commit/d155d7efdb2fdd299719661747227d8c00269e98
https://github.com/opensearch-project/OpenSearch/commit/3ffadc8f35e095d36f8ca22f67a35bf1193814be
> [Backport 1.3] Backport gradle check updates to 1.3 branch.

- README.md
Signed-off-by: Sai Sampath Kumar Balivada <balivadask2000@gmail.com>
Adds a Codecov status badge as a part of issue #850
Merge after #1320 is implemented.
Fixes #1323
> Adds status badge for showing code coverage in README

- release-notes/opensearch.release-notes-1.3.4.md
Add release notes for patch release 1.3.4.
> Add release notes for release 1.3.4.

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
OpenJDK Update (July 2022 Patch releases).
Closes https://github.com/opensearch-project/OpenSearch/issues/4011
> OpenJDK Update (July 2022 Patch releases)

- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
- server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
- server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/TranslogManager.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
- server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
- server/src/test/java/org/opensearch/index/engine/NoOpEngineTests.java
- server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
- test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Signed-off-by: Satyajit Ganguly <satyajga@amazon.com>
This PR aims to encapsulate Translog into TranslogManager. Original PR [link](https://github.com/opensearch-project/OpenSearch/pull/3751).
> [Backport 2.x] Changes to encapsulate Translog into TranslogManager

- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
- server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
- server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/TranslogManager.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
- server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
- server/src/test/java/org/opensearch/index/engine/NoOpEngineTests.java
- server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
- test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Original [PR](https://github.com/opensearch-project/OpenSearch/pull/4095) for 2.x backport.
(cherry-picked from commit: 98dfdf5eab081194487bccacbfb45cecf319e974 of 2.x branch)
> [Backport 2.2] Changes to encapsulate Translog into TranslogManager

- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
> [Backport 2.1] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected

- server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
- server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
> [Backport 2.0] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected

- distribution/src/bin/opensearch-service.bat
Backport to 2.x for https://github.com/opensearch-project/OpenSearch/pull/4289
> [Backport 2.x] Bug fix for opensearch-service.bat

- distribution/src/bin/opensearch-service.bat
Backport to 1.x for https://github.com/opensearch-project/OpenSearch/pull/4289
> [Backport 1.x] Bug fix for opensearch-service.bat

- CHANGELOG.md
- MAINTAINERS.md
I nominated Suraj Singh (@dreamer-89) to be a co-maintainer for Opensearch through our [nomination process](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#nomination). The maintainers have agreed, and Suraj has kindly accepted.
Suraj has quickly become one of the [top contributors to OpenSearch](https://github.com/opensearch-project/OpenSearch/graphs/contributors?from=2021-05-27&to=2022-08-15&type=c) since the fork, authoring [70 PRs](https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+author%3Adreamer-89+is%3Aclosed+) and reviewing numerous others from his peers. His major contributions include:
* [Removal of mapping types](https://github.com/opensearch-project/OpenSearch/issues/1940), which was released …
> Adding @dreamer-89 to Opensearch maintainers.

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.5.md
Add release notes for patch release 1.3.5
> Add release notes for patch release 1.3.5

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.2.1.md
Add release notes for patch release 2.2.1
> Add release notes for patch release 2.2.1

- CHANGELOG.md
- distribution/src/bin/opensearch-service.bat
- distribution/src/bin/opensearch.bat
Backport to 1.x for https://github.com/opensearch-project/OpenSearch/pull/4305
> [Backport 1.x] Bug fix for missing logs directory

- release-notes/opensearch.release-notes-1.3.5.md
> [Backport 1.3] Add release notes for patch release 1.3.5 (#4343)

- release-notes/opensearch.release-notes-2.2.1.md
> [Backport 2.2] Add release notes for patch release 2.2.1 (#4344)

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
Signed-off-by: Ajay Kumar Movva <movvaam@amazon.com>
Modified `cat/shards` Rest tests for the point in time stats.
> Modified cat shards test for pit stats

- .github/CODEOWNERS
- .github/dependabot.yml
- CHANGELOG.md
Backport the `CODEOWNERS` file and `dependabot.yml` configuration to `1.x` since these are missing here.
N/A
> Backport CODEOWNERS and dependabot.yml files

- CHANGELOG.md
Catches up the changelog for`feature/extensions` branch with all merged (and non-reverted) PRs.
See discussion on #4477
- ~[ ] All tests pass~
> [Feature/extensions] Catch up feature/extensions branch CHANGELOG

- CHANGELOG.md
- IDENTITY_ROADMAP.md
Fill in the identity roadmap for broad review
> [Feature/Identity] Fill in the identity roadmap for broad review

- CHANGELOG.md
- buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
Related commit: 0e9f74e35f1255cb9ec45be3d8960aad195a9f6e
(cherry picked from commit 2c0277be599d1683e189349fd80be38fabb519b9)
> Fix invalid search location of JDK for arm64 (#4613)

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
- server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommand.java
- server/src/main/java/org/opensearch/index/shard/ShardStateMetadata.java
- server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
- server/src/main/java/org/opensearch/index/store/InMemoryRemoteSnapshotDirectory.java
- server/src/main/java/org/opensearch/index/store/RemoteSnapshotDirectoryFactory.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
- server/src/test/java/org/opensearch/index/shard/ShardPathTests.java
- server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
- test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java
Also includes #4774 in this backport because that was a bug fix for the original PR
> [Backport 2.x] Introduce experimental searchable snapshot API

- CHANGELOG.md
- buildSrc/src/testFixtures/java/org/opensearch/gradle/test/JUnit3MethodProvider.java
- client/rest-high-level/src/test/java/org/opensearch/client/RestHighLevelClientTests.java
- modules/lang-painless/src/main/java/org/opensearch/painless/Compiler.java
- modules/lang-painless/src/main/java/org/opensearch/painless/PainlessScriptEngine.java
- modules/lang-painless/src/main/java/org/opensearch/painless/ScriptClassInfo.java
- modules/lang-painless/src/main/java/org/opensearch/painless/lookup/PainlessLookupBuilder.java
- test/logger-usage/src/test/java/org/opensearch/test/loggerusage/OpenSearchLoggerUsageTests.java
Backport 763ef13ad42cb912fb406c5d42fa7f76e3708e89 from #4821.
> [Backport] [2.4] Use getParameterCount instead of getParameterTypes (#4821)

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
- server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
- server/src/main/java/org/opensearch/index/store/remote/utils/BlobFetchRequest.java
- test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
- Backports #5055 , #5048 to 2.4
- #4962 
> Add integration tests for searchable snapshots, Fix length calculation for block based storage

- modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
Signed-off-by: Xiao Cui <constantine124@gmail.com>
Clean up unused semicolon, shouldn't affect any functionalities/tests
> Cleanup: remove unused semicolon

- client/rest/src/main/java/org/opensearch/client/Response.java
- server/src/main/java/org/opensearch/common/logging/HeaderWarning.java
- server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
- server/src/main/java/org/opensearch/common/logging/LoggerMessageFormat.java
Remove Elasticsearch from HTTP header warning message. Remove unused variables, redundant method calls and simplify conditions.
N/A
> Clean up common logging code

- gradle/wrapper/gradle-wrapper.properties
> Update Gradle to 7.6-rc3

- server/src/main/java/org/opensearch/OpenSearchException.java
> Fix typo in comment in OpenSearchException

- .github/workflows/gradle-check.yml
Complete copy of gradle-check from main.
Backport https://github.com/opensearch-project/OpenSearch/pull/5297
> [Backport 2.x] #5297 ++

- gradle/wrapper/gradle-wrapper.properties
> Update Gradle to 7.6-rc-4

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java
- server/src/test/java/org/opensearch/action/bulk/BulkRequestParserTests.java
> [Backport 2.x] Reject bulk requests with invalid actions (#5302)

- server/src/main/java/org/opensearch/Version.java
Update Apache Lucene to 9.4.2 for OpenSearch 2.4.1
See please https://github.com/opensearch-project/OpenSearch/pull/5361
> Update Apache Lucene to 9.4.2 for OpenSearch 2.4.1

- sandbox/libs/authn/docs/auth_flow.md
Include high-level documentation about auth flows and node-to-node communication
> [Feature/Identity] Include high-level documentation about auth flows and node-to-node communication

- server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
Fixing supported version after https://github.com/opensearch-project/OpenSearch/pull/5498
Part of https://github.com/opensearch-project/OpenSearch/issues/5170
> Add max_shard_size parameter for Shrink API (fix supported version after backport)

- release-notes/opensearch.release-notes-1.3.7.md
Signed-off-by: owaiskazi19 <owaiskazi19@gmail.com>
Updated 1.3.7 release note date
> Updated 1.3.7 release note date

- release-notes/opensearch.release-notes-2.4.1.md
Update release note date. 
Related https://github.com/opensearch-project/opensearch-build/issues/2925
> Update release date in 2.4.1 release notes

- release-notes/opensearch.release-notes-2.4.1.md
Add release notes for 2.4.1
Related: https://github.com/opensearch-project/opensearch-build/issues/2925
> Add release notes for 2.4.1

- release-notes/opensearch.release-notes-2.4.1.md
Update 2.4.1 release notes
N/A
> Update 2.4.1 release notes

- server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/index/IndexService.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommand.java
- server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/index/IndexModuleTests.java
- server/src/test/java/org/opensearch/index/IndexSettingsTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Users will be able to create remote translog enabled indices
> Enable creation of indices using Remote Translog   

- .github/CODEOWNERS
> Adding @gbbafna to code owners

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/action/admin/indices/rollover/RolloverIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateNumberOfReplicasIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/template/SimpleIndexTemplateIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
- server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
* Add default replica count config settings
Signed-off-by: Arpit Bandejiya <abandeji@amazon.com>
> Backport[2.x]: Add support of default replica count change (#5610)

- CHANGELOG.md
- server/src/main/java/org/opensearch/index/translog/BufferedChecksumStreamInput.java
- server/src/main/java/org/opensearch/index/translog/Checkpoint.java
- server/src/main/java/org/opensearch/index/translog/TranslogReader.java
- server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
- server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java
- server/src/main/java/org/opensearch/index/translog/transfer/FileTransferException.java
- server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
- server/src/main/java/org/opensearch/index/translog/transfer/TransferSnapshot.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
- server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
- server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
- server/src/main/java/org/opensearch/index/translog/transfer/listener/package-info.java
- server/src/main/java/org/opensearch/index/translog/transfer/package-info.java
- server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
* Introduce remote translog transfer support
> [Backport 2.x] [Remote Translog] Introduce remote translog transfer support (#4480)

- .github/CODEOWNERS
> [Backport  2.5] Adding @gbbafna to code owners 

- CHANGELOG.md
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
- buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
- buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
- buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
- distribution/archives/integ-test-zip/build.gradle
- modules/build.gradle
- server/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/5704 to `2.x`
> [Backport] [2.x] Update nebula-publishing-plugin to 19.2.0 (#5704)

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/pit/DeletePitMultiNodeIT.java
- server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
Signed-off-by: Bharathwaj G <bharath78910@gmail.com>
Backport of PR - https://github.com/opensearch-project/OpenSearch/pull/5750/files
> [Backport 2.5] Renaming PIT tests to IT in order to fix intermittent failures

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/pit/DeletePitMultiNodeIT.java
- server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
Backport of PR - https://github.com/opensearch-project/OpenSearch/pull/5750/files
> [Backport 2.x] Renaming tests to IT to fix PIT tests intermittent failures

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
- server/src/internalClusterTest/java/org/opensearch/cluster/ClusterAwarenessHealthIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
- server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestBuilder.java
- server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
- server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
- server/src/main/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessHealth.java
- server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
- server/src/test/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessHealthTests.java
Signed-off-by: Nishchay Malhotra <nishcha@amazon.com>
Backport https://github.com/opensearch-project/OpenSearch/pull/5694
https://github.com/opensearch-project/OpenSearch/issues/5230.
> [Backport 2.5]Awareness health api rest and transport layer changes

- server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
- server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
Signed-off-by: Nishchay Malhotra <nishcha@amazon.com>
Backport https://github.com/opensearch-project/OpenSearch/pull/5694
https://github.com/opensearch-project/OpenSearch/issues/5230.
> [2.x] Changing min version required for Awareness health api to 2.5

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequest.java
- server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequestBuilder.java
- server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java
- server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java
- server/src/main/java/org/opensearch/cluster/decommission/DecommissionHelper.java
- server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
- server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
- server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
- server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java
- server/src/test/java/org/opensearch/cluster/decommission/DecommissionHelperTests.java
- server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataSerializationTests.java
- server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataTests.java
- server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataXContentTests.java
- server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java
Backport https://github.com/opensearch-project/OpenSearch/pull/5542
> [Backport 2.5] Gracefully handle concurrent zone decommission action (#5542)

- release-notes/opensearch.release-notes-2.5.0.md
- Fixes release notes for v2.5
- N/A
> Update release notes

- release-notes/opensearch.release-notes-2.5.0.md
- Adds release notes for v2.5.0
- N/A
> [Backport 2.5] Add release notes for v2.5.0

- CHANGELOG.md
- Fixes the 2.4 changelog post 2.4.1 release
> Update changelog for 2.4 post release

- CHANGELOG.md
- Clear out the changelog post release note generation
- N/A
> Update changelog post release

- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
Fix for the issue described in #5706. 
There is an existing race condition for segment replication where a replica could receive a checkpoint when it hits POST_RECOVERY and processes it. This will be followed by a round of segment replication which will not block for any ongoing replications. We want to avoid this situation where parallel rounds of segment replication events might take place. 
This PR adds a check for this scenario. 
Resolves #5706 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIB …
> [Segment Replication] Adding check to avoid parallel replication events taking place

- server/src/internalClusterTest/java/org/opensearch/indices/IndexingMemoryControllerIT.java
- server/src/main/java/org/opensearch/index/engine/EngineConfig.java
- server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
- server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
- server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
- server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
- server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
- server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
- test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
* Add builder for EngineConfig
Original PR - https://github.com/opensearch-project/OpenSearch/pull/5618
> [Backport 2.x] Add builder for EngineConfig (#5618)

- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Muting on Windows until it is fixed.
related https://github.com/opensearch-project/OpenSearch/issues/5923.
> Muting TranslogTransferManagerTests on Windows.

- DEVELOPER_GUIDE.md
Several changes have not been backported. This commit was created with the following command:
```
git checkout main DEVELOPER_GUIDE.md
```
> [Backport 2.x] Reconcile DEVELOPER_GUIDE.md

- CHANGELOG.md
This PR fixes changelog entry. The task that this changelog entry tracks needs to in 2.x. release. 
> Fix changelog entry and move to 2.x section

- CHANGELOG.md
Removes build related entry from https://github.com/opensearch-project/OpenSearch/pull/4587.
See https://github.com/opensearch-project/OpenSearch/pull/6097#discussion_r1091224664
N/A
> Remove CI related changelog entry.

- CHANGELOG.md
> Move dependency updates that have been backported

- sandbox/libs/authn/docs/auth_flow.md
Documentation for in-process authentication state
> Documentation for in-process authentication state

- release-notes/opensearch.release-notes-1.3.8.md
> Add release notes for 1.3.8

- .github/ISSUE_TEMPLATE/failed_check.md
- .github/workflows/gradle-check.yml
Update the autocut with a better description of why the issue was raised.  Also add the branch name to issue title.
N/A
> Improve autocut issue content on push gradle check failure.

- gradle/wrapper/gradle-wrapper.properties
Update Gradle to 8.0.1 (https://github.com/gradle/gradle/releases/tag/v8.0.1)
N/A
> Update Gradle to 8.0.1

- server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
Fixes flaky test testConsecutiveWritesAtLeastBufferIntervalAway in BufferedAsyncIOProcessorTests by
- Increasing the minimum value of buffer interval in the test case.
- As per [Java documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/System.html#currentTimeMillis()), the resolution of `System.nanoTime()` is as atleast as good as `System. currentTimeMillis()` which has a resolution of 10s of milliseconds. Hence adjusting the comparison check to allow certain degree of buffer.  
This fixes #6317. …
> [Remote Translog] Fix flaky test in BufferedAsyncIOProcessorTests

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- Currently, integ tests which check restore flow are written in generic way.
- To make it generic, we used `randomBoolean()`to decide between `refresh` and `flush` and `randomIntBetween` to decide number of rotations.
- This makes it very hard to debug a failing test or in some cases, difficult to reproduce the bug.
- With this change, we are moving away with generic test and adding specific tests for each scenario.
> Refactor remote store integ tests to add scenario specific tests

- CHANGELOG.md
- rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
* Update API spec for cluster health API
Backport PR - https://github.com/opensearch-project/OpenSearch/pull/6399
> [Backport -2.x]Update API spec for cluster health API (#6399)

- server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java
- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
- server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
- server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
- server/src/test/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationActionTests.java
This is a backport PR for #6268, which fixes flaky tests and refactors code.
Resolves https://github.com/opensearch-project/OpenSearch/issues/6261, https://github.com/opensearch-project/OpenSearch/issues/6255
> [Backport 2.x] [Segment Replication] Backport of #6268

- server/src/test/java/org/opensearch/search/backpressure/trackers/HeapUsageTrackerTests.java
Adding unit test for the bug fix in Search backpressure.
#5173
Signed-off-by: PritLadani <pritkladani@gmail.com>
> Adding unit test for test isHeapUsageDominatedBySearch

- server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
- server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
- server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
- test/framework/src/main/java/org/opensearch/test/transport/CapturingTransport.java
- test/framework/src/main/java/org/opensearch/test/transport/MockTransport.java
Backports https://github.com/opensearch-project/OpenSearch/pull/6523 to `2.x`
> [Segment Replication] Add new segrep settings (#6523)

- gradle/wrapper/gradle-wrapper.properties
> Update Gradle to 8.0.2

- server/src/main/java/org/opensearch/bootstrap/Security.java
> [Backport 2.x] Backporting extensions directory permissions

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
- server/src/main/java/org/opensearch/repositories/fs/FsRepository.java
- server/src/main/java/org/opensearch/search/DocValueFormat.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- server/src/test/java/org/opensearch/repositories/fs/FsRepositoryTests.java
- server/src/test/java/org/opensearch/search/DocValueFormatTests.java
- Backports #6357 and #6558 to 2.x
- NA
> [Backport 2.x] Backports 6558 and 6537 

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/Setting.java
- server/src/main/java/org/opensearch/common/settings/WriteableSetting.java
- server/src/test/java/org/opensearch/common/settings/SettingTests.java
Add Regex Validator implement Writeable and Validator to make Validator writeable for custom setting. 
Fixes https://github.com/opensearch-project/opensearch-sdk-java/issues/350
> [Extensions] Add Regex validator

- server/src/test/java/org/opensearch/search/DocValueFormatTests.java
update UT for DocUalueFormat
[6581]
> Ut doc value format test

- .github/CODEOWNERS
- MAINTAINERS.md
Update the list of maintainers
Resolves #6319 
> Update Maintainers List

- release-notes/opensearch.release-notes-1.3.9.md
> Adds release notes for 1.3.9

- .github/workflows/publish-maven-snapshots.yml
The recent workflow run failed for 1.3 due to mismatched java version https://github.com/opensearch-project/OpenSearch/actions/runs/4452471724
Tested with java 11 works well.
<details><summary>Details</summary>
<p>
```
% tree snapshots
snapshots
└── org
└── opensearch
├── client
│   ├── client-benchmarks
│   │   ├── 1.3.10-SNAPSHOT
│   │   │   ├── client-benchmarks-1.3.10-20230318.000649-1.jar
│   │   │   ├── client-benchmarks-1.3.10-20230318.000649-1.jar.md5
│   │   │   ├── client-benchmarks-1.3.10-20230318.000649-1.jar.sha1
│   │   │   ├── client-benchmarks-1.3.10-20230318.000649-1.jar.sha256
│   │   │   ├── client-benchmarks-1.3.10-20230318.000649-1.jar.sha512
│   │   │   ├── client-benchmarks-1.3.10-20230318.000649-1-javadoc.jar
│   │   │   ├── …
```
> Fix java version for 1.3 maven snapshots

- server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
- server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
> Add privileged section to remote fetch/file cache write

- server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
- server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
… for this scenario.
Signed-off-by: varuntumbe <varuntumbe1@gmail.com>
NPE and OpenSearch crash on malformed Extensions.yml
https://github.com/opensearch-project/opensearch-sdk-java/issues/583
> [Extensions] BUG NPE handling and malformed Extension.yml

- .github/ISSUE_TEMPLATE/failed_check.md
- Adds `autocut` label for gradle check failure issues cut post merge to help with issue bucketization
- N/A
> Add autocut label for autocut issues

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
- server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
- server/src/main/java/org/opensearch/cluster/ClusterModule.java
- server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
- server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
- server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
- server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/common/util/FeatureFlags.java
- server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
- server/src/test/java/org/opensearch/node/NodeTests.java
(cherry picked from commit 1c8421805955341ab692b003416b45b8d55ccd24)
- Backports #7117 to `2.x`
- N/A
> [Backport 2.x] Remove feature flag for searchable snapshots (#7117)

- server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
- server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
- server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
> Update version guards for searchable snapshots

- CHANGELOG.md
Adds changelog which was missed in https://github.com/opensearch-project/OpenSearch/pull/6932/files
NA
> Add changelog for remote store cluster level settings

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.7.0.md
This PR adds release notes for v2.7.0
#6967 
> Add release notes for v2.7.0

- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
- test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
> [Backport 2.7] Fix snapshotting searchable snapshot indexes (#7247)

- server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
- test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
> [Backport 2.x] Fix snapshotting searchable snapshot indexes (#7247)

- gradle/wrapper/gradle-wrapper.properties
> Update Gradle to 8.1.1

- DEVELOPER_GUIDE.md
When adding dependencies one has to do a bunch of things such as updating licenses and SHAs. I believe licenses are added manually.
> Updated developer guide for adding dependencies.

- CHANGELOG.md
- Syncs changelog for 2.x section with main
N/A
> Sync changelog for 2.x with main

- libs/common/src/main/java/org/opensearch/common/Numbers.java
Fix flaky SignificantTermsAggregatorTests, a very rare failure observed here (https://build.ci.opensearch.org/job/gradle-check/15149/testReport/junit/org.opensearch.search.aggregations.bucket.terms/SignificantTermsAggregatorTests/testSupportedFieldTypes/):
```
java.lang.AssertionError: Aggregator [significant_terms] supports field type [unsigned_long] but executing against the field threw an exception: [Value [0] is out of range for an unsigned long]
at __randomizedtesting.SeedInfo.seed([B2AD85EC7DE1CCCF:15BE38D802C515FC]:0)
at org.opensearch.search.aggregations.AggregatorTestCase.testSupportedFieldTypes(AggregatorTestCase.java:805)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
N/A …
> Fix flaky SignificantTermsAggregatorTests

- CHANGELOG.md
Add changelog entry for XContent parsing constraints )https://github.com/opensearch-project/OpenSearch/pull/7550)
> Add changelog entry for XContent parsing constraints

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.10.md
> Adds 1.3.10 release notes

- .github/CODEOWNERS
- CHANGELOG.md
- MAINTAINERS.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/7665
> [Backport-2.x] Added @dbwiddis to OpenSearch maintainers

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.8.0.md
This PR adds release notes for the v2.8.0 release.
https://github.com/opensearch-project/OpenSearch/issues/7664
> Add release notes v2.8.0

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.8.0.md
> [Backport 2.8] Add release notes v2.8.0 (#7825)

- rest-api-spec/src/main/resources/rest-api-spec/test/tasks.list/10_basic.yml
- server/src/main/java/org/opensearch/tasks/TaskResourceStats.java
Bring https://github.com/opensearch-project/OpenSearch/pull/7856 to `main`
> Concurrent Search Tasks Response Updates (update BWC versions)

- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
- server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandler.java
- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
- server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Backports https://github.com/opensearch-project/OpenSearch/pull/7777 into 2.x
> [Remote Segment Store] Combine metadata and snapshot files (#7777)

- CHANGELOG.md
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/opensearch/gradle/plugin/OptionalDependenciesPlugin.groovy
- buildSrc/src/main/resources/META-INF/gradle-plugins/opensearch.optional-dependencies.properties
- libs/cli/build.gradle
- libs/core/build.gradle
- server/build.gradle
Backport of https://github.com/opensearch-project/OpenSearch/pull/7068 to `2.x`
> [Backport] [2.x] Bump com.netflix.nebula:gradle-extra-configurations-plugin from 9.0.0 to 10.0.0 in /buildSrc (#7068)

- .github/workflows/poc-checklist.yml
Add a Github action workflow that adds a comment to all issues tagged with label "poc" with a checklist of potential pitfalls to keep in mind during the design of the poc for a feature.
Need a maintainer/code owner to create a label titled "poc" since I am not able to. 
Resolves #8028 
> Workflow to add a checklist for POC issues

- server/src/internalClusterTest/java/org/opensearch/cluster/ClusterAwarenessHealthIT.java
- server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestTests.java
Signed-off-by: Nishchay Malhotra <nishcha@amazon.com>
Refactoring the IT class
Refactoring the IT class
> Fixed capitalization in ClusterAwarenessHealthIT class name

- plugins/repository-s3/build.gradle
- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java
- plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/20_repository_permanent_credentials.yml
- plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/30_repository_temporary_credentials.yml
- plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/40_repository_ec2_credentials.yml
- plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/50_repository_ecs_credentials.yml
- plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/60_repository_eks_credentials.yml
* Defaulting repository-s3 region to empty string
Signed-off-by: Raghuvansh Raj <raghraaj@amazon.com>
* Added region us-west-2 for S3ThirdPartyTests
Signed-off-by: Raghuvansh Raj <raghraaj@amazon.com>
* Always specify a region.
* Fix: ./gradlew :plugins:repository-s3:yamlRestTest runs locally.
---------
Signed-off-by: Raghuvansh Raj <raghraaj@amazon.com>
Co-authored-by: Raghuvansh Raj <raghraaj@amazon.com>
(cherry picked from commit fb0f0e41b0e83d3703b9a6adcec0a56d434b587b) …
> [Backport] Remove default s3 region (#7989)

- CHANGELOG.md
- buildSrc/version.properties
Bump 'mockito' from 5.2.0 to 5.4.0
N/A
> Bump 'mockito' from 5.2.0 to 5.4.0

- server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
This PR backports PR's #8186 and #8235 to 2.x
Resolves #8162 
> [Backport 2.x] Backport PR's #8186 and #8235

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/indices/IndexTemplateMetadata.java
- client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexTemplatesResponseTests.java
- server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
- server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
- server/src/main/java/org/opensearch/action/admin/indices/resolve/ResolveIndexAction.java
- server/src/main/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverService.java
- server/src/main/java/org/opensearch/cluster/DiffableUtils.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
- server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
- server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
- server/src/main/java/org/opensearch/gateway/DanglingIndicesState.java
- server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
- server/src/main/java/org/opensearch/snapshots/EmptySnapshotsInfoService.java
- server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/main/java/org/opensearch/snapshots/SnapshotShardSizeInfo.java
- server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
- server/src/test/java/org/opensearch/cluster/metadata/IndexTemplateMetadataTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
- server/src/test/java/org/opensearch/cluster/serialization/DiffableTests.java
- server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
- test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/7b8796aa26cc864bf9731422eca5b166b779a1ef from #7306.
> [Backport 2.x] [Refactor] ImmutableOpenMap to j.u.Map in IndexMetadata (#7306)

- buildSrc/src/main/groovy/org/opensearch/gradle/CheckCompatibilityTask.groovy
Make 2.x as default branch for check compatibility task
https://github.com/opensearch-project/OpenSearch/commit/79bf7695d56a4993393f78f83c49d399c4b11b6a#r119490167
> Make 2.x as default branch for check compatibility task

- CHANGELOG.md
- buildSrc/version.properties
- qa/wildfly/build.gradle
- qa/wildfly/docker-compose.yml
- qa/wildfly/src/main/java/org/opensearch/wildfly/model/Employee.java
- qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelClientActivator.java
- qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelClientEmployeeResource.java
- qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelClientProducer.java
- qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelJacksonJsonProvider.java
- qa/wildfly/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
Backports 246b922fc1a15985254d38222fc6c62570f16cf3 from #8209
> [Backport 2.x] Bump resteasy-jackson2-provider from 3.0.26.Final to 6.2.4.Final in /qa/wildfly

- CHANGELOG.md
Part of https://github.com/opensearch-project/OpenSearch/pull/8318
> [1.3] Clear out changelog after release

- server/src/main/java/org/opensearch/index/IndexService.java
https://github.com/opensearch-project/OpenSearch/issues/8338
> Handle case where IndexShard is null due to failed creation of index

- rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
Update after https://github.com/opensearch-project/OpenSearch/pull/8333
N/A
> Update search.aggregation/370_multi_terms.yml after backport

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
- Backports fixes for #7751 to 2.x
Resolves #7751 
> [Backport 2.x] Fix primary balance flaky test

- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
- server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
- server/src/test/java/org/opensearch/common/blobstore/fs/FsBlobContainerTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/2c5a22d167460a0a5d2ad61f16914ca309efe427 from https://github.com/opensearch-project/OpenSearch/pull/8314
> [Backport 2.x] Add method in BlobContainer to fetch the keys in sorted order

- CHANGELOG.md
- plugins/telemetry-otel/build.gradle
- plugins/telemetry-otel/config/telemetry-otel/log4j2.properties
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelResourceProvider.java
Backport to 2.x 
Main PR - https://github.com/opensearch-project/OpenSearch/pull/8393
Main branch commit - 7a5c810a238e0566f0c7bdb6fbc774dafb3674b0
> Adds log4j configuration for telemetry-otel plugin (#8393)

- buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
- buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
- buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
Initial changes to ensure integration testing for extensions functions properly, following https://github.com/opensearch-project/OpenSearch/pull/8029
> [Extensions] Change extension integration testing to reflect new initialization sequence

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
Mute org.opensearch.remotestore.RemoteStoreRefreshListenerIT.testRemoteRefreshRetryOnFailure() integration test.
- https://github.com/opensearch-project/OpenSearch/issues/7703
> [Remote Store] Mute testRemoteRefreshRetryOnFailure test case

- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
- server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
- server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
- server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
- server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/pull/8350
> [Backport 2.x][Remote Store] Update Translog Metadata file name (#8350)

- buildSrc/build.gradle
- gradle/wrapper/gradle-wrapper.properties
Update Gradle to 8.2.1
https://github.com/gradle/gradle/releases/tag/v8.2.1
> Update Gradle to 8.2.1

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
- server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
- server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/TranslogManager.java
- server/src/test/java/org/opensearch/common/blobstore/fs/FsBlobContainerTests.java
- server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
- server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/5c0e3c94950796f7c99a20456528181ae9f16bbf from https://github.com/opensearch-project/OpenSearch/pull/8363
> [Backport 2.x] [Remote Segment Store] Make metadata file immutable (#8363)

- CHANGELOG.md
- modules/lang-painless/src/main/java/org/opensearch/painless/AnalyzerCaster.java
- modules/lang-painless/src/test/java/org/opensearch/painless/FactoryTests.java
* Created a failing test to reproduce painless bug
Signed-off-by: Shivansh Arora <shivansh.arora@protonmail.com>
* Removed unused import
Signed-off-by: Shivansh Arora <shivansh.arora@protonmail.com>
* Throw exception when trying to cast def to void
Signed-off-by: Shivansh Arora <shivansh.arora@protonmail.com>
* Removed update context change
Signed-off-by: Shivansh Arora <shivansh.arora@protonmail.com>
* Created a different test
Signed-off-by: Shivansh Arora <shivansh.arora@protonmail.com>
---------
Signed-off-by: Shivansh Arora <shivansh.arora@protonmail.com>
(cherry picked from commit a39f60f482c405a102e6eec83097e91acc90a889)
Backport of PR #8315 to 2.x branch
Resolves #6435  …
> [Backport 2.x] Fix painless casting bug causing opensearch to crash (#8315)

- server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
- server/src/main/java/org/opensearch/repositories/Repository.java
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
- server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Backports https://github.com/opensearch-project/OpenSearch/commit/a430e18e82f7671e01c37ae5a549fc36dd673b1a from https://github.com/opensearch-project/OpenSearch/pull/7497
> [Backport 2.x] Add Changes in Snapshot Delete Flow for remote store interoperability. (#7497)

- CHANGELOG.md
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/OTelTelemetryPlugin.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/OTelTelemetrySettings.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelResourceProvider.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/exporter/OTelSpanExporterFactory.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/exporter/package-info.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/OTelTelemetryPluginTests.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/exporter/DummySpanExporter.java
- plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/exporter/OTelSpanExporterFactoryTests.java
2.x Backport PR for #8624 
Resolves #8620
> Make Otel Span exporter configurable

- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
> [Backport 2.x] [Remote Store] Integrate S3 async upload with S3BlobContainer 

- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Backports https://github.com/opensearch-project/OpenSearch/commit/230a06daee9c8484e38d6aad867a98c3c10c2485 from https://github.com/opensearch-project/OpenSearch/pull/8487
> [Backport 2.x] Use files from segmentInfosSnapshot in upload (#8487)

- CHANGELOG.md
- README.md
- Fix version for `2.x` post version bump on `main`
- N/A
> Fix versions for 2.x on main

- server/src/main/java/org/opensearch/cluster/ClusterInfo.java
- Updates BwC version as the changes have been backported to `2.x`
- Original change: https://github.com/opensearch-project/OpenSearch/pull/8208
> Update BwC version for file cache safeguards

- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
The [commit to comment out `forceFailure()`][1] was done about 8 years ago so I don't think we'll be bringing it back. Also this makes the code base a slightly friendlier place :)
[1]: https://github.com/opensearch-project/OpenSearch/commit/e5a699fa05a6e4ffcb919e8a2a6da8f57e1c2ce8#diff-bfffcb86804c8bddf5c6c6d26c0212121f61baf3d7d3c86602f4af54f91a0963R659
> Remove empty if/try-finally in base integ test class

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.12.md
> [Backport 1.3] Add release notes for 1.3.12

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.12.md
> [Backport 1.x] Add release notes for 1.3.12

- release-notes/opensearch.release-notes-1.3.12.md
> Add release notes for 1.3.12

- .github/workflows/backport.yml
- In case of backport failure, the new version adds labels to the PR for better tracking
- Ref: https://github.com/opensearch-project/security/pull/3063/files
> Upgrade backport action to support failed labels

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java
- server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
Backport https://github.com/opensearch-project/OpenSearch/pull/9177
> [Backport] [2.x] Rethrow OpenSearch exception in concurrent search (#9177)

- CHANGELOG.md
> Fix location of zstd fix changelog entry

- .github/CODEOWNERS
- MAINTAINERS.md
Michael has graciously accepted our invitation to become a maintainer. Welcome, Michael!
> Add Michael Froh as a maintainer

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
- server/src/internalClusterTest/java/org/opensearch/search/sort/SimpleSortIT.java
- server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java
- server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
- server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java
Solves the sort related ITs
Resolves #8510 
> Fix the script sort related ITs

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
- server/src/internalClusterTest/java/org/opensearch/search/sort/SimpleSortIT.java
- server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java
- server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
- server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java
Backports https://github.com/opensearch-project/OpenSearch/pull/9466
> Backport Fix sort related ITs for concurrent search

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java
Backporting https://github.com/opensearch-project/OpenSearch/pull/9437 to 2.x branch.
> Fixing unblock condition for index create block

- CHANGELOG.md
Move the changelog entry to Unreleased 2.x section
> Move the changelog entry to correct section

- server/src/internalClusterTest/java/org/opensearch/search/pit/DeletePitMultiNodeIT.java
- Set the `deleted` flag between starting search threads and sending delete pit request
- Confirm all shard failures are caused by `SearchContextMissingException`, including partial failures
Resolves #9481 
> Fix test DeletePitMultiNodeIT.testDeleteWhileSearch

- server/src/main/java/org/opensearch/OpenSearchServerException.java
- server/src/main/java/org/opensearch/action/admin/cluster/repositories/put/PutRepositoryRequest.java
- server/src/main/java/org/opensearch/cluster/metadata/RepositoryMetadata.java
BWC compatibility fix for crypto settings in put repository request
> BWC fix for crypto settings in repository request and metadata

- server/src/main/java/org/opensearch/index/translog/TranslogStats.java
Update version check for Remote Translog Store upload flow stats in nodes stats API
#8311
> [Remote Store] Update version check for Remote Translog Store upload flow stats in nodes stats API

- server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Backport PR for https://github.com/opensearch-project/OpenSearch/pull/9746
> [Backport 2.x] Add logic to fetch previousClusterUUID (#9746)

- libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
Fixes flaky tests #9780
Resolves #9780 
> Fix default tracer flaky test

- CHANGELOG.md
- buildSrc/version.properties
Bump mockito and bytebuddy
N/A
> Bump mockito and bytebuddy

- distribution/tools/keystore-cli/build.gradle
- distribution/tools/plugin-cli/build.gradle
- distribution/tools/upgrade-cli/build.gradle
- plugins/ingest-attachment/build.gradle
- plugins/repository-azure/build.gradle
- plugins/repository-gcs/build.gradle
- plugins/repository-hdfs/build.gradle
- qa/evil-tests/build.gradle
Sync Guava version across all modules
N/A
> Sync Guava version across all modules

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.13.md
- Add release notes for 1.3.13
> [Backport 1.3] Add release notes for 1.3.13

- release-notes/opensearch.release-notes-1.3.13.md
- Adds release notes for 1.3.13
> Add release notes for 1.3.13

- CHANGELOG.md
- server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
- server/src/main/java/org/opensearch/extensions/rest/RestActionsRequestHandler.java
- server/src/main/java/org/opensearch/extensions/rest/RestInitializeExtensionAction.java
- server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
- server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
- server/src/test/java/org/opensearch/extensions/rest/RestInitializeExtensionActionTests.java
- server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/10256
> [Backport 2.x] Fix: register mulitple extensions. 

- CHANGELOG.md
- plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepository.java
- plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureRepositorySettingsTests.java
- plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageRepository.java
- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRepositoryRegistrationIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationWithRemoteStorePressureIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
- server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
- server/src/internalClusterTest/java/org/opensearch/snapshots/SystemRepositoryIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/repositories/put/TransportPutRepositoryAction.java
- server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
- server/src/main/java/org/opensearch/repositories/RepositoriesService.java
- server/src/main/java/org/opensearch/repositories/Repository.java
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
- server/src/main/java/org/opensearch/repositories/fs/FsRepository.java
- server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
- server/src/test/java/org/opensearch/repositories/fs/FsRepositoryTests.java
- test/framework/src/main/java/org/opensearch/test/TestCluster.java
#9839
---------
(cherry picked from commit 699d235a7edad81be19dabbb57e2933ad4f1b6d6)
> [Backport 2.x][Remote Store] Add support to restrict creation & deletion if system repository and mutation of immutable settings of system repository

- .github/pull_request_template.md
Follow-up PR for #10242
#10242
> Update TODO for updating public documentation

- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
- Came across an issue during testing where the blob metadata might be missing some attributes and never returns since the exception is never captured/contained.
- Adds a try/catch block to notify the listener of any failures
> Fix error handling for future completion

- modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/MoreExpressionIT.java
Mute the test only for the concurrent search enabled case. See #10079.
> Mute MoreExpressionIT.testSpecialValueVariable

- release-notes/opensearch.release-notes-2.11.0.md
Synced release notes with the original CHANGELOG.md on 2.11
> Add more commits from 2.11 changelog

- server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
To be merged after merging https://github.com/opensearch-project/OpenSearch/pull/10629
https://github.com/opensearch-project/OpenSearch/issues/10501
> [Remote Store] Update version check for remote store backpressure rejection stats

- CHANGELOG.md
> fix change log conflicts

- release-notes/opensearch.release-notes-2.11.0.md
- Adds in a missing entry for 2.11 release notes
> Add missing entry for 2.11 release notes

- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
Resolves #10735 https://github.com/opensearch-project/OpenSearch/issues/10735
> Muting s3 request stats test

- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Fix spotless failure in RemoteClusterStateServiceTests.
> Fix spotless failure

- .github/pull_request_template.md
- CONTRIBUTING.md
Backport ffe9371b38f98a2c9314bb6cfed4f8f224ff085c from #10751.
> [Backport] [1.3] Update Github pull request template to have a task for inspecting failing checks (#10751)

- server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
- server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
- server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
- server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
- server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
- server/src/main/java/org/opensearch/index/SegmentReplicationRejectionStats.java
- server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/main/java/org/opensearch/node/NodeService.java
- server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
- server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
- server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
- server/src/test/java/org/opensearch/index/SegmentReplicationStatsTrackerTests.java
- server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
- test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
- test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
This PR Backports #10656 
Resolves #10501 
> [Backport 2.x] [Segment Replication] Backport Adding Segment Replication Backpressure Rejection Stats to _nodes/stats

- server/src/main/java/org/opensearch/action/search/SearchRequest.java
- server/src/main/java/org/opensearch/action/search/SearchResponse.java
Change request latency phase_took version check from 3.0 to 2.12. Originally merged as 3.0 for backward compatibility test.
Merge in conjunction with 2.x backport https://github.com/opensearch-project/OpenSearch/pull/10797
> Update per request latency check to 2.12 on main

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
- server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
- server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
- server/src/main/java/org/opensearch/cluster/coordination/InMemoryPersistedState.java
- server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
- server/src/main/java/org/opensearch/cluster/service/ClusterStateStats.java
- server/src/main/java/org/opensearch/cluster/service/MasterService.java
- server/src/main/java/org/opensearch/discovery/DiscoveryStats.java
- server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
- server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
- server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
- server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
- server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
- server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
- test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
Backport https://github.com/opensearch-project/OpenSearch/commit/54e74a84437238c6154b0a15d209a9a1ecbaa4bb from https://github.com/opensearch-project/OpenSearch/pull/10670.
Resolves #10669
> [Backport 2.x] Add cluster state stats

- server/src/main/java/org/opensearch/action/search/SearchQueryCategorizer.java
Backporting from https://github.com/opensearch-project/OpenSearch/pull/10971
> [Backport 2.x] Change log level to trace for query shape

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
OpenJDK Update (October 2023 Patch releases)
Part of https://github.com/opensearch-project/OpenSearch/issues/10746
> OpenJDK Update (October 2023 Patch releases)

- CHANGELOG.md
Fix changelog entry from 3.0 to 2.x
> Fix changelog for multiterm perf PR

- .github/workflows/assemble.yml
- .github/workflows/precommit.yml
Add Java 11/17/21 matrix for precommit and assemble checks
N/A
> Add Java 11/17/21 matrix for precommit and assemble checks

- CHANGELOG.md
- modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
- qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/30_geoshape.yml
- qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/30_geoshape.yml
- qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/30_geoshape.yml
- server/src/main/java/org/opensearch/index/mapper/GeoShapeFieldMapper.java
Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.
Main branch PR: https://github.com/opensearch-project/OpenSearch/pull/11095
Resolves https://github.com/opensearch-project/OpenSearch/issues/10958
> [Backport-2.x] Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.

- server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationSuiteIT.java
Muting these tests until #9499 is resolved
#9499 
> Muting flaky tests in SegmentReplicationSuiteIT

- server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
- server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
- server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
- server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
- server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/11242 to `2.x`
> [Backport] [2.x] [BWC and API enforcement] Reduce the visibility of some existing APIs (#11242)

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.11.1.md
> Add 2.11.1 release notes

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.11.1.md
> [Backport 2.11] Add 2.11.1 release notes

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.11.1.md
> [Backport 2.x] Add 2.11.1 release notes (#11284)

- server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
- server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
- server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
- server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
- server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerSupport.java
- server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Followup on https://github.com/opensearch-project/OpenSearch/pull/11242
N/A
> Properly encapsulate SearchRequestOperationsListener related APIs as package protected (internal)

- server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
- server/src/main/java/org/opensearch/index/engine/EngineConfig.java
- server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
- server/src/main/java/org/opensearch/index/engine/InternalEngine.java
- server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
- server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
- server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
- server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
- server/src/main/java/org/opensearch/index/shard/IndexShard.java
- server/src/main/java/org/opensearch/index/shard/ReleasableRetryableRefreshListener.java
- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
- server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/LocalTranslog.java
- server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
- server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
- server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
- server/src/main/java/org/opensearch/index/translog/Translog.java
- server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
- server/src/main/java/org/opensearch/index/translog/TranslogManager.java
- server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
- server/src/test/java/org/opensearch/index/shard/ReleasableRetryableRefreshListenerTests.java
- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
- server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
- server/src/test/java/org/opensearch/index/translog/TestTranslog.java
Backport https://github.com/opensearch-project/OpenSearch/commit/ed1c8b7f53176d1669b8c9189c9c0835a9f17fab from https://github.com/opensearch-project/OpenSearch/pull/11330.
> [Backport 2.x] [Remote Store] Handoff refreshes, translog uploads during relocation from old to new primary (#11330)

- server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
This PR attempts to fix the `QueryProfilerTests.testBasic` with concurrent execution. The issue happened where a slice has `0` invocations for a breakdown type from its leading leaves. For example, a slice with three leaves: leaf A with a next_doc count of  `0`, leaf B with a next_doc count of  `0`, and leaf C with a next_doc count of  `4`. We should skip the slice start/end time computation for leaf A and leaf B since `0` does not represent an actual timing. Only when we've checked all leaves in a slice and still find no invocations, then we should set the slice start/end time to the default `0`.
Resolves #10941 …
> Fix query profiler test basic with concurrent execution

- CHANGELOG.md
- libs/core/src/main/java/org/opensearch/core/common/bytes/AbstractBytesReference.java
- libs/core/src/main/java/org/opensearch/core/common/bytes/BytesArray.java
- libs/core/src/main/java/org/opensearch/core/common/bytes/BytesReference.java
- libs/core/src/main/java/org/opensearch/core/common/io/stream/BytesStreamInput.java
- libs/core/src/main/java/org/opensearch/core/util/BytesRefUtils.java
- libs/core/src/test/java/org/opensearch/core/util/BytesRefUtilsTests.java
- server/src/main/java/org/opensearch/common/lucene/store/ByteArrayIndexInput.java
- server/src/main/java/org/opensearch/index/translog/BufferedChecksumStreamInput.java
This PR is a manual backport of https://github.com/opensearch-project/OpenSearch/pull/11362.
> [Backport 2.x] Interpret byte array as primitive using VarHandles (#11362)

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/bulk/BulkPrimaryExecutionContext.java
- server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
> [Backport] [2.x] Fix for stuck update action in a bulk with retry_on_conflict property (#11153)

- CHANGELOG.md
- test/fixtures/hdfs-fixture/build.gradle
Jetty version bump
Resolves https://nvd.nist.gov/vuln/detail/CVE-2023-44487
> Bump jetty version in hdfs-fixture to 9.4.53.v20231009

- buildSrc/build.gradle
Signed-off-by: Marc Handalian <marc.handalian@gmail.com>
(cherry picked from commit a2f792d4f6c5ecf485a15ba5e7791d4b66c8149e)
Manual backport of #11565
N/A
> [Backport 2.x] Bump grgit-core ffrom 5.2.0 to 5.2.1 (#11565)

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.14.md
Add release notes for 1.3.14 up to commit 21940d8239b50285ef7f98a1762ef281a5b1c7ee
> Add release notes for 1.3.14

- release-notes/opensearch.release-notes-1.3.14.md
Fix date on 1.3.14 release notes
> Fix date on 1.3.14 release notes

- release-notes/opensearch.release-notes-1.3.14.md
> Add release notes for 1.3.14 (#11592)

- rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
> Update skip version to match branches

- distribution/archives/integ-test-zip/src/test/java/org/opensearch/test/rest/JsonLogsFormatAndParseIT.java
- plugins/discovery-azure-classic/src/internalClusterTest/java/org/opensearch/discovery/azure/classic/AzureDiscoveryClusterFormationTests.java
- plugins/discovery-azure-classic/src/main/java/org/opensearch/cloud/azure/classic/management/AzureComputeServiceImpl.java
- plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2NetworkTests.java
- plugins/discovery-gce/src/main/java/org/opensearch/cloud/gce/util/Access.java
- plugins/ingest-attachment/src/main/java/org/opensearch/ingest/attachment/TikaImpl.java
- plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
- plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageRetryingInputStream.java
- plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsPlugin.java
- plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsRepository.java
- plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsSecurityContext.java
- plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HaHdfsFailoverTestSuiteIT.java
- plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsBlobStoreContainerTests.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/OTelTelemetrySettings.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetry.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/exporter/OTelMetricsExporterFactory.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelResourceProvider.java
- plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/exporter/OTelSpanExporterFactory.java
- qa/evil-tests/src/test/java/org/opensearch/bootstrap/OpenSearchPolicyUnitTests.java
- qa/evil-tests/src/test/java/org/opensearch/bootstrap/SystemCallFilterTests.java
- qa/evil-tests/src/test/java/org/opensearch/plugins/PluginSecurityTests.java
- qa/logging-config/src/test/java/org/opensearch/qa/custom_logging/CustomLoggingConfigIT.java
- qa/unconfigured-node-name/src/test/java/org/opensearch/unconfigured_node_name/JsonLogsFormatAndParseIT.java
Add @SuppressWarnings("removal") to not fail the build with -Werror for some JDKs (more classes)
N/A
> Add @SuppressWarnings("removal") to not fail the build with -Werror for some JDKs (more classes)

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
OpenJDK Update (January 2024 Patch releases), update to JDK `11.0.22+7`
Part of https://github.com/opensearch-project/OpenSearch/issues/11906
> OpenJDK Update (January 2024 Patch releases)

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
OpenJDK Update (January 2024 Patch releases) (#11998)
Part of https://github.com/opensearch-project/OpenSearch/issues/11906
> OpenJDK Update (January 2024 Patch releases) (#11998)

- buildSrc/version.properties
> Update Mockito to 5.10.0

- libs/core/src/main/java/org/opensearch/Version.java
Forward port of https://github.com/opensearch-project/OpenSearch/pull/12069
N/A
> Update Apache Lucene version for 2.12.0 release

- plugins/telemetry-otel/build.gradle
The telemetry-otel should not publish any client JARs (since it does not expose client facing APIs)
N/A
> The telemetry-otel should not publish any client JARs (since it does not expose client facing APIs)

- gradle/wrapper/gradle-wrapper.properties
Update to Gradle 8.6 (https://github.com/gradle/gradle/releases/tag/v8.6.0)
N/A
> Update to Gradle 8.6

- CHANGELOG.md
- test/fixtures/hdfs-fixture/build.gradle
- Fixes https://nvd.nist.gov/vuln/detail/CVE-2023-39410 and other pending backports for hadoop transitive dependencies
Resolves CVE-2023-39410
> [Backport 2.x] Fix CVE 2023 39410

- server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
- Fixes BwC versioning introduced with #12111 
Resolves build failures
> Fix BwC for admission control

- CHANGELOG.md
- server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
- server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
- server/src/test/java/org/opensearch/telemetry/tracing/SpanBuilderTests.java
* bug fix to have RestActions rawPath as operation names, query params as tags and avoid using exact URI (#10791)
---------
Signed-off-by: Atharva Sharma <athrv@amazon.com>
Signed-off-by: Atharva Sharma <60044988+atharvasharma61@users.noreply.github.com>
Co-authored-by: Atharva Sharma <athrv@amazon.com>
(cherry picked from commit c0fca74709e96ec7c8cf295cdca6110946b592b8)
Backport PR #12005 
> Backport/backport 12005 to 2.x

- rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries.yml
Fix 350_matched_queries.yml tests while awaiting for backport
Awaiting backport of https://github.com/opensearch-project/OpenSearch/pull/11626
> Fix 350_matched_queries.yml tests while awaiting for backport

- .github/ISSUE_TEMPLATE/meta.yml
Similar to feature requests and bugs, this dropdown will ensure that every meta issue gets assigned to a component.
> Add 'Related component' dropdown to meta template

- release-notes/opensearch.release-notes-2.12.0.md
- server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/CompositeAggIT.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/12375
https://github.com/opensearch-project/OpenSearch/issues/12331
~- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
~- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~ …
> Disable concurrent search path for composite aggregations.

- .github/workflows/check-compatibility.yml
- .github/workflows/gradle-check.yml
- .github/workflows/poc-checklist.yml
- CHANGELOG.md
Backport of https://github.com/opensearch-project/OpenSearch/pull/12462 to `2.x`
> [Backport] [2.x] Bump peter-evans/create-or-update-comment from 3 to 4 (#12462)

- CHANGELOG.md
- test/fixtures/hdfs-fixture/build.gradle
(cherry picked from commit 2ce15a53e2fcc6becf1f854cf531e09c088c9a35)
* Fixes https://github.com/advisories/GHSA-337f-xr2x-6fcf by bumping up org.apache.kerby:kerb-admin
> Fix CVE-2023-25613 (#12194)

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.15.md
Release notes for v1.3.15
Also cleans up the changelog
N/A
> [Backport 1.3] Release notes for 1.3.15

- release-notes/opensearch.release-notes-1.3.15.md
Cleans up release notes for v1.3.15
N/A
> Clean up release notes for 1.3.15

- CHANGELOG.md
- plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiCompletionAnalyzerProvider.java
- plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiCompletionFilterFactory.java
- plugins/analysis-kuromoji/src/main/java/org/opensearch/plugin/analysis/kuromoji/AnalysisKuromojiPlugin.java
- plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/AnalysisKuromojiFactoryTests.java
- plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
- plugins/analysis-kuromoji/src/test/resources/org/opensearch/index/analysis/kuromoji_analysis.json
- plugins/analysis-kuromoji/src/yamlRestTest/resources/rest-api-spec/test/analysis_kuromoji/10_basic.yml
Add kuromoji_completion analyzer and filter.
Resolves #4835 
> Add kuromoji_completion analyzer and filter (#4835)

- server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
- server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
- server/src/main/java/org/opensearch/indices/IndicesModule.java
- server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
- server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
- server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataHelper.java
- server/src/test/java/org/opensearch/gateway/ReplicaShardAllocatorTests.java
- server/src/test/java/org/opensearch/index/store/StoreTests.java
(backport 12115d1a from #8356 )
> Add batch async shard fetch transport action for replica #8218 (#8356)

- release-notes/opensearch.release-notes-2.13.0.md
- A changelog entry was added to 2.13 after the release notes PR was raised. 
- This PR adds that missing change log entry to release notes
NA
- ~[ ] All tests pass~ …
> add missing changelog entry to 2.13 release nodes

- test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
> chore: remove repetitive words

- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
- server/src/internalClusterTest/java/org/opensearch/remotemigration/ResizeIndexMigrationTestCase.java
- server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
- server/src/main/java/org/opensearch/snapshots/RestoreService.java
- server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
- server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
(cherry picked from commit c168e1c9216ba914fcd5c310ffb070df8ef5e6b5)
Backport #12748 to 2.x
> [Backport 2.x] Update index settings during remote store migration (#12748)

- buildSrc/version.properties
- libs/core/src/main/java/org/opensearch/Version.java
> Bump 2.x to 2.15.0

- server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
Quick follow up for #13480 
Resolves #13480 
> Update TermsQueryBuilderTests to include TermQuery

- .github/workflows/backport.yml
Backport https://github.com/opensearch-project/OpenSearch/commit/a10f2ecee4d2488ffafac15777199f260a969147 from https://github.com/opensearch-project/OpenSearch/pull/13800.
> [Backport 1.3] Add backport workflow to 1.x

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.17.md
> Add release notes for 1.3.17

- server/build.gradle
Upgrade the japicmp plugin to latest version as requested in https://github.com/melix/japicmp-gradle-plugin/issues/72
> Bump japicmp plugin version

- .github/pull_request_template.md
Backports ac78f0a4dc39f5b4be32adc8bf54999b2b44cd14 from #13979 to `2.x`
> [Backport 2.x] Shorten PR template checklist (#13979)

- server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
- server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Make remote seeding a low priority upload
> [Remote Migration] Make remote seeding a low priority upload

- CHANGELOG.md
- client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
- modules/opensearch-dashboards/src/main/java/org/opensearch/dashboards/OpenSearchDashboardsPlugin.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpChunk.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpRequest.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingHttpChannel.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingRequestConsumer.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingResponseProducer.java
- plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/StreamingHttpContentSender.java
- plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorHttpClient.java
- plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportStreamingTests.java
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/main/java/org/opensearch/common/xcontent/support/XContentHttpChunk.java
- server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
- server/src/main/java/org/opensearch/http/DefaultRestChannel.java
- server/src/main/java/org/opensearch/http/DefaultStreamingRestChannel.java
- server/src/main/java/org/opensearch/http/HttpChunk.java
- server/src/main/java/org/opensearch/http/HttpServerTransport.java
- server/src/main/java/org/opensearch/http/HttpTracer.java
- server/src/main/java/org/opensearch/http/StreamingHttpChannel.java
- server/src/main/java/org/opensearch/rest/BaseRestHandler.java
- server/src/main/java/org/opensearch/rest/RestController.java
- server/src/main/java/org/opensearch/rest/RestHandler.java
- server/src/main/java/org/opensearch/rest/StreamingRestChannel.java
- server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
- server/src/test/java/org/opensearch/rest/action/document/RestBulkStreamingActionTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/13772 to `2.x`
> [Backport] [2.x] [Streaming Indexing] Enhance RestAction with request / response streaming support (#13772)

- CHANGELOG-3.0.md
- CHANGELOG.md
Fix CHANGELOG.md entry
Follow up on https://github.com/opensearch-project/OpenSearch/pull/14146
> Fix CHANGELOG.md entry

- libs/core/src/main/java/org/opensearch/Version.java
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/14074 to `main`
> [Forwardport] Update to Apache Lucene 9.11.0 (#14074)

- server/src/main/java/org/opensearch/index/query/SourceFieldMatchQuery.java
- server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
backport https://github.com/opensearch-project/OpenSearch/pull/14154
Resolves https://github.com/opensearch-project/OpenSearch/issues/14156
> [2.15] Backport 14154

- release-notes/opensearch.release-notes-2.15.0.md
Add the match_only_text rewrite fix to release notes
Resolves https://github.com/opensearch-project/OpenSearch/issues/14156 …
> Add the match_only_text rewrite fix to release notes main

- release-notes/opensearch.release-notes-2.15.0.md
Add the match_only_text rewrite fix to release notes
Resolves https://github.com/opensearch-project/OpenSearch/issues/14156 …
> Add the match_only_text rewrite fix to release notes 2.x

- .github/CODEOWNERS
- MAINTAINERS.md
Updates @dreamer-89 maintership status.
Related https://github.com/opensearch-project/OpenSearch/issues/12970
~- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
~- [ ] Commit changes are listed out in CHANGELOG.md file (See: …
> Update @dreamer-89 maintainership status

- TESTING.md
These are a few cases I have seen that have resulted in flaky tests. I would love to see more details added here so that this can be used as a sort of checklist when writing, reviewing, or trying to fix tests.
> Add more details to testing bad practices

- .github/CODEOWNERS
Adds @ashking94 to codeowners
None
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBU …
> Add Ashish Singh to codeowners

- server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
- server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
Add unit tests for read and write flow of RemoteIndexMetadataManager
> Add UTs for RemoteIndexMetadataManager

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.18.md
Add release notes for release 1.3.18
Part of https://github.com/opensearch-project/opensearch-build/issues/4763
> Add release notes for release 1.3.18

- rest-api-spec/src/main/resources/rest-api-spec/test/index/110_strict_allow_templates.yml
- rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_mapping/all_path_options.yml
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/14737 to `main`
> [Forwardport] Add `strict_allow_templates` dynamic mapping option (#14555) (#14737)

- server/src/test/java/org/opensearch/cluster/applicationtemplates/ClusterStateSystemTemplateLoaderTests.java
Resolves https://github.com/opensearch-project/OpenSearch/issues/14786
> [ClusterStateSystemTemplateLoaderTests] Fix flaky test due to node being used across all tests

- .github/CODEOWNERS
- MAINTAINERS.md
Following the nomination and agreement from the maintainers, adding Gao Binlong (@gaobinlong) as a co-maintainer, who kindly accepted the invitation.
Gao is a long time contributor to the repository as well as a very active community member:
- he has authored over 70 pull requests (https://github.com/opensearch-project/OpenSearch/pulls/gaobinlong) related to search / indexing / ingestion / ...
- he is one of the most active contributors to OpenSearch forum  (https://forum.opensearch.org/u/gaobinlong/summary)
- he is more and more engaged in the pull request reviews with high quality feedback (https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+reviewed-by%3Agaobinlong+) 
- moreover, his contributions go beyond just OpenSearch Core (to note a few, …
> Add Gao Binlong as maintainer

- .github/workflows/benchmark-pull-request.yml
Fix env variable name typo in benchmark workflow.  …
> Fix env variable name typo in benchmark workflow. 

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
- server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
- server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
- server/src/test/java/org/opensearch/cluster/coordination/PersistedStateStatsTests.java
- test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Add integration tests for Remote Routing Table.
Resolves https://github.com/opensearch-project/OpenSearch/issues/14648
To ensure test reliability and stability, each test was executed 100 times to confirm that there were no intermittent or flaky failures.
> [Remote Routing Table] Add integration tests for Remote Routing Table

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/ActionModule.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponse.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/RestWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequest.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringValidationResult.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringAction.java
- server/src/main/java/org/opensearch/action/admin/indices/tiering/package-info.java
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/indices/tiering/TieringRequestValidator.java
- server/src/main/java/org/opensearch/indices/tiering/package-info.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponseTests.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequestTests.java
- server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java
- server/src/test/java/org/opensearch/indices/tiering/TieringRequestValidatorTests.java
> Add rest, transport layer changes for Hot to warm tiering - dedicated setup 

- CHANGELOG.md
Add changelog for remote state multi part upload fix (#14888)
NA
> Add changelog for remote state multi part upload fix

- release-notes/opensearch.release-notes-2.16.0.md
Update release notes for the backport PR: https://github.com/opensearch-project/OpenSearch/pull/14968
<del>- [ ] Functionality includes testing.</del>
<del>- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.</del>
<del>- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.</del>
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certif …
> Update release notes for 2.16

- CHANGELOG.md
- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
OpenJDK Update (July 2024 Patch releases)
Part of https://github.com/opensearch-project/OpenSearch/issues/14794
> OpenJDK Update (July 2024 Patch releases)

- .github/CODEOWNERS
Backport https://github.com/opensearch-project/OpenSearch/pull/15137
> [Backport 2.x] CODEOWNERS personalizations for jed326 (#15137)

- .github/CODEOWNERS
Backport https://github.com/opensearch-project/OpenSearch/pull/15137
> [Backport 1.x] CODEOWNERS personalizations for jed326 (#15137)

- .github/CODEOWNERS
Backport https://github.com/opensearch-project/OpenSearch/pull/15137
> [Backport 1.3] CODEOWNERS personalizations for jed326 (#15137)

- .github/workflows/benchmark-pull-request.yml
Fix missing curly brace in benchmark workflow file
> fix missing curly brace in benchmark workflow file

- rest-api-spec/src/main/resources/rest-api-spec/test/index/120_field_name.yml
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/15188 to `main`
N/A
> [Forwardport] Update 120_field_name.yml

- server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
Adds a log line when download completes 
> Add log when download completes with its size

- server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
- server/src/main/java/org/opensearch/indices/TermsLookup.java
Support Filtering on Large List encoded by Bitmap (version update)
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/15314 
> [Forwardport] Support Filtering on Large List encoded by Bitmap (version update)

- CHANGELOG.md
- server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
- server/src/main/java/org/opensearch/index/IndexSettings.java
- server/src/main/java/org/opensearch/search/DefaultSearchContext.java
- server/src/test/java/org/opensearch/search/SearchServiceTests.java
Signed-off-by: Ganesh Ramadurai <gramadur@amazon.com>
(cherry picked from commit b6b04039ab9b05de4da50863503b68f6be74e424)
Backport to 2.x of https://github.com/opensearch-project/OpenSearch/pull/15336
> [Backport 2.x] Add support for index level slice count setting (#15336)

- CHANGELOG.md
- release-notes/opensearch.release-notes-1.3.19.md
Add release notes for 1.3.19
Part of https://github.com/opensearch-project/opensearch-build/issues/4888
~~- [ ] Functionality includes testing.~~
> Add release notes for 1.3.19

- test/framework/src/main/java/org/opensearch/transport/nio/MockNioTransport.java
Compare numbers with equals() instead of ==
> Compare numbers with equals() instead of ==

- release-notes/opensearch.release-notes-1.3.19.md
Add release notes for release 1.3.19
Part of https://github.com/opensearch-project/opensearch-build/issues/4888
~~- [ ] Functionality includes testing.~~
> Add release notes for release 1.3.19

- server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Flaky test
Resolves https://github.com/opensearch-project/OpenSearch/issues/15600
> Adding awaitsFix to approximateRangeTest flaky tests

- server/src/main/java/org/opensearch/OpenSearchServerException.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
Change version to `V_2_17_0` in changes from #15409
> Change version to V_2_17_0 in changes from #15409

- client/rest-high-level/src/test/java/org/opensearch/client/SnapshotRequestConvertersTests.java
- qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
Fix breaking changes of #15409
Resolves #15463
> Fix breaking changes of #15409

- server/src/main/java/org/opensearch/OpenSearchServerException.java
- server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
(cherry picked from commit 0f53bf9762f758505a814543ac93c5aaa7bf8e74)
Backport #15596 to `2.x`
> [Backport 2.x] Change version to V_2_17_0 (#15596)

- server/src/main/java/org/opensearch/repositories/IndexId.java
- server/src/main/java/org/opensearch/repositories/RepositoryData.java
- server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
- server/src/test/java/org/opensearch/repositories/IndexIdTests.java
Set Version to 2.17 for hashed prefix snapshots
Related to https://github.com/opensearch-project/OpenSearch/pull/15426
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-o …
> Set Version to 2.17 for hashed prefix snapshots

- server/src/main/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponse.java
- server/src/test/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponseTests.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/14717
> [2.17] Backporting of IndicesSegmentsResponse optimisation

- CHANGELOG.md
- server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationIT.java
- server/src/main/java/org/opensearch/index/IndexModule.java
- server/src/main/java/org/opensearch/index/IndexService.java
- server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
- server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
- server/src/main/java/org/opensearch/node/Node.java
- server/src/test/java/org/opensearch/index/IndexModuleTests.java
- server/src/test/java/org/opensearch/index/IndexServiceTests.java
- server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
manual backport of https://github.com/opensearch-project/OpenSearch/pull/15627 to 2.17
> [Backport 2.17] [RW Separation] Add polling segment replication for search replicas (#15627) 

- CHANGELOG.md
- server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
- server/src/main/java/org/opensearch/threadpool/ThreadPool.java
- server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/3fc0139ca68a1ff843ec1492c3cd52c2c4c67f02 from https://github.com/opensearch-project/OpenSearch/pull/15568
> [Backport 2.17] Optimise snapshot deletion to speed up snapshot deletion and creation(#15568)

- .github/workflows/assemble.yml
Fix MacOS assemble workflows
See please https://opensearch.slack.com/archives/C0561HRK961/p1725526478827459
> Fix MacOS assemble workflows

- release-notes/opensearch.release-notes-2.17.0.md
Since https://github.com/opensearch-project/OpenSearch/pull/15751 is pending merge to 2.17, will add a new item to release notes
> Adding release notes for new setting

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.17.0.md
Release notes for https://github.com/opensearch-project/OpenSearch/pull/15765
> Add release notes for WithFieldName interface

- CHANGELOG.md
Removes entry that have been put into 2.17
> Remove un-necessary changelog entry

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.17.0.md
Entries added to CHANGELOG.md that were backported to 2.17 branch and are included in upcoming 2.17 release
> Updating release-notes for 2.17

- CHANGELOG.md
The change is already present in [2.17 release notes](https://github.com/opensearch-project/OpenSearch/blob/2.17/release-notes/opensearch.release-notes-2.17.0.md?plain=1#L54). Hence, removing it from the main branch. It was not added to 2.x branch
> Fixing the CHANGELOG.md by removing change published in 2.17

- TESTING.md
["Building with extra plugins"](
https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#building-with-extra-plugins
) section of TESTING.md is stale. Updating docs to reflect plugin documentation.
#15847
> Update TESTING.md 'Building with extra plugins' documentation

- README.md
Update instance of 2.17.0 in the README to 2.18.0 now that 2.x is pointing to 2.18
> Update version in README to 2.18.0

- .github/workflows/delete_backport_branch.yml
Manual backport of https://github.com/opensearch-project/OpenSearch/pull/15983 https://github.com/opensearch-project/OpenSearch/pull/16003
> [Backport 2.x] Refactor branch deletion workflow for backports

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.17.1.md
Add 2.17.1 release notes
Part of https://github.com/opensearch-project/opensearch-build/issues/5046
> Add 2.17.1 release notes

- modules/ingest-geoip/src/test/java/org/opensearch/ingest/geoip/IngestGeoIpModulePluginTests.java
- modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/IngestUserAgentModulePlugin.java
- modules/ingest-user-agent/src/test/java/org/opensearch/ingest/useragent/IngestUserAgentModulePluginTests.java
Follow up of PR: https://github.com/opensearch-project/OpenSearch/pull/15325
I missed registering the setting with OpenSearch.
- [] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
> Registering disable user-agent setting with OpenSearch

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.17.1.md
Forward port of https://github.com/opensearch-project/OpenSearch/pull/16040 to `2.x`
> [Forwardport] [2.x] Add 2.17.1 release notes (#16104)

- .github/workflows/assemble.yml
> [Backport] [1.x] Fixing MacOS 13 assemble workflows (once again) (#15898) (#15899) 

- libs/core/src/main/java/org/opensearch/Version.java
Update Apache Lucene version for 2.18.0
Follow up on https://github.com/opensearch-project/OpenSearch/pull/16211
> Update Apache Lucene version for 2.18.0

- CHANGELOG.md
- plugins/workload-management/build.gradle
- plugins/workload-management/src/javaRestTest/java/org/opensearch/rest/WorkloadManagementRestIT.java
Backport https://github.com/opensearch-project/OpenSearch/pull/15955
> Backport 2.x: Add Integration Tests for Workload Management CRUD APIs (#15955)

- CHANGELOG.md
- server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
2.x backport https://github.com/opensearch-project/OpenSearch/pull/16290
> Enable coordinator search.request_stats_enabled by default (#16290)

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
- server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
- server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
backport a53e0c63aa9c6a85fed30e7bdce8b533aa471060 from #16215
> [Backport 2.x] Update last seen cluster state in commit phase (#16215)

- rest-api-spec/src/main/resources/rest-api-spec/test/indices.create/10_basic.yml
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/16343 to `main`
> [Forwardport] [main] Update 10_basic.yml

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- buildSrc/version.properties
Update JDK to 21.0.5
Part of https://github.com/opensearch-project/OpenSearch/issues/16354
> Update JDK to 21.0.5

- CHANGELOG.md
- server/src/main/java/org/opensearch/cluster/service/MasterService.java
- server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java
- server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
2.x Backport PR of https://github.com/opensearch-project/OpenSearch/pull/16421
> [2.x] Add logic in master service to optimize performance and retain detailed logging for critical cluster operations. (#16421)

- .github/workflows/detect-breaking-change.yml
Update Gradle version for Detect Breaking Changes Github action
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/16684
> Update Gradle version for Detect Breaking Changes Github action

- server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java
- server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
- server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
- server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Backport https://github.com/opensearch-project/OpenSearch/commit/72559bf60c84a59908a0685db01d2ed5b1419111 from https://github.com/opensearch-project/OpenSearch/pull/16383.
* create publication repos during join task
> [Backport 2.x] - create publication repos during join task execution (#16383)

- release-notes/opensearch.release-notes-1.3.20.md
Added release notes for 1.3.20
Part of https://github.com/opensearch-project/opensearch-build/issues/4990
~~- [ ] Functionality includes testing.~~
> Added release notes for 1.3.20

- .github/benchmark-configs.json
Add benchmark confirm for lucene-10 big5 index snapshot …
> Add benchmark config for lucene-10 big5 index snapshot

- plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java
this way we ensure that it doesn't include any additional tokens which we don't want.
this is a follow-up to commit 4d943993ac9 / #16993.
n/a
> improve `PhoneNumberAnalyzerTests#testTelPrefixSearch`

- rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/20_slice.yml
- server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequest.java
Forwardport of https://github.com/opensearch-project/OpenSearch/pull/17025 to `main`
> [Forwardport] [main] Fix versions and breaking API changes

- plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
- plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
This PR improves exception handling in the S3BlobContainer's synchronous delete operations by properly handling InterruptedException and ExecutionException. The changes ensure that interrupted status is preserved and exceptions are properly propagated with their original cause.
- Added a helper method `getFutureValue()` to centralize future completion handling
- Modified `delete()` and `deleteBlobsIgnoringIfNotExists()` methods to use the new helper method
- Added proper exception handling for:
- InterruptedException: Preserves thread interrupted status and wraps in IllegalStateException
- ExecutionException: Unwraps and preserves original cause while maintaining exception hierarchy
- Other exceptions: Wrapped in RuntimeException
Added new test cases to verify exception handling:
- …
> Improve exception handling in S3BlobContainer synchronous operations

- .github/workflows/publish-maven-snapshots.yml
- buildSrc/version.properties
Switch alpha to alpha1 and update publish maven to support qualifier and meet requirements
https://github.com/opensearch-project/opensearch-build/issues/3747
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/ma …
> Switch alpha to alpha1 and update publish maven to support qualifier and meet requirements

- MAINTAINERS.md
> Fix Binlong's name in MAINTAINERS.md

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- gradle/libs.versions.toml
- server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Update bundled JDK to `21.0.6+7`
Part of https://github.com/opensearch-project/OpenSearch/issues/17089
> OpenJDK Update (January 2025 Patch releases)

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.19.1.md
> [2.19] Add 2.19.1 release notes

- .github/CODEOWNERS
- MAINTAINERS.md
Following the [nomination process][1], I have nominated and other maintainers have agreed to add Pan Guixin (@bugmakerrrrrr) as a co-Maintainer of the OpenSearch repository. Pan Guixin has kindly accepted the invitation.
---
Pan has been an active contributor to OpenSearch since 2023, adding features, enhancing performance, and fixing bugs in a variety of different areas. For example, Pan created a [detailed issue](https://github.com/opensearch-project/OpenSearch/issues/16061) describing a number of problems with the flat_object type. He did a deep dive into the implementation and proposed multiple improvements backed by data to justify the improvements. He then led the implementation with the help of another contributor. He also actively reviews other contributors’ code, and has …
> Add @bugmakerrrrrr as maintainerrrrrr

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
Resolve typo in 2.x jdk version 21
Resolve type introduced in this PR:
* https://github.com/opensearch-project/OpenSearch/pull/17141
Thanks.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.m …
> Resolve typo in 2.x jdk version 21

- DEVELOPER_GUIDE.md
Fixes a small typo I found while reading the DEVELOPER_GUIDE.md. 
> Small typo found while reading DEVELOPER_GUIDE.md

- .github/workflows/benchmark-pull-request.yml
- .github/workflows/publish-maven-snapshots.yml
Update beta1 qualifier for 3.0.0 version
https://github.com/opensearch-project/opensearch-build/issues/3747
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …
> Update beta1 qualifier for 3.0.0 version

- .github/workflows/dependabot_pr.yml
> Update dependabot changelog helper for 3.x major version

- CHANGELOG.md
@beanuwave @cwperks I noticed this right after I merged the previous PR.
> Fix label in changelog entry

- .github/workflows/benchmark-pull-request.yml
Add credentials to retrieve jenkins data as we plan to switch from anonymous read-only access to authenticated users. Starting with this workflow before moving to gradle check. Associated PR that has script changes: https://github.com/opensearch-project/opensearch-build/pull/5423
> Authenticate jenkins calls for benchmark workflow

- libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java
- libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerChainExtractor.java
Minor optimization to avoid creating a collection when iteration is the only thing needed.
@reta Let me know what you think. Seems like a nice optimization assuming we never need to do anything other than iterate over the results.
> Skip list creation on stack walker

- .github/CODEOWNERS
- MAINTAINERS.md
Unfortunately I don't have the bandwidth to monitor OpenSearch core anymore.
> Remove dblock@ from core maintainers.

- server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
> Fix feature flag error in SearchServiceStarTreeTests

- libs/agent-sm/agent/build.gradle
Fix :libs:agent-sm:agent publication
Closes https://github.com/opensearch-project/OpenSearch/issues/16288
> Fix :libs:agent-sm:agent publication

- server/src/main/resources/org/opensearch/bootstrap/security.policy
- server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
Fix security policy for Windows based builds and deployments
See please https://github.com/opensearch-project/custom-codecs/pull/235
> Fix security policy for Windows based builds and deployments

- modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy
- plugins/transport-reactor-netty4/src/main/plugin-metadata/plugin-security.policy
Fix security policy for Windows based builds and deployments for transport plugins
See please https://github.com/opensearch-project/custom-codecs/actions/runs/14380426679/job/40339261780?pr=235
> Fix security policy for Windows based builds and deployments for transport plugins

- server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
- server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
Pass the maxPoll, timeout from config to poller function call
> [Pull-based Ingesiton] Pass the maxPoll, timeout from config to poller

- MAINTAINERS.md
Technically, I start at Uber next week, but it seems silly to mark myself as "Independent" for a week.
N/A
> Update my affiliation

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- gradle/libs.versions.toml
Update bundled JDK to 21.0.7+6 (April 2025 Patch releases)
Part of https://github.com/opensearch-project/OpenSearch/issues/18009
> Update bundled JDK to 21.0.7+6 (April 2025 Patch releases)

- server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
Related to #18108 and https://github.com/opensearch-project/OpenSearch/issues/15842#issuecomment-2836112699
> Mute RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop

- CHANGELOG.md
- release-notes/opensearch.release-notes-2.19.2.md
> Add release notes for 2.19.2

- release-notes/opensearch.release-notes-3.0.0.md
> Fix release notes title

- release-notes/opensearch.release-notes-3.0.0.md
Updated 3.0 release note related to #17682
- NA
> Updated 3.0 release note related to #17682

- server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
> Fix flaky RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop

- plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Backport of https://github.com/opensearch-project/OpenSearch/pull/18193 to `3.0`
> [Backport] [3.0] Fixing Flaky ReactorNetty4StreamingStressIT test case (another attempt) (#18193)

- distribution/tools/plugin-cli/build.gradle
- distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/PluginSecurity.java
- gradle/code-coverage.gradle
- libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java
- libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/FileInterceptorIntegTests.java
- qa/evil-tests/src/test/java/org/opensearch/tools/cli/plugin/PluginSecurityTests.java
- server/src/main/java/org/opensearch/monitor/os/OsProbe.java
- server/src/main/resources/org/opensearch/bootstrap/security.policy
- server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
- server/src/main/resources/org/opensearch/bootstrap/test.policy
- test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
- test/framework/src/main/java/org/opensearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java
Prepare the codebase for running on JDK-24+. The changes are largely coming from https://github.com/opensearch-project/OpenSearch/pull/18085/ except HDFS and bundled JDK updates.
Closes https://github.com/opensearch-project/OpenSearch/issues/17661
> Prepare the codebase for running on JDK-24+

- MAINTAINERS.md
Following the [nomination process][1], I have nominated and other maintainers have agreed to add Rishabh Maurya (@rishabhmaurya) as a co-maintainer of the OpenSearch repository. Rishabh has kindly accepted the invitation.
[1]: https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer
https://github.com/opensearch-project/.github/issues/336
Rishabh has authored [40 issues](https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aissue%20state%3Aopen%20author%3Arishabhmaurya) including 5 RFCs, merged [41 PRs](https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+author%3Arishabhmaurya+is%3Aclosed+) and provided review on [60 PRs](https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+commenter%3Arishabhmaurya+).
Rishabh is …
> Add @rishabhmaurya as a maintainer

- CODE_OF_CONDUCT.md
- README.md
This change updates the code of conduct link - https://opensearch.org/code-of-conduct/ and correct mailing information as mentioned in the project website's [COC](https://opensearch.org/code-of-conduct) after the project's transfer from AWS to LF.
> Code of Conduct - update AWS to LF links/contact

- server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
- server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Validate Search Phase Request Processors in the search pipeline
> Validate Search Phase Request Processors in Search Pipeline

- server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
- server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Follow up of https://github.com/opensearch-project/OpenSearch/pull/18363
Failed build on neural search side: https://github.com/opensearch-project/neural-search/actions/runs/15329740172/job/43133281587?pr=1360
> Add Search Phase Result Processors to SearchPipelineInfo

- server/src/main/java/org/opensearch/node/Node.java
> Remove extra call to initializeFeatureFlags

- libs/core/src/main/java/org/opensearch/Version.java
Bump 2.19.3 to Apache Lucene 9.12.2
Follow up on https://github.com/opensearch-project/OpenSearch/pull/18574
> Bump 2.19.3 to Apache Lucene 9.12.2

- server/build.gradle
- server/src/main/java/org/opensearch/cluster/ClusterInfo.java
- server/src/main/java/org/opensearch/index/IndexService.java
- server/src/main/java/org/opensearch/indices/IndicesService.java
Remove exclusions from breaking changes check (post 3.1.0 release)
Follow up on https://github.com/opensearch-project/OpenSearch/pull/18501
> Remove exclusions from breaking changes check (post 3.1.0 release)

- server/src/internalClusterTest/java/org/opensearch/indices/state/RemoteCloseIndexIT.java
> Mute newly introduced RemoteCloseIndexIT pending fix

- buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
- gradle/libs.versions.toml
Update JDK 21 to 21.0.8+9
Part of https://github.com/opensearch-project/OpenSearch/issues/18788
> Update JDK 21 to 21.0.8+9

- libs/core/src/main/java/org/opensearch/Version.java
Update Apache Lucene version for 2.19.3
Related Issues
Follow up on https://github.com/opensearch-project/OpenSearch/issues/14585
> Update Apache Lucene version for 2.19.3

- .github/workflows/assemble.yml
- .github/workflows/precommit.yml
- plugins/repository-hdfs/build.gradle
Update Github Actions to use JDK-24
Followup on https://github.com/opensearch-project/OpenSearch/pull/18797#issuecomment-3131864220
> Update Github Actions to use JDK-24

- CHANGELOG.md
- release-notes/opensearch.release-notes-3.2.0.md
Update changelog file for this PR https://github.com/opensearch-project/OpenSearch/pull/18955
- Coming from https://build.ci.opensearch.org/job/docker-scan/5192/artifact/scan_docker_image.txt/*view*/
- Related Issue: https://github.com/opensearch-project/OpenSearch/issues/18577
- Part of https://github.com/opensearch-project/opensearch-build/issues/5595
> Update changelog file

- server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
Backport 251cc3603e73405cc047e192663e8b5dbaa1c61d from #18944.
> [Backport 2.19] Fix segment replication bug during primary relocation

- plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java
Set context class loader to plugin's class loader when creating kafka consumer to avoid `ClassNotFoundException`. For example, when configuring SASL authentication in Kafka, the `java.base/javax.security.auth.login.LoginContext` needs to new a `org.apache.kafka.common.security.plain.PlainLoginModule` instance, but the class `PlainLoginModule` is loaded by class loader of `KafkaPlugin`, so a `ClassNotFoundException` would be thrown.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING. …
> Set context class loader to plugin's class loader when creating kafka consumer

- plugins/repository-gcs/src/internalClusterTest/java/org/opensearch/repositories/gcs/GoogleCloudStorageThirdPartyTests.java
- plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
- test/framework/src/main/java/org/opensearch/repositories/AbstractThirdPartyRepositoryTestCase.java
- test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java
Attempt to fix flaky AzureBlobStoreRepositoryTests
Closes https://github.com/opensearch-project/OpenSearch/issues/14291
> Attempt to fix flaky AzureBlobStoreRepositoryTests

- .github/CODEOWNERS
- MAINTAINERS.md
Moving myself to Emeritus and updating affiliation and codeowners.
> Move Vachashah@ to Emeritus

- server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
This PR is to address the issues mentioned in #[[19456](https://github.com/opensearch-project/OpenSearch/issues/19456)].
Resolves #[[19456](https://github.com/opensearch-project/OpenSearch/issues/19456)]
> [FIX BUG] Fix QueryPhaseTests.testMaxScoreWithSortOnScoreAndCollapsingResults

- .github/benchmark-configs.json
Refresh performance benchmark configs. Updated snapshots for lucene-10.3.0 version. 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md …
> Refresh performance benchmark configs

- CHANGELOG.md
- server/src/main/java/org/opensearch/indices/IndicesService.java
- server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
- server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java
- server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
- server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
- server/src/main/java/org/opensearch/search/profile/aggregation/ProfilingAggregator.java
- server/src/main/java/org/opensearch/search/streaming/FlushModeResolver.java
- server/src/test/java/org/opensearch/search/aggregations/metrics/MaxAggregatorTests.java
- server/src/test/java/org/opensearch/search/aggregations/metrics/MinAggregatorTests.java
> [Backport 3.3] Disable request cache for streaming and other fixes
