server/src/main/java/org/opensearch/index/ShardIndexingPressureTracker.java
server/src/test/java/org/opensearch/index/ShardIndexingPressureTrackerTests.java

This PR is 2nd of the multiple planned PRs for Shard Indexing Pressure (#478). It provides the construct (tracker) to perform shard level tracking for indexing operations.
Shard Indexing Pressure introduces smart rejections of indexing requests when there are too many stuck/slow requests in the cluster, breaching key performance thresholds. This Tracker is to store all the tracking that needs to be performed at every Shard Level for Indexing Operations on the node. Info is maintained at the granularity of three kinds of write operation (tasks) on the node i.e. coordinating, primary and replica. This will be useful in evaluating the shard indexing back-pressure on the node, to throttle requests and also to publish runtime stats.
Addresses Item 2 of #478
- [+] New functionality includes …

Add Shard Indexing Pressure Tracker. (#478)

---

build.gradle

Add sonatype repository to push snapshots.  This is an immediate solution to pushing OpenSearch artifacts to https://aws.oss.sonatype.org/content/repositories/snapshots for plugins to consume.  This will be executed via maven-publish plugin's generated task -
```
./gradlew publishAllPublicationsToSnapshotsRepository.
```
It is dependent on credentials via environment variables 
- SONATYPE_USER
- SONATYPE_PASSWORD
This will be executed via CI to generate daily snapshots.
Next steps here are to define how to publish for any opensearch repo without copying this into each repository.
[20](https://github.com/opensearch-project/opensearch-build/issues/20) …

Add Snapshot maven repository

---

server/src/main/java/org/opensearch/plugins/PluginsService.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

Add Plugin Name to make NoClassDefFoundError more verbose.
https://github.com/opensearch-project/OpenSearch/issues/824

Add Plugin name for verbose Plugin not found exception

---

server/src/main/java/org/opensearch/plugins/PluginsService.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

Add Plugin Name to make class loading errors more verbose.
https://github.com/opensearch-project/OpenSearch/issues/824

Verbose plugin not found exception

---

server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationPriorityTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationServiceTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java

Backports  (#546) in 1.x
Node initial primaries recoveries are counted towards total incoming recoveries on a node, which then throttles the replica recoveries into that node. This is incorrect as per the documentation since both limits should be separately counted. This PR attempts to fix this discrepancy by counting the initial primary recoveries separately. As a side effect of this change, I was able to optimize the time taken by ThrottlingAllocationDecider for primary shard allocation decision from the order of total number of initializing primary shards to constant. …

[Backport-1.x] Decouples primaries_recoveries limit from concurrent recoveries limits

---

buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java

Update RepositoriesSetupPlugin to point to opensearch lucene snapshot repo.  This repo not use the commit hash as a top level directory, but it does include it in the artifact name and version.
example: 
https://artifacts.opensearch.org/snapshots/lucene/org/apache/lucene/lucene-spatial-extras/9.0.0-snapshot-803d131fd08/lucene-spatial-extras-9.0.0-snapshot-803d131fd08.pom
To use:
Update version.properties to desired snapshot version, ex.
lucene            = 9.0.0-snapshot-803d131fd08
[#607]
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md …

Add URL for lucene snapshots

---

buildSrc/src/integTest/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTarIT.java
buildSrc/src/main/java/org/opensearch/gradle/VersionProperties.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/LicenseAnalyzer.java
buildSrc/src/main/java/org/opensearch/gradle/transform/SymbolicLinkPreservingUntarTransform.java
libs/nio/src/main/java/org/opensearch/nio/ServerChannelContext.java
modules/lang-painless/src/main/java/org/opensearch/painless/api/Json.java
server/src/internalClusterTest/java/org/opensearch/search/geo/GeoFilterIT.java
server/src/internalClusterTest/java/org/opensearch/versioning/ConcurrentSeqNoVersioningIT.java
server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

Backport #816 to `1.x` branch:
* Address resource leak issue suggested by Amazon CodeGuru Reviewer:
* Add try-with-resources block to automatically close the resources after using to avoid resource leak, in `SymbolicLinkPreservingTarIT`, `LicenseAnalyzer`, `SymbolicLinkPreservingUntarTransform`, `ConcurrentSeqNoVersioningIT` in `VersionProperties`, `GeoFilterIT`, `XContentHelper`,  `Json` and `IndexShard` class
* Add try-finally block to close the resources after using to avoid resource leak, in `ServerChannelContext` class.
* Add try-catch block to close the resources when exception occurs in `FsBlobContainer` class (when XContentFactory.xContentType throws an exception)
* Close resources when assertion error occurs, in `ServerChannelContext` class.
Testing:
`./gradlew check` passed. …

[Backport] [1.x] Fix resource leak issues suggested by Amazon CodeGuru (#816)

---

buildSrc/src/integTest/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTarIT.java
buildSrc/src/main/java/org/opensearch/gradle/VersionProperties.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/LicenseAnalyzer.java
buildSrc/src/main/java/org/opensearch/gradle/transform/SymbolicLinkPreservingUntarTransform.java
libs/nio/src/main/java/org/opensearch/nio/ServerChannelContext.java
modules/lang-painless/src/main/java/org/opensearch/painless/api/Json.java
server/src/internalClusterTest/java/org/opensearch/search/geo/GeoFilterIT.java
server/src/internalClusterTest/java/org/opensearch/versioning/ConcurrentSeqNoVersioningIT.java
server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

Backport #816 to `1.0` branch:
* Address resource leak issue suggested by Amazon CodeGuru Reviewer:
* Add try-with-resources block to automatically close the resources after using to avoid resource leak, in `SymbolicLinkPreservingTarIT`, `LicenseAnalyzer`, `SymbolicLinkPreservingUntarTransform`, `ConcurrentSeqNoVersioningIT` in `VersionProperties`, `GeoFilterIT`, `XContentHelper`,  `Json` and `IndexShard` class
* Add try-finally block to close the resources after using to avoid resource leak, in `ServerChannelContext` class.
* Add try-catch block to close the resources when exception occurs in `FsBlobContainer` class (when XContentFactory.xContentType throws an exception)
* Close resources when assertion error occurs, in `ServerChannelContext` class.
`./gradlew check` passed.
None
By …

[Backport] [1.0] Fix resource leak issues suggested by Amazon CodeGuru (#816)

---

client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/main/java/org/opensearch/action/main/TransportMainAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/action/main/MainActionTests.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

This PR addresses #693 by using a cluster setting instead of a system property suggested by [814](https://github.com/opensearch-project/OpenSearch/pull/814)
This setting is intended to be set after a rolling upgrade via the cluster settings API.
```
PUT /_cluster/settings
{
"compatibility" : {
"override_main_response_version" : true
}
}
``` 
It can be turned off with the same request with a value of false.
A default value for this setting may also be configured via opensearch.yml.  If not present, it defaults to false.
#693  …

Add MainResponse version override as a cluster setting.

---

client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/main/java/org/opensearch/action/main/TransportMainAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/action/main/MainActionTests.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

Backport of #847 into 1.x
This change adds a new cluster setting "compatibility.override_main_response_version"
that when enabled spoofs the version.number returned from MainResponse
for REST clients expecting legacy version 7.10.2.

Backport 1.x - Add cluster setting to spoof version number returned from MainResponse (#847)

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java

Backport PR: https://github.com/opensearch-project/OpenSearch/pull/764
We need to install elasticsearch in the test cluster nodes to be able to run the BWC tests. This commit makes the following changes to enable that,
- updates DistributionDownloadPlugin to download elasticsearch-oss distributions.
- updates OpenSearchNode to be able to run both OpenSearch and Elasticsearch distributions. …

[1.0] Backport support running elasticsearch-oss distribution in test cluster for BWC

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java

This change updates DistributionDownloader by registering a second
repository under FAKE_IVY_GROUP to fetch release-candidate bundles.  This repository exists as a fallback and will
only be checked if the release repository does not contain the requested
version.
This change also updates the snapshot repository to point to a new
snapshot repository and changes to fetch -min- versions of the bundles.
With this change steps outlined in #600 will work where a 1.0.0-SNAPSHOT version can be fetched.
The opensearch.version flag used during a plugin build it will determine which repo from snapshots or release to use.
```
./gradlew build -Dopensearch.version=1.0.0-SNAPSHOT  <- fetches from /snapshot/
./gradlew build -Dopensearch.version=1.0.0  <- …
```

Update DistributionDownloader to fetch snapshots and staging bundles.

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java

… (#904)
This change updates DistributionDownloader by registering a second
repository containing release-candidate bundles.  This repository will
only be checked if the release repository does not contain the requested
version.
This change also updates the snapshot repository to point to a new
snapshot repository.

Backport [1.x] - Update DistributionDownloader to fetch snapshots and staging bundles

---

qa/mixed-cluster/src/test/java/org/opensearch/backwards/ExceptionIT.java
server/src/main/java/org/opensearch/OpenSearchException.java

Fix for backward compatibility issue while propagating OpensearchExceptions accros nodes
#897

Replace metadata keys in OpenSearchException during serialization and deserialization

---

server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

This Change removes version.distribution when the version.number is
overridden with the cluster setting compatibility.override_main_response_version.
Removes the distribution property when in compatibility mode with 7.10.2.
curl without setting:
```
curl localhost:9200/
{
"name" : "runTask-0",
"cluster_name" : "runTask",
"cluster_uuid" : "vAOiFtLXSDqYXeCuItQGLA",
"version" : {
"distribution" : "opensearch",
"number" : "1.0.0-SNAPSHOT",
"build_type" : "tar",
"build_hash" : "457f8e746edf13c3e519fd2622521787b822a478",
"build_date" : "2021-06-29T04:15:13.028108Z",
"build_snapshot" : true,
"lucene_version" : "8.8.2",
"minimum_wire_compatibility_version" : "6.8.0",
"minimum_index_compatibility_version" : "6.0.0-beta1"
}
}
```
turn on …

Remove distribution from main response in compatibility mode

---

server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

This Change removes version.distribution when the version.number is
overridden with the cluster setting compatibility.override_main_response_version.

[Backport 1.0] Remove distribution from main response in compatibility mode

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java

Snapshots pulled from DistributionDownloader are still broken because it is fetching from the wrong path.
Snapshots are published with a -latest suffix.
Example:
```
https://artifacts.opensearch.org/snapshots/core/opensearch-dashboards/1.0.0-SNAPSHOT/opensearch-dashboards-min-1.0.0-SNAPSHOT-linux-arm64-latest.tar.gz
```
This change updates the pattern to correctly append -latest.
closes #769 …

Fix Snapshot pattern in DistributionDownloader.

---

server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

Partially replace PR #902 .
PR #902 often fails BWC test. Because BWC test uses the latest snapshot of OpenSearch 1.0.0, where "tagline" is neither in MainResponse of sever side nor of rest-client side, so the test fails when calling "Info API" from REST client requiring "tagline" but to a sever don't response with "tagline".
So I created this PR to only restore "tagline" in sever side, but not in rest-client side, aim to pass the BWC test.
- Add "tagline" field back to "MainResponse" in sever side (not in rest-high-level-client side) that removed in PR #427 .
- Replace with a new tagline "The OpenSearch Project: https://opensearch.org/".
- Turn the tagline into a constant in `server/src/main/java/org/opensearch/action/main/MainResponse.java`.
Current output of the MainResponse:
```
{ …
```

Add 'tagline' back to MainResponse in server that was removed in PR #427

---

server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

Backport #913 to `1.x` branch
- Add "tagline" field back to "MainResponse" in sever side (not in rest-high-level-client side) that removed in PR #427 .
- Replace with a new tagline "The OpenSearch Project: https://opensearch.org/".
- Turn the tagline into a constant in `server/src/main/java/org/opensearch/action/main/MainResponse.java`.
After the change in the PR, the tagline field is back:
```
{
"name" : "node-9200",
"cluster_name" : "opensearch",
"cluster_uuid" : "IoY5158sQp6oz5lkCPCVUg",
"version" : {
"distribution" : "opensearch",
"number" : "1.1.0-SNAPSHOT",
"build_type" : "tar",
"build_hash" : "79e1180251d26fd98fa88e42d4c4eca1a6768b09",
"build_date" : "2021-06-30T23:15:13.489461Z",
"build_snapshot" : true,
"lucene_version" : "8.8.2",
"minimum_wire_compatibility_version" : "6.8.0", …
```

[1.x] Add 'tagline' back to MainResponse in server that was removed in PR #427

---

server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

Backport #913 (main) #914 (1.x) to `1.0` branch.
- Add "tagline" field back to "MainResponse" in sever side (not in rest-high-level-client side) that removed in PR #427 .
- Replace with a new tagline "The OpenSearch Project: https://opensearch.org/".
- Turn the tagline into a constant in `server/src/main/java/org/opensearch/action/main/MainResponse.java`.
After the change in the PR, the tagline field is back:
```
{
"name" : "node-9200",
"cluster_name" : "opensearch",
"cluster_uuid" : "IoY5158sQp6oz5lkCPCVUg",
"version" : {
"distribution" : "opensearch",
"number" : "1.1.0-SNAPSHOT",
"build_type" : "tar",
"build_hash" : "79e1180251d26fd98fa88e42d4c4eca1a6768b09",
"build_date" : "2021-06-30T23:15:13.489461Z",
"build_snapshot" : true,
"lucene_version" : "8.8.2", …
```

[1.0] Add 'tagline' back to MainResponse in server that was removed in PR #427

---

server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

This Change removes version.distribution when the version.number is
overridden with the cluster setting compatibility.override_main_response_version.

[Backport 1.x] Remove distribution from main response in compatibility mode (#898)

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java

Snapshots are published with a -latest flag into s3, this updates
the pattern to correctly point to -latest.

[Backport 1.x] Fix Snapshot pattern in DistributionDownloader. (#916)

---

buildSrc/src/main/java/org/opensearch/gradle/Jdk.java

Backporting this change to the release branch, [original PR](https://github.com/opensearch-project/OpenSearch/pull/809). 
---
Found when attempting to build on an `arm64` machine when I recieved an error message below.  Root cause is that string equality in java cannot be done with the `==` sign.
```
unknown architecture [arm64] for jdk [provisioned_runtime], must be one of [aarch64, x64]
```

Fix arm architecture translation issue (#809)

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RefreshVersionInClusterStateIT.java
server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
server/src/main/java/org/opensearch/discovery/zen/NodeJoinController.java
server/src/main/java/org/opensearch/transport/TransportService.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java

PR for fixing the issue https://github.com/opensearch-project/OpenSearch/issues/827
Fix:
1. As soon as OpenSearch node becomes master, it refreshes the nodes version in cluster state by comparing against their channel version. Right now, it doesn't wait for all Elasticsearch nodes to leave the cluster before refreshing the version.
2. There was bug in DiscoveryNode BWC serialization logic where any ES version < 7.10.2 was getting over-written with 7.10.2
https://github.com/opensearch-project/OpenSearch/issues/827 …

Refresh OpenSearch nodes version in cluster state after upgrade

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RefreshVersionInClusterStateIT.java
server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
server/src/main/java/org/opensearch/discovery/zen/NodeJoinController.java
server/src/main/java/org/opensearch/transport/TransportService.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java

Backport PR #865 to `1.x` branch.
Fix:
- As soon as OpenSearch node becomes master, it refreshes the nodes version in cluster state by comparing against their channel version. Right now, it doesn't wait for all Elasticsearch nodes to leave the cluster before refreshing the version.
- There was bug in DiscoveryNode BWC serialization logic where any ES version < 7.10.2 was getting over-written with 7.10.2
#827 

[1.x] Refresh OpenSearch nodes version in cluster state after upgrade (#865)

---

buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java

Update DistributionDownloader to support fetching arm64 bundles.
Before this change if integration tests were executed from arm64 machines it would still fetch bundles with the -x64 classifier.  This fixes that by correctly reading and appending the -arm64 classifier.
closes #930 930

Update DistributionDownloader to support fetching arm64 bundles.

---

rest-api-spec/src/main/resources/rest-api-spec/test/cat.health/10_basic.yml
test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java

Fixes the cat.health yaml failures when running in a bwc mixed cluster with legacy (pre 1.0.0) nodes.
closes #912 
closes #922

[BUG] Fix cat.health test failures in pre 1.0.0 mixed cluster test

---

buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java

Backport #929 to 1.x branch
#930

[Backport 1.x] Update DistributionDownloader to support fetching arm64 bundles. (#929)

---

buildSrc/src/main/java/org/opensearch/gradle/Jdk.java

Backporting the change in #809 to the 1.x branch on behalf of @peternied 
Found when attempting to build on an arm64 machine when I recieved an error message below. Root cause is that string equality in java cannot be done with the == sign.
Error message:
```
unknown architecture [arm64] for jdk [provisioned_runtime], must be one of [aarch64, x64]
```
Signed-off-by: Peter Nied petern@amazon.com
For more information on following Developer Certificate of Origin and signing off your commits, please check here.

[1.x] Fix arm architecture translation issue (#809)

---

rest-api-spec/src/main/resources/rest-api-spec/test/cat.health/10_basic.yml
test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java

Fixes the cat.health yaml failures when running in a bwc mixed cluster with
legacy (pre 1.0.0) nodes.

[1.x] Bug - Fix cat.health test failures in pre 1.0.0 mixed cluster test (#928)

---

modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractAsyncBulkByScrollAction.java
modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java

The interceptor that was added in this [PR](https://github.com/opensearch-project/OpenSearch/pull/547), is not being applied as it is not set in the Rest client created to connect to remote cluster.
This change rebuilds the Rest client after the interceptor has been initialized. Once pushed to main branch, this should be ported to 1.0 branch.
#890  …

Rebuild Rest client after setting interceptor

---

.ci/java-versions.properties
DEVELOPER_GUIDE.md
build.gradle
buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java
distribution/tools/java-version-checker/build.gradle
server/build.gradle
test/framework/build.gradle

This is a rebased version of https://github.com/opensearch-project/OpenSearch/pull/636 on which I made a mess.

Lower build requirement from Java 14+ to Java 11+

---

server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/ShardIndexingPressureStore.java
server/src/test/java/org/opensearch/index/ShardIndexingPressureStoreTests.java

This PR is 4th of the multiple planned PRs planned for Shard Indexing Pressure (#478). It introduces a Store for Shard Indexing Pressure Trackers which were introduced as part of (#717 ).  It helps to manage lifecycle of tracker objects and provide access to them.
Addresses Item 4 of #478

Add Shard Indexing Pressure Store (#478)

---

build.gradle

This change backports #829 to 1.x so that we can publish snapshots to our maven repository - https://aws.oss.sonatype.org/content/repositories/snapshots/

[Backport 1.x] Add Snapshot maven repository #829

---

build.gradle

This change backports #829 to 1.0 so that we can publish patch snapshots to our maven repository - https://aws.oss.sonatype.org/content/repositories/snapshots/ 

[Backport 1.0] Add Snapshot maven repository

---

modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractAsyncBulkByScrollAction.java
modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java

Backport #876 to 1.x branch
The interceptor that was added in this #547, is not being applied as it is not set in the Rest client created to connect to remote cluster.
This change rebuilds the Rest client after the interceptor has been initialized. Once pushed to main branch, this should be ported to 1.0 branch.
fixes #890 

[1.x] Pass interceptor to super constructor (#876)

---

CONTRIBUTING.md
DEVELOPER_GUIDE.md
TESTING.md
buildSrc/version.properties
qa/translog-policy/build.gradle
server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java

Checking the boxes in https://github.com/opensearch-project/OpenSearch/issues/943
Closes #943.

Cleanup TESTING and DEVELOPER_GUIDE markdowns

---

.github/workflows/links.yml
client/benchmark/README.md
plugins/examples/rest-handler/src/yamlRestTest/resources/rest-api-spec/api/cat.example.json

Adding a broken links checker github action to check for broken links on PRs and push.
#873 

Adding broken links checker

---

README.md
plugins/examples/rest-handler/src/yamlRestTest/resources/rest-api-spec/api/cat.example.json

The link checker is failing with the docs-beta links for example in PR #947. Updating the docs-beta link references to the /docs links. 
#956 

Replacing docs-beta links with /docs

---

CONTRIBUTING.md
DEVELOPER_GUIDE.md
TESTING.md
buildSrc/version.properties
qa/translog-policy/build.gradle
server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java

[Backport-1.x] Cleanup TESTING and DEVELOPER_GUIDE markdowns (#946)

---

server/src/main/java/org/opensearch/rest/BaseRestHandler.java
server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
server/src/test/java/org/opensearch/usage/UsageServiceTests.java

Remove override for `routes()` in `BaseRestHandler` to respect default behavior of routes() defined in `RestHandler`.
This will help developers avoid re-implementing `routes()` in the subclasses of `BaseRestHandler`
They can always override the method if they'd like.
#694 

Avoid override of routes() in BaseRestHandler to respect the default behavior defined in RestHandler

---

distribution/src/config/log4j2.properties

Currently, the permissions for opensearch logs are -rw-r-r-, which gives read access to anyone. This weak permission structure can lead to leakage of any sensitive information (if published) in the logs. This commit restricts read access for logs with -rw-r--- permission.
New permission structure (verified w/ linux and darwin distros)
```
-rw-r----- 1 ubuntu ubuntu  7016 Jul 14 19:23 opensearch.log
-rw-r----- 1 ubuntu ubuntu     0 Jul 14 19:23 opensearch_deprecation.json
-rw-r----- 1 ubuntu ubuntu     0 Jul 14 19:23 opensearch_deprecation.log
-rw-r----- 1 ubuntu ubuntu     0 Jul 14 19:23 opensearch_index_indexing_slowlog.json
-rw-r----- 1 ubuntu ubuntu     0 Jul 14 19:23 opensearch_index_indexing_slowlog.log
-rw-r----- 1 ubuntu ubuntu     0 Jul 14 19:23 …
```

Restricting logs permissions

---

server/src/main/java/org/opensearch/rest/RestHandler.java
server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java

The purpose of this PR is to add a method to `RestHandler` interface so it can add prefixes to both old and new routes for REST APIs.
The PR will address the request from @vrozov in PR #1256: https://github.com/opensearch-project/security/pull/1256
- [ Done] New functionality has been documented.
- [ Done] Commits are signed per the DCO using --signoff 

Introduce replaceRoutes() method and 2 new constructors to RestHandler.java

---

server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/ShardIndexingPressureMemoryManager.java
server/src/main/java/org/opensearch/index/ShardIndexingPressureTracker.java
server/src/test/java/org/opensearch/index/ShardIndexingPressureMemoryManagerTests.java

This PR is 5th of the multiple planned PRs planned for Shard Indexing Pressure (#478). It introduces a Memory Manager for Shard Indexing Pressure. It is responsible for increasing and decreasing the allocated shard limit based on incoming requests, and validate the current values against the thresholds.
Addresses Item 5 of #478 

Add Shard Indexing Pressure Memory Manager (#478)

---

distribution/src/bin/opensearch-env

Fix line 81 of opensearch-env always sources the environment from hardcoded file. Let users override the value of OPENSEARCH_PATH_CONF. 
#633 

Fix opensearch-env always sources the environment from hardcoded file

---

distribution/src/bin/opensearch-env
distribution/src/config/jvm.options

In scripts bin/opensearch-env and config/jvm.options, the Elasticsearch 7.13 (current) version links have now been reset to Elasticsearch 7.12 version links. 
#949 

Reset Elasticsearch 7.13 links in scripts

---

buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
buildSrc/src/main/java/org/opensearch/gradle/plugin/PluginPropertiesExtension.java
buildSrc/src/main/resources/plugin-descriptor.properties
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/ListPluginsCommand.java
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/PluginHelper.java
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/RemovePluginCommand.java
distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/ListPluginsCommandTests.java
distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/RemovePluginCommandTests.java
server/src/main/java/org/opensearch/plugins/PluginInfo.java
server/src/main/java/org/opensearch/plugins/PluginsService.java
server/src/test/java/org/opensearch/nodesinfo/NodeInfoStreamingTests.java
server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

This PR allows the user to add a custom folder name for plugin cli installation. This custom folder name can be specified in the plugin properties file for the plugin, when this property is specified, the plugin would be installed with the custom folder name otherwise it will be installed with the name of the plugin. This feature would be available for versions after 1.0.0. 
The feature includes:
1. Support for custom folder name for plugin installation after 1.0.0 versions with backwards compatibility.
2. The `install` plugin command will display the folder name where the plugin is being installed.
3. The `list` plugin command will continue to display the plugin name to maintain backwards compatibility.
4. The `remove` plugin command will …

Allowing custom folder name for plugin installation

---

server/src/main/java/org/opensearch/rest/BaseRestHandler.java
server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
server/src/test/java/org/opensearch/usage/UsageServiceTests.java

[Backport-1.x]Avoid override of routes() in BaseRestHandler to respect the default behavior defined in RestHandler (#889)

---

server/src/main/java/org/opensearch/rest/RestHandler.java
server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java

* Add addRoutesPrefix() method to RestHandler.java
Signed-off-by: Azar Fazel <azar.fazel@gmail.com>
Signed-off-by: cliu123 <lc12251109@gmail.com>

[Backport-1.x]Introduce replaceRoutes() method and 2 new constructors to RestHandler.java (#947)

---

distribution/src/bin/opensearch-env
distribution/src/config/jvm.options

Replace the docs links In scripts bin/opensearch-env and config/jvm.options, with OpenSearch docs links.
Signed-off-by: Poojita-Raj <poojiraj@amazon.com>
(cherry picked from commit 6bc4ce017ad654cc2c8d7d37553c82d61c61b964)
Signed-off-by: Poojita-Raj <poojiraj@amazon.com>
Backported #994 into 1.x 
Replaces elasticsearch documentation links with OpenSearch documentation links 

[1.x] Replace Elasticsearch docs links in scripts (#994)

---

client/rest-high-level/src/test/java/org/opensearch/client/documentation/QueryDSLDocumentationTests.java
modules/mapper-extras/src/main/java/org/opensearch/index/query/RankFeatureQueryBuilder.java
modules/mapper-extras/src/main/java/org/opensearch/index/query/RankFeatureQueryBuilders.java
modules/mapper-extras/src/test/java/org/opensearch/index/query/RankFeatureQueryBuilderTests.java

Add support for rank feature query linear
https://github.com/opensearch-project/OpenSearch/issues/977

Rank feature - unknown field linear

---

server/src/test/java/org/opensearch/ExceptionSerializationTests.java
server/src/test/java/org/opensearch/rest/action/RestActionListenerTests.java

Validate that onFailure() sends response even when BytesRestResponse can not be constructed using passed exception. 
#989

Add unit test for RestActionListener. Follow up on #923.

---

server/src/main/java/org/opensearch/rest/BaseRestHandler.java
server/src/main/java/org/opensearch/rest/RestHandler.java

Wrapper class that implements delegate pattern for `RestHandler`
None, this is java utility class that can be utilized by OpenSearch core and OpenSearch plugins

Introduce RestHandler.Wrapper to help with delegate implementations

---

client/rest-high-level/src/test/java/org/opensearch/client/documentation/QueryDSLDocumentationTests.java
modules/mapper-extras/src/main/java/org/opensearch/index/query/RankFeatureQueryBuilder.java
modules/mapper-extras/src/main/java/org/opensearch/index/query/RankFeatureQueryBuilders.java
modules/mapper-extras/src/test/java/org/opensearch/index/query/RankFeatureQueryBuilderTests.java

Add support for rank feature query linear
( backport as requested here https://github.com/opensearch-project/OpenSearch/pull/983#issuecomment-889366050 )
https://github.com/opensearch-project/OpenSearch/issues/977

Rank feature - unknown field linear (#983)

---

server/src/main/java/org/opensearch/rest/action/cat/RestMasterAction.java

Signed-off-by: Bukhtawar Khan bukhtawa@amazon.com
`_cat/master` is a fundamental API to know the master instance in the cluster. Given `RestClusterState` is exempted from tripping already, doesn't make sense for `RestMasterAction` to trip
https://github.com/opensearch-project/OpenSearch/blob/b7cf1fae41869416ab206e5e8a36226e5d9c57ac/server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java#L156-L159
```
[2021-08-02T02:46:28,857][DEBUG][r.suppressed             ] [7f929454300e3b3db558b8d2980127fd] path: /_cat/master, params: {v=}
org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [<http_request>] would be [8163010008/7.6gb], which is larger than the limit of [8127315968/7.5gb], real usage: [8163010008/7.6gb], new …
```

Prevent /_cat/master from getting tripped by the CB

---

server/src/main/java/org/opensearch/rest/BaseRestHandler.java
server/src/main/java/org/opensearch/rest/RestHandler.java

Backport #1004 to 1.x
None, this is java utility class that can be utilized by OpenSearch core and OpenSearch plugins

[1.x] Introduce RestHandler.Wrapper to help with delegate implementations

---

distribution/src/bin/opensearch
distribution/src/bin/opensearch-cli
distribution/src/bin/opensearch-env
distribution/src/bin/opensearch-env-from-file
distribution/src/bin/opensearch-keystore
distribution/src/bin/opensearch-node
distribution/src/bin/opensearch-plugin
distribution/src/bin/opensearch-shard
distribution/src/bin/opensearch-upgrade

Signed-off-by: hackacad <admin@hackacad.net>
Be more liberal about the location of bash
required for upstream FreeBSD support

alt bash path support

---

buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java

This change fixes the issue where running publish commands, the sources and javadoc artifacts were not built and included with the publications.
#1028 

Include sources and javadoc artifacts while publishing to a Maven repository

---

buildSrc/build.gradle
buildSrc/src/integTest/groovy/org/opensearch/gradle/OpenSearchTestBasePluginFuncTest.groovy
buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
buildSrc/src/testKit/opensearch.build/build.gradle
buildSrc/src/testKit/testingConventions/build.gradle
buildSrc/src/testKit/thirdPartyAudit/build.gradle

https://blog.gradle.org/jcenter-shutdown
#1055 

Replace JCenter with Maven Central.

---

server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

Signed-off-by: frotsch <frotsch@mailbox.org>
Fix OpenSearch process crashing on using the index.lifecycle.name in the API body when asserts are enabled
#1019
- [x ] Commits are signed per the DCO using --signoff 

Avoid crashing on using the index.lifecycle.name in the API body

---

server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

Signed-off-by: frotsch <frotsch@mailbox.org>
Backport of #1060 Avoid crashing on using the index.lifecycle.name in the API body
#1019

Avoid crashing on using the index.lifecycle.name in the API body (#1060)

---

.github/ISSUE_TEMPLATE/bug_template.md

Do not default label beta when opening bugs.

Removed beta from new issues.

---

server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
server/src/main/java/org/opensearch/index/ShardIndexingPressure.java
server/src/main/java/org/opensearch/index/ShardIndexingPressureMemoryManager.java
server/src/main/java/org/opensearch/index/ShardIndexingPressureTracker.java
server/src/main/java/org/opensearch/index/stats/IndexingPressurePerShardStats.java
server/src/main/java/org/opensearch/index/stats/ShardIndexingPressureStats.java
server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java
server/src/test/java/org/opensearch/index/ShardIndexingPressureTests.java

This PR is next among the planned PRs planned for Shard Indexing Pressure (#478). It introduces the main Shard Indexing Pressure construct and implementation to access stats. It is a framework level artefact build on top of IndexingPressure to track incoming indexing request, per shard. 
Overall ShardIndexingPressure provides:
* Memory Accounting at shard level. Overall this feature can be enabled/disabled using on dynamic setting.
* Memory Accounting at Node level. Tracking is done using the IndexingPressure constructs to support seamless feature toggling.
* Interfaces to access the statistics (ShardIndexingPressureStats) for shard trackers.
Addresses Item 6 of #478 …

Add ShardIndexingPressure framework level construct and Stats

---

libs/grok/src/main/java/org/opensearch/grok/Grok.java
libs/grok/src/test/java/org/opensearch/grok/GrokTests.java

This change refactors the circular reference check in the Grok processor class
to use a formal depth-first traversal. It also includes a logic update to
prevent a stack overflow in one scenario and a check for malformed patterns.
This bugfix addresses CVE-2021-22144.
Signed-off-by: Kartik Ganesh <85275476+kartg@users.noreply.github.com>
closes #1078 
- [ x] New functionality has been documented.
- [x ] New functionality has javadoc added …

Improving the Grok circular reference check to prevent stack overflow

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java

This PR adds supporting logic for implementing bwc tests in plugins. This are being used in PR [anomaly-detection#158](https://github.com/opensearch-project/anomaly-detection/pull/158).
As part of #1002 

Support for bwc tests for plugins

---

libs/grok/src/main/java/org/opensearch/grok/Grok.java
libs/grok/src/test/java/org/opensearch/grok/GrokTests.java

Backporting commit af6fbc7 from main to 1.x to address CVE-2021-22144.
closes #1078
- [ x] New functionality has been documented.
- [x ] New functionality has javadoc added

Backport fix for CVE 2021 22144 to 1.x

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java

* Support for bwc tests for plugins
* Adding support for restart upgrades for plugins bwc
Backport #1051 in 1.x

[Backport-1.x] Support for bwc tests for plugins (#1051)

---

server/src/main/java/org/opensearch/index/IndexingPressureService.java
server/src/test/java/org/opensearch/index/IndexingPressureServiceTests.java

This PR is next among the planned PRs planned for Shard Indexing Pressure (#478). It introduces the main Indexing Pressure Service. It aims to provide abstraction and orchestration for indexing pressure interfaces when called from Transport Actions or for Stats.
Addresses Item 7 of #478

Add Indexing Pressure Service which acts as orchestrator for IP

---

distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/KeyStoreWrapperTests.java
plugins/store-smb/src/internalClusterTest/java/org/opensearch/index/store/SmbNIOFsTests.java
plugins/store-smb/src/main/java/org/opensearch/index/store/smbniofs/SmbNIOFsDirectoryFactory.java
plugins/store-smb/src/main/java/org/opensearch/index/store/smbsimplefs/SmbSimpleFsDirectoryFactory.java
plugins/store-smb/src/main/java/org/opensearch/plugin/store/smb/SMBStorePlugin.java
plugins/store-smb/src/test/java/org/opensearch/index/store/SmbNIOFSDirectoryTests.java
server/src/internalClusterTest/java/org/opensearch/cluster/routing/AllocationIdIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/gateway/MetadataStateFormat.java
server/src/main/java/org/opensearch/gateway/PersistedClusterStateService.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/index/translog/Checkpoint.java
server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/gateway/MetadataStateFormatTests.java
server/src/test/java/org/opensearch/gateway/PersistedClusterStateServiceTests.java
server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

Lucene 9 removes support for SimpleFS File System format. This PR deprecates the SimpleFS format in favor of NIOFS.
resolves #1072

[DEPRECATE] SimpleFS in favor of NIOFS

---

distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/KeyStoreWrapperTests.java
plugins/store-smb/src/internalClusterTest/java/org/opensearch/index/store/SmbNIOFsTests.java
plugins/store-smb/src/main/java/org/opensearch/index/store/smbniofs/SmbNIOFsDirectoryFactory.java
plugins/store-smb/src/main/java/org/opensearch/index/store/smbsimplefs/SmbSimpleFsDirectoryFactory.java
plugins/store-smb/src/main/java/org/opensearch/plugin/store/smb/SMBStorePlugin.java
plugins/store-smb/src/test/java/org/opensearch/index/store/SmbNIOFSDirectoryTests.java
server/src/internalClusterTest/java/org/opensearch/cluster/routing/AllocationIdIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
server/src/main/java/org/opensearch/env/NodeEnvironment.java
server/src/main/java/org/opensearch/gateway/MetadataStateFormat.java
server/src/main/java/org/opensearch/gateway/PersistedClusterStateService.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/index/translog/Checkpoint.java
server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/gateway/MetadataStateFormatTests.java
server/src/test/java/org/opensearch/gateway/PersistedClusterStateServiceTests.java
server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

Lucene 9 removes support for SimpleFS File System format. This commit deprecates
the SimpleFS format in favor of NIOFS.

[1.x] Deprecate SimpleFS in favor of NIOFS (#1073)

---

buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java

Backport #1049 to 1.x
This change fixes the issue where the sources and javadoc artifacts were not built and included with the publish.

[1.x] Include sources and javadoc artifacts while publishing to a Maven repository (#1049)

---

server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
server/src/main/java/org/opensearch/action/resync/TransportResyncReplicationAction.java
server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
server/src/main/java/org/opensearch/cluster/service/ClusterService.java
server/src/main/java/org/opensearch/index/IndexingPressureService.java
server/src/main/java/org/opensearch/index/seqno/RetentionLeaseSyncAction.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTookTests.java
server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionForIndexingPressureTests.java
server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java
server/src/test/java/org/opensearch/index/IndexingPressureServiceTests.java
server/src/test/java/org/opensearch/index/IndexingPressureTests.java
server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

This PR is next among the planned PRs for Shard Indexing Pressure (#478). It introduces the main integration logic of Indexing Pressure Service with Node and Transport Action classes. These IP Service APIs, will now be called appropriately for during the indexing flow. Multiple tests also updated accordingly.
Addresses Item 8 of #478

Add plumbing logic for IndexingPressureService in Transport Actions.

---

server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

Improves test run time for `server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.testSnapshotPrimaryRelocations` by reducing max datanode count and max shard count in testcase.
#579 

Improve test run time for SnapshotResiliencyTests.testSnapshotPrimaryRelocations

---

server/src/test/java/org/opensearch/search/SearchServiceTests.java

Improves test run time for server/src/test/java/org/opensearch/search/SearchServiceTests.testSearchWhileIndexDeleted by reducing max iterations.
See details [here](https://github.com/opensearch-project/OpenSearch/issues/578#issuecomment-907990472)
#578 

Reduce iterations to improve test run time for SearchServiceTests.testSearchWhileIndexDeleted

---

server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

[Backport-1.x] Tune datanode count  and shards count to improve test run time (#1170)

---

buildSrc/version.properties
client/rest/.gitignore
client/rest/build.gradle
client/rest/src/test/java/org/opensearch/client/RestClientBuilderIntegTests.java
client/rest/src/test/java/org/opensearch/client/RestClientGzipCompressionTests.java
client/rest/src/test/java/org/opensearch/client/RestClientMultipleHostsIntegTests.java
client/rest/src/test/java/org/opensearch/client/RestClientSingleHostIntegTests.java
client/sniffer/build.gradle
client/sniffer/src/test/java/org/opensearch/client/sniff/OpenSearchNodesSnifferTests.java

In scope of https://github.com/opensearch-project/OpenSearch/issues/114, it turned out the `:client:sniffer` and `:client:rest` test cases are never run under `SecurityManager`. As such, the usage of `SecureMock` and `MockSocket` is not needed and regular `Mockito` dependency could be used without any consequences.
Part of: https://github.com/opensearch-project/OpenSearch/issues/114

Drop mocksocket & securemock dependencies from sniffer and rest client (no needed)

---

NOTICE.txt
README.md
buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPluginFuncTest.groovy
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPlugin.java
distribution/packages/build.gradle

[Backport -1.x]Fixed copyright to OpenSearch 
#1175 

[Backport -1.x]Fixed copyright to OpenSearch (#1175)

---

buildSrc/version.properties
client/rest/build.gradle
client/rest/src/test/java/org/opensearch/client/RestClientBuilderIntegTests.java
client/rest/src/test/java/org/opensearch/client/RestClientGzipCompressionTests.java
client/rest/src/test/java/org/opensearch/client/RestClientMultipleHostsIntegTests.java
client/rest/src/test/java/org/opensearch/client/RestClientSingleHostIntegTests.java
client/sniffer/build.gradle
client/sniffer/src/test/java/org/opensearch/client/sniff/OpenSearchNodesSnifferTests.java

Cherry-pick https://github.com/opensearch-project/OpenSearch/pull/1174 to `1.x`
Part of: #114

Drop mocksocket & securemock dependencies from sniffer and rest client (no need) (#1174)

---

server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/Version.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/test/java/org/opensearch/VersionTests.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
test/framework/src/main/java/org/opensearch/test/VersionUtils.java

The version framework only added support for OpenSearch 1.x bwc with legacy
clusters. This commit adds support for v2.0 which will be the last version with
bwc support for legacy clusters (v7.10)

[Bug] Fix mixed cluster support for OpenSearch 2+

---

server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/Version.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/test/java/org/opensearch/VersionTests.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
test/framework/src/main/java/org/opensearch/test/VersionUtils.java

The version framework only added support for OpenSearch 1.x bwc with legacy
clusters. This commit adds support for v2.0 which will be the last version with
bwc support for legacy clusters (v7.10)

[1.x] Fix mixed cluster support for OpenSearch 2+ (#1191)

---

.github/workflows/links.yml
.lycheeexclude

Fixes https://github.com/opensearch-project/OpenSearch/issues/1199.
Lychee also reads `--exclude [list]`, so specifying multiple `--exclude` is unnecessary.
If you read this far, you might be interested in https://github.com/lycheeverse/lychee/pull/306.

Added all icu-project.org websites to the link checker exclusions.

---

buildSrc/src/main/resources/plugin-descriptor.properties

Clarify the version number of OpenSearch that goes into plugin-descriptor.properties.
If you include `-SNAPSHOT`, then a plugin cannot be installed. See https://github.com/opensearch-project/opensearch-build/issues/359 for a discussion.

Clarify opensearch.version to not include -SNAPSHOT.

---

buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
buildSrc/src/main/java/org/opensearch/gradle/Version.java
buildSrc/src/test/java/org/opensearch/gradle/BwcOpenSearchVersionsTests.java
buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java
buildSrc/src/test/java/org/opensearch/gradle/VersionTests.java
buildSrc/version.properties
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
server/src/main/java/org/opensearch/Version.java
server/src/main/java/org/opensearch/cluster/coordination/DiscoveryUpgradeService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/transport/InboundDecoder.java
server/src/main/java/org/opensearch/transport/TransportHandshaker.java
server/src/test/java/org/opensearch/VersionTests.java
server/src/test/java/org/opensearch/action/support/IndicesOptionsTests.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/discovery/zen/NodeJoinControllerTests.java
server/src/test/java/org/opensearch/transport/TransportHandshakerTests.java
test/framework/src/main/java/org/opensearch/test/VersionUtils.java
test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
test/framework/src/main/java/org/opensearch/upgrades/AbstractFullClusterRestartTestCase.java
test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java

Add next version 2.0.
depends #1191

[Version] Increment main to 2.0

---

server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/Version.java
server/src/test/java/org/opensearch/VersionTests.java

Cherry-picking https://github.com/opensearch-project/OpenSearch/pull/1112 to 1.x
https://github.com/opensearch-project/OpenSearch/issues/622

[1.x] Restoring alpha/beta/rc version semantics (#1112)

---

DEVELOPER_GUIDE.md
TESTING.md

Backport PR https://github.com/opensearch-project/OpenSearch/pull/1153 to `1.x` branch.
In DEVELOPER_GUIDE.md:
- Explicitly point out the JDK 8 requirement is for runtime, but not for compiling.
- Clarify the `JAVAx_HOME` env variables are for the "backwards compatibility test".
- Update the requirement for the `JAVAx_HOME` env variables. (Run BWC test for `1.0` or `1.x` branch requires JDK 8 and 14)
In TESTING.md:
- Add explanation on how the backwards compatibility tests get the OpenSearch distributions for a specific version.
- Clarify the requirement for `JAVAx_HOME` env variables.
#1138  …

[1.x] Clarify JDK requirement in the Developer Guide

---

server/src/main/java/org/opensearch/plugins/PluginInfo.java
server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

Keeping the original constructor for PluginInfo which was changed in PR #848 to add a new parameter. Restoring the original one so that if anything depends on it, it does not break.
#1190 

Kept the original constructor for PluginInfo to maintain bwc

---

server/src/main/java/org/opensearch/plugins/PluginInfo.java
server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

[Backport-1.x] Kept the original constructor for PluginInfo to maintain bwc (#1206)

---

qa/smoke-test-http/src/test/java/org/opensearch/http/ShardIndexingPressureRestIT.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

This PR is next among the planned PRs for Shard Indexing Pressure (#478). It introduces the shard indexing pressure metric/stats via rest end point.
Addresses Item 9 of #478
-  [x] Commits are signed per the DCO using --signoff 

Add shard indexing pressure metric/stats via rest end point.

---

.lycheeexclude

Signed-off-by: Sai Kumar <karanas@amazon.com>
Exclude failing links from plugins/modules in link checker
N/A

Exclude failing links from plugins/modules in link checker

---

modules/reindex/src/test/java/org/opensearch/index/reindex/ReindexRestClientSslTests.java

On Windows with Docker Desktop installed, some of the `org.opensearch.index.reindex.ReindexRestClientSslTests` are failling with `javax.net.ssl.SSLPeerUnverifiedException`. The problem in this particular case is related to the fact that all certificates have been generated for the `localhost` but the local hostname was resolved to `kubernetes.docker.internal`.
The solution is pretty simple and has no consequences: just use `localhost` as bind and connect address, otherwise the certificate validation is going to fail in any case (run into it while working on https://github.com/opensearch-project/OpenSearch/pull/1205, issue is gone after the fix)
https://github.com/opensearch-project/OpenSearch/issues/710 …

Fix org.opensearch.index.reindex.ReindexRestClientSslTests#testClientSucceedsWithCertificateAuthorities - javax.net.ssl.SSLPeerUnverifiedException

---

.github/workflows/links.yml

Most PRs do not add/update links, however sites go down often. This change makes sure that we catch any broken links in the repository and fix it, but at the same time we do not block PRs because of some unrelated broken link.
This PR updates the workflow to run everyday at midnight UTC.
N/A

Run link checker GitHub action on schedule.

---

server/src/internalClusterTest/java/org/opensearch/index/IndexingPressureIT.java
server/src/internalClusterTest/java/org/opensearch/index/ShardIndexingPressureIT.java
server/src/internalClusterTest/java/org/opensearch/index/ShardIndexingPressureSettingsIT.java
server/src/main/java/org/opensearch/index/IndexingPressureService.java
server/src/test/java/org/opensearch/index/ShardIndexingPressureMemoryManagerTests.java

This PR is next among the planned PRs for Shard Indexing Pressure (#478). It introduces the shard indexing pressure integration ITs and refactoring for indexing pressure ITs.
Addresses Item 10 of #478

Add shard indexing pressure integration tests.

---

server/src/main/java/org/opensearch/search/SearchService.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java

Backport PR #1054 to 1.x
Changes the Exception to throw a OpenSearchRejectedExecutionException on max scroll limit breach
Signed-off-by: Bukhtawar Khan bukhtawa@amazon.com

[1.x] Max scroll limit breach to throw a OpenSearchRejectedExecutionException (#1054)

---

gradle/code-coverage.gradle
test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java

- Fix the issue that code coverage in HTML format can't be disabled.
- Resolve the error when running `./gradlew check -Dtests.coverage=true`
Explanation:
1. Html format report is generated by default in [JaCoCo gradle plugin](https://github.com/gradle/gradle/blob/4fa9149b3148554bc84c2f6e12ec7b53c10e4e2f/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java#L159), so it needs to be disabled manually.
2. System property `tests.coverage` is introduced in https://github.com/elastic/elasticsearch/commit/2a129f186874689f7c16b8ab77eba508d9ae7250, then I used the same property for generating the code coverage report, and it caused the error (a past forum thread about the error https://discuss.elastic.co/t/estestcase-2-x-jacoco-not-working/45104).
- I think that …

Fix defects in code-coverage.gralde to generate code coverage report properly

---

buildSrc/version.properties
libs/secure-sm/src/main/java/org/opensearch/secure_sm/SecureSM.java
libs/secure-sm/src/test/java/org/opensearch/secure_sm/SecureSMTests.java
modules/reindex/src/test/java/org/opensearch/index/reindex/ReindexRestClientSslTests.java
modules/repository-url/src/test/java/org/opensearch/common/blobstore/url/URLBlobStoreTests.java
modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/Netty4SizeHeaderFrameDecoderTests.java
plugins/discovery-azure-classic/src/internalClusterTest/java/org/opensearch/discovery/azure/classic/AzureDiscoveryClusterFormationTests.java
plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/AbstractEC2MockAPITestCase.java
plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2NetworkTests.java
plugins/examples/rest-handler/src/javaRestTest/java/org/opensearch/example/resthandler/ExampleFixtureIT.java
plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
server/src/test/java/org/opensearch/transport/RemoteClusterConnectionTests.java
test/framework/build.gradle
test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
test/framework/src/main/java/org/opensearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java
test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchMockAPIBasedRepositoryIntegTestCase.java
test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java

Drop `mocksocket` in favour of custom security manager checks (tests only). The `mocksocket` was used as a trusted sandbox for network-related communications in test framework. Sadly, it introduces additional dependency on third-party library in order to bypass security manager checks.
The suggested alternative solution is not equivalent but has acceptable trade-offs (feedback is very welcome). The basic idea is to:
- extend `SecurityManager` which is used in **test only** to trust caller chains involving `sun.net.httpserver.ServerImpl`, `java.net.ServerSocket` and `java.net.Socket` for Socket's `connect` and `accept` permission checks
- constraint the `host` to local addresses only (IPv4 & IPv6)
How does it compare to:
```
grant {
// …
```

Drop mocksocket in favour of custom security manager checks (tests only)

---

build.gradle
buildSrc/src/main/groovy/org/opensearch/gradle/BuildPlugin.groovy
gradle/code-coverage.gradle
test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java

Backport #971 and #1214 to `1.x` branch
- Apply JaCoCo Gradle plugin to the root project, and to all the sub-projects through `BuildPlugin`.
- Add 3 Gradle tasks: `codeCoverageReport`, `codeCoverageReportForUnitTest`, `codeCoverageReportForIntegrationTest` to generate code coverage report for all the tests, unit tests, and integration tests correspondingly.
- Attach Gradle `codeCoverageReport` task to `check` task.
- Remove outdated code of giving JaCoCo files permission when Java security manager enabled
Usage of the new Gradle tasks:
- Generate code coverage report after `check` task: run `./gradlew check -Dtests.coverage=true`
- Generate code coverage report
for all the test: `./gradlew codeCoverageReport`, 
for unit tests only: `./gradlew codeCoverageReportForUnitTest`,
for …

[1.x] Add support to generate code coverage report with JaCoCo

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
distribution/docker/build.gradle
distribution/packages/build.gradle

Rename build artifact to include -min. Distinguish minimal distribution from bundle(with plugins from other repos in opensearch-project).
#1094

Rename build artifact to include -min

---

buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
distribution/docker/build.gradle
distribution/packages/build.gradle

Backport PR#[1251](https://github.com/opensearch-project/OpenSearch/pull/1251)
#1094 

[1.x] Rename build artifact to include -min

---

buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java

Fix gradle check failing due to artifact renaming in #1094.
#1285 

Fix gradle check fail due to artifact renaming with "-min"

---

server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java

INDEX_PLUGINS_REPLICATION_TRANSLOG_RETENTION_LEASE_PRUNING_ENABLED_SETTING was
deprecated, then deprecation was removed. This adds deprecation back so that the
setting can be moved to the plugin in the next minor release.

[Revert] Translog Pruning Setting Deprecation Removal

---

server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

This commit adds test coverage for translog pruning setting to
MetadataCreateIndexServiceTests

[Tests] Translog Pruning tests to MetadataCreateIndexServiceTests

---

server/src/internalClusterTest/java/org/opensearch/script/ScriptCacheIT.java
server/src/main/java/org/opensearch/script/GeneralScriptException.java
server/src/test/java/org/opensearch/script/ScriptCacheTests.java

When a circuit breaker occurs due to compilation threshold breach, then OpenSearchRejectedExecutionException is called.
Resolves #1064 

Painless compilation threshold breach with correct error status

---

server/src/main/java/org/opensearch/monitor/jvm/JvmStats.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java

JVM stats published today represents the point in time usage of the heap across pools. While
`MemoryPoolMXBean::getCollectionUsage` provides the memory usage after the Java virtual machine most recently expended effort in recycling unused objects in this memory pool. Exposing this information could be quite helpful while troubleshooting GC and memory issues.
The `jvm` section of the node statistics had been extended to include the additional details regarding most recent GC cycle for a particular memory pool, under new `last_gc_stats` section:
```
"old" : {                             
"used_in_bytes" : 50526632,
"max_in_bytes" : 357957632,
"peak_used_in_bytes" : 50526632,
"peak_max_in_bytes" : 357957632,
"last_gc_stats" : { …
```

Support for Heap after GC stats

---

server/src/main/java/org/opensearch/monitor/jvm/JvmStats.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/1265 to 1.x
https://github.com/opensearch-project/OpenSearch/issues/981

[Backport] [1.x] Support for Heap after GC stats (opensearch-project#1265)

---

server/src/main/java/org/opensearch/monitor/jvm/JvmStats.java

Signed-off-by: Andriy Redko andriy.redko@aiven.io
Correction after https://github.com/opensearch-project/OpenSearch/pull/1309 backport, lowering version requirements to `1.2.0`.
https://github.com/opensearch-project/OpenSearch/issues/981

Support for Heap after GC stats (correction after backport to 1.2.0)

---

README.md

Signed-off-by: Rishikesh Pasham <rishireddy1159@gmail.com>
Security warnings and issues reporting instructions are added on README.md file.
#1266 

Adding Security Reporting Instructions in README.md file.

---

buildSrc/src/main/resources/checkstyle_suppressions.xml
gradle/formatting.gradle
rest-api-spec/src/yamlRestTest/java/org/opensearch/test/rest/ClientYamlTestSuiteIT.java

Applied Spotless to rest-api-spec module and excluded it from CheckStyle.
Part of https://github.com/opensearch-project/OpenSearch/issues/1362 and https://github.com/opensearch-project/OpenSearch/issues/974

Run spotless and exclude checkstyle on `rest-api-spec` module

---

buildSrc/src/main/resources/checkstyle_suppressions.xml
gradle/formatting.gradle
rest-api-spec/src/yamlRestTest/java/org/opensearch/test/rest/ClientYamlTestSuiteIT.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/1462

[Backport-1.x] Run Spotless and exclude Checkstyle on rest-api-spec module (#1462)

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/translog/DefaultTranslogDeletionPolicy.java
server/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicy.java
server/src/main/java/org/opensearch/index/translog/TranslogReader.java
server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
server/src/test/java/org/opensearch/index/translog/TranslogTests.java
test/framework/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicies.java

As part of the commit 2ebd0e04, we added a new method to the EnginePlugin to provide a custom `TranslogDeletionPolicy.` This commit makes `minTranslogGenRequired` method abstract in this class for overridden by plugins. The default implementation is provided by `DefaultTranslogDeletionPolicy`.
Relates #1260 

Make TranslogDeletionPolicy abstract for extension

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/RunTask.java

This change updates the logic in RunTask to use deterministic port values for all nodes rather than just the first node in a cluster. The local address of the first node is also used as the seed_hosts value to allow the cluster to form correctly.
Signed-off-by: Kartik Ganesh <85275476+kartg@users.noreply.github.com>
N/A

Fixing support for a multi-node cluster via "gradle run"

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/translog/DefaultTranslogDeletionPolicy.java
server/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicy.java
server/src/main/java/org/opensearch/index/translog/TranslogReader.java
server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
server/src/test/java/org/opensearch/index/translog/TranslogTests.java
test/framework/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicies.java

As part of the commit 2ebd0e04, we added a new method to the EnginePlugin to provide a
custom `TranslogDeletionPolicy`. This commit makes `minTranslogGenRequired` method
abstract in this class for implementation by child classes. The default implementation
is provided by `DefaultTranslogDeletionPolicy`.

[Backport 1.x] Make TranslogDeletionPolicy abstract for extension (#1456)

---

libs/nio/src/test/java/org/opensearch/nio/InboundChannelBufferTests.java
plugins/examples/rescore/src/main/java/org/opensearch/example/rescore/ExampleRescoreBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java
server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
server/src/test/java/org/opensearch/index/shard/StoreRecoveryTests.java
server/src/test/java/org/opensearch/index/snapshots/blobstore/FileInfoTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java
server/src/test/java/org/opensearch/search/aggregations/metrics/SumAggregatorTests.java
test/framework/src/main/java/org/opensearch/common/bytes/AbstractBytesReferenceTestCase.java

CodeQL scanning has warnings about implicit narrowing conversion in compound assignment. PR to avoid the warnings. 
#1000 

Remove codeQL warning about implicit narrowing conversion in compound assignment

---

libs/nio/src/test/java/org/opensearch/nio/InboundChannelBufferTests.java
plugins/examples/rescore/src/main/java/org/opensearch/example/rescore/ExampleRescoreBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java
server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
server/src/test/java/org/opensearch/index/shard/StoreRecoveryTests.java
server/src/test/java/org/opensearch/index/snapshots/blobstore/FileInfoTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java
server/src/test/java/org/opensearch/search/aggregations/metrics/SumAggregatorTests.java
test/framework/src/main/java/org/opensearch/common/bytes/AbstractBytesReferenceTestCase.java

Backport PR#[1403](https://github.com/opensearch-project/OpenSearch/pull/1403)

[Backport 1.x]Remove codeQL warning about implicit narrowing conversion in compound assignment

---

qa/no-bootstrap-tests/src/test/java/org/opensearch/bootstrap/SpawnerNoBootstrapTests.java
server/src/main/java/org/opensearch/plugins/PluginsService.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

Fixes a bug that would not allow OpenSearch to run when a {dot} file (i.e. ".test") was present in the plugins folder.
https://github.com/opensearch-project/OpenSearch/issues/626

Added logic to allow {dot} files on startup

---

build.gradle

This PR reenables bwc testing after syncing proper staged versions on all development branches.
closes #1507

[bwc] reenable bwc testing after syncing staged branches

---

distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/DetectEsInstallationTaskTests.java
distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ImportYmlConfigTaskTests.java
distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/UpgradeCliTests.java
distribution/tools/upgrade-cli/src/test/resources/config/elasticsearch.yml

I observed a [test failure][1] that I believe was caused by the fact
that an OpenSearch server happened to be running at localhost:9200 when
these unit tests were executed. The code under test has logic to try to
connect to localhost:9200 and then fall back to defaults if that port is
not open. The tests expect these defaults and will fail if different
data is returned. The change here is to use a non-default port to make
it very unlikely that a real instance will be running at the non-default
port. I don't know why an OpenSearch service happened to be running
during the linked test failure, but I think making these unit tests more
independent and isolated is helpful no matter the underlying cause in
this case.
[1]: https://fork-jenkins.searchservices.aws.dev/job/OpenSearch_CI/job/PR_Check …

Use a non-default port for upgrade-cli unit tests

---

qa/no-bootstrap-tests/src/test/java/org/opensearch/bootstrap/SpawnerNoBootstrapTests.java
server/src/main/java/org/opensearch/plugins/PluginsService.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

* Added logic to allow {dot} files on startup
* Ensures that only plugin directories are returned by findPluginDirs()
* Prevents . files from being returned as plugins
Backport of #1437 
#626 
- [X ] New functionality includes testing.
- [X ] All tests pass
- [ X] Commits are signed per the DCO using --signoff 

[Backport] Added logic to allow {dot} files on startup (#1437)

---

.whitesource
whitesource.config

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
The WhiteSource config was set to default and doesn't seem to work properly for OpenSearch repo. We change the mode to `LOCAL` and provide the `unified agent` config file we used before. 
N/A

Add a whitesource unified agent file and update the config

---

modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/netty4/OpenSearchLoggingHandlerIT.java
plugins/transport-nio/src/internalClusterTest/java/org/opensearch/transport/nio/NioTransportLoggingIT.java
server/src/test/java/org/opensearch/common/settings/SettingsFilterTests.java
server/src/test/java/org/opensearch/transport/TransportLoggerTests.java
test/framework/src/main/java/org/opensearch/test/MockLogAppender.java

I observed a test failure with the message
'Attempted to append to non-started appender mock' from an assertion in
`OpenSearchTestCase::after`. I believe this indicates that a
MockLogAppender (which is named "mock") was added as an appender to the
static logging context and some other test in the same JVM happened to
cause a logging statement to hit that appender and cause an error, which
then caused an unrelated test to fail (because they share static state
with the logger). Almost all usages of MockLogAppender start it
immediately after creation. I found a few that did not and fixed those.
I also made a static helper in MockLogAppender to start it upon
creation. …

Start MockLogAppender before adding to static context

---

server/src/main/java/org/opensearch/cluster/coordination/FollowersChecker.java

Production systems generally don't have debug logging enabled. The reasons for follower rejection are now logged at the default INFO logging level.
#992 

Improve leader node-left logging to indicate timeout/coordination state rejection

---

release-notes/opensearch.release-notes-1.1.0.md
release-notes/opensearch.release-notes-1.2.0.md

Adds release notes from 1.2 starting with[ 1.x version bump to 1.2](https://github.com/opensearch-project/OpenSearch/commit/bf1d35c41a186d9318b9a252a99334a2fccaaa7d).  Also removed overlap for commits that were backported to 1.x after they appeared in and were released with the 1.1 branch.
The 1.1 release notes are missing a set of commits. This updates the release notes
to the commit specified in the 1.1 release tag - 15e9f13 and 
https://github.com/opensearch-project/OpenSearch/commits/1.1.0
#1317  …

Add 1.2 release notes and correct 1.1 release notes.

---

client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
client/rest-high-level/src/test/java/org/opensearch/client/ReindexIT.java

Enables the RestHighLevelClient to set the `require_alias` Parameter for Index and Update Bulk Requests and for Reindex Requests
[[High level REST client index() is not respecting the indexRequest.setRequireAlias(true) method call]](https://github.com/opensearch-project/OpenSearch/issues/1528)

Enable RestHighLevel-Client to set parameter require_alias 

---

modules/mapper-extras/src/test/resources/org/opensearch/index/mapper/metricbeat-6.0.template.json

Signed-off-by: Rishikesh Pasham <rishireddy1159@gmail.com>
Renaming slave to replica in filebeat-6.0.template.json file
#1556 

Renaming "slave" terminology to replica.

---

server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

Signed-off-by: Megha Sai Kavikondala <kavmegha@amazon.com>
Changes made for giving more informative error messages.
If a URL with an empty index name or having double slash is requested, a pretty random answer is given:
```
$ curl -X PUT -H 'Content-type: application/json' localhost:9200//_cluster/settings?pretty -d '{}'
{
"error" : {
{
"type" : "string_index_out_of_bounds_exception",
"reason" : "String index out of range: 0"
}
],
"type" : "string_index_out_of_bounds_exception",
"reason" : "String index out of range: 0"
},
"status" : 500
}
```
Thus, rather than giving a random answer, an informative error message is given:
```
{
"error" : {
{
"type" : "invalid_index_name_exception",
"reason" : "Invalid index name [], reason: Invalid index name [], must …
```

Giving informative error messages for double slashes in API call URLs

---

client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
client/rest-high-level/src/test/java/org/opensearch/client/ReindexIT.java

Signed-off-by: Jan Baudisch <jan.baudisch.libri@gmail.com>
- [x ] New functionality has been documented.
- [ x] New functionality has javadoc added
- [x ] Commits are signed per the DCO using --signoff 

Enable RestHighLevel-Client to set parameter require_alias for bulk index and reindex requests

---

.github/workflows/backport.yml
DEVELOPER_GUIDE.md

This Github action creates backport PR automatically when appropriate labels are added to the PR on main. Once the original PR gets merged to main, this Github action will open backport PR. For example, if we want to backport a PR to 1.x, add label `backport 1.x` to the original PR, once this PR is merged, the Github action will open a backport to 1.x PR from the original PR.
Reference: https://github.com/marketplace/actions/backporting
I tried this on my own repo and was able to create appropriate backport PRs. Example: https://github.com/VachaShah/TestGithubActions/pull/7
For more information …

Adding Github action for auto backport PR creation

---

.ci/java-versions.properties
DEVELOPER_GUIDE.md
build.gradle
buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java
distribution/tools/java-version-checker/build.gradle
server/build.gradle
test/framework/build.gradle

This is a backported version of #940 into 1.x.

[Backport 1.x] Lower build requirement from Java 14+ to Java 11+

---

server/src/main/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilder.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/test/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilderTests.java
server/src/test/java/org/opensearch/search/SearchModuleTests.java

Rename field_masking_span to span_field_masking as well as maintain backwards compatibility.
#1531 

Rename field_masking_span to span_field_masking

---

buildSrc/build.gradle

Fixing publishing to Maven Local for plugins
```
> Task :build-tools:publishPluginMavenPublicationToMavenLocal
Execution optimizations have been disabled for task ':build-tools:publishPluginMavenPublicationToMavenLocal' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/tmp/tmptny3_u2s/OpenSearch/buildSrc/build/distributions/build-tools-2.0.0-SNAPSHOT.pom'. Reason: Task ':build-tools:publishPluginMavenPublicationToMavenLocal' uses this output of task ':build-tools:generatePomFileForNebulaPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to …
```

Support Gradle 7. Fixing publishing to Maven Local for plugins

---

server/src/main/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilder.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/test/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilderTests.java
server/src/test/java/org/opensearch/search/SearchModuleTests.java

Backport PR[#1606](https://github.com/opensearch-project/OpenSearch/pull/1606)
Rename field_masking_span to span_field_masking as well as maintain backwards compatibility.

[Backport 1.x] Rename field_masking_span to span_field_masking (#1606)

---

buildSrc/build.gradle

More reliable fix for https://github.com/opensearch-project/OpenSearch/pull/1624 to cover all plugin-related tasks.
N/A

  Support Gradle 7. More reliable tasks dependencies for Maven plugins publishing

---

DEVELOPER_GUIDE.md

Realised that the auto-backport added in PR #1600 was missing the point that the backport workflow needs to run on the PR to auto-backport. Adding it in the documentation.

Updating auto backport documentation

---

modules/mapper-extras/src/test/resources/org/opensearch/index/mapper/metricbeat-6.0.template.json

Signed-off-by: Rishikesh Pasham <rishireddy1159@gmail.com>
Renaming Slave Terminology to Replica in 1.x branch. This is backporting to 1.x of PR https://github.com/opensearch-project/OpenSearch/pull/1569
https://github.com/opensearch-project/opensearch/issues/1556

Renaming Slave terminology to Replica in 1.x branch (backporting)

---

build.gradle

The `eclipse` plugin fails with:
```
...
> Task :test:fixtures:hdfs-fixture:eclipseJdt                                                                                                                                                
Execution optimizations have been disabled for task ':test:fixtures:hdfs-fixture:eclipseJdt' to ensure correctness due to the following reasons:                                             
- Gradle detected a problem with the following location: '/home/andriy.redko/Workspaces/Experiments/OpenSearch/test/fixtures/hdfs-fixture/.settings/org.eclipse.jdt.core.prefs'. Reason: Ta
sk ':test:fixtures:hdfs-fixture:eclipseJdt' uses this output of task ':test:fixtures:hdfs-fixture:copyEclipseSettings' without declaring …
```

Support Gradle 7. Fixing 'eclipse' plugin dependencies

---

.gitattributes

There is a difference between end of line CRLF vs LF between Windows/*nix systems which causes `spotless` checks to fail. The suggested solution is to use `.gitattributes` , see please https://github.com/diffplug/spotless/issues/23
Linux:
```
$ ./gradlew spotlessJavaCheck
...
> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
Gradle Version        : 7.3
OS Info               : Linux 5.13.0-22-generic (amd64)
JDK Version           : 11 (Ubuntu JDK)
JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
Random Testing Seed   : 2A834AAD373C92B6
In FIPS 140 mode      : false …
```

Added .gitattributes to manage end-of-line checks for Windows/*nix systems

---

.gitattributes

Backport of https://github.com/opensearch-project/OpenSearch/pull/1638 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1637

[Backport] [1.x] Added .gitattributes to manage end-of-line checks for Windows/*nix systems (#1638)

---

modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/netty4/OpenSearchLoggingHandlerIT.java
plugins/transport-nio/src/internalClusterTest/java/org/opensearch/transport/nio/NioTransportLoggingIT.java
server/src/test/java/org/opensearch/common/settings/SettingsFilterTests.java
server/src/test/java/org/opensearch/transport/TransportLoggerTests.java
test/framework/src/main/java/org/opensearch/test/MockLogAppender.java

I observed a test failure with the message
'Attempted to append to non-started appender mock' from an assertion in
`OpenSearchTestCase::after`. I believe this indicates that a
MockLogAppender (which is named "mock") was added as an appender to the
static logging context and some other test in the same JVM happened to
cause a logging statement to hit that appender and cause an error, which
then caused an unrelated test to fail (because they share static state
with the logger). Almost all usages of MockLogAppender start it
immediately after creation. I found a few that did not and fixed those.
I also made a static helper in MockLogAppender to start it upon
creation.

[BACKPORT-1.x] Start MockLogAppender before adding to static context (#1587)

---

server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/Version.java
server/src/test/java/org/opensearch/LegacyESVersionTests.java
server/src/test/java/org/opensearch/VersionTests.java
test/framework/src/main/java/org/opensearch/test/VersionUtils.java
test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java

In preparation for removing all LegacyESVersion support by 3.0; this PR
largely refactors the `LegacyESVersion` test logic from the OpenSearch `Version`
test logic into an independent test class. This PR also updates `Version.fromString`
to ensure a proper legacy version is returned when major is > 3 (to support 
legacy yaml test and build scripts).
Note that bwc w/ legacy versions are still supported so some cross compatibility 
testing is retained in the Version test class.

Refactor LegacyESVersion tests from Version tests

---

.github/workflows/precommit.yml
.github/workflows/wrapper.yml

As part of https://github.com/opensearch-project/opensearch-build/issues/982, move gradle wrapper and precommit checks into the OpenSearch GHA. These currently are implemented and running on a private Jenkins instance, which needs not to be.

Move Gradle wrapper and precommit checks into OpenSearch repo.

---

.github/workflows/dco.yml

Signed-off-by: CEHENKLE <henkle@amazon.com>
Backport of #1458.
https://github.com/opensearch-project/OpenSearch/issues/1318

[Backport] Backport DCO check into GHA

---

server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java

Try to fix the unit test `testFailsHealthOnHungIOBeyondHealthyTimeout()` in class `FsHealthServiceTests`, according to the idea in comment https://github.com/opensearch-project/OpenSearch/issues/1567#issuecomment-989021906
- Increase the max waiting time between cancelling the IO hanging and checking the File System health status. Increase the `2x` multiplier to `3x` that applied to `refreshInterval`.
- Remove the duplicate assertion statements for getting better error message.
Note:
**1**
The test failure can not be reproduced easily locally, and only sometime shows up in the CI workflow. I guess the reason of the test failure is there are dozens of file directories have to be restoring from the IO hanging status in the below step, …

Fix unit test testFailsHealthOnHungIOBeyondHealthyTimeout() by incresing the max waiting time before assertion

---

distribution/src/config/jvm.options
gradle.properties

Since the integration of [1] into JDK-18,  setting `SecurityManager` now requires JVM command line option to enable it explicitly. Running OpenSearch server or tests on latest JDK-18 EA builds fails with exception:
```
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
at java.base/java.lang.System.setSecurityManager(System.java:416)
at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:91)
```
[1] https://bugs.openjdk.java.net/browse/JDK-8270380
Part of https://github.com/opensearch-project/OpenSearch/issues/1687
For more …

Support JDK 18 EA builds

---

.github/workflows/links.yml

Ensures that the link checker workflow only runs on opensearch-project/OpenSearch, and not on private forks of the repo.
N/A

link checker fix - only run on opensearch-project/OpenSearch

---

.gitattributes

Backport of https://github.com/opensearch-project/OpenSearch/pull/1717 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1713

[Backport] [1.x] Fixing .gitattributes for binary content, removing *.class files (#1717)

---

distribution/src/config/jvm.options
gradle.properties

Backport of https://github.com/opensearch-project/OpenSearch/pull/1710 to 1.x
Part of [#1687](https://github.com/opensearch-project/OpenSearch/issues/1687)

[Backport] [1.x] Support JDK 18 EA builds

---

release-notes/opensearch.release-notes-1.2.1.md

Adding release notes for 1.2.1

Adding release notes for 1.2.1

---

libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentBuilder.java

Apologies for spamming. I was trying to compile a plugin and this typo was in the way.

Fix JavaDoc typo in XContentBuilder

---

server/src/main/java/org/opensearch/index/mapper/DynamicTemplate.java
server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
server/src/test/java/org/opensearch/index/mapper/DynamicTemplateTests.java

This PR removes legacy version checks in DynamicTemplate parsing that are no longer valid in OpenSearch 2.0.0.

[Remove] DynamicTemplate deprecations

---

plugins/repository-azure/build.gradle
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureBlobStore.java
test/fixtures/azure-fixture/src/main/java/fixture/azure/AzureHttpHandler.java

The issue is closely related to FasterXML/jackson-databind#3322 and in the nutshell, Azure Blob APIs V12 heavily relies on the fact that empty XML elements / attributes are going to be nullified.
However, sadly, it highly depends on `XMLInputReader` instance being picked up at runtime: the `Woodstox` does that, whereas the default one from JDK `com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl` does not. It leads to infinite loop within `listBlobsByHierarchy` or `listBlobs` - the page iterator only understands `null` as termination condition.
The fastest option to get it fixed is to fallback to manual iteration. The bug report to upstream is also submitted https://github.com/Azure/azure-sdk-for-java/issues/26064
Closes …

[plugin] repository-azure is not working properly hangs on basic operations

---

plugins/repository-azure/build.gradle
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureBlobStore.java
test/fixtures/azure-fixture/src/main/java/fixture/azure/AzureHttpHandler.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/1740 to 1.2
Closes https://github.com/opensearch-project/OpenSearch/issues/1734

[backport] [1.2] [plugin] repository-azure is not working properly hangs on basic operations

---

build.gradle
gradle.properties

Better support of  JDK-18 EA without breaking other JDK runtimes **(tests only)**.  Tested with
```
gradle :plugins:repository-azure:check -Druntime.java=11
gradle :plugins:repository-azure:check -Druntime.java=15
gradle :plugins:repository-azure:check -Druntime.java=16
gradle :plugins:repository-azure:check -Druntime.java=18
gradle :plugins:repository-azure:check
```
N/A

Better JDK-18 EA (and beyond) support of SecurityManager

---

server/src/main/java/org/opensearch/Build.java

This PR removes unnecessary serialization of unused flavor variable in build
metadata from V_1_3_0+. This will need to be backported to ensure bwc tests do not fail.

[Remove] Remaining Flavor Serialization

---

server/src/internalClusterTest/java/org/opensearch/search/profile/ProfilerSingleNodeNetworkTest.java
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
server/src/main/java/org/opensearch/action/search/SearchExecutionStatsCollector.java
server/src/main/java/org/opensearch/action/search/SearchQueryThenFetchAsyncAction.java
server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
server/src/main/java/org/opensearch/search/profile/NetworkTime.java
server/src/main/java/org/opensearch/search/profile/ProfileShardResult.java
server/src/main/java/org/opensearch/search/profile/SearchProfileShardResults.java
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/main/java/org/opensearch/search/query/QuerySearchResult.java
server/src/main/java/org/opensearch/transport/RequestHandlerRegistry.java
server/src/main/java/org/opensearch/transport/TcpTransportChannel.java
server/src/test/java/org/opensearch/search/profile/SearchProfileShardResultsTests.java

Signed-off-by: Raj <poojiraj@a07817a9866b.ant.amazon.com>
For profiler queries on multi-node clusters, we get a timing breakdown on a shard-by-shard basis regarding time spent in various sub parts of the query. However, this neglects the time spent on each shard query in transit over the network in the case of multi node clusters.
This PR resolves this by adding additional fields for each shard to get the time spent in transit over the network (in milliseconds).
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-or …

Bridging the gap in network overhead measurement in the profiler

---

build.gradle
gradle.properties

Backport of https://github.com/opensearch-project/OpenSearch/pull/1750 to 1.x

[Backport] [1.x] Better JDK-18 EA (and beyond) support of SecurityManager (#1750)

---

.gitattributes
release-notes/opensearch.release-notes-1.2.1.md

Updating `.gitattributes` for additional file types.
With exiting `.gitattributes`, Linux is seeing unexpected changes:
```
On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   buildSrc/src/main/resources/cacerts.bcfks
modified:   client/rest/src/test/resources/test.crt
modified:   gradlew.bat
modified:   libs/ssl-config/src/test/resources/certs/ca-all/ca.p12
modified:   plugins/ingest-attachment/licenses/commons-collections4-LICENSE.txt
modified:   plugins/ingest-attachment/licenses/commons-collections4-NOTICE.txt
modified:   plugins/ingest-attachment/licenses/slf4j-api-LICENSE.txt
modified: …
```

Updating .gitattributes for additional file types

---

server/src/main/java/org/opensearch/Build.java
server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteResponse.java
server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateResponse.java
server/src/main/java/org/opensearch/action/search/SearchRequest.java
server/src/main/java/org/opensearch/cluster/action/shard/ShardStateAction.java
server/src/main/java/org/opensearch/index/flush/FlushStats.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/index/translog/TranslogStats.java
server/src/main/java/org/opensearch/indices/flush/SyncedFlushService.java
server/src/main/java/org/opensearch/persistent/PersistentTasksCustomMetadata.java
server/src/main/java/org/opensearch/persistent/StartPersistentTaskAction.java
server/src/main/java/org/opensearch/plugins/PluginInfo.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
server/src/main/java/org/opensearch/search/slice/SliceBuilder.java
server/src/main/java/org/opensearch/transport/Header.java
server/src/main/java/org/opensearch/transport/OutboundMessage.java
server/src/main/java/org/opensearch/transport/TransportLogger.java
server/src/test/java/org/opensearch/BuildTests.java
server/src/test/java/org/opensearch/LegacyESVersionTests.java
server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestTests.java
server/src/test/java/org/opensearch/search/slice/SliceBuilderTests.java
test/framework/src/test/java/org/opensearch/test/rest/yaml/section/SetupSectionTests.java

This PR removes `LegacyESVersion.V_6_3_x` constants including all
pre-release versions and bug fixes.
closes #1688

Remove LegacyESVersion.V_6_3_x constants

---

.gitattributes

Backporting #1727 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1713

[Backport 1.x] Updating .gitattributes for additional file types

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeFilters.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeFiltersTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java

Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
Instead of recreating the filters from the difference passed to settings update consumer, existing filters are updated to preserve original settings as well
#1716

Fixing allocation filters to persist existing state on settings update

---

distribution/docker/build.gradle
qa/remote-clusters/build.gradle

the `composeUp` needs `preProcessFixture` to be executed before, otherwise the folders:
```
distribution/docker/build/logs/1
distribution/docker/build/logs/2
```
won't exists and will be created by `Docker` under `root` user:
```
drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:40 classes
drwxrwxr-x 4 user.user user.user 4.0K Nov 30 10:03 docker
drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:38 forbidden-apis-config
drwxrwxr-x 3 user.user user.user 4.0K Nov 29 15:40 generated
drwxrwxr-x 2 user.user user.user 4.0K Nov 29 15:45 heapdump
drwxr-xr-x 4 root         root         4.0K Dec 14 11:24 logs
drwxrwxr-x 2 user.user user.user 4.0K Nov 29 15:44 markers
drwxrwxrwx 2 user.user user.user 4.0K Dec 13 09:20 repo
drwxrwxr-x 4 user.user …
```

Gradle clean failing after a failed gradle check, folders created by Docker under 'root' user

---

buildSrc/src/test/java/org/opensearch/gradle/precommit/UpdateShasTaskTests.java

This unit test asserts that a SHA file for a groovy dependency gets
created. However, a SHA file for javaparser-core also gets created in
the same directory. For some reason, builds were failing on my machine
because `Files::list` was returning the javaparser-core file first. I
don't believe there are any ordering guarantees with that API, so I
relaxed the assertion to not depend on ordering.

Ignore file order in test assertion

---

buildSrc/src/test/java/org/opensearch/gradle/precommit/UpdateShasTaskTests.java

This unit test asserts that a SHA file for a groovy dependency gets
created. However, a SHA file for javaparser-core also gets created in
the same directory. For some reason, builds were failing on my machine
because `Files::list` was returning the javaparser-core file first. I
don't believe there are any ordering guarantees with that API, so I
relaxed the assertion to not depend on ordering.

[Backport] [1.x] Ignore file order in test assertion (#1755)

---

modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/netty4/OpenSearchLoggingHandlerIT.java
plugins/transport-nio/src/internalClusterTest/java/org/opensearch/transport/nio/NioTransportLoggingIT.java
server/src/internalClusterTest/java/org/opensearch/action/admin/indices/rollover/RolloverIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/allocation/ClusterRerouteIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/single/SingleNodeDiscoveryIT.java
server/src/test/java/org/opensearch/bootstrap/MaxMapCountCheckTests.java
server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java
server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
server/src/test/java/org/opensearch/common/settings/SettingTests.java
server/src/test/java/org/opensearch/common/settings/SettingsFilterTests.java
server/src/test/java/org/opensearch/discovery/HandshakingTransportAddressConnectorTests.java
server/src/test/java/org/opensearch/gateway/IncrementalClusterStateWriterTests.java
server/src/test/java/org/opensearch/gateway/PersistedClusterStateServiceTests.java
server/src/test/java/org/opensearch/http/AbstractHttpServerTransportTests.java
server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
server/src/test/java/org/opensearch/transport/TcpTransportTests.java
server/src/test/java/org/opensearch/transport/TransportLoggerTests.java
test/framework/src/main/java/org/opensearch/test/MockLogAppender.java
test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
test/framework/src/test/java/org/opensearch/transport/nio/TestEventHandlerTests.java

The context of this change is that some unit and integration tests make assertions about
the logging behavior of the code under test by adding a MockLogAppender to the
static (i.e. global) logging system to collect logging events. On top of this, the base
test class `OpenSearchTestCase` has an `@After` method that asserts that the logging
system itself did not emit any errors indicating a problem with the logging setup. A
problem occurs if a MockLogAppender is added to a logger before it is started or is
stopped before it is removed. A non-started appender can cause the logger to emit and
fail therefore fail a test. The specific error I've observed is "Attempted to append to non-started
appender mock". When running a single test in isolation, there will not be a problem
regardless of the …

Use try-with-resources with MockLogAppender

---

modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/netty4/OpenSearchLoggingHandlerIT.java
plugins/transport-nio/src/internalClusterTest/java/org/opensearch/transport/nio/NioTransportLoggingIT.java
server/src/internalClusterTest/java/org/opensearch/action/admin/indices/rollover/RolloverIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/allocation/ClusterRerouteIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/single/SingleNodeDiscoveryIT.java
server/src/test/java/org/opensearch/bootstrap/MaxMapCountCheckTests.java
server/src/test/java/org/opensearch/cluster/NodeConnectionsServiceTests.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java
server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
server/src/test/java/org/opensearch/common/settings/SettingTests.java
server/src/test/java/org/opensearch/common/settings/SettingsFilterTests.java
server/src/test/java/org/opensearch/discovery/HandshakingTransportAddressConnectorTests.java
server/src/test/java/org/opensearch/gateway/IncrementalClusterStateWriterTests.java
server/src/test/java/org/opensearch/gateway/PersistedClusterStateServiceTests.java
server/src/test/java/org/opensearch/http/AbstractHttpServerTransportTests.java
server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java
server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
server/src/test/java/org/opensearch/transport/TcpTransportTests.java
server/src/test/java/org/opensearch/transport/TransportLoggerTests.java
test/framework/src/main/java/org/opensearch/test/MockLogAppender.java
test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
test/framework/src/test/java/org/opensearch/transport/nio/TestEventHandlerTests.java

I previously added a helper that started a MockLogAppender to ensure it
was never added to a Logger before it was started. I subsequently found
the opposite case in RolloverIT.java where the appender was stopped
before it was closed, therefore creating a race where a concurrently
running test in the same JVM could cause a logging failure. This seems
like a really easy mistake to make when writing a test or introduce when
refactoring a test. I've made a change to use try-with-resources to
ensure that proper setup and teardown is done. This should make it much
harder to introduce this particular test bug in the future.
Unfortunately, it did involve touching a lot of files. The changes here
are purely structural to leverage try-with-resources; no testing logic
has been changed. …

[Backport] [1.x] Use try-with-resources with MockLogAppender (#1595)

---

plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepositoryPlugin.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java
plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java

The Azure Repository Plugin supports only single timeout setting which translates to operation timeout in Azure SDK v12. However, there are connect/write/response/read timeouts which could be fine tuned for a particular environment but there is no convenient way to configure those right now.
The following new settings have been introduced:
```
azure.client.<client>.connect.timeout
azure.client.<client>.write.timeout
azure.client.<client>.read.timeout
azure.client.<client>.response.timeout
```
Closes https://github.com/opensearch-project/OpenSearch/issues/1762 …

[plugin] repository-azure: add configuration settings for connect/write/response/read timeouts

---

plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepositoryPlugin.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java
plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/1789 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1762

[Backport] [1.x] [plugin] repository-azure: add configuration settings for connect/write/response/read timeouts (#1789)

---

distribution/docker/build.gradle
qa/remote-clusters/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/1726 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1675

[Backport] [1.x] Gradle clean failing after a failed gradle check, folders created by Docker under 'root' user (#1726)

---

server/src/internalClusterTest/java/org/opensearch/cluster/ClusterHealthIT.java

Increase master node timeout causing intermittent test failures.
[[ClusterHealthIT:testHealthOnMasterFailover Failure 1693]](https://github.com/opensearch-project/OpenSearch/issues/1693)

[Tests] ClusterHealthIT:testHealthOnMasterFailover - Increase master node timeout

---

buildSrc/src/main/java/org/opensearch/gradle/test/rest/RestTestUtil.java

Using opensearch.yaml-rest-test Gradle plugin outside of the OpenSearch core (fe, in plugins), for example yamlRestTest, fails with the following exception:
```
> Task :yamlRestTest
org.opensearch.path.to.plugin.RenameClientYamlTestSuiteIT > initializationError FAILED
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Layout
```
Since the log4j-core is declared as optional, it is not being picked up. Adding it as an explicit dependency does not solve the problem either (see please opensearch-project/opensearch-plugin-template-java#16 for more details) because the task uses dedicated configuration `yamlRestTestImplementation` and only its dependencies.
Closes https://github.com/opensearch-project/OpenSearch/issues/1814
By …

RestIntegTestTask fails because of missed log4j-core dependency

---

buildSrc/src/main/java/org/opensearch/gradle/test/rest/RestTestUtil.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/1815 to 1.x
Using opensearch.yaml-rest-test Gradle plugin outside of the OpenSearch core (fe, in plugins), for example yamlRestTest, fails with the following exception:
```
> Task :yamlRestTest
org.opensearch.path.to.plugin.RenameClientYamlTestSuiteIT > initializationError FAILED
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Layout
```
Since the log4j-core is declared as optional, it is not being picked up. Adding it as an explicit dependency does not solve the problem either (see please opensearch-project/opensearch-plugin-template-java#16 for more details) because the task uses dedicated configuration `yamlRestTestImplementation` and only its …

[Backport] [1.x] RestIntegTestTask fails because of missed log4j-core dependency (#1815)

---

buildSrc/src/main/java/org/opensearch/gradle/test/rest/RestTestUtil.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/1815 to 1.2
Using opensearch.yaml-rest-test Gradle plugin outside of the OpenSearch core (fe, in plugins), for example yamlRestTest, fails with the following exception:
```
> Task :yamlRestTest
org.opensearch.path.to.plugin.RenameClientYamlTestSuiteIT > initializationError FAILED
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Layout
```
Since the log4j-core is declared as optional, it is not being picked up. Adding it as an explicit dependency does not solve the problem either (see please opensearch-project/opensearch-plugin-template-java#16 for more details) because the task uses dedicated configuration `yamlRestTestImplementation` and only its …

[Backport] [1.2] RestIntegTestTask fails because of missed log4j-core dependency (#1815)

---

server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java

Although there has been a commit https://github.com/opensearch-project/OpenSearch/commit/baa10b9b203d20e585471d93b9aa538a3f681585 that aimed to fix the test failure in #1567, there is still a failure reported in https://github.com/opensearch-project/OpenSearch/issues/1567#issuecomment-996021163.
The PR gives another try to fix the unit test `testFailsHealthOnHungIOBeyondHealthyTimeout()` in class `FsHealthServiceTests` by extending the timeout period again, based on the idea in https://github.com/opensearch-project/OpenSearch/issues/1567#issuecomment-989021906.
- Increase the max waiting time between cancelling the IO hanging and checking the File System health status. Increase the `3x` multiplier to `4x` that applied to `refreshInterval`.
For more detail about the past attempt to fix the …

[TEST] Fix FsHealthServiceTest by increasing the timeout period before checking the FS health after restoring the FS status

---

test/fixtures/azure-fixture/build.gradle
test/fixtures/gcs-fixture/build.gradle
test/fixtures/krb5kdc-fixture/build.gradle
test/fixtures/s3-fixture/build.gradle

Fixed (and checked) the repeated executions of:
```
gradle :plugins:repository-gcs:check
gradle :plugins:repository-azure:check
gradle :plugins:repository-hdfs:check
gradle :plugins:repository-s3:check
```
Closes https://github.com/opensearch-project/OpenSearch/issues/1821

Execution failed for task ':test:fixtures:azure/s3/hdfs/gcs-fixture:composeDown'

---

test/fixtures/azure-fixture/build.gradle
test/fixtures/gcs-fixture/build.gradle
test/fixtures/krb5kdc-fixture/build.gradle
test/fixtures/s3-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/1824 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1821

[Backport] [1.x] Execution failed for task ':test:fixtures:azure/s3/hdfs/gcs-fixture:composeDown' (#1824)

---

modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java

Netty4HttpServerTransport uses es-http-channel and es-http-server-channel as an attribute key for netty channel.
They are replaced with `opensearch-`.
- #1795
Signed-off-by: Shinsuke Sugaya <shinsuke@apache.org>

Replace with opensearch-http-channel and opensearch-http-server-channel

---

distribution/tools/plugin-cli/build.gradle

We have seen this issue before on `main` (and fixed it as part of https://github.com/opensearch-project/OpenSearch/pull/1358/files#diff-1a51c2f0353076590c29fbdc710bcdf9289345866c2497ecce07f91819fe6dc9R52), but seems like `1.x` is also running into this problem from time to time.
Closes https://github.com/opensearch-project/OpenSearch/issues/1826

Attempt to fix "Intermittent java.lang.Exception: Suite timeout exceeded (>= 1200000 msec)

---

server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateResponse.java
server/src/main/java/org/opensearch/action/delete/DeleteRequest.java
server/src/main/java/org/opensearch/action/index/IndexRequest.java
server/src/main/java/org/opensearch/action/support/IndicesOptions.java
server/src/main/java/org/opensearch/cluster/RestoreInProgress.java
server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java
server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
server/src/main/java/org/opensearch/index/get/GetResult.java
server/src/main/java/org/opensearch/index/mapper/AbstractShapeGeometryFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/LegacyGeoShapeFieldMapper.java
server/src/main/java/org/opensearch/monitor/os/OsInfo.java
server/src/main/java/org/opensearch/search/SearchHits.java
server/src/main/java/org/opensearch/search/SearchSortValues.java
server/src/test/java/org/opensearch/BuildTests.java
server/src/test/java/org/opensearch/LegacyESVersionTests.java
server/src/test/java/org/opensearch/action/admin/cluster/state/ClusterStateRequestTests.java
server/src/test/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelperTests.java
server/src/test/java/org/opensearch/index/mapper/ExternalMapper.java
server/src/test/java/org/opensearch/index/query/GeoShapeQueryBuilderTests.java

This PR removes the `LegacyESVersion.V_6_6_x` constants and all their usages.
Part of #1674 

Remove LegacyESVersion.V_6_6_x constants

---

modules/reindex/src/main/java/org/opensearch/index/reindex/TransportUpdateByQueryAction.java
qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
qa/translog-policy/src/test/java/org/opensearch/upgrades/TranslogPolicyIT.java
server/src/main/java/org/opensearch/Build.java
server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/action/admin/indices/mapping/put/PutMappingRequest.java
server/src/main/java/org/opensearch/action/admin/indices/stats/ShardStats.java
server/src/main/java/org/opensearch/action/search/SearchRequest.java
server/src/main/java/org/opensearch/cluster/ClusterState.java
server/src/main/java/org/opensearch/cluster/action/shard/ShardStateAction.java
server/src/main/java/org/opensearch/cluster/block/ClusterBlock.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/query/InnerHitBuilder.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTranslogOperationsRequest.java
server/src/main/java/org/opensearch/search/SearchHit.java
server/src/main/java/org/opensearch/search/aggregations/InternalAggregations.java
server/src/main/java/org/opensearch/search/aggregations/metrics/TopHitsAggregationBuilder.java
server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
server/src/test/java/org/opensearch/BuildTests.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java
server/src/test/java/org/opensearch/LegacyESVersionTests.java
server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
server/src/test/java/org/opensearch/cluster/action/shard/ShardStateActionTests.java
server/src/test/java/org/opensearch/cluster/block/ClusterBlockTests.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/indices/TermsLookupTests.java

This commit removes the LegacyESVersion.V_6_7_x constants and their usages.
Part of #1674

Remove LegacyESVersion.V_6_7_x constants

---

.github/workflows/backport.yml

This should fix the backport workflow failures since the branch protection is relaxed in PR #1816. I tried with the similar set of permissions on my repo and the workflow ran successfully https://github.com/VachaShah/TestGithubActions/runs/4706516920?check_suite_focus=true. The default permissions are  `read` for all the scopes if not specified, for example: https://github.com/opensearch-project/OpenSearch/runs/4702581161?check_suite_focus=true
Note: I will add a backport label to a PR in this repo to verify.
#1712  …

Fixing auto backport workflow

---

.github/workflows/version.yml

Adds a workflow that increments the version of OpenSearch whenever a new X.Y.Z tag is pushed. 
To test this I pushed a 1.2.4 tag to my branch, `git tag -d 1.2.4 ; git tag 1.2.4 ; git push origin :1.2.4 ; git push origin --tags`. That's what would happen if we were to release 1.2.4 tomorrow.
- Successful run: https://github.com/dblock/OpenSearch/actions/runs/1631531500
- PRs generated: 
https://github.com/dblock/OpenSearch/pull/2
https://github.com/dblock/OpenSearch/pull/3
https://github.com/dblock/OpenSearch/pull/6
The new workflow produces 3 PRs similar to https://github.com/opensearch-project/OpenSearch/pull/1758 and backport PRs into main, and 1.x. It removes the manual steps that start triggering the whole automation to produce the next patch …

Auto-increment next development iteration.

---

distribution/archives/build.gradle
distribution/archives/darwin-arm64-tar/build.gradle
distribution/archives/no-jdk-darwin-arm64-tar/build.gradle
distribution/build.gradle
modules/lang-painless/src/main/java/org/opensearch/painless/Def.java
server/src/main/java/org/opensearch/plugins/Plugin.java
server/src/main/java/org/opensearch/script/AggregationScript.java
settings.gradle

Signed-off-by: Cédric Pelvet <cedric.pelvet@gmail.com>
Add darwin-arm64-tar and no-jdk-darwin-arm64-tar flavors for the archives distribution.
#1667

Add darwin-arm64-tar and no-jdk-darwin-arm64-tar archive distributions.

---

server/src/main/java/org/opensearch/Build.java

This PR removes unnecessary serialization of unused flavor variable in build metadata from V_1_3_0+

[1.x] Remove remaining Flavor Serialization (#1751)

---

server/src/main/java/org/opensearch/Build.java

Fixing build failures after Flavor Serialization backport (https://github.com/opensearch-project/OpenSearch/pull/1757)
Multiple builds are failing:
- https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1804.log
- https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1801.log
- ...

Fixing build failures after Flavor Serialization backport

---

server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/Version.java
server/src/main/java/org/opensearch/transport/TransportHandshaker.java
server/src/test/java/org/opensearch/LegacyESVersionTests.java
server/src/test/java/org/opensearch/VersionTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/common/lucene/uid/VersionsTests.java
server/src/test/java/org/opensearch/common/rounding/RoundingDuelTests.java

This commit removes all usages of the `LegacyESVersion.V_6_8_x` constants from the codebase.
Part of #1674

Remove LegacyESVersion.V_6_8_x constants

---

server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/profile/AbstractProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/ContextualProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/Profilers.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/query/InternalProfileCollector.java
server/src/main/java/org/opensearch/search/profile/query/InternalProfileComponent.java
server/src/main/java/org/opensearch/search/profile/query/InternalQueryProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ProfileScorer.java
server/src/main/java/org/opensearch/search/profile/query/ProfileWeight.java
server/src/main/java/org/opensearch/search/profile/query/QueryProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/query/QueryProfiler.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java

Part of https://github.com/opensearch-project/OpenSearch/pull/1500, it was suggested to split the initial pull request into smaller chunks to simplify the review. This one extracts changes related to profiler support.

Concurrent Searching (Experimental): modify profiling implementation to support concurrent data collection

---

buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java

Attempt to fix `:test:fixtures:s3-fixture:composeUp` fails due to HTTP connection issue by introducing configurable property `dockerComposeHttpTimeout` with default value of 120 seconds. To change it, the standard `ExtraPropertiesExtension`  is used:
```
ext {
dockerComposeHttpTimeout = 180
}
```
The timeout seems to be taken into account (simulated failures are below);
```
ERROR: for minio-fixture-other  HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out. (read timeout=180)
ERROR: for minio-fixture  HTTPConnectionPool(host='127.0.0.1', port=2375): Read timed out. (read timeout=180)
An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of …
```

[WIP] Attempt to fix :test:fixtures:s3-fixture:composeUp fails due to HTTP connection issue

---

server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java

This test fails due to equality check of majors between OpenSearch Version 1.x and LegacyESVersion 7.x. They should be equivalent but in this case the check fails and LegacyVersion.v6.8.x is chosen which was removed in 52508d5.
This change fixes the comparison logic by using `Version.compareMajor` method instead.
Discovered in #1866
Log - https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1837.log
Signed-off-by: …

Use Version.compareMajor instead of using equals operator

---

server/src/main/java/org/opensearch/Version.java
server/src/test/java/org/opensearch/VersionTests.java

Latest release is `1.2.3` 
Hence, only last major (`2.0.0`), last minor(`1.3.0`) and (`1.2.4`) can be unreleased
Resolves #1855 

Remove unwanted unreleased versions

---

buildSrc/build.gradle
buildSrc/src/integTest/groovy/org/opensearch/gradle/OpenSearchTestBasePluginFuncTest.groovy
buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
buildSrc/src/testKit/opensearch.build/build.gradle
buildSrc/src/testKit/testingConventions/build.gradle
buildSrc/src/testKit/thirdPartyAudit/build.gradle
settings.gradle

On February 3 2021, JFrog [announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) the shutdown of JCenter. Later on April 27 2021, an update was provided that the repository will only be read only and new package and versions are no longer accepted on JCenter.  This means we should no longer use JCenter for our central artifacts repository.
This change replaces JCenter with Maven Central as per the Gradle recommendation - https://blog.gradle.org/jcenter-shutdown
[#1456](https://github.com/opensearch-project/opensearch-build/issues/1456)
For more …

[Backport 1.x] Replace JCenter with Maven Central. (#1057)

---

modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/netty4/OpenSearchLoggingHandlerIT.java

Attempt to fix `o.o.transport.netty4.OpenSearchLoggingHandlerIT` fails w/ stack overflow by hardening test expectation patterns. I was not able to reproduce the issue locally but suspects are: `Log4j` (specific message) and our own `MockLogAppender.LoggingExpectation`. At least, if the issue continues to manifest, we should be able to exclude `MockLogAppender.LoggingExpectation` from suspects.
Possibly closes https://github.com/opensearch-project/OpenSearch/issues/1767 …

Attempt to fix o.o.transport.netty4.OpenSearchLoggingHandlerIT fails w/ stack overflow by hardening test expectation patterns

---

server/src/main/java/org/opensearch/transport/InboundHandler.java
server/src/test/java/org/opensearch/transport/InboundHandlerTests.java

Most commonly backward incompatible changes to APIs like stats can cause ser/de over the wire to fail. A bit more details regarding the (de)serialization handling inside `InboundHandler`:
> 1) If there is a serialization bug it would manifest itself in the `InboundHandler#messageReceived` causing to throw an `IllegalStateException`. 
Interestingly, it is only raised when input stream has **unconsumed bytes**, the case when stream has less bytes than needed to reconstruct the payload is not classified as serialization issue (resulting in `java.io.EOFException`s). More importantly, there is a difference if the message is request or response:
- if the message is `request` than all exceptions are caught inside `handleRequest`, the exceptions …

[BUG] Serialization bugs can cause node drops

---

server/src/test/java/org/opensearch/common/network/InetAddressesTests.java

There is a real possibility that loopback interface has no IPv6 address assigned (fe IPv6 is disabled, ...) but the test blindly assumes that loopback interface always has IPv6 address and as such, fails with ` java.net.UnknownHostException: no scope_id found` if that is not the case.
```
org.opensearch.common.network.InetAddressesTests > testForStringIPv6WithScopeIdInput FAILED
243 | java.net.UnknownHostException: no scope_id found
244 | at __randomizedtesting.SeedInfo.seed([D7519A98383FCD86:F581D4F66795B2D5]:0)
245 | at java.base/java.net.Inet6Address.deriveNumericScope(Inet6Address.java:538)
246 | at java.base/java.net.Inet6Address$Inet6AddressHolder.init(Inet6Address.java:247)
247 | at …
```

Fixing org.opensearch.common.network.InetAddressesTests.testForStringIPv6WithScopeIdInput

---

server/src/test/java/org/opensearch/common/network/InetAddressesTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/1913 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1887

[Backport] [1.x] Fixing org.opensearch.common.network.InetAddressesTests.testForStringPv6WithScopeIdInput (#1913)

---

server/src/main/java/org/opensearch/transport/TransportHandshaker.java
test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java

This PR fixes `TransportHandshaker` to send a spoofed Legacy 7.10.2 mincompat
version to ensure OpenSearch 2.x nodes can join a Legacy 7.10.x cluster for
rolling upgrade support. Without this change 7.10.x and OpenSearch 2.x mixed
cluster bwc tests were failing.

[BWC] Ensure 2.x compatibility with Legacy 7.10.x

---

server/src/main/java/org/opensearch/LegacyESVersion.java
server/src/main/java/org/opensearch/Version.java
server/src/test/java/org/opensearch/LegacyESVersionTests.java
server/src/test/java/org/opensearch/VersionTests.java
test/framework/src/main/java/org/opensearch/test/VersionUtils.java
test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java

In preparation for removing all LegacyESVersion support by 3.0; this PR
largely refactors the LegacyESVersion test logic from the OpenSearch Version
test logic into an independent test class. This PR also updates Version.fromString
to ensure a proper legacy version is returned when major is > 3 (to support
legacy yaml test and build scripts).
Note that bwc w/ legacy versions are still supported so some cross compatibility
testing is retained in the Version test class.

[1x] Backport Refactor LegacyESVersion tests from Version tests (#1662)

---

server/src/internalClusterTest/java/org/opensearch/search/sort/SortFromPluginIT.java
server/src/main/java/org/opensearch/plugins/SearchPlugin.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
server/src/main/java/org/opensearch/search/sort/SortBuilder.java
server/src/main/java/org/opensearch/search/sort/SortParser.java
server/src/test/java/org/opensearch/search/sort/SortBuilderTests.java
server/src/test/java/org/opensearch/search/sort/plugin/CustomSortBuilder.java
server/src/test/java/org/opensearch/search/sort/plugin/CustomSortPlugin.java

Add the ability for plugin authors to add custom sort builders.  Backport of #1856 

[1.x] Make SortBuilders pluggable (#1856)

---

server/src/main/java/org/opensearch/plugins/SearchPlugin.java

[Back port] Expand SearchPlugin javadocs. (#1909)

---

server/src/internalClusterTest/java/org/opensearch/index/ShardIndexingPressureSettingsIT.java

The change adds wait for outstanding requests to avoid failure due to occasional processing delays in previous requests.
[1843](https://github.com/opensearch-project/OpenSearch/issues/1843)

[Bug] Wait for outstanding requests to complete

---

.github/workflows/backport.yml

Fixes the issue for custom branch name for auto backport workflow. This will help in defining permissions properly for branches. For now, I have added the custom branch name changes in my [fork](https://github.com/VachaShah/backport) of the GHA repo, hence I am using a release version from my forked repo. Once the concerned change is merged to the backport GHA repo [tibdex/backport](https://github.com/tibdex/backport), I will update the GHA repo name.
After this PR is merged, I will verify it by running the backport workflow on a PR.
#1712  …

Using custom branch name for auto backporting PRs

---

server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTestCase.java
server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java
server/src/test/java/org/opensearch/cluster/routing/RoutingNodeTests.java
server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java

The primary shards are always picked up first from node for shard movement. That is achieved by bucketing the shards into primary/replicas and iterating over primaries first.
#1349

Prioritize primary shard movement during shard allocation

---

server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java

Removing lingering transport client references.
Fixes gradle precommit.
#1954 

Removing lingering transportclient references

---

.github/workflows/backport.yml

Updating `pull_request` to `pull_request_target` to allow the permissions for the GITHUB_TOKEN because even with the permissions block added to the workflow file, the permissions in the [workflow run](https://github.com/opensearch-project/OpenSearch/runs/4887125705?check_suite_focus=true) default to read on `pull_request`. Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target …

Using pull_request_target in place of pull_request

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java

Add hook to execute custom logic before the integ test starts. 
This is required for a workaround to enable the jacoco code coverage for Integ Tests.
Related PR: https://github.com/opensearch-project/cross-cluster-replication/pull/284
[[1926]](https://github.com/opensearch-project/OpenSearch/issues/1928)

Add hook to execute custom logic before Integ test task starts

---

qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

Soft Deletes have been enabled by default since Legacy version 7.0 and made
mandatory in Version 2.0.0. This PR refactors the InternalEngine to always
use soft-deletes. It is a follow on to making soft deletes mandatory in 2.0.0.

[Refactor] InternalEngine to always use soft deletes

---

server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
server/src/test/java/org/opensearch/index/query/IntervalQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/WildcardIntervalsSourceProviderTests.java

Add support for setting the max expansions on a wildcard interval.
The default value is still 128 and the max value is bounded by
`BooleanQuery.getMaxClauseCount()`.
#1857 

Add max_expansions option to wildcard interval

---

TESTING.md

Signed-off-by: Dave Lago <davelago@amazon.com>
Updated testing guide to clarify guidance on when to use the different testing classes. This PR is intended to be a vehicle for discussion as this will become the guidance for new tests.
N/A

Modified TESTING instructions to clarify use of testing classes

---

server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
server/src/main/java/org/opensearch/index/IndexingPressureService.java
server/src/test/java/org/opensearch/index/IndexingPressureServiceTests.java

Delay the ramBytesUsed computation for Indexing requests on the coordinator until reached a point, where absolutely necessary for IndexingPressure or ShardIndexingPressure.
This optimises the additional request size calculation, which otherwise would have been no-op. See (#1560)
The ramBytesUsed computations are done repeatedly at multiple places (replica, primary and coordinator), and are present even in the older version of IndexingPressure. Here in OS1.2 for every request overhead would be the request size computations for the number of documents in the batch. Given that this call has neither showed up in any CPU profiling data and was neither was called out as regression when first added in the indexing path during 7.9 release, this might not be the smoking gun, however this …

Delay the request size calculation until required by the indexing pressure framework

---

server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
server/src/test/java/org/opensearch/index/query/IntervalQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/WildcardIntervalsSourceProviderTests.java

Add support for setting the max expansions on a wildcard interval.
The default value is still 128 and the max value is bounded by
`BooleanQuery.getMaxClauseCount()`.
1x backport of #1916 

[backport] add max expansion support to wildcard interval

---

server/src/main/java/org/opensearch/search/aggregations/bucket/composite/BinaryValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceConfig.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceParserHelper.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DateHistogramValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DoubleValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GeoTileGridValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GeoTileValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GlobalOrdinalValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/HistogramValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/LongValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/TermsValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/missing/MissingOrder.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationBuilderTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesCollectorQueueTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/SingleDimensionValuesSourceTests.java

Support _first and _last parameter for missing bucket ordering in composite aggregation.
If missing_order is "_first" or "_last", regardless order, missing_bucket is at first or last respectively. for example, the following query will sort `product` asc and null bucket will be placed at last.
```
{
"size": 0,
"aggs": {
"my_buckets": {
"composite": {
"sources": [
{
"product_name": {
"terms": {
"field": "product",
"missing_bucket": true,
"missing_order": "last",
"order": "asc"
}
}
}
]
}
}
}
}
```
#1899
- [x ] New functionality includes testing.
- [x ] New functionality has javadoc added
For more …

Support _first and _last parameter for missing bucket ordering in composite aggregation

---

server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java

Change from 2x to 1.3 for wildcard interval max_expansion version check
since #1916 was backported.

Wildcard max_expansion version check update

---

server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/MergePolicyConfig.java
server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
server/src/test/java/org/opensearch/index/MergePolicySettingsTests.java

`max_merge_at_once_explicit` is removed in lucene 9 so this PR deprecates the corresponding index setting for removal in the next major release.

[Deprecate] index.merge.policy.max_merge_at_once_explicit

---

server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

The test `testClusterGreenAfterPartialRelocation` timed out while waiting for the cluster to become green. Increasing the timeout will help.
https://github.com/opensearch-project/OpenSearch/issues/1957

Added timeout to ensureGreen() for testClusterGreenAfterPartialRelocation

---

modules/analysis-common/src/test/java/org/opensearch/analysis/common/CompoundAnalysisTests.java
server/src/main/java/org/opensearch/index/analysis/AbstractIndexAnalyzerProvider.java
server/src/main/java/org/opensearch/index/analysis/AbstractTokenFilterFactory.java
server/src/main/java/org/opensearch/index/analysis/AbstractTokenizerFactory.java
server/src/main/java/org/opensearch/index/analysis/Analysis.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
server/src/test/resources/org/opensearch/index/analysis/test1.json
server/src/test/resources/org/opensearch/index/analysis/test1.yml

Removal of deprecated setting in #1978. 
Lucene 9 removes the ability to define an explicit version on an analysis
component so remove the the version parameter and deprecation warning
prohibiting users from explicitly setting versioned analyzers.

[Remove] Setting explicit version on analysis component

---

server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/MergePolicyConfig.java
server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
server/src/test/java/org/opensearch/index/MergePolicySettingsTests.java
server/src/test/java/org/opensearch/index/OpenSearchTieredMergePolicyTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Removal of deprecated parameter in #1981
Deprecated `max_merge_at_once_explicit` parameter is removed since it has been removed in lucene 9 and deprecated in opensearch 1.3

[Remove] index.merge.policy.max_merge_at_once_explicit

---

server/src/main/java/org/opensearch/common/settings/Setting.java

Fixing invalid Java code example in JavaDoc
Including several other minor typos in JavaDoc.
No code has been changed, just JavaDoc.

Fixing invalid Java code example in JavaDoc

---

server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

This PR is backport of PR #1974. It removes sort optimization code present in OpenSearch because from Lucence 8.10.1, Numeric sort optimization is already done in Lucene Comparators. Now Lucene also supports sort optimization with search_after queries.
#1570 

[Backport] Enabling Sort Optimization to make use of Lucene

---

distribution/docker/src/docker/Dockerfile

[BUG] Docker distribution builds are failing. Switching to http://vault.centos.org

---

server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/InternalCompositeTests.java

Fix bug introduce by #1942. InternalBucket compareKey method should use MissingOrder to decide null values's order
* Run CompositeAggregatorTests 100 times, `./gradlew ':server:test' -Dtests.iters=100 --tests "org.opensearch.search.aggregations.bucket.composite.CompositeAggregatorTests"`,  All Passed
* Run `./gradlew 'server:test'`, All Passed.
#1998

Fix composite aggregation failed test cases introduce by missing_order parameter (#1942)

---

distribution/docker/src/docker/Dockerfile

Backport of https://github.com/opensearch-project/OpenSearch/pull/2024 to the 1.2 branch.
https://github.com/opensearch-project/OpenSearch/issues/2023

[Backport 1.2] Docker distribution builds are failing. Switching to http://vault.centos.org

---

buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java

Upgrading Shadow gradle plugin to 7.1.2.
Shadow plugin is used for publishing jars
and this upgrades Log4J dependency for build.
Ref: https://github.com/johnrengelman/shadow/releases/tag/7.1.2

Upgrading Shadow plugin to 7.1.2

---

build.gradle
buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/util/Util.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Add support for reproducible builds
Reproducible builds is an initiative to create an independently-verifiable path from source to binary code [1]. This can be done by:
- Make all archive tasks in gradle reproducible by ignoring timestamp on files [2]
- Preserve the order in side the archives [2]
- Ensure GlobalBuildInfoPlugin.java use [SOURCE_DATE_EPOCH] when available
[SOURCE_DATE_EPOCH]: https://reproducible-builds.org/docs/source-date-epoch/
[1]: https://reproducible-builds.org/
[2]: https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
N/A
- [-] New functionality includes testing.
- [-] All tests pass
- [-] New functionality has javadoc added …

build: introduce support for reproducible builds

---

server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/MergePolicyConfig.java
server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
server/src/test/java/org/opensearch/index/MergePolicySettingsTests.java

Backport of #1981. max_merge_at_once_explicit is removed in lucene 9 so the index setting is deprecated for removal in the next major release.

[1x] Deprecate index.merge.policy.max_merge_at_once_explicit (#1981)

---

Vagrantfile
distribution/packages/src/common/env/opensearch
distribution/packages/src/deb/init.d/opensearch
distribution/packages/src/rpm/init.d/opensearch
distribution/src/bin/opensearch-env
distribution/src/bin/opensearch-env.bat
qa/os/src/test/java/org/opensearch/packaging/test/ArchiveTests.java
qa/os/src/test/java/org/opensearch/packaging/test/PackagingTestCase.java
qa/os/src/test/java/org/opensearch/packaging/test/WindowsServiceTests.java

Add OPENSEARCH_JAVA_HOME environment variable to override JAVA_HOME variable. The OPENSEARCH_JAVA_HOME takes the precedence of JAVA_HOME, which in turn takes the precedence over bundled JDK.
Closes https://github.com/opensearch-project/OpenSearch/issues/1872

[FEATURE] Add OPENSEARCH_JAVA_HOME env to override JAVA_HOME

---

Vagrantfile
distribution/packages/src/common/env/opensearch
distribution/packages/src/deb/init.d/opensearch
distribution/packages/src/rpm/init.d/opensearch
distribution/src/bin/opensearch-env
distribution/src/bin/opensearch-env.bat
qa/os/src/test/java/org/opensearch/packaging/test/ArchiveTests.java
qa/os/src/test/java/org/opensearch/packaging/test/PackagingTestCase.java
qa/os/src/test/java/org/opensearch/packaging/test/WindowsServiceTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/2001 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1872

[Backport] [1.x] [FEATURE] Add OPENSEARCH_JAVA_HOME env to override JAVA_HOME

---

distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java

The assertion error message was incorrectly requesting http protocol.
Too trivial to open a new ticket for.

Fix AssertionError message

---

buildSrc/build.gradle
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java

This reverts commit 8725061c15fac70a81d144ed2d79b09f5e1a2f7f.
Reverting this change as it needs Gradle 7+. 
Plugins/Libraries in OpenSearch bundle haven't migrated yet and will continue to run with Gradle 6.6.x line for rest of 1.x releases.
https://github.com/opensearch-project/opensearch-plugins/issues/107
https://github.com/opensearch-project/opensearch-build/issues/1587

Revert "Upgrading Shadow plugin to 7.1.2 (#2033) (#2037)"

---

modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/netty4/OpenSearchLoggingHandlerIT.java
test/framework/src/main/java/org/opensearch/test/MockLogAppender.java

This time no guesses, I was able to reproduce the issue. The Netty dumps raw messages (in hex) into logs and for some specific rare patterns (I have an example), the appender filter blows with `StrackOverflowError`. The change to appender filter to watch only for single line log statements (expressed in expectations) fixed the issue. 
Closes https://github.com/opensearch-project/OpenSearch/issues/1767

Another attempt to fix o.o.transport.netty4.OpenSearchLoggingHandlerIT fails w/ stack overflow

---

server/src/main/java/org/apache/lucene/queries/BinaryDocValuesRangeQuery.java
server/src/main/java/org/opensearch/action/search/TransportSearchHelper.java
server/src/main/java/org/opensearch/common/io/stream/BytesStreamInput.java
server/src/main/java/org/opensearch/common/util/ByteUtils.java
server/src/main/java/org/opensearch/index/fielddata/plain/AbstractBinaryDVLeafFieldData.java
server/src/main/java/org/opensearch/index/mapper/BinaryFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/BinaryRangeUtil.java
server/src/main/java/org/opensearch/index/mapper/RangeType.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/test/java/org/opensearch/common/io/stream/BaseStreamTests.java
server/src/test/java/org/opensearch/common/io/stream/ByteBufferStreamInputTests.java
server/src/test/java/org/opensearch/common/io/stream/BytesReferenceStreamInputTests.java
server/src/test/java/org/opensearch/common/io/stream/BytesStreamInputTests.java
server/src/test/java/org/opensearch/common/io/stream/FilterStreamInputTests.java
server/src/test/java/org/opensearch/common/io/stream/InputStreamStreamInputTests.java
server/src/test/java/org/opensearch/common/util/ByteUtilsTests.java
server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
server/src/test/java/org/opensearch/index/translog/TranslogTests.java

Lucene 9 changes from [BigEndian to LittleEndian](https://issues.apache.org/jira/browse/LUCENE-9047) in DataInput and DataOutput. The use of Lucene's Data IO classes are refactored in this PR to use StreamInput and StreamOutput which maintains the same method calls for backwards compatibility while preserving the byte order of the data.

[Refactor] Lucene DataInput and DataOutput to StreamInput and StreamOutput

---

server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java
server/src/main/java/org/opensearch/common/breaker/CircuitBreaker.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
server/src/test/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerServiceTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

RAM Accounting of segments is removed so remove the associated Accounting
circuit breaker.
relates #2029

[Remove] CircuitBreaker Accounting

---

.github/workflows/delete_backport_branch.yml

Workflow to automatically delete the branches created by the [backport action ](https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/backport.yml) of type `backport/*`.
I will backport this PR to release branches so that the auto delete runs on backport PRs created for those branches.
Part 2 of #1962 

Adding workflow to auto delete backport merged branches from backport workflow

---

server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/test/java/org/opensearch/index/query/IntervalQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/RegexpIntervalsSourceProviderTests.java

Add a regexp interval source provider so people can use regular
expressions inside of intervals queries.
#1858 

Add regexp interval source

---

.github/workflows/backport.yml

Using Github App token in the auto-backport workflow to trigger CI on auto-backport PRs since events created by `secrets.GITHUB_TOKEN` cannot trigger other workflows. Reference: https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250
Part 1 of #1962 

Using Github App to trigger CI for auto-backport

---

server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java

Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
The issue is caused due to one of the primary shard being initialized and some replica starts meanwhile. Hence, latch is counted down as half shards are already initialized. Making the check more robust by ensuring no primaries are initializing and not more than 20% of replicas have started on new nodes
#1957 
- [] New functionality has been documented.
- [] New functionality has javadoc added

Backport/backport 2048,2074 to 1.x

---

modules/percolator/src/main/java/org/opensearch/percolator/PercolatorFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/Mapper.java
server/src/main/java/org/opensearch/index/mapper/RangeFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/IpRangeFieldTypeTests.java
server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java

Update the same field using the same mapping with the same settings causes
```
"error" : {
{
"type" : "illegal_state_exception",
"reason" : "[index.version.created] is not present in the index settings for index with UUID [null]"
}
],
"type" : "illegal_state_exception",
"reason" : "[index.version.created] is not present in the index settings for index with UUID [null]"
},
"status" : 500
}
```
Closes https://github.com/opensearch-project/OpenSearch/issues/1921 …

 Mapping update for “date_range” field type is not idempotent

---

plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepositoryPlugin.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/ProxySettings.java
plugins/repository-azure/src/main/plugin-metadata/plugin-security.policy
plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java

Now to configure Azure plugin to use any proxy you need to set username/password using standard process variables:
Such settings have 2 main problems:
- Storing password this way is insecure
- In case of password leaking it is necessary to restart all nodes in the cluster
To avoid of a such problem username and password security settings were added 
Storing username/password in security settings is more secure compare to process settings and in case of any problem with username and password such security settings could be reloaded without restart of each node in the cluster.
Re-loadable security settings:
- `azure.client.*.proxy.username` - Proxy user name
- `azure.client.*.proxy.password` - Proxy user password …

Add proxy username and password settings for Azure repository plugin

---

server/src/main/java/org/opensearch/search/aggregations/bucket/composite/BinaryValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceConfig.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceParserHelper.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DateHistogramValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DoubleValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GeoTileGridValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GeoTileValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GlobalOrdinalValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/HistogramValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/LongValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/TermsValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/missing/MissingOrder.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationBuilderTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesCollectorQueueTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/InternalCompositeTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/composite/SingleDimensionValuesSourceTests.java

Backporting #1942 and #2005 to 1.x branch.
Passed,  `./gradlew ':server:test' -Dtests.iters=100 --tests "org.opensearch.search.aggregations.bucket.composite.CompositeAggregatorTests"` 
Passed, `./gradlew precommit`
#1899 
- [x ] New functionality has javadoc added

[Backport 1.x] Support first and last parameter for missing bucket ordering in composite aggregation

---

.github/dependabot.yml
.github/workflows/dependabot_pr.yml

This PR fixes dependabot integrations:
1. Updates the paths for the nested directories so all the `build.gradle` can be scanned.
2. Adds a workflow for running on dependabot PRs to run `./gradlew updateSHAs` and `./gradlew spotlessApply` on dependabot generated PRs since dependabot only updates the version in the `build.gradle`.
Note: I tried these updates on my fork and dependabot successfully opened PRs and the `dependabot_pr` workflow successfully updated them with the updateSHAs and spotless (if required). https://github.com/VachaShah/OpenSearch/pulls
The current open pr limit is being set to 1, once the PRs open correctly with the auto commits (along with CI triggers), I will go and update the limits to 10.
#1897  …

Dependabot fix and pr actions

---

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceBuilder.java
server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java

1. Adjust  version to 1.3.0.0 after backport PR #2049 merged.
2. Test Passed.
2.1. `./gradlew precommit`
2.2.`./gradlew ':server:test' -Dtests.iters=100 --tests "org.opensearch.search.aggregations.bucket.composite.CompositeAggregatorTests"`
2.3.`./gradlew ':qa:mixed-cluster:v1.3.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT"`
3. Add bwc test for missing_order.
#2143.

Adjust version after backport to 1.3.0.0

---

plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageClientSettings.java
plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStoragePlugin.java
plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageService.java
plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/ProxySettings.java
plugins/repository-gcs/src/main/plugin-metadata/plugin-security.policy
plugins/repository-gcs/src/test/java/org/opensearch/repositories/gcs/GoogleCloudStorageClientSettingsTests.java
plugins/repository-gcs/src/test/java/org/opensearch/repositories/gcs/GoogleCloudStorageServiceTests.java

Now to configure GCS plugin to use any proxy you need to set standard process variables:
- `proxyHost`
- `socksProxyHost`
- `proxyPort`
- `proxyUser` 
- `proxyPassword`
with proxy types prefix. 
Such settings have 2  main problems:
- Storing password this way is insecure
- In case of password leaking it is necessary to restart all nodes in the cluster
To avoid of a such problem all proxy settings were added to OS settings and security settings
Storing username/password in security settings is more secure compare to process settings and in case of any problem with username and password such security settings could be reloaded without restart of each node in the cluster.
Re-loadable security settings:
- `gcs.client.*.proxy.username` - Proxy user name
- `gcs.client.*.proxy.password` - Proxy …

Add proxy settings for GCS repository plugin

---

plugins/mapper-annotated-text/src/test/java/org/opensearch/index/mapper/annotatedtext/AnnotatedTextFieldTypeTests.java
rest-api-spec/src/main/resources/rest-api-spec/test/search/230_interval_query.yml
server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
server/src/main/java/org/opensearch/index/query/IntervalBuilder.java
server/src/main/java/org/opensearch/index/query/IntervalMode.java
server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
server/src/test/java/org/opensearch/index/query/CombineIntervalsSourceProviderTests.java
server/src/test/java/org/opensearch/index/query/IntervalBuilderTests.java
server/src/test/java/org/opensearch/index/query/IntervalQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/MatchIntervalsSourceProviderTests.java

This commit exposes Intervals.unorderedNoOverlaps (LUCENE-8828).  This commit does bwc checks against `Version.V_1_3_0` assuming it will be backported if merged.
#2053 

Support unordered non-overlapping intervals

---

modules/parent-join/src/test/java/org/opensearch/join/mapper/ParentJoinFieldMapperTests.java
server/src/internalClusterTest/java/org/opensearch/search/morelikethis/MoreLikeThisIT.java
server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetFieldMappingsResponse.java
server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsResponse.java
server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
server/src/main/java/org/opensearch/cluster/action/index/MappingUpdatedAction.java
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/MappingMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
server/src/main/java/org/opensearch/index/mapper/MapperService.java
server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
server/src/test/java/org/opensearch/index/mapper/DynamicTemplatesTests.java
server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java
server/src/test/java/org/opensearch/index/query/IdsQueryBuilderTests.java
server/src/test/resources/org/opensearch/index/mapper/dynamictemplate/simple/test-mapping.json
server/src/test/resources/org/opensearch/index/mapper/simple/test-mapping.json

Default mappings were deprecated in Legacy version 6x and cannot be added to
indexes created in legacy 7+ or any version of OpenSearch. All support for
default mappings are removed for OpenSearch 2+.
relates #1674

[Remove] Default Mapping

---

modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/ConcatenateGraphTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/ConcatenateGraphTokenFilterFactoryTests.java

Lucene has a ConcatenateGraphFilter that can concatenate tokens from a TokenStream
to create a single token (or several tokens that have the same position if
input TokenStream is a graph).
The change is to enable that ConcatenateGraphFilter by adding a Factory.
Signed-off-by: Mau Bach Quang <quangmaubach@gmail.com>
Add Factory to enable Lucene's ConcatenateGraphFilter.
Resolves #1278 

Add Factory to enable Lucene ConcatenateGraphFilter (#1278)

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/230_interval_query.yml
server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java

Change BWC checks to 1.3 since #2103 was backported.

Update #2103 BWC Versions

---

client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStats.java
server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequest.java
server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequestBuilder.java
server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/IndexingStats.java
server/src/main/java/org/opensearch/index/shard/InternalIndexingStats.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndicesStatsAction.java

Removes type specific index stats since only one type is allowed.
relates #1940

[Remove] Type Specific Index Stats

---

modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/ConcatenateGraphTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/ConcatenateGraphTokenFilterFactoryTests.java

Lucene has a ConcatenateGraphFilter that can concatenate tokens from a TokenStream
to create a single token (or several tokens that have the same position if
input TokenStream is a graph).
The change is to enable that ConcatenateGraphFilter by adding a Factory.
(cherry-pick from 0e95bb9dff976a9c7f9cdac63a92040043d029e2)
Signed-off-by: Mau Bach Quang <quangmaubach@gmail.com>
Add Factory to enable Lucene's ConcatenateGraphFilter.
Resolves https://github.com/opensearch-project/OpenSearch/issues/1278
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBU …

Add Factory to enable Lucene ConcatenateGraphFilter (#1278) (#2152)

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/230_interval_query.yml
server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
server/src/test/java/org/opensearch/index/query/IntervalQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/RegexpIntervalsSourceProviderTests.java

Add a `case_insensitive` flag to regexp interval source.

Case Insensitive Support in Regexp Interval

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/230_interval_query.yml
server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
server/src/test/java/org/opensearch/index/query/IntervalQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/RegexpIntervalsSourceProviderTests.java

1x backport of #2237.  Add a `case_insensitive` flag to regexp interval source.

[Backport] Case Insensitive Support in Regexp Interval (#2237)

---

DEVELOPER_GUIDE.md
buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java

The alerting plugin build started to fail with this commit. This is now blocking the opensearch-build for 1.3
This reverts the backport commit to unblock the opensearch-build
https://github.com/opensearch-project/alerting/issues/312

Revert Backport 1.x PR #2191

---

client/client-benchmark-noop-api-plugin/src/main/java/org/opensearch/plugin/noop/action/bulk/RestNoopBulkAction.java
client/client-benchmark-noop-api-plugin/src/main/java/org/opensearch/plugin/noop/action/search/RestNoopSearchAction.java

Removes type specific end-points from no-op bulk and search APIs. 
Other changes were implemented in
1.  https://github.com/opensearch-project/OpenSearch/pull/2215 
2. https://github.com/opensearch-project/OpenSearch/pull/2239
Relates #1940  

Remove type end-points from NOOP bulk and search action

---

server/src/main/java/org/opensearch/common/time/EpochTime.java
server/src/test/java/org/opensearch/common/time/DateFormattersTests.java

Fixes a regression introduced with Elasticsearch 7 regarding the date
field type that removed support for negative timestamps with sub-second
granularity. Reintroduces support for arbitrary negative timestamps in `epoch_millis` format.
Thanks to Ryan Kophs (https://github.com/rkophs) for allowing me to use
his previous work.
#1991 

Reintroduce negative epoch_millis #1991

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/ProxySettings.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
plugins/repository-s3/src/main/plugin-metadata/plugin-security.policy
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java

Add support of SOCKS proxies for S3 repository.
Instead of using `s3.client.protocol` as a proxy type a new property was added:
- `s3.client.proxy.type` - which maps directly to the official AWS proxy protocol setting. 
And support `HTTP`, `HTTPS` and `SOCKS` proxies. 
This code is almost the same as for others PRs related to PROXY support and needs to be move to the common place/part.

Add support of SOCKS proxies for S3 repository

---

buildSrc/build.gradle

Backport https://github.com/opensearch-project/OpenSearch/commit/3faeec8c53058a5f8cc9d7a2e645fe7c9a1d48da from https://github.com/opensearch-project/OpenSearch/pull/2113

Bump forbiddenapis from 3.0 to 3.2 in /buildSrc (#2113)

---

buildSrc/build.gradle
buildSrc/src/main/groovy/org/opensearch/gradle/ResolveAllDependencies.java
buildSrc/src/main/java/org/opensearch/gradle/LoggedExec.java
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
buildSrc/src/main/java/org/opensearch/gradle/ReaperPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/ReaperService.java
buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalBwcGitPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/ForbiddenApisPrecommitPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/ValidateJsonNoKeywordsTask.java
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestApiTask.java
buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestTestsTask.java
buildSrc/src/main/java/org/opensearch/gradle/test/rest/RestResourcesPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/transform/SymbolicLinkPreservingUntarTransform.java
buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java
buildSrc/src/main/java/org/opensearch/gradle/vagrant/VagrantBasePlugin.java
buildSrc/src/test/java/org/opensearch/gradle/docker/DockerSupportServiceTests.java

Lower version compatibility in an attempt to fix https://github.com/opensearch-project/OpenSearch/issues/2298.
Rewrite Java 9+ code in a Java 8-compatible way.
Should I back-port some of this to main even though we're going to deprecate JDK 8 in 2.0?
Closes https://github.com/opensearch-project/OpenSearch/issues/2298.
Closes https://github.com/opensearch-project/OpenSearch/issues/2319.

Restore Java 8 compatibility for build tools.

---

buildSrc/build.gradle
buildSrc/src/main/groovy/org/opensearch/gradle/ResolveAllDependencies.java
buildSrc/src/main/java/org/opensearch/gradle/LoggedExec.java
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
buildSrc/src/main/java/org/opensearch/gradle/ReaperPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/ReaperService.java
buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalBwcGitPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/ForbiddenApisPrecommitPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/precommit/ValidateJsonNoKeywordsTask.java
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestApiTask.java
buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestTestsTask.java
buildSrc/src/main/java/org/opensearch/gradle/test/rest/RestResourcesPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/transform/SymbolicLinkPreservingUntarTransform.java
buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java
buildSrc/src/main/java/org/opensearch/gradle/vagrant/VagrantBasePlugin.java
buildSrc/src/test/java/org/opensearch/gradle/docker/DockerSupportServiceTests.java

Restore Java 8 compatibility for build tools, make source code compatible with Java 8. Backports https://github.com/opensearch-project/OpenSearch/pull/2300. Even though we're removing support for JDK8 in 2.0 via https://github.com/opensearch-project/OpenSearch/issues/1689, this I want to have a commit on main that works for JDK8. 
Closes https://github.com/opensearch-project/OpenSearch/issues/2298.
Closes https://github.com/opensearch-project/OpenSearch/issues/2319. …

Restore Java 8 compatibility for build tools. (#2300)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

Move segment replication setting to IndexMetadata so that it can be set during index creation. This change also adds a simple integration test - SegmentReplicationIT that indexes some docs then compares doc counts between primary and replica shards.
This integ test is failing 20% of the time and produces reproducible seeds. Example seed:
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.indices.replication.SegmentReplicationIT.testReplicationAfterPrimaryRefreshAndFlush" -Dtests.seed=5F30ED7187D1E2E4 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=ro-RO -Dtests.timezone=Libya -Druntime.java=17 -Dtests.output=true -Dtests.opensearch.logger.level=DEBUG
```
This failure is when comparing the doc count …

Move segment replication setting to IndexMetadata so that it can be set during index creation.

---

server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java

Fixing soft deletes deprecation warning after merging #2315 into 1.x. 
Tested bwc with main.
#2334 

Fixing soft deletes deprecation warning

---

qa/translog-policy/src/test/java/org/opensearch/upgrades/TranslogPolicyIT.java

This test is slated for removal as it only applies to ancient indexes (Legacy
6.x). Muting test so bwc tests are consistent and no longer angry.

[Test-Failure] Mute TranslogPolicyIT

---

buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java

Manifested in https://github.com/opensearch-project/job-scheduler/pull/130
Part of https://github.com/opensearch-project/job-scheduler/pull/130

Fixing the --release flag usage for javac

---

buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java
distribution/tools/java-version-checker/build.gradle

* Fixing the --release flag usage for javac
* Fixing the --html5 flag usage for javadoc
Bringing https://github.com/opensearch-project/OpenSearch/pull/2343 to `main`
Part of https://github.com/opensearch-project/job-scheduler/pull/130

Fixing the --release flag usage for javac (#2343)

---

server/src/internalClusterTest/java/org/opensearch/search/geo/GeoShapeIntegrationIT.java
server/src/internalClusterTest/java/org/opensearch/search/geo/LegacyGeoShapeIntegrationIT.java
server/src/main/java/org/opensearch/index/query/AbstractGeometryQueryBuilder.java
server/src/main/java/org/opensearch/index/query/GeoShapeQueryBuilder.java
server/src/main/java/org/opensearch/index/query/QueryBuilders.java
server/src/test/java/org/opensearch/index/query/GeoShapeQueryBuilderTests.java

Remove type mappings from GeoShapeQueryBuilder
Relates #1940

[Remove] Type mappings from GeoShapeQueryBuilder

---

distribution/docker/src/docker/Dockerfile

Docker distribution builds are failing for http://vault.centos.org. Updated the mirror url to http://vault.epel.cloud provided by Cloudflare for now. For the later stage we can move to another distribution. 
Ref: https://www.getpagespeed.com/server-setup/how-to-fix-dnf-after-centos-8-went-eol
https://github.com/opensearch-project/OpenSearch/issues/2154

Updated the url for docker distribution

---

server/src/main/java/org/opensearch/common/time/EpochTime.java
server/src/test/java/org/opensearch/common/time/DateFormattersTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/2232.

Reintroduce negative epoch_millis #1991 (#2232)

---

server/src/main/java/org/opensearch/search/aggregations/metrics/AbstractPercentilesAggregationBuilder.java
server/src/main/java/org/opensearch/search/aggregations/metrics/PercentileRanksAggregationBuilder.java
server/src/main/java/org/opensearch/search/aggregations/metrics/PercentilesAggregationBuilder.java
server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java

Signed-off-by: Subhobrata Dey <sbcd90@gmail.com>
Ensures that `valuesField` is correctly populated in PercentilesAggregationBuilder even when the serialized query is passed as argument to the constructor.
https://github.com/opensearch-project/alerting/issues/306
[X] All tests pass
[X] Commits are signed per the DCO using --signoff 

Add valuesField in PercentilesAggregationBuilder streamInput constructor

---

distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java

* edited opensearch-plugin install help output to include plugin URL
Signed-off-by: Joshua Palis <jpalis@amazon.com>
* fixed unit test for plugin install help output by correctly identifying the beginning og the non-option argument list
Signed-off-by: Joshua Palis <jpalis@amazon.com>
* added comments to install plugins help non option argument ouput unit test
Signed-off-by: Joshua Palis <jpalis@amazon.com>
* fixed format violation
Signed-off-by: Joshua Palis <jpalis@amazon.com>
* added additional details on valid plugin ids and how to use plugin URLs
Signed-off-by: Joshua Palis <jpalis@amazon.com>
* added additional information to plugin install help output
Signed-off-by: Joshua Palis <jpalis@amazon.com>
Co-authored-by: Joshua Palis <jpalis@amazon.com>
(cherry picked from commit …

[Backport 1.x] Install plugin command help (#2193)

---

server/src/main/java/org/opensearch/rest/action/search/RestCountAction.java

Removes type endpoint from count action. Internal reference removal were done as part of https://github.com/opensearch-project/OpenSearch/pull/2109
Related #1940 

Remove type end-points from count action

---

server/src/internalClusterTest/java/org/opensearch/indices/IndexingMemoryControllerIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/OpenSearchReaderManager.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

Docrep and segrep should be able to work in parallel with this change. Previously, commented code was breaking docrep
- test docrep by running IndexRecoveryIT 
Resolves #2197 

Toggle replication strategy based on segrep index setting

---

server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

This change fixes a new bug that flipped primary and replica shard InternalEngine implementations.
This also updates replicas to set a historyUUID so that assertSequenceNumbersInCommit succeeds when initializing the shard.
SegmentReplicationIT now passes with this change.
- [] New functionality includes testing.

[Segment Replication] Fix replicas to set a history UUID inside InternalEngine.

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationReplicaService.java
server/src/main/java/org/opensearch/indices/replication/copy/CopyState.java
server/src/main/java/org/opensearch/indices/replication/copy/PrimaryShardReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/copy/ReplicationCollection.java

This PR comprises two changes:
1. The first updates the `ReplicationRef` class to mirror `RecoveryRef` and simply be an extension of `GatedAutoCloseable`.
2. The second change removes the SegmentInfosRef class and replaces it with GatedCloseable wrapper. This is similar to the removal of the IndexCommitRef class.
closes #2202 

Updates to segrep classes to mirror refactoring in main

---

modules/lang-mustache/src/main/java/org/opensearch/script/mustache/RestMultiSearchTemplateAction.java

Type mapping end-points from RestMultiSearchTemplateAction. This change escaped in https://github.com/opensearch-project/OpenSearch/pull/2263
Related to #1940 

[Remove] Type mapping end-points from RestMultiSearchTemplateAction

---

server/src/internalClusterTest/java/org/opensearch/action/termvectors/GetTermVectorsIT.java
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/LuceneChangesSnapshot.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/fieldvisitor/FieldsVisitor.java
server/src/main/java/org/opensearch/index/mapper/Uid.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/translog/Translog.java
server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsContext.java
server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsPhase.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/engine/LuceneChangesSnapshotTests.java
server/src/test/java/org/opensearch/index/translog/TranslogTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoverySourceHandlerTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
test/framework/src/main/java/org/opensearch/index/engine/TranslogHandler.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Removes types from Uid class along with cleaning up all obsolete MapperService
dependendices. This includes removing Uid from the Translog Delete operation
which is no longer needed due to type dependency removal.
relates #1940

[Remove] types from Uid and remaining types/Uid from translog

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/150_rewrite_on_coordinator.yml
server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
server/src/internalClusterTest/java/org/opensearch/validate/SimpleValidateQueryIT.java
server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
server/src/main/java/org/opensearch/indices/TermsLookup.java
server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
server/src/test/java/org/opensearch/indices/TermsLookupTests.java

Remove types from TermsLookUp
Related #1940 

[Remove] Type from TermsLookUp

---

server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/TasksIT.java
server/src/internalClusterTest/java/org/opensearch/gateway/GatewayIndexStateIT.java
server/src/internalClusterTest/java/org/opensearch/gateway/MetadataNodesIT.java
server/src/main/java/org/opensearch/action/index/IndexRequest.java
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/MappingMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
server/src/main/java/org/opensearch/index/mapper/MapperService.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/tasks/TaskResultsService.java
server/src/main/resources/org/opensearch/tasks/task-index-mapping.json
server/src/test/java/org/opensearch/cluster/metadata/MetadataMappingServiceTests.java

Removes types from the TaskResults internal index along with the getMappings
method from IndexMetadata. This is needed to further remove types from
CreateIndexRequest.
relates #1940

[Remove] type from TaskResults index and IndexMetadata.getMappings

---

server/src/internalClusterTest/java/org/opensearch/validate/SimpleValidateQueryIT.java
server/src/main/java/org/opensearch/action/admin/indices/validate/query/TransportValidateQueryAction.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/query/QueryRewriteContext.java
server/src/main/java/org/opensearch/index/query/QueryShardContext.java
server/src/main/java/org/opensearch/index/query/RangeQueryBuilder.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/SearchService.java
server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/2416 to 1.x

[Backport] [1.x] Discrepancy in result from _validate/query API and actual query validity (#2416)

---

rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_field_mapping/20_missing_field.yml
server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/LuceneChangesSnapshot.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/PrimaryReplicaSyncer.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/engine/LuceneChangesSnapshotTests.java
server/src/test/java/org/opensearch/index/replication/IndexLevelReplicationTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

Improves the LuceneChangesSnapshot to get an accurate count of recovery
operations using sort by sequence number optimization. This is needed 
for Lucene 9 where searchAfter pagination is not thread safe (leading to 
inaccurate recovery count exceptions).

[Refactor] LuceneChangesSnapshot to use accurate ops history

---

server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java

Fixing PluginsServiceTests
Part of https://github.com/opensearch-project/OpenSearch/issues/2063

Fixing PluginsServiceTests (post Lucene 9 update)

---

server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexPrimaryRelocationIT.java

Unmutes IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing which was
fixed by LuceneChangesSnapshot using accurate ops history.
relates #2063

[Unmute] IndexPrimaryRelocationIT.testPrimaryRelocationWhileIndexing

---

modules/ingest-common/src/test/java/org/opensearch/ingest/common/AppendProcessorTests.java
modules/ingest-common/src/test/java/org/opensearch/ingest/common/SetProcessorTests.java
server/src/main/java/org/opensearch/action/ingest/SimulatePipelineRequest.java
server/src/main/java/org/opensearch/ingest/IngestDocument.java
server/src/test/java/org/opensearch/action/ingest/SimulatePipelineRequestParsingTests.java

Remove _type field support in ingest document
Related: #1940 

[Remove] Type metadata from ingest documents

---

modules/mapper-extras/src/test/java/org/opensearch/index/query/RankFeatureQueryBuilderTests.java
modules/percolator/src/internalClusterTest/java/org/opensearch/percolator/PercolatorQuerySearchIT.java
modules/percolator/src/test/java/org/opensearch/percolator/PercolateQueryBuilderTests.java
modules/percolator/src/test/java/org/opensearch/percolator/PercolateWithNestedQueryBuilderTests.java
server/src/internalClusterTest/java/org/opensearch/document/AliasedIndexDocumentActionsIT.java
server/src/internalClusterTest/java/org/opensearch/index/HiddenIndexIT.java
server/src/internalClusterTest/java/org/opensearch/indices/template/SimpleIndexTemplateIT.java
server/src/internalClusterTest/java/org/opensearch/search/basic/TransportTwoNodesSearchIT.java
server/src/internalClusterTest/java/org/opensearch/search/searchafter/SearchAfterIT.java
server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/indices/mapping/put/PutMappingRequest.java
server/src/main/java/org/opensearch/action/admin/indices/mapping/put/PutMappingRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/indices/rollover/RolloverRequestBuilder.java
server/src/main/java/org/opensearch/action/admin/indices/template/put/PutIndexTemplateRequest.java
server/src/main/java/org/opensearch/action/admin/indices/template/put/PutIndexTemplateRequestBuilder.java
server/src/test/java/org/opensearch/action/admin/indices/mapping/put/PutMappingRequestTests.java
server/src/test/java/org/opensearch/index/mapper/RangeFieldQueryStringQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/MatchQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/TermsSetQueryBuilderTests.java
test/framework/src/main/java/org/opensearch/test/AbstractBuilderTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java

Continues removal of types from PutIndexTemplateRequest and
PutIndexTemplateRequestBuilder.mapping. Delegated mapping method in
PutIndexTemplateRequestBuilder is refactored to setMapping for consistency with
similar methods (e.g., setSettings, setAliases).
relates #1940

[Remove] Type from PutIndexTemplateRequest and PITRB

---

release-notes/opensearch.release-notes-1.3.0.md

Adds 1.3 release notes starting from [1.x version bump to 1.3](https://github.com/opensearch-project/OpenSearch/commit/ce7b091da6ae50bbc3c015a78b7611923475386c). 
https://github.com/opensearch-project/OpenSearch/issues/2257

Add 1.3.0 release notes in main

---

modules/percolator/src/internalClusterTest/java/org/opensearch/percolator/PercolatorQuerySearchIT.java
modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
modules/percolator/src/test/java/org/opensearch/percolator/PercolateQueryBuilderTests.java

Remove types from percolate query API
Related: #1940 

[Remove] Type from Percolate query API

---

server/src/main/java/org/opensearch/index/mapper/RangeFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/IpRangeFieldMapperTests.java

Allows using `ignore_malformed` on a mapping for `ip_range` data type 
Closes https://github.com/opensearch-project/OpenSearch/issues/1873

ignore_malformed parameter on ip_range data_type throws mapper_parsing_exception

---

server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java

After merging Lucene 9.1 NumberFieldTypeTests is now passing. Unmute test.
closes #2063

[Unmute] NumberFieldTypeTests

---

server/src/internalClusterTest/java/org/opensearch/search/geo/AbstractGeoDistanceIT.java
server/src/internalClusterTest/java/org/opensearch/search/geo/GeoDistanceQueryGeoPointsIT.java
server/src/internalClusterTest/java/org/opensearch/search/geo/GeoDistanceQueryGeoShapesIT.java
server/src/main/java/org/opensearch/index/query/GeoDistanceQueryBuilder.java
server/src/test/java/org/opensearch/index/query/GeoDistanceQueryBuilderTests.java

Adds support for using the `geo_distance` query on `geo_shape` field types by
lifting the `geo_point` restriction in the QueryBuilder. Distance query
integration tests are abstracted to test both `geo_point` and `geo_shape` field
types.
closes #2514

Support for geo_distance queries on geo_shape fields

---

plugins/repository-hdfs/build.gradle

Updating repository commons logging version to use central versioning system by OpenSearch.
This also solves the problem of Jar hell when https://github.com/dependabot is trying to upgrade commons-logging.
Ref: https://github.com/opensearch-project/OpenSearch/pull/2388#issuecomment-1073125291

Updating repository commons logging version

---

server/src/internalClusterTest/java/org/opensearch/search/geo/AbstractGeoBoundingBoxQueryIT.java
server/src/internalClusterTest/java/org/opensearch/search/geo/GeoBoundingBoxQueryGeoPointsIT.java
server/src/internalClusterTest/java/org/opensearch/search/geo/GeoBoundingBoxQueryGeoShapesIT.java
server/src/main/java/org/opensearch/index/query/GeoBoundingBoxQueryBuilder.java
server/src/test/java/org/opensearch/index/query/GeoBoundingBoxQueryBuilderTests.java

Adds support for using `geo_bounding_box` queries on `geo_shape` field types by
lifting the `geo_point` restriction in the QueryBuilder. Bounding Box query
integration tests are abstracted to test both `geo_point` and `geo_shape` types.
closes #2505

Support for geo_bounding_box queries on geo_shape fields

---

server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/plugins/SearchPlugin.java
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/main/java/org/opensearch/search/query/QueryPhaseSearcher.java
server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/node/MockNode.java
test/framework/src/main/java/org/opensearch/search/MockSearchService.java

In scope of https://github.com/opensearch-project/OpenSearch/pull/1500 implementation, provides an extension point to allow plugging in own search implementation to be used at the `QueryPhase` time. With that, the concurrent search could be implemented using sandbox plugin, without touching the core.

Introduce QueryPhaseSearcher extension point (SearchPlugin)

---

server/src/main/java/org/opensearch/index/mapper/RangeFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/IpRangeFieldMapperTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/2429 to 1.x
Closes https://github.com/opensearch-project/OpenSearch/issues/1873

[Backport] [1.x] ignore_malformed parameter on ip_range data_type throws mapper_parsing_exception (#2429)

---

server/src/main/java/org/opensearch/search/lookup/LeafDocLookup.java

Remove deprecation warning on use of _type in doc scripts
Related: #1940

[Type removal] Remove deprecation warning on use of _type in doc scripts

---

server/src/main/java/org/opensearch/transport/InboundDecoder.java

Change InboundDecoder `ensureVersionCompatibility` check for `onOrAfter`
`V_2_0_0` instead of explicit 2.0 check. This way bug fix and minor
versions will correctly handshake in a mixed 1.x Cluster.

[Bug] Fix InboundDecoder version compat check

---

server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/plugins/SearchPlugin.java
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/SearchModule.java
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/main/java/org/opensearch/search/query/QueryPhaseSearcher.java
server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/node/MockNode.java
test/framework/src/main/java/org/opensearch/search/MockSearchService.java

Backport https://github.com/opensearch-project/OpenSearch/commit/82fb7abb7158788fa727543dbcc89cffc318c67a from https://github.com/opensearch-project/OpenSearch/pull/1931

[Backport] [1.x] Introduce QueryPhaseSearcher extension point (SearchPlugin)

---

modules/transport-netty4/src/internalClusterTest/java/org/opensearch/rest/discovery/Zen2RestApiIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
server/src/main/java/org/opensearch/action/admin/cluster/configuration/AddVotingConfigExclusionsRequest.java
server/src/main/java/org/opensearch/cluster/InternalClusterInfoService.java
server/src/main/java/org/opensearch/cluster/coordination/ClusterBootstrapService.java
server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/coordination/DetachClusterCommand.java
server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
server/src/main/java/org/opensearch/cluster/coordination/Reconfigurator.java
server/src/main/java/org/opensearch/cluster/coordination/UnsafeBootstrapMasterCommand.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
server/src/main/java/org/opensearch/discovery/HandshakingTransportAddressConnector.java
server/src/main/java/org/opensearch/discovery/PeerFinder.java
server/src/main/java/org/opensearch/env/NodeRepurposeCommand.java
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/IncrementalClusterStateWriter.java
server/src/main/java/org/opensearch/gateway/PersistedClusterStateService.java
server/src/main/java/org/opensearch/persistent/PersistentTasksClusterService.java
server/src/main/java/org/opensearch/repositories/blobstore/package-info.java
server/src/test/java/org/opensearch/action/admin/cluster/configuration/AddVotingConfigExclusionsRequestTests.java
server/src/test/java/org/opensearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsActionTests.java
server/src/test/java/org/opensearch/cluster/coordination/ClusterBootstrapServiceTests.java
server/src/test/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelperTests.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
server/src/test/java/org/opensearch/discovery/AbstractDisruptionTestCase.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

Replace "master" terminology in Log messages.
https://github.com/opensearch-project/OpenSearch/issues/2539

Replaced "master" terminology in Log message

---

server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Enable merge on refresh and merge on commit on Opensearch. Luckily, Apache Lucene 9.1 introduces `MergeOnFlushMergePolicy` which we could use from now on, activated by `index.max_full_flush_merge` (expert) index setting. The experiments I have done using [1] and `pmc` track shows significant reduction of the segments for a price of more merges:
```
./rally race    --track pmc      --target-hosts localhost:9200     --pipeline benchmark-only     --kill-running-processes --exclude-tasks="force-merge,refresh-after-force-merge,wait-until-merges-finish"
```
**Baseline**: 2.0.0-SNAPSHOT
**Contender**: 2.0.0-SNAPSHOT +  "index.max_full_flush_merge": "10s"
|                                                        Metric | …

Enable merge on refresh and merge on commit on Opensearch

---

buildSrc/reaper/build.gradle

Fix build-tools/reaper source/target compatibility to be JDK-11
Fixes https://github.com/opensearch-project/OpenSearch/issues/2581

Fix build-tools/reaper source/target compatibility to be JDK-11

---

distribution/build.gradle

This is a short-term solution to unblock the build process for the 1.3
release. A tool used in that process (cpio) is failing on a symlink in
the JDK man pages, so this is a hack to just remove that symlink. See
issue #2517 for more details.
#2517

Exclude man page symlink in distribution

---

test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java

Came across this during some testing. Adding check for SLM deletion for OpenSearch versions since SLM was part of x-pack.

Removing SLM check in tests for OpenSearch versions

---

server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java

Add mapping method back; removed earlier as part of `remove mapping types` effort. The method was removed [here](https://github.com/opensearch-project/OpenSearch/commit/b619a050bf1048d3edc7b80dd05801a89698ccf1#diff-403b4373119da8105496a50962025139b4031c2900205987d4e374c439e0407c). It is used in [dashboard-reports ](https://github.com/opensearch-project/dashboards-reports/blob/main/reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/index/ReportDefinitionsIndex.kt#L68) repo and probably others. 
Related: #1940  …

[Type Removal] Add mapping method referenced in other repos

---

jenkins/jenkinsfile

Updated jdk version to use 17 for gradle check on `main`, `2.x` and `2.0` after jenkins will go public.
https://github.com/opensearch-project/OpenSearch/issues/2644

Updated JAVA_HOME to jdk-17 in jenkinsfile

---

jenkins/jenkinsfile

Backport of https://github.com/opensearch-project/OpenSearch/pull/2166. The only change is pointing JAVA_HOME  to jdk-11 for 1.x for jenkins to pick up once it goes public.
Part of https://github.com/opensearch-project/OpenSearch/issues/2644

[Backport-1.x] Added jenkisfile to run gradle check in OpenSearch

---

.github/workflows/version.yml

Backporting changes for version workflow

---

server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

Fixes the failing tests caused by incorrect initialization of engineConfig in - 
1. EngineTestCase 
2. RefreshListenerTests
Failure mentioned in issue #2414 

fix gradle check failure caused by init of EngineConfig

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java
server/src/test/java/org/opensearch/index/seqno/SegmentReplicationLocalCheckpointTrackerTests.java

For segment replication, previously the local processed checkpoint was not being updated. This is now fixed along with unit tests for the same.
Resolves #2358 

fix local processed checkpoint update

---

server/src/main/java/org/opensearch/OpenSearchException.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java

Fixes a failing test case in gradle check: 
org.opensearch.ExceptionSerializationTests.testExceptionRegistration 
Failure mentioned in #2414 

gradle check fix exception test failure

---

rest-api-spec/src/main/resources/rest-api-spec/api/cluster.get_settings.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.pending_tasks.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.put_settings.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.reroute.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.state.json
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterGetSettingsAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterRerouteAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterUpdateSettingsAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestPendingClusterTasksAction.java
server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
server/src/test/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteRequestTests.java
server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthActionTests.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/2658 / commit https://github.com/opensearch-project/OpenSearch/commit/7d23b180f77821266f0acd779a9db637739ee0b9 into `2.0` branch.
- Deprecate the request parameter `master_timeout` that used in Cluster APIs which have got the parameter.
- Add alternative new request parameter `cluster_manager_timeout`.
- Add unit tests.
A part of issue #2511

[2.0] Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' in Cluster APIs (#2658) 

---

plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java

Signed-off-by: Raphael Lopez <raphael.lopez@aiven.io>
Previously, the `repository-azure` plugin failed to load when a SAS token was provided for authentication rather than an Azure Storage Account key. This was due to a dependency in the `ENDPOINT_SUFFIX_SETTING` - more details in the issue description.
I opted to remove the dependency altogether since the plugin has a check in [buildConnectString()](https://github.com/opensearch-project/OpenSearch/blob/bdcaec5caf4a55afc8a2e5e5f136c2f65d098fd6/plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java#L281) to ensure that either a SAS token or a Storage Account key is provided. 
Relates to #2462 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Remove endpoint_suffix dependency on account key

---

buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java

This change swaps the order of the task to first check for no pointless exclusions.
If not caught first these will be thrown inside of the bogusExcludesCount block that logs a
useless error message.
This has caused a few dependabot PRs to linger with the error message:
```
"All excluded classes seem to have no issues. This is sometimes an indication that the check silently failed"
```
After this change it will properly list the pointless exclusions:
```
> Task :modules:ingest-geoip:thirdPartyAudit
Unnecessary exclusions, following classes are not missing:
* org.apache.http.HttpEntity
* org.apache.http.HttpResponse
* org.apache.http.StatusLine
* org.apache.http.client.config.RequestConfig
* …
```

Update ThirdPartyAuditTask to check for and list pointless exclusions.

---

rest-api-spec/src/main/resources/rest-api-spec/test/tasks.list/10_basic.yml
server/src/main/java/org/opensearch/tasks/TaskInfo.java

Fixes the version check around resourceStats serialization and unmutes the
failing bwc test.
closes #2757

Fix TaskInfo serialization and unmute task_list bwc test

---

rest-api-spec/src/main/resources/rest-api-spec/api/cluster.get_settings.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.pending_tasks.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.put_settings.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.reroute.json
rest-api-spec/src/main/resources/rest-api-spec/api/cluster.state.json
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterGetSettingsAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterRerouteAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterUpdateSettingsAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestPendingClusterTasksAction.java
server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
server/src/test/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteRequestTests.java
server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthActionTests.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/2658 / commit https://github.com/opensearch-project/OpenSearch/commit/7d23b180f77821266f0acd779a9db637739ee0b9 into `2.x` branch.
- Deprecate the request parameter `master_timeout` that used in Cluster APIs which have got the parameter.
- Add alternative new request parameter `cluster_manager_timeout`.
- Add unit tests.
A part of issue #2511

[2.x] Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' in Cluster APIs (#2658)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/Segment.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/copy/CopyState.java
server/src/main/java/org/opensearch/indices/replication/copy/ReplicationCheckpoint.java
server/src/main/java/org/opensearch/indices/replication/copy/SegmentReplicationTarget.java

This PR is a combination of three changes that gets Segrep integ tests to reliably pass.
Fixes:
1. Updates the tests to use a single BackgroundIndexer.  This ensures we correctly index the expected amount of documents. BackgroundIndexers start indexing with docId of 0, so using multiple indexers creates conflicts.
2. Fix Index shards to correctly compare checkpoint version instead of segment gen when determining
if a received checkpoint should be processed. Without this change replicas will ignore checkpoints for merges.
3. Store the latest checkpoint received and process it after a copy event completes.  This ensures we are always processing the latest checkpoint if it is received during an active copy.
Improvements:
- Update tests to compare result of segments() API.  This will compare …

Fix Segment Replication integ tests

---

plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
test/fixtures/azure-fixture/src/main/java/fixture/azure/AzureHttpHandler.java

Fix test flakiness
Fixes https://github.com/opensearch-project/OpenSearch/issues/2782

Update azure-storage-blob to 12.15.0: fix test flakiness

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
server/src/test/java/org/opensearch/search/aggregations/bucket/RareTermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/SignificantTermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/TermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/BinaryTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java

This change fixes a code path that did not properly impose the index-level max_regex_length limit. Therefore, it was possibly to provide an arbitrarily large string as the include/exclude reg-ex value under search aggregations. This exposed the underlying node to crashes from a StackOverflowError, due to how the Lucene RegExp class processes strings using stack frames.
closes #1992 

Bugfix to guard against stack overflow errors caused by very large reg-ex input

---

qa/mixed-cluster/src/test/java/org/opensearch/backwards/ExceptionIT.java

- Allow deprecation warning when calling `GET _cat/master` API in `ExceptionIT` class of mixed cluster BWC test
The test `ExceptionIT.testOpensearchException()` calls API `GET _cat/master` to log the cluster-manager node ID.
Since the REST API is deprecated in version 2.0 and `RestClient` used in the test treats warning as failure, the test breaks when running the BWC test against node version >=2.0
Note:
Mixed cluster BWC test will spin up 4 nodes with the specified old version, and upgrade 2 nodes to the current version to form a mixed version cluster. 
Resolve https://github.com/opensearch-project/OpenSearch/issues/2759 …

Allow deprecation warning for API call 'GET _cat/master' in 'ExceptionIT' of mixed cluster BWC test

---

server/src/main/java/org/opensearch/common/inject/BindingProcessor.java
server/src/main/java/org/opensearch/common/inject/InheritingState.java
server/src/main/java/org/opensearch/common/inject/InjectorImpl.java
server/src/main/java/org/opensearch/common/inject/State.java
test/framework/src/main/java/org/opensearch/test/rest/yaml/DenylistedPathPatternMatcher.java
test/framework/src/main/java/org/opensearch/test/rest/yaml/OpenSearchClientYamlSuiteTestCase.java
test/framework/src/test/java/org/opensearch/test/rest/yaml/DenylistedPathPatternMatcherTests.java

This is the last PR for replacing non-inclusive terminology `blacklist`. 
Most of the internal usages of non-inclusive terminology `blacklist/whitelist` was replaced by PR https://github.com/opensearch-project/OpenSearch/pull/2178, while there are a few remaining.
- Replace `blacklist` with `denylist` in internal class and method names.
Note:
1. The 2 classes to be renamed are not published to Maven
- class `org.opensearch.test.rest.yaml.BlacklistedPathPatternMatcher`
- interfact `org.opensearch.common.inject.State`, javadoc of the package: https://opensearch.org/javadocs/1.3.1/OpenSearch/server/build/docs/javadoc/org/opensearch/common/inject/package-summary.html
2. The package `org.opensearch.common.inject` is a forked version of `Google Guice` framework 2.0 …

Replace remaining 'blacklist' with 'denylist' in internal class and method names

---

server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java

Removed the null-case for IndexSettings since this only occurs in tests. The tests now use a dummy Index Setting.
This change also fixes a bug with the base case handling of max regex length in the check.

Updates to the large string reg-ex check

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java

The cat shards api output now includes the store size for the replica.
Resolves #2431 

fix _cat/shards api replica output

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
server/src/test/java/org/opensearch/search/aggregations/bucket/RareTermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/SignificantTermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/TermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/BinaryTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java

This change fixes a code path that did not properly impose the index-level max_regex_length limit. Therefore, it was possibly to provide an arbitrarily large string as the include/exclude reg-ex value under search aggregations. This exposed the underlying node to crashes from a StackOverflowError, due to how the Lucene RegExp class processes strings using stack frames.
This change also includes the removal of the null-case for IndexSettings since this only occurs in tests (the tests now use a dummy Index Setting) and fixes a bug with the base case handling of max regex length in the check.
Backport of #2810 and #2814  …

[Backport] [2.x] Bugfix to guard against stack overflow errors caused by very large reg-ex input 

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
server/src/test/java/org/opensearch/search/aggregations/bucket/RareTermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/SignificantTermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/TermsTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/BinaryTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java

This change fixes a code path that did not properly impose the index-level max_regex_length limit. Therefore, it was possibly to provide an arbitrarily large string as the include/exclude reg-ex value under search aggregations. This exposed the underlying node to crashes from a StackOverflowError, due to how the Lucene RegExp class processes strings using stack frames.
This change also includes the removal of the null-case for IndexSettings since this only occurs in tests (the tests now use a dummy Index Setting) and fixes a bug with the base case handling of max regex length in the check.
Backport of #2810 and #2814  …

[Backport] [2.0] Bugfix to guard against stack overflow errors caused by very large reg-ex input

---

plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java

Backport https://github.com/opensearch-project/OpenSearch/commit/365e07ce4be444a2f12938f442698f50782e80dc from https://github.com/opensearch-project/OpenSearch/pull/2485

[Backport 2.x] Remove endpoint_suffix dependency on account key

---

server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java

This change refactors an earlier change to impose a reg-ex size limit on the include/exclude string. Instead of accepting an IndexSettings instance, the class now accepts a integer limit value. This is necessary because the IncludeExclude class is used outside the core codebase, whose use-cases may be unaware of indices and their settings. To ensure that a limit is always imposed, a default limit is defined in the class.
closes #2858 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develop …

Decouple IndexSettings from IncludeExclude

---

rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/10_basic.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/20_source_mapping.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/30_copy_settings.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/10_basic.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/20_source_mapping.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/10_basic.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/20_source_mapping.yml
rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
server/src/main/java/org/opensearch/rest/BaseRestHandler.java
server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetMappingAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java

According to the comments, change the deprecation message of REST API parameter `master_timeout`:
https://github.com/opensearch-project/OpenSearch/pull/2678#discussion_r847640803 
https://github.com/opensearch-project/OpenSearch/pull/2682#discussion_r847636915
- Specify the version (3.0) to remove the deprecated parameter.
- Change the word `promote` to `support`.
Related to #2511 

Change deprecation message for REST API parameter 'master_timeout' to specify the version of removal

---

rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/20_filtering.yml
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterRerouteAction.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java

- Fix REST API test failure caused by the commit https://github.com/opensearch-project/OpenSearch/commit/07fc06d5a69106078d5467993752693a64423fb0#diff-07ee2fae81fcb1a59586494ccd6ec9d44a21bdcb5a57ebf053aa352aa85ba5f7 (of PR https://github.com/opensearch-project/OpenSearch/pull/2678), where the file `cluster.state/20_filtering.yml` is changed by mistake.
- Revise the deprecation message to include the version of removal. A similar PR https://github.com/opensearch-project/OpenSearch/pull/2863 for reference.
The test failure of `org.opensearch.test.rest.ClientYamlTestSuiteIT" -Dtests.method="test {p0=cluster.state/20_filtering/Filtering the cluster state returns cluster_uuid at the top level regardless of metric filters}`, see https://github.com/opensearch-project/OpenSearch/pull/2875#issuecom …

Change deprecation message for API parameter value 'master_node' of parameter 'metric'

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

This fix stops the replica shards from incorrectly trying to send checkpoints by avoiding wiring up the replica's internalRefreshListeners with CheckpointRefreshListener.
Resolves #2815 

fix - replica shards trying to send replica checkpoints

---

server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/TextFieldTypeTests.java

When the length of the query prefix is = minChars-1, the code follows the path in TextFieldMapper and throws an NPE [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java#L586). Adding a null check for the method, the query returns a result without an NPE now:
```
curl -XPUT localhost:9200/test --data '{                                                                             
"mappings": {
"t": {
"type": "text",
"index_prefixes": { "min_chars": "3" }
}
}
}
}' -H "Content-Type:Application/json"
{{"acknowledged":true,"shards_acknowledged":true,"index":"test"}
```
```
curl 'localhost:9200/test/_search?pretty' --data '{"query":{"prefix":{"t": …
```

Adding a null pointer check to fix index_prefix query

---

distribution/src/bin/opensearch-env

distribution/bin/opensearch-env always sources the environment from the default environment file /etc/default/opensearch. This is an issue if we want to run multiple instances of OpenSearch on the same host. This change lets users override the default behavior by not sourcing the default environment file in case OPENSEARCH_PATH_CONF  is set.
Signed-off-by: xuezhou25 <85715413+xuezhou25@users.noreply.github.com>
[1.x backport] Fix opensearch-env always sources the environment from hardcoded file in #875
https://github.com/opensearch-project/opensearch-build/issues/1545#issuecomment-1092408321 …

[1.x backport] Fix opensearch-env always sources the environment from hardcoded file in #875

---

distribution/src/bin/opensearch-env

distribution/bin/opensearch-env always sources the environment from the default environment file /etc/default/opensearch. This is an issue if we want to run multiple instances of OpenSearch on the same host. This change lets users override the default behavior by not sourcing the default environment file in case OPENSEARCH_PATH_CONF  is set.
Signed-off-by: xuezhou25 <85715413+xuezhou25@users.noreply.github.com>
[1.x backport] Fix opensearch-env always sources the environment from hardcoded file in #875
https://github.com/opensearch-project/opensearch-build/issues/1545#issuecomment-1092408321 …

[1.3 backport] Fix opensearch-env always sources the environment from hardcoded file in #875

---

MAINTAINERS.md

Following the process in https://github.com/opensearch-project/.github/pull/59, I had nominated Andriy Redko (@reta) as a co-maintainer. The maintainers have voted and agreed to this nomination.
Andriy is the author of [124 PRs](https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+author%3Areta+is%3Aclosed) into OpenSearch, [second](https://github.com/opensearch-project/OpenSearch/graphs/contributors?from=2021-05-27&to=2022-04-04&type=c) in code change volume since the fork.
Some of reta@’s notable early code contributions were in the supporting infrastructure space, and have increasingly been shifting into adding new features:
- https://github.com/opensearch-project/OpenSearch/pull/1500: Concurrent searching
- …

Adding @reta to OpenSearch maintainers.

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Signed-off-by: Nicholas Walter Knize <nknize@apache.org>
Signed-off-by: Sai Kumar <karanas@amazon.com>
Adds a deprecated API to create a history operations snapshot from the translog.
https://github.com/opensearch-project/OpenSearch/issues/2482

Add deprecated API for creating History Ops Snapshot from translog

---

qa/rolling-upgrade/build.gradle
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/AbstractRollingTestCase.java
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/MappingTypeRemovalIT.java
test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java

- Add backwards compatibility tests for testing type mapping changes from OS2.0
- https://github.com/opensearch-project/OpenSearch/issues/2240
- https://github.com/opensearch-project/OpenSearch/pull/2601

Add type mapping removal bwc tests for indexing, searching, snapshots

---

.github/workflows/lucene-snapshots.yml
DEVELOPER_GUIDE.md
buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java

This change introduces a github workflow so that maintainers can build and push snapshots of lucene.
The RepositoriesSetupPlugin is also updated with a url from where these snapshots can be retrieved.
This workflow will be initially manually executable by maintainers but will be extended to run periodically and test compatibility with OpenSearch.
I have [tested](https://github.com/mch2/TestActions/actions/workflows/lucene-snapshots.yml) this workflow & the Integration with RepositoriesSetupPlugin from a personal repository.
closes #2785 
closes #2786 
closes https://github.com/opensearch-project/opensearch-build/issues/1920
closes https://github.com/opensearch-project/opensearch-build/issues/1778
By submitting this pull request, I confirm …

Add Github Workflow to build and publish lucene snapshots.

---

test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java

The PR can only be merged after PR https://github.com/opensearch-project/OpenSearch/pull/2920 merged. [<- achieved]
This reverts commit 6a2a33d1872850b04562164c39621698cb99d7b8, and will be get into `2.x` branch.
This PR sets the High-Level-Rest-Client tests back to treating warning header as a failure.
During the process of deprecating REST API request parameter `master_timeout` and add alternative parameter `cluster_manager_timeout`, I made High-Level-Rest-Client tests allow deprecation warning temporarily, by changing the argument of `setStrictDeprecationMode()` to `false` when building `RestClient` for tests, in the above commit / PR https://github.com/opensearch-project/OpenSearch/pull/2702.
Now it's decided not to emit deprecation warning for using parameter `master_timeout` in …

[2.x] Revert "Make High-Level-Rest-Client tests allow deprecation warning temporarily (#2702)"

---

build.gradle

Bumps com.diffplug.spotless from 6.4.1 to 6.4.2.
---
updated-dependencies:
- dependency-name: com.diffplug.spotless
dependency-type: direct:production
update-type: version-update:semver-patch
...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit c876f55294b5636e558e5735cf2f0c629bcda080)
Backport from #2827  …

[Backport-2.x] Bump com.diffplug.spotless from 6.4.1 to 6.4.2 (#2827)

---

client/rest-high-level/src/main/java/org/opensearch/client/cluster/ProxyModeInfo.java
client/rest-high-level/src/main/java/org/opensearch/client/cluster/RemoteConnectionInfo.java
client/rest-high-level/src/main/java/org/opensearch/client/cluster/SniffModeInfo.java

- The logs for the flakey test have the generic Java object hash representation
- Adding in `toString` overrides for corresponding classes for usable logs
- https://github.com/opensearch-project/OpenSearch/issues/1703

Override toString for usable logs

---

.github/CODEOWNERS

Adding reta to codeowners

---

distribution/src/config/jvm.options

Update default jvm settings to use G1GC by default for
JDK11 and greater.
#2916

Use G1GC on JDK11+

---

build.gradle
gradle/code-coverage.gradle

Gradle [released](https://docs.gradle.org/7.4/release-notes.html) version 7.4  tool allows  to create aggregated test and Jacoco coverage HTML reports, see please [1].
Where the reports are located:
- build/reports/jacoco/testCodeCoverageReport (more details [2])
- build/reports/tests/unit-tests/aggregated-results (more details [3])
[1] https://docs.gradle.org/7.4/release-notes.html#new-features-and-usability-improvements
[2] https://docs.gradle.org/7.4/samples/sample_jvm_multi_project_with_code_coverage_standalone.html
[3] https://docs.gradle.org/7.4/samples/sample_jvm_multi_project_with_test_aggregation_standalone.html
[4] https://docs.gradle.org/current/userguide/test_report_aggregation_plugin.html
N/A
By submitting this pull request, …

Add Gradle 7.4 Aggregated Test Reports

---

server/src/main/java/org/opensearch/action/admin/indices/recovery/TransportRecoveryAction.java
server/src/main/java/org/opensearch/common/concurrent/AutoCloseableRefCounted.java
server/src/main/java/org/opensearch/common/concurrent/GatedCloseable.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveriesCollection.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryState.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTimer.java
server/src/main/java/org/opensearch/indices/replication/common/Timer.java
server/src/test/java/org/opensearch/common/concurrent/AutoCloseableRefCountedTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTargetTests.java
server/src/test/java/org/opensearch/rest/action/cat/RestRecoveryActionTests.java

This PR is one of the first steps in merging the feature branch `feature/segment-replication` back into `main` by re-PRing key changes. It covers part of the code changes in #2926 . The breakdown of the plan to merge segment-replication to main is detailed in #2355 
The changes included in this PR are as follows:
1. `GatedAutoCloseable` currently wraps a subclass of `RefCounted`. Segment replication adds another subclass, but this also wraps `RefCounted`. Both subclasses have the same shutdown hook - `decRef`. Therefore, `GatedAutoCloseable` has been made less generic (and renamed to `AutoCloseableRefCounted`) to increase code convergence.
2. The `RecoveryState.Timer` inner class has been moved to a top-level class. This will eventually be …

Refactoring GatedAutoCloseable and moving RecoveryState.Timer

---

.gitignore
.linelint.yml

Coming from https://github.com/opensearch-project/OpenSearch/pull/2969. Removed the binary file from linelint.yml and added it to gitignore in case if its generated on local.
Part of https://github.com/opensearch-project/OpenSearch/issues/2857

Removed binary file from linelint

---

client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/main/java/org/opensearch/action/main/TransportMainAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/action/main/MainActionTests.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

With types removal OpenSearch 2.0.0 no longer supports HLRC compatibility with legacy clients. 
This commit removes all 1.x logic to spoof the version as a legacy cluster.
closes #3023

[Remove] MainResponse version override cluster setting

---

whitesource.config

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Since the WhiteSource integration on GitHub is not working as expected on OpenSearch repo; from what I heard from WhiteSource support, we will need to have this `whitesource.config` file in the `1.x` repo since the WhiteSource file is targeting on the `1.x` branch right now. https://github.com/opensearch-project/OpenSearch/blob/03fbca3f500d8541b4b32c1456997a8493ebe4f5/.whitesource#L6
The `.whitesource` file should stay in the default branch. 
Let's do as what their support suggested and see if this will resolve the issues on WhiteSource integration scanning OpenSearch repo for CVEs . 
For …

Add whitesource config file to 1.x branch

---

.gitignore
.linelint.yml

Backport of https://github.com/opensearch-project/OpenSearch/pull/3015
Part of https://github.com/opensearch-project/OpenSearch/issues/2857

[Backport 2.x] Removed binary file from linelint

---

gradle/code-coverage.gradle

Temporary adding Apache Lucene repositories for snapshots
Fixes build issues (after https://github.com/opensearch-project/OpenSearch/pull/2924)

Temporary adding Apache Lucene repositories for snapshots

---

client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
client/rest-high-level/src/test/java/org/opensearch/client/RestHighLevelClientTests.java

See please https://github.com/opensearch-project/OpenSearch/issues/2436#issuecomment-1105614010
Closes https://github.com/opensearch-project/OpenSearch/issues/2436

Added explicit 'null' check for response listener to prevent obscure NullPointerException issues

---

buildSrc/src/main/resources/forbidden/opensearch-test-signatures.txt
server/src/main/resources/org/opensearch/bootstrap/security.policy

A few places still referenced legacy ESTestCase naming. This refactors those
instances to OpenSearchTestCase.

[Rename] ESTestCase stragglers to OpenSearchTestCase

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/main/java/org/opensearch/common/util/FeatureFlags.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationType.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/resources/org/opensearch/bootstrap/security.policy
server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java

This change formalizes the notion of [feature flags](https://featureflags.io/feature-flag-introduction/), and adds a "replication type" setting that will differentiate between document and [segment replication](https://github.com/opensearch-project/OpenSearch/issues/2229), gated by a feature flag. 
Since seg-rep is currently an incomplete implementation, the feature flag ensures that the setting is not visible to users without explicitly setting a system property. We can then continue to merge seg-rep related changes from the [feature branch](https://github.com/opensearch-project/OpenSearch/tree/feature/segment-replication) to `main` safely hidden behind the feature flag gate.
The ReplicationType setting is represented as an enum. Its …

Adds the replication type index setting, alongside a formal notion of feature flags

---

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml

Signed-off-by: Peng Huo <penghuo@gmail.com>
This PR need to backport to 2.x branch.
Correct the skip version in 370_multi_terms.yml as the [multi_terms aggregation feature has been backport to 2.x](https://github.com/opensearch-project/OpenSearch/pull/3022) and will be released in 2.1.
#1629 
PASSED: `./gradlew ':qa:mixed-cluster:v2.1.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/370_multi_terms/*}"`
PASSED, `./gradlew ':qa:mixed-cluster:v2.0.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/370_multi_terms/*}"` …

Correct the skip version, multi_terms aggregation is supported on 2.1

---

client/benchmark/README.md
client/benchmark/src/main/java/org/opensearch/client/benchmark/AbstractBenchmark.java
client/benchmark/src/main/java/org/opensearch/client/benchmark/rest/RestClientBenchmark.java

This change removes the `_type` param support in client benchmark bulk indexing actions. 
https://github.com/opensearch-project/OpenSearch/issues/3074
https://github.com/opensearch-project/OpenSearch/issues/2979

[Type removal] Remove _type support in NOOP bulk indexing from client benchmark

---

server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
server/src/main/java/org/opensearch/index/mapper/MapperService.java
server/src/main/java/org/opensearch/index/mapper/NestedPathFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
server/src/main/java/org/opensearch/indices/IndicesModule.java
server/src/main/java/org/opensearch/indices/mapper/MapperRegistry.java
server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
server/src/test/java/org/opensearch/index/mapper/FieldAliasMapperValidationTests.java
server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java
server/src/test/java/org/opensearch/index/mapper/NestedPathFieldMapperTests.java
server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
server/src/test/java/org/opensearch/index/search/nested/NestedSortingTests.java
server/src/test/java/org/opensearch/index/shard/ShardSplittingQueryTests.java
server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/nested/ReverseNestedAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
server/src/test/java/org/opensearch/search/sort/GeoDistanceSortBuilderTests.java
server/src/test/java/org/opensearch/search/sort/ScriptSortBuilderTests.java

types support is removed yet nested documents use the `_type` field to store the
path for nested documents. A new `_nested_path` metadata field mapper is added to
take the place of the `_type` field in order to remove the type dependency in
nested documents. BWC is handled in the new field mapper to ensure compatibility
with older versions.
relates #1940 
relates #2989

[Remove] Type from nested fields using new metadata field mapper

---

client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
client/rest-high-level/src/main/java/org/opensearch/client/TimedRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComponentTemplatesRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComposableIndexTemplateRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexTemplatesRequest.java
client/rest-high-level/src/test/java/org/opensearch/client/ClusterRequestConvertersTests.java
client/rest-high-level/src/test/java/org/opensearch/client/TimedRequestTests.java
client/rest-high-level/src/test/java/org/opensearch/client/indices/CloseIndexRequestTests.java
client/rest/src/main/java/org/opensearch/client/Node.java
client/rest/src/main/java/org/opensearch/client/NodeSelector.java
client/rest/src/test/java/org/opensearch/client/NodeSelectorTests.java
client/rest/src/test/java/org/opensearch/client/RestClientMultipleHostsTests.java
client/rest/src/test/java/org/opensearch/client/documentation/RestClientDocumentation.java
test/framework/src/test/java/org/opensearch/test/rest/yaml/section/ClientYamlTestSuiteTests.java

- Replace the non-inclusive terminology "master" with "cluster manager" in code comments, internal variable and method names, in `client` directory.

Replace internal usages of 'master' term in 'client' directory

---

buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
buildSrc/src/main/resources/META-INF/gradle-plugins/opensearch.pluginzip.properties
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java

Signed-off-by: pgodithi <pgodithi@amazon.com>
This change will add custom zippublish plugin, that can publish plugin zips to maven repo.
(This is a BackPort PR, merging to main branch, There is already a [PR](https://github.com/opensearch-project/OpenSearch/pull/2988) that was merged to 2.0)
https://github.com/opensearch-project/opensearch-build/issues/1916

Custom plugin backport to main branch

---

buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
buildSrc/src/main/resources/META-INF/gradle-plugins/opensearch.pluginzip.properties
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java

Signed-off-by: pgodithi <pgodithi@amazon.com>
This change will add custom zippublish plugin, that can publish plugin zips to maven repo.
(This is a BackPort PR, merging to main branch, There is already a [PR](https://github.com/opensearch-project/OpenSearch/pull/2988) that was merged to 2.0)
https://github.com/opensearch-project/opensearch-build/issues/1916

Custom plugin backport to 2.x branch

---

server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
server/src/main/java/org/opensearch/index/mapper/NestedPathFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
server/src/main/java/org/opensearch/indices/IndicesModule.java
server/src/main/java/org/opensearch/indices/mapper/MapperRegistry.java
server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
server/src/test/java/org/opensearch/index/mapper/FieldAliasMapperValidationTests.java
server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java
server/src/test/java/org/opensearch/index/mapper/NestedPathFieldMapperTests.java
server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
server/src/test/java/org/opensearch/index/search/nested/NestedSortingTests.java
server/src/test/java/org/opensearch/index/shard/ShardSplittingQueryTests.java
server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/nested/ReverseNestedAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorTests.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
server/src/test/java/org/opensearch/search/sort/GeoDistanceSortBuilderTests.java
server/src/test/java/org/opensearch/search/sort/ScriptSortBuilderTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/6b641d2fd29b9542b94f419fc083847fa5bdf55b from https://github.com/opensearch-project/OpenSearch/pull/3004

[Backport 2.0] [Remove] Type from nested fields using new metadata field mapper

---

server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java

There is a `ClusterStateTask` with identifier `_BECOME_MASTER_TASK_` used to indicate the node to be the cluster manager node when joining the cluster.
To support inclusive language, and finally change the "master" terminology, I made the following plan:
In version 2.0:
- Deprecate the task identifier `_BECOME_MASTER_TASK_`
- Add alternative name `_BECOME_CLUSTER_MANAGER_TASK_`
- Modify the method that identify the task `isBecomeMasterTask()` to accept the 2 names
In version 3.0:
- Remove the current task identifier `_BECOME_MASTER_TASK_`
The reason not change the name in-place:
The related methods are public methods, in case there are clients that call these method in a mixed version cluster of 1.x and 2.x, this way can keep the compatibility of using these methods with version 1.x …

Rename BecomeMasterTask to BecomeClusterManagerTask in JoinTaskExecutor

---

distribution/packages/build.gradle

When using package distribution
```
./gradlew :distribution:packages:no-jdk-deb:assemble
```
When `true` this include jdk switch the boolean to the correct value
fix https://github.com/opensearch-project/OpenSearch/issues/3024

Build: do not ship jdk when no-jdk option set

---

MAINTAINERS.md

Fixing some discrepancies between names in this list and actual permissions that were introduced prior to us adding the external maintainers process.

Sync maintainers with actual permissions.

---

MAINTAINERS.md

Backport of https://github.com/opensearch-project/OpenSearch/pull/3127 to 2.x.

Sync maintainers with actual permissions. (#3127)

---

server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java
server/src/main/java/org/opensearch/cluster/coordination/CoordinationMetadata.java
server/src/main/java/org/opensearch/cluster/coordination/DetachClusterCommand.java
server/src/test/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelperTests.java
test/framework/src/main/java/org/opensearch/cluster/coordination/CoordinationStateTestCluster.java

To support inclusive language, replace "master" with "cluster manager".
- Replace public field `MUST_JOIN_ELECTED_MASTER` with `MUST_JOIN_ELECTED_CLUSTER_MANAGER` in `VotingConfiguration` class
- Rename the preserved node id `_must_join_elected_master_` to `_must_join_elected_cluster_manager_`
The original `_must_join_elected_master_` is only used as a preserved node id for "Detach Cluster Command" (https://github.com/opensearch-project/OpenSearch/blob/1.3.1/server/src/main/java/org/opensearch/cluster/coordination/DetachClusterCommand.java#L89).
"Detach Cluster Command" `./bin/opensearch-node detach-cluster` can detach a node from its cluster by resetting its cluster UUID. The node can then join another cluster with a different UUID. `_must_join_elected_master_` is set as a node id and …

Rename reserved node id '_must_join_elected_master_' to '_must_join_elected_cluster_manager_' that used by in DetachClusterCommand

---

server/src/internalClusterTest/java/org/opensearch/cluster/MinimumMasterNodesIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/SpecificMasterNodesIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/MasterDisruptionIT.java
server/src/main/java/org/opensearch/cluster/coordination/NoMasterBlockService.java
server/src/main/java/org/opensearch/discovery/SeedHostsProvider.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java
server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
test/framework/src/main/java/org/opensearch/action/support/replication/ClusterStateCreationUtils.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
test/framework/src/main/java/org/opensearch/test/RandomObjects.java
test/framework/src/test/java/org/opensearch/test/test/InternalTestClusterTests.java

To support inclusive language, replace "master" with "cluster manager".
There is no compatibility concern with this code change.
- Rename the description of ClusterBlock `NO_MASTER_BLOCK_...` from `no master` to `no cluster-manager`
- Modify all other usages of `no master` to `no cluster-manager`
A part of #1548

Rename ClusterBlock description 'no master' to 'no cluster-manager'

---

server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexUpgradeService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexUpgradeServiceTests.java

This is a very simple fix that adds a special case for the backward
compatibility message for OS 1.x/ES 7.x. This basically mirrors a
special case already codified in [Version][1]. I think this is a
reasonable fix because it allows the message to be quite verbose. It
should also only need to exist on the 2.x branch of OpenSearch since it
is a special case that will no longer exist in 3.x when the entire
LegacyESVersion concept can be removed from the code base.
[1]: https://github.com/opensearch-project/OpenSearch/blob/cb238aae616d6a0fd8f82e128a1f94c8e4e8b1f7/server/src/main/java/org/opensearch/Version.java#L398
closes #2936 …

Fix minimum index compatibility error message

---

server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java

Fix a bug where indexing timesout when extensions do not exist

[Feature/extensions] Fix a bug where indexing timesout when extensions do not exist

---

server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/3099 / commit https://github.com/opensearch-project/OpenSearch/commit/017773c62d345edac607b4474bac99f200c560f8 to `2.x` branch.
There is a `ClusterStateTask` with identifier `_BECOME_MASTER_TASK_` used to indicate the node to be the cluster manager node when joining the cluster.
To support inclusive language, and finally change the "master" terminology, I made the following plan:
In version 2.0:
- Deprecate the task identifier `_BECOME_MASTER_TASK_`
- Add alternative name `_BECOME_CLUSTER_MANAGER_TASK_`
- Modify the method that identify the task `isBecomeMasterTask()` to accept the 2 names
In version 3.0:
- Remove the current task identifier `_BECOME_MASTER_TASK_`
The reason not change the name in-place:
The related methods …

[2.x] Rename BecomeMasterTask to BecomeClusterManagerTask in JoinTaskExecutor (#3099)

---

buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java

Signed-off-by: pgodithi <pgodithi@amazon.com>
This fix will remove the following warning's during runtime
```
Execution optimizations have been disabled for task ':publishPluginZipPublicationToZipStagingRepository' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: 'opensearch-plugin-template-java/build/distributions/rename-unspecified.pom'. Reason: Task ':publishPluginZipPublicationToZipStagingRepository' uses this output of task ':generatePomFileForNebulaPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implicit_dependency for more …
```

Gradle plugin `opensearch.pluginzip` Add implicit dependency.

---

distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java

Plugin installation URL for official plugins do not consume build qualifier, causing problems with the folder structure we expose for `artifacts.opensearch.org`. 
This PR fixes it and consumes the build qualifier while populating the URL for native plugins.
Unit tests already cover this, but added manual testing into PR for readability. 
Before the fix:
```
opensearch-3.0.0-rc1 % ./bin/opensearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: …
```

Fixing plugin installation URL to consume build qualifier

---

MAINTAINERS.md

I have nominated, and maintainers have agreed to add Bukhtawar Khan (@bukhtawar) as a co-maintainer, who kindly accepted. 
Bukhtawar is the main [author](https://github.com/opendistro-for-elasticsearch/asynchronous-search/pulls?q=is%3Apr+author%3ABukhtawar+is%3Aclosed) and maintainer of [Asynchronous Search](https://github.com/opensearch-project/asynchronous-search). He has reviewed/approved significant core contributions including Indexing backpressure and search resource tracking. He personally has also made [4 feature PRs](https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+author%3ABukhtawar+is%3Aclosed) into OpenSearch, and quite a few into the version before fork. He was already actively opening issues in Elastic and is now …

Adding @Bukhtawar to OpenSearch maintainers.

---

server/src/internalClusterTest/java/org/opensearch/cluster/MinimumMasterNodesIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/SnapshotDisruptionIT.java
server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeAction.java
server/src/main/java/org/opensearch/cluster/ClusterStateTaskListener.java
server/src/main/java/org/opensearch/cluster/action/index/NodeMappingRefreshAction.java
server/src/main/java/org/opensearch/cluster/action/shard/ShardStateAction.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/main/java/org/opensearch/cluster/coordination/LeaderChecker.java
server/src/main/java/org/opensearch/cluster/coordination/NoMasterBlockService.java
server/src/main/java/org/opensearch/cluster/coordination/NodeRemovalClusterStateTaskExecutor.java
server/src/main/java/org/opensearch/cluster/coordination/Reconfigurator.java
server/src/main/java/org/opensearch/cluster/service/MasterService.java
server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
server/src/main/java/org/opensearch/gateway/GatewayService.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/repositories/fs/FsRepository.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
server/src/test/java/org/opensearch/discovery/PeerFinderTests.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

In PR https://github.com/opensearch-project/OpenSearch/pull/2575, most of the `master` terminology in log messages is replaced by `cluster-manager`, but there are a few remaining.
This PR replaces more `master` word with `cluster-manager` in `server/src/main` directory that used in log messages.
https://github.com/opensearch-project/OpenSearch/issues/2539

[2.0] Replace 'master' terminology with 'cluster manager' in log messages in 'server/src/main' directory - Part 2

---

server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteIndexInput.java
server/src/main/java/org/opensearch/index/store/RemoteIndexOutput.java
server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexInputTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexOutputTests.java

As described in the https://github.com/opensearch-project/OpenSearch/issues/2700, all the read/write operations to remote segment store will happen via `RemoteDirectory` interface. This change adds the RemoteDirectory interface along with corresponding `RemoteIndexInput` (extends IndexInput) and `RemoteIndexOutput` (extends IndexOutput) classes.
- https://github.com/opensearch-project/OpenSearch/issues/2993

[Remote Segment Store] Add RemoteDirectory interface to copy segment files to/from remote store

---

buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java

Fixing PublishTests tests when running against unclean build folders, which fails with:
```
org.opensearch.gradle.pluginzip.PublishTests > testZipPublish FAILED
java.nio.file.FileAlreadyExistsException at PublishTests.java:57
```
To reproduce, just run 1-2 times:
```
./gradlew :build-tools:test --rerun-tasks
```
N/A

Fixing PublishTests tests (running against unclean build folders)

---

buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java

Allow to configure POM for ZIP publication using DSL
```
publishing {
publications {
pluginZip(MavenPublication) { publication ->
pom {
name = pluginName
description = pluginDescription
licenses {
license {
name = "The Apache License, Version 2.0"
url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
}
}
developers {
developer {
name = "OpenSearch"
url = "https://github.com/opensearch-project/opensearch-plugin-template-java"
}
}
}
}
}
}
```
Related to https://github.com/opensearch-project/opensearch-plugin-template-java/pull/31 …

Allow to configure POM for ZIP publication

---

server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java
server/src/main/java/org/opensearch/bootstrap/jvm/DenyJvmVersionsParser.java
server/src/main/resources/org/opensearch/bootstrap/jvm/deny-jvm-versions.txt
server/src/test/java/org/opensearch/bootstrap/BootstrapChecksTests.java
server/src/test/java/org/opensearch/bootstrap/jvm/DenyJvmVersionsParserTests.java

Implements runtime version checks on startup in order to prevent running with JDK versions known to be flawed (see please [1]). The example of failed bootstrap check:
```
ERROR: [1] bootstrap checks failed
[1]: The current JVM version 11.0.13+8 is not recommended for use: for more details, please check https://github.com/opensearch-project/OpenSearch/issues/2791 and https://bugs.openjdk.java.net/browse/JDK-8259541
```
[1] https://github.com/opensearch-project/OpenSearch/issues/2791
Closes https://github.com/opensearch-project/OpenSearch/issues/3005 …

Bootstrap should implement a denylist of Java versions (ranges)

---

client/rest-high-level/src/main/java/org/opensearch/client/TimedRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComponentTemplatesRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComposableIndexTemplateRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexTemplatesRequest.java
client/rest-high-level/src/test/java/org/opensearch/client/ClusterRequestConvertersTests.java
client/rest-high-level/src/test/java/org/opensearch/client/TimedRequestTests.java
client/rest-high-level/src/test/java/org/opensearch/client/indices/CloseIndexRequestTests.java
client/rest/src/main/java/org/opensearch/client/Node.java
client/rest/src/main/java/org/opensearch/client/NodeSelector.java
client/rest/src/test/java/org/opensearch/client/NodeSelectorTests.java
client/rest/src/test/java/org/opensearch/client/RestClientMultipleHostsTests.java
client/rest/src/test/java/org/opensearch/client/documentation/RestClientDocumentation.java
test/framework/src/test/java/org/opensearch/test/rest/yaml/section/ClientYamlTestSuiteTests.java

Backport commit https://github.com/opensearch-project/OpenSearch/commit/dd7add25681b9fa206a92dceee97c69ca21948ef / PR https://github.com/opensearch-project/OpenSearch/pull/3088 to `2.x` branch.
- Replace the non-inclusive terminology "master" with "cluster manager" in code comments, internal variable and method names, in `client` directory.
A part of #1548 …

[2.x] Replace internal usages of 'master' term in 'client' directory

---

modules/lang-painless/build.gradle
modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java

The ANTLR runtime version was updated to 4.9.3 by dependabot [1] however the runtime checks have been left unchanged and fill the logs with warnings like:
```
[2022-05-12T11:59:22,540][WARN ][stderr                   ] [xxx] ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.9.3
[2022-05-12T11:59:22,565][WARN ][stderr                   ] [xxx] ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.9.3
```
Regenerated lexer and parser using:
```
./gradlew :modules:lang-painless:regenParser
```
[1]  https://github.com/opensearch-project/OpenSearch/commit/fb76361812367ed5dc4ff7aea09ec9e93610d449
N/A …

Update generated ANTLR lexer/parser to match runtime version

---

buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java

Added Adoptium JDK8 support and updated `DistroTestPlugin` JDK version used by Gradle. The JDK is used by the plugin to run distro tests, for example:
```
./gradlew :qa:os:centos-7:distroTest.linux-archive-no-jdk 
./gradlew :qa:os:ubuntu-1804:distroTest.linux-archive-no-jdk 
``` 
N/A

Added Adoptium JDK8 support and updated DistroTestPlugin JDK version used by Gradle

---

qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
qa/multi-cluster-search/build.gradle
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
qa/smoke-test-ingest-disabled/build.gradle
qa/smoke-test-plugins/src/test/resources/rest-api-spec/test/smoke_test_plugins/10_basic.yml

- Replace the non-inclusive terminology "master" with "cluster manager" in code comments, internal variable and method names, in `qa` directory.

Replace 'master' terminology with 'cluster manager' in 'qa' directory

---

modules/aggs-matrix-stats/src/yamlRestTest/resources/rest-api-spec/test/stats/10_basic.yml
modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/10_basic.yml
modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/10_basic.yml
modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/DatabaseReaderLazyLoader.java
modules/ingest-geoip/src/yamlRestTest/resources/rest-api-spec/test/ingest_geoip/10_basic.yml
modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/10_basic.yml
modules/lang-expression/src/yamlRestTest/resources/rest-api-spec/test/lang_expression/10_basic.yml
modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/10_basic.yml
modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/10_basic.yml
modules/mapper-extras/src/test/resources/org/opensearch/index/mapper/metricbeat-6.0.template.json
modules/parent-join/src/internalClusterTest/java/org/opensearch/join/aggregations/ChildrenIT.java
modules/reindex/src/test/java/org/opensearch/index/reindex/RetryTests.java
modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/90_remote.yml
modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/95_parent_join.yml
modules/repository-url/src/yamlRestTest/resources/rest-api-spec/test/repository_url/10_basic.yml
modules/transport-netty4/src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml

- Replace the non-inclusive terminology "master" with "cluster manager" in code comments, internal variable and method names, in `modules` directory.

Replace 'master' terminology with 'cluster manager' in 'modules' directory

---

plugins/discovery-azure-classic/src/yamlRestTest/resources/rest-api-spec/test/discovery_azure_classic/10_basic.yml
plugins/discovery-ec2/src/internalClusterTest/java/org/opensearch/discovery/ec2/Ec2DiscoveryUpdateSettingsTests.java
plugins/discovery-ec2/src/yamlRestTest/resources/rest-api-spec/test/discovery_ec2/10_basic.yml
plugins/discovery-gce/src/internalClusterTest/java/org/opensearch/discovery/gce/GceDiscoverTests.java
plugins/discovery-gce/src/yamlRestTest/resources/rest-api-spec/test/discovery_gce/10_basic.yml
plugins/examples/custom-significance-heuristic/src/yamlRestTest/resources/rest-api-spec/test/custom-significance-heuristic/10_basic.yml
plugins/examples/custom-suggester/src/yamlRestTest/resources/rest-api-spec/test/custom-suggester/10_basic.yml
plugins/examples/painless-whitelist/src/yamlRestTest/resources/rest-api-spec/test/painless_whitelist/10_basic.yml
plugins/examples/rescore/src/yamlRestTest/resources/rest-api-spec/test/example-rescore/10_basic.yml
plugins/examples/script-expert-scoring/src/yamlRestTest/resources/rest-api-spec/test/script_expert_scoring/10_basic.yml
plugins/ingest-attachment/src/yamlRestTest/resources/rest-api-spec/test/ingest_attachment/10_basic.yml
plugins/repository-azure/src/yamlRestTest/resources/rest-api-spec/test/repository_azure/10_basic.yml
plugins/repository-gcs/src/yamlRestTest/resources/rest-api-spec/test/repository_gcs/10_basic.yml
plugins/repository-hdfs/src/test/resources/rest-api-spec/test/hdfs_repository/10_basic.yml
plugins/repository-hdfs/src/test/resources/rest-api-spec/test/secure_hdfs_repository/10_basic.yml
plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/10_basic.yml
plugins/store-smb/src/yamlRestTest/resources/rest-api-spec/test/store_smb/10_basic.yml

- Replace the non-inclusive terminology "master" with "cluster manager" in code comments, internal variable and method names, in `plugins` directory.

Replace 'master' terminology with 'cluster manager' in 'plugins' directory

---

server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteDirectoryFactory.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java
server/src/test/java/org/opensearch/index/store/RemoteDirectoryFactoryTests.java
server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

- This change adds another Directory instance to Store. With this change, Store will have two directories: `primaryDirectory` and `secondaryDirectory`. The idea is to encapsulate RemoteDirectory in Store instead of creating a separate instance of Store, remoteStore.
- Discussing both the approaches here: https://github.com/opensearch-project/OpenSearch/issues/2994#issuecomment-1121932498
- https://github.com/opensearch-project/OpenSearch/issues/2994
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUT …

Add RemoteDirectory instance to Store as a secondary directory

---

modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.txt
server/src/main/java/org/opensearch/script/JodaCompatibleZonedDateTime.java
server/src/test/java/org/opensearch/script/JodaCompatibleZonedDateTimeTests.java

There are number of deprecated methods in `JodaCompatibleZonedDateTime` which are still available in scripts. Those should be removed since in some cases they pose significant performance overhead (due to deprecation warnings).
Closes https://github.com/opensearch-project/OpenSearch/issues/3156 and https://github.com/opensearch-project/OpenSearch/issues/3345

[Remove] Remove deprecated methods from JodaCompatibleZonedDateTime which are called by scripts

---

server/src/main/java/org/opensearch/action/search/TransportSearchAction.java

Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
Removes the hard coding for max concurrent shard requests
#3363 

Removing hard coded value of max concurrent shard requests

---

modules/reindex/src/test/resources/responses/failure_with_status.json
modules/reindex/src/test/resources/responses/rejection.json
modules/reindex/src/test/resources/responses/scroll_fully_loaded.json
modules/reindex/src/test/resources/responses/scroll_fully_loaded_1_7.json
modules/reindex/src/test/resources/responses/scroll_ok.json
modules/reindex/src/test/resources/responses/start_ok.json

Remove _type in mocked scroll hit responses
Related: https://github.com/opensearch-project/OpenSearch/issues/3131

[Type removal] _type removal from mocked responses of scroll hit tests

---

modules/ingest-common/src/main/java/org/opensearch/ingest/common/ScriptProcessor.java
modules/ingest-common/src/test/java/org/opensearch/ingest/common/ScriptProcessorTests.java
server/src/main/java/org/opensearch/ingest/ConditionalProcessor.java
server/src/main/java/org/opensearch/script/UpdateScript.java
server/src/test/java/org/opensearch/ingest/ConditionalProcessorTests.java

With removal of type in `2.0`, _type deprecation messages processor scripts is not required
Related with 
https://github.com/opensearch-project/OpenSearch/issues/2979
https://github.com/opensearch-project/OpenSearch/issues/3131

[Type removal] Remove _type deprecation from script and conditional processor

---

.github/workflows/lucene-snapshots.yml

I think the workflow is failing because the `localSettings` task is running before/in parallel to `checkJdkInternalsExportedToGradle`. 
`localSettings` generates a gradle.properties file with jvm args exporting jdk.compiler modules.
`checkJdkInternalsExportedToGradle` ensures that these modules have been exported.
I've tested this on my fork [here](https://github.com/mch2/OpenSearch/runs/6500274889?check_suite_focus=true), note my fork fails at a later step to get aws creds, I don't have it set up to complete the whole workflow.
https://github.com/opensearch-project/OpenSearch/issues/3383 …

Fix Lucene-snapshots workflow to ensure gradle settings are created first.

---

server/src/main/java/org/opensearch/threadpool/ThreadPool.java

Removed unused FIXED_AUTO_QUEUE_SIZE thread pool type, leftover of https://github.com/opensearch-project/OpenSearch/pull/3352
Part of https://github.com/opensearch-project/OpenSearch/issues/2595 

[REMOVE] Cleanup deprecated thread pool types (FIXED_AUTO_QUEUE_SIZE)

---

test/framework/src/test/java/org/opensearch/test/rest/yaml/section/ClientYamlTestSuiteTests.java
test/framework/src/test/java/org/opensearch/test/rest/yaml/section/DoSectionTests.java
test/framework/src/test/resources/rest-api-spec/test/suite1/10_basic.yml

Remove mapping types from tests; testing yaml test sections.
Related: #3131 

[Type removal] _type removal from tests of yaml tests

---

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

- This change adds implementation to `afterRefresh` method of `RemoteStoreRefreshListener`.
- After each refresh, newly created segment files are uploaded to remote segment store.
- To avoid reading remote directory every time, we keep a set of remote files in memory.
- It also deletes files from remote store that are no longer present in the local filesystem.
- https://github.com/opensearch-project/OpenSearch/issues/2995
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate …

Upload segment to remote store post refresh

---

server/src/main/java/org/opensearch/Version.java

Bumps Version.V_2_1_0 lucene version to 9.2 after backporting upgrage in #3422.

Bump version 2.1 to Lucene 9.2 after upgrade

---

server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java
server/src/test/java/org/opensearch/action/bulk/BulkRequestParserTests.java

Removes type handling in BulkRequestParser's parsing and perform related cleanup 
Related: #3131 

[Type removal] Remove type from BulkRequestParser

---

server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java

- Add optional field "discovered_cluster_manager" in the XContent Parser of `ClusterHealthResponse`. 
One benefit is JSON format of `Cluster Health API` response with `discovered_cluster_manager` field can be parsed to `ClusterHealthResponse` object.
- Add temporary unit test for the above change.
- Replace `discovered_master` to `discovered_cluster_manager` in the internal variable name from the related classes.

Rename master to cluster_manager in the XContent Parser of ClusterHealthResponse

---

server/src/test/java/org/opensearch/monitor/os/OsProbeTests.java

Backporting https://github.com/opensearch-project/OpenSearch/pull/2101 to 1.3
Addresses https://github.com/opensearch-project/OpenSearch/pull/2067#issuecomment-1135160622

[Backport] [1.3] Fixing org.opensearch.monitor.os.OsProbeTests::testLogWarnCpuMessageOnlyOnes when CGroups are not available (#2101)

---

server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java

There is a flaky test failure, caused by the newly added assertion statement by PR https://github.com/opensearch-project/OpenSearch/pull/2825, which doesn't fail the Gradle check.
Such as https://github.com/opensearch-project/OpenSearch/pull/2825#issuecomment-1137826254, https://github.com/opensearch-project/OpenSearch/pull/3359#issuecomment-1135046268 and https://github.com/opensearch-project/OpenSearch/pull/3436#issuecomment-1136543205
The reason for adding the assertion is to validate the deprecated `master` role is not in the BUILT_IN_ROLES list any more. While the "[roleMap](https://github.com/opensearch-project/OpenSearch/blob/2.0.0-rc1/server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java#L565)" variable is a static variable in class `DiscoveryNode`, the value is …

[TEST] Fix testSetAdditionalRolesCanAddDeprecatedMasterRole() by removing the initial assertion

---

modules/mapper-extras/src/main/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapper.java
modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java

Signed-off-by: Vesa Pehkonen <vesa.pehkonen@intel.com>
This fix the issue #1901
This fix the issue #1901
- [x ] New functionality includes testing.
- [x ] Commits are signed per the DCO using --signoff 

Set term vector flags to false for ._index_prefix field (#1901).

---

server/src/test/java/org/opensearch/monitor/os/OsProbeTests.java

Finally, seems to understand what is going on. The issue seems to be a tricky combination of Docker and OS versions, which implies what CGroup version is in use: v1 or v2. I was not able to reproduce the exact issue but was able to trigger the same code path and observe test to fail. 
Fixes https://github.com/opensearch-project/OpenSearch/issues/2592

[BUG] Fixing org.opensearch.monitor.os.OsProbeTests > testLogWarnCpuMessageOnlyOnes when cgroups are available but cgroup stats is not

---

server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
server/src/internalClusterTest/java/org/opensearch/recovery/TruncatedRecoveryIT.java
server/src/main/java/org/opensearch/indices/recovery/FileChunkRequest.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryState.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/recovery/RetryableTransportClient.java
server/src/main/java/org/opensearch/indices/replication/CheckpointInfoResponse.java
server/src/main/java/org/opensearch/indices/replication/GetSegmentFilesResponse.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationState.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

This PR introduces components that orchestrate the flow for Segment Replication events.  They are not currently wired up as part of this PR.  This will happen in following PRs.
- `SegmentReplicationTargetService` - orchestration component for replication events. Registers a request handler to handle file chunk requests for segrep.
- `SegmentReplicationSource `- Interface that will provide checkpoint data & copy segment files.  This PR only introduces the interface, the next PR will include an implementation where the primary shard is the source of replication.
- Request/response objects from `SegmentReplicationSource`
- `SegmentReplicationSourceFactory` - A factory class that determines the source to use for a particular shard.
Along with …

[Segment Replication] Add SegmentReplicationTargetService to orchestrate replication events.

---

server/src/main/java/org/opensearch/rest/RestController.java
server/src/test/java/org/opensearch/rest/RestControllerTests.java

Filter out invalid URI and HTTP method of a error message, which shown when there is no handler found for a REST request sent by user, so that HTML special characters `<>&"'` will not shown in the error message.
The error message is return as mine-type `application/json`, which can't contain active (script) content, so it's not a vulnerability. Besides, no browsers are going to render as html when the mine-type is that.
While the common security scanners will raise a false-positive alarm for having HTML tags in the response without escaping the HTML special characters, so the solution only aims to satisfy the code security scanners.
If the URI is valid, the error message remains.
If the URI is not valid, the change is:
old error message: `{"error":"no handler found for uri …

Filter out invalid URI and HTTP method in the error message of no handler found for a REST request

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/CheckpointInfoRequest.java
server/src/main/java/org/opensearch/indices/replication/GetSegmentFilesRequest.java
server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
server/src/main/java/org/opensearch/indices/replication/common/SegmentReplicationTransportRequest.java
server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/engine/ReadOnlyEngineTests.java
server/src/test/java/org/opensearch/index/store/StoreTests.java
server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java

Note - Throughout this code change, I've attempted to use the terms _target_ and _source_ consistently:
* _target_ - The target of the replication process i.e. the node/shard to which segment files are being _copied to_. This is typically a replica shard.
* _source_ - The source for the replication process i.e. the node/shard _from which_ segment files are fetched/sent. This is typically a primary shard.
Javadocs for the new classes call out whether the code path executes on the source or the target, in the interest of clarity.
---
This change expands on the existing `SegmentReplicationSource` interface and its corresponding Factory class by introducing an implementation where the replication source is a primary shard (`PrimaryShardReplicationSource`). These code paths execute on the …

[Segment Replication] Added source-side classes for orchestrating replication events

---

buildSrc/src/main/resources/deb/postinst.ftl
buildSrc/src/main/resources/deb/preinst.ftl

Signed-off-by: Cole White <cwhite@wikimedia.org>
Passing bash with flags to the first argument of /usr/bin/env requires its
own flag to interpret it correctly.  Rather than use `env -S` to split
the argument, have the script `set -e` to enable the same behavior
explicitly in preinst and postinst scripts.
Closes: #3492

Move bash flag to set statement

---

rest-api-spec/src/main/resources/rest-api-spec/test/bulk/11_with_deprecated_types.yml
server/src/internalClusterTest/java/org/opensearch/action/bulk/BulkIntegrationIT.java
server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
server/src/test/java/org/opensearch/action/bulk/BulkRequestParserTests.java
server/src/test/resources/org/opensearch/action/bulk/bulk-with-deprecated-types.json

Don't fail bulk request on _type field in bulk request. This change reduces the friction with external clients which still uses _type field in bulk requests. The change include creating bulk request parser with errorOnType set to false to accommodate _type params. It also add some of test cases previously removed in https://github.com/opensearch-project/OpenSearch/pull/2215 to verify the assumption
Related
https://github.com/opensearch-project/OpenSearch/pull/2215
https://github.com/opensearch-project/OpenSearch/issues/3484
```
curl localhost:9200/_bulk -H 'Content-type:application/json' -d '
{ "index" : { "_index" : "test-index", "_type":"test_type", "_id" : "1" } }
{ "field1" : "value1" }
'
```
```
{
"error": {
"root_cause": [
{
"type": …
```

[Type removal] Ignore _type field in bulk request

---

buildSrc/src/main/resources/deb/postinst.ftl
buildSrc/src/main/resources/deb/preinst.ftl

Backport https://github.com/opensearch-project/OpenSearch/commit/2fbf33555ef2bb552af2ce1fe86b6ccdcf0c74ce from https://github.com/opensearch-project/OpenSearch/pull/3494

[Backport 2.x] Move bash flag to set statement

---

buildSrc/build.gradle

Conflict resolve to latest dependency for log4j-core to avoid CVE. Main and 2.x are already using gradle 7.x which automatically brings the latest log4j-core dependency. 
```
+--- com.github.jengelman.gradle.plugins:shadow:6.0.0
|    +--- org.jdom:jdom2:2.0.6
|    +--- org.ow2.asm:asm:8.0.1
|    +--- org.ow2.asm:asm-commons:8.0.1
|    |    +--- org.ow2.asm:asm:8.0.1
|    |    +--- org.ow2.asm:asm-tree:8.0.1
|    |    |    \--- org.ow2.asm:asm:8.0.1
|    |    \--- org.ow2.asm:asm-analysis:8.0.1
|    |         \--- org.ow2.asm:asm-tree:8.0.1 (*)
|    +--- commons-io:commons-io:2.5 -> 2.7
|    +--- org.apache.ant:ant:1.9.7 -> 1.10.12 (*)
|    +--- org.codehaus.plexus:plexus-utils:3.0.24 -> 3.2.1
|    +--- …
```

[Dependency upgrade] Use log4j-core 2.17.1 to avoid CVE violation

---

buildSrc/build.gradle
buildSrc/version.properties

Fix jdom2 CVE violation
```
+--- com.github.jengelman.gradle.plugins:shadow:6.0.0
|    +--- org.jdom:jdom2:2.0.6 -> 2.0.6.1
|    +--- org.ow2.asm:asm:8.0.1
|    +--- org.ow2.asm:asm-commons:8.0.1
|    |    +--- org.ow2.asm:asm:8.0.1
|    |    +--- org.ow2.asm:asm-tree:8.0.1
|    |    |    \--- org.ow2.asm:asm:8.0.1
|    |    \--- org.ow2.asm:asm-analysis:8.0.1
|    |         \--- org.ow2.asm:asm-tree:8.0.1 (*)
```
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-o …

[Dependency upgrade] Fix jdom2 CVE violation

---

client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
server/src/main/java/org/opensearch/action/main/MainResponse.java
server/src/main/java/org/opensearch/action/main/TransportMainAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/action/main/MainActionTests.java
server/src/test/java/org/opensearch/action/main/MainResponseTests.java

This reverts commit 199fbb817c45346b40c98c23a7558aff05236920 which removed the `opensearch.http.override_main_response_version` cluster setting.
The setting was originally added so users of legacy clients would not have to upgrade their client to begin using OpenSearch 1.x. 
With 2.0 the REST API is further fragmented from legacy clients such that users are [forced to upgrade](https://github.com/opensearch-project/OpenSearch/issues/3023#issuecomment-1105681019) to the latest OpenSearch client. 
To reduce this friction OpenSearch is working on a [REST API Versioning](https://github.com/opensearch-project/OpenSearch/issues/3035) mechanism to support API compatibility with at least the legacy 7.x line; but this will not be ready until 2.2 at the earliest.
The immediate problem is that there …

Revert "[Remove] MainResponse version override cluster setting (#3031) (#3032)"

---

server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/util/FeatureFlags.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/RemoteIndexInput.java
server/src/main/java/org/opensearch/index/store/RemoteIndexOutput.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java
server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteDirectoryFactoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexInputTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexOutputTests.java
server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This PR is combining 4 commits merged to a feature branch `feature/durability-enhancements`. Following are the PRs corresponding to each commit:
- https://github.com/opensearch-project/OpenSearch/pull/3102
- https://github.com/opensearch-project/OpenSearch/pull/3243
- https://github.com/opensearch-project/OpenSearch/pull/3285
- https://github.com/opensearch-project/OpenSearch/pull/3403
- https://github.com/opensearch-project/OpenSearch/issues/2993
- https://github.com/opensearch-project/OpenSearch/issues/3141
- https://github.com/opensearch-project/OpenSearch/issues/2994
- https://github.com/opensearch-project/OpenSearch/issues/2995 …

[Remote Store] Upload segments to remote store post refresh

---

server/src/main/java/org/opensearch/Version.java

Cause by https://github.com/opensearch-project/OpenSearch/pull/3555
```
org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT > testLuceneVersionConstant FAILED
Expected: <9.3.0>
but: was <9.2.0>
at __randomizedtesting.SeedInfo.seed([7F490400E9B4F125:F22C395CCEBC326C]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:964)
at org.junit.Assert.assertThat(Assert.java:930)
at org.opensearch.qa.verify_version_constants.VerifyVersionConstantsIT.testLuceneVersionConstant(VerifyVersionConstantsIT.java:56)
```
Closes  https://github.com/opensearch-project/OpenSearch/issues/3565 …

Fixing VerifyVersionConstantsIT test failure

---

server/src/internalClusterTest/java/org/opensearch/cluster/allocation/AwarenessAllocationIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java

This Pull Request fixes the issue of unassigned shards when cluster fails to rebalance itself after a partial zonal outage recovery by adding a dynamic setting called `flat_slew` to the load_awareness decider. More details on the bug can be found on the issue
#3497 

Add flat_skew setting to node overload decider

---

server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AwarenessAllocationTests.java

…Decider
This commit fixes allocation explanation reason displaying incorrect number of awareness attributes in some cases when forced zone awareness is enabled.
This commit fixes bug in AwarenessAllocationDecider showing incorrect number of awareness attribute in allocation explanation reason. More details on the bug and how to reproduce it can be found in the issue.
https://github.com/opensearch-project/OpenSearch/issues/3413 …

Fix for bug showing incorrect awareness attributes count in AwarenessAllocationDecider

---

distribution/docker/src/test/resources/rest-api-spec/test/11_nodes.yml
rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleGenerator.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleTests.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java
server/src/test/java/org/opensearch/rest/action/cat/RestNodesActionTests.java

Signed-off-by: Yaliang Wu <ylwu@amazon.com>
Currently OpenSearch only supports several built-in nodes like data node
role. If specify unknown node role, OpenSearch node will fail to start.
This limit how to extend OpenSearch to support specific tasks. For
example, user may prefer to run ML tasks on some dedicated node which
doesn't serve as any built-in node roles. So the ML tasks won't impact
OpenSearch core function. This PR removed the limitation. So user can
specify any node role and OpenSearch will start node correctly with that
unknown role. This opens the door for plugin developer to run specific
tasks on dedicated nodes.
https://github.com/opensearch-project/OpenSearch/issues/2877
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Support dynamic node role

---

server/src/internalClusterTest/java/org/opensearch/cluster/allocation/AwarenessAllocationIT.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeLoadAwareAllocationDecider.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/allocation/NodeLoadAwareAllocationTests.java

* Add flat_skew setting to node overload decider
Backport `836a9c4910f5eb4e7fcaca5573bd3bf47073d416` from #3563

[Backport 1.x] Add flat_skew setting to node overload decider

---

server/src/test/java/org/opensearch/lucene/index/ShuffleForcedMergePolicyTests.java

Fixing potential flakiness for ShuffleForcedMergePolicyTests, first observed in https://github.com/opensearch-project/OpenSearch/pull/3556:
```
org.opensearch.lucene.index.ShuffleForcedMergePolicyTests > testDiagnostics FAILED
Expected: a value greater than <2>
but: <2> was equal to <2>
at __randomizedtesting.SeedInfo.seed([1161A2BF9C23F5EE:241F7C459E731AC7]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:964)
at org.junit.Assert.assertThat(Assert.java:930)
at org.opensearch.lucene.index.ShuffleForcedMergePolicyTests.testDiagnostics(ShuffleForcedMergePolicyTests.java:81)
2> NOTE: reproduce with: gradlew test --tests …
```

Fixing flakiness of ShuffleForcedMergePolicyTests

---

server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java
server/src/test/java/org/opensearch/search/aggregations/bucket/HistogramTests.java

Resolves a NullPointerException which occurs when the methods minBound() and maxBound
https://github.com/opensearch-project/OpenSearch/blob/8844f0590a96a791f56902b9c3e004d3beb91d10/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java#L228-L236
are called before they are set in DoubleBounds
https://github.com/opensearch-project/OpenSearch/blob/8844f0590a96a791f56902b9c3e004d3beb91d10/server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DoubleBounds.java#L154-L160
#3604  …

Fix NPE when minBound/maxBound is not set before being called.

---

server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

This changes NRTReplicationEngineTests to assert against the exact version of
SegmentInfos passed from the primary to replicas.  Under certain conditions a primary
can perform a merge while the replica is updating, making its latest segmentInfos differ
from what was passed to the replica.  It also removes the assertion against engine.segments(),
because that is always computed from the `lastCommittedSegmentInfos`, which will differ after a merge.
closes #3584  …

Fix random gradle check failure issue 3584.

---

server/src/main/java/org/opensearch/indices/RunUnderPrimaryPermit.java
server/src/main/java/org/opensearch/indices/recovery/FileChunkWriter.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/recovery/RetryableTransportClient.java
server/src/main/java/org/opensearch/indices/replication/GetSegmentFilesRequest.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/RemoteSegmentFileChunkWriter.java
server/src/main/java/org/opensearch/indices/replication/SegmentFileTransferHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
server/src/main/java/org/opensearch/indices/replication/common/SegmentReplicationTransportRequest.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/indices/recovery/RecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentFileTransferHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java

This change adds the required components to SegmentReplicationSourceService (used on primary shards to send segments to replicas) to initiate copy and react to lifecycle events.
Along with new components it refactors common file copy code from RecoverySourceHandler into reusable pieces.
Refactoring:
- Extracts RunUnderPrimaryPermit from RecoverySourceHandler to a top lvl class.
- Extracts sendFiles method from RecoverySourceHandler to another class, SegmentFileTransferHandler that is used by both RecoverySourceHandler and the segrep equivalent, SegmentReplicationSourceHandler.
- Extracts writeFileChunk into a separate interface, FileChunkWriter, that is extended by RecoveryTargetHandler.
- Moves transport layer handling of file chunks …

[Segment Replication] Add components for segment replication to perform file copy.

---

server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequest.java
server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequestBuilder.java
server/src/main/java/org/opensearch/action/support/master/AcknowledgedResponse.java
server/src/main/java/org/opensearch/action/support/master/MasterNodeOperationRequestBuilder.java
server/src/main/java/org/opensearch/action/support/master/MasterNodeReadOperationRequestBuilder.java
server/src/main/java/org/opensearch/action/support/master/MasterNodeReadRequest.java
server/src/main/java/org/opensearch/action/support/master/MasterNodeRequest.java
server/src/main/java/org/opensearch/action/support/master/ShardsAcknowledgedResponse.java
server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeAction.java
server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeReadAction.java
server/src/main/java/org/opensearch/action/support/master/info/ClusterInfoRequest.java
server/src/main/java/org/opensearch/action/support/master/info/ClusterInfoRequestBuilder.java
server/src/main/java/org/opensearch/action/support/master/info/TransportClusterInfoAction.java
server/src/main/java/org/opensearch/action/support/master/info/package-info.java
server/src/main/java/org/opensearch/action/support/master/package-info.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/3593 / commit https://github.com/opensearch-project/OpenSearch/commit/223d472e6d8ea4454cb05fba7271d213430a1a4e to `2.x` branch
To support inclusive language, the master terminology is going to be replaced by cluster manager in the code base.
In PR https://github.com/opensearch-project/OpenSearch/pull/3597, the package `org.opensearch.action.support.master` has be renamed to `org.opensearch.action.support.clustermanager`, and the classes with "master" name are renamed as well.
This PR adds the old [package](https://github.com/opensearch-project/OpenSearch/tree/2.0.0/server/src/main/java/org/opensearch/action/support/master) and classes back to keep the backwards compatibility and marks them as deprecated.
Apply 3 changes to …

[2.x] Deprecate classes in org.opensearch.action.support.master (#3593)

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

In some circumstances, when running a search operation, if the client TCP connection is closed before the search operation is completed, opensearch crashes with:
```
[2022-06-09T16:54:39,763][ERROR][org.opensearch.bootstrap.OpenSearchUncaughtExceptionHandler] fatal error in thread [opensearch[mycluster-elasticsearch-5][search][T#10]], exiting
java.lang.AssertionError: unexpected higher total ops [18] compared to expected [17]
```
I was able to reproduce the problem in tests, the failure only seems to manifest when number of requests per node is throttled, and there is an exception happening during `onPhaseDone()` execution. In this case the `onShardFailure` is unexpectedly called again, mismatching the operations counter.
Closes …

[BUG] opensearch crashes on closed client connection before search reply

---

server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeOperationRequestBuilder.java
server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeRequest.java
server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
server/src/main/java/org/opensearch/action/support/clustermanager/info/TransportClusterInfoAction.java
server/src/main/java/org/opensearch/action/support/master/MasterNodeOperationRequestBuilder.java
server/src/main/java/org/opensearch/action/support/master/MasterNodeRequest.java
server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeAction.java
server/src/main/java/org/opensearch/action/support/master/info/TransportClusterInfoAction.java

This is a follow up PR for the previous PR https://github.com/opensearch-project/OpenSearch/pull/3617 to fix the backwards compatibility.
In the PR #3617, I renamed public methods with "master" word in the new package `org.opensearch.action.support.clustermanager`, and preserved those methods by their old names in the classes of the old package `org.opensearch.action.support.master`.
This will break the compatibility in a case.
For example:
Before the class renaming: 
The class `ClusterHealthRequest` extends `MasterNodeReadRequest` extends `MasterNodeRequest`.
Class `MasterNodeRequest` has got a method `masterNodeTimeout(TimeValue)`.
Then the class `ClusterHealthRequest` can access the method `masterNodeTimeout(TimeValue)`.
After the class renaming: 
The class `ClusterHealthRequest` …

Reserve all methods with 'master' in the names in the package 'org.opensearch.action.support.clustermanager'

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/LifecycleAware.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogRecoveryRunner.java
server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
server/src/main/java/org/opensearch/index/translog/listener/CompositeTranslogEventListener.java
server/src/main/java/org/opensearch/index/translog/listener/TranslogEventListener.java
server/src/main/java/org/opensearch/index/translog/listener/package-info.java
server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
server/src/test/java/org/opensearch/index/translog/listener/TranslogListenerTests.java

The PR aims to decouple translog away from the engine. This is the first part of introducing new interfaces and implementation as a part of decoupling. The overall proposal can be reviewed at #3471
Breaks down the main decouple PR into #3471 Pluggable translog work
https://github.com/opensearch-project/OpenSearch/issues/3241

Introduce TranslogManager implementations decoupled from the Engine

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/3dba46ecd14c5b1eb18500357400d6cefafc2836 from https://github.com/opensearch-project/OpenSearch/pull/3626
Closes https://github.com/opensearch-project/OpenSearch/issues/3557

[Backport 2.0] [BUG] opensearch crashes on closed client connection before search reply

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/3dba46ecd14c5b1eb18500357400d6cefafc2836 from https://github.com/opensearch-project/OpenSearch/pull/3626
Closes https://github.com/opensearch-project/OpenSearch/issues/3557

[Backport 1.x] [BUG] opensearch crashes on closed client connection before search reply

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/3dba46ecd14c5b1eb18500357400d6cefafc2836 from https://github.com/opensearch-project/OpenSearch/pull/3626
Closes https://github.com/opensearch-project/OpenSearch/issues/3557

[Backport 1.3] [BUG] opensearch crashes on closed client connection before search reply

---

buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java

Only create SCM and URL sections if those are not provided.
Closes https://github.com/opensearch-project/OpenSearch/issues/3649

[BUG] Custom POM configuration for ZIP publication produces duplicit tags (url, scm)

---

server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
server/src/test/java/org/opensearch/common/settings/ConsistentSettingsServiceTests.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/3686 to `2.1` branch.
Revert renaming method `onMaster()` and `offMaster()` in interface `LocalNodeMasterListener`
I didn't realize that the `onMaster()` and `offMaster()` is exposed to the public, then renamed it directly to make the method name inclusive. The classes that implement the interface need to implement the method in new name, so it breaks backwards compatibility.
The original file: https://github.com/opensearch-project/OpenSearch/blob/2.0.1/server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
https://github.com/opensearch-project/OpenSearch/issues/3688 …

[2.1] Revert renaming method onMaster() and offMaster() in interface LocalNodeMasterListener

---

server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
server/src/test/java/org/opensearch/common/settings/ConsistentSettingsServiceTests.java

Revert renaming method `onMaster()` and `offMaster()` in interface `LocalNodeMasterListener`
I didn't realize that the `onMaster()` and `offMaster()` is exposed to the public, then renamed it directly to make the method name inclusive. The classes that implement the interface need to implement the method in new name, so it breaks backwards compatibility.
The original file: https://github.com/opensearch-project/OpenSearch/blob/2.0.1/server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
https://github.com/opensearch-project/OpenSearch/issues/3688 …

Revert renaming method onMaster() and offMaster() in interface LocalNodeMasterListener

---

server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
server/src/test/java/org/opensearch/common/settings/ConsistentSettingsServiceTests.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/3686 to `2.x` branch.
- Revert renaming method `onMaster()` and `offMaster()` in interface `LocalNodeMasterListener`
`onMaster()` and `offMaster()` were renamed directly to make the method name inclusive. However they are exposed to the public, then the classes that implement the interface need to implement the method in new name, so it breaks backwards compatibility.
The original file: https://github.com/opensearch-project/OpenSearch/blob/2.0.1/server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
https://github.com/opensearch-project/OpenSearch/issues/3688 …

[2.x] Revert renaming method onMaster() and offMaster() in interface LocalNodeMasterListener

---

server/src/internalClusterTest/java/org/opensearch/cluster/allocation/AwarenessAllocationIT.java

Caused by #3563 
```
org.opensearch.cluster.allocation.AwarenessAllocationIT > testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness FAILED
java.lang.AssertionError: unexpected
at org.opensearch.test.InternalTestCluster.removeExclusions(InternalTestCluster.java:1912)
at org.opensearch.test.InternalTestCluster.stopNodesAndClients(InternalTestCluster.java:1777)
at org.opensearch.test.InternalTestCluster.stopNodesAndClient(InternalTestCluster.java:1764)
at org.opensearch.test.InternalTestCluster.stopRandomNode(InternalTestCluster.java:1672)
at org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness(AwarenessAllocationIT.java:425)
Caused by:
java.util.concurrent.ExecutionException: …
```

Fixing flaky test testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness

---

.github/workflows/gradle-check.yml

Update github action gradle-check to use pull_request_target for accessing token
Since Jenkins workflow needs to be triggered through github workflow with a token, `pull_request` does not allow fork repo to read secret just to be safe, therefore change to use `pull_request_target` for this access.
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
`Workflows triggered via pull_request_target have write permission to the target repository. They also have access to target repository secrets. The same is true for workflows triggered on pull_request from a branch in the same repository, but not from external forks. The reasoning behind the latter is that it is safe to share the repository secrets if the user creating …

Update github action gradle-check to use pull_request_target for accessing token

---

gradle.properties
settings.gradle

The Gradle build cache is a cache mechanism that aims to save time by reusing outputs produced by other builds. The build cache works by storing (locally or remotely) build outputs and allowing builds to fetch these outputs from the cache when it is determined that inputs have not changed, avoiding the expensive work of regenerating them [1].
Even when used by a single developer only, the build cache can be very useful. Gradle’s incremental build feature helps to avoid work that is already done, but once you re-execute a task, any previous results are forgotten. When you are switching branches back and forth, the local results get rebuilt over and over again, even if you are building something that has already been built before. The …

Optimize Gradle builds by enabling local build caching

---

.github/workflows/gradle-check.yml

Move gradle-check code to its own scripts.
It is not easy to keep updating all the branches with any workflow changes in code.
Therefore, move the gradle check code to its own scripts.
This also attempt to upload codecoverage xml to codecov if gradle check success.
https://github.com/opensearch-project/opensearch-build/issues/2193

Move gradle-check code to its own scripts and upload codecov

---

server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
server/src/main/java/org/opensearch/cluster/coordination/NoMasterBlockService.java
server/src/test/java/org/opensearch/cluster/coordination/NoMasterBlockServiceTests.java

When there is no master in the cluster, or a node is partitioned off the cluster all writes see a 5xx, this leads to availability drop espl when there is a master quorum loss(writes do not need a quorum to succeed)
We can switch the default to only fail metadata writes as a part of index creation/dynamic mapping updates but let other writes succeed. 
https://github.com/opensearch-project/OpenSearch/issues/3045
- [] New functionality includes testing.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRI …

Changing default  no_master_block from write to metadata_write

---

server/src/main/java/org/opensearch/action/admin/cluster/remotestore/restore/RestoreRemoteStoreRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/restore/package-info.java
server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteIndexInput.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/restore/RestoreRemoteStoreRequestTests.java
server/src/test/java/org/opensearch/cluster/routing/RecoverySourceTests.java
server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
server/src/test/java/org/opensearch/index/engine/NoOpEngineRecoveryTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexInputTests.java
server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
test/framework/src/main/java/org/opensearch/cluster/routing/ShardRoutingHelper.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

- This change adds implementation for the remote store restore API.
- Currently, only segment restore is supported. Once remote translog support is added, we need to modify implementation of this API to restore data from remote translog as well.
- API endpoint is added as part of this PR: https://github.com/opensearch-project/OpenSearch/pull/3576
- This will be followed by integ tests PR which will cover end-to-end flow of segment upload and restore.
- https://github.com/opensearch-project/OpenSearch/issues/3145 …

[Remote Store] Add remote store restore API implementation

---

build.gradle

Enable XML test reports for Jenkins integration
See please https://github.com/opensearch-project/opensearch-build/pull/2304

Enable XML test reports for Jenkins integration

---

.github/workflows/auto-release.yml

Release tags are automatically published by https://github.com/opensearch-project/opensearch-build.
Github releases [1] are not published and are manually published after every release. 
This workflow automates publishing github releases.
It automatically includes the release notes. 
I've tested this manually on my fork: 
Release: https://github.com/saratvemulapalli/OpenSearch/releases/tag/5.4.6
Workflow: https://github.com/saratvemulapalli/OpenSearch/actions/runs/2632146820
[1] https://github.com/opensearch-project/OpenSearch/releases …

Adding workflow to automatically publish releases after a tag is pushed

---

release-notes/opensearch.release-notes-2.1.0.md

This PR removes incorrect heading of breaking change  in [3773](https://github.com/opensearch-project/OpenSearch/pull/3773), we incorrectly put one of the heading as Breaking changes. Breaking changes should be released only in major versions. This PR also removes one PR from 2.1.0 release notes  which was reverted.
#3773 

Removing Incorrect heading of breaking changes in 2.1.0 release notes

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/LifecycleAware.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogRecoveryRunner.java
server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
server/src/main/java/org/opensearch/index/translog/listener/CompositeTranslogEventListener.java
server/src/main/java/org/opensearch/index/translog/listener/TranslogEventListener.java
server/src/main/java/org/opensearch/index/translog/listener/package-info.java
server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
server/src/test/java/org/opensearch/index/translog/listener/TranslogListenerTests.java

Introducing TranslogManager implementations decoupled from the Engine (keeping Engine backward compatible)
Here is the Original [CR](https://github.com/opensearch-project/OpenSearch/pull/3638)

Introducing TranslogManager implementations decoupled from the Engine [2.x]

---

.github/workflows/gradle-check.yml

Ignore backport / autocut / dependentbot branches for gradle checks.
These branches come and go and are not long-lived, thus no reason to even run gradle check on push.
They can run gradle check on pull_request_target event.
https://github.com/opensearch-project/opensearch-build/issues/851

Ignore backport / autocut / dependabot branches for gradle checks on push

---

server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java

testHighWatermarkNotExceeded is failing with > 50% failure rate. There is already a [fix](https://github.com/opensearch-project/OpenSearch/pull/3561) in place, muting till the fix is merged. 
Related
https://github.com/opensearch-project/OpenSearch/issues/3579

Mute testHighWatermarkNotExceeded

---

test/fixtures/minio-fixture/Dockerfile
test/fixtures/minio-fixture/docker-compose.yml

Upgrading minio image to new version (the previous one was 3 years old).
On top of that addressing MinIO warning:
- setup ulimits
- use of static console port
- do not use deprecated argument names
With regard to static port this is related to a change MinIO introduced in RELEASE.2021-07-08T01-15-01Z where the console was embedded into the server itself. For more details visit: https://docs.min.io/minio/baremetal/console/minio-console.html
We could let the port be assigned dynamically, however, when we set it statically it can give user an option to make use of the console web UI for MinIO troubleshooting (though I think the ports still need to be exported in this case).
A minor note: the third service in docker-compose was using a bit …

Upgrade minio image version

---

build.gradle
buildSrc/src/main/java/org/opensearch/gradle/info/BuildParams.java
buildSrc/src/main/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTar.java

Fixing implausibly old time stamp 1970-01-01 00:00:00 by using the timestamp from the Git revision instead of default 0 value.
Closes https://github.com/opensearch-project/OpenSearch/issues/2412

Fixing implausibly old time stamp 1970-01-01 00:00:00 by using the timestamp from the Git revision instead of default 0 value

---

distribution/build.gradle
modules/systemd/src/main/java/org/opensearch/systemd/SystemdPlugin.java
modules/systemd/src/test/java/org/opensearch/systemd/SystemdPluginTests.java

PR to remove distribution check when using a Systemd notify service
* #3666 

Unable to use Systemd module with tar distribution

---

README.md

Adds badges to readme for different jobs listed below
1. GHA gradle check
2. GHA precommit
3. GHA validate pull request
4. Public jenkins gradle check
5. Documentation
6. Forum
#1323 
#850 

Add coverage, gha, jenkins server, documentation and forum badges

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java
gradle/wrapper/gradle-wrapper.properties

Gradle 7.5 update. As always, hitting API incompatibilities.
Closes https://github.com/opensearch-project/OpenSearch/issues/3901

Update to Gradle 7.5

---

README.md

Move badges after OpenSearch logo. Move chat/doc in front which will be useful for wider audience.
https://github.com/dreamer-89/OpenSearch/tree/update_badge_position
Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/1323
Related
https://github.com/opensearch-project/OpenSearch/issues/850

Move badges after logo & change ordering of badges

---

buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java

Docker doesn't provide the permissions to test EmptyDirTask. Similar to the Windows OS, the test should not run if it detects that environment.
The primary/reliable/consistent test of whether in a Docker container is the presence of a `.dockerenv` file in the root directory. There was mention in 2016 that this could in theory be removed in the future but it's still present 6 years later and other proposed alternatives are not consistently valid in 2022. I added two potential backup tests.
Fixes #3674  …

Don't run EmptyDirTaskTests in a Docker container

---

server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java

Adding support to register dynamic settings. 
For plugins/extensions, they can define their own settings which are propagated across the cluster. 
This PR adds support to register `Node` Scope or `Index` Scope settings at anytime. 
This feature support unlocks a part of extensions hot swap.  
This is a recreate of PR: https://github.com/opensearch-project/OpenSearch/pull/3529
#3434 

[Feature/extensions] Adding support to register settings dynamically

---

build.gradle
distribution/packages/build.gradle
gradle/missing-javadoc.gradle

This Pull Request proposes small improvements to the build script logic to improve performance and cache hit ratio in the project.
* Fixed compilation avoidance for tasks `buildNoJdkRpm` and `buildRpm` #3927
* Makes `missingJavadoc` task cacheable
* `javadoc` outputs are reusable between different environments
The configuration of the task `buildNoJdkRpm` is:
```
tasks.register('buildNoJdkRpm', Rpm) {
configure(commonRpmConfig(true, 'x64'))
}
```
The current configuration was setting the incorrect parameter `jdk` to true. This configuration was causing in incremental build scenarios the execution of the tasks. After setting the correct parameter tasks are UP-TO-DATE.
Results:
Main branch: https://scans.gradle.com/s/2wvwfoybovs3e
This PR: https://scans.gradle.com/s/jdjx4vxwgqy4w
Caching …

Build performance improvements

---

codecov.yml

Add PR code coverage requirement and default settings. Used `70%` coverage based on existing coverage which is just above 70%. 
As an improvement, project specific status checks can be added. For e.g. `server/` which contains the core logic should have strict rules and separate status checks. 
https://github.com/opensearch-project/OpenSearch/issues/1324

PR coverage requirement and default settings

---

benchmarks/src/main/java/org/opensearch/benchmark/time/NanoTimeVsCurrentTimeMillisBenchmark.java
gradle/formatting.gradle
modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexInputTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexOutputTests.java
server/src/test/java/org/opensearch/index/translog/listener/TranslogListenerTests.java
server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentFileTransferHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java

Fails the build if a regex matching a wildcard import is encountered.
https://github.com/opensearch-project/OpenSearch/issues/3767

Fail build on wildcard imports

---

benchmarks/src/main/java/org/opensearch/benchmark/time/NanoTimeVsCurrentTimeMillisBenchmark.java
gradle/formatting.gradle
modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
server/src/test/java/org/opensearch/index/translog/listener/TranslogListenerTests.java
server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/3939
https://github.com/opensearch-project/OpenSearch/issues/3767

[Backport 2.x] Fail build on wildcard imports

---

server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java
server/src/test/java/org/opensearch/extensions/ExtensionsOrchestratorTests.java

Added Unit tests for registerHandler of ClusterState, ClusterSettings and LocalNode
Part of https://github.com/opensearch-project/opensearch-sdk/issues/25

[Feature/extensions] Added unit test for createComponent workflow

---

server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java

Make the `HybridDirectory`'s list of mmap extensions configurable
via index settings instead of being hard-coded.
Set defaults to the list of currently hard-coded values for
backwards compatibility.

Make HybridDirectory MMAP Extensions Configurable

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

This change wires up segment replication under the feature flag and adds some ITs.  This PR reuses peer recovery with segment replication.  Replicas will be in sync in that they have durably persisted all docs, but will not have all docs searchable until the next refresh on the primary & replication event.
Other changes:
-   Add null check when computing max segment version in store.java.
With segment replication enabled Lucene does not set the SegmentInfos
min segment version on a refresh or flush, leaving the default value as null.  The value is only set when reading infos from a commit point.
-  Update peer recovery to set the translogUUID of replicas to the UUID generated on the primary.
This change updates the UUID when the translog …

[Segment Replication] Wire up segment replication with peer recovery and add ITs.

---

server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryState.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationLuceneIndex.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/StoreRecoveryTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoverySourceHandlerTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTargetTests.java
server/src/test/java/org/opensearch/repositories/fs/FsRepositoryTests.java
server/src/test/java/org/opensearch/rest/action/cat/RestRecoveryActionTests.java

This PR backports [PR](https://github.com/opensearch-project/OpenSearch/pull/3075) to 2.x branch and resolve conflict in RecoveryState class.

[Backport 2.x] [Segment Replication] Moving RecoveryState.Index to a top-level class and renaming

---

server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java

Signed-off-by: Piyush Daftary <pdaftary@amazon.com>
Currently during snapshot delete, deletion of [unlinked shard level blob ](https://github.com/opensearch-project/OpenSearch/blob/b9ff91d591ce4b0a23d48b291e689ca906b6ab3b/server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java#L892)is single threaded using SNAPSHOT threadpool. Hence if there is huge number of unlinked shard level blob flies, it will take considerable amount of time to clean them.
Hence I propose to make unlinked shard level blob deletion multi threaded delete the same way we do for cleaning up of [stale indices](https://github.com/opensearch-project/OpenSearch/blob/b9ff91d591ce4b0a23d48b291e689ca906b6ab3b/server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java#L1237), …

Parallelize stale blobs deletion during snapshot delete

---

CONTRIBUTING.md

A set of guidelines for contributors to help them deciding whether a feature should be included in OpenSearch.
N/A 

Add guidelines for code contributions

---

distribution/packages/src/common/systemd/systemd-entrypoint

Uses a shell environment where `-o pipefail` is available.
Closes #4005

Use bash in systemd-entrypoint shebang

---

server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/ShardGetServiceTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

The Apache Lucene 9.3 made merge-on-refresh enabled by default [1], [2].  The OpenSearch merge on refresh and merge on commit defaults have to be updated in order to accommodate this change.
Additional context, the merge-on-refresh is now fully implemented by `MergePolicy`. Some merge polices (like `TieredMergePolicy` and `LogMergePolicy`) already benefit from this right away, but for others the wrapping merge policy (like 
`MergeOnFlushMergePolicy`) still has (or could) to be applied. This pull request acknowledged the merge-on-refresh as default and also allows to disable it or supply the merge policy to be used.
[1] https://github.com/apache/lucene/pull/921
[2] https://github.com/apache/lucene/pull/935
Closes …

Update merge on refresh and merge on commit defaults in Opensearch (Lucene 9.3)

---

server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/ShardGetServiceTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/3561 to `2.x` (automatic one failed).
Closes https://github.com/opensearch-project/OpenSearch/issues/3553

[Backport] [2.x] Update merge on refresh and merge on commit defaults in Opensearch (Lucene 9.3) (#3561)

---

client/rest-high-level/src/main/java/org/opensearch/client/ClusterRequestConverters.java
client/rest-high-level/src/main/java/org/opensearch/client/IndicesRequestConverters.java
client/rest-high-level/src/main/java/org/opensearch/client/TimedRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComponentTemplatesRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComposableIndexTemplateRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexTemplatesRequest.java
client/rest-high-level/src/test/java/org/opensearch/client/TimedRequestTests.java
client/rest-high-level/src/test/java/org/opensearch/client/documentation/ClusterClientDocumentationIT.java
client/rest-high-level/src/test/java/org/opensearch/client/documentation/IndicesClientDocumentationIT.java
client/rest-high-level/src/test/java/org/opensearch/client/indices/CloseIndexRequestTests.java
client/rest/src/main/java/org/opensearch/client/Node.java
client/rest/src/main/java/org/opensearch/client/NodeSelector.java
client/sniffer/src/test/java/org/opensearch/client/sniff/OpenSearchNodesSnifferTests.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/3966 / commit https://github.com/opensearch-project/OpenSearch/commit/ccf1d15618770acd54be9b3f37e731612a42e2d6 to `2.x` branch
To support inclusive language, the `master` terminology is going to be replaced by `cluster manager` in the code base.
This PR deprecate public and protected methods/variable that contains `master` terminology in the name in `client` directory, and create alternatives.
List of public methods to be renamed in `client` directory:
```
public void setMasterTimeout(TimeValue clusterManagerTimeout)
public TimeValue masterNodeTimeout()
public TimeValue getMasterNodeTimeout()
public void setMasterNodeTimeout(@Nullable TimeValue clusterManagerNodeTimeout)
public void setMasterNodeTimeout(String …
```

[2.x] Deprecate public methods and variables that contain 'master' terminology in 'client' directory (#3966)

---

plugins/mapper-annotated-text/src/test/java/org/opensearch/search/fetch/subphase/highlight/AnnotatedTextHighlighterTests.java
rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
server/src/main/java/org/apache/lucene/search/uhighlight/CustomUnifiedHighlighter.java
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightBuilder.java
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/SearchHighlightContext.java
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
server/src/test/java/org/opensearch/lucene/search/uhighlight/CustomUnifiedHighlighterTests.java

I was not able to edit the original pull request so I open another one

[Backport 2.x] Adds a new parameter, max_analyzer_offset, for the highlighter

---

rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java

Change the version used to check if the new field is presented on the main branch.

Adds a new parameter, max_analyzer_offset, for the highlighter

---

modules/rank-eval/src/test/java/org/opensearch/index/rankeval/RankEvalResponseTests.java
server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/MinimumClusterManagerNodesIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/NoClusterManagerNodeIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
server/src/main/java/org/opensearch/cluster/coordination/NoClusterManagerBlockService.java
server/src/main/java/org/opensearch/cluster/service/ClusterService.java
server/src/main/java/org/opensearch/cluster/service/MasterService.java
server/src/main/java/org/opensearch/common/util/concurrent/BaseFuture.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java
server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
server/src/test/java/org/opensearch/cluster/InternalClusterInfoServiceSchedulingTests.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
server/src/test/java/org/opensearch/cluster/coordination/NoClusterManagerBlockServiceRenamedSettingTests.java
server/src/test/java/org/opensearch/cluster/coordination/NoClusterManagerBlockServiceTests.java
server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/test/RandomObjects.java

To support inclusive language, the `master` terminology is going to be replaced by `cluster manager` in the code base.
- Deprecated public methods and variables in class `NoMasterBlockService` and `MasterService`, and created alternative methods or variables.
- A unit test is added to validate the change of thread name that identifies the thread running update task for MasterService.
List of public methods and variables that deprecated.
In class `NoMasterBlockService`:
```
int NO_MASTER_BLOCK_ID
ClusterBlock NO_MASTER_BLOCK_WRITES
ClusterBlock NO_MASTER_BLOCK_ALL
ClusterBlock NO_MASTER_BLOCK_METADATA_WRITES
ClusterBlock getNoMasterBlock()
```
In class `MasterService`:
```
String MASTER_UPDATE_THREAD_NAME
boolean assertMasterUpdateThread()
boolean assertNotMasterUpdateThread(String reason) …
```

Deprecate public methods and variables that contain 'master' terminology in class 'NoMasterBlockService' and 'MasterService'

---

server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngineFactory.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/seqno/LocalCheckpointTracker.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/seqno/LocalCheckpointTrackerTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

This PR backports [PR](https://github.com/opensearch-project/OpenSearch/pull/3240) to 2.x branch and resolve conflict in LocalCheckpointTrackerTests,  LocalCheckpointTracker classes.
https://github.com/opensearch-project/OpenSearch/issues/3109

[Backport 2.x] [Segment Replication] Add a new Engine implementation for replicas with segment replication enabled.

---

server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
server/src/test/java/org/opensearch/cluster/InternalClusterInfoServiceSchedulingTests.java
server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerService.java
test/framework/src/main/java/org/opensearch/test/disruption/BlockClusterManagerServiceOnClusterManager.java
test/framework/src/main/java/org/opensearch/test/disruption/BusyClusterManagerServiceDisruption.java
test/framework/src/test/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerServiceTests.java

To support inclusive language, the master terminology is going to be replaced by cluster manager in the code base.
After the class `MasterService` has been deprecated and class `ClusterManagerService` has been created in https://github.com/opensearch-project/OpenSearch/pull/4022 / commit https://github.com/opensearch-project/OpenSearch/commit/740f75d2051f27cffbbbfe2b601a85db9b30328c, the classes in `test/framework` directory with name 'MasterService' can be deprecated and renamed.
- Rename the following classes in `test/framework` directory:
```
FakeThreadPoolMasterService -> FakeThreadPoolClusterManagerService
BlockMasterServiceOnMaster -> BlockClusterManagerServiceOnClusterManager
BusyMasterServiceDisruption -> BusyClusterManagerServiceDisruption
```
In the following PR, I will add back …

Rename classes with name 'MasterService' to 'ClusterManagerService' in directory 'test/framework'

---

test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolMasterService.java
test/framework/src/main/java/org/opensearch/test/disruption/BlockMasterServiceOnMaster.java
test/framework/src/main/java/org/opensearch/test/disruption/BusyMasterServiceDisruption.java

To support inclusive language, the master terminology is going to be replaced by cluster manager in the code base.
In a previous PR https://github.com/opensearch-project/OpenSearch/pull/4051, 3 classes in `test/framework` directory that contains `master` in the name were renamed:
```
FakeThreadPoolMasterService -> FakeThreadPoolClusterManagerService
BlockMasterServiceOnMaster -> BlockClusterManagerServiceOnClusterManager
BusyMasterServiceDisruption -> BusyClusterManagerServiceDisruption
```
This is a following PR to add back the classes with the old name to keep the backwards compatibility. The classes with the old name will be subclass of the classes with new name, so that maintaining one implementation can support the usage for two classes.
A part of issue …

Deprecate class FakeThreadPoolMasterService, BlockMasterServiceOnMaster and BusyMasterServiceDisruption, in 'test/framework' directory

---

server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/IndicesModule.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointRequest.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/SegmentReplicationCheckpointPublisher.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/package-info.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Backport https://github.com/opensearch-project/OpenSearch/commit/fd5a38de12cbb0fe5fca40aa833cd77ad3efdb8e from https://github.com/opensearch-project/OpenSearch/pull/3108
#3108 

[Backport 2.x] [Segment Rreplication] Adding CheckpointRefreshListener to trigger when Segment replication is turned on and Primary shard refreshes

---

modules/transport-netty4/build.gradle

The extension framework [opensearch-sdk](https://github.com/opensearch-project/opensearch-sdk) requires the [transport-netty4](https://github.com/opensearch-project/OpenSearch/tree/main/modules/transport-netty4) module as a dependency.
Fixes #3118

Publish transport-netty4 module to Central Repository

---

DEVELOPER_GUIDE.md
TESTING.md
rest-api-spec/src/main/resources/rest-api-spec/test/README.md

Replace non-inclusive word "master" in `*.md` documentation file.
Close #2694

Replace master terminology in documentation

---

server/src/internalClusterTest/java/org/opensearch/action/admin/indices/rollover/RolloverIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/allocation/AwarenessAllocationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateNumberOfReplicasIT.java
server/src/internalClusterTest/java/org/opensearch/indices/template/SimpleIndexTemplateIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
server/src/main/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalance.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AwarenessAllocationTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalanceTests.java
server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

* Making all copies a multiple of attribute count
(cherry picked from commit 82ff463fd1bc07c241c8674b72182f2875a60425)

[Backport 2.x] Making shard copy count a multiple of attribute count (#3462)

---

server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/TasksIT.java
server/src/main/java/org/opensearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java
server/src/main/java/org/opensearch/action/search/SearchShardTask.java
server/src/main/java/org/opensearch/action/search/SearchTask.java
server/src/main/java/org/opensearch/action/support/TransportAction.java
server/src/main/java/org/opensearch/cluster/ClusterModule.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/tasks/Task.java
server/src/main/java/org/opensearch/tasks/TaskManager.java
server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java
server/src/main/java/org/opensearch/tasks/ThreadResourceInfo.java
server/src/main/java/org/opensearch/threadpool/AutoQueueAdjustingExecutorBuilder.java
server/src/main/java/org/opensearch/threadpool/RunnableTaskExecutionListener.java
server/src/main/java/org/opensearch/threadpool/TaskAwareRunnable.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/main/java/org/opensearch/transport/RequestHandlerRegistry.java
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/RecordingTaskManagerListener.java
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TaskManagerTestCase.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
server/src/test/java/org/opensearch/tasks/TaskManagerTests.java
server/src/test/java/org/opensearch/tasks/TaskResourceTrackingServiceTests.java
test/framework/src/main/java/org/opensearch/test/tasks/MockTaskManager.java
test/framework/src/main/java/org/opensearch/test/tasks/MockTaskManagerListener.java
test/framework/src/main/java/org/opensearch/threadpool/TestThreadPool.java

* Support task resource tracking in OpenSearch
* Reopens changes from #2639 (reverted in #3046) to add a framework for task resource tracking. Currently, SearchTask and SearchShardTask support resource tracking but it can be extended to any other task.
* Fixed a race-condition when Task is unregistered before its threads are stopped
* Improved error handling and simplified task resource tracking completion listener
* Avoid registering listeners on already completed tasks
Signed-off-by: Ketan Verma <ketan9495@gmail.com> …

[Backport 2.x]Support task resource tracking in OpenSearch (#3982)

---

server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
server/src/internalClusterTest/java/org/opensearch/recovery/TruncatedRecoveryIT.java
server/src/main/java/org/opensearch/indices/recovery/FileChunkRequest.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryState.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
server/src/main/java/org/opensearch/indices/recovery/RetryableTransportClient.java
server/src/main/java/org/opensearch/indices/replication/CheckpointInfoResponse.java
server/src/main/java/org/opensearch/indices/replication/GetSegmentFilesResponse.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationState.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/e9b19a095c2cf90274c41aa701432a2748c03468 from https://github.com/opensearch-project/OpenSearch/pull/3439
#3112 

[Backport 2.x] [Segment Replication] Add SegmentReplicationTargetService to orchestrate replication events.

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

Current setting index.remote_store removes the flexibility of adding few sub-settings related to remote store for the same index. In the future, we can have requirements like supporting only remote trans-log, separate remote store for given index. With this change, we introduce `index.remote_store.enabled`, which will allow inclusion of all the remote_store settings under `index.remote_store`.
- https://github.com/opensearch-project/OpenSearch/issues/4059
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CON …

[Remote Store] Add support to add nested settings for remote store

---

server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
server/src/main/java/org/opensearch/action/support/clustermanager/info/TransportClusterInfoAction.java
server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
test/framework/src/main/java/org/opensearch/test/TestCluster.java

The method `protected void masterOperation(Task task, Request request, ClusterState state, ActionListener<Response> listener)` was not properly deprecated by the commit https://github.com/opensearch-project/OpenSearch/commit/2a1b239c2af8d7f333a404c66467a50dc0a52c80 / PR https://github.com/opensearch-project/OpenSearch/pull/403.
There is a problem that it doesn't make any difference to whether overriding the method `void masterOperation(Task task, Request request, ClusterState state, ActionListener<Response> listener)` or not.
The reason is the only usage for the method changed to call another method `clusterManagerOperation(task, request, clusterState, l)`, which is the default implementation for the method `masterOperation(with task param)`. There is no other usage for the method …

Fix the bug that masterOperation(with task param) is bypassed

---

server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java

Coming from https://github.com/opensearch-project/OpenSearch/issues/3988 which relies on ReplicationCheckpoint ordering for correctly identifying the furthest ahead replica. The existing `ReplicationCheckpoint#isAheadOf` is not correct as it uses `||` b/w `segmentInfosVersion` (1st) & PrimaryTerm(2nd) terms; instead of relying on 2nd term (PrimaryTerm field) `ONLY WHEN` first field (`segmentInfosVersion`) is equal.
This PR also fixes, the comparison order i.e. PrimaryTerm first followed by segmentInfosVersion; this is to prioritize active primary over stale. 
https://github.com/opensearch-project/OpenSearch/issues/3988
https://github.com/opensearch-project/OpenSearch/pull/4041
By submitting this pull request, I confirm that my contribution …

[Bug] [Segment Replication] Fix isAheadOf logic for ReplicationCheckpoint comparison

---

server/src/main/java/org/opensearch/indices/IndicesModule.java

This PR binds empty instance of SegmentReplicationCheckpointPublisher when Feature Flag is off. As SegmentReplicationCheckpointPublisher will be created even when feature flag is off, to be safe we want to bind it with empty instance.

[Segment Replication] Binding empty instance of SegmentReplicationCheckpointPublisher when Feature Flag is off

---

server/src/main/java/org/opensearch/cluster/LocalNodeClusterManagerListener.java
server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
server/src/main/java/org/opensearch/cluster/ack/AckedRequest.java
server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java

Deprecate and rename abstract methods in interface
```
void onMaster()
void offMaster()
TimeValue masterNodeTimeout()
```
#3544 
#3543 

Deprecate and rename abstract methods in interfaces that contain 'master' in name

---

server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This change disables shard idle when segment replication is enabled.
Primary shards will only push out new segments on refresh, we do not want to block this based on search behavior.
Replicas will only refresh on an externally provided SegmentInfos, so we do not want search requests to hang waiting for a refresh.
To achieve this - on replicas NRTReplicationEngine will never return that a refresh is needed, all refreshes will originate from within the engine itself.  This also avoids the step of reading and comparing isCurrent on the latest reader, which for segrep will use [StandardDirectoryReader](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/StandardDirectoryReader.java#L450) without a writer …

Disable shard idle with segment replication.

---

buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

Backporting https://github.com/opensearch-project/OpenSearch/pull/3323 and https://github.com/opensearch-project/OpenSearch/pull/4091 to 1.3
Closes https://github.com/opensearch-project/OpenSearch/issues/4011

[Backport] [1.3] OpenJDK Update (July 2022 Patch releases)

---

server/src/internalClusterTest/java/org/opensearch/index/WaitUntilRefreshIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java

Fix queries with WAIT_UNTIL refresh policy for segrep indices.  These queries are hanging because refresh listeners are not currently wired in NRTReplicationEngine.
#4118 

[Segment Replication] Fix waitUntil refresh policy for segrep enabled indices.

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

In some circumstances, when running a search operation, if the client TCP connection is closed before the search operation is completed, opensearch crashes with:
```
[2022-07-20T17:51:36,145][ERROR][org.opensearch.bootstrap.OpenSearchUncaughtExceptionHandler] fatal error in thread [opensearch[mycluster-elasticsearch-3][search][T#8]], exiting
java.lang.AssertionError: unexpected higher total ops [15] compared to expected [14]
at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:465) ~[opensearch-1.3.4.jar:1.3.4]
at org.opensearch.action.search.AbstractSearchAsyncAction.lambda$performPhaseOnShard$2(AbstractSearchAsyncAction.java:303) ~[opensearch-1.3.4.jar:1.3.4]
```
Closes …

OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

[Backport 2.2] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected 

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

[Backport 1.x] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected 

---

server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java

[Backport 1.3] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected

---

release-notes/opensearch.release-notes-2.2.0.md

* Added rough release notes for 2.2
This includes an inline sed command to rewrite PR ids to full Github URLs.
Command - git log --pretty=format:"* %s" --since=6-24-2022 | sed -E "s|(\(#([0-9]*)\))|([#\2](https://github.com/opensearch-project/opensearch/pull/\2))|g"
* Organizing 2.2.0 release notes into sections
* Removed lines from changelog that were already in 2.1.0
* Adding one last commit to release notes …

2.2.0 release notes (#4151)

---

.github/workflows/auto-release.yml

Release workflow automates releasing github tags. 
Looks like the workflow was never run because tags regex didnt match. 
Since we only push tags when there is a release, automating it to release when a tag is pushed.
Follow up of: https://github.com/opensearch-project/OpenSearch/pull/3813

Updating release workflow

---

gradle.properties

gradle check failing with java heap OutOfMemoryError
Closes https://github.com/opensearch-project/OpenSearch/issues/3973

[Bug]: gradle check failing with java heap OutOfMemoryError

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/main/java/org/opensearch/common/util/FeatureFlags.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java

Introduce Remote translog feature flag, to gate remote translog changes from breaking remote segment store development and ensuring we can selectively enable remote segment store without requiring remote translog store. This clearly decouples durability semantics from refresh based(only remote segment based where clients would need to maintain non-flushed operations) to a per operation based durability semantics
For now we want to restrict enabling remote translog to cases when only remote segment store is enabled.  …

Introduce Remote translog feature flag

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

Came from discussion in https://github.com/opensearch-project/OpenSearch/pull/4041#discussion_r939084536, this PR adds `getLatestReplicationCheckpoint` behind feature flag. 
#2212 #3988 

Add IndexShard#getLatestReplicationCheckpoint behind segrep enable feature flag

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java

Allow `remote_store.enabled=true` index setting only when replication type is set to segment replication (`replicaiton.type=SEGMENT`).
- https://github.com/opensearch-project/OpenSearch/issues/3147

[Remote Store] Add validator that forces segment replication type before enabling remote store

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java

This change fixes segrep to work with multiple shards per node by keying ongoing replications on
allocation ID.  This also updates cancel methods to ensure state is properly cleared on shard cancel.
#4129.

[Segment Replication] Fix OngoingSegmentReplications to key by allocation ID instead of DiscoveryNode.

---

server/src/main/java/org/opensearch/discovery/InitializeExtensionsRequest.java
server/src/main/java/org/opensearch/discovery/InitializeExtensionsResponse.java
server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java

Signed-off-by: mloufra <mloufra@amazon.com>
Rename method names, class names, variable names from plugin to extensions in the sdk codebase and related OpenSearch code
Equivalent PR on SDK: https://github.com/opensearch-project/opensearch-sdk/pull/72
https://github.com/opensearch-project/opensearch-sdk/issues/28

issue #28 Rename to extensions

---

server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java

- Currently, if we try to enable `index.remote_store.enabled` without setting replication type to SEGMENT, we get following error:
```
{
"error" : {
{
"type" : "illegal_argument_exception",
"reason" : "Settings index.remote_store.enabled cannot be enabled when index.replication.type is set to DOCUMENT"
}
],
"type" : "illegal_argument_exception",
"reason" : "Settings index.remote_store.enabled cannot be enabled when index.replication.type is set to DOCUMENT"
},
"status" : 400
}
```
- But this does not make the dependency of segment replication clear. With this change, we are changing the error message to:
```
{
"error" : {
{
"type" : "illegal_argument_exception",
"reason" : "To enable …
```

[Remote Store] Change remote_store setting validation message to make it more clear

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java

This PR changes the logic to ignore missing files which currently causes exception on replica. This issue happens when primary performs delete/update operations which generates extra files for older segment group. This PR also adds a unit test which exercises this code by generating actual segment group files. 
Existing logic
```
for (List<StoreFileMetadata> segmentFiles : getGroupedFilesIterable()) {
boolean consistent = true;
for (StoreFileMetadata meta : segmentFiles) {
StoreFileMetadata storeFileMetadata = recoveryTargetSnapshot.get(meta.name());
if (storeFileMetadata == null) {
consistent = false;  --> missing files (e.g. `*.liv`) makes existing segment group inconsistent
missing.add(meta);
} else if (storeFileMetadata.isSame(meta) == false) {
consistent = false;
different.add(meta); …
```

[Bug] [Segment Replication] Update store metadata recovery diff logic to ignore missing files causing exception

---

server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

- To avoid concurrency issues where two primary exists for a given shard at the same time and upload segment files which can overwrite each other, we [decided](https://github.com/opensearch-project/OpenSearch/issues/3906) to add a unique suffix (UUID) to each segment filename that is uploaded to remote segment store.
- But when we restore these segment files, we need restore them as per their original name. Also, need a mechanism to understand which segment file is a part of particular commit checkpoint. For this, we also upload a metadata file per checkpoint (refresh/commit). This metadata file contains map of original segment name to uploaded segment name.
- The above logic is implemented in `RemoteSegmentStoreDirectory` which composes two …

[Remote Store] Add RemoteSegmentStoreDirectory to interact with remote segment store

---

gradle.properties

Backport 0f2ed704577d6a8a2fa95ee7c110dd7a2b91a141 from #4150
Closes https://github.com/opensearch-project/OpenSearch/issues/3973

[Backport] [1.x] [Bug]: gradle check failing with java heap OutOfMemoryError (#4150)

---

gradle.properties

Backport 0f2ed704577d6a8a2fa95ee7c110dd7a2b91a141 from #4150
Closes https://github.com/opensearch-project/OpenSearch/issues/3973

[Backport] [1.3] [Bug]: gradle check failing with java heap OutOfMemoryError (#4150)

---

DEVELOPER_GUIDE.md

Signed-off-by: Pranav Garg <pranavgarg@gmail.com>
Adding documentation about creation of uber-JARs
https://github.com/opensearch-project/OpenSearch/issues/3702

Adding documentation about creation of uber-JARs

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/190_index_prefix_search.yml

Mixed cluster testing is failing with the new [`search with uppercase regex`](https://github.com/opensearch-project/OpenSearch/blob/280b938b562fc2088a9afa8a8547f1adb96a84a5/rest-api-spec/src/main/resources/rest-api-spec/test/search/190_index_prefix_search.yml#L86) test from #3967. This PR prevents the test from running on pre-3.0 clusters until the feature is backported.

[MUTE] search with uppercase regex in bwc testing

---

server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

The PR tries to introduce a Translog factory for supporting remote file-system backed txlog. The remote file-system backed translog will still use operations committed on local on-disk txlog and will upload the same to the remote blob store container.

Introduce TranslogFactory for Local/Remote Translog support

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

This test adds thread sleep in testDeleteOperations test to account for generic replica lag. Please check https://github.com/opensearch-project/OpenSearch/issues/4216 for more details.
https://github.com/opensearch-project/OpenSearch/issues/4216

[Segment Replication] Wait for documents to replicate to replica shards

---

server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java

This adds index shard level tests for update & delete ops while using segrep.
related #4216 
- [x ] Commits are signed per the DCO using --signoff 

Segment Replication - Add additional unit tests for update & delete ops.

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This change adds basic failover support with segment replication.  Once selected, a replica will commit its SegmentInfos and reopen a writeable engine.  The replica will also remove all other commits so that this commit is selected when the writeable engine is opened.  It is possible that this commit is not considered 'safe' by the primary, meaning its max seqNo is higher than the global cp.  While an edge case, we never want replicas to reindex with segment replication enabled, so if the global cp has not been updated yet we do not want to revert to a safe commit. This change also updates how SegmentReplicationCheckpointPublisher is wired up within IndexShard so that once promoted the new primary can publish checkpoints.
This PR does not …

Support shard promotion with Segment Replication.

---

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java

This change introduces instrumentation logging that measures the latency of the various stages of segment replication as seen by each replica. Logs have also been added to the source node for checkpoint publishing and checkpoint metadata responses. All logging is currently at the TRACE level.
Part of #2583 

Added timing data and more granular stages to SegmentReplicationState

---

server/src/internalClusterTest/java/org/opensearch/index/WaitUntilRefreshIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This PR backports following 12 PR's from main branch:
1. #3658 
2. #3743 
3. #4118 
4. #4112 
5. #4137 
6. #4163 
7. #4182 
8. #4185 
9. #4157 
10. #4236 
11. #4224 
12. #4237 

[Backport 2.x] [Segment Replication] Backport all PR's containing remaining segment replication changes

---

server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java

This change returns a 400 status code when a mapping with "." properties is created
Previously
```
{
"error": {
"root_cause": [
{
"type": "array_index_out_of_bounds_exception",
"reason": "Index -1 out of bounds for length 0"
}
],
"type": "array_index_out_of_bounds_exception",
"reason": "Index -1 out of bounds for length 0"
},
"status": 500
}
```
Now:
```
{
"error" : {
{
"type" : "mapper_parsing_exception",
"reason" : "Index -1 out of bounds for length 0"
}
],
"type" : "mapper_parsing_exception",
"reason" : "Index -1 out of bounds for length 0"
},
"status" : 400
}
``` …

Handles the status code for `.` properties

---

server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java
server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
test/framework/src/main/java/org/opensearch/test/gateway/TestGatewayAllocator.java

Backport of https://github.com/opensearch-project/OpenSearch/commit/d308a2925818ad89e0a85161bc6ee43c057eb6d8 

[Segment Replication] Update PrimaryShardAllocator to prefer replicas with higher replication checkpoint (#4041)

---

server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java

From Lucene's [`IndexSearcher`](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true) javaDoc:
> NOTE: The [search(org.apache.lucene.search.Query, int)](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true#search(org.apache.lucene.search.Query,int)) and [searchAfter(org.apache.lucene.search.ScoreDoc, org.apache.lucene.search.Query, int)](https://lucene.apache.org/core/9_0_0/core/org/apache/lucene/search/IndexSearcher.html?is-external=true#searchAfter(org.apache.lucene.search.ScoreDoc,org.apache.lucene.search.Query,int)) methods are configured to only count top hits accurately up to 1,000 and may return a [lower …

Fix AbstractStringFieldDataTestCase tests to account for TotalHits lower bound

---

server/src/main/java/org/opensearch/discovery/InitializeExtensionsRequest.java

Added HostAddress and Port in initial extension request for SDKClient to run.
Part of https://github.com/opensearch-project/opensearch-sdk/issues/66

[Feature/extensions] Added HostAddress and Port in initial extension request

---

server/src/main/java/org/opensearch/discovery/InitializeExtensionsRequest.java

Reverts opensearch-project/OpenSearch#4197
When originally reviewing this, I neglected to look at it in the context of https://github.com/opensearch-project/opensearch-sdk-java/pull/67
I did make some initial review requests commenting on the configurability of the fixed port (9200) when making room for a setter, but in fact if a user has customized their port in the config, this will break the SDK code in [SDK PR 67](https://github.com/opensearch-project/opensearch-sdk-java/pull/67) by using the incorrect (default) port.  To fix this, if we were to keep this change, we would additionally need to use that setter in the `ExtensionsOrchestrator` to get the current OpenSearch configured port and add it.
However, per [this comment](https://github.com/opensearch-project/opensearch-sdk-java/pull …

[Feature/extensions] Revert "[Feature/extensions] Added HostAddress and Port in initial extension request"

---

server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java

Reverts opensearch-project/OpenSearch#4251

Revert "[Backport 2.2] Handles the status code for `.` properties"

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

This PR adds update document integration tests in order to verify the fix (https://github.com/opensearch-project/OpenSearch/pull/4185) works for update operations. 
Verified without fix above, the added update IT fails with below error
```
[2022-08-16T20:03:03,300][ERROR][o.o.i.r.SegmentReplicationTargetService] [node_t1] replication failure
org.opensearch.OpenSearchException: Segment Replication failed
at org.opensearch.indices.replication.SegmentReplicationTargetService$3.onFailure(SegmentReplicationTargetService.java:235) [main/:?]
...
Caused by: java.lang.IllegalStateException: Shard [test-idx-1][0] has local copies of segments that differ from the primary
at org.opensearch.indices.replication.SegmentReplicationTarget.getFiles(SegmentRe …
```

[Segment Replication] Add update doc integ test for Segment replication

---

server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java

This code in RecoveryTarget is not invoked, all of these methods are implemented by the parent ReplicationTarget with the same behavior.

Removing dead code in RecoveryTarget.

---

.github/workflows/changelog_verifier.yml
CHANGELOG.md
CONTRIBUTING.md

- Update the head ref to changelog verifier
- Update changelog contribution guide
- N/A

Update the head ref to changelog verifier

---

.github/workflows/changelog_verifier.yml
CHANGELOG.md
CONTRIBUTING.md

* Update changelog contribution guide
* Fix reference to pull request
(cherry picked from commit 5dd79479a2ca84a633a7583eb37df07504cd8a90)
- Backports https://github.com/opensearch-project/OpenSearch/pull/4296
- N/A

Update the head ref to changelog verifier (#4296)

---

CHANGELOG.md

- Add 2.x version to changelog for tracking unreleased 2.x changes.
- N/A

Add 2.x version to CHANGELOG

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
server/src/main/java/org/opensearch/OpenSearchException.java
server/src/main/java/org/opensearch/action/support/replication/PendingReplicationActions.java
server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
server/src/main/java/org/opensearch/index/shard/PrimaryShardClosedException.java
server/src/test/java/org/opensearch/ExceptionSerializationTests.java
server/src/test/java/org/opensearch/action/support/replication/PendingReplicationActionsTests.java
server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java

This commit prevents a replica shard from being failed in the case that
a replication action to a replica is canceled due to the primary shard
being closed.
closes #803 

Do not fail replica shard due to primary closure

---

server/src/main/java/org/opensearch/discovery/InitializeExtensionsRequest.java
server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java
server/src/test/java/org/opensearch/extensions/ExtensionsOrchestratorTests.java

Companion PR: https://github.com/opensearch-project/opensearch-sdk-java/pull/103
Sends a single `DiscoveryExtension` object when initializing an extension, rather than the entire list.
Fixes https://github.com/opensearch-project/opensearch-sdk-java/issues/93

[Feature/extensions] Only send one extension info when initializing

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteIndexInput.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/index/IndexModuleTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteIndexInputTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

- RemoteSegmentStoreDirectory was added as an extension to RemoteDirectory as part of this PR: https://github.com/opensearch-project/OpenSearch/pull/4020
- In this change, we use RemoteSegmentStoreDirectory in the segment upload as well as download (restore) flow.
- https://github.com/opensearch-project/OpenSearch/issues/3906
- https://github.com/opensearch-project/OpenSearch/issues/4283

Use RemoteSegmentStoreDirectory instead of RemoteDirectory

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
buildSrc/src/test/resources/pluginzip/customizedGroupValue.gradle
buildSrc/src/test/resources/pluginzip/customizedInvalidGroupValue.gradle
buildSrc/src/test/resources/pluginzip/groupAndVersionValue.gradle
buildSrc/src/test/resources/pluginzip/missingGroupValue.gradle
buildSrc/src/test/resources/pluginzip/missingPOMEntity.gradle

When publishing Zip POM the groupId value was hard-coded to `org.opensearch.plugin` value which works fine for existing core plugins but is not convenient for other plugins (such as community plugins maintained in independent repositories).
This PR introduces a main change in where the value for the groupId is taken from. Instead of using a hard-coded value it is taken from the `project.group` value.
This PR also brings a major rework of tests in PublishTests class. Individual testing scenarios are driven by "real" gradle building scripts (utilizing `java-gradle-plugin` gradle plugin).
Closes #3692 …

Use the project.group value for Zip POM groupId value

---

CHANGELOG.md
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

The existing failure happens during `onNewCheckpoint` method invocation verification on specific checkpoint (`anotherNewCheckpoint` in this test). It might possilbly be related to a race condition in mockito where method call capture resolution is delayed. This tests passes 100% on ading a minute timeout on verification call. 
```
verify(spy, timeout(0).times(2)).onNewCheckpoint(eq(anotherNewCheckpoint), any());
```
#4312 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifi …

[Segment Replication] Add timeout on Mockito.verify to reduce flakyness in testReplicationOnDone test

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This is a backport of https://github.com/opensearch-project/OpenSearch/pull/4135. Conflicts here were around translogManager & remote store updates that are in main but not yet backported.  This backport removes those changes from the original commit.
* Support shard promotion with Segment Replication.
This change adds basic failover support with segment replication.  Once selected, a replica will commit and reopen a writeable engine.
* Add check to ensure a closed shard does not publish checkpoints.
* Clean up in SegmentReplicationIT.
* PR feedback.
* Fix merge conflict.
Signed-off-by: …

[Backport 2.x] Support shard promotion with Segment Replication. (#4135)

---

.github/workflows/changelog_verifier.yml
CHANGELOG.md

- The `activationLabel` property helps the plugin to add changes automatically to the CHANGELOG. 
- Added a new label `dependabot` to our repo, made changes to dependabot for using the new label (See: #4348) 
- The changes in this PR utilize commit options to further help with the changelog commit workflow steps to sign off the commits.
- #4319

Fixed commit workflow for dependabot PR helper

---

.github/dependabot.yml
CHANGELOG.md

- Noticed a dependabot PR which did not have the changelog automatically updated: #4319
- Adds dependabot label configuration to trigger the changelog workflow
- More details: #4331 
- N/A

Add label configuration for dependabot PRs

---

CHANGELOG.md
modules/transport-netty4/build.gradle
modules/transport-netty4/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
modules/transport-netty4/src/internalClusterTest/java/org/opensearch/http/netty4/Netty4Http2IT.java
modules/transport-netty4/src/internalClusterTest/java/org/opensearch/http/netty4/Netty4HttpRequestSizeLimitIT.java
modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpChannel.java
modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4BadRequestTests.java
modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpClient.java
modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpServerPipeliningTests.java
modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpServerTransportTests.java

Support for HTTP/2. The initial pull request adds:
- `h2c` support (HTTP/2 over clear text)
- uses HTTP/2 to HTTP codecs to keep existing handlers working  
Here are couple of examples:
- normal HTTP/1.1 request / response processing
```
$ curl http://localhost:9200 -v
*   Trying 127.0.0.1:9200...
* Connected to localhost (127.0.0.1) port 9200 (#0)
> GET / HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 560
< 
{
"name" : "runTask-0",
"cluster_name" : "runTask",
"cluster_uuid" : "oUex0RlaQ9GsNt_IemilMQ",
"version" : {
"distribution" : "opensearch",
"number" : "3.0.0-SNAPSHOT",
"build_type" …
```

Support for HTTP/2 (server-side) 

---

.github/workflows/changelog_verifier.yml
CHANGELOG.md

- Commit pushes are failing to the source branch due to token permission issues (See [here](https://github.com/opensearch-project/OpenSearch/runs/8103150811?check_suite_focus=true))
- Fixed token usage with reference from 'dependabot_pr.yml` GHA
N/A

Fix token usage for changelog helper

---

CHANGELOG.md
distribution/src/bin/opensearch-service.bat
distribution/src/bin/opensearch.bat

Backport to 2.x for https://github.com/opensearch-project/OpenSearch/pull/4305

[Backport 2.x] Bug fix for missing logs directory

---

.github/workflows/changelog_verifier.yml
CHANGELOG.md

This reverts commit c28221e0176ad3ce782c18a2b23ea2e59ed0e0a8.
- Token usage breaking workflow for all PRs
- Reverting to unblock new PRs while I work on the fix

Revert "Fix token usage for changelog helper (#4351)"

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Segment Replication.  Implement cancellation of replication events.  This caused some file handle leaks during failover because resources are not properly cleaned up.
This PR updates segment replication paths to correctly cancel replication events on the primary and replica.
- In the source service (used by primary shards), any ongoing replication event for a primary shard that is sending segments to a replica that shuts down or is promoted as a new primary are cancelled.
- In the target service (used by replica shards), any ongoing event for a replica that is promoted as the new primary or is fetching from a primary that shuts down are cancelled.
- In the target service, we now handle cancellation initiated by the local node or by …

Segment Replication - Implement segment replication event cancellation.

---

.github/pull_request_template.md
.github/workflows/changelog_verifier.yml
.github/workflows/dependabot_pr.yml
.linelint.yml
CHANGELOG.md

- Moves the depedenabot changelog plugin helper under the `dependabot_pr` workflow
- Fixes the link for changelog contributions under the pull_request_template
- #1868 

Bug fixes for dependabot changelog verifier

---

server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java
server/src/main/java/org/opensearch/extensions/RegisterTransportActionsRequest.java
server/src/test/java/org/opensearch/extensions/ExtensionsOrchestratorTests.java
server/src/test/java/org/opensearch/extensions/RegisterTransportActionsRequestTests.java

Adds support for registering Transport Actions for extensions. 
Closes https://github.com/opensearch-project/opensearch-sdk-java/issues/105

[Feature/extensions] Adding support for registering Transport Actions for extensions

---

CHANGELOG.md
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

Overload `generateHistoryOnReplica` to be able to generate only a specific `Engine.Operation.TYPE` operations as required by the `testUpdateSegments` test
Resolves #4346 

Fix randomized test failure `NRTReplicationEngineTests.testUpdateSegments`

---

server/src/main/java/org/opensearch/extensions/rest/RestExecuteOnExtensionResponse.java
server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java
server/src/test/java/org/opensearch/extensions/rest/RestExecuteOnExtensionTests.java

Companion PR: https://github.com/opensearch-project/opensearch-sdk-java/issues/114
In the initial SDK implementation, I simply returned a `String` from the Extension's REST handler to the user.  
This PR updates the (SDK API) return value to a `RestResponse` to match what a user would have received from OpenSearch itself or a plugin, including the HTTP Status Code, and the ability to return formats other than text.
As a bonus, I figured out how to test the input and output streams in the Request/Response classes and have improved those tests as well.
Fixes [SDK #112](https://github.com/opensearch-project/opensearch-sdk-java/issues/112) …

[Feature/extensions] Pass full RestResponse to user from Extension

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java

During failover, when a new primary is chosen, replica should close on-going replication with previous primary. Continuing to copy files from two different primaries can be catastrophic and lead to multiple failures e.g. shard failure. Though logically two primary can't co-exist but due to some random bug, an older primary node can continue to hold onto replica for file transfer. This change is also needed:
1. To clean local store and cleanup temporary files already copied. 
2. Interrupt the existing threads involved in replication. 
https://github.com/opensearch-project/OpenSearch/issues/4205
https://github.com/opensearch-project/OpenSearch/pull/4225
By submitting this pull request, I confirm that my contribution is made under the terms …

[Segment Replication] Add check to cancel ongoing replication with old primary on onNewCheckpoint on replica

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/4225 to 2.x.

[Backport 2.x] Implement segment replication event cancellation.

---

.github/pull_request_template.md
.github/workflows/changelog_verifier.yml
.github/workflows/dependabot_pr.yml
.linelint.yml
CHANGELOG.md

* Fix token usage for changelog helper
* Add conditional check for dependabot steps
* Add dependency section
* Bug fixes for dependabot changelog verifier
* Update the changelog
(cherry picked from commit 4a6e937b3ba120f38fa991c9c481a01daec18e94)
Backports #4364 to 2.x …

[Backport 2.x] Bug fixes for dependabot changelog verifier (#4364)

---

.github/pull_request_template.md
.github/workflows/changelog_verifier.yml
.github/workflows/dependabot_pr.yml
.linelint.yml
CHANGELOG.md

* Fix token usage for changelog helper
* Add conditional check for dependabot steps
* Add dependency section
* Bug fixes for dependabot changelog verifier
* Update the changelog
(cherry picked from commit 4a6e937b3ba120f38fa991c9c481a01daec18e94)
- Backports #4364 to 1.x …

[Backport 1.x] Bug fixes for dependabot changelog verifier (#4364)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/4365/

[Segment Replication] Bump segment infos counter before commit during replica promotion

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/indices/recovery/FileChunkWriter.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/RemoteSegmentFileChunkWriter.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java

Extend FileChunkWriter interface to allow cancellation on retryable transport client for on-going file transfers. This adds the capability that allows primary shard to cancel on going transport request. This is currently used during shard close method. 
#4205 

[Segment Replication] Extend FileChunkWriter to allow cancel on transport client

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java

Signed-off-by: Ajay Kumar Movva <movvaam@amazon.com>
Added Rest Layer Changes for PIT stats.
Service Layer Changes: [#4030 ](https://github.com/opensearch-project/OpenSearch/pull/4030)
[#1147](https://github.com/opensearch-project/OpenSearch/issues/1147)
1. Index Creation: `localhost:9200/my-index-000001/_doc/`.
2. Creation multiple PIT 's.
3. Node Stats API output PIT's
```
"search" : {
"open_contexts" : 0,
"query_total" : 0,
"query_time_in_millis" : 0,
"query_current" : 0,
"fetch_total" : 0,
"fetch_time_in_millis" : 0,
"fetch_current" : 0,
"scroll_total" : 0,
"scroll_time_in_millis" : 0,
"scroll_current" : 0,
"point_in_time_total" : 4,
"point_in_time_time_in_millis" : 379478,
"point_in_time_current" : 0,
"suggest_total" : 0,
"suggest_time_in_millis" : 0,
"suggest_current" : 0
},
```
Cat …

Added RestLayer Changes for PIT stats

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java

Manul backport of https://github.com/opensearch-project/OpenSearch/pull/4363 to 2.x

[Backport 2.x] [Segment Replication] Add check to cancel ongoing replication with old primary on onNewCheckpoint on replica

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java

Bug [#1](https://github.com/opensearch-project/OpenSearch/issues/4233)
- Currently, remote store implementation assumes repository with cluster UUID to be created before creating an index and uses this repository to store/retrieve translog and segments.
- Accessing cluster UUID in IndexService fails one of the assertions which prevent accessing cluster UUID in the same flow where we change the cluster state. More details [here](https://github.com/opensearch-project/OpenSearch/issues/4233).
- In this change, we pass repository ID while creating the index.
- With this change, following things are achieved:
- No conflicts. With current implementation, there is a possibility of existence of repository with same name as cluster UUID. With new …

[Remote Store] Add index specific setting for remote repository

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/settings/SettingsModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java

PR link to main: https://github.com/opensearch-project/OpenSearch/pull/4253
Bug [#1](https://github.com/opensearch-project/OpenSearch/issues/4233)
- Currently, remote store implementation assumes repository with cluster UUID to be created before creating an index and uses this repository to store/retrieve translog and segments.
- Accessing cluster UUID in IndexService fails one of the assertions which prevent accessing cluster UUID in the same flow where we change the cluster state. More details [here](https://github.com/opensearch-project/OpenSearch/issues/4233).
- In this change, we pass repository ID while creating the index.
- With this change, following things are achieved:
- No conflicts. With current implementation, there is a …

[Backport 2.x] [Remote Store] Add index specific setting for remote repository (#4253)

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This PR updates the existing test to fix the flakyness, which cause few recent gradle check failures. The test is modified to use `SegmentReplicationTarget` cancellation to better synchronize the test execution. 
The test also decRef on CopyState which is needed to perform the clean up operations. This occasionally fails the test due to open file handle issues.
```
MockDirectoryWrapper: cannot close: there are still 1 open files: {segments_2=1}
```
The change also moves the log statement after checkForCancel method.
Thanks @mch2 for the suggestion. …

[Semgnet Replication] Update flaky testOnNewCheckpointFromNewPrimaryCancelOngoingReplication unit test

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/CheckpointInfoResponse.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/store/StoreTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/4366 to 2.x

Segment Replication - Fix NoSuchFileException errors caused when computing metadata snapshot on primary shards.

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/4414 to 2.x

[Segment Replication] Update flaky testOnNewCheckpointFromNewPrimaryCancelOngoingReplication unit test

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java

This PR fixes timeout issue temporarily for experimental release of segment-replication.
#4392 

[Segment Replication] Fix timeout issue by calculating time needed to process getSegmentFiles.

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java

This PR fixes timeout issue by calculating time needed to process getSegmentFiles.
This is Backport PR of #4426 
#4392 

[Segment Replication] [Backport] Fix timeout issue by calculating time needed to process getSegmentFiles.

---

build.gradle
server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4328 to `2.1`

[Backport] [2.1] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)

---

CHANGELOG.md
build.gradle
server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4328 to 2.x

[Backport] [2.x] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)

---

build.gradle
server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4328 to `2.2`

[Backport] [2.2] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)

---

build.gradle
server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4328 to `2.0`

[Backport] [2.0] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/store/StoreTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This change updates replicas to commit SegmentInfos before the shard is closed, on receiving a new commit point from a primary, and when a new primary is detected. This change also makes the public commitSegmentInfos on NRTEngine obsolete, refactoring IndexShard to simply call reset on the engine.
closes https://github.com/opensearch-project/OpenSearch/issues/4178

[Segment Replication] - Update replicas to commit SegmentInfos instead of relying on segments_N from primary shards.

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/4402 to 2.x

[Backport to 2.x] [Segment Replication] - Update replicas to commit SegmentInfos instead of relying on segments_N from primary shards.

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.3.0.md

The steps taken to compile and organize these release notes is documented here - https://github.com/opensearch-project/OpenSearch/issues/4017#issuecomment-1206795641 and https://github.com/opensearch-project/OpenSearch/issues/4017#issuecomment-1206795641
I plan to backport this change to`main` and `2.x` branch.
Part of https://github.com/opensearch-project/OpenSearch/issues/4357

2.3.0 release notes

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.3.0.md

Backport of https://github.com/opensearch-project/OpenSearch/pull/4457 to 2.x

[Backport to 2.x] 2.3.0 release notes (#4457)

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.3.0.md

Backport of https://github.com/opensearch-project/OpenSearch/pull/4457 to `main`

[Backport to main] 2.3.0 release notes (#4457)

---

CHANGELOG.md
distribution/src/bin/opensearch-cli.bat
distribution/src/bin/opensearch-env.bat
distribution/src/bin/opensearch-service.bat
distribution/src/bin/opensearch.bat

[Backport 2.x] Bugfix: Allow opensearch.bat file and opensearch-env.bat files to run when install path includes a space.
#4362

[Backport 2.x] Bugfix: Allow opensearch.bat file and opensearch-env.bat files to run when install path includes a space.

---

CHANGELOG.md
distribution/src/bin/opensearch-cli.bat
distribution/src/bin/opensearch-env.bat
distribution/src/bin/opensearch-service.bat
distribution/src/bin/opensearch.bat

[Backport 2.3] Bugfix: Allow opensearch.bat file and opensearch-env.bat files to run when install path includes a space.
#4362

[Backport 2.3] Bugfix: Allow opensearch.bat file and opensearch-env.bat files to run when install path includes a space.

---

server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java

Companion PR: https://github.com/opensearch-project/opensearch-sdk-java/pull/123
Adds the ability to handle REST path parameters (named wildcards).  Most changes are on the SDK repo. However, it is necessary (see Javadoc) for the `prepareRequest()` method to indicate which parameters were consumed.  If the user provides too many parameters, they receive an error.
In local/plugin operation, simply fetching the parameter via `param(key)` consumes it.  Since the parameters are being consumed remotely, this requires communicating the list of consumed parameters, which is done in the response header (normally unused and provided for purposes such as this!)
Fixes [SDK #122](https://github.com/opensearch-project/opensearch-sdk-java/issues/122) …

[Feature/extensions] Handle named wildcards (REST path parameters)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogManager.java
server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

Add getHistoryOperationsFromTranslog method to fetch the hostory snapshot from translogs
Original issue for reference: https://github.com/opensearch-project/OpenSearch/issues/2482
[375](https://github.com/opensearch-project/cross-cluster-replication/issues/375)

Add getHistoryOperationsFromTranslog method to fetch the history snapshot from translogs

---

CHANGELOG.md
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java

On rare occasions, ResourceAwareTasksTests.testTaskIdPersistsInThreadContext would fail assertions when the response was sent before the task was unregistered.
#4358
Signed-off-by: Ketan Verma <ketan9495@gmail.com>

Fixed flaky test: ResourceAwareTasksTests.testTaskIdPersistsInThreadContext

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java

Warn future developers not to pass headers to extensions
* Related https://github.com/opensearch-project/OpenSearch/issues/4429

[Feature/extensions] Warn future developers not to pass headers to extensions

---

CHANGELOG.md
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java

Configuring to use IRSA via repository-s3 plugin for S3 access with identity file may end up with `SecurityException` due to access denied "java.lang.RuntimePermission" "accessDeclaredMembers" when trying to get snapshots.
Closes https://github.com/opensearch-project/OpenSearch/issues/4269

Getting security exception due to access denied 'java.lang.RuntimePermission' 'accessDeclaredMembers' when trying to get snapshot with S3 IRSA

---

CHANGELOG.md
distribution/tools/java-version-checker/src/main/java/org/opensearch/tools/java_version_checker/SuppressForbidden.java
distribution/tools/java-version-checker/src/main/java/org/opensearch/tools/java_version_checker/package-info.java
distribution/tools/keystore-cli/src/main/java/org/opensearch/common/settings/KeyStoreCli.java
distribution/tools/keystore-cli/src/main/java/org/opensearch/common/settings/package-info.java
distribution/tools/launchers/build.gradle
distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/package-info.java
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/PluginCli.java
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/PluginHelper.java
distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/package-info.java
gradle/missing-javadoc.gradle

Adds javadocs and removes exclusions for  `:distribution:tools:java-version-checker`, `:distribution:tools:keystore-cli`, `:distribution:tools:launchers`, and `:distribution:tools:plugin-cli`.
Relates to #221
~- [ ] New functionality includes testing.~
~- [ ] All tests pass~

[Javadoc] add missing javadocs for :distribution:tools modules

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/mapper/FieldMapper.java

This pull request ignores all malformed items, allowing the other fields to be indexed.
#4002 

Ignore all malformed objects when ignore_malformed is true

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
server/src/test/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java

PR introduces snapshots integration tests when segment replication.
https://github.com/opensearch-project/OpenSearch/issues/3695

[Segment Replication] Add snapshot and restore tests for segment replication feature

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

With remote translog, nrt segment replication and no-op replication, the need for translog on replicas become obsolete. Recovery consists of multiple steps - where replaying lucene operation (after acquiring PRRL post the last safe commit) is one of the steps. Since with segment replication, we don't really index the data, and with remote translog, the need to keep the operations in translog goes away, we can skip recovering the lucene operations.
Initiate Recovery (Existing) -
**[PR Scope]** Initiate Recovery for remote translog enabled indices -
Recovery process (Existing) -
**[PR Scope]** Recovery process for remote translog enabled indices -
Couple of open items -
- PRRL might be not required for replica recovery. This needs to looked further into. This will be fixed in #4502.
#4527 …

[Remote Store] Change behaviour in replica recovery for remote translog enabled indices

---

CHANGELOG.md
server/src/test/java/org/opensearch/index/store/StoreTests.java

In `StoreTests.testCleanupAndPreserveLatestCommitPoint()` a lock file is used during the test.  Since it is not one of the committed files, it does not appear in the commit metadata snapshot, but as it is in use during the cleanup operation, it is also not cleaned up.
This PR updates the test to ignore the presence of the lock file.
Fixes #4538
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develope …

[Segment Replication] Ignore lock file when testing cleanupAndPreserveLatestCommitPoint

---

CHANGELOG.md
qa/evil-tests/src/test/java/org/opensearch/common/logging/EvilLoggerTests.java
server/src/main/java/org/opensearch/common/logging/LogConfigurator.java

The part of code is introduced by https://github.com/elastic/elasticsearch/commit/22459576d757833d9dfbca59cb44b09fc8bd77b1.
The main purpose of the commit is to make the node name available to all loggers all the time, aims make the way of getting logger unified and simple.
The code that removed in this PR used for helping users migrate to the new usage of getting node name in log, by scanning the specific pattern setting in log4j.properties files and add the node name into the pattern.
I think the part of code can be removed safely in next major version, because:
1 there is already a warning message shown to the user:
https://github.com/opensearch-project/OpenSearch/blob/2c27dfddbdabbf064317bd315a5464ba5f41c1da/server/src/main/java/org/opensearch/common/logging/LogConfigurator.java#L257-L …

Remove deprecated code to add node name into log pattern of log4j property file

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java

Unmute RelocationIT.testRelocationWhileIndexingRandom. The linked [issue](https://github.com/opensearch-project/OpenSearch/issues/2063) in AwaitsFix has been resolved, also validated with given seed `-Dtests.seed=6158774967A60B81`
related to #2063

Unmute RelocationIT.testRelocationWhileIndexingRandom.

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/ExtensionsOrchestrator.java

Fixed javadoc warning for build failure

[Feature/extensions] Fixed javadoc warning for build failure

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
buildSrc/src/test/resources/pluginzip/customizedGroupValue.gradle
buildSrc/src/test/resources/pluginzip/customizedInvalidGroupValue.gradle
buildSrc/src/test/resources/pluginzip/missingGroupValue.gradle
buildSrc/src/test/resources/pluginzip/missingPublications.gradle
buildSrc/src/test/resources/pluginzip/publishToMavenLocal.gradle
buildSrc/src/test/resources/pluginzip/useDefaultValues.gradle

A follow-up of PR https://github.com/opensearch-project/OpenSearch/pull/4156 that brings in further simplification of the ZIP publication implementation and new tests.
It is possible to remove some of the initialization code because the work is already handled by other library under the hood (most likely by NebulaPublishPlugin).
For instance the condition to test the `groupId` presence: `if (groupId == null)` was pointless. It was never `true`. If the `project.group` is not defined the publication task fails with an exception, if there is a custom `groupId` value setup in publication config then it overrides the `project.group` as well. Tests are provided to cover these use cases.
As for the new tests they cover the following cases:
- verify that the task "publishToMavenLocal" gets …

Further simplification of the ZIP publication implementation

---

CHANGELOG.md
modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsGeoShapeAggregatorTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java

Using JDK14 (downloaded from https://jdk.java.net/archive/), I tried running ./gradlew check, and received errors like:
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java:440: warning: no description for @throws
The build then failed with "warnings found and -Werror specified".
I tried again with JDK17 and the build passed.
According to DEVELOPER_GUIDE.md, we should be able to build with JDK14, I added the missing Javadoc tag descriptions.
Fixes unit test compilation with JDK14.
None …

Add missing Javadoc tag descriptions in unit tests

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/Jdk.java

Related commit: 0e9f74e35f1255cb9ec45be3d8960aad195a9f6e
JDK dependency location is invalid for arm64 architecture. This commit sets correct location for JDK dependency for arm64 architecture.
```
Execution failed for task ':test:logger-usage:test'.
> Error while evaluating property 'javaVersion' of task ':test:logger-usage:test'
> Could not resolve all files for configuration ':jdk_provisioned_runtime'.
> Failed to transform mac-17.0.4-arm64.tar.gz (adoptium_17:mac:17.0.4) to match attributes {artifactType=directory, jdk=true, org.gradle.status=integration}.
> Could not find mac-17.0.4-arm64.tar.gz (adoptium_17:mac:17.0.4).
Searched in the following locations:
https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4+8/OpenJD …
```

Fix invalid search location of JDK for arm64

---

CHANGELOG.md
server/src/main/java/org/opensearch/identity/AccessToken.java
server/src/main/java/org/opensearch/identity/AccessTokenManager.java
server/src/main/java/org/opensearch/identity/AuthenticationManager.java
server/src/main/java/org/opensearch/identity/AuthenticationToken.java
server/src/main/java/org/opensearch/identity/Identity.java
server/src/main/java/org/opensearch/identity/Principals.java
server/src/main/java/org/opensearch/identity/StringPrincipal.java
server/src/main/java/org/opensearch/identity/Subject.java
server/src/main/java/org/opensearch/identity/noop/NoopAccessTokenManager.java
server/src/main/java/org/opensearch/identity/noop/NoopAuthenticationManager.java
server/src/main/java/org/opensearch/identity/noop/NoopSubject.java

[Feature/Identity] AccessTokenManager stubs

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/rest/ExtensionRestRequest.java
server/src/main/java/org/opensearch/extensions/rest/RestExecuteOnExtensionRequest.java
server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
server/src/test/java/org/opensearch/extensions/rest/ExtensionRestRequestTests.java

Companion PR on SDK: [#163](https://github.com/opensearch-project/opensearch-sdk-java/pull/163)
- This PR will break SDK build due to a class rename, merge these together.
- This PR will also break Extension API due to change in package location for ExtensionRestRequest. AD Extension will need to be updated
Passes the `params()` from the original `RestRequest` object to extensions.  Internally tracks the consumed params (similar to the `RestRequest` class) when they are consumed with the `param(key)` method (similar to existing plugin usage).
During the process, realized that the `RestExecuteOnExtensionRequest` class (here) completely duplicated the `ExtensionRestHandler` class (in the SDK), so removed the SDK duplicate and renamed the "Execute" class as `ExtensionRestHandler`. …

[Feature/extensions] Pass REST params and content to extensions

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
server/src/main/java/org/opensearch/snapshots/SnapshotsService.java

[Backport] [2.x] Fixed the SnapshotsInProgress error during index deletion (#4570)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java

Add getter for path field in NestedQueryBuilder
https://github.com/opensearch-project/OpenSearch/issues/4609

Add getter for path field in NestedQueryBuilder

---

.github/workflows/gradle-check.yml
CHANGELOG.md

Attempt to fix Github workflow for Gradle Check job
N/A

Attempt to fix Github workflow for Gradle Check job

---

CHANGELOG.md
server/src/main/java/org/opensearch/identity/AccessToken.java
server/src/main/java/org/opensearch/identity/AccessTokenManager.java
server/src/main/java/org/opensearch/identity/AuthenticationManager.java
server/src/main/java/org/opensearch/identity/AuthenticationToken.java
server/src/main/java/org/opensearch/identity/ExtensionTokenProcessor.java
server/src/main/java/org/opensearch/identity/Identity.java
server/src/main/java/org/opensearch/identity/PrincipalIdentifierToken.java
server/src/main/java/org/opensearch/identity/Principals.java
server/src/main/java/org/opensearch/identity/StringPrincipal.java
server/src/main/java/org/opensearch/identity/Subject.java
server/src/main/java/org/opensearch/identity/authz/AuthorizationRequest.java
server/src/main/java/org/opensearch/identity/authz/AuthorizationResponse.java
server/src/main/java/org/opensearch/identity/authz/AuthorizationStatus.java
server/src/main/java/org/opensearch/identity/authz/CheckableParameter.java
server/src/main/java/org/opensearch/identity/authz/WriteableParameter.java
server/src/main/java/org/opensearch/identity/authz/package-info.java
server/src/main/java/org/opensearch/identity/noop/NoopAccessTokenManager.java
server/src/main/java/org/opensearch/identity/noop/NoopAuthenticationManager.java
server/src/main/java/org/opensearch/identity/noop/NoopSubject.java
server/src/main/java/org/opensearch/identity/noop/package-info.java
server/src/main/java/org/opensearch/identity/package-info.java
server/src/test/java/org/opensearch/identity/ExtensionTokenProcessorTests.java
server/src/test/java/org/opensearch/identity/IdentityTests.java
server/src/test/java/org/opensearch/identity/PrincipalIdentifierTokenTests.java
server/src/test/java/org/opensearch/identity/StringPrincipalTests.java
server/src/test/java/org/opensearch/identity/authz/CheckableParameterTests.java
server/src/test/java/org/opensearch/identity/authz/WriteableParameterTests.java
server/src/test/java/org/opensearch/identity/noop/NoopAuthenticationManagerTests.java
server/src/test/java/org/opensearch/identity/noop/NoopSubjectTests.java

Switch to smaller license header
Background on this change https://github.com/opensearch-project/alerting/issues/136#issuecomment-966657180

[Feature/Identity] Switch to smaller license header

---

.github/workflows/precommit.yml
CHANGELOG.md

Taking a stab at windows precommit in GHA
Closes https://github.com/opensearch-project/OpenSearch/issues/1448

Adding precommit support for Windows

---

.github/workflows/precommit.yml
CHANGELOG.md

As we added support for windows #1448 , I just realized MacOS should also be tested. 
Part of https://github.com/opensearch-project/OpenSearch/issues/1449

Adding precommit support for MacOS (darwin)

---

CHANGELOG.md
server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java

This test fails pretty reliably if I run it on repeat. I believe the problem is that the test assumes the function will take longer than 2ms, which is likely not a valid assumption in all cases. Fortunately, I can pass in a zero duration which is guaranteed to timeout even if the system clock does not advance at all.
Also moved the assertions out of the callback into the main test method, otherwise the assertion error messages would get buried and the test report would just show a timeout error.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUT …

Fix flaky DecommissionControllerTests.testTimesOut

---

release-notes/opensearch.release-notes-1.3.6.md

This PR adds release notes for patch release 1.3.6. This is Backport PR for #4681 
N/A

[Backport 1.3]Add release notes for patch release 1.3.6

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java

Fixing 
```
> Task :publishPluginZipPublicationToMavenLocal
Execution optimizations have been disabled for task ':publishPluginZipPublicationToMavenLocal' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/home/opensearch-plugin-template-java/build/distributions/rename-unspecified.pom'. Reason: Task ':publishPluginZipPublicationToMavenLocal' uses this output of task ':generatePomFileForNebulaPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about …
```

Fixing Gradle warnings associated with publishPluginZipPublicationToXxx tasks

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdSettings.java
server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdSettingsTests.java

Removes support for using a system property to disable the automatic release 
of the write block applied when a node exceeds the flood-stage watermark.

Always auto release the flood stage block

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This PR backports #4630
#3923 

[Backport 2.x] [Segment Replication ] Add shard routing primary check when processing a checkpoint.

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/ActionFuture.java
server/src/main/java/org/opensearch/action/ActionListener.java
server/src/main/java/org/opensearch/action/ActionListenerResponseHandler.java
server/src/main/java/org/opensearch/action/ActionRequest.java
server/src/main/java/org/opensearch/action/ActionRequestBuilder.java
server/src/main/java/org/opensearch/action/ActionRequestValidationException.java
server/src/main/java/org/opensearch/action/ActionResponse.java
server/src/main/java/org/opensearch/action/ActionRunnable.java
server/src/main/java/org/opensearch/action/ActionType.java

Refactors base action classes implemented by external plugins through `ActionPlugin` from `@opensearch.internal` to `@opensearch.api` to signal extensibility to third-party developers. This should help clear confusion on which classes should be extensible through ActionPlugin.

[Refactor] Base Action class javadocs to OpenSearch.API

---

CHANGELOG.md
server/src/main/java/org/opensearch/repositories/RepositoryData.java

This `min_version` field in the RepositoryData metadata is only used for ancient snapshot generations 
and needs to be removed in the next major version. This commit sets up the removal for backwards 
compatibility support.

[Deprecate] RepositoryData.MIN_VERSION for removal in next major release

---

CHANGELOG.md
client/rest/src/main/java/org/opensearch/client/Node.java
client/rest/src/test/java/org/opensearch/client/NodeTests.java
server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java

Backport PR https://github.com/opensearch-project/OpenSearch/pull/4689 / commit https://github.com/opensearch-project/OpenSearch/commit/c1272c181e6bd96d1db725dfbbcd5ac8e6058502 to `2.x` branch
Add a new node role which is dedicated to provide search capability.
The role name is `search`.
https://github.com/opensearch-project/OpenSearch/issues/4652

[2.x] Add a new node role 'search' which is dedicated to provide search capability (#4689)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/4696/ to 2.x

[Backport] [2.x] Fixing Gradle warnings associated with publishPluginZipPublicationToXxx tasks

---

CHANGELOG.md

- Fixes the CHANGELOG.md format to match the plugin/GHA format
- #1868 

Format changelog as per plugin requirements

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/EnglishPluralStemFilter.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerTokenFilterFactoryTests.java

This originated from https://github.com/elastic/elasticsearch/issues/42892 originally authored by @markharwood (nice job Mark!). The [PR](https://github.com/elastic/elasticsearch/pull/43248/files) is licensed ALv2 and never found a home in Elasticsearch. The [improvements](https://github.com/elastic/elasticsearch/issues/42892#issuecomment-512296214) over the buggy lucene implementation are substantial so I'm opening a PR to include it in OpenSearch 2.4.

Better plural stemmer than minimal_english

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/util/FeatureFlags.java
server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommand.java
server/src/main/java/org/opensearch/index/shard/ShardStateMetadata.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/InMemoryRemoteSnapshotDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSnapshotDirectoryFactory.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/ShardPathTests.java
server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java

This commit adds a new parameter to the snapshot restore API to restore to a new type of "remote snapshot" index where, unlike traditional snapshot restores, the index data is not all downloaded to disk and instead is read on-demand at search time. The feature is functional with this commit, and includes a simple end-to-end integration test, but is far from complete. See tracking issue #2919 for the rest of the work planned/underway.
All new capabilities are gated behind a new searchable snapshot feature flag.
#4138 …

Introduce experimental searchable snapshot API

---

CHANGELOG.md
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

This test randomly fails if the enum selected isn't the same as the one choosen by the legacy constructor.

Fix assertion in test of ShardStateMetadata

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/rest/ExtensionRestRequest.java
server/src/test/java/org/opensearch/extensions/rest/ExtensionRestRequestTests.java

Companion PR: https://github.com/opensearch-project/opensearch-sdk-java/pull/192
This PR does not change the API and can be merged at any time before the companion PR even if it is still in review.
Adds a `contentParser()` method to the `ExtensionRestRequest` class to enable extensions to parse REST requests with bodies containing JSON, SMILE, YAML, or CBOR.
OpenSearch part of [SDK #178](https://github.com/opensearch-project/opensearch-sdk-java/issues/178)
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/C …

[Feature/extensions] Add contentParser method to ExtensionRestRequest

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java

Now that the searchable snapshot API change has been backported to 2.x, the version guard has to change from 3.0 to 2.4.

Update version check after backport

---

CHANGELOG.md
buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
buildSrc/src/test/java/org/opensearch/gradle/plugin/PluginBuildPluginTests.java

As per gradle [docs](https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives) apply gradle configuration to remove timestamps and package with same order for all plugins. This is required from [reproducible](https://reproducible-builds.org/) builds
This PR is a result of https://github.com/opensearch-project/opensearch-plugin-template-java/pull/38 discussion.
- [-] New functionality has been documented.
- [-] New functionality has javadoc added
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …

Apply reproducible builds to plugins

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java

Replicas are bootstrapped using the recovery path, as opposed to the restore path used for creating the primary shard. This has been broken in the initial implementation of searchable snapshots. The fix here is to put in the appropriate checks to avoid failing during recovery.
#4778

Fix recovery path for searchable snapshots

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java
server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java

This PR resolves decommission status update metadata bug where in the non leader nodes were not getting status update locally as the same object was updated during submit state update causing the diff to be 0. Detailed explanation can be found in the issue.
#4799 

Fix decommission status update to non leader nodes

---

CHANGELOG.md
buildSrc/version.properties
plugins/discovery-azure-classic/build.gradle
test/fixtures/hdfs-fixture/build.gradle

See https://github.com/advisories/GHSA-56h3-78gp-v83r. The version was previously bumped in discovery-azure-classic but hadoop-minicluster still brings in a vulnerable version of jettison. This excludes the transitive dependency and brings in the patched version 1.5.1.  This PR also moves the version declaration to version.properties.  

Exclude jettison version brought in with hadoop-minicluster.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java

Disables merge on refresh for DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark. This fixes reproducible failure on `main` and `2.x` branches:
```
./gradlew ':server:internalClusterTest' --tests "org.opensearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testRestoreSnapshotAllocationDoesNotExceedWatermark" -Dtests.seed=926BB9577ACEFB6 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-PR -Dtests.timezone=America/Virgin -Druntime.java=17
```
closes #4162

Disable merge on refresh in DiskThresholdDeciderIT

---

CHANGELOG.md
buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
buildSrc/src/test/resources/pluginzip/allProjectsGroup.gradle
buildSrc/src/test/resources/pluginzip/groupPriorityLevel.gradle

The groupId can be defined on several levels. This commit adds more tests to cover the "edge" cases.
- In one case the groupId is inherited from the top most `allprojects` section (and thus can be missing in the publications section).
- The other case is opposite, it tests that if the groupId is defined on several levels then the most internal level outweighs the other levels.
Closes: #4771

Add groupId value propagation tests for ZIP publication task

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java

Backport 49363fb06a4cbd48e6baa90f53b74764fb8ec155 from #4828

[Backport 2.x] Disable merge on refresh in DiskThresholdDeciderIT (#4828)

---

CHANGELOG.md
plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/CorruptedBlobStoreRepositoryIT.java
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/delete/DeleteSnapshotRequest.java
server/src/main/java/org/opensearch/cluster/SnapshotDeletionsInProgress.java
server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
server/src/main/java/org/opensearch/repositories/IndexMetaDataGenerations.java
server/src/main/java/org/opensearch/repositories/RepositoryData.java
server/src/main/java/org/opensearch/repositories/ShardGenerations.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
server/src/test/java/org/opensearch/repositories/RepositoryDataTests.java
test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java

Removes all stale snapshot / restore code for legacy versions prior to OpenSearch 2.0. This includes 
handling null ShardGenerations, partial concurrency, null index generations, etc. which are no longer 
supported in snapshot versions after legacy 7.5.
relates #2747
depends on #4729

[Remove] Legacy Version support from Snapshot/Restore Service

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/EnglishPluralStemFilter.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerTokenFilterFactoryTests.java

Backport c92846d0ae121db54ce740790df75b36a24f804e from #4738

[Backport 2.x] Better plural stemmer than minimal_english (#4738)

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/BalancedSingleShardTests.java

* Refactor BalancedAllocator.Balancer to LocalShardsBalancer
* Deprecate Balancer to maintain BWC
(cherry picked from commit 1d654851ff2ea50b0fbb07b7602945f3a0e4cc88)
- Backports #4761 to 2.x
- #4761 

Refactor BalancedAllocator.Balancer to LocalShardsBalancer (#4761)
