opensearch-project/OpenSearch

server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java

This change was backported to 2.x in #7945.

Update compressed cluster state version guard

---

CHANGELOG.md
buildSrc/build.gradle

Force nebula plugins to use latest org.bouncycastle:* artifacts. The new nebula plugins require Gradle 7 which will be a breaking change for `1.x`.
```
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================   
OpenSearch Build Hamster says Hello!          
Gradle Version        : 6.6.1
OS Info               : Linux 6.2.0-23-generic (amd64)     
JDK Version           : 11 (JDK)                
JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
Random Testing Seed   : F502C2130485FC41
In FIPS 140 mode      : false
=======================================                        
> Task :build-tools:dependencyInsight
org.bouncycastle:bcpg-jdk15on:1.70
variant "runtime" [                 
org.gradle.status …
```

Force nebula plugins to use latest org.bouncycastle:* artifacts

---

plugins/events-correlation-engine/src/javaRestTest/java/org/opensearch/plugin/correlation/CorrelationVectorsEngineIT.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/EventsCorrelationPlugin.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/CorrelationParamsContext.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/VectorField.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/BasePerFieldCorrelationVectorsFormat.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/CorrelationCodecService.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/CorrelationCodecVersion.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/CorrelationCodec.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/PerFieldCorrelationVectorsFormat.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapper.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/VectorFieldMapper.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/package-info.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryBuilder.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryFactory.java
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/package-info.java
plugins/events-correlation-engine/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/CorrelationParamsContextTests.java
plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/VectorFieldTests.java
plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/CorrelationCodecTests.java
plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapperTests.java
plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryBuilderTests.java
plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/settings/EventsCorrelationSettingsTests.java

adds hnsw graph based storage & query layer to events correlation engine
https://github.com/opensearch-project/OpenSearch/issues/6854

adds storage & query layer to events correlation engine

---

CHANGELOG.md
buildSrc/build.gradle

(cherry picked from commit c7511718e1ca1224ffa857f8fd211f3e7c1e6a05)
- Backports #8233 to `1.3`

[Backport 1.3] Force nebula plugins to use latest org.bouncycastle:* artifacts (#8233)

---

server/src/main/java/org/opensearch/transport/TransportService.java

The header `extension_unique_id` is being set twice, in OpenSearch and [here](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/handlers/ExtensionsInitRequestHandler.java#L56) in SDK for the case when extension is getting initialized. This header helps OpenSearch to recognize node as an extension node while doing `connectToExtensionNode`. The issue was mostly with threadContext restoring the header and trying to set it again.
Closes https://github.com/opensearch-project/opensearch-sdk-java/issues/771 …

[Extensions] Fixed duplicate extension unique id

---

server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

This PR Removes exception throw when remote store is used with system indices, which was introduced in PR #8186. Instead when system index is used with remote store we just set remote store to false and use document replication. This is a temporary workaround until issue #8158 is fixed.
Resolves #8162 

[Segment Replication + Remote Store] Removing exception throw when remote store is used with system indices

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java

Mutes flaky test until https://github.com/opensearch-project/OpenSearch/issues/7751 is resolved.

Mute Flaky Test SegmentReplicationAllocationIT.testPerIndexPrimaryAllocation

---

qa/mixed-cluster/build.gradle
qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

1. Adds segment replicatoin stats verification step by asserting `checkpoints_behind` metric from `_cat/segment_replication` API should be 0.
2. Skips test execution for 1.x bwc versions
https://github.com/opensearch-project/OpenSearch/issues/7490
Ran test 50 times locally without any failure i.e. test is not flaky
```
for i in $(seq 0 50); do echo "running $i iteration\n";  ./gradlew :qa:rolling-upgrade:v2.9.0#upgradedClusterTest --tests "org.opensearch.upgrades.IndexingIT.testIndexingWithSegRep" >> /tmp/iteration_$i; done; &
...
ubuntu@ip-172-31-49-145:~$ grep "BUILD SUCCESS" /tmp/iteration_* | wc -l
51
``` …

[Segment Replication] Update segrep bwc tests to verify replica checkpoints and skip tests for 1.x bwc versions

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java

Adds integ tests for Remote Store Stats API
NA

Add integ tests for remote store stats api

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

- Posting the [comment](https://github.com/opensearch-project/OpenSearch/issues/8100#issuecomment-1597481801) as it is: The `getLatestSegmentInfosAndCheckpoint` method is eventually invoked and failing with the call to `getEngine().config().getCodec().getName()` because the engine is already closed. The method already has logic to return empty if the shard is not open, but it is shut after this check. So we need to ensure the shard is not closed while this method is invoked or if we don't want to block shard close for this catch the error and gracefully return.
- Some of the tests in `SegmentReplicationIT` are flaky. This was observed while debugging flakiness in `SegmentReplicationRemoteStoreIT` which extends SegmentReplicationIT with remote store settings.
- Reproducing the flakiness is …

Fix SegmentReplication flaky integ tests 

---

server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java

This PR adds integration tests for Remote Segment Backpressure. 
Resolves #7527

[Remote Store] Add remote segment upload backpressure integ tests

---

libs/core/src/main/java/org/opensearch/Version.java

Fix Apache Lucene verson for 2.9.0 release (after https://github.com/opensearch-project/OpenSearch/pull/8277)
Closes https://github.com/opensearch-project/OpenSearch/issues/8289

Fix Apache Lucene verson for 2.9.0 release

---

rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.restore.json
server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/main/java/org/opensearch/repositories/FilterRepository.java
server/src/main/java/org/opensearch/repositories/Repository.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestTests.java
server/src/test/java/org/opensearch/cluster/routing/RecoverySourceTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java

Changes required in Restore Snapshot Flow for [Snapshot Interoperability with Remote Store](https://github.com/opensearch-project/OpenSearch/issues/6575).

[Snapshot Interop] Add Changes in Restore Snapshot Flow for remote store Interoperability

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
server/src/test/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheActionTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java

- Removes concurrency based minimum file cache size restriction which limits based on per segment capacity.
- Details on #8259
Resolves #8259

Remove concurrency based minimum file cache size restriction

---

CHANGELOG.md
libs/geo/src/main/java/org/opensearch/geometry/GeometryCollection.java
modules/geo/build.gradle
modules/geo/src/internalClusterTest/java/org/opensearch/geo/GeoModulePluginIntegTestCase.java
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/MissingValueIT.java
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/common/GeoBoundsHelper.java
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoAggregatorModulePluginTestCase.java
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsITTestCase.java
modules/geo/src/main/java/org/opensearch/geo/GeoModulePlugin.java
modules/geo/src/main/java/org/opensearch/geo/algorithm/PolygonGenerator.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsGeoShapeAggregator.java
modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsGeoShapeAggregatorTests.java
modules/geo/src/test/java/org/opensearch/geo/tests/common/RandomGeoGeometryGenerator.java
server/src/main/java/org/opensearch/common/geo/GeoShapeDocValue.java
server/src/main/java/org/opensearch/common/geo/ShapeDocValue.java
server/src/main/java/org/opensearch/index/fielddata/FieldData.java
server/src/main/java/org/opensearch/index/fielddata/GeoShapeValue.java
server/src/main/java/org/opensearch/index/fielddata/LeafGeoShapeFieldData.java
server/src/main/java/org/opensearch/index/fielddata/plain/AbstractGeoShapeIndexFieldData.java
server/src/main/java/org/opensearch/index/fielddata/plain/AbstractLeafGeoShapeFieldData.java
server/src/main/java/org/opensearch/index/fielddata/plain/GeoShapeDVLeafFieldData.java
server/src/main/java/org/opensearch/index/mapper/AbstractGeometryFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/GeoShapeFieldMapper.java
server/src/main/java/org/opensearch/search/aggregations/support/CoreValuesSourceType.java
server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
server/src/test/java/org/opensearch/common/util/CollectionUtilsTests.java
server/src/test/java/org/opensearch/index/fielddata/GeoShapeValueTests.java
server/src/test/java/org/opensearch/index/mapper/GeoShapeFieldMapperTests.java
server/src/test/java/org/opensearch/search/aggregations/support/CoreValuesSourceTypeTests.java

Enables geo_bounds aggregation to work with geo_shape field types.
This enhancement includes:
* Addition of Doc values on the GeoShape Field.
* Addition of GeoShape ValueSource level code interfaces for accessing the DocValues.
* Addition of Missing Value feature in the GeoShape Aggregations.
Resolves #3980

[Backport 2.x]Add GeoBounds aggregation on GeoShape field type.(#3980) (#4266)

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

This change improves the `testIndexingWithSegRep` bwc test by relying on _cat/segments API to verify shard store and doc count and is preferred because of below reasons:
1. `index/_stats` API does not return data for all shards specially when it is newly created (this is probably not all shard copy have documents and thus no stats), thus test fails as mentioned here https://github.com/opensearch-project/OpenSearch/pull/7626#issuecomment-1604534314
2. The only reason for `_stats` was to build nodeId to shardId map so that targeted `_search` can be made using `"_shards:" + shardNumber + "|_only_nodes:" + nodeId` preference. This is unnecessary two step process.
3. _cat/segments resonates better with segment replication as we are verifying segment names and doc count. …

[Segment Replication] Update bwc test to rely on segments for verification

---

server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java

Mutes `SegmentReplicationUsingRemoteStoreIT.testPressureServiceStats` which has repeatedly failed and loss a lot of unrelated PR time.
relates #7592

[Mute] SegRepUsingRemoteStoreIT.testPressureServiceStats

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregator.java
server/src/test/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregatorTests.java

The implementation for the 'buildEmptyAggregation' method for MultiTermsAggregator was incomplete and was simply returning null.  This change completes the implementation for this method and adds a YAML REST test case for it.
I have another PR that has a unit test for this change.  I want to get feedback on that separately from this PR.
#7089 
#5785 
- [x ] Commits are signed per the DCO using --signoff

Implement buildEmptyAggregations for MultiTermsAggregator (#7089)

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/bytes/AbstractBytesReference.java
test/framework/src/main/java/org/opensearch/common/bytes/AbstractBytesReferenceTestCase.java

* Check UTF16 string size before converting to string to avoid OOME
Backport - https://github.com/opensearch-project/OpenSearch/pull/7963

[Backport -2.x] Check UTF16 string size before converting to String to avoid OOME

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/fielddata/IndexFieldData.java
server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/FloatValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/IntValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java

[Backport 2.x] Enable Point based optimization for custom comparators (#8168)

---

test/fixtures/hdfs-fixture/build.gradle

Fix HDFS fixture by excluding BouncyCastle
After https://github.com/opensearch-project/OpenSearch/pull/8247 got merged, we found out that `hdfs-fixture` transitivity bring `xxx-jdk15on` artifacts nonetheless, excluding them:
```
org.bouncycastle:bcpkix-jdk15on:1.68
variant "runtime" [
org.gradle.status              = release (not requested)
org.gradle.usage               = java-runtime
org.gradle.libraryelements     = jar
org.gradle.category            = library
Requested attributes not found in the selected variant:
org.gradle.dependency.bundling = external
org.gradle.jvm.version         = 8
]
org.bouncycastle:bcpkix-jdk15on:1.68
\--- org.apache.hadoop:hadoop-yarn-server-web-proxy:3.3.5
+--- org.apache.hadoop:hadoop-minicluster:3.3.5
|    \--- runtimeClasspath
+--- …
```

Fix HDFS fixture by excluding BouncyCastle

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java

- Fix primary balance flaky test
- Asserts for a window within threshold of -1 and +1 of the average value because of the general variance
Tested with the following seeds from the failure mentions
- CC0A02835F66CD86 (https://build.ci.opensearch.org/job/gradle-check/16741/testReport/org.opensearch.indices.replication/SegmentReplicationAllocationIT/testPerIndexPrimaryAllocation_4/)
- 9631830FBDB9647 (https://build.ci.opensearch.org/job/gradle-check/16211/testReport/junit/org.opensearch.indices.replication/SegmentReplicationAllocationIT/testPerIndexPrimaryAllocation/) 
- 2F83A4C6F3228287 (https://build.ci.opensearch.org/job/gradle-check/17287/testReport/org.opensearch.indices.replication/SegmentReplicationAllocationIT/testPerIndexPrimaryAllocation/)
Resolves #7751 …

Fix primary balance flaky test

---

rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_empty.yml

Fix search.aggregation/60_empty.yml test case (fails on BWC runs):
```
java.lang.AssertionError: Failure at [search.aggregation/60_empty:24]: expected [2xx] status code but api [search] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"response_handler_failure_transport_exception","reason":"java.lang.NullPointerException","stack_trace":"ResponseHandlerFailureTransportException[java.lang.NullPointerException]; nested: NullPointerException;\nCaused by: java.lang.NullPointerException
at org.opensearch.action.search.QueryPhaseResultConsumer$PendingMerges.ramBytesUsedQueryResult(QueryPhaseResultConsumer.java:319)
at org.opensearch.action.search.QueryPhaseResultConsumer$PendingMerges.consume(QueryPhaseResultConsumer.java:358)
at …
```

Fix search.aggregation/60_empty.yml test case (fails on BWC runs)

---

test/fixtures/hdfs-fixture/build.gradle

Backport #8359 for f2fbd17457170d1c734c97afa82445acf06cc6cf

[Backport] [2.x] Fix HDFS fixture by excluding BouncyCastle (#8359) 

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java

- Follow up on #8366 and #8370 
- Adds lower and upper bound support for appropriate variance thresholds
Tested with the new seed on #8370 (45A0A15704FDEF1F) and additional 500 runs
Resolves #7751

Add lower and upper bound support for appropriate variance thresholds

---

.github/workflows/version.yml

- As noticed in https://github.com/opensearch-project/OpenSearch/pull/8368 and https://github.com/opensearch-project/OpenSearch/pull/8369, the version ID has unnecessary 0 post the minor version
- This change fixes the version mismatch
- N/A

Fix version script for higher patch numbers

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
server/src/main/java/org/opensearch/search/SearchService.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java

Fix for #8212.
If `missing` is specified in `sort` queries like below, it should result documents with null values as well in last. With #7453 optimizations of min/max values short cutting, this is breaking beucase if shard/segment has its min/max values out of search_after range but can still have missing values those are qualified for the output result.
```
{
"size": 5,
"sort": [{
"amount_cents": {
"order": "desc",
"missing": "_last"
}
}, {
"id": {
"order": "desc",
"missing": "_last"
}
}],
"search_after": [150, "2"],
"track_total_hits": false,
"_source": false
}
```
Resolves #8212  …

Avoid search_after short cutting in case of missing is specified

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/index/IndexModuleTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Changes to move the stale commit deletion logic to async flow.
Resolves #4315

[Remote Store] Moving stale commit deletion to async flow

---

server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java

- In order to efficiently search latest metadata files, metadata files in remote store would be named with following format:
```
metadata_<Inverted Primary Term>_<Inverted Commit Generation>_<Inverted Translog Generation>_<Timestamp>
```
- Here, each inverted number is represented as Long.MAX_VALUE - original number padded with 0s at the front to make the length consistent with that of Long.MAX_VALUE.
- The reason behind using inverted values is to make use of Lexicographic sort order that is supported in majority of the blob stores that remote store feature supports.
- In this PR, we introduce utility methods to convert a given number into inverted format and vice versa.
For …

[Remote Store] Add remote store utils useful to name metadata files

---

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java

Backports #7905 to 2.x branch.
Resolves #7443

[Backport 2.x] [Remote Store] Optimize segments metadata upload (#7905)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java
server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
server/src/test/java/org/opensearch/index/IndexServiceTests.java
server/src/test/java/org/opensearch/index/IndexSettingsTests.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java

Backports #8175 to 2.x branch.
Resolves #8172

[Backport 2.x] Make remote translog upload buffer interval setting dynamic (#8175)

---

server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java

- Integ tests in `RestoreSnapshotIT` that used remote store integration were flaky due to client used from the stopped node.
- In this fix, we are re-initializing the client after stopping the node.
- https://github.com/opensearch-project/OpenSearch/issues/8352
- 

Fix flaky tests in restore flow using snapshot interop

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
server/src/main/java/org/opensearch/search/SearchService.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/240193a8b129aaffffb39a57403264b8c4893efb from https://github.com/opensearch-project/OpenSearch/pull/8391.

[Backport 2.] Avoid search_after short cutting in case of missing is specified (#8391)

---

CHANGELOG.md
plugins/telemetry-otel/build.gradle
plugins/telemetry-otel/config/telemetry-otel/log4j2.properties
plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelResourceProvider.java

Adds log4j configuration for telemetry-otel  LoggingSpanExporter. We will create our on log4j programatic appender later on to avoid the log file generation on case of LoggingSpanExporter is not configured.

Adds log4j configuration for telemetry-otel plugin

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/ExtensionDependency.java
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/main/java/org/opensearch/extensions/rest/RestInitializeExtensionAction.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
server/src/test/java/org/opensearch/extensions/rest/RestInitializeExtensionActionTests.java

This PR modifies the `RestInitializeExtensionAction` to extract any additional settings supplied from ExtensionAwarePlugin.getExtensionSettings <- utilized by the security plugin to define security settings for extensions.
I tested this change by running an extension locally and defining settings from the Security plugin and calling on the API to initialize an extension. I plan to test different types of settings, booleans, strings, arrays, etc to verify this works with different types of settings. ~~I was not able to modify the test to show this working from a test case, but plan to add an automated test ASAP.~~ This PR uses Mockito to partially mock ExtensionsManager to show how additional settings work with the REST endpoint for extension initialization.
Resolves …

Support extension additional settings with extension REST initialization

---

server/src/internalClusterTest/java/org/opensearch/remotestore/PrimaryTermValidationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java

Add integration test for primary term validation for remote translog enabled indexes. 
Resolves #5636

[Remote translog] Add integration tests for primary term validation

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java

Backporting https://github.com/opensearch-project/OpenSearch/pull/8135 to 2.x
Adds integ tests for Remote Store Stats API
NA

[Backport 2.x][Remote Store]Add integ tests for remote store stats api

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

This PR fixes flaky test org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testNodeDropWithOngoingReplication by adding ensureYellow() check after stopping node.
Resolves #8439 

[Remote Store + Segment Replication] Fix flaky test org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testNodeDropWithOngoingReplication

---

server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java

Changing version check to 2.9.
Related backport PR - https://github.com/opensearch-project/OpenSearch/pull/8376
Resolves https://github.com/opensearch-project/OpenSearch/issues/6723

[Search Pipelines] Changing Version Check to 2.9

---

CHANGELOG.md
libs/core/src/main/java/org/opensearch/core/common/io/stream/BaseStreamInput.java
libs/core/src/main/java/org/opensearch/core/common/io/stream/BaseStreamOutput.java
libs/core/src/main/java/org/opensearch/core/common/io/stream/BaseWriteable.java
libs/core/src/main/java/org/opensearch/core/common/io/stream/package-info.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoGrid.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoHashGrid.java
modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoTileGrid.java
server/src/main/java/org/opensearch/common/geo/GeoBoundingBox.java
server/src/main/java/org/opensearch/common/geo/GeoPoint.java
server/src/main/java/org/opensearch/common/io/stream/StreamInput.java
server/src/main/java/org/opensearch/common/io/stream/StreamOutput.java
server/src/main/java/org/opensearch/common/io/stream/Writeable.java
server/src/main/java/org/opensearch/index/query/GeoDistanceQueryBuilder.java
server/src/main/java/org/opensearch/index/query/GeoPolygonQueryBuilder.java
server/src/main/java/org/opensearch/script/JodaCompatibleZonedDateTime.java
server/src/main/java/org/opensearch/transport/TransportService.java
server/src/test/java/org/opensearch/common/io/stream/BaseStreamTests.java
server/src/test/java/org/opensearch/common/io/stream/BytesStreamsTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java

Backport https://github.com/opensearch-project/OpenSearch/commit/392325705eca9afe54d3ed38063b1ee7e0263fa2 from #7465.

[Backport 2.x] [Refactor] Stream Reader and Write Generics (#7465)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java

- Unmutes `SegmentReplicationUsingRemoteStoreIT.testPressureServiceStats()` as it does not fail with the linked seeds
- Tested with the following seeds: 
```
- 6FBC0417BD6F56E8 (https://build.ci.opensearch.org/job/gradle-check/15525)
- 9E739B916891FC83 (https://build.ci.opensearch.org/job/gradle-check/18400/) 
- 6D4AC220FB10A7F1 (https://build.ci.opensearch.org/job/gradle-check/15780/)
- 7F31E8DDB5E9A165 (https://build.ci.opensearch.org/job/gradle-check/15533)
- 8D757DA0D0D145D2 (https://build.ci.opensearch.org/job/gradle-check/17783/)
- 73A2F9AEDE71F705 (https://build.ci.opensearch.org/job/gradle-check/17803)
- 7C703462CB16D721 (https://build.ci.opensearch.org/job/gradle-check/17824)
- 1392808F9FD4A3EF (https://build.ci.opensearch.org/job/gradle-check/17927/)
- F32B62765BE17A94 …
```

Unmute remote store test testPressureServiceStats

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java

This PR is to update the default ZStandard compression level to 3 based on the performance gains we are observing over [here](https://github.com/opensearch-project/OpenSearch/issues/7555#issuecomment-1620301595) at #7555
Resolves:
Optimization mentioned at #7555

Updating default compression level for ZStandard Codecs

---

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java

This add logs to help debug the issue of NoSuchFileException being thrown when trying to read `SegmentInfos.readCommit(storeDirectory, latestSegmentInfos.get())`. More details present in #7815.
Resolves #7815 

Add logs to debug NoSuchFileException during segments upload

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java

Signed-off-by: Sarthak Aggarwal <sarthagg@amazon.com>
(cherry picked from commit eca5a6cbc4f8454afaebd35e81f4d3c23071d92d)
Backport of #8471 
Resolves:
Optimization for #7555

[Manual Backport 2.x] Updating default compression level for ZStandard Codecs (#8471)

---

CHANGELOG.md
server/src/main/java/org/opensearch/node/Node.java
settings.gradle
test/framework/build.gradle
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetryPlugin.java
test/telemetry/build.gradle
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpan.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingContextPropagator.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/SpanProcessor.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/package-info.java

Backport to 2.x
Main PR - https://github.com/opensearch-project/OpenSearch/pull/8357
Commit -  5fd49d0f3052ccc37553c236e8016ce7a6a344a7

[Backport] [2.x] Adds mock implementation for TelemetryPlugin (#8357)

---

CHANGELOG.md
buildSrc/build.gradle

[Backport 2.x] Bump org.apache.maven:maven-model from 3.9.2 to 3.9.3

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

Add condition to ensure data correctness on primary promotion
https://github.com/opensearch-project/OpenSearch/issues/8059

Flaky test: Add condition to ensure data correctness on primary promotion

---

CHANGELOG.md
libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/7909

Backport #7909: Enable Fast Double Parser in Jackson with system property

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

[Backport 2.x] [Segment Replication] Remove Restriction of strictly using only docrep for system indices and hidden indices

---

CHANGELOG.md
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/ScriptRequestProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessorTests.java
modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessorTests.java
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
server/src/main/java/org/opensearch/search/pipeline/Processor.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

A named search pipeline may be created with a PUT request, while an "anonymous" or "ad hoc" search pipeline can be defined in the search request source. In the latter case, we don't want to create any "resource-heavy" processors, since they're potentially increasing the cost of every search request, whereas named pipeline processors get reused.
This change passes a configuration flag to a processor factory if it's being called as part of an ad hoc pipeline. The factory can use that information to avoid allocating expensive resources (maybe by throwing an exception instead).
Resolves https://github.com/opensearch-project/OpenSearch/issues/8163 …

[Search pipelines] Pass "adhocness" flag to processor factories

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java

[Backport 2.x] Create concept of persistent ThreadContext headers that are unstashable (#8291)

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml
rest-api-spec/src/main/resources/rest-api-spec/test/index/105_partial_flat_object_nested.yml
server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java

Before this PR, flat_object can only be defined at the root field of JSON object in 2.7 and 2.8, because the json object is flatten so it lost the structure of a tree. Now,  this PR enables json object to be partially mapped as flat_object field type while other fields in the JSON can be other field type. 
The main idea is to remember the flat object field name as `mappedFieldTypeName` in the dynamic created field (only in query time and it will vanish after returning result), which helps the logic to identify the starting point of a flat object, to decide if a query contains a dot path after flat object field name. 
In the example given in the issue, 
`issue.label` is defined as a flat_object, so `issue.labels` is the flat object field name, and`issue.label.comment` contains a dot path …

Enable Partial Flat Object

---

CHANGELOG.md
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/main/java/org/opensearch/action/search/ArraySearchPhaseResults.java
server/src/main/java/org/opensearch/action/search/CanMatchPreFilterSearchPhase.java
server/src/main/java/org/opensearch/action/search/DfsQueryPhase.java
server/src/main/java/org/opensearch/action/search/ExpandSearchPhase.java
server/src/main/java/org/opensearch/action/search/FetchSearchPhase.java
server/src/main/java/org/opensearch/action/search/SearchPhase.java
server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
server/src/main/java/org/opensearch/action/search/SearchPhaseName.java
server/src/main/java/org/opensearch/action/search/SearchPhaseResults.java
server/src/main/java/org/opensearch/action/search/SearchScrollAsyncAction.java
server/src/main/java/org/opensearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
server/src/main/java/org/opensearch/search/pipeline/SearchPhaseResultsProcessor.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

Add new search pipeline processor type, SearchPhaseResultsProcessor, that can modify the result of one search phase before starting the next phase.
Along with this, added the code to resolve the Search pipeline once and added new SearchRequest type PipelinedRequest.
Backport of PR: https://github.com/opensearch-project/OpenSearch/pull/7283
RFC: https://github.com/opensearch-project/neural-search/issues/152 …

[Backport 2.x] [Search Pipelines] Adding the SearchPhaseResultsProcessor interface in Search Pipeline

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java

- Mute `RemoteStoreIT.testStaleCommitDeletionWithInvokeFlush` and `RemoteStoreIT.testStaleCommitDeletionWithoutInvokeFlush`
- https://github.com/opensearch-project/OpenSearch/issues/8504

[Remote Segment Store] Mute testStaleCommitDeletion test cases

---

CHANGELOG.md
plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/CorrelationCodecService.java
server/src/internalClusterTest/java/org/opensearch/indices/IndexingMemoryControllerIT.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/codec/CodecService.java
server/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java
server/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormat.java
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCodec.java
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCodec.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
server/src/test/java/org/opensearch/index/codec/CodecTests.java
server/src/test/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormatTests.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

This PR enables the compression level settings for the ```zstd``` and ```zstd_no_dict``` codecs. The prerequisite for this PR is #7908 
Resolves #7555 

Compression Levels Settings for zstd and zstd_no_dict

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

We are changing translog metadata file name to  
<inverted_primary_term>-- <inverted_generation>--<inverted_timestamp>--<version>
This would enable us to use lexicographic sort given by remote stores and find the latest metadata in just one list call, instead of doing pagination .
With this change, we are also deleting the older metadata files with every cleanup operation. 

[Remote Store] Update Translog Metadata file name

---

CHANGELOG.md
distribution/tools/upgrade-cli/build.gradle

Handled https://github.com/opensearch-project/OpenSearch/pull/8402 here by setting transitive dependencies as false.
Bumps [com.google.guava:guava](https://github.com/google/guava) from 32.0.1-jre to 32.1.1-jre.
guava 32.1.1-jre brings up `4.11.0` of mockito-core as a transitive dependency: https://mvnrepository.com/artifact/com.google.guava/guava-parent/32.1.1-jre whereas OpenSearch is having `5.4.0` of [mockito](https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties#L56). 
```
* What went wrong:
Could not determine the dependencies of task ':distribution:tools:plugin-cli:forbiddenApisTest'.
> Could not resolve all task dependencies for configuration ':distribution:tools:plugin-cli:testRuntimeClasspath'.
> Conflict(s) found for the following module(s):
- …
```

Bump com.google.guava:guava from 32.0.1-jre to 32.1.1-jre in /distribution/tools/upgrade-cli

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/ConcurrentSegmentSearchCancellationIT.java
server/src/internalClusterTest/java/org/opensearch/search/ConcurrentSegmentSearchTimeoutIT.java
server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/test/java/org/opensearch/search/SearchCancellationTests.java
server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java

This PR adds support for partial results in the cases of timeouts for concurrent segment search.
"Full" partial results are not supported for early terminations because shard failures are expected in that case and thus the behavior between concurrent and non-concurrent search is already consistent. See #817 for more details.
We achieve this by swallowing the timeout exception in the `ContextIndexSearcher.searchLeaf` method and forces us to finish processing all of the leaves in both the sequential and concurrent cases.
Resolves #2586 …

Add early termination support for concurrent segment search

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/ConcurrentSegmentSearchCancellationIT.java
server/src/internalClusterTest/java/org/opensearch/search/ConcurrentSegmentSearchTimeoutIT.java
server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
server/src/main/java/org/opensearch/search/query/QueryPhase.java
server/src/test/java/org/opensearch/search/SearchCancellationTests.java
server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java

Backports #8306 
Resolves #2586

[Backport 2.X] Add early termination support for concurrent segment search (#8306)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java

Fix flakyness in `RemoteStoreRefreshListernerIT` ->  testRemoteRefreshRetryOnFailure
Resolves #7703

Fix flakyness in RemoteStoreRefreshListenerIT

---

server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

Fix flakyness in `RemoteStoreRefreshListenerTests` -> `testRefreshSuccessOnThirdAttemptAttempt`
Resolves #8549

Fix flakyness in RemoteStoreRefreshListenerTests

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java

- `RemoteStoreIT.testStaleCommitDeletion*` tests validate number of metadata files created as part of number of iterations of data ingestion.
- As part of these tests, index is created. Index creation involves flush which uploads a metadata file. We have an optimization to prevent empty refreshes so based on test parameters it is possible to have metadata files which are same as number of iterations or (number of iterations + 1)
Resolves https://github.com/opensearch-project/OpenSearch/issues/8504
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIB …

[Remote Segment Store] Fix flaky RemoteStoreIT.testStaleCommitDeletion tests

---

server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Add integration tests for recovery flow for remote enabled indexes by extending existing recovery indexing integ tests.
Resolves #8476 and #8485

Extend existing IndexRecoveryIT for remote indexes

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java

This PR fixes methods in InternalEngine to access translog methods via TranslogManager. This PR removes few translogManager.getTranslog() occurrences in `InternalEngine` of 2.x branch. 
All of the occurrences in InternalEngine cannot be removed in this PR as they will cause breaking change in InternalEngine.
Few occurrences like : 
```
-> commitIndexWriter(indexWriter, translogManager.getTranslog())
-> translogManager.getTranslog().currentFileGeneration()
-> translogManager.getTranslog().newSnapshot(localCheckpoint + 1, recoverUpToSeqNo))
```
are left out.
Resolves #8443  …

Fix methods in InternalEngine to access translog methods via TranslogManager

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/IndexingMemoryControllerIT.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/codec/CodecService.java
server/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormat.java
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCodec.java
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCodec.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
server/src/test/java/org/opensearch/index/codec/CodecTests.java
server/src/test/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormatTests.java
server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

Backport #8312 
Resolves #7555 

[Backport] [2.x] Enabling Compression Level Index Settings for ZSTD and ZSTD Codecs 

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/cluster/ClusterInfoServiceIT.java
server/src/main/java/org/opensearch/cluster/ClusterInfo.java
server/src/main/java/org/opensearch/cluster/InternalClusterInfoService.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/test/java/org/opensearch/cluster/ClusterInfoTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardConstraintDeciderOverlapTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderUnitTests.java
test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java

- Related to #7713 
- Adds safeguards to prevent file cache over-subscription during allocation for individual node level decisions. 
- Fetches the filecache stats to get node cache size, calculates the `remote` shard size on nodes and verifies if the shard can be safely allocated to the said node
- `size of shard + sum(remote shards on the node) < 5 * (node cache size)`
- The constant value will be replaced by a setting in a following PR.
Resolves #7033   …

Add safeguard limits for file cache during node level allocation

---

buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java

[Backport 2.x] Change extension integration testing to reflect new initialization sequence (#8145)

---

CHANGELOG.md

Accidentally put the changelog in the 3.0 section instead of the 2.x. This change corrects this. 
#8573

Move changelog entry for #8573

---

CHANGELOG.md
build.gradle
distribution/src/config/jvm.options

Adds support for the incubating jdk vector package (PANAMA) when using jdk 20+ runtime.

add jdk.incubator.vector module support for JDK 20+

---

server/src/test/java/org/opensearch/index/codec/CodecTests.java

Fixes CodecTests for backported PR #8312 
Resolves #7555

Fix CodecTests

---

CHANGELOG.md
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/ScriptRequestProcessor.java
modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessorTests.java
modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessorTests.java
modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
server/src/main/java/org/opensearch/search/pipeline/Processor.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

A named search pipeline may be created with a PUT request, while an "anonymous" or "ad hoc" search pipeline can be defined in the search request source. In the latter case, we don't want to create any "resource-heavy" processors, since they're potentially increasing the cost of every search request, whereas named pipeline processors get reused.
This change passes a configuration flag to a processor factory if it's being called as part of an ad hoc pipeline. The factory can use that information to avoid allocating expensive resources (maybe by throwing an exception instead). …

[Search pipelines] Pass "adhocness" flag to processor factories (#8164)

---

server/src/main/java/org/opensearch/index/translog/Checkpoint.java
server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
server/src/test/java/org/opensearch/index/translog/TranslogHeaderTests.java

Since remote store is ensuring translog durability there is no need to fsync translog/checkpoint data in request path. Disabling fsync adds improvement of 10%-15% throughput. 
https://github.com/opensearch-project/OpenSearch/issues/8058

Disabled translog fsync in remote store path

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/0c7ba945806893ab07c705324de890f21bd623cc from https://github.com/opensearch-project/OpenSearch/pull/8134.

[Backport 2.x] Fix SegmentReplication flaky integ tests

---

server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

This PR mutes flaky RemoteStoreRefreshListenerTests, which is frequently causing recent gradle check failures. More info [here](https://github.com/opensearch-project/OpenSearch/issues/8549#issuecomment-1630939783)
https://github.com/opensearch-project/OpenSearch/issues/8549

[Mute] flaky RemoteStoreRefreshListenerTests

---

server/src/main/java/org/opensearch/common/io/VersionedCodecStreamWrapper.java

Adds logs to understand metadata checksum validation intermittent failures.
Helps with https://github.com/opensearch-project/OpenSearch/issues/8491

Add logs for remote store metadata intermittent read failures

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationSuiteIT.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java

This change updates Segment Replication to ensure all listeners are cleaned up during cancellation.  This happens because of a race condition with beforeIndexShardClosed cancelling with RecoveriesCollection#cancelForShard and the target failing.  CancelForShard immediately removes the target from the collection and then invokes cancel.  When cancel would complete, it relies on another call to fail to remove it from the collection & notify the listeners, but it had already been removed.  This PR fixes this by introducing a new method to RecoveriesCollection to request cancellation only.
This change includes tests using suite scope to catch for any open tasks. This caught other locations where this was possible:
1. On a replica during force sync if the shard was closed while resolving its …

Fix bug where ReplicationListeners would not complete on cancellation.

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/8560 to `2.x`

[Segment Replication] Add logic back to update tracking replication checkpoint on source

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/util/FeatureFlags.java

Flip the feature flag as described in https://github.com/opensearch-project/OpenSearch/pull/8513#issuecomment-1630338966
https://github.com/opensearch-project/OpenSearch/issues/8489

[Search Pipeline] Flip SEARCH_PIPELINE feature flag for Search Pipeline GA

---

server/src/main/java/org/opensearch/action/get/MultiGetShardRequest.java
server/src/main/java/org/opensearch/action/get/MultiGetShardResponse.java
server/src/main/java/org/opensearch/action/search/FetchSearchPhase.java
server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
server/src/main/java/org/opensearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsShardRequest.java
server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsShardResponse.java
server/src/main/java/org/opensearch/common/transport/PortsRange.java
server/src/main/java/org/opensearch/search/fetch/ShardFetchRequest.java
server/src/main/java/org/opensearch/search/fetch/ShardFetchSearchRequest.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java
test/framework/src/main/java/org/opensearch/test/TestCluster.java

Refactors usage of obsolete HPPC IntArrayList and ObjectArrayList to java.util.List.
relates #5910

[Refactor] HPPC IntArrayList and ObjectArrayList to j.u.List

---

server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

Mute RemoteStoreRefreshListenerTests tests causing gradle check failure on 2.x branch
Related Issue: https://github.com/opensearch-project/OpenSearch/issues/8638

Mute RemoteStoreRefreshListenerTests tests causing gradle check failure on 2.x branch

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/util/FeatureFlags.java

(cherry picked from commit 051550112c7ae7ae1e81f9da3eff10c73407cf38)
Signed-off-by: Louis Chu <clingzhi@amazon.com>
Manually backport https://github.com/opensearch-project/OpenSearch/pull/8613 to resolve merge conflict on changelog

[Backport 2.x] [Search Pipeline] Flip SEARCH_PIPELINE feature flag for search pipeline GA (#8613)

---

server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

Fix segments upload retry regression introduced in PR #7119
Resolves #8631

Fix remote segments sync retry regression introduced in PR #7119

---

server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

- Backporting part of #8632 to fix the flaky tests. We can't backport https://github.com/opensearch-project/OpenSearch/pull/8632 completely as it is dependent on another PR.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8638

Make sure IndexOutput of metadata file is always closed

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java

* Cluster State Update Optimization - Optimize Metadata build() to skip redundant computations of indicesLookup as part of ClusterState build
Signed-off-by: Sandesh Kumar <sandeshkr419@gmail.com>
---------
Signed-off-by: Sandesh Kumar <sandeshkr419@gmail.com>
(cherry picked from commit cb0d13b9cab950b39269eb28691e6075cd9cf1aa)
Backporting https://github.com/opensearch-project/OpenSearch/pull/7853 to 2.x branch
Resolves https://github.com/opensearch-project/OpenSearch/issues/7002
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer- …

[Backport-2.x] Cluster State Update Optimization (#7853)

---

server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

Backports https://github.com/opensearch-project/OpenSearch/pull/8653/ to 2.9
Resolves https://github.com/opensearch-project/OpenSearch/issues/8638

Make sure IndexOutput of metadata file is always closed (#8653)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

This reverts commit ef4881f0486a16519e5680624eabc524265e335b.
This reverts PR #8502 in 2.9 branch, as it might impact plugins with system indices

[Segment Replication] [Revert] Remove Restriction of strictly using only docrep for system indices and hidden indices (#8502)

---

plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java

Credits: @vikasvb90 and @itiyamas for the design and core implementations of the feature.

[Remote Store] Integrate S3 async upload with S3BlobContainer

---

qa/mixed-cluster/build.gradle
qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

Manual backport to 2.x for below PRs
1. https://github.com/opensearch-project/OpenSearch/pull/7537 
2. https://github.com/opensearch-project/OpenSearch/pull/7876
3. https://github.com/opensearch-project/OpenSearch/pull/8203
4. https://github.com/opensearch-project/OpenSearch/pull/8267
Resolves https://github.com/opensearch-project/OpenSearch/issues/8202

[Backport] [Segment Replication] Added mixed and rolling upgrade bwc test (#7537)

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java
server/src/main/java/org/opensearch/search/aggregations/ConcurrentAggregationProcessor.java
server/src/main/java/org/opensearch/search/aggregations/DefaultAggregationProcessor.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/test/java/org/opensearch/search/SearchCancellationTests.java
server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

The tests were failing because during the concurrent segment search for each slice the codec producers for the leafs were initialized by the slice thread. Later in reduce phase, the post collection happens over those codec producers on the search thread. With AssertingCodec it verifies that all access is done by the same thread causing the failures. More details are in #8095 
Resolves #8095
- [] New functionality has been documented.
- [] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog)) …

CardinalityIT/NestedIT test failures with concurrent search enabled and AssertingCodec

---

server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java

Removed unused extension directory
Resolves https://github.com/opensearch-project/OpenSearch/issues/8563

[Extensions] Removed unused extension directory

---

CHANGELOG.md

The changes removed here from `[Unreleased 3.0]` have all been backported in previous releases.

Remove CHANGELOG entries that have been backported

---

server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java

This change fixes RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty by properly setting replication type on primary shards.
resolves #8699

Fix RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty.

---

server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java

[Backport 2.x] Fix RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty (#8704)

---

server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/8674

[Backport-2.x] Removed unused extension directory

---

server/src/internalClusterTest/java/org/opensearch/action/search/TransportSearchIT.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This is a re-open of https://github.com/opensearch-project/OpenSearch/pull/7736.
Description
With Segment Replication enabled we generally disable shard idle. This change ensures there are replicas in the index before disabling shard idle with SR.  It will warn if a user attempts to update the search.idle.after interval with replicas configured.
Related Issues
https://github.com/opensearch-project/OpenSearch/issues/7761

Segment Replication - Allow search idle with no replicas

---

server/src/internalClusterTest/java/org/opensearch/cluster/shards/ClusterShardLimitIT.java

Muting ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting
https://github.com/opensearch-project/OpenSearch/issues/6287

Mute ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting

---

server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java

This change fixes flaky test testDropPrimaryDuringReplication.  This test would hit an edge case where after an updateSegments call on NRTReplicationReaderManager the reader is not actually refreshed because of another concurrent refresh call. Fixes by using a blocking refresh during updateSegments to ensure a refresh has happened.  This also removes unnecessary synchronization on the updateSegments method.  This is to avoid a deadlock case where the concurrent refresh picks up the new segments but is unable to acquire the object monitor to refresh internally in ReferenceManager.swapReference.
resolves #8059  …

Fix flaky test testDropPrimaryDuringReplication.

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

- As part of segment download from remote segment store, we fsync each downloaded segment file. 
- `fsync` is not required as the segments are already present in remote store.
- Also, `fsync` will slow down the segment download flow.
- This was introduced in https://github.com/opensearch-project/OpenSearch/pull/6788

[Remote Store] Do not trigger storeDirectory.sync in segment download flow from remote store

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

* Start replication timer before segments upload.
* Addressed comments
---------
This backports https://github.com/opensearch-project/OpenSearch/commit/32e72619251957cc3e045b29d13f4e3c190a5008 from #8221

[Backport 2.x] Start replication checkpointTimers on primary before segments upload to remote store. (#8221)

---

qa/mixed-cluster/build.gradle
rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml

Address ./gradlew ':qa:mixed-cluster:v2.9.0#mixedClusterTest' failure issue, when bwc version is 2.9.0, and flag is true in build.gradle. The node with new code can't find the flag setting from the node with old code. On the other hand, when flag is fully removed or the bwc version is included, the node with old code has the flag default set to false will reject the request sent from node with new code. Related issue: https://github.com/opensearch-project/OpenSearch/issues/8070
https://github.com/opensearch-project/OpenSearch/issues/8070 …

Fix search pipeline bwc test

---

server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/index/shard/CloseableRetryableRefreshListenerTests.java
server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

* Use CloesableRetryableRefreshListener to drain ongoing after refresh tasks on relocation ---------
This backports https://github.com/opensearch-project/OpenSearch/commit/2ba1157947c84418234386ad5671719a99f4b889 from #8683

[Backport 2.x] Use CloseableRetryableRefreshListener to drain ongoing after refresh tasks on relocation (#8683)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SignificantTermsSignificanceScoreIT.java
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
server/src/main/java/org/opensearch/search/aggregations/InternalAggregation.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalSignificantTerms.java
server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/test/java/org/opensearch/test/search/aggregations/bucket/SharedSignificantTermsTestMethods.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

Implements solution 2 from https://github.com/opensearch-project/OpenSearch/issues/8703#issue-1805435821
In short: supersetSize and supersetDf are shard level counts that are gathered via count queries. In concurrent segment search these will still be shard level counts rather than segment slice level counts, so we do not want to sum up these counts across segment slices, only at the coordinator level (across shards)
Resolves #8703

Change InternalSignificantTerms to only sum shard level counts in final reduce

---

server/src/internalClusterTest/java/org/opensearch/remotestore/PrimaryTermValidationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java

---------
Manual backport for #8484 
#8483

Add integration tests for remote store restore flow (#8484)

---

server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java

This PR associates the Lucene major version with each uploaded segment file metadata entry that is maintained in remote store. As part of the Lucene version compatibility check, this major version information stored in the metadata will be used to skip downloading the segment files unnecessarily if they were written by an incompatible Lucene version.
1. For the segment files that house the segment data (`.cfe`, `.cfs`, etc.), we track the Lucene major version as captured in the respective `SegmentInfo` instance.
2. For the `segment_N` files that house the information on segments, we track the Lucene major version used for the commit as captured in the respective `SegmentInfos` instance.
3. For the `_<segmentNumber>_<monotonicallyIncrementingCountOfUpdate>_Lucene<major><minor>_<bugfix>.dvm` …

[Remote Segment Store] Add Lucene major version to UploadedSegmentMetadata

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SignificantTermsSignificanceScoreIT.java
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
server/src/main/java/org/opensearch/search/aggregations/InternalAggregation.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalSignificantTerms.java
server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/test/java/org/opensearch/test/search/aggregations/bucket/SharedSignificantTermsTestMethods.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

Change InternalSignificantTerms to only sum shard level counts in final reduce (#8735)

---

server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java

Manual backport for #8088
Resolves https://github.com/opensearch-project/OpenSearch/issues/7722

[Remote Segment Store] Add Lucene major version to UploadedSegmentMetadata (#8088)

---

test/fixtures/krb5kdc-fixture/Dockerfile

Running composeBuild task for krb5kdc-fixture throws read-only file system error while writing hostname to local hosts file. Since, hostname resolution is already present and pointing to local node, let's remove writing it again from the Dockerfile.
Resolves: #8761

fixtures: fix read-only krb5kdc composeBuild failure

---

CHANGELOG.md
codecov.yml

Updated codecov.yml to exclude the "benchmarks" directory from the code coverage report.

Exclude 'benchmarks' from codecov report

---

server/src/main/java/org/opensearch/index/IndexSettings.java

This property is unused now and can be safely removed.

Remove searchSegmentOrderReversed from IndexSettings

---

.github/CODEOWNERS
MAINTAINERS.md

I have nominated and maintainers have agreed to invite Sorabh Hamirwasia(@sohami) to be a co-maintainer. Sorabh has kindly accepted.
Sorabh has led the design and implementation of multiple features like query cancellation, concurrent segment search for aggregations and snapshot inter-operability w/remote storage in OpenSearch. Some significant issues and PRs authored by Sorabh for this effort are as follows:
Concurrent segment search for aggregations : https://github.com/opensearch-project/OpenSearch/issues/6798
Searchable Remote Index : https://github.com/opensearch-project/OpenSearch/issues/2900
Concurrent segment search for aggregations: https://github.com/opensearch-project/OpenSearch/pull/7514
Lucene changes to leaf slices for concurrent search: …

Adding @sohami to OpenSearch maintainers

---

CHANGELOG.md
build.gradle

Manually bump org.gradle.test-retry from 1.5.3 to 1.5.4 since #8841 failed. 

Manually Bump org.gradle.test-retry from 1.5.3 to 1.5.4

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Manually bump org.apache.zookeeper:zookeeper from 3.8.1 to 3.8.2 since  #8839 failed

Manually bump org.apache.zookeeper:zookeeper from 3.8.1 to 3.8.2

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java

This test was marked as non flaky recently, but I was able to catch it while testing a fix for https://github.com/opensearch-project/OpenSearch/issues/8059. This test occasionally fails on an assertion on segrep stats after a failover event.  The assertion is checking that there are no stats returned right after the event because the new primary has no allocated replicas.  
```
java.lang.AssertionError: expected:<0> but was:<1>
at __randomizedtesting.SeedInfo.seed([6FBC0417BD6F56E8:B70016A383AEB076]:0)
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.opensearch.indices.replication.SegmentReplicationIT.testPressureServiceStats(SegmentReplicati …
```

Fix flaky test SegmentReplicationRemoteStoreIT.testPressureServiceStats

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

OpenJDK Update (July 2023 Patch releases)
Part of https://github.com/opensearch-project/OpenSearch/issues/8867

OpenJDK Update (July 2023 Patch releases)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java

PR contains 2 changes in separate commits:
1. Remove flakey assertion from SearchTimeoutIT.
2. Make SourceLookup thread safe in SignificantTextAggregatorFactory by creating a new SourceLookup for each aggregator.
Resolves #8790
Resolves #8509 

Create separate SourceLookup instance per segment slice in SignificantTextAggregatorFactory

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java

[Backport 2.x] Create separate SourceLookup instance per segment slice in SignificantTextAggregatorFactory

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

Mute `testPitCreatedOnReplica` test causing a higher gradle check failures in recent runs. Based on issue description and linked PRs which failed, it seems it is failing mostly on 2.x branch.
Related #https://github.com/opensearch-project/OpenSearch/issues/8850

Skip testPitCreatedOnReplica IT with remote store

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java

This test is failing in two ways.
First it fails when copying segments from the remote store and there is a cksum mismatch. In this case it is not guaranteed the directory implementation will replace the existing file when copying from the store.  This change ensures the mismatched file is cleaned up but only if the shard is not serving reads.  In that case we fail the shard so it is re-recovered rather than deleting the segment underneath it.
This test also fails with a divide by 0 in RemoteStoreRefreshListener.
Resolves #7643  …

Fix SegmentReplicationUsingRemoteStoreIT.testReplicaHasDiffFilesThanPrimary.

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This change removes RefreshListeners used by IndexShard & InternalEngine to provide waitFor functionality from NRT replicas. These listeners were previously registered onto NRT replicas only to be force released on the next scheduled refresh cycle without actually refreshing the reader.
This change also removes the unnecessary blocking refresh from NRTReaderManager because we no longer have conflicting refresh invocations from scheduledRefresh, resolving the deadlock in #8858.
Added test to ensure refreshListeners are not registered.  This is also covered by existing tests testDropPrimaryDuringReplication and testPrimaryRelocation.
Resolves #8858
related https://github.com/opensearch-project/OpenSearch/pull/8859
By submitting this pull request, I confirm that my contribution is made under …

Remove unnecessary refresh listeners from NRTReplicationReaderManager.

---

.github/workflows/version.yml
CHANGELOG.md

Updating Version.java path in version.yml from server/src/main/java/org/opensearch/Version.java to libs/core/src/main/java/org/opensearch/Version.java

Updated Version.java path from server to libs in version.yml

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/lucene/search/XMoreLikeThis.java
server/src/main/java/org/opensearch/gateway/PersistedClusterStateService.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/LuceneChangesSnapshot.java
server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
server/src/main/java/org/opensearch/index/get/ShardGetService.java
server/src/main/java/org/opensearch/index/shard/ShardSplittingQuery.java
server/src/main/java/org/opensearch/index/termvectors/TermVectorsService.java
server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightUtils.java
server/src/main/java/org/opensearch/search/lookup/LeafFieldsLookup.java
server/src/main/java/org/opensearch/search/lookup/SourceLookup.java
server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
server/src/test/java/org/opensearch/common/lucene/index/FreqTermsEnumTests.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/engine/RecoverySourcePruneMergePolicyTests.java
server/src/test/java/org/opensearch/index/query/MoreLikeThisQueryBuilderTests.java
server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
server/src/test/java/org/opensearch/index/shard/ShardSplittingQueryTests.java
server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
server/src/test/java/org/opensearch/lucene/queries/BlendedTermQueryTests.java
server/src/test/java/org/opensearch/search/lookup/LeafFieldsLookupTests.java
server/src/test/java/org/opensearch/search/slice/DocValuesSliceQueryTests.java
server/src/test/java/org/opensearch/search/slice/TermsSliceQueryTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java

Backport https://github.com/opensearch-project/OpenSearch/commit/4fd6877eef7c9cb0b48268a7505506aeb33278a2 from [7792](https://github.com/opensearch-project/OpenSearch/pull/7792)

[Backport 2.x] Replace the deprecated IndexReader APIs with new storedFields() & termVectors()

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/restore/RestoreRemoteStoreRequest.java
server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRestoreRemoteStoreAction.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/restore/RestoreRemoteStoreRequestTests.java
server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

- Currently, [remote store restore API ](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/remote-store/index/#restoring-from-a-backup)restores all the shards of a given index irrespective of the shard state.
- This approach is not optimized for scenarios where only few of the shards are unassigned. Restore will still download data for all the shards in order to restore them.
- We also need to close the index before calling remote store restore API. This impacts the index availability during the restore.
- Ideally, we should be able to restore only those shards that are unassigned and that too without closing the index.
- In restore API execution, while marking shards to be restored, we filter shards based on existing …

[Remote Store] Add support to restore only unassigned shards of an index

---

server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java

The test configured a [timeout duration of zero][1] for certain tasks and asserted that all tasks were throttled or timed out. This is not a valid assertion because it is possible for a task to complete before the [asynchronous timeout operation runs][2], which means the task would complete successfully. The fix is to adjust the assertion to allow for successful tasks in this case.
[1]: https://github.com/opensearch-project/OpenSearch/blob/60985bc300d9eafd36c1ab25d46235e1c925c565/server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java#L941
[2]: https://github.com/opensearch-project/OpenSearch/blob/9fc3f4096958159ec9b53012fc7ced19fd793e1b/server/src/main/java/org/opensearch/common/util/concurrent/PrioritizedOpenSearchThreadPoolExecutor.java#L266
Resolves #5958
By …

Fix flakiness in MasterServiceTests.testThrottlingForMultipleTaskTypes

---

server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java

This test is now failing for node-node replication and is a bug. On the primary shard the prepareSegmentReplication method should cancel any ongoing replication if it is running and start a new sync.  This is incorrectly using Map.compute which will cancel the existing handler but not replace its entry in the allocationIdToHandlers map. As a result this can leave the copyState map with an entry which holds an index commit while the test is cleaning up.  The copyState is only cleared when a handler is cancelled directly or from a cluster state update.
Resolves https://github.com/opensearch-project/OpenSearch/issues/7643
For more information on following Developer Certificate …

Fix SegmentReplicationIT.testReplicaHasDiffFilesThanPrimary for node-node replication

---

build.gradle

The intent of #8825 was to retry only specified tests. The wrong parameter was configured though: ['filter' should be set][1], not 'classRetry'.
[1]: https://github.com/gradle/test-retry-gradle-plugin/blob/main/README.adoc#filtering

Configure test-retry plugin filter properly

---

client/rest-high-level/src/main/java/org/opensearch/client/indices/CreateIndexRequest.java
client/rest-high-level/src/main/java/org/opensearch/client/indices/PutMappingRequest.java
libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
libs/core/src/main/java/org/opensearch/core/xcontent/MediaType.java
libs/core/src/main/java/org/opensearch/core/xcontent/MediaTypeRegistry.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
libs/x-content/src/test/java/org/opensearch/common/xcontent/MediaTypeParserTests.java
server/src/main/java/org/opensearch/rest/AbstractRestChannel.java
server/src/main/java/org/opensearch/transport/TransportService.java

Coming out of https://github.com/opensearch-project/OpenSearch/pull/8826#discussion_r1273746991, this PR rote refactors `MediaTypeParserRegistry` to `MediaTypeRegistry` to make the class naming align with the intention of the logic. The `MediaTypeRegistry` is a mechanism for downstream extensions to register concrete `MediaTypes` thus having "Parser" in the name is unneeded.
relates #5910
relates #8110

[Refactor] MediaTypeParserRegistry to MediaTypeRegistry

---

server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

Fixes `SegmentReplicationTargetServiceTests.testShardAlreadyReplicating` flaky test by ensuring first round of segment replication is not completed before invoking next round.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8928

[Segment Replication] Use deterministic mechanism to have concurrent invocation of segment replication

---

libs/core/src/main/java/org/opensearch/core/xcontent/MediaTypeRegistry.java
libs/core/src/main/java/org/opensearch/core/xcontent/spi/MediaTypeProvider.java
libs/core/src/main/java/org/opensearch/core/xcontent/spi/package-info.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/spi/XContentProvider.java
libs/x-content/src/main/java/org/opensearch/common/xcontent/spi/package-info.java
libs/x-content/src/main/resources/META-INF/services/org.opensearch.core.xcontent.spi.MediaTypeProvider
server/src/main/java/org/opensearch/transport/TransportService.java

This PR provides a new SPI interface `MediaContentProvider`. Modules, Plugins, Extensions, implement this interface and provide the concrete `MediaType` implementations (and MIME aliases) through `getMediaTypes` and `getAdditionalMediaTypes`, respectively. This enables downstream extensions (e.g., serverless or cloud native implementations) as well as plugins or core modules to register their own custom `MediaType` through the interface. All types are registered through `ServiceLoader.load(MediaTypeProvider.class)` when the classloader loads the `MediaTypeRegistry` instead of having to register the types explicitly in application code. `XContentType` is also cutover to use this SPI interface through the `:libs:opensearch-x-content` library and the manual registration logic in …

Register MediaTypes through SPI

---

server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java

Deleting testUpdateSegmentsWhileRefreshing test as it flaky and not needed anymore. The [original PR](https://github.com/opensearch-project/OpenSearch/pull/8715) where logic to perform blocking refresh on NRTReaderManager was added, got removed in follow up PR https://github.com/opensearch-project/OpenSearch/pull/8859. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/8941

[Segment Replication] Remove testUpdateSegmentsWhileRefreshing flaky test failure

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Adds additional codecs to the tests

Amend tests to include all codecs

---

server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java

Added `metadata` prefix to remote translog metadata files. This serves two purpose 
1. Follow convention used in Remote Segment Store metadata .
2. Ignore the extra files which can generated by different OS. 
https://github.com/opensearch-project/OpenSearch/issues/8834

[Remote Store] Add metadata prefix to Remote Translog Metadata file

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/restore/RestoreRemoteStoreRequest.java
server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRestoreRemoteStoreAction.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/restore/RestoreRemoteStoreRequestTests.java
server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

Backports https://github.com/opensearch-project/OpenSearch/commit/c25c175c94efa4d90a1d98e3c7eac3e4aad6e41f from https://github.com/opensearch-project/OpenSearch/pull/8792

[Remote Store] Add support to restore only unassigned shards of an index (#8792)

---

server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggester.java

CompletionSuggestSearchIT.testSkipDuplicates is Flaky, caused by https://github.com/opensearch-project/OpenSearch/pull/8668
Resolves https://github.com/opensearch-project/OpenSearch/issues/8932

[BUG] CompletionSuggestSearchIT.testSkipDuplicates is flaky

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

This reverts commit c43743dd8ac132314dfe375f712c37a7a0f7d8df.
Revert "amending tests to include all codecs (#8907)", causing random failures for completion suggesters
```
Failed to execute phase [query], all shards failed; shardFailures {[xjSEU8WnRrWqVEA7XUuBEQ][vfvppfjpmz][0]: RemoteTransportException[[node_s1][127.0.0.1:45533][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[lpvzbmxouw is not a SuggestField]; }
at __randomizedtesting.SeedInfo.seed([D6593E046E320B3C:D9803AA8A4A760E9]:0)
at app//org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:677)
at app//org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:373)
at …
```

Revert "amending tests to include all codecs (#8907)"

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/search/SearchBootstrapSettings.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/internal/MaxTargetSliceSupplier.java
server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
server/src/test/java/org/opensearch/search/internal/IndexReaderUtils.java
server/src/test/java/org/opensearch/search/internal/MaxTargetSliceSupplierTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java

Introduces a static setting in 2.x to control slice computation using lucene default or max target slice mechanism for concurrent segment search. This is replacement of PR https://github.com/opensearch-project/OpenSearch/pull/8847
Resolves https://github.com/opensearch-project/OpenSearch/issues/7358

Introduce new setting search.concurrent.max_slice to control the slice computation for concurrent segment search

---

modules/parent-join/src/main/java/org/opensearch/join/query/HasChildQueryBuilder.java
modules/percolator/src/main/java/org/opensearch/percolator/PercolateQuery.java
modules/percolator/src/test/java/org/opensearch/percolator/CandidateQueryTests.java
server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
server/src/main/java/org/opensearch/common/lucene/search/MoreLikeThisQuery.java
server/src/main/java/org/opensearch/common/lucene/search/MultiPhrasePrefixQuery.java
server/src/main/java/org/opensearch/common/lucene/search/function/FunctionScoreQuery.java
server/src/main/java/org/opensearch/common/lucene/search/function/ScriptScoreQuery.java
server/src/main/java/org/opensearch/index/document/SortedUnsignedLongDocValuesRangeQuery.java
server/src/main/java/org/opensearch/index/query/DateRangeIncludingNowQuery.java
server/src/main/java/org/opensearch/index/search/OpenSearchToParentBlockJoinQuery.java
server/src/main/java/org/opensearch/lucene/queries/MinDocQuery.java
server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggester.java
server/src/test/java/org/opensearch/deps/lucene/VectorHighlighterTests.java
server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
server/src/test/java/org/opensearch/index/query/SpanMultiTermQueryBuilderTests.java
server/src/test/java/org/opensearch/index/search/OpenSearchToParentBlockJoinQueryTests.java
server/src/test/java/org/opensearch/lucene/queries/MinDocQueryTests.java
server/src/test/java/org/opensearch/lucene/queries/SpanMatchNoDocsQueryTests.java
server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java

`Query#rewrite(IndexReader reader)` is deprecated in Lucene 9.7 and removed in Lucene 10 in favor of `Query#rewrite(IndexSearcher searcher)`. The latter provides `LeafCollector` hooks to optimize for concurrent queries. This commit cuts over usage of `rewrite(IndexReader)` to `rewrite(IndexSearcher)` for Lucene 10 compatibility and upstream query optimizations.
relates #8932 
relates #8963

Replace deprecated Query#rewrite(IndexReader with rewrite(IndexSearcher

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java
server/src/test/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestTests.java
server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java

- Follow up on #8208 
- Adds changes to prevent oversubscription at the searchable snapshot restore operation, building on top of the allocation level logic
- Makes the value for subscription ratio configurable instead of the fixed value
Resolves #7033
- https://github.com/opensearch-project/OpenSearch/pull/7713#issuecomment-1601824927
- #8208 

Add restore level safeguards to prevent file cache oversubscription

---

CHANGELOG.md
settings.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/8996 to `2.x`

[Backport] [2.x] Bump com.gradle.enterprise from 3.13.3 to 3.14.1 (#8996)

---

build.gradle

After the fix in #8901, I ran the following in a loop all day (about 1400 times) and saw no failures:
```
./gradlew ':server:test' --tests "org.opensearch.cluster.service.MasterServiceTests"
```

Remove MasterServiceTests from retries

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/profile/aggregation/AggregationProfilerIT.java
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/profile/AbstractProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/ProfileResult.java
server/src/main/java/org/opensearch/search/profile/Profilers.java
server/src/main/java/org/opensearch/search/profile/Timer.java
server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfiler.java
server/src/main/java/org/opensearch/search/profile/aggregation/ConcurrentAggregationProfiler.java
server/src/main/java/org/opensearch/search/profile/aggregation/InternalAggregationProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
server/src/test/java/org/opensearch/search/profile/ProfileResultTests.java
server/src/test/java/org/opensearch/search/profile/TimerTests.java
server/src/test/java/org/opensearch/search/profile/aggregation/AggregationProfileShardResultTests.java
server/src/test/java/org/opensearch/search/profile/aggregation/ConcurrentAggregationProfilerTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfileShardResultTests.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

Add support for aggregation profiler with concurrent aggregation.
Resolves #8331

Add support for aggregation profiler with concurrent aggregation

---

CHANGELOG.md
modules/ingest-common/src/test/java/org/opensearch/ingest/common/BytesProcessorTests.java
server/src/main/java/org/opensearch/common/unit/ByteSizeValue.java
server/src/test/java/org/opensearch/common/unit/ByteSizeValueTests.java

This PR removes the deprecation warning for fractional bytes size values and, instead, throws an `OpenSearchParseException` if a user passes in a fraction byte value (e.g., `5.2b`). This leniency was deprecated a long time ago in Legacy 6.2 so the removal should come as no surprise to users.

[Remove] Deprecated Fractional ByteSizeValue support

---

server/src/main/java/org/opensearch/common/settings/Setting.java

This fixes a bug where the `Setting#byteSizeSetting` static method returned fractional byte values when calling `.toString` inside the lambda. The change is to directly return the bytes value as a string instead of using `ByteSizeValue#toString` which tries to be smart and pretty print in a more human-friendly format.
closes #9010 
relates #9005

[Bug] Fix Setting#byteSizeSetting to use whole value string

---

CHANGELOG.md
modules/ingest-common/src/test/java/org/opensearch/ingest/common/BytesProcessorTests.java
server/src/main/java/org/opensearch/common/settings/Setting.java
server/src/main/java/org/opensearch/common/unit/ByteSizeValue.java
server/src/test/java/org/opensearch/common/unit/ByteSizeValueTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/0b1f875d34c7d723afd41396234f8f2003c6be2c from #9005.
Also adds a couple missing items from the changelog.

[Backport 2.x] [Remove] Deprecated Fractional ByteSizeValue support (#9005)

---

CHANGELOG.md
server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java

The `assertMemoryUsageWithinLimits` method checks if the memory usage is within 5% (up to 200 KB) of the expected memory usage. This additional buffer is to account for the class loading overhead when new code is encountered at runtime. Over time, addition of new code paths has resulted in greater overhead. This PR bumps up the 200 KB limit to 500 KB.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8213

Fix flaky ResourceAwareTasksTests.testBasicTaskResourceTracking test

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/profile/aggregation/AggregationProfilerIT.java
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/profile/AbstractProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/ProfileResult.java
server/src/main/java/org/opensearch/search/profile/Profilers.java
server/src/main/java/org/opensearch/search/profile/Timer.java
server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfiler.java
server/src/main/java/org/opensearch/search/profile/aggregation/ConcurrentAggregationProfiler.java
server/src/main/java/org/opensearch/search/profile/aggregation/InternalAggregationProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
server/src/test/java/org/opensearch/search/profile/ProfileResultTests.java
server/src/test/java/org/opensearch/search/profile/TimerTests.java
server/src/test/java/org/opensearch/search/profile/aggregation/AggregationProfileShardResultTests.java
server/src/test/java/org/opensearch/search/profile/aggregation/ConcurrentAggregationProfilerTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfileShardResultTests.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

(cherry picked from commit 35662f06bbef75447ba6204bc6a7e032066509cc)
Backport of #8801 to `2.x` branch. Add support for aggregation profiler with concurrent aggregation.
Resolves #8331 

[Backport] [2.x] [Concurrent Segment Search]: Add support for aggregation profiler with concurrent aggregation (#8801)

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

Backport of https://github.com/opensearch-project/OpenSearch/pull/8872 to `1.3`

[Backport] [1.3] OpenJDK Update (July 2023 Patch releases) (#8872)

---

.github/workflows/check-compatibility.yml
buildSrc/src/main/groovy/org/opensearch/gradle/CheckCompatibilityTask.groovy

**_All the issues linked here confirmed that all plugins have passing `gradle assemble` and `mavenlocal()` as their first repository in build.gradle are closed now: https://github.com/opensearch-project/opensearch-devops/issues/114_**
This change adds a workflow to check the compatibility with all the plugins in opensearch-project. It adds a comment if any component is incompatible. Example: https://github.com/gaiksaya/OpenSearch/pull/7#issuecomment-1623129382
https://github.com/opensearch-project/opensearch-devops/issues/114 …

Add workflow to check compatibility

---

modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java

This changes the version check for `MediaType` in `PercolateQueryBuilder` for BWC.

[BWC] Change BWC version check for MediaType in PercolateQueryBuilder

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/codec/CodecCompressionLevelIT.java
server/src/main/java/org/opensearch/index/codec/CodecService.java
server/src/main/java/org/opensearch/index/codec/CodecSettings.java
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCodec.java
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCodec.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/test/java/org/opensearch/index/codec/CodecTests.java

This PR will disallow the compression level to be set for ```default``` and ```best_compression``` codec. Compression level does not hold any impact on these two codecs
Resolves #8677 

Disallowing compression level for lz4 and best_compression codec

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Adding ZStandard Codecs in existing tests

Readding codecs in the tests

---

server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/8988 to `2.x`

[Backport] [2.x] Added featureflag (#8988)

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

- During deletion of index, shard close is called.
- We have assertion for remote enabled indices in close to ensure engine is InternalEngine. In case of already closed indices the engine would be NoOpEngine, leading the assert to fail in tests.
Unblocks backport PR merge #9025

skip engine instanceOf InternalEngine assertion for closed shards

---

server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexPrimaryRelocationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

1. Added few more tests for failover and relocation for remote store
2. Added Remote Translog UT framework . `SegmentReplicationWithRemoteIndexShardTests` now uses remote translog
3. Avoid indexing already indexed  documents as stale in non primary mode for SegRep based indices . 
4. Added UT for checking no duplicate documents having same sequence number 
Ran `RemoteIndexPrimaryRelocationIT` 10 times on local to ensure it is not flaky . Running it 100 times more 
- [] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog)) …

[Remote Store] Avoid indexing documents as stale in non primary mode 

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java

This fixes the flaky test for different type of failures mentioned in the issue #9036.
- Assertion count for successful shards
- Due to node being stopped and failover not completing, during the teardown there were assertion failures on primaryMode. 
Resolves #9036

Fix flaky test testStatsOnShardUnassigned in RemoteStoreStatsIT

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponse.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureService.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/DirectoryFileTransferTracker.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponseTests.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

Backport https://github.com/opensearch-project/OpenSearch/pull/8718 to 2.x branch

[Backport-2.x] Add Segment download stats to remotestore stats API

---

server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java

* DefaultSearchContext should evaluate if the concurrent search is enabled for a request during the construction of this object and then cache that value for all other invocations. Currently the way it is implemented it can happen that between invocations the cluster setting can change resulting in inconsistent value during the request flow.
* DefaultSearchContext should also not provide executor to the IndexSearcher if concurrent search segment is disabled for the request.
Resolves #9058 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md …

Change to determine if concurrent segment search should be used by the request during SearchContext creation

---

server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

Fixes unit test `testUploadMetadataMissingSegment` by fetching primary term from ReplicationCheckpoint vs using hard-coded value. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/9096
Ran this test 1k times successfully without failure

Fix testUploadMetadataMissingSegment unit test on 2.x

---

server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

Forward port unit test `testUploadMetadataMissingSegment` added in https://github.com/opensearch-project/OpenSearch/pull/8653
Resolves None

[Remote Store] Add missing unit test in main

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/SegmentReplicationCheckpointPublisher.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/8889

[Backport 2.x] Fix test testDropPrimaryDuringReplication and clean up ReplicationCheckpoint validation

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/aggregations/MultiBucketConsumerService.java
server/src/test/java/org/opensearch/search/aggregations/MultiBucketConsumerTests.java

callCount variable needs to be made thread safe as there is a periodic check on the CircuitBreaker in the MultiConsumerService that checks if the CB has tripped. With Concurrent Search, for each shard, there are multiple slices running on different threads and having one instance of MultiBucketConsumer. Multiple threads within the same instance of MultiBucketConsumer will try to access the callCount variable, and as of current logic that checks for CB trip after every 1024 calls to the accept function, there is possibility that if the callCount is not made thread safe, the CB trip check might never happen.
Initializing callCount as a LongAdder variable making it thread safe and also having an additional volatile` variable that tries to trip the CB for the other threads in case for one of …

Make MultiBucketConsumerService thread safe to use across slices during search

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/aggregations/MultiBucketConsumerService.java
server/src/test/java/org/opensearch/search/aggregations/MultiBucketConsumerTests.java

Backporting https://github.com/opensearch-project/OpenSearch/pull/9047

Make MultiBucketConsumerService thread safe to use across slices during search (#9047)

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/ClusterModule.java
server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
server/src/main/java/org/opensearch/cluster/routing/ShardMovementStrategy.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeVersionAllocationDecider.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java
server/src/test/java/org/opensearch/cluster/routing/ShardMovementStrategyTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java

When some node or set of nodes is excluded, the shards are moved away in random order. When segment replication is enabled for a cluster, we might end up in a mixed version state where replicas will be on lower version and unable to read segments sent from higher version primaries and fail.
To avoid this, we could prioritize replica shard movement to avoid entering this situation.
Adding a new setting called shard movement strategy - `SHARD_MOVEMENT_STRATEGY_SETTING` - that will allow us to specify in which order we want to move our shards: `NO_PREFERENCE` (default), `PRIMARY_FIRST` or `REPLICA_FIRST`. 
The `PRIMARY_FIRST` option will perform the same behavior as the previous setting `SHARD_MOVE_PRIMARY_FIRST_SETTING` which will be now deprecated in favor of the shard movement strategy …

[Segment Replication] Prioritize replica shard movement during shard relocation

---

server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java

Mutes flaky test ReplicaToPrimaryPromotionIT.testFailoverWhileIndexing that has failed 3 times in the past 24 hours. 
First recorded here: https://github.com/opensearch-project/OpenSearch/issues/9092 
Issue: https://github.com/opensearch-project/OpenSearch/issues/9130 
Related to: https://github.com/opensearch-project/OpenSearch/issues/9130 

Mute flaky test ReplicaToPrimaryPromotionIT.testFailoverWhileIndexing

---

server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
server/src/test/java/org/opensearch/index/shard/CloseableRetryableRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
test/framework/src/main/java/org/opensearch/test/RemoteStoreTestUtils.java

Today, if a refresh occurs for an IndexShard, the afterRefresh method of `ReferenceManager.RefreshListener` (Lucene class) objects are invoked. RemoteStoreRefreshListener, currently, has the responsibility of updating the segment tracker with the upto date information of segment files which are part of the most recent refresh. It also has the responsibility of uploading the segments to the remote store after each refresh and then updating the segment tracker with the relevant information about the upload. This information is exposed via remote store stats api and is also used for rejection incoming write requests when there is a lag between the local store and the remote store (remote segment backpressure). While updating the tracker with local state happens at the beginning of the …

Fix local segments stats update in RemoteStoreRefreshListener

---

libs/core/src/main/java/org/opensearch/core/common/util/CollectionUtils.java

Maven snapshot publication started failing after: https://github.com/opensearch-project/OpenSearch/pull/9120
The error stemmed from a compilation warning:
> /home/runner/work/OpenSearch/OpenSearch/libs/core/src/main/java/org/opensearch/core/common/util/CollectionUtils.java:143: warning: [unchecked] unchecked generic array creation for varargs parameter of type Iterator<? extends Object>[]
return () -> Iterators.concat(map.keySet().iterator(), map.values().iterator());
^
error: warnings found and -Werror specified
See: https://github.com/opensearch-project/OpenSearch/actions/runs/5767554873/job/15637408847 …

Fix compilation warning in CollectionUtils affecting maven snapshot publication

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/ClusterModule.java
server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
server/src/main/java/org/opensearch/cluster/routing/ShardMovementStrategy.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/NodeVersionAllocationDecider.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java
server/src/test/java/org/opensearch/cluster/routing/ShardMovementStrategyTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java

…relocation (#8875)
* add shard movement strategy setting
* add tests
* add changelog
* Add NodeVersionAllocationDecider check
* refactoring
* add annotation + refactor
---------
(cherry picked from commit c6e4bcd097969f00956c0f4c152540cb610e4f93)
Manual backport of #8875 to 2.x  …

[Backport 2.x] Prioritize replica shard movement during shard 

---

.github/workflows/precommit.yml
buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java

Add Gradle's 'assemble' check to catch the distribution generation issues
Related to https://github.com/opensearch-project/OpenSearch/issues/8903

Add Gradle's 'assemble' check to catch the distribution generation issues

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
server/src/main/java/org/opensearch/search/internal/MaxTargetSliceSupplier.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
server/src/test/java/org/opensearch/search/internal/IndexReaderUtils.java
server/src/test/java/org/opensearch/search/internal/MaxTargetSliceSupplierTests.java
server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

This is a follow-up to https://github.com/opensearch-project/OpenSearch/issues/7358 to make the setting `search.concurrent.max_slice` dynamic in main (with lucene 9.8 version).  This PR will not be backported to 2.x unless lucene 9.8 is released and available in 2.x branch. Until then we will use the static setting mechanism for 2.x branch supported by previous PR.
https://github.com/opensearch-project/OpenSearch/issues/8870

Update search.concurrent.max_slice setting to dynamic cluster setting for main with lucene-9.8

---

server/src/main/java/org/opensearch/search/SearchBootstrapSettings.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java

Changing the name of the setting to add `_count` suffix
Follow-Up of https://github.com/opensearch-project/OpenSearch/pull/9107
- [] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

Update the max_slice setting name to max_slice_count

---

CHANGELOG.md
modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java
server/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecMergeIT.java
server/src/main/java/org/opensearch/index/codec/CodecService.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/test/java/org/opensearch/index/codec/CodecTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

The users will be able to set the codecs in the index settings using their algorithm names. This will help the user get visibility on the algorithm being used in the background for compression 
Resolves #8695

Referencing default and best compressions codecs as their algo name

---

MAINTAINERS.md

This PR reinstates Rabi Panda, and Abbas Hussain as maintainers of the opensearch repository after inadvertant removal in https://github.com/opensearch-project/OpenSearch/commit/0f651b8664ea80c993e93d47170b33fcef0d8d73 and  https://github.com/opensearch-project/OpenSearch/commit/62157b93d297f30a922c462a74310c7578ee4537, respectively. The [removing maintainers](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#moving-on) process specifies maintainers are removed as follows: 
```
Existing maintainers can choose to leave the project at any time, with or without reason, by making a pull request to move themselves to the "Emeritus" section of MAINTAINERS.md, and asking an [members of the admin team](https://github.com/opensearch-project/.github/blob/main/ADMINS.md) to …
```

Reinstate maintainers from emeritus to active

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/9148 to `2.x`

[Backport] [2.x] Bump org.apache.maven:maven-model from 3.9.3 to 3.9.4 in /buildSrc (#9148)

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

This PR is to discuss the optimisation changes for listener based get_snapshot calls handled through async based model.
This is a backport commit of the PR: https://github.com/opensearch-project/OpenSearch/pull/8377
Resolves #1788 

Backport/backport 8377 to 2.x

---

CHANGELOG.md
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanContext.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/runnable/TraceableRunnable.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/runnable/package-info.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/TraceableRunnableTests.java
server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
server/src/test/java/org/opensearch/telemetry/tracing/WrappedTracerTests.java

2.x backport of PR - https://github.com/opensearch-project/OpenSearch/pull/8831.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8428

[Backport] [2.x] Adds support for tracing runnable scenarios

---

client/rest/src/test/java/org/opensearch/client/RestClientSingleHostIntegTests.java

The issue was caused by race between aborting the HTTP request and completing the resulting future. Added `Phaser` to predictably control the cancellation race.
Resolves https://github.com/opensearch-project/OpenSearch/issues/9034

[BUG] org.opensearch.client.RestClientSingleHostIntegTests.testRequestResetAndAbort is flaky

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java

Fixes two flaky tests : 
1.  testStaleCommitDeletion - There was an extra refresh/no op refresh , which can decrease/increase the metadata file count. Disabled implicit refresh and factored in no op refreshes as well
2. testFailoverWhileIndexing : There can be an `Updated` response as well on new docs creation . Factored in same .
Use of bulk indexing API to make Remote ITs faster as well . 
Resolves https://github.com/opensearch-project/OpenSearch/issues/8658
Resolves https://github.com/opensearch-project/OpenSearch/issues/9130 …

[Remote Store] Fix couple of Remote Store flaky test and use bulk api for ingestion

---

.github/dependabot.yml

Shamelessly copying @peternied work on `security` plugin (https://github.com/opensearch-project/security/pull/3133)
N/A

Automatically update GitHub Actions dependencies with dependabot

---

server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This test is specific to remote store and should not be run for node-node replication.
NA

Fix flaky test SegmentReplicationIndexShardTests.testPrimaryRestart

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Force upgrades the following transitive dependencies to hadoop-minicluster which have CVEs logged against them:
* `org.xerial.snappy:snappy-java`
* `com.squareup.okio:okio`
Removes transitive dependency on `com.cedarsoftware:json-io` as all versions are vulnerable and removal does not impact our use-case.
These DO NOT impact end users of OpenSearch as these are purely integration test dependencies.

Force upgrade the vulnerable dependencies of hadoop-minicluster

---

server/src/main/java/org/opensearch/action/admin/cluster/remotestore/restore/TransportRestoreRemoteStoreAction.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java

- Currently remote store backed index restore logic resides in RestoreService along with snapshot restore logic.
- We introduce a new RemoteStoreRestoreService which will host the logic for remote store restore.
- RestoreService will keep on existing and will only contain logic around snapshot restore.
NA

[Remote Store][Refactor] Introduce RemoteStoreRestoreService to handle restore from remote store

---

CHANGELOG.md
modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java
server/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecMergeIT.java
server/src/main/java/org/opensearch/index/codec/CodecService.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/test/java/org/opensearch/index/codec/CodecTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Signed-off-by: Sarthak Aggarwal <sarthagg@amazon.com>
(cherry picked from commit 3713bcb1ab69d18cc990cd36f91f5b5261b71132)
Backporting #9123 to 2.x
Resolves https://github.com/opensearch-project/OpenSearch/issues/8695

[Backport] [2.x] Referencing default and best compressions codecs as their algo name (#9123)

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

This PR fixes SegmentReplicationIT.testDeleteOperations which can occasionally fail when no docs are indexed.  Fixed by ensuring at least one doc is indexed and flagged for deletion.  Also reduced the doc count potentially indexed to speed up the test.
N/A

Fix flaky test SegmentReplicationIT.testDeleteOperations.

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

1. Unmutes `testIndexingWithSegRep` as https://github.com/opensearch-project/OpenSearch/pull/8560 (pre-requisite for segment replication bwc test) is merged to main and backported to 2.x. 
2. Fixes flakyness by first asserting row count from _cat/segments API response to enable retry without which test fails with `IndexOutOfBoundsException` as mentioned [here](https://github.com/opensearch-project/OpenSearch/issues/7679#issuecomment-1663232969). [Edit]: Needed to remove rows with `0` doc count before adding assertion of number of rows to be multiple of shard copies. 
Resolves: #7679 
Ran test in a loop for ~~500~~ 100 iterations without failure on main ~~and 2.x~~
`main`
```
for in in {1..100}; do ./gradlew ':qa:rolling-upgrade:v2.10.0#upgradedClusterTest' --tests …
```

[Segment Replication] Unmute testIndexingWithSegRep rolling upgrade test

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/9079 to 2.x

[Backport to 2.x] [Segment Replication] Unmute testIndexingWithSegRep rolling upgrade test

---

server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalTerms.java

After #8860, the shard_size parameters are not applied until the shard level reduce. This means that no bucket candidates will be eliminated until the reduce phase, which also means there should be no doc_count_error at the slice level reduce. This change fixes that and the test failures in #9209
Resolves #9209

docCountError must be 0 for shard level reduce

---

server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
server/src/test/java/org/opensearch/index/shard/CloseableRetryableRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
test/framework/src/main/java/org/opensearch/test/RemoteStoreTestUtils.java

Backport https://github.com/opensearch-project/OpenSearch/commit/2416d4574f251180447bd7c9602a3981b329d010 from https://github.com/opensearch-project/OpenSearch/pull/8758.

[Backport 2.x] Fix local segments stats update in RemoteStoreRefreshListener (#8758)

---

CHANGELOG.md
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingTelemetry.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/attributes/Attributes.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/attributes/package-info.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/runnable/TraceableRunnable.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/TraceableRunnableTests.java
plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelAttributesConverter.java
plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingTelemetry.java
plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelAttributesConverterTests.java
plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelTracingTelemetryTests.java
server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
server/src/test/java/org/opensearch/telemetry/tracing/WrappedTracerTests.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpan.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingContextPropagator.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java

Backport PR for #9199 
Resolves https://github.com/opensearch-project/OpenSearch/issues/9197

[Backport] [2.x] Adds attributes to startSpan 

---

libs/common/src/main/java/org/opensearch/common/annotation/DeprecatedApi.java
libs/common/src/main/java/org/opensearch/common/annotation/ExperimentalApi.java
libs/common/src/main/java/org/opensearch/common/annotation/InternalApi.java
libs/common/src/main/java/org/opensearch/common/annotation/PublicApi.java

Post merge enhancements as per https://github.com/opensearch-project/OpenSearch/pull/9223#issuecomment-1677572747

[BWC and API enforcement] Extend the element types the initial set of  annotations could be applied to

---

CHANGELOG.md
DEVELOPER_GUIDE.md
libs/common/src/main/java/org/opensearch/common/annotation/DeprecatedApi.java
libs/common/src/main/java/org/opensearch/common/annotation/ExperimentalApi.java
libs/common/src/main/java/org/opensearch/common/annotation/InternalApi.java
libs/common/src/main/java/org/opensearch/common/annotation/PublicApi.java
libs/common/src/main/java/org/opensearch/common/annotation/package-info.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/9223 to `2.x`

[Backport] [2.x] [BWC and API enforcement] Define the initial set of annotations, their meaning and relations between them (#9223)

---

server/src/test/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandTests.java

The `RemoveCorruptedShardDataCommandTests` tests for appropriate exceptions on corrupted translogs.  In the rare edge case where the corruption occurs in the header where the UUID tracks the engine, the expected `TranslogCorruptedException` is caught and rethrown as an `EngineCreationFailureException` rather than the `TranslogException` expected by the test.
This change relaxes the test to allow either wrapped exception while testing the same cause.
Fixes #6179 
Command reproducing this failure at linked issue; this test passes after this fix. …

Fix flaky testCorruptedTranslog test

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java

Change noisy logs on SegRep and remote store paths to trace level
Resolves https://github.com/opensearch-project/OpenSearch/issues/8452

Change noisy logs on SegRep and remote store paths to trace level

---

qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

Mute `testIndexingWithSegRep` test after it is still found to be flaky post [last fix](https://github.com/opensearch-project/OpenSearch/issues/9079). The test today fails because replica shard is remains lagging primary shard on `checkpoints_behind` metric which is verified [here](https://github.com/opensearch-project/OpenSearch/blob/8e57a660d20b257d30d05288432733595713d464/qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java#L159). This assertion is important to ensure replica eventually catches up with primary but it is found replica is still not able to catch up with primary after 1 minute of wait.
Related #7679  …

[Segment Replication] Mute flaky testIndexingWithSegRep test

---

buildSrc/build.gradle

Enforces up-to-date Guava in buildSrc.
Guava is a transitive dependency of spotless via google-java-format, the version that was being pulled in has CVE-2023-2976. While this would not affect end users it causes excess alerts.

Enforce up-to-date Guava in buildSrc

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java

This fails frequently. Muting for now until it is fixed to unblock unrelated PRs.
Related to (but does not fix) #9326

Mute RemoteRestoreSnapshotIT.testRestoreInSameRemoteStoreEnabledIndex

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

Mute remote store + segRep flaky tests that frequently block checks.
These tests have opened bugs against them and are not on our retry list.  To prevent blocking checks this mutes them.
N/A

Mute remote store + segRep flaky tests that frequently block checks.

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.9.0.md

Most of the issues here are from entries going into the `3.0` section on main but end up backported to `2.x`. There were also a few ordering issues and one issue where a change was included in the 2.9 release notes but was not actually backported until after the 2.9 release.

Fix changelog divergence on main

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java

Currently OpenSearch code contains an explicit list of file extensions which load using mmap from hybridfs. Other file extensions default to nio. This PR flips the logic to keep a list of nio file extensions while all others default to mmap. This will prevent any future regressions in case Lucene adds new segment file type that should be using mmap.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8297

Default to mmapfs within hybridfs

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java
server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java

CircuitBreaker tests are breaking because of the difference in the Exceptions being thrown at the shard failure. The exceptions can be found below:
Shard failure exception with Concurrent Search
```
shard[[wkVu-9P-R1ylmYdjXkGw4w][cb-test][6]], reason [RemoteTransportException[[node_t0][127.0.0.1:62392][indices:data/read/search[phase/query/id]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: CircuitBreakingException[[fielddata] Data too large, data for [test] would be [1689/1.6kb], which is larger than the limit of [100/100b]]; ], cause [CircuitBreakingException[[fielddata] Data too large, data for [test] would be [1689/1.6kb], which is larger than the limit of [100/100b]]
at org.opensearch.common.breaker.ChildMemoryCircuitBreaker.circuitBreak(Ch …
```

Rethrow OpenSearch exception in concurrent search

---

server/src/main/java/org/opensearch/index/engine/SegmentsStats.java

Changing node stats based remotestore stats metric version filter to 2.10 to retain compatibility. 
***This change should be merged after backport PR https://github.com/opensearch-project/OpenSearch/pull/9301 is merged to the `2.x` branch***
N/A

[Remote Store] Changing remotestore based NodesStats metrics version to 2.10

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteSegmentStatsFromNodesStatsIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
server/src/main/java/org/opensearch/index/remote/RemoteStorePressureSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/DirectoryFileTransferTracker.java
server/src/main/java/org/opensearch/indices/IndicesModule.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Backport https://github.com/opensearch-project/OpenSearch/pull/9253 to 2.x
#8311

[Remote Store] Rename RemoteRefreshSegmentPressureSettings and RemoteRefreshSegmentPressureService

---

.github/workflows/changelog_verifier.yml
.github/workflows/check-compatibility.yml
.github/workflows/gradle-check.yml
.github/workflows/lucene-snapshots.yml
.github/workflows/precommit.yml
.github/workflows/publish-maven-snapshots.yml
.github/workflows/version.yml
.github/workflows/wrapper.yml

Backport 0d5dbde4d34462e0ee5178363bbd0037cb47dd28 from #9284.

[Backport 2.x] Restrict GitHub Actions to run only on OpenSearch repo (#9284)

---

server/src/main/java/org/opensearch/index/engine/InternalEngine.java

We saw an assertion failure [here](https://github.com/opensearch-project/OpenSearch/blob/c1505f1cfed580ef43df3ceb3fe1c660b4bc5178/server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java#L6644) where `currentOngoingRefreshCheckpoint` was `-1` and  `lastRefreshedCheckpoint` was `0`. This was not reproducible after 50K test iterations. 
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=649, name=Thread-197, state=RUNNABLE, group=TGRP-InternalEngineTests]
at __randomizedtesting.SeedInfo.seed([B448FCE4648CA4EB:7A3CB282E14976E1]:0)
Caused by: java.lang.AssertionError: 
Expected: a value equal to or greater than <0L>
but: <-1L> was less than <0L>
at __randomizedtesting.SeedInfo.seed([B448FCE4648CA4EB]:0)
at …
```

Fix flaky test InternalEngineTests.testLastRefreshCheckpoint

---

server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

Fix flaky test NRTReplicationEngineTests.testPreserveLatestCommit.
This test occasionally failed when the primary's engine performed a flush and merge behind the scenes.  The test would assert against a specific refCount on committed files with a value of 2 - one for being part of the replica's latest commit and one for being active on the reader.  With the unexpected merge, the files will not be part of the latest infos on the reader but still be part of the replica's latest commit point, leaving the files referenced once.  I've changed this to instead assert referenced vs unreferenced instead of the specific refCount so that the test can handle the random merges.  Further cleaned this up so assertions include a refCount check and to validate the files exist in the directory.
I've run …

Fix flaky test NRTReplicationEngineTests.testPreserveLatestCommit

---

client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexTemplatesResponseTests.java
test/framework/src/main/java/org/opensearch/index/RandomCreateIndexGenerator.java

Although rare, [if you throw random alpha strings together often enough](https://en.wikipedia.org/wiki/Infinite_monkey_theorem), you'll get a collision.
Fixes #6739

Fix flaky test by preventing duplicate keys in random mapping fields

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java

While executing some test runs to evaluate the memory usage for indexing path, I found there was an increase in memory used when using Zstd but not with other compression codec implementations.
This PR closes Zstd Dictionary after execution to avoid any memory leak.
Saw the following memory utilization with the existing implementation and after the change:

Close Zstd Dictionary after execution to avoid any memory leak.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/action/get/TransportGetAction.java
server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java
server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java

This change supports realtime reads for GET requests when segment replication is enabled. 
If there are no preferences mentioned for the incoming GET request then we route it to primary shards which serve strong reads by parsing source from the translog. 
Resolves #8536 

[Segment Replication] Support realtime reads for GET requests

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/action/get/TransportGetAction.java
server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java
server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java

Manual backport of #9212 due to changelog conflict.

[Backport 2.x][Segment Replication] Support realtime reads for GET requests (#9212)

---

server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalWithNodeSettingsIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
server/src/test/java/org/opensearch/index/IndexModuleTests.java

This PR aims to introduce notion of cluster level default and minimum index refresh interval. More details are present in #9266.
Resolves #9266

Introduce cluster default and minimum index refresh interval settings

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java

Backports 5cc73134321fb5c070664f7071014a3f0dedb39e to 2.x

[Backport 2.x] Close Zstd Dictionary after execution to avoid any memory leak. (#9403)

---

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java

Change log level of SegRep cancellations to debug.  These are noisy in tests where replication is cancelled on node drop.
related https://github.com/opensearch-project/OpenSearch/issues/8452

Change log level of SegRep cancellations to debug

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteSegmentStatsFromNodesStatsIT.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java

Adding cumulative bytes lag to the `remote_store` section of NodesStats. The new API output looks like the following:
```
"remote_store": {
"upload": {
"total_uploads": {
"started": "4.4mb",
"started_bytes": 4708635,
"succeeded": "4.4mb",
"succeeded_bytes": 4708635,
"failed": "0b",
"failed_bytes": 0
},
"refresh_size_lag": {
"total": "0b",
"total_bytes": 0,
"max": "0b",
"max_bytes": 0
},
"max_refresh_time_lag": "0s",
"max_refresh_time_lag_in_millis": 0
}
```
N/A …

[Remote Store] Add cumulative bytes lag to NodesStats

---

server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/test/java/org/opensearch/cluster/routing/ShardMovementStrategyTests.java

Fixes the flaky timeout issue on testClusterRelocationNoPreferenceShardMovementPrimaryFirstEnabled so it passes every time as expected. 
The issue was incorrect detection of the primary first shard movement strategy for throttling in the event that `ShardMovementStrategy` is set to `NO_PREFERENCE` and `movePrimaryFirst` deprecated setting is set to `true`.
Changed the logic of setting the shard movement strategy value. 
Resolves #9178 

Fix testClusterRelocationNoPreferenceShardMovementPrimaryFirstEnabled failure due to timeout

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java

- Currently, in `RemoteFsTranslog`, as part of `trimUnreferencedReaders`, we delete stale remote primary terms.
- The `deleteStaleRemotePrimaryTerms` function assumes existing list of translog readers to be non empty and have a corresponding assert.
- This assert results in flaky behavior of tests like: https://github.com/opensearch-project/OpenSearch/issues/9455
- In this PR, we remove the assert and return from `deleteStaleRemotePrimaryTerms` if translog reader list is empty.
- It is safe to remove the assert as translog reader list can be empty due to `super.trimUnreferencedReaders()` that is executed prior.
Resolves https://github.com/opensearch-project/OpenSearch/issues/9455 …

Bugfix: remove assert on non-empty translog reader list

---

.github/workflows/precommit.yml

Github action for Gradle precommit failing on MacOS (see please https://github.com/actions/runner-images/issues/8104)
Closes https://github.com/opensearch-project/OpenSearch/issues/9478

Github action for Gradle precommit failing on MacOS

---

.github/workflows/lucene-snapshots.yml
CHANGELOG.md

Backport https://github.com/opensearch-project/OpenSearch/commit/9fb86a5d647635d030065f856fb5b4d95bec1097 from https://github.com/opensearch-project/OpenSearch/pull/9457
Bumps [actions/setup-java](https://github.com/actions/setup-java) from 2 to 3.
- [Release notes](https://github.com/actions/setup-java/releases)
- [Commits](https://github.com/actions/setup-java/compare/v2...v3)
---
updated-dependencies:
- dependency-name: actions/setup-java 
- dependency-type: direct:production 
- update-type: version-update:semver-major
(cherry picked from commit 9fb86a5d647635d030065f856fb5b4d95bec1097)
n/a …

[2.x] Bump actions/setup-java from 2 to 3 (#9457)

---

CHANGELOG.md
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScoreScript.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
modules/lang-painless/src/main/java/org/opensearch/painless/action/PainlessExecuteAction.java
modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.score.txt
modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/120_script_score_term_frequency.yml
plugins/examples/script-expert-scoring/src/main/java/org/opensearch/example/expertscript/ExpertScriptPlugin.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/ExplainableScriptIT.java
server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreFunctionBuilder.java
server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunction.java
server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunctionFactory.java
server/src/main/java/org/opensearch/script/ScoreScript.java
server/src/main/java/org/opensearch/script/ScoreScriptUtils.java
server/src/main/java/org/opensearch/search/lookup/LeafSearchLookup.java
server/src/main/java/org/opensearch/search/lookup/LeafTermFrequencyLookup.java
server/src/test/java/org/opensearch/search/query/ScriptScoreQueryTests.java
test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java

Expose term frequency in Painless script score context.
Original issue - https://github.com/opensearch-project/OpenSearch/issues/7558
RFC - https://github.com/opensearch-project/OpenSearch/issues/8702

[Feature] Expose term frequency in Painless script score context

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
server/src/test/java/org/opensearch/index/store/StoreTests.java
server/src/test/java/org/opensearch/index/translog/TranslogHeaderTests.java

- If we have an index where all the ingested data is in translog alone (the first refresh is not triggered yet), restoring such index from remote store fails due to issue mentioned in https://github.com/opensearch-project/OpenSearch/issues/7923
- This happens as the translog UUID of the downloaded translog files do not match with that of segment files (that are created newly as part of restore)
- In this change, we make sure to create empty store with the same UUID that is present in the remote translog.
Resolves https://github.com/opensearch-project/OpenSearch/issues/7923 …

[Remote Store] Fix tests when we restore index without any refresh

---

server/src/main/java/org/opensearch/action/search/GetAllPitNodesResponse.java
server/src/main/java/org/opensearch/action/search/ListPitInfo.java
server/src/test/java/org/opensearch/action/search/GetAllPitNodesResponseTests.java

Today, we haven't reconstructed pit infos when deserialize GetAllPitNodesResponse, which causes corresponding field is empty.

[BUG] Reconstruct pit infos when deserialize GetAllPitNodesResponse

---

server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java

This test fails on ensureGreen after adding a replica. This is run inside of the try with resources that blocks operations.  The block works by mocking transport calls to prevent segrep from completing until released.  This will prevent force-sync recovery of the replica from completing, block recovery, and eventually result in ensureGreen timing out.  Fixed by moving the ensureGreen until after releasing blockOperations.
This PR also reduces the doc count that is used while indexing down from max 200.  Writes wit h the remote store version of this test take a much longer time to execute whe n performed serially, and we don't need this many docs indexed to create needed checkpoints.
Resolves #8887 …

Fix flaky test SegmentReplicationWithRemoteStorePressureIT.testAddReplicaWhileWritesBlocked

---

.github/workflows/check-compatibility.yml

Run compatibility check based on PR base branch rather than main branch. See [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) and [pull_request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
Resolves #9371 

Run compatibility check based on PR base branch

---

CHANGELOG.md
plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsBlobStoreRepositoryTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/utils/HttpRangeUtils.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RetryingInputStreamTests.java
test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java

The `readBlob(String, long, long)` method in the S3 repository has been broken since the upgrade to AWS SDK v2. The cause is that the SDK v2 returns the content range length details in a string formatting per the [RFC 9110][1] spec. For example:
```
bytes 0-100/200
```
However, the code was attempting to parse it as:
```
bytes=0-100
```
The fix here is to not parse this string at all and instead use `GetObjectResponse#contentLength`.
Note that the incorrect format matches how a range is specified in a _request_ per the [byte ranges][2] section of the RFC and that is likely the source of the confusion.. We lack any dedicated integration testing of this method so the bug was not caught by any tests. Additionally, the range read is only used by the searchable snapshot feature currently and …

Fix range reads in respository-s3

---

CHANGELOG.md
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScoreScript.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
modules/lang-painless/src/main/java/org/opensearch/painless/action/PainlessExecuteAction.java
modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.score.txt
modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/120_script_score_term_frequency.yml
plugins/examples/script-expert-scoring/src/main/java/org/opensearch/example/expertscript/ExpertScriptPlugin.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/ExplainableScriptIT.java
server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreFunctionBuilder.java
server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunction.java
server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunctionFactory.java
server/src/main/java/org/opensearch/script/ScoreScript.java
server/src/main/java/org/opensearch/script/ScoreScriptUtils.java
server/src/main/java/org/opensearch/search/lookup/LeafTermFrequencyLookup.java
server/src/test/java/org/opensearch/search/query/ScriptScoreQueryTests.java
test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java

Add the following functions in Painless script score context:
* termfreq
* tf
* totaltermfreq
* sumtotaltermfreq
Each of these maps to a Lucene value source.
Signed-off-by: Louis Chu <clingzhi@amazon.com>
(cherry picked from commit 5d3633cbecfaa1cdc4fcf5efd5ed1ec603de5081)

[Manual backport 2.x][Feature] Expose term frequency in Painless script score context (#9081)

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java

The `partSize()` value can be null if the underlying repository implementation does not implement file chunking.
Resolves #9291 

Handle null partSize in OnDemandBlockSnapshotIndexInput

---

CHANGELOG.md
plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsBlobContainer.java
plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsBlobStoreRepositoryTests.java

Implement range reads in HDFS repository

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/IndexModule.java

Removing the vec file extension from INDEX_STORE_HYBRID_NIO_EXTENSIONS, to ensure the no performance degradation for vector search via Lucene Engine.
This PR: https://github.com/opensearch-project/OpenSearch/pull/8508/files added .vec file extension in INDEX_STORE_HYBRID_NIO_EXTENSIONS and deprecated the setting : INDEX_STORE_HYBRID_MMAP_EXTENSIONS. Which made .vec not to be Mmapped. This resulted in below problems:
1. K-NN plugin was adding the required files like .vec and .vex to INDEX_STORE_HYBRID_MMAP_EXTENSIONS to make sure that files are Mmapped, for best performance. But now as the setting is deprecated the Unit test started to fail and K-NN plugin need to hack around to make sure that unit tests are succeeding. https://github.com/opensearch-project/k-NN/blob/3df8308bbe7ce6559b559f3 …

Removing the vec file extension from INDEX_STORE_HYBRID_NIO_EXTENSIONS, to ensure the no performance degradation for vector search via Lucene Engine.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteSegmentStatsFromNodesStatsIT.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/DirectoryFileTransferTracker.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java

Backporting https://github.com/opensearch-project/OpenSearch/pull/9393 and https://github.com/opensearch-project/OpenSearch/pull/9454 to `2.x` branch
Removing version checks also in this backport PR. Changes in `main` to remove the version checks would follow this PR.

[Backport-2.x] Adding extra fields under RemoteStore stats in NodeStats

---

server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java

Removing version checks from `RemoteSegmentStats` to retain BwC. This PR should be followed after https://github.com/opensearch-project/OpenSearch/pull/9544 is merged

[Remote Store] Removing version checks from RemoteSegmentStats

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
server/src/main/java/org/opensearch/common/StreamLimiter.java
server/src/main/java/org/opensearch/common/blobstore/transfer/stream/RateLimitingOffsetRangeInputStream.java
server/src/main/java/org/opensearch/index/snapshots/blobstore/RateLimitingInputStream.java
server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/repositories/FilterRepository.java
server/src/main/java/org/opensearch/repositories/Repository.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/test/java/org/opensearch/common/blobstore/transfer/stream/RateLimitingOffsetRangeInputStreamTests.java
server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
test/framework/src/main/java/org/opensearch/index/shard/RestoreOnlyRepository.java

* Rate Limiter integration for remote transfer, introduces repository settings to rate limit remote store uploads and downloads

[Backport 2.x]Rate Limiter integration for remote transfer (#9448)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

---------
Signed-off-by: bansvaru <bansvaru@amazon.com>
(cherry picked from commit a1d8bebab16fb099c85cb199af91fb4980dcafb8)

[Backport 2.x] Set replication type to SEGMENT in remote store enabled cluster if nothing specified by user (#9264)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java

- Currently, in remote store restore flow, we only restore primary and ignore replicas. But this creates issue with shards having replicas as mentioned in https://github.com/opensearch-project/OpenSearch/issues/8479
- In this change, we add replica information as well in the new routing table that is getting created as part of restore.
- We apply following logic:
- If primary of the shard is unassigned, mark it for restore and mark all the replicas for peer recovery
- If primary of the shard is active or initializing, do not mark it for restore. Check all replicas and mark replica for peer recovery only if replica is unassigned.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8479 …

Bugfix: add replica information in remote store restore flow

---

CHANGELOG.md
plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsBlobStoreRepositoryTests.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/utils/HttpRangeUtils.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RetryingInputStreamTests.java
test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java

Backports 0c839c3e35b4086acb88a276de9d10ece637d318 to `2.9`

[Backport 2.9] Fix range reads in respository-s3 (#9516)

---

.github/CODEOWNERS
MAINTAINERS.md

Backports 89ccda9a3a0f8120c0a701094c759d55288bd0bd from #9463 to `2.x`.
This brings the 2.x MAINTAINERS.md file in line with the version on main as I think another change was not backported, hence the conflict on cherry-pick.

[Backport 2.x] Add Michael Froh as a maintainer (#9463)

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/main/java/org/opensearch/search/query/QueryPhaseSearcherWrapper.java
server/src/main/java/org/opensearch/search/sort/SortAndFormats.java
server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

https://github.com/opensearch-project/OpenSearch/issues/9538

For sort request on timeseries field use non concurrent search path

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This change fixes an issue where replica shards can temporarily return stale results during promotion to primary.  This happens in `resetEngineToGlobalCheckpoint` because the shard temporarily flips to a ReadOnly engine and initializes its reader from disk.  This is possible because NRTReplicationEngine did not previously implement flush and the freshest data is only active on the reader. Fixed by implementing flush and also honoring acquireLatestCommit's flushFirst parameter.
related #8985
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.m …

[Segment Replication] Fix bug where replica shows stale doc count during engine reset.

---

server/src/main/java/org/opensearch/action/get/TransportGetAction.java
server/src/main/java/org/opensearch/cluster/ClusterState.java
server/src/test/java/org/opensearch/cluster/ClusterStateTests.java

Adds a public method in ClusterState which identifies whether for input index name, `SEGMENT` replication is enabled or not.
Resolves #9566

[Segment Replication] Add ClusterState utility to identify SEGMENT replication

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/DefaultSearchContext.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
server/src/main/java/org/opensearch/search/internal/SearchContext.java
server/src/main/java/org/opensearch/search/query/QueryPhaseSearcherWrapper.java
server/src/main/java/org/opensearch/search/sort/SortAndFormats.java
server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
test/framework/src/main/java/org/opensearch/test/TestSearchContext.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/9562
Resolves #https://github.com/opensearch-project/OpenSearch/issues/9538

[Backport] [2.x] For sort request on timeseries field use non concurrent search path

---

CHANGELOG.md
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingContextPropagator.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/http/HttpTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/http/package-info.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/TraceableRunnableTests.java
plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingContextPropagator.java
plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelTracingContextPropagatorTests.java
server/src/main/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorage.java
server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
server/src/test/java/org/opensearch/telemetry/tracing/WrappedTracerTests.java
test/telemetry/build.gradle
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingContextPropagator.java

Back port merge of - https://github.com/opensearch-project/OpenSearch/pull/9506

[Backport] [2.x] Add support to use trace propagated from client (#9506)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

[Backport 2.x] [Segment Replication] Fix bug where replica shows stale doc count during engine reset. (#9495)

---

.github/workflows/check-compatibility.yml

Compatibility-check workflow runs are frequently [failing](https://github.com/opensearch-project/OpenSearch/actions/workflows/check-compatibility.yml) with shutdown signal sent to GH runners.
```
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
```
This change increases the swapfile on the GH ubuntu runner to 10G as suggested [here](https://github.com/actions/runner-images/discussions/7188#discussioncomment-6750749). Tried in my fork and triggered 10 simultaneous runs https://github.com/gaiksaya/OpenSearch/actions/workflows/check-compatibility.yml and all of them passed.
Resolves #9549
For …

Fix GH runners memory issue by increasing swapfile

---

build.gradle

Retry `RemoteIndexShardTests` remote store flaky tests. These tests are failing frequently resulting in check failures, and lot of developer pain. These tests should be retried vs failing the gradle check. 
Sample gradle check failrues (there may be more).
1. https://build.ci.opensearch.org/job/gradle-check/23624
2. https://build.ci.opensearch.org/job/gradle-check/23669
Resolves None
Related 
1. https://github.com/opensearch-project/OpenSearch/issues/9598
2. https://github.com/opensearch-project/OpenSearch/issues/9586 …

[Remote Store] Retry RemoteIndexShardTests flaky tests

---

server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java

This test is yet again failing but only with remote store.  This time a concurrent flush can wipe out an old commit file while we are in the remote store refresh listener. The listener will fetch the latest infos from the reader which will reference a segments_n that has been deleted by an incoming flush.
To fix this, InternalEngine will conditionally acquire the previous commit point and preserve it until a new commit is loaded onto the reader.  This guarantees a commit point is not deleted while inside of an active refresh.
Resolves #https://github.com/opensearch-project/OpenSearch/issues/8059 …

Fix SegmentReplicationUsingRemoteStoreIT#testDropPrimaryDuringReplication.

---

test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetryPlugin.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java

There could be some asynchronous tasks running that we should await for before the closing up the tracer instance. Allow MockTracingTelemetry to await for asynchronous tasks termination before validating spans.
N/A

Allow MockTracingTelemetry to await for asynchronous tasks termination before validating spans

---

benchmarks/src/main/java/org/opensearch/benchmark/index/mapper/CustomBinaryDocValuesFieldBenchmark.java
server/src/main/java/org/opensearch/index/mapper/BinaryFieldMapper.java

Add benchmark to measure CustomBinaryDocValuesField.
We were considering using a TreeMap in CustomBinaryDocValuesField instead of ArrayList.  Benchmarks showed that ArrayList performs better.  We are keeping the benchmark code for future reference.
Resolves #6897

Add benchmark to measure CustomBinaryDocValuesField performance

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java

Adding metrics for concurrent segment search
PR has the following new metrics:
| Metric | Description |
| --- | --- |
| search.concurrent_query_total | The total number of query operations using concurrent segment search. |
| search.concurrent_query_time_in_millis | The total time for all query operations using concurrent segment search, in milliseconds. |
| search.concurrent_query_current | The number of query operations using concurrent segment search that are currently running. |
New node stats response:
```
curl "localhost:9200/_nodes/stats/indices/search?pretty" 
{
"_nodes" : {
"total" : 1,
"successful" : 1,
"failed" : 0
},
"cluster_name" : "runTask",
"nodes" : {
"eZDZszatQxKL_sKQZ3hUWg" : {
"timestamp" : 1693428497044,
"name" : "runTask-0",
"transport_address" : "127.0.0.1:9300", …
```

Adding concurrent search versions of query count/time metrics

---

server/src/main/java/org/opensearch/action/get/TransportGetAction.java
server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java
server/src/main/java/org/opensearch/cluster/ClusterState.java
server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java
server/src/test/java/org/opensearch/action/get/TransportMultiGetActionTests.java
server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/FailedNodeRoutingTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java

This change will ensure that the replica that's on the oldest opensearch version is promoted to primary in the event of a failover in a segment replication enabled cluster. This would avoid the problem of replicas on older opensearch versions not being able to read the segments sent by newer opensearch version primaries.
Resolves #9027 

[Segment Replication] Handle failover in mixed cluster mode

---

server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
server/src/main/java/org/opensearch/index/remote/RemoteStorePressureSettings.java
server/src/main/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactory.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/IndicesModule.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactoryTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreTestsHelper.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

1. Currently, `RemoteSegmentTransferTracker` is strongly coupled with `RemoteStorePressureService`. `RemoteStorePressureService` is the provider of the trackers while it should just be consuming it. This PR decouples `RemoteSegmentTransferTracker` from `RemoteStorePressureService` by introducing the concept of a factory that manages the stats trackers.
2. Currently, `RemoteSegmentTransferTracker` allows setting a different moving average window size for upload bytes, upload speed, and upload time. These don't add much value and would rather deteriorate the user experience. We change these to apply a single window size for moving average stat calculations.
#8311
For more …

[Remote Store] Add tracker factory to manage remote store stats trackers

---

server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java

[Backport 2.x] Fix SegmentReplicationUsingRemoteStoreIT#testDropPrimaryDuringReplication. (#9471)

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/gateway/remote/package-info.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

Create service to publish cluster state to remote store
Backport for #9160 

[Backport 2.x][Remote State] Create service to publish cluster state to remote store (#9160)

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java
modules/analysis-common/src/main/java/org/opensearch/analysis/common/DelimitedTermFrequencyTokenFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/DelimitedTermFrequencyTokenFilterFactoryTests.java
modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/9479 to `2.x`

[Backport] [2.x] Expose DelimitedTermFrequencyTokenFilter (#9479)

---

CHANGELOG.md
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsVerifyingBlobContainer.java
server/src/main/java/org/opensearch/common/blobstore/VerifyingMultiStreamBlobContainer.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/FileCompletionListener.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/FilePartWriter.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListener.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/package-info.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/package-info.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/FileCompletionListenerTests.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/FilePartWriterTests.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ListenerTestUtils.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java

- Adds async blob read and download support using multiple streams using new APIs
- The entire code is laid out as a part of #9182 
The request flow can be visualized using the following diagram: 
Partially resolves https://github.com/opensearch-project/OpenSearch/issues/9031

Add async blob read and download support using multiple streams

---

server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java

Mutes RemoteIndexShardTests tests which are flaky and causing gradle check failures. These tests were originallly introduced in https://github.com/opensearch-project/OpenSearch/pull/5579 and then refactored to separate test class `RemoteIndexShardTests` in https://github.com/opensearch-project/OpenSearch/pull/8767.  I added this test class for retry consideration in https://github.com/opensearch-project/OpenSearch/pull/9597 hoping to see reduction in gradle check failures but it did not help and in most cases all retry attempts fails - resulting in gradle check failures. I think muting them for now is the right decision until these tests are fixed. 
CC @sachinpkale @mch2 @anasalkouz 
Relates …

Mute RemoteIndexShardTests primary promotion flaky tests

---

server/src/main/java/org/opensearch/rest/action/cat/RestPitSegmentsAction.java

Today, CAT APIs decide whether to include column headers based on query parameter `v`, but these headers are included by default in pit segments response.

remove redundent column headers in pit segments response

---

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java

This change allows segment replication to proceed when local store contains files that are not referenced by active reader. This currently fails with `FileAlreadyExistsException` because for replica we only consider files referenced by active reader while evaluating the [diff](https://github.com/opensearch-project/OpenSearch/blob/81c7b9773cbb862bbb3e36695077c62bcfdaa7b6/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java#L180) in order to request missing files. Since, these files are already copied the attempt to copy again fails with the exception. This change is better as it 
1. Prevents duplicate file copy actions.
2. Prevent fatal exception resulting in replication failure.
```
Caused by: java.util.concurrent.ExecutionException: …
```

[Segment Replication] Allow segment replication with on disk files not referenced by reader with matching checksum

---

CHANGELOG.md
qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

Fix SegRep's bytesbehind metric to be accurate by computing a diff of segments referenced by each ReplicationCheckpoint.
This change adds a map of StoreFileMetadata to ReplicationCheckpoint, which is computed from the SegmentInfos used to build the checkpoint.
Resolves #9685

Fix Segment Replication stats bytes behind metric

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java

Mute RemoteIndexRecoveryIT.testReplicaRecovery flaky test as it has caused a flurry of gradle check failures. This test was probably missed in https://github.com/opensearch-project/OpenSearch/pull/8812 where remaining flaky tests were overridden in RemoteIndexRecoveryIT. 
Relates: https://github.com/opensearch-project/OpenSearch/issues/9580
Relates: https://github.com/opensearch-project/OpenSearch/issues/8919 …

[Remote Store] Mute RemoteIndexRecoveryIT.testReplicaRecovery flaky test

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java

Add average query concurrency metric for concurrent segment search. The average is computed as `sum(queryConcurrency across shards) / sum(concurrentQueryCount across shards)` rather than the average of the shard level averages.
Sample outputs:
```
"search" : {
"open_contexts" : 0,
"query_total" : 1,
"query_time_in_millis" : 9,
"query_current" : 0,
"concurrent_query_total" : 0,
"concurrent_query_time_in_millis" : 0,
"concurrent_query_current" : 0,
"concurrent_avg_slice_count" : 0.0,
"fetch_total" : 1,
"fetch_time_in_millis" : 13,
"fetch_current" : 0,
"scroll_total" : 0,
"scroll_time_in_millis" : 0,
"scroll_current" : 0,
"point_in_time_total" : 0,
"point_in_time_time_in_millis" : 0,
"point_in_time_current" : 0,
"suggest_total" : 0,
"suggest_time_in_millis" : 0,
"suggest_current" : 0
}
``` …

Add average query concurrency metric for concurrent segment search

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

- Adds support to download latest IndexMetadata from remote cluster state.
- Please skip the changes in ClusterMetadataMarker file as it is part of the upload PR - https://github.com/opensearch-project/OpenSearch/pull/9160/files

Add support download latest index metadata from remote

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java

Any `_search` query return `hits.total.value` in response like mentioned in below example. Which specifies how many hits are matching actual query (sort/search_after are not part of query).
i.e, check response for below query
```
GET logs-*/_search
{
"query": {
"match_all": {}
},
"sort" : [
{"@timestamp" : "asc"}
],
"search_after": ["1998-06-01"]
}
```
Response [partial]
```
{
"took": 25,
"timed_out": false,
"_shards": {
"total": 35,
"successful": 35,
"skipped": 0,
"failed": 0
},
"hits": {
"total": {
"value": 10000,
"relation": "gte"
},
"max_score": null,
"hits": [
{
"_ind
```
This `hits.total.value` is capped at `10000` max as lucene can match at max 10000 documents in results.
If you want exact match in `hits.total.value`, we need to add `track_total_hits=true` in request parameter. …

Disable shard/segment level search_after short cutting if track_total_hits != false

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/main/java/org/opensearch/index/SegmentReplicationShardStats.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/SegmentReplicationCheckpointPublisher.java
server/src/main/java/org/opensearch/indices/replication/common/SegmentReplicationLagTimer.java
server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
server/src/test/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationActionTests.java

[Backport 2.x] Decouple replication lag from logic to fail stale replicas (#9507)

---

server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This change prevents snapshots from being taken with segment replication during shard promotion.  This prevents snapshots from being taken on stale data.
Resolves https://github.com/opensearch-project/OpenSearch/issues/9626

Segment Replication - Block snapshot creation if the target primary shard has not completed failover.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/index/IndexModuleTests.java
server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Backport https://github.com/opensearch-project/OpenSearch/commit/f5d3fd2483f58cdbb0d77cf53a1e5439b3cc860a from https://github.com/opensearch-project/OpenSearch/pull/9584

[Backport 2.x] Introduce cluster default remote translog buffer interval setting (#9584)

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/coordination/PersistedStateRegistry.java
server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
server/src/test/java/org/opensearch/cluster/coordination/PreVoteCollectorTests.java
server/src/test/java/org/opensearch/cluster/coordination/PublicationTests.java
server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/cluster/coordination/CoordinationStateTestCluster.java
test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java
test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java

Follow up PR for : https://github.com/opensearch-project/OpenSearch/pull/9160
In the above PR, RemotePersistedState and RemoteClusterStateService were created. In the current PR, these classes are integrated into the cluster state publish flow. The upload of cluster metadata will happen just before the cluster state publish request is sent to all nodes
https://github.com/opensearch-project/OpenSearch/issues/9338
Previous PR in forked repo: https://github.com/soosinha/OpenSearch/pull/3
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#deve …

[Remote state] Integrate remote cluster state in publish/commit flow

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java

2.x Backport PR for concurrent segment search related metrics
- #9622 
- https://github.com/opensearch-project/OpenSearch/pull/9670

[Backport 2.x] Adding concurrent search versions of query count and time metrics (#9622)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/main/java/org/opensearch/index/ReplicationStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/9709 to 2.x branch

[Segment Replication] Adding segment replication statistics rolled up at index, node and cluster level (#9709)

---

server/src/main/java/org/opensearch/index/engine/SegmentsStats.java

With this [PR](https://github.com/opensearch-project/OpenSearch/pull/9709) we have temporarily changed the version from 2_10_0 to 3_0_0. As the PR is merged and backported we can now revert it back to 2_10_0

[Segment Replication] Update version back to 2_10_0 in Segmentstats.

---

server/src/main/java/org/opensearch/index/search/stats/SearchStats.java

Fix the bwc for concurrent segment search stats. This PR is to be merged alongside 
* https://github.com/opensearch-project/OpenSearch/pull/9653

Fix bwc version for concurrent segment search stats

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/SearchService.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/test/java/org/opensearch/search/SearchServiceTests.java

[Backport 2.x] Disable shard/segment level search_after short cutting if track_total_hits != false (#9683)

---

.github/CODEOWNERS
MAINTAINERS.md

Peter has contributed to OpenSearch in a multitude of ways but primarily as a code reviewer.  He has reviewed 93 PRs:
https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+reviewed-by%3Apeternied
Peter has created 60 issues on the OpenSearch repo, many associated with security and identity discussions:
https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aissue+author%3Apeternied
Peter has been active on the OpenSearch repo since its early days, when he helped with the initial Jenkins CI setup (Jenkins and DCO enforcement):
https://github.com/opensearch-project/OpenSearch/pull/96
https://github.com/opensearch-project/OpenSearch/pull/123
https://github.com/opensearch-project/OpenSearch/pull/152
Peter led the Identity feature and authored multiple associated PRs …

Add Peter Nied as a Maintainer

---

server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java

This changes name of fields from `total_uploads` to `total_upload_size` and `total_downloads` to `total_download_size` for consistency in remote store stats api and node stats api segment/translog section. Also, renames `total_syncs_to_remote` to `total_uploads` for segments upload in remote store stats api.
Sample response snippet for node stats api -
```
"remote_store": {
"upload": {
"total_upload_size": {
"started_bytes": 8056,
"succeeded_bytes": 8056,
"failed_bytes": 0
},
"refresh_size_lag": {
"total_bytes": 0,
"max_bytes": 0
},
"max_refresh_time_lag_in_millis": 0,
"total_time_spent_in_millis": 58
},
"download": {
"total_download_size": {
"started_bytes": 0,
"succeeded_bytes": 0,
"failed_bytes": 0
},
"total_time_spent_in_millis": 0
}
},
```
Sample snippet of remote store stats api - …

Rename remote store stats field names

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/profile/AbstractInternalProfileTree.java
server/src/main/java/org/opensearch/search/profile/AbstractProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/ContextualProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/query/AbstractQueryProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/InternalQueryProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ProfileWeight.java
server/src/main/java/org/opensearch/search/profile/query/QueryProfiler.java
server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

At present, the query profiler is the total timing obtained by summing all segments. However, this does not accurately represent the detailed timing of the query, including queue time and gap time, during concurrent execution. This PR will address the problem.
``` json
{
"took": 61,
"timed_out": false,
"num_reduce_phases": 2,
"_shards": {...},
"hits": {...},
"profile":
{
"shards":
[
{
"id": "[FFjuubYPTGSYwNLsL2ccbA][test][0]",
"inbound_network_time_in_millis": 6,
"outbound_network_time_in_millis": 1,
"searches":
[
{
"query":
[
{
"type": "TermQuery",
"description": "field1:one",
"time_in_nanos": 3944209,
"max_slice_time_in_nanos": 3944209,
"min_slice_time_in_nanos": 3892625,
"avg_slice_time_in_nanos": 3918417,
"breakdown":
{
"max_match": 0,
"set_min_competitive_score_count": 0, …
```

Add support for query profiler with concurrent aggregation

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Currently, during segment merge (both during auto merge and force merge), OpenSearch creates multiple temporary files while merging individual segment components. Once individual components of the segments are merged, IndexWriter creates a Compound file (*.cfs) containing all the Lucene components for a segment. At the end, OpenSearch deletes these temporary files.
Now, in case these temporary files consume all the space on the node (because enough amount of space is unavailable for segment merge to go through), segment merge will fail. Also, the files which got created during segment merge do not get cleaned up and it continues to occupy space on the node. This can cause FSHealthService checks to fail for this node, ultimately causing these nodes to be removed from cluster.
Expected …

Cleanup Unreferenced file on segment merge failure

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java

Retrying translog download if it fails due to no file found for a finite time
In Primary to Primary relocation , there can be concurrent upload and download of translog.
While translog files are getting downloaded by new primary, it might hence be deleted by the primary
Hence we retry if tlog/ckp files are not found .
This doesn't happen in last download , where it is ensured that older primary has stopped modifying tlog data.
Resolves #9191

Retry download of RemoteFSTranslog to fix transient race conditions

---

server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java

We're comparing for unequal manifests but randomBoolean() has a high probability of getting clashed because of a small search-space, making test flaky. Let's limit randomization here.
Resolves #9688

fix: flaky test ClusterMetadataManifestTests

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
server/src/main/java/org/opensearch/cluster/coordination/PersistedStateRegistry.java
server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
server/src/test/java/org/opensearch/cluster/coordination/PreVoteCollectorTests.java
server/src/test/java/org/opensearch/cluster/coordination/PublicationTests.java
server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/cluster/coordination/CoordinationStateTestCluster.java
test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java
test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java

Integrate remote cluster state in publish/commit flow
Backport for #9665 

[Remote state] Integrate remote cluster state in publish/commit flow (#9665)

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

(cherry picked from commit 37bdb6bb6536b31392f1dcfaa0eb0f0ab283c2c9)
Backport https://github.com/opensearch-project/OpenSearch/pull/9503

[Backport 2.x] Cleanup Unreferenced file on segment merge failure (#9503)

---

server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexPrimaryRelocationIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java

Fixing Flaky Test - https://github.com/opensearch-project/OpenSearch/actions/runs/6094377255/job/16535787653?pr=9664

[Remote Store] Fixing flaky test - RemoteIndexPrimaryRelocationIT

---

server/src/main/java/org/opensearch/action/admin/cluster/crypto/CryptoSettings.java
server/src/main/java/org/opensearch/cluster/metadata/CryptoMetadata.java
server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
server/src/test/java/org/opensearch/node/RemoteStoreNodeAttributeTests.java

Crypto Metadata support in repo registration
Sample repo details 
```
"node.attr.remote_store.segment.repository" , "remote-store-A",
"node.attr.remote_store.repository.remote-store-A.type" , "s3",
"node.attr.remote_store.repository.remote-store-A.settings.bucket" , "abc",
"node.attr.remote_store.repository.remote-store-A.settings.base_path" , "xyz",
"node.attr.remote_store.repository.remote-store-A.crypto_metadata.key_provider_name" , "store-test",
"node.attr.remote_store.repository.remote-store-A.crypto_metadata.key_provider_type" , "aws-kms",
"node.attr.remote_store.repository.remote-store-A.crypto_metadata.settings.region" , "us-east-1",
"node.attr.remote_store.repository.remote-store-A.crypto_metadata.settings.key_arn" , "arn:aws:kms:us-east-1:12345:key/6e9aa906"
```
Partially …

Crypto Metadata support in repo registration

---

server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java

- Mutes flaky test #9776 till a fix is out

Mute flaky test ReadContextListenerTests.testReadContextListenerFailure

---

server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/main/java/org/opensearch/node/Node.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

* Add support to restore remote cluster state in RemoteStoreRestoreService
(cherry picked from commit 81d2ae1ccbd2b68926c7e03ae55922f3bbee9be8)
Backports https://github.com/opensearch-project/OpenSearch/pull/9086 to 2.x
NA

[Backport 2.x][Remote Store] Add support to remote restore IndexMetadata (#9086)

---

server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

- Currently, NRTReplicationEngine calls `store.incRef()` in the constructor and corresponding `store.decRef()` is only called on IOException.
- But in case of exceptions like `TranslogCorruptedException`, store is not de-referenced causing ShardLock issues.
- In this PR, we make sure to always call `store.decRef()` if there is a failure in creating NRTReplicationEngine.

Decrease store refcount on any failure to create NRTReplicationEngine

---

server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
server/src/test/java/org/opensearch/node/RemoteStoreNodeAttributeTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java

- Remote Store related settings were moved to node attrs as part of https://github.com/opensearch-project/OpenSearch/issues/8623
- Remote Cluster state introduced another cluster settings. We need to move this cluster settings to node attrs as well.
Resolves #9813

[Remote Cluster State] Move remote cluster state related settings to node attrs

---

modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java
plugins/custom-codecs/src/internalClusterTest/java/org/opensearch/index/codec/CodecCompressionLevelIT.java
plugins/custom-codecs/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecMergeIT.java

There were flaky instances where the codec was being loaded for the index, before the lock obtained to close shard was released. With this change, we will wait for the shards before proceeding for the next step.
Resolves #9872, #9853

[Bug Fix] Fixing Flaky Codec Tests

---

CHANGELOG.md
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java

Follow up PR of https://github.com/opensearch-project/OpenSearch/pull/9746
This PR uses the logic to fetch previous cluster UUID of the above PR to restore the index metadata during bootstrap.
Resolves #9821 

Restore cluster metadata during bootstrap

---

qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java

https://github.com/opensearch-project/OpenSearch/pull/9686 temporarily muted `testIndexingWithPrimaryOnBwcNodes` due to addition of new field (StoreFileMetadata map) in ReplicationCheckpoint class. As the change is backported to 2.x, we can unmute testIndexingWithPrimaryOnBwcNodes test.
Resolves #None
Relates: #9685 

Unmute testIndexingWithPrimaryOnBwcNodes

---

server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

Backport PR for https://github.com/opensearch-project/OpenSearch/pull/9746

[Backport 2.10] Add logic to fetch previousClusterUUID (#9746)

---

server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java

Changing compatibility version of sourceRemoteStoreRepository in RestoreSnaphotRequest back to 2.10. This PR should follow backport PRs:
- https://github.com/opensearch-project/OpenSearch/pull/9892
- https://github.com/opensearch-project/OpenSearch/pull/9901
https://github.com/opensearch-project/OpenSearch/issues/9792

[Remote Store] Changing compatibility version of sourceRemoteStoreRepository in RestoreSnaphotRequest back to 2.10

---

server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/199123d9d62a726dfcbf8e0530dff265844fe91f from https://github.com/opensearch-project/OpenSearch/pull/9796.

[Backport 2.10] Decrease store refcount on any failure to create NRTReplicationEngine

---

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java

- With Remote Cluster State https://github.com/opensearch-project/OpenSearch/issues/9143, we have multiple files in blob store related to cluster state. 
- Overtime few of these files will become stale and we only need files references by latest cluster state.
- This change ensures these stale unreferenced files are cleaned with every cluster state write to remote
Resolves #9343 

[Remote Cluster State] Remove stale remote cluster state

---

server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/199123d9d62a726dfcbf8e0530dff265844fe91f from https://github.com/opensearch-project/OpenSearch/pull/9796.

[Backport 2.x] Decrease store refcount on any failure to create NRTReplicationEngine

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java

Disabling the query profile tests with concurrent execution for now and track to enable it as part of the rewrite fix.
Resolves #9815 #9787

Mute the query profile IT with concurrent execution

---

server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

- Disable remote data integrity for encrypted repos in ChecksumBlobstoreFormat
NA

Disable remote integrity check for encrypted repos for ChecksumBlobstoreFormat

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/aggregations/MissingValueIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Parameterize tests annotated with @OpenSearchIntegTestCase.SuiteScopeTestCase.
Without this, the parameterization is not working as initializeSuiteScope() expects a default constructor and we have a different constructor with parameterization.
ref: https://build.ci.opensearch.org/job/gradle-check/24979/testReport/junit/org.opensearch.search.aggregations/MissingValueIT/classMethod/
this has many classes failing with this exception: https://build.ci.opensearch.org/job/gradle-check/24979/#showFailuresLink
Relates #9443  …

Parameterize tests with OpenSearchIntegTestCase.SuiteScopeTestCase annotation

---

CHANGELOG.md
benchmarks/src/main/java/org/opensearch/common/ArrayRoundingBenchmark.java
server/src/main/java/org/opensearch/common/Rounding.java
server/src/test/java/org/opensearch/common/RoundingTests.java

[Backport 2.x] Improve performance of rounding dates in date_histogram aggregation

---

CHANGELOG.md
benchmarks/src/main/java/org/opensearch/common/ArrayRoundingBenchmark.java
server/src/main/java/org/opensearch/common/Rounding.java
server/src/test/java/org/opensearch/common/RoundingTests.java

[Backport 2.10] Improve performance of rounding dates in date_histogram aggregation

---

plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/CorrelationCodecTests.java

Fix is pending in #7771, but that PR may take some time to land in main so muting for the time being.
Related #8329

Mute CorrelationCodecTests.testCorrelationVectorIndex

---

.github/workflows/check-compatibility.yml

Instead of appending a new comment every time check compatibility runs, this will instead update a single comment with the latest results. The history of previous runs is retained in the comment as GitHub allows you to view the edited revisions of any comment. This matches the behavior of the codecov workflow and should substantially reduce noise in PRs.
Relates #9699
I tested this [on my user fork](https://github.com/andrross/OpenSearch/pull/208#issuecomment-1708952354):
Assuming folks like this approach, I'll do the same thing for the gradle check comment. …

Update single comment for check compatibility

---

server/src/internalClusterTest/java/org/opensearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
server/src/main/java/org/opensearch/cluster/coordination/UnsafeBootstrapClusterManagerCommand.java

During unsafe bootstrap, node will form a cluster with a new cluster UUID but with the existing metadata. This new state will not know about the previous cluster UUIDs and so we will not able to construct the cluster UUID chain to get the last known cluster UUID to restore from. So we need to block unsafe-bootstrap when remote cluster state is enabled.
#9926 

Block unsafe bootstrap when remote state is enabled

---

CHANGELOG.md
client/rest/src/main/java/org/opensearch/client/nio/HeapBufferedAsyncEntityConsumer.java
client/rest/src/test/java/org/opensearch/client/nio/HeapBufferedAsyncEntityConsumerTests.java

The HeapBufferedAsyncEntityConsumer over-allocates the response buffer (up to configured limit, by default of 100Mb) in order to consume the response. This may not be an issue in most cases but if there are many requests being sent in parallel, the memory overhead will be noticeable. 
This is not a memory leak (all resources are properly closed) but the consequences of over committing the heap buffers.
Closes https://github.com/opensearch-project/OpenSearch/issues/9866 …

Don't over-allocate in HeapBufferedAsyncEntityConsumer in order to consume the response

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cat.thread_pool/10_basic.yml
server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchThreadPoolExecutor.java
server/src/main/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutor.java
server/src/main/java/org/opensearch/common/util/concurrent/QueueResizingOpenSearchThreadPoolExecutor.java
server/src/main/java/org/opensearch/common/util/concurrent/TimedRunnable.java
server/src/main/java/org/opensearch/rest/action/cat/RestThreadPoolAction.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/main/java/org/opensearch/threadpool/ThreadPoolStats.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/threadpool/ThreadPoolStatsTests.java

Adds threadpool wait time metric for threadpool executors that support TimedRunnable
Sample output excerpt:
```
curl "localhost:9200/_nodes/stats/thread_pool?pretty&human"
"remote_refresh_retry" : {
"threads" : 0,
"queue" : 0,
"active" : 0,
"rejected" : 0,
"largest" : 0,
"completed" : 0
},
"search" : {
"threads" : 2,
"queue" : 0,
"active" : 0,
"rejected" : 0,
"largest" : 2,
"completed" : 2,
"total_wait_time" : "629.9micros",
"total_wait_time_in_nanos" : 629932
},
"search_throttled" : {
"threads" : 0,
"queue" : 0,
"active" : 0,
"rejected" : 0,
"largest" : 0,
"completed" : 0,
"total_wait_time" : "0s",
"total_wait_time_in_nanos" : 0
},
```
```
dengjay@88665a3f24d4 OpenSearch % curl "localhost:9200/_cat/thread_pool?v&h=name,twt"
name                         twt
analyze …
```

Add threadpool wait time metric

---

modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.score.txt
server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunctionFactory.java
server/src/main/java/org/opensearch/script/ScoreScriptUtils.java

Remove tf() painless method
https://github.com/opensearch-project/OpenSearch/issues/9958

Remove tf() painless method

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/aggregations/MissingValueIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

[Backport] [2.x] Allow parameterization of tests with OpenSearchIntegTestCase.SuiteScopeTestCase annotation

---

CHANGELOG.md
buildSrc/build.gradle
test/fixtures/hdfs-fixture/build.gradle

- Fixes the following CVEs for `1.3`
- - CVE-2023-34453
- - CVE-2023-2976
- -  CVE-2023-34455
- - CVE-2023-3635
- - CVE-2023-34610

[Backport 1.3] Force upgrade the vulnerable dependencies of hadoop-minicluster, Enforce up-to-date Guava in buildSrc 

---

.github/workflows/copy-linked-issue-labels.yml

- Add workflow to copy labels from linked issues to the PR
Resolves #8199

Add workflow to copy labels from linked issues to the PR

---

qa/evil-tests/build.gradle

Potentially fixes CVEs for `1.3`
- CVE-2023-2976
Resolves CVE-2023-2976

[Backport 1.3] Bump guava dependency to 32.0.1-jre 

---

.github/workflows/precommit.yml

For a while, I've noticed that one of our workflows has an extra "s" in "Asssemble". I finally decided to fix it.
N/A

Fix typo in Precommit and Assemble workflow

---

qa/evil-tests/build.gradle

- Exclude packaged guava from jimfs

Exclude packaged guava from jimfs

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java

- [org.opensearch.remotestore.RemoteStoreRestoreIT.testRateLimitedRemoteDownloads](https://build.ci.opensearch.org/job/gradle-check/24888/testReport/junit/org.opensearch.remotestore/RemoteStoreRestoreIT/testRateLimitedRemoteDownloads/) test slows down restore by adding rate limit in repository settings.
- Due to the rate limit, if the recovery takes more time, `ensureGreen` check fails, making the test flaky.
- In this change, we increase timeout of `ensureGreen` from default 30secs to 120secs
- One of the failed builds: https://build.ci.opensearch.org/job/gradle-check/24888/ …

Fix flaky behavior of RemoteStoreRestoreIT.testRateLimitedRemoteDownloads

---

CHANGELOG.md
plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/single/SingleNodeDiscoveryIT.java
server/src/main/java/org/opensearch/telemetry/tracing/handler/TraceableTransportResponseHandler.java
server/src/main/java/org/opensearch/telemetry/tracing/handler/package-info.java
server/src/main/java/org/opensearch/transport/TransportResponseHandler.java
server/src/main/java/org/opensearch/transport/TransportService.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Add tracing instrumentation in transport service.
Resolves #8553

Add tracing instrumentation in transport service

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/translog/TranslogHeader.java

- In the restore from snapshot flow, primary shards are recovered from snapshot data and replica shards are recovered using peer-recovery flow.
- The changes in this PR address following issue which is applicable only to remote store enabled indices.
- If we execute following steps in order:
- Create index
- Ingest docs
- Take a snapshot
- Delete index
- Created index with the same name
- The new index gets created with different translog UUID. The data in snapshot refers to older translog UUID.
- After recovering primary from snapshot, remote segment store is not updated with new data until the value of [primaryMode is true](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java#L170). 
- Before …

Always create empty translog on replica for remote store enabled index

---

CHANGELOG.md
plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/single/SingleNodeDiscoveryIT.java
server/src/main/java/org/opensearch/telemetry/tracing/handler/TraceableTransportResponseHandler.java
server/src/main/java/org/opensearch/telemetry/tracing/handler/package-info.java
server/src/main/java/org/opensearch/transport/TransportResponseHandler.java
server/src/main/java/org/opensearch/transport/TransportService.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

[Backport] [2.x] Add instrumentation in transport service.

---

server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java

- After Cluster Manager recovery or a fresh cluster bootstrap, we trigger the `GatewayService.RecoverStateUpdateTask` which performs various mutations to the cluster state.
- One of the mutations blindly overrides the routing table in the cluster state. This makes sense as after recovery or new cluster bootstrap, routing table should be generated from scratch.
- But for Remote Store and Remote Cluster State enabled clusters, we auto restore previous valid cluster state from Remote(Only IndexMetadata in 2.10). So routing tables are generated as part of restore flow with remote store recovery source.
- To avoid `GatewayService.RecoverStateUpdateTask` overriding the pre-generated routing table entries for remote store clusters we have skipped the routing table override.
- If we did not skip …

skip overriding routing table when it already contains entries with remote recovery source

---

server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/IndexSortConfig.java

While resolving one of comment, https://github.com/opensearch-project/OpenSearch/pull/10045#discussion_r1326049739
I added `shouldWidenIndexSortTpe` as a class member and initialized from Settting.
But `IndexSortConfig` constructor is always getting called before `IndexSettings` determines the current version and put `shouldWidenIndexSortTpe` in their class. So `shouldWidenIndexSortTpe` always stayed false after that change and lead failuers in integ test `org.opensearch.backwards.IndexingIT.testUpdateSnapshotStatus` in 2.10 branch.
I am going to update this PR as well https://github.com/opensearch-project/OpenSearch/pull/10076

Integ test fix -> Fix broken backward compatibility from 2.7 for IndexSorted field indices #10045

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

Optimize read write lock constructs during translog upload to remote store
Resolves #10013

Optimize read write lock constructs during translog upload to remote store

---

server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

This fixes the logic for generating the cluster chain when a new cluster manager node is bootstrapping
#10019 

Fix cluster chaining during bootstrap

---

server/src/main/java/org/opensearch/index/mapper/MapperService.java

This error message is no longer relevant and should not be used now.
Closes: #7007
Removing outdated error message.
#7007 

Remove outdated default index mapping error message

---

.github/workflows/precommit.yml

Update Github action for Gradle precommit on MacOS
Reverting https://github.com/opensearch-project/OpenSearch/pull/9486 mitigation, it should be now in GA MacOS image

Update Github action for Gradle precommit on MacOS

---

server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java

There can be cases where one or more slice may not have timing related information for its leaves in contexts map. During creation of slice and query level breakdown map it needs to handle such cases by using default values correctly. Also updating the min/max/avg sliceNodeTime to not include time to create weight and wait times by slice threads. It will reflect the min/max/avg execution time of each slice whereas totalNodeTime will reflect the total query time.
Resolves #9815  …

Fix NPE in ConcurrentQueryProfile while computing the breakdown map for slices

---

CHANGELOG.md
buildSrc/build.gradle

Bump version of jgit to 6.7.0.202309050840-r to fix CVE-2023-4759

---

plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapperTests.java
qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java

Removing extra protobuf notice file

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

#10117
Resolves #10117 and #10133

Downgrade write lock to read lock before translog upload to remote store

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/9752 to `2.x`

[Backport] [2.x] Bump com.github.tomakehurst:wiremock-jre8-standalone from 2.35.0 to 3.0.1 in /buildSrc (#9752)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java

- As a part of the changes for repository registration (#9105) the default repository type was switched to `FsRepository` within `RemoteStoreBaseIntegTestCase`
- This fixes and reenables the usage of `MockFsRepository` and `MockFsAsyncBlobContainer` for `RemoteStoreMultipartIT`

Reenable multipart repository within multipart ITs

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainer.java
server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobContainer.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
server/src/test/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainerTests.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ListenerTestUtils.java

- Add async blob read support for encrypted containers
Resolves #10105 

Add support for encrypted async blob read

---

server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/StoreTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

- This PR builds on top of #9592 and utilizes the new APIs within core
- The APIs will be used within the `RemoteSegmentStoreDirectory` path to copy over segment files from the remote store.
- Logically, the caller will not see any difference within the workings of download segments but the files will be parallelized and each file will support multiple streams for download due to the async nature of the APIs.
Resolves #8596 

Add async segment file download support from remote store within OpenSearch core

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
server/src/test/java/org/opensearch/index/OpenSearchTieredMergePolicyTests.java

There are latency-sensitive users for whom the default 20% allowable accumulation of deletes is too high, so they force merge with "only_expunge_deletes".
Unfortunately, this has ignored the max segment size, so despite the word "only" in there, they get the terrible side-effect of producing segments larger than the max segment size. These oversized segments are unlikely to participate in future merges, until they have so many deletes that they could drop back below the max segment size, likely making the whole "too many deletes" problem even worse.
This commit fixes that so that "only_expunge_deletes" ONLY EXPUNGES DELETES without creating oversized segments.
Resolves #7644 …

Honor max segment size during only_expunge_deletes

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/cbff21d7ea58d3185b969df43f48de10e32180e2 from https://github.com/opensearch-project/OpenSearch/pull/10135.

[Backport 2.x] Downgrade write lock to read lock before translog upload to remote store

---

CHANGELOG.md
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanContext.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanCreationContext.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanKind.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingTelemetry.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/runnable/TraceableRunnable.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/TraceableRunnableTests.java
plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelSpanKindConverter.java
plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingTelemetry.java
plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelSpanKindConverterTests.java
plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelTracingTelemetryTests.java
server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
server/src/test/java/org/opensearch/telemetry/tracing/TracerFactoryTests.java
server/src/test/java/org/opensearch/telemetry/tracing/WrappedTracerTests.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpan.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingContextPropagator.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java

Add support for span kind in the tracer. It will help if categorising the spans. 
Resolves #10121

[Tracing Framework] Add support for SpanKind

---

server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
server/src/test/java/org/opensearch/index/query/ScriptQueryBuilderTests.java
server/src/test/java/org/opensearch/index/query/ScriptScoreQueryBuilderTests.java

Adding Visit method in Script Score Query Builder. I missed it in my earlier PR [https://github.com/opensearch-project/OpenSearch/pull/10110](https://github.com/opensearch-project/OpenSearch/pull/10110)

Script Score Query Builder Visit Method

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

This PR brings in the code to restrict indexes with async translog durability mode. This is achieved by enabling a cluster setting that by default allows creating indexes with any translog durability mode. However, if the cluster setting is true, it would restrict creation or updation of index which tries to set the durability to async mode.
Resolves #10186

Add capability to restrict async durability mode for remote indexes

---

libs/core/src/main/java/org/opensearch/core/index/Index.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandler.java
server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

This PR improves the logging by adding debug, info and trace logs. 

Enhance debug, trace & info logs for remote store flows

---

.github/workflows/stalled.yml

This workflow adds in the stalled label to PRs that have had no activity for 30 days along with a comment. We no longer close the PR since there could be a possibility that contributors PRs could get closed without receiving any review. 

Add workflow to add stalled label and message

---

modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/BaseWordDelimiterTokenFilterFactoryTestCase.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/50_char_filters.yml
server/src/main/java/org/opensearch/index/analysis/Analysis.java

Support hashtag in token filter type_table rules parser
Resolves #6867

[Feature] Support hashtag in token filter type_table rules parser

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java

Fix recovery activity timeout for remote enabled indexes during peer recovery. In this PR, we update the last access time in the recovery target when the segments download is happening. This ensures that we do not cancel the peer recovery during segment download.
Resolves #10249

Update recovery target access time during segment sync for remote index

---

CHANGELOG.md
libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java
rest-api-spec/src/main/resources/rest-api-spec/test/nodes.stats/11_indices_metrics.yml
server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java
server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java
server/src/main/java/org/opensearch/index/shard/IndexingStats.java
server/src/main/java/org/opensearch/index/shard/InternalIndexingStats.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTookTests.java
server/src/test/java/org/opensearch/core/RestStatusTests.java
server/src/test/java/org/opensearch/index/shard/IndexingStatsTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

Currently, Opensearch returns a 200 OK response code for a Bulk API call, even though there can be partial/complete failures within the request E2E. Tracking these failures requires client to parse the response on their side and make sense of them. But, a general idea around trend in growth of different rest status codes at item level can provide insights on how indexing engine is performing.
Resolves #4562 
<details>
<summary>Benchmarks!</summary>
**Configuration:**
- 3 Data Nodes: r6g.4xlarge
- 3 Manager Nodes: c6g.2xlarge
- Heap: 64 GB
- Indexed 160,000,000 (160M) docs using [opensearch-benchmark](https://github.com/opensearch-project/opensearch-benchmark)
- CPU Utilization > 90% each run
|Metric	|Unit	|Task	|String Keys	|Baseline	|Short Keys	|ThreadLocalMap|AtomicLong[] …

Indexing: add Doc status counter

---

CHANGELOG.md

Fixed changelong deps since `versions.bouncycastle` uses for 3 dependencies:
- `org.bouncycastle:bcmail-jdk15to18:${versions.bouncycastle}`
- `org.bouncycastle:bcprov-jdk15to18:${versions.bouncycastle}`
- `org.bouncycastle:bcpkix-jdk15to18:${versions.bouncycastle}`
Note: https://github.com/opensearch-project/OpenSearch/pull/10232 fixed already

Fixed changelog for BC update

---

CHANGELOG.md
libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java
rest-api-spec/src/main/resources/rest-api-spec/test/nodes.stats/11_indices_metrics.yml
server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java
server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java
server/src/main/java/org/opensearch/index/shard/IndexingStats.java
server/src/main/java/org/opensearch/index/shard/InternalIndexingStats.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTookTests.java
server/src/test/java/org/opensearch/core/RestStatusTests.java
server/src/test/java/org/opensearch/index/shard/IndexingStatsTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

Backport [`d656e3d`](https://github.com/opensearch-project/OpenSearch/commit/d656e3db592f29466d35452867caa241f5429485) from #8716.

 [Backport 2.x] Indexing: add Doc status counter

---

rest-api-spec/src/main/resources/rest-api-spec/test/nodes.stats/11_indices_metrics.yml
server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
server/src/main/java/org/opensearch/index/shard/IndexingStats.java

Changing version check to 2.11. Original PR - https://github.com/opensearch-project/OpenSearch/pull/8386
Backport PR - https://github.com/opensearch-project/OpenSearch/pull/10279
Also merging this PR - https://github.com/opensearch-project/OpenSearch/pull/10271

[Search latency - Coordinator] Changing version check to 2.11

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
server/src/main/java/org/opensearch/index/query/QueryShardContext.java
server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java

Lucene introduced a new feature of joining child and parent document in knn search. https://github.com/apache/lucene/pull/12434
To utilize the feature, we need to pass parent filter to inner query so that inner query can dedupe child document per parent document.
Once this change is made, we can use the parent filter data to call appropriate query in kNN repo. https://github.com/opensearch-project/k-NN/issues/1065
N/A

Pass parent filter to inner query in nested query

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/Settings.java

There was a weird circular class-loading dependency between Settings and Settings.Builder that could result in ClassLoader deadlock if multiple threads trigger class-loading of Settings at the same time.
Resolves #10065

Fix circular dependency in Settings initialization

---

CHANGELOG.md
distribution/packages/build.gradle
distribution/packages/src/deb/lintian/opensearch
qa/os/src/test/java/org/opensearch/packaging/util/Packages.java

While working on improving OpenSearch packaging in https://github.com/opensearch-project/opensearch-build/pull/3898, we saw that some unexpected SGID bit was set on some directories and that we had to remove it to match the default packages behavior of packages on Debian.
The SGID bit can be tracked to https://github.com/rjernst/elasticsearch/commit/a5c18f15b252747bc8c62372bc8e07a36572e441 where it was added so that on first start, the opensearch service has access to the keystore initialized by the root user.  However, when deploying OpenSearch today, the keystore is created by the opensearch user and the SGID bit is not required anymore.
This PR remove the code that sets these SGID bits so that we do not need to clean them anymore when packaging.
* …

Remove spurious SGID bit on directories

---

CHANGELOG.md
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/main/java/org/opensearch/extensions/rest/RestActionsRequestHandler.java
server/src/main/java/org/opensearch/extensions/rest/RestInitializeExtensionAction.java
server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
server/src/test/java/org/opensearch/extensions/rest/RestInitializeExtensionActionTests.java
server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java

Fixes registering multiple extensions with OpenSearch.
To reproduce the issue install two extensions, using https://github.com/opensearch-project/opensearch-sdk-java and https://github.com/opensearch-project/opensearch-sdk-py samples.
```
cd ~/source/opensearch-project/OpenSearch/dblock-OpenSearch/
git diff
cd ~/source/opensearch-project/opensearch-sdk-java/dblock-opensearch-sdk-java/
./gradlew helloWorld
cat bin/main/org/opensearch/sdk/sample/helloworld/hello.json | jq
curl -s -XPOST "localhost:9200/_extensions/initialize" -H "Content-Type:application/json" --data @bin/main/org/opensearch/sdk/sample/helloworld/hello.json | jq
curl http://localhost:9200/_extensions/_hello-world-java/hello
cd ~/source/opensearch-project/opensearch-sdk-py/dblock-opensearch-sdk-py/
cat …
```

Fix: register mulitple extensions.

---

.github/workflows/lucene-snapshots.yml

Update `.github/workflows/lucene-snapshots.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=REVISION::$(git rev-parse --short HEAD)"
```
**TO-BE**
```yaml
echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
```
Resolves #10288  …

Replace deprecated command with environment file

---

.github/pull_request_template.md

Changes introduced by various PRs are often supposed to be followed with respective updates to the public documentation, maintained in https://github.com/opensearch-project/documentation-website. 
This PR updates the PR template to add a checklist item to ensure we either create a GitHub issue or PR in the documentation repo while reviewing the original code changes PR, to ensure that the public documentation updates to be done are tracked and not missed.
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …

Add TODO for updating public documentation

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/merge/MergeStats.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Backport https://github.com/opensearch-project/OpenSearch/pull/10204

[Backport-2.x] Add unreferenced file cleanup count to merge stats (#10204)

---

.github/workflows/version.yml
CHANGELOG.md

Backport of https://github.com/opensearch-project/OpenSearch/pull/10301 to `2.x`

[Backport] [2.x] Bump peter-evans/create-pull-request from 3 to 5 (#10301)

---

libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
server/src/main/java/org/opensearch/http/HttpChannel.java
server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableHttpChannel.java
server/src/main/java/org/opensearch/telemetry/tracing/handler/TraceableTransportResponseHandler.java
server/src/main/java/org/opensearch/transport/TransportResponseHandler.java

Fix the HttpChannel trace termination in case of exceptions
N/A

Fix the HttpChannel trace termination in case of exceptions

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
server/src/internalClusterTest/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandIT.java
server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/internalClusterTest/java/org/opensearch/update/UpdateIT.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/LogByteSizeMergePolicyProvider.java
server/src/main/java/org/opensearch/index/MergePolicyProvider.java
server/src/main/java/org/opensearch/index/TieredMergePolicyProvider.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/action/admin/indices/segments/IndicesSegmentsRequestTests.java
server/src/test/java/org/opensearch/index/MergePolicySettingsTests.java
server/src/test/java/org/opensearch/index/MergeSchedulerSettingsTests.java
server/src/test/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandTests.java
server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Backport https://github.com/opensearch-project/OpenSearch/pull/9992 to 2.x 

Backport - Configurable merge policy and option to choose between LogByteSize and Tiered MergePolicy (#9992)

---

server/src/main/java/org/opensearch/index/merge/MergeStats.java

Changing unrefernced file cleanup stats based MergeStats metrics version to 2.11
This change should be merged after backport PR https://github.com/opensearch-project/OpenSearch/pull/10333 is merged to the 2.x branch

Changing unrefernced file cleanup stats based MergeStats metrics version to 2.11

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainer.java
server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobContainer.java
server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
server/src/test/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainerTests.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ListenerTestUtils.java

* Add support for encrypted async blob read
* Add async blob read support for encrypted containers
---------
(cherry picked from commit c4c4ad84d995f75f8749a0f99aa8a1ecc3b71760)
Backports #10131 to `2.x`
Resolves Backport for #10131

[Backport 2.x] Add support for encrypted async blob read (#10131)

---

server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/TranslogConfig.java
server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Adding validation to identify multiple writers to same primary term and generation in remote store
Adding node id to remote segment and translog metadata files . This is to identify if we have concurrent writers to same file , causing consistency issues. 

Add node id to segment and translog metadata

---

server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java

- If we have 2 refresh flows executing concurrently (one for scheduled refresh, another as part of flush), there is a race condition where the scheduled refresh uploads the new segments, new segments_N is created with flush and the refresh that is part of flush becomes a no-op as it does not find any new segments that are not part of the reader.
- Due to this, the metadata file corresponding to commit generation on disk is not uploaded to remote store and results in `NoSuchFileException`.
- In this change, we retry on such exception. This makes sure the problem will not occur even if the same scenario explained above re-occurs. Following are the reasons.
- if the ingestion is stopped, the first refresh would be a no-op.
- if the ingestion is on-going, the second refresh would not be a …

Retry on failure to acquire lock on remote metadata

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/remote/RemoteStorePressureSettings.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java

This PR makes the change to set the value of `remote_store.segment.pressure.enabled` as true by default. There are tests around remote store backpressure already.
Resolves #10355

Enable remote segment upload backpressure by default

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java

This PR fixes the erroneous close of translog on account of upload failures. These are not really tragic events since the issue with remote store can be transient (for eg - throttling, temporary connectivity issues).  
Resolves #10358

Fix shard failure due to translog tragic close on upload failure

---

server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java

Mute DeleteSnapshotIT.testDeleteShallowCopySnapshot

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/10299 to `2.x`

[Backport] [2.x] Bump org.xerial.snappy:snappy-java from 1.1.10.4 to 1.1.10.5 in /test/fixtures/hdfs-fixture (#10299)

---

server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListener.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java

This change updates ReadContextListener to first write parts to a temp location until all parts have been received.  This ensures that partially written files do not lead to corruption.  The temp location is prefixed with a random uuid ensuring there is no collision on retries.
Resolves https://github.com/opensearch-project/OpenSearch/issues/9784

Update multipart download path to first write to temp files

---

server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListener.java
server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java

Backports ca0dae61cb1845f2a2543d051a00be946635fc83 from #10347

[Backport 2.x] Update multipart download path to first write to temp files

---

CHANGELOG.md
modules/repository-url/src/main/java/org/opensearch/repositories/url/URLRepository.java
plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepository.java
plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageRepository.java
plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsRepository.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
server/src/main/java/org/opensearch/repositories/RepositoriesService.java
server/src/main/java/org/opensearch/repositories/Repository.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/main/java/org/opensearch/repositories/blobstore/MeteredBlobStoreRepository.java
server/src/main/java/org/opensearch/repositories/fs/FsRepository.java
server/src/main/java/org/opensearch/repositories/fs/ReloadableFsRepository.java
server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
server/src/test/java/org/opensearch/repositories/fs/ReloadableFsRepositoryTests.java
server/src/test/java/org/opensearch/snapshots/mockstore/MockEventuallyConsistentRepository.java

---------
Backport #9569 to 2.x
#9118

[Backport 2.x] [Remote Store] Add support to reload repository metadata inplace (#9569)

---

server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

fix stale remote cluster uuid state not purged from remote

---

buildSrc/build.gradle

Manual backport of
https://github.com/opensearch-project/OpenSearch/pull/10205

[Backport 2.x] Bump org.apache.commons:commons-compress from 1.23.0 to 1.24.0 in /buildSrc

---

server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java

This PR fixes a race condition in datetime optimization done under PR #9567
It addresses the case where dateTimeFormatter parser list can be partially read by threads when another thread is modifying it
Resolves https://github.com/opensearch-project/OpenSearch/issues/4558

Race condition fix for datetime optimization

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java

This change fixes a bug where shards could not be recreated locally after corruption. This occured because the store was not decref'd to 0 if the commit on close would fail with a corruption exception.
This change handles failures during the commit on close and marks the store corrupt if it occurs.
This change also handles failures while fetching local metadata by wrapping them as a corruption exception - without this shards would indefinitely retry and fail replication events.  Rethrowing the exception as a corruption exception ensures the shard is properly failed and re-recovered.  For this to happen a file would have to be wiped directly from the store, but would require a node reboot to correct it.
Added some ITs that will test these corruption cases - primary sending faulty data to …

Segment Replication - Fix ShardLockObtained error during corruption cases

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

This PR reports stats for multistream downloads. With addition of copyTo() in [PR](https://github.com/opensearch-project/OpenSearch/pull/9710/files#diff-f57628264c235a133d2d6db458404e07a43f18026e40ed5e956536c03add9925) proper stats are no longer reported. This PR fixes the issue and reports proper stats.
Resolves #10283

[Remote Store] Fix stats reporting for multistream downloads.

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
server/src/main/java/org/opensearch/index/store/lockmanager/FileLockInfo.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerUtils.java
server/src/test/java/org/opensearch/index/store/lockmanager/FileLockInfoTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java

We are using URL Safe Base64UUID in most of the places in code which can have '__' as one of the characters. For Remote Store Metadata Lock files, Keeping '____' (triple underscores) as separator to separate out snapshot UUID and remote store metadata name would not work because if either the Metadata or the Snapshot UUID starts or ends will '_', we cannot use our separator to separate out the fields.
To Fix this, as part of this PR I am updating the separator to "..." for new lock files. We will still support reading older lock files  for backward compatibility, but we will do best effort by pulling out the snapshotID from the end first and then getting the md file.
Resolves #9115 …

Updating the separator for RemoteStoreLockManager since underscore is allowed in base64UUID url charset

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/store/Store.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/10370 to 2.x

[Backport 2.x] Segment Replication - Fix ShardLockObtained error during corruption cases #10370

---

.github/workflows/assemble.yml
settings.gradle

Disable build cache since Github Action runners fail with 'no space left on device'
```
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$$Lambda$587/0x000000080061fc40@2f53f4ec.
org.gradle.api.UncheckedIOException: Could not add entry ':distribution:packages:buildRpm' to cache executionHistory.bin (/home/runner/work/OpenSearch/OpenSearch/.gradle/8.3/executionHistory/executionHistory.bin).
at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:162)
at org.gradle.cache.internal.DefaultMultiProcessSafeIndexedCache.lambda$put$1(DefaultMultiProcessSafeIndexedCache.java:67)
at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:216)
at …
```

Disable build cache since Github Action runners fail with 'no space left on device'

---

CHANGELOG.md
modules/transport-netty4/src/internalClusterTest/java/org/opensearch/http/netty4/Netty4HeaderVerifierIT.java
modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/Netty4BlockingPlugin.java
modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4Plugin.java
server/src/main/java/org/opensearch/rest/RestHandler.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/10261 to 2.11.
There are differences in the netty pipeline between main and 2.x (mainly around http2). This PR updates the test to accommodate for the differences.

[Backport 2.11] Allow customization of netty channel handles before and during decompression

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java

Fix to include static settings in addition to dynamic repo metadata

Fix to include static settings in addition to dynamic repo metadata

---

buildSrc/src/main/java/org/opensearch/gradle/internal/InternalBwcGitPlugin.java
gradle/wrapper/gradle-wrapper.properties
gradlew

Update Gradle to 8.4
```
Here are the highlights of this release:
- Compiling and testing with Java 21
- Faster Java compilation on Windows
- Role focused dependency configurations creation
```
N/A

Update Gradle to 8.4

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
server/src/internalClusterTest/java/org/opensearch/search/fieldcaps/FieldCapabilitiesIT.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

Muted tests:
* DiversifiedSamplerIT.testNestedSamples
* QueryProfilePhaseTests.testMaxScore
* QueryProfilePhaseTests.testCollapseQuerySearchResults
* HighlighterSearchIT.testHighlightQueryRewriteDatesWithNow
* FieldCapabilitiesIT.testWithIndexFilter
* QueryProfilePhaseTests.testDisableTopScoreCollection
Muting these tests only for concurrent search enabled cases.
See:
- #10046
- #9932
- #10139
- https://github.com/opensearch-project/OpenSearch/issues/10434
- https://github.com/opensearch-project/OpenSearch/issues/10433
- https://github.com/opensearch-project/OpenSearch/issues/10469
Haven't seen any reported failures for https://github.com/opensearch-project/OpenSearch/issues/9401 or https://github.com/opensearch-project/OpenSearch/issues/9464 for a while now so leaving those unmuted. …

Mute flaky concurrent segment search tests pending fixes

---

server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

Using hash of node id in remote segment and translog metadata file names
Resolves #10450 

[Remote Store] Using hash of node id in metadata file names

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java

This fixes #10459 
Resolves #10459

Fix flaky testRemoteRefreshRetryOnFailure in RemoteStoreRefreshListenerIT

---

server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

This fixes #10489
Resolves #10489

Fix failing testGetPrimaryTermAndGeneration in TranslogTransferManagerTests

---

server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

- Backports https://github.com/opensearch-project/OpenSearch/commit/98defa595cc83369fa863d50057d518133b81540 from https://github.com/opensearch-project/OpenSearch/pull/10480.
- Backports https://github.com/opensearch-project/OpenSearch/commit/22ddcf19c7a0ceb8998cdc6344ba132b547cef1c from https://github.com/opensearch-project/OpenSearch/pull/10490

[Backport 2.x] [Remote Store] Using hash of node id in metadata file names

---

server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureAndResiliencyIT.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

This PR fixes 2 issues which are causing red indexes while I performed stress testing -
1. https://github.com/opensearch-project/OpenSearch/issues/10400
2. https://github.com/opensearch-project/OpenSearch/issues/10398
Resolves #10398, #10400.

Fix bugs causing red indexes with remote indexes during translog upload & store recovery

---

server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

- Backports https://github.com/opensearch-project/OpenSearch/commit/98defa595cc83369fa863d50057d518133b81540 from https://github.com/opensearch-project/OpenSearch/pull/10480.
- Backports https://github.com/opensearch-project/OpenSearch/commit/22ddcf19c7a0ceb8998cdc6344ba132b547cef1c from https://github.com/opensearch-project/OpenSearch/pull/10490

[Backport 2.11] [Remote Store] Using hash of node id in metadata file names

---

server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java

Avoid size=0 test flakiness for terminate_after tests: https://github.com/opensearch-project/OpenSearch/issues/9946
Need to do a deeper dive of the underlying issue, tracking that in https://github.com/opensearch-project/OpenSearch/issues/10435
Ran this test locally 1500 times and saw no failures.
Resolves #9946 

Avoid size=0 for terminate_after tests

---

server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java

This was a bad use of randomization. The test is super fast so it can be run against every scaling thread pool every time.

Fix ScalingThreadPoolTest to handle new pool

---

CHANGELOG.md
server/src/test/java/org/opensearch/action/ingest/SimulatePipelineRequestParsingTests.java

The two methods `testParseUsingPipelineStore` and `innerTestParseWithProvidedPipeline` in SimulatePipelineRequestParsingTests never run, that's because `testParseUsingPipelineStore` has unused input parameter and `innerTestParseWithProvidedPipeline` doesn't start with `test`,  this PR fix the bug and fix the test failure when running `innerTestParseWithProvidedPipeline`.
https://github.com/opensearch-project/OpenSearch/issues/10493

Fix some test methods in SimulatePipelineRequestParsingTests never run and fix test failure

---

CHANGELOG.md
server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
server/src/main/java/org/opensearch/search/backpressure/stats/SearchShardTaskStats.java
server/src/main/java/org/opensearch/search/backpressure/stats/SearchTaskStats.java
server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
server/src/test/java/org/opensearch/search/backpressure/stats/SearchShardTaskStatsTests.java
server/src/test/java/org/opensearch/search/backpressure/stats/SearchTaskStatsTests.java

With this change the nodeStats API will also return the completionCount of search tasks at shard and coordinator level. Opening this separate PR due to DCO issue in a past commit.
Closed PR : https://github.com/opensearch-project/OpenSearch/pull/8701.
new sample response for an API call like ` curl "localhost:9200/_nodes/stats/search_backpressure?pretty"` will look like the following
```
{
"_nodes" : {
"total" : 1,
"successful" : 1,
"failed" : 0
},
"cluster_name" : "runTask",
"nodes" : {
"dPpgbce2STSxlvH7LDaGiA" : {
"timestamp" : 1693433903192,
"name" : "runTask-0",
"transport_address" : "127.0.0.1:9300",
"host" : "127.0.0.1",
"ip" : "127.0.0.1:9300",
"roles" : [
"cluster_manager",
"data",
"ingest",
"remote_cluster_client"
],
"attributes" : {
"testattr" : "test", …
```

add taskCompletionCount in search_backpressure stats

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backports #9822 via commit 0c4e95095e4d44540ea8a90aa5ca55fea1248366
Manual backport was required due to conflicts in CHANGELOG

[Backport 2.x] Bumps jetty version to 9.4.52.v20230823 to fix GMS-2023-1857 (#9822)

---

server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/test/java/org/opensearch/index/IndexModuleTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteStoreFileDownloaderTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

There are a few open issues with the multi-stream download approach:
- Recovery stats are not being reported correctly
- It is incompatible (short of reopening and re-reading the entire file) with the existing Lucene checksum validation logic
- There are some issues with integrating it with the pending client side encryption work
Given this, I attempted an experiment where I replaced with multi-stream-within-a-single-file approach with simply parallelizing downloads across files (this is how snapshot restore works). I actually got better results with this approach: recovering a ~52GiB shard took about 4.7 minutes with the multi-stream code versus 3.9 minutes with the parallel file approach (r7g.4xlarge EC2 instance, 500MiB/s EBS volume, S3 as remote repository).
I think this is the right …

Replace multipart download with parallel file download

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java

Make bulk delete size configurable
Resolves #10451

[S3 Repository] Make bulk delete size configurable

---

CHANGELOG.md
modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpChannel.java
modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/Netty4TcpChannel.java
server/src/main/java/org/opensearch/http/HttpChannel.java
server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableHttpChannel.java
server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableTcpTransportChannel.java
server/src/main/java/org/opensearch/transport/TaskTransportChannel.java
server/src/main/java/org/opensearch/transport/TcpChannel.java
server/src/main/java/org/opensearch/transport/TcpTransportChannel.java
server/src/main/java/org/opensearch/transport/TransportChannel.java

While instrumenting the transports (both TCP and HTTP), we found out that `security` plugin heavily depends on `netty` transport (in fact, it does not support anything else) but it is excessive typecasting the different transport object to their `Netty4Xxx` equivalents for accessing handlers and attributes. It significantly complicates any instrumentation efforts and needs general mechanism to access contextual information without typecasting.
Related to https://github.com/opensearch-project/security/issues/3515 …

Add the means to extract the contextual properties from HttpChannel, TcpChannel and TrasportChannel without excessive typecasting

---

server/src/main/java/org/opensearch/index/IndexModule.java
server/src/main/java/org/opensearch/index/IndexService.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
server/src/test/java/org/opensearch/index/IndexModuleTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
server/src/test/java/org/opensearch/index/store/RemoteStoreFileDownloaderTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

Backport 00ccfc49f3aa2bf06ddc22ff8f0bc24790b222da from #10519.

[Backport 2.11] Replace multipart download with parallel file download

---

libs/core/src/main/java/org/opensearch/Version.java

Update OpenSearch 2.12 to use Apache Lucene 9.8.0
N/A

Update OpenSearch 2.12 to use Apache Lucene 9.8.0

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureAndResiliencyIT.java
server/src/main/java/org/opensearch/index/engine/Engine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/TranslogManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/main/java/org/opensearch/index/translog/transfer/TranslogUploadFailedException.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/90c4297266495de41c3b09728ce82d1a9aec1d64 from https://github.com/opensearch-project/OpenSearch/pull/10513.

[Backport 2.x] Fix shard failure on flush during upload failures for remote indexes

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRepositoryRegistrationIT.java
server/src/main/java/org/opensearch/action/admin/cluster/repositories/get/GetRepositoriesResponse.java
server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java

- system_repository setting value was removed during toXContent call of RepositoriesMetadata
- This was done to remove this setting from GetRepositoies API call
- But toXContent also serializes data for persistent local disk state. 
- So during cluster state recovery from local disk, this system_repository setting was lost.
- This change ensures system_respository setting is persisted in local disk state
Resolves https://github.com/opensearch-project/OpenSearch/issues/10555 …

Fix system_repository setting is restored after cluster metadata recovery from local disk

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.11.0.md

- Updated CHANGELOG.md
- `Bump org.apache.commons:commons-compress from 1.22 to 1.23.0` had been released in 2.8 https://github.com/opensearch-project/OpenSearch/blob/main/release-notes/opensearch.release-notes-2.8.0.md?plain=1#L46
- `Bump netty from 4.1.99.Final to 4.1.100.Final (#10564)` is released in 2.11
- Added other changes from CHANGELOG.md to the new 2.11 release notes

Add release notes for 2.11

---

CHANGELOG.md
release-notes/opensearch.release-notes-2.11.0.md

Signed-off-by: Louis Chu <clingzhi@amazon.com>
(cherry picked from commit 382eb301b21bf5c6eda613432b9ddccda1c414b9)
- Manual backport https://github.com/opensearch-project/OpenSearch/pull/10594

[Manual Backport 2.11] Add release notes for 2.11 (#10594)

---

server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java

I was looking through some cluster settings, stumbled across the search back-pressure settings, saw they were deprecated, and the Javadoc alluded to some myserious new settings.
I'm adding links to the class with the new settings to help future developers.
N/A

Point deprecated settings to the new location.

---

release-notes/opensearch.release-notes-2.11.0.md

Remove unrelease commits in 2.11
https://github.com/opensearch-project/OpenSearch/pull/10594#issuecomment-1760455201

Remove unrelease commits in 2.11

---

CHANGELOG.md
modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/90_simulate.yml
server/src/main/java/org/opensearch/action/ingest/SimulatePipelineRequest.java
server/src/test/java/org/opensearch/action/ingest/SimulatePipelineRequestParsingTests.java

Backport https://github.com/opensearch-project/OpenSearch/pull/10101.
https://github.com/opensearch-project/OpenSearch/issues/10097

[Backport 2.x] Fix class_cast_exception when passing int to _version and other metadata fields in ingest simulate API

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java
server/src/main/java/org/opensearch/action/search/SearchRequest.java
server/src/main/java/org/opensearch/action/search/SearchResponse.java
server/src/main/java/org/opensearch/action/search/SearchResponseMerger.java
server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java
server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
server/src/test/java/org/opensearch/action/search/SearchResponseTests.java
server/src/test/java/org/opensearch/action/search/SearchTimeProviderTests.java
test/framework/src/main/java/org/opensearch/search/RandomSearchRequestGenerator.java

Per Request level tracking: Introduce a new field (phase_took) in search response which will give more insights/visibility into overall time taken by different search phases(query/fetch/canMatch etc) to the clients. This is tracked from the coordinator node, not shards.
Sample search response with phase_took field enabled:
```
% curl -XGET 'localhost:9200/_search?pretty&phase_took' -H 'Content-Type: application/json' -d'
{                                                
"query": { "query_string": { "query": "value1" } }
}'
{
"took" : 3439,
"phase_took" : {
"dfs_pre_query" : 0,
"query" : 69,
"fetch" : 22,
"dfs_query" : 0,
"expand" : 0,
"can_match" : 0
},
"timed_out" : false,
"_shards" : {
"total" : 10,
"successful" : 10,
"skipped" : 0,
"failed" : 0
},
"hits" : {
"total" : {
"value" : 1, …
```

Request level latency tracking

---

server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

This test was incorrectly hardcoding a segment to delete to force corruption. If a merge occurs randomly before segments are copied the expected segment did not exist failing the test. This will now look for any .si and delete it.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10616

Fix broken test testCommitOnCloseThrowsException_decRefStore

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

Backport https://github.com/opensearch-project/OpenSearch/pull/10524 to 2.x
https://github.com/opensearch-project/OpenSearch/issues/10501

[Remote Store] Add Remote Store backpressure rejection stats to _nodes/stats (#10524)

---

CHANGELOG.md
plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageService.java
plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/SocketAccess.java

Fix java.lang.SecurityException in repository-gcs plugin
Closes #10509 

[BUG] Fix java.lang.SecurityException in repository-gcs plugin

---

server/src/test/java/org/opensearch/action/search/SearchRequestTests.java

Fix for flaky `SearchRequestTests.testEqualsAndHashcode`
Resolves https://github.com/opensearch-project/OpenSearch/issues/10643

Fix flaky testEqualsAndHashcode in SearchRequestTests

---

server/src/test/java/org/opensearch/action/ingest/SimulatePipelineRequestParsingTests.java

Backport #10496 to 2.x branch.
https://github.com/opensearch-project/OpenSearch/issues/10493

[Backport 2.x] Fix some test methods in SimulatePipelineRequestParsingTests never run and fix test failure

---

server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java

This test is flaky in two ways, one it may hit a case where a merge occurs and the hardcoded segment does not exist to delete similar to https://github.com/opensearch-project/OpenSearch/pull/10621. Two with certain mock filesystems a corruption exception won't be thrown here, only a NoSuchFile - This doesn't change our handling in the engine, but the test should conditionally handle if the store is marked corrupted on close.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10616
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTI …

Fix flaky test testFlushThrowsFlushFailedExceptionOnCorruption.

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

- Updates and revives exiting integ tests for remote cluster state auto restore
Resolves https://github.com/opensearch-project/OpenSearch/issues/9834

revive remote cluster state auto restore integ tests

---

server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

This PR unmutes Test `SegmentReplicationTargetServiceTests.testShardAlreadyReplicating`
Resolves #8928 

[Segment Replication] Unmute Test SegmentReplicationTargetServiceTests.testShardAlreadyReplicating

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java

In S3 SDK v2, if stream supplied by the caller doesn't support mark and reset then in case of IO errors, entire upload fails instead of just retrying the buffer. This change wraps the provided stream with BufferedInputStream to always allow mark and reset for efficient uploads.

Added BufferedInputStream to allow mark and reset ops during IO errors

---

CHANGELOG.md
server/src/main/java/org/opensearch/identity/tokens/AuthToken.java
server/src/main/java/org/opensearch/identity/tokens/OnBehalfOfClaims.java

This change swaps the OnBehalfOf claims provider in core in order to work with external token providers. Without this change, implementing the TokenManager class is not straightforward. We would force users to to provide an expiration _time_ (i.e. system time) when we want them to be able to provide a value in seconds and do the math for them. 

OnBehalfOf claims take second duration

---

CHANGELOG.md
server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/monitor/fs/DeviceStatsTests.java
server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java

Backport of FS stats PR - https://github.com/opensearch-project/OpenSearch/pull/10541
https://github.com/opensearch-project/OpenSearch/issues/8910

[Backport 2.x] Enhancing FS stats to include read / write time, io time and queue size

---

server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
test/framework/src/main/java/org/opensearch/index/replication/TestReplicationSource.java
test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java

- Fixes progress tracking for segment replication 
- `_cat/segment_replication` returns the replica results when the replication event completes successfully which is recorded  here - https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java#L520-L522
- This change ensures that the downloads are tracked and record the completed events correctly. 
Resolves #10515 

Fix download reporting for segment replication

---

CHANGELOG.md
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

This PR includes backporting of below PR:
* Change filenames for IndexMetadata and Manifest: [ Original PR:  #10557 ]
Changes done during backporting:
* Resolved conflicts of change log.

[Backport 2.x] Change filenames for IndexMetadata and Manifest [#10557]

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/node/Node.java
server/src/main/java/org/opensearch/node/NodeResourceUsageStats.java
server/src/main/java/org/opensearch/node/NodeService.java
server/src/main/java/org/opensearch/node/NodesResourceUsageStats.java
server/src/main/java/org/opensearch/node/ResourceUsageCollectorService.java
server/src/main/java/org/opensearch/node/resource/tracker/AbstractAverageUsageTracker.java
server/src/main/java/org/opensearch/node/resource/tracker/AverageCpuUsageTracker.java
server/src/main/java/org/opensearch/node/resource/tracker/AverageMemoryUsageTracker.java
server/src/main/java/org/opensearch/node/resource/tracker/NodeResourceUsageTracker.java
server/src/main/java/org/opensearch/node/resource/tracker/ResourceTrackerSettings.java
server/src/main/java/org/opensearch/node/resource/tracker/package-info.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
server/src/test/java/org/opensearch/node/ResourceUsageCollectorServiceTests.java
server/src/test/java/org/opensearch/node/resource/tracker/AverageUsageTrackerTests.java
server/src/test/java/org/opensearch/node/resource/tracker/NodeResourceUsageTrackerTests.java
test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/9890 which adds 'ResourceUsageTrackers' and 'ResourceUsageCollectorService'
https://github.com/opensearch-project/OpenSearch/issues/8910

[Backport 2.x] Add resource usage trackers and resource usage collector service

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java

Resolves https://github.com/opensearch-project/OpenSearch/issues/10525

Remote Restore Cluster Metadata if local disk state lost after quorum loss recovery

---

server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/monitor/fs/FsInfo.java

Version fix for `node/_stats` fields due to backport of 
https://github.com/opensearch-project/OpenSearch/pull/10695
https://github.com/opensearch-project/OpenSearch/pull/10695

Version fixes for Resource Usage Stats and FS Stats

---

.github/CODEOWNERS

Then I copy/pasted the sorted list back into the file.
Add @abbashus and @adnapibar back to CODEOWNERS, since they are in MAINTAINERS.
Also, I sorted CODEOWNERS alphabetically, with:
```
cat CODEOWNERS | tr ' ' '\n' | sort
```
Then I copy/pasted the sorted list back into the file.
Resolves #9534 

Add @abbashus and @adnapibar back to CODEOWNERS

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java

Adding close on buffered stream in s3 async upload for early cleanup of resources.

Closing buffered stream in s3

---

server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java

Need to merge post merging https://github.com/opensearch-project/OpenSearch/pull/10715 
Changing version for repo stats blob  as 2.x will now understand this blob. 

Changing version for repo stats blob post backport to 2.x

---

server/src/main/java/org/opensearch/search/DocValueFormat.java

Performance Improvement for Datetime formats (update version checks to 2.12.0)
https://github.com/opensearch-project/OpenSearch/pull/10448

Performance Improvement for Datetime formats (update version checks to 2.12.0)

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This bug was found from analyzing flakiness of existing ITs using remote store where replicas would not be caught up with the primary.  Retries within RemoteStoreRefreshListener run outside of the refresh thread.  This means that concurrent refreshes may occur during syncSegments execution that update the on-reader SegmentInfos.  A shard's latest ReplicationCheckpoint is computed and set in a refresh listener, but it is not guaranteed the listener has run before the retry fetches the infos or checkpoint independently. This fix ensures the listener recomputes the checkpoint while fetching the SegmentInfos but only if necessary.
I believe this is the fix for all SegmentReplicationUsingRemoteStore IT flakies where replica count is not high enough.
Resolves …

Fix bug where retries within RemoteStoreRefreshListener cause infos/checkpoint mismatch

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
server/src/test/java/org/opensearch/index/store/RemoteStoreFileDownloaderTests.java
test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java

This change makes Make RemoteStoreReplicationSource#getSegmentFiles asynchronous.
It also ensures that SegmentReplicationTargets are properly closed during cancellation with remote store enabled if the cancel is issued during a file download.
Resolves https://github.com/opensearch-project/OpenSearch/issues/8089
Resolves https://github.com/opensearch-project/OpenSearch/issues/10619

Make RemoteStoreReplicationSource#getSegmentFiles asynchronous

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java

Backports 
https://github.com/opensearch-project/OpenSearch/pull/10710
https://github.com/opensearch-project/OpenSearch/pull/10690 

[Backport 2.x] Added BufferedInputStream to allow mark and reset ops during IO errors #10690 

---

server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

Fix flaky test `testGlobalMetadataOnlyUpdated` in RemoteClusterStateServiceTests.
Ran 2000 iteration of the tests after fix, it is passing every time.
```
./gradlew ':server:test' --tests "org.opensearch.gateway.remote.RemoteClusterStateServiceTests.testGlobalMetadataOnlyUpdated" -Dtests.iters=2000
```
#10743 

Fix flaky remote cluster state UT

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/Translog.java
server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java

This PR solves Peer Recovery failure that can happen due to receive timeout exceptions during prepare translog phase of peer recovery. This type of failure can be prominent in zero replica remote store backed indexes. However this can also happen during slow remote interactions. This PR fixes the problem handles both kind of issues.
This PR handles the following cases - 
- Removes searchIdle support for remote enabled indexes. This means that we continue to refresh and upload segments periodically at the configured refresh interval.
- Fixes the bug where actual translog retention was higher than the translog flush threshold size. 
- Makes the transport timeout configurable for prepare translog phase in peer recovery. This is now controlled through the …

[Remote Store] Fix relocation failure due to transport receive timeout

---

.github/pull_request_template.md
CONTRIBUTING.md

Update Github pull request template to have a task for inspecting failing checks. Since we have not got the consensus on https://github.com/opensearch-project/OpenSearch/issues/10371, and this issue does not only persist but gets worst with mostly every new feature integrated, there is an alternative path to tackle the problem making it a part of the process. 
The idea is to at least ask every contributor to inspect the failing checks (we are talking about Gradle checks primarily) and make a reference (by commenting) to:
- an existing known issue
- or, create and attach a new issue 
It won't solve the problem of flaky tests going away but at least we may get attention (hopefully engaging more engineers into fixing flaky tests) and we should at least spot a new flaky tests proactively …

Update Github pull request template to have a task for inspecting failing checks

---

server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java

The remote recovery thread pool does blocking I/O when downloading files, so the "half processor count max 10" was definitely too small. This can be shown by triggering recoveries on a node that is also doing segment replication, and the replication lag will increase due to contention on that thread pool. Some amount of contention is inevitable, but the change here to increase the download thread pool, and also limit the concurrent usage of that thread pool by any single recovery/replication to 25% of the threads does help.
Long term, we can improve this even further by moving to fully async I/O to avoid blocking threads in the application on draining InputStreams.
For more …

Increase remote recovery thread pool size

---

server/src/main/java/org/opensearch/index/ReplicationStats.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java

This change does 2 things: 
1. Returns segment replication stats metrics in an unformatted raw format unless requested in a human readable format (query parameter of human=true) 
2. The replication lag metric being returned `MAX_REPLICATION_LAG` now takes into account the total replication lag i.e., it now includes the time taken to upload data to the remote store. 
Resolves #10666
Resolves #10722 

Return unformatted Segment Replication metrics that take upload time into account for replication lag

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureAndResiliencyIT.java
server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java

For remote store, we track refresh lag in node stats api and it is as well used for remote segments upload backpressure. Until now, we were using the time difference of the most recent successful remote upload and local refresh. This conveys the lag in terms of freshness of data. While it works for cases where the refresh interval is default and low, it shows huge spikes when the user has configured refresh interval of -1 and the flushes are governed by the translog flush size breach. In this PR, we make the change to determine lag by only comparing the time when the local refresh succeeded versus the time elapsed since the refresh until remote upload finishes. This simplifies the mental model of perceiving the lag as it would always grow gradually from 0 to a higher number in contrast to …

[Remote Store] Use time elapsed since last successful local refresh for refresh lag

---

server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java

Remove remote store attributes from discovery node toString method to reduce the noise in logs. With this change, it will not log the remote store attributes when it logs the node's information.
**Log before fix:**
`
[2023-10-21T11:59:37,563][INFO ][o.o.c.s.MasterService    ] [a483e760c3eb.ant.amazon.com] elected-as-cluster-manager ([1] nodes joined)[{a483e760c3eb.ant.amazon.com}{h32zPMOiSdi2-bPknzppAg}{-TZ4rc9URAqRxMMrQ7urhQ}{127.0.0.1}{127.0.0.1:9300}{dimr}{remote_store.repository.my-repo-1.settings.region=XXXXX, remote_store.repository.my-repo-1.settings.bucket=XXXXXX, remote_store.repository.my-repo-1.type=XXXX, remote_store.state.repository=my-repo-1, remote_store.repository.my-repo-1.settings.base_path=XXXXX, shard_indexing_pressure_enabled=true, …

Remove remote store attributes from DiscoveryNode toString()

---

server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

Backport flaky test fix to 2.x: https://github.com/opensearch-project/OpenSearch/pull/10780

[Backport 2.x] Fix flaky remote cluster state UT

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java

Fix custom metadata not getting stored for remote store not supporting async write.
#10691 
#10697 

Fix custom metadata not getting stored for remote store not supporting async write

---

server/src/main/java/org/opensearch/gateway/GatewayMetaState.java

Removed the catch statement which will never be invoked, as with remote store the remote state repository is registered at the time of bootstrap.
No tracking issue for this

Removed unnecessary catch statement

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java

- Immediately after remote state restore, we write restored state to disk with UNKNOWN_UUID cluster uuid. 
- This leads to issues if process restarts before committing newly generated state with valid uuid to disk
- Now, If restart happens before performing a new write to disk with valid cluster uuid, the auto restore fails with conflicting states in remote and local disk. 
- Please find more details in the linked issue
Resolves https://github.com/opensearch-project/OpenSearch/issues/10776
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md …

Override local disk state if we are able to restore from remote

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java

- Fixes failing test on main - org.opensearch.remotestore.RemoteStoreClusterStateRestoreIT#testFullClusterRestoreDoesntFailWithConflictingLocalState
NA

fix integ test: check for red indices and then manually restore to green

---

server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
server/src/main/java/org/opensearch/index/SegmentReplicationRejectionStats.java

This PR updates version check for segment replication backpressure rejection stats made in #10656 .
This PR should only be merged after #10834 is merged.
Resolves #10501 

[Segment Replication] Update version check for segment replication backpressure rejection stats

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/index/remote/RemoteTranslogTransferTracker.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

With this PR, we are doing following changes -
1. On replica promotion, we update the segments tracker with remote uploaded files on `remoteDirectory.init()` method invocation in `runAfterRefreshExactlyOnce(..)`. This ensures that we do not see spikes in refresh lag bytes on failovers.
2. There is a case during failover where the  `runAfterRefreshExactlyOnce` gets executed, but the `syncSegments` does not. This happens due to the `this.primaryTerm != indexShard.getOperationPrimaryTerm()` evaluating true for the first time, but evaluating to false on the second time.
Resolves #10821, #10831 …

[Remote Store] Sync segments in refresh listener on refresh after commit

---

server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
server/src/main/java/org/opensearch/index/IndexSettings.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java

Even after https://github.com/opensearch-project/OpenSearch/issues/9191 , we are seeing recovery failures on primary relocations. 
This is due to the fact that older primary is continuously uploading and deleting from remote translog. So it can happen that even with retries , newer primary is not able to complete the download of all the files. 
This PR adds some buffer before deleting the files from remote translog .  …

[Remote Store] Add extra buffer before deleting older generations of translog

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

- Make remote store index and global metadata upload timeout dynamic
- Adds 2 new dynamically configurable settings, with default value 20s:
- `cluster.remote_store.index_metadata.upload_timeout`
- `cluster.remote_store.global_metadata.upload_timeout`
Resolves #10688 

Make index and global metadata upload timeout dynamic cluster settings

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/Store.java

- This reverts commit 6c022612769e6bc7ed18b9ec0888d6cd0dd415cc.
- The change has significant impact on the performance in the download segment flow.
- For now, relying on configured remote store's in-built checksum validation. 
- We will re-visit this once we have better idea on perf and potential optimizations.

Revert "Validate checksum of each segment file post download from remote store (#10119)"

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

Backport PR of #10814 
Resolves https://github.com/opensearch-project/OpenSearch/issues/10688

[Backport 2.x] Make index and global metadata upload timeout dynamic cluster setting

---

server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java

Backport PR is merged in 2.x branch with 2.12 version check. Updating it in main as well.
Backport PR: https://github.com/opensearch-project/OpenSearch/pull/10711

Changing version check to 2.12 for remote cluster state

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/indices/IndicesService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

* Add cluster setting CLUSTER_RESTRICT_INDEX_REPLICATION_TYPE_SETTING to restrict setting of index setting replication type
* Add Changelog entry
* refactoring
---------
Backport #10866 to 2.x

Add cluster setting cluster.restrict.index.replication_type t… (#10866)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

- Currently, we don't guarantee translog sync to remote on primary mode activation.
- This creates issue in flows similar to one listed below:
- Index some data with 0 replica
- wait for snapshot to be created
- delete index
- restore from snapshot - wait for index to turn green
- terminate instance
- _remote/restore the index — Fails.. shards are not getting assigned. — recovery is failing with exception: `java.nio.file.NoSuchFileException: <index path>/4/translog/translog.ckp`
- In this change, we make sure to always sync translog on primary activation. …

Sync translog to remote on primary activate

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
server/src/test/java/org/opensearch/index/OpenSearchTieredMergePolicyTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/10036
There are latency-sensitive users for whom the default 20% allowable accumulation of deletes is too high, so they force merge with "only_expunge_deletes".
Unfortunately, this has ignored the max segment size, so despite the word "only" in there, they get the terrible side-effect of producing segments larger than the max segment size. These oversized segments are unlikely to participate in future merges, until they have so many deletes that they could drop back below the max segment size, likely making the whole "too many deletes" problem even worse.
This commit fixes that so that "only_expunge_deletes" ONLY EXPUNGES DELETES without creating oversized segments.
N/A
By submitting this pull request, I confirm that …

[Backport 2.x] Honor max segment size during only_expunge_deletes

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

Backports https://github.com/opensearch-project/OpenSearch/commit/6f36752d9e84e95ce2280347cc26b0c9138b2d57 from https://github.com/opensearch-project/OpenSearch/pull/10839

Sync translog to remote on primary activate (#10839)

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/Store.java

- This reverts commit https://github.com/opensearch-project/OpenSearch/commit/6c022612769e6bc7ed18b9ec0888d6cd0dd415cc.
- The change has significant impact on the performance in the download segment flow.
- For now, relying on configured remote store's in-built checksum validation.
- We will re-visit this once we have better idea on perf and potential optimizations.

Revert "Validate checksum of each segment file post download from remote store (#10119) (#10590)"

---

server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java

Cluster chaining can break if there is consecutive node replace and restart
This change removes the check for `clusterUUIDCommitted` for current state when fetch previousClusterUUID from remote. But since we already have a check on `clusterUUIDCommitted` while constructing cluster chain, we should be good
https://github.com/opensearch-project/OpenSearch/blob/ef4b327ab48a6a674b657049e440418fe427cb0c/server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java#L829-L833
** It might be beneficial to make previousClusterUUID part of `Metadata` itself in future **
Resolves https://github.com/opensearch-project/OpenSearch/issues/10841 …

link previous cluster uuid to current cluster uuid even if current cluster uuid is not committed

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
test/framework/src/main/java/org/opensearch/test/CorruptionUtils.java

- While downloading segments from remote segment store, if the process stops abruptly, leaving incomplete segment files on local, starting the same process again fails the recovery with `FileAlreadyExistsException`
- In this change, we delete the partially downloaded file so that it can re-downloaded from the remote store.

Delete corrupted file to re-download from remote store

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationDisruptionIT.java
server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

This test is failing with WindowsFS.
This change moves SegRep corruption tests to a separate IT class and skips running on WindowsFS.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10542
Resolves https://github.com/opensearch-project/OpenSearch/issues/10709

Fix flaky test testSendCorruptBytesToReplica

---

server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java

Move the assertion to more deterministic test where cluster state update will happen for sure. Executed the test 1000 time locally in a loop to verify it's not going to be flaky anymore.
Resolves #10899 
~- [x] New functionality has been documented.~
~- [x] New functionality has javadoc added~
~- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~

Fix flaky testClusterStateBatchedUpdates test

---

server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardCorruptionTests.java

This test is breaking for WindowsFS only. Moving it to a separate file where it is skipped on WindowsFS.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10927

Fix flaky test IndexShardTests.testLocalDirectoryContains

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java

There is a bug in RemoteStoreRefreshListener class which is occurring on primary term change when a retry is happening. This is more prominent during index creation and failover.
Resolves #10917

[Remote Store] Fix refresh lag bug on primary term change

---

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java

This change avoid replication failures in event of exception when reading the local file not currently referenced by reader. This is useful and cover scenarios where reading the on-disk results in IOException due to file corruption or partial writes. 
Without change, the added unit test depicts replication event failure.
```
[2023-10-25T20:37:43,197][ERROR][o.o.i.s.RemoteIndexShardTests] [org.opensearch.index.shard.RemoteIndexShardTests] Unexpected replication failure in test
org.opensearch.indices.replication.common.ReplicationFailedException: Segment Replication failed
at org.opensearch.indices.replication.SegmentReplicationTargetService$3.onFailure(SegmentReplicationTargetService.java:532) [main/:?]
at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90) …
```

[Segment Replication] Handle exceptions on local file read during replication

---

server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java

If there are connectivity issues with the configured remote store (or degraded remote store uploads) resulting in translog uploads taking longer than 30s, it leads in TimeoutException being thrown. This exception is later tried to be casted to RuntimeException which leads to ClassCastException which ultimately fails the shard.
Resolves #10924
~- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
~- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ …

[Remote Store] Fix shard failure on flush due to upload timeout

---

server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java

Improved logging around remote cluster state service. Added info/debug logs.

Improved logging around remote cluster state

---

server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

When the condition that cluster UUID should be committed and it should be not be pointed to by any cluster UUIDs are applied simultaneously, it might skip all the cluster UUIDs. This can happen in case the last cluster UUID in a chain was uncommitted like below:
```
UUID1(committed) -> NA
UUID2(committed) -> UUID1(committed)
UUID3(uncommitted) -> UUID2(committed
```
So we need to first apply the condition of cluster UUID should be committed then reconstruct the graph and then apply the condition of clusterUUID not being pointed to by any cluster UUID.
#10911  …

Fix valid cluster UUID logic for uncommitted cluster UUIDs

---

server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java

`testSegRepSucceedsOnPreviousCopiedFiles` and `testNoFailuresOnFileReads` have been found to be flaky in recent gradle check runs, resulting in failures. As part of this PR, muting these two tests until it is fixed. Both tests have similar code flow structure, hence using same tracking issue.
Related https://github.com/opensearch-project/OpenSearch/issues/10885

Mute testSegRepSucceedsOnPreviousCopiedFiles and testNoFailuresOnFileReads unit tests

---

server/src/main/java/org/opensearch/index/shard/IndexShard.java

Adds a log for duration of failover time that will help in debugging issues. 
Resolves #10951 

[Segment Replication] Add log for failover time 

---

server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Resolves https://github.com/opensearch-project/OpenSearch/issues/10739 and https://github.com/opensearch-project/OpenSearch/issues/9891
https://github.com/opensearch-project/OpenSearch/issues/10739
https://github.com/opensearch-project/OpenSearch/issues/9891

Fix unreferenced file cleanup flaky tests

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
server/src/main/java/org/opensearch/action/resync/TransportResyncReplicationAction.java
server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
server/src/main/java/org/opensearch/index/seqno/RetentionLeaseSyncAction.java
server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTests.java
server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTookTests.java
server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionForIndexingPressureTests.java
server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java
server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

Auto-backport for [this](https://github.com/opensearch-project/OpenSearch/pull/10273) PR failed.
Manually raising a PR to backport changes to 2.x

[Backport 2.x] Add tracing instrumentation for indexing paths

---

server/src/main/java/org/opensearch/action/search/SearchQueryCategorizer.java

We want to prevent flooding the logs hence changing the log level to trace for query shape
Changes are part of the search query categorization feature.

Change log level to trace for query shape

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
test/framework/src/main/java/org/opensearch/test/ParameterizedOpenSearchIntegTestCase.java

This is to make sure that the index random function which is used in multiple classes has creation of multiple segments to test the concurrent search code path. Without this change there are 848 IT tests that are running with slice count<=1.
With this change the number of tests having slice<=1 is down to 325. This pr can also be used to add index random in the other tests not running with the higher slice count. e.g. https://github.com/opensearch-project/OpenSearch/commit/6157d4e0065121789a70d40c44349c3f331d262b
Resolves #10310 …

Update the indexRandom function to create more segments

---

server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java

_nodes/stats is failing due to recently added cluster state stats. This PR fixes that issue by writing **statsName** field on the stream and reads from it to properly create the PersistedStateStats object. 
Resolves #10961 
~- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~

Add statsName field on stream while constructing PersistedStateStats

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

- During QL remote state restore we do not restore previous cluster state version
- With this change, we intent to restore the cluster state version back.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10692

Restore ClusterState version during remote state restore

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

* Restore ClusterState version during remote state restore
Signed-off-by: bansvaru <bansvaru@amazon.com>
(cherry picked from commit 73bbeb57a8a56de0d1f9cf69e711a8a0ff26afe5)
Backport of https://github.com/opensearch-project/OpenSearch/pull/10853
NA

[Backport 2.x] Restore ClusterState version during remote state restore (#10853)

---

server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java

Use async write for Manifest file.
Use latch for maintaining timeout for file transfer of manifest file.

Use async write for manifest file and use latch for timeout

---

server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java

- Currently, shallow copy snapshot (which references data in remote store) takes a lock on remote store metadata file based on primary term and generation.
- But as we upload a metadata file each refresh, there are multiple files that get created for the same primary term and generation.
- Following is the example that creates issues in the snapshot flow:
- Snapshot triggers flush, generation is increased to 4 and snapshot has taken lock on primary term and generation 4. Assume metadata file name was `md_1_4_1`
- As indexing proceeded, multiple metadata files are uploaded for the same primary term and generation. Let's say last file uploaded was `md_1_4_24`.
- While restoring snapshot, we only provide primary term and generation and ask to get the metadata file where the latest metadata …

Read the same medata file that is locked during restore of shallow snapshot

---

buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties

OpenJDK Update (October 2023 Patch releases)
Part of https://github.com/opensearch-project/OpenSearch/issues/10746

OpenJDK Update (October 2023 Patch releases)

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java

- In order to debug data consistency issues with remote store, we need to log info related to last successful upload to remote translog and the download from remote translog per shard level.
- In this PR, we track this info using sequence numbers.

Log more info with max seq no on upload to and download from remote translog

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java

Fixing - > #10997.
Disable point based sort optimization for half_flaot.
There is a way we can enable it back but it needs bigger code change and I will send out shortly. We will have to create HalfFloatNumericSourceComparator as well HafFloatComparator same as we did for `unsigned_long` for that.
Created follow up issue here to make it back.
https://github.com/opensearch-project/OpenSearch/issues/10998

Disable sort optimization for HALF_FLOAT

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/main/java/org/opensearch/search/pipeline/SearchRequestProcessor.java
server/src/main/java/org/opensearch/search/pipeline/SearchResponseProcessor.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

If a search processor needs to make a call out to another service, we should not risk blocking on the transport thread. We should support async execution.
Resolves #10248

Make search pipelines asynchronous

---

CHANGELOG.md
server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/10999

[Backport] [2.11] Disable sort optimization for HALF_FLOAT (#10999)

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
server/src/main/java/org/opensearch/search/pipeline/SearchRequestProcessor.java
server/src/main/java/org/opensearch/search/pipeline/SearchResponseProcessor.java
server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/10598 to 2.x
(Conflicts on changelog needed to be resolved.)

[Backport 2.x] Make search pipelines asynchronous

---

server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java

Removes primary relocation targets from replication tracker.

[Segment Replication] Remove primary targets from replication tracker

---

CHANGELOG.md
buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11000 to `2.x`

[Backport] [2.x] Bump org.apache.logging.log4j:log4j-core from 2.21.0 to 2.21.1 in /buildSrc/src/testKit/thirdPartyAudit/sample_jars (#11000)

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/search/340_keyword_doc_values.yml
server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/CustomQueryScorer.java
server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java

The keywordfield mapper provides access to various query types, e.g. the termsQuery, fuzzyQuery. These are inherited as is from the StringType. But we do not take into account the fact that keyword fields can have doc_values enabled. This PR adds the ability for various queries to first check if doc_values are enabled and if so outsource the work to lucene to decide if it's better to use index values or doc_values when running queries.
Resolves #7057 

Adds various Query overrides to Keyword Field to enable doc_values

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

This change fixes a bug that can occur with SegRep where primary shard does not update its local tracking of replica ReplicationCheckpoint state.  This can occur post failover or relocation where a new primary publishes a checkpoint that is swallowed by replicas that are already up to date.  Unless a new write is made to the index, the lag will grow indefinitely.
Resolves https://github.com/opensearch-project/OpenSearch/issues/11016

Fix SegRep bug where primary shards do not update tracked replica state post failover/relocation

---

server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java

Fixes flaky tests
https://github.com/opensearch-project/OpenSearch/issues/5957
https://github.com/opensearch-project/OpenSearch/issues/10673
Resolves https://github.com/opensearch-project/OpenSearch/issues/5957 https://github.com/opensearch-project/OpenSearch/issues/10673

Add fix for flaky tests in weighted routing 

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/profile/AbstractInternalProfileTree.java
server/src/main/java/org/opensearch/search/profile/AbstractProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/ContextualProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/Profilers.java
server/src/main/java/org/opensearch/search/profile/Timer.java
server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/query/AbstractQueryProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfiler.java
server/src/main/java/org/opensearch/search/profile/query/InternalQueryProfileTree.java
server/src/main/java/org/opensearch/search/profile/query/ProfileWeight.java
server/src/main/java/org/opensearch/search/profile/query/QueryProfiler.java
server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java
server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfilerTests.java
server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

This PR backports following PRs from main to 2.x as discussed [here](https://github.com/opensearch-project/OpenSearch/pull/10352#issuecomment-1775603136). There were no new changes needed other than updating the CHANGELOG.md file.
https://github.com/opensearch-project/OpenSearch/pull/9248
https://github.com/opensearch-project/OpenSearch/pull/10111
https://github.com/opensearch-project/OpenSearch/pull/10547
https://github.com/opensearch-project/OpenSearch/pull/10352
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of …

Backport of PRs for profile related changes in concurrent search path

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/search/340_keyword_doc_values.yml
server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
server/src/main/java/org/opensearch/search/fetch/subphase/highlight/CustomQueryScorer.java
server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java

Backport of #10425 
The keywordfield mapper provides access to various query types, e.g. the termsQuery, fuzzyQuery. These are inherited as is from the StringType. But we do not take into account the fact that keyword fields can have doc_values enabled. This PR adds the ability for various queries to first check if doc_values are enabled and if so out-source the work to lucene to decide if it's better to use index values or doc_values when running queries.
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
(cherry picked from commit 63aff16c0d08bac44e1d1a6158ee3f838a043074) …

[Backport 2.x] Adds various Query overrides to Keyword Field (#10425)

---

CHANGELOG.md
plugins/identity-shiro/src/main/java/org/opensearch/identity/shiro/ShiroTokenManager.java
plugins/identity-shiro/src/test/java/org/opensearch/identity/shiro/AuthTokenHandlerTests.java
server/src/main/java/org/opensearch/discovery/InitializeExtensionRequest.java
server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
server/src/main/java/org/opensearch/extensions/NoopExtensionsManager.java
server/src/main/java/org/opensearch/extensions/rest/ExtensionRestRequest.java
server/src/main/java/org/opensearch/extensions/rest/RestActionsRequestHandler.java
server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
server/src/main/java/org/opensearch/identity/noop/NoopTokenManager.java
server/src/main/java/org/opensearch/identity/tokens/AuthToken.java
server/src/main/java/org/opensearch/identity/tokens/BasicAuthToken.java
server/src/main/java/org/opensearch/identity/tokens/BearerAuthToken.java
server/src/main/java/org/opensearch/identity/tokens/OnBehalfOfClaims.java
server/src/main/java/org/opensearch/identity/tokens/TokenManager.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/action/ActionModuleTests.java
server/src/test/java/org/opensearch/discovery/InitializeExtensionRequestTests.java
server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
server/src/test/java/org/opensearch/extensions/rest/ExtensionRestRequestTests.java
server/src/test/java/org/opensearch/extensions/rest/RestInitializeExtensionActionTests.java
server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java

Implement on behalf of token passing for extensions
This is a manual backport of feature Service Accounts and On-behalf-of Authentication for security plugin
* Relate https://github.com/opensearch-project/security/issues/3557
PRs
* Relate https://github.com/opensearch-project/OpenSearch/pull/8679
* Relate https://github.com/opensearch-project/OpenSearch/pull/9618
* Relate https://github.com/opensearch-project/OpenSearch/pull/10614
* Relate https://github.com/opensearch-project/OpenSearch/pull/10664
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRI …

[Backport 2.x] Service accounts and on-behalf-of authentication in 2.x

---

CHANGELOG.md
libs/core/src/main/java/org/opensearch/core/common/logging/LoggerMessageFormat.java

Per #9879, I've added my suggested source header. I've only eyeballed the code (it's a comment being added) and haven't run any compiling/testing. No concerns if folk want to do a different PR for this, but I'm only a brief visitor to these shores.
- Resolves #9879

Adding slf4j license header to LoggerMessageFormat.java

---

server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java

This is a minor refactor to SegmentReplicationTargetService.  After a replication event completes we store a reference to the latest completed SegmentReplicationTarget for the purpose of returning metrics.  These metrics rely on the SegmentReplicationState object alone, not the entire target which can be cleaned up.
N/A

[Segment Replication] Clean up SegmentReplicationTargetService only hold the state of last completed replications 

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SamplerIT.java
server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/DiversifiedAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/SamplerAggregatorFactory.java

Disable concurrent aggs for Diversified Sampler and Sampler aggs. See https://github.com/opensearch-project/OpenSearch/issues/11075#issuecomment-1793077372 for more details.
Resolves #10046
Resolves #10893
Resolves #10822

Disable concurrent aggs for Diversified Sampler and Sampler aggs

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

This change adds an assertBusy to wait until files are cleared from disk as it is not synchronous with the scroll/pit removal.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10769

Fix flaky pit/scroll tests in SegmentReplicationIT

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
server/src/internalClusterTest/java/org/opensearch/search/fieldcaps/FieldCapabilitiesIT.java
server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

Backport https://github.com/opensearch-project/OpenSearch/commit/9cb4f9dbd44e42269fe573f9592d58d4115cc522 from https://github.com/opensearch-project/OpenSearch/pull/10437.

[Backport 2.x] Mute flaky concurrent segment search tests pending fixes (#10437)

---

CHANGELOG.md
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/30_geoshape.yml
qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/30_geoshape.yml
qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/30_geoshape.yml
server/src/main/java/org/opensearch/index/mapper/GeoShapeFieldMapper.java

Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10958

Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.

---

server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java

Recent failures in this test are due to a hardcoded assertion on the segments file name.
```
org.junit.ComparisonFailure: expected:<segments_[5]> but was:<segments_[6]>
```
I haven't been able to reproduce this locally, but the replica must be performing an additional commit in the background before replication.
This test's purpose is to ensure old commits are cleaned up and we don't care what the actual generation value is.  Made an update here to expect that we only have a single segments file and its gen is higher than the previous.
Resolves #10303  …

Fix flaky test RemoteIndexShardtests.testRepicaCleansUpOldCommitsWhenReceivingNew

---

server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

This flaky test uses [min_score](https://opensearch.org/docs/latest/query-dsl/compound/function-score/#filtering-documents-that-dont-meet-a-threshold) to filter documents. Documents with lower score are excluded from the search results, but it still makes sense to include the actual score time and count in the profile response. As a result, the score time_in_nanos should not always be greater than or equal to `100`, and we need to revise the test accordingly. I run the new changes 1000+ times to make sure that they all passed.
Resolves #10518 …

Fix flaky testMinScoreDisablesCountOptimization in query profile phase tests

---

server/src/internalClusterTest/java/org/opensearch/search/fieldcaps/FieldCapabilitiesIT.java

Test was originally muted for concurrent search in https://github.com/opensearch-project/OpenSearch/pull/10437
This test was fixed already so unmuting, see https://github.com/opensearch-project/OpenSearch/issues/10474#issuecomment-1766394994.

Unmute FieldCapabilitiesIT.testWithIndexFilter for concurrent search

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SamplerIT.java
server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/DiversifiedAggregatorFactory.java
server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/SamplerAggregatorFactory.java

Disable concurrent aggs for Diversified Sampler and Sampler aggs. See https://github.com/opensearch-project/OpenSearch/issues/11075#issuecomment-1793077372 for more details.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10046
Resolves https://github.com/opensearch-project/OpenSearch/issues/10893
Resolves https://github.com/opensearch-project/OpenSearch/issues/10822

[Backport 2.x] Disable concurrent aggs for Diversified Sampler and Sampler aggs (#11087)

---

qa/remote-clusters/src/test/java/org/opensearch/cluster/remote/test/RemoteClustersIT.java
server/src/main/java/org/opensearch/transport/ProxyConnectionStrategy.java
server/src/main/java/org/opensearch/transport/RemoteClusterService.java

Avoid potential race condition in `RemoteClustersIT.testHAProxyModeConnectionWorks`
https://github.com/opensearch-project/OpenSearch/issues/1703

Flaky RemoteClustersIT: Add assert busy to avoid race condition

---

CHANGELOG.md
modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
modules/analysis-common/src/test/java/org/opensearch/analysis/common/PathHierarchyTokenizerFactoryTests.java
modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/30_tokenizers.yml

Deprecate CamelCase `PathHierarchy` tokenizer name in favor to LowerCase `path_hierarchy`.
See https://github.com/opensearch-project/OpenSearch/issues/2773#issuecomment-1733693782
Note: Taking out all items from the below check list relevant to "new functionality" as there is no new functionality in this PR.
~New functionality includes testing.~
~New functionality has been documented.~
~New functionality has javadoc added~

Deprecate CamelCase PathHierarchy tokenizer name

---

.github/workflows/lucene-snapshots.yml
.github/workflows/publish-maven-snapshots.yml
CHANGELOG.md

Backport of https://github.com/opensearch-project/OpenSearch/pull/10504 to `2.x`

[Backport] [2.x] Bump aws-actions/configure-aws-credentials from 2 to 4 (#10504)

---

server/src/main/java/org/opensearch/common/lucene/search/FilteredCollector.java
server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java

In the post filter query, a profile node is created during the creation of the filtered collector context, which occurred before the concurrent path in `ContextIndexSearcher::search()`. However, there is no association call for the filtered collector to leaves. Consequently, this led to an unexpected context size when generating the profile results.
This PR adds the association for the collector to leaves before building the scorer on the post-filter profile node. Following this modification, we can identify the missing association call for `sliceCollectorsToLeave@739870973`, and we can also confirm that the leaf counts in the `contexts` map match those in `sliceCollectorsToLeaves` when we invoke `toBreakdownMap() `to build the result.
``` ruby
------------ post filter query with 2 slices …
```

Fix slice collectors to leaves association with post filter

---

CHANGELOG.md
server/src/main/java/org/opensearch/common/regex/Regex.java
server/src/test/java/org/opensearch/common/regex/RegexTests.java

Manually backport simple regex refactor. 
#11060 

Manually backport #11060 (simple regex normalization refactor)

---

CHANGELOG.md
modules/transport-netty4/src/internalClusterTest/java/org/opensearch/http/netty4/Netty4HeaderVerifierIT.java
modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/Netty4BlockingPlugin.java
modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/Netty4MarkedMessagePlugin.java
modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4Plugin.java

Allow customization of netty channel handles before and during decompression
- https://github.com/opensearch-project/security/issues/3559

[Backport 1.3] Allow customization of netty channel handles before and during decompression (#10261)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/search/suggest/CompletionSuggestSearchIT.java

During the testSkipDuplicates its possible that not all documents were fully indexed by the time the search with suggestions was created, updating the indexing operations to refresh the index before returning.
As its possible that did not fix the issue, I've added logging around the test case to capture the state when the error occurred that can assist in future troubleshooting.
(cherry picked from commit 0ba5d5807860a799c76f0fb6e063e8c5bd458492)
- Related #10798
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/m …

[Backport 2.x] Fix SuggestSearch.testSkipDuplicates by forceing refresh when indexing its test documents (#11068)

---

.github/workflows/gradle-check.yml

Continuing in the spirit of #9699, this makes the gradle check comment less verbose while containing all the same information. The goal is to reduce visual noise on the PR feed and maybe allow for more comments before GitHub starts hiding older comments behind the "load more" link.
This is super subjective so happy to hear any opinions if the previous format is preferred.

Make the gradle check comment more compact

---

server/src/internalClusterTest/java/org/opensearch/search/basic/TransportTwoNodesSearchIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

This change updates the index random function to delete the bogus documents and add a refresh in the function such that the bogus documents are deleted and refresh ensures that the search doesnt account for the deleted segments.
This should fix some flaky issues encountered after adding the indexRadomForConcurrentSearch function to the tests.
Also, added [TransportTwoNodesSearchIT.java](https://github.com/opensearch-project/OpenSearch/compare/main...neetikasinghal:OpenSearch:slices-testing?expand=1#diff-cdddd7663031228dcf7a60e865cfb9bfa7a374c830ec86f12bb9fbec637dcd3e) to use indexRandomForConcurrentSearch.
Resolves #10900 …

update index random function to fix the bogus document deletion

---

.github/workflows/gradle-check.yml

Backports dcb64d8facde23587da9b09e92e587b68d022e94 to 2.x from #11151
There were also some indenting differences, hence the conflict on cherry pick. I've also fixed those differences here so the file should be identical to what is on `main`.

[Backport 2.x] Make the gradle check comment more compact

---

server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java

As seen in https://github.com/opensearch-project/OpenSearch/issues/10902, we can see that during test cleanup, we see an assertion failure that happens due to max reader generation being different than supplied generation. This will fix multiple flaky tests that fail due to this reason.
Resolves #10902

[Remote Translog] Fix translog inconsistent generation assertion failure in ITs

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityWithRequestBreakerIT.java

Mute CardinalityWithRequestBreakerIT pending fix

---

server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NaNSortingIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NestedIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/RangeIT.java

* IndexStatsIT.java
* SearchTimeoutIT.java
* NaNSortingIT.java
* NestedIT.java
* RangeIT.java
Updates the above tests to use multiple segment slices for concurrent segment search

Add indexRandomForConcurrentSearch method to tests:

---

CHANGELOG.md
modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/30_geoshape.yml
qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/30_geoshape.yml
qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/30_geoshape.yml
server/src/main/java/org/opensearch/index/mapper/GeoShapeFieldMapper.java

Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.
Main branch PR: https://github.com/opensearch-project/OpenSearch/pull/11095
Resolves https://github.com/opensearch-project/OpenSearch/issues/10958

[Backport-2.11] Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.

---

buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
buildSrc/version.properties
distribution/src/config/jvm.options
distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
libs/core/build.gradle
server/build.gradle
server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
server/src/internalClusterTest/java/org/opensearch/discovery/StableClusterManagerDisruptionIT.java
server/src/main/java/org/opensearch/common/util/concurrent/BaseFuture.java
test/framework/src/main/java/org/opensearch/cluster/coordination/MockSinglePrioritizingExecutor.java
test/framework/src/test/java/org/opensearch/test/disruption/LongGCDisruptionTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/10576 to `2.x`

[Backport] [2.x] Update bundled JDK to JDK-21.0.1 (#10576)

---

server/src/internalClusterTest/java/org/opensearch/search/fetch/FetchSubPhasePluginIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/RandomScoreFunctionIT.java

This makes use of the indexRandomForConcurrentSearch function, which creates more segments for concurrent search tests, in several test cases for their concurrent search use-cases. The following test suites are affected by this change:
- RandomScoreFunctionIT.java
- FetchSubPhasePluginIT.java
- ~SearchWhileRelocatingIT.java~
Resolves #11112 
Resolves #11106 

Fixed flaky and failing test cases for concurrent search

---

server/src/internalClusterTest/java/org/opensearch/search/msearch/MultiSearchIT.java
server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
server/src/internalClusterTest/java/org/opensearch/search/scriptfilter/ScriptQuerySearchIT.java

* MultiSearchIT.java
* SimpleNestedIT.java
* SearchPreferenceIT.java
* SimpleQueryStringIT.java
* ScriptQuerySearchIT.java
Follow-up to #11065 
Muted tests related to nested sorting that are flaky

Add indexRandomForConcurrentSearch for tests:

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsDocCountErrorIT.java
test/framework/src/main/java/org/opensearch/test/ParameterizedOpenSearchIntegTestCase.java

This PR is to make sure that the index random function which is used in multiple classes has creation of multiple segments to test the concurrent search code path in the following IT:
```
TermsDocCountErrorIT
```
This change will fix 2 concurrent search tests.

Fix tests for concurrent Search: TermsDocCountErrorIT

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_mixed.yml
rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml

Skipping half_float sort tests for 2.11.0 as well
https://github.com/opensearch-project/opensearch-py/issues/582

Skipping half_float sort tests for 2.11.0 as well

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java

We need to call `onPhaseEnd()` before `buildSearchResponse()` else the SearchResponse will not have phase took time for the last phase.
Original PR: https://github.com/opensearch-project/OpenSearch/pull/10351

Per request latency onPhaseEnd fix

---

CHANGELOG.md
server/src/main/java/org/opensearch/ingest/IngestService.java
server/src/main/java/org/opensearch/ingest/Processor.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

This change solves the problem of ingest pipeline processors not being able to access index mapping information. By passing reference to IngestService we opening this possibility, processor may use it to read mapping like this :
in the ingest plugin
```
Map<String, Processor.Factory> getProcessors(Processor.Parameters parameters) {
return Map.of(
MyIngestProcessor.TYPE,
new MyIngestProcessorFactory(parameters.indicesService)
);
}
```
in the processor factory
```
public MyIngestProcessor create(... ) throws Exception {
return new MyIngestProcessor(parameters.indicesService);
}
```
in the processor
```
IndicesService indicesService;
void execute(IngestDocument ingestDocument, BiConsumer<IngestDocument, Exception> handler) {
String index = …
```

Passing IndicesService to ingest processor factory with processor params

---

server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java

Today segment replication's pressure service provides a setting `segrep.replication.time.limit` that if set to a positive value will spawn an Async task every 30s validating if there are replicas over that limit.  If over the limit the task considers if shards should be failed remotely. The async task is being rescheduled every 30s, even if the setting is set to 0.  This change ensures that task isn't scheduled at all and reconsiders only if the setting is updated.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10568 …

Fix SegmentReplicationPressureService to not schedule async tasks when remote failures are disabled

---

CHANGELOG.md
benchmarks/src/main/java/org/opensearch/common/round/RoundableBenchmark.java
libs/common/src/main/java/org/opensearch/common/round/BidirectionalLinearSearcher.java
libs/common/src/main/java/org/opensearch/common/round/BinarySearcher.java
libs/common/src/main/java/org/opensearch/common/round/Roundable.java
libs/common/src/main/java/org/opensearch/common/round/RoundableFactory.java
libs/common/src/main/java/org/opensearch/common/round/package-info.java
libs/common/src/test/java/org/opensearch/common/round/RoundableTests.java
server/src/main/java/org/opensearch/common/Rounding.java
server/src/test/java/org/opensearch/common/RoundingTests.java

Manual backport of #11023
(cherry picked from commit 08db961e1914d93ce9d81e6da84e6e232b8d37e2)

[Backport 2.x] Refactor common parts from the Rounding class into a separate 'round' package (#11023)

---

server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java

Follow-up to https://github.com/opensearch-project/OpenSearch/pull/11076.
Added indexRandomForConcurrentSearch method to the tests that were failing earlier for concurrent search case.
Resolves https://github.com/opensearch-project/OpenSearch/issues/11074

Fixing the tests for concurrent search

---

server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java

This change reduces the amount of docs we ingest inside SegmentReplicationIT. Many of these tests were ingesting 1-200 docs where only a handful of docs were required to create segments.
This speeds up tests when run with remote store through SegmentReplicationUsingRemoteStore as each translog write is sync'd to remote store and adds latency.  On my machine it takes execution time of this suite from 5-7+ mins down to ~1 min.
Also add TestLogging annotation on the replication package for known flaky tests.
Related flaky tests have added `@TestLogging`
https://github.com/opensearch-project/OpenSearch/issues/10026 
https://github.com/opensearch-project/OpenSearch/issues/9712
https://github.com/opensearch-project/OpenSearch/issues/9735  …

Reduce amount of docs ingested for SegRep ITs

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/FloatValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/HalfFloatValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/IntValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java

[NumericComparator](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/comparators/NumericComparator.java#L195C51-L195C76) uses `missingValue` to determine if to apply BKD based skipping logic in case `missingValue` is not competitive. If `missingValue` is competitive, we cant apply this optimization as per the comment.
If we dont pass missing value here, it might hit the corner case like here https://github.com/opensearch-project/OpenSearch/issues/9537. We fixed this in Lucene, https://github.com/apache/lucene/pull/12520, but didnt add integ tests here in OpenSearch.
https://github.com/opensearch-project/OpenSearch/issues/10998
For more …

[Sort] Sending missing values in comparator instead sending null

---

server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java

The CommonTermsQuery tests in SearchQueryIT had one case that depended on the default cutoff frequency percentage. A recent change for concurrent search increased the number of deleted documents that could be indexed in the "indexRandom" helper method, and it turns out the cutoff percentage is calculated from a max docs value that includes deleted docs. This change replaces the default percentage with an absolute value (number of documents that must match) so it is no longer susceptible to behavior change due to number of deleted documents.
Resolves #11208 …

Fix SearchQueryIT to not depend on percentage

---

server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NaNSortingIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NestedIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/RangeIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/FetchSubPhasePluginIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/InnerHitsIT.java
server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/MatchedQueriesIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/RandomScoreFunctionIT.java
server/src/internalClusterTest/java/org/opensearch/search/msearch/MultiSearchIT.java
server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
server/src/internalClusterTest/java/org/opensearch/search/scriptfilter/ScriptQuerySearchIT.java
server/src/internalClusterTest/java/org/opensearch/search/scroll/SearchScrollIT.java
server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
server/src/internalClusterTest/java/org/opensearch/search/sort/GeoDistanceIT.java
server/src/internalClusterTest/java/org/opensearch/search/sort/SortFromPluginIT.java
server/src/internalClusterTest/java/org/opensearch/search/source/MetadataFetchingIT.java
server/src/internalClusterTest/java/org/opensearch/search/source/SourceFetchingIT.java
server/src/internalClusterTest/java/org/opensearch/search/suggest/SuggestSearchIT.java

Manual backport for the following commits:
- #11181
- #11118 
- #11130
- #11212
- #11184
- #11076

[Backport 2.x] Add indexRandomForConcurrentSearch for tests

---

server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java

Reduce the visibility of some existing APIs
Follow up on https://github.com/opensearch-project/OpenSearch/pull/11182

[BWC and API enforcement] Reduce the visibility of some existing APIs

---

modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/MoreExpressionIT.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionAggregationScript.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/PerThreadReplaceableConstDoubleValueSource.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/ReplaceableConstDoubleValueSource.java

fix the flaky test `org.opensearch.script.expression.MoreExpressionIT.testSpecialValueVariable {p0={"search.concurrent_segment_search.enabled":"true"}}`
Resolves https://github.com/opensearch-project/OpenSearch/issues/10079
[ ] ~New functionality has been documented.~

Fix flaky test MoreExpressionIT.testSpecialValueVariable in concurrent search path

---

server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityWithRequestBreakerIT.java
server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/TopHitsIT.java
server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/DecayFunctionScoreIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScoreFieldValueIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScoreIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScorePluginIT.java
server/src/internalClusterTest/java/org/opensearch/search/functionscore/QueryRescorerIT.java

Add indexRandomForConcurrentSearch to tests:
* CardinalityWithRequestBreakerIT.java
* TopHitsIT.java
* SearchFieldsIT.java
* DecayFunctionScoreIT.java
* FunctionScoreFieldValueIT.java
* FunctionScoreIT.java
* FunctionScorePluginIT.java
* QueryRescorerIT.java

Add indexRandomForConcurrentSearch to tests

---

server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java

`Math.max(float, float` will return NaN if either parameter is `NaN`, so there's a small bug here where `max_score` might end up as `NaN` even if one of the collector scores is not `NaN`.
I ran `FieldSortIT.testTrackScores` 200x after this change and saw no more flakiness whereas before it was failing around 40% of the time (https://github.com/opensearch-project/OpenSearch/issues/11189#issuecomment-1817206936)
Resolves #11189

Fix maxScore check in reduce phase when some scores are NaN

---

CHANGELOG.md
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultSpanScope.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanReference.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingContextPropagator.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/transport/TransportTracer.java
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/transport/package-info.java
libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingContextPropagator.java
plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelTracingContextPropagatorTests.java
server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
server/src/main/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorage.java
server/src/main/java/org/opensearch/telemetry/tracing/TracerFactory.java
server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
server/src/main/java/org/opensearch/transport/InboundHandler.java
server/src/main/java/org/opensearch/transport/TransportService.java
server/src/test/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorageTests.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingContextPropagator.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/TelemetryValidators.java
test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/NumberOfTraceIDsEqualToRequests.java

The thread context stashing messes up the propagation of the current span across thread boundaries (and even same thread boundary). It leads to split brain situation when some state is stored in `ThreadContext` and in the thread local scope, which is difficult (if possible at all) to reconcile. 
Closes https://github.com/opensearch-project/OpenSearch/issues/10789

[BUG] The thread context is not properly cleared and messes up the traces

---

CHANGELOG.md
buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11270 to `2.x`

[Backport] [2.x] Bump org.apache.logging.log4j:log4j-core from 2.21.1 to 2.22.0 in /buildSrc/src/testKit/thirdPartyAudit/sample_jars (#11270)

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/search/240_date_nanos.yml
rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java

There is a corner case where sort is failing on nested field after this PR https://github.com/opensearch-project/OpenSearch/pull/7453. When nested field is `date` type and have `filter` in nested field has `now()` function call.
OpenSearch prevents SortFields' initialization in such cases more then one time.
This is very corner scenario but I added integ tests for that as we didn't have any integ test.
As a mitigation, I am pssing already initialized `SortAndFormats` in ContextIndexSearcher in this PR. In fact I also made change to invoke that `if clause` only if SearchContext contains searchAfter.
This happens only when nested_sort is having date field type and filter is having range along with now(). Culprit is the now() call that Opensearch is trying to avoid since now() should get …

Handle canMatchSearchAfter for frozen context scenario

---

CHANGELOG.md
server/src/main/java/org/opensearch/ingest/IngestService.java
server/src/main/java/org/opensearch/ingest/Processor.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java

Manual backport of commit https://github.com/opensearch-project/OpenSearch/commit/c0c76e6db6b6a39401700de54f7aa64e2cc6f9f1 for PR https://github.com/opensearch-project/OpenSearch/pull/10307

[Backport 2.x]  Passing IndicesService to ingest processor factory with processor params (#10307)

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/search/240_date_nanos.yml
rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/11249

[Backport 2.x] Handle canMatchSearchAfter for frozen context scenario #11249

---

rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/FloatValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/HalfFloatValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/IntValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java
server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/11196

[Backport 2.x] [Sort] Sending missing values in comparator instead sending null

---

server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/10569 into 2.x

[Backport 2.x] Fix SegmentReplicationPressureService to not schedule async tasks when remote failures are disabled

---

CHANGELOG.md
modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonPlugin.java
modules/ingest-common/src/main/java/org/opensearch/ingest/common/KeyValueProcessor.java
modules/ingest-common/src/test/java/org/opensearch/ingest/common/KeyValueProcessorFactoryTests.java
modules/ingest-common/src/test/java/org/opensearch/ingest/common/KeyValueProcessorTests.java
modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/150_kv.yml

Backport https://github.com/opensearch-project/OpenSearch/pull/10040.
https://github.com/opensearch-project/OpenSearch/issues/9964

[Backport 2.x] Add template snippets support for field and target_field in KV ingest processor

---

server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java

Muting the flaky test as reported here https://github.com/opensearch-project/OpenSearch/issues/11258 to avoid noise.
N/A
~New functionality includes testing.~
~All tests pass~
~New functionality has been documented.~
~New functionality has javadoc added~
~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~
For more …

Mute testNestedSort for concurrent segment search case

---

modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/MoreExpressionIT.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionAggregationScript.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
modules/lang-expression/src/main/java/org/opensearch/script/expression/PerThreadReplaceableConstDoubleValueSource.java

Backport https://github.com/opensearch-project/OpenSearch/commit/f4b25d6faecca0334331d9a4e08f91e458e92914 from https://github.com/opensearch-project/OpenSearch/pull/11088.
Resolves https://github.com/opensearch-project/OpenSearch/issues/10079
~New functionality has been documented.~
~New functionality has javadoc added~
~Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))~
~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~
~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~ …

[Backport 2.x] Fix flaky test MoreExpressionIT.testSpecialValueVariable in concurrent search path

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/bulk/BulkPrimaryExecutionContext.java
server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java

When updates are sent as part of a bulk request, they can remain stuck in an infinite loop in a scenario where `VersionConflictEngineExceptions` are repeatedly thrown. This PR fixes that and adds a test case to detect the same.
https://github.com/opensearch-project/OpenSearch/issues/11152

Fix for stuck update action in a bulk with retry_on_conflict property

---

CHANGELOG.md
modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveProcessor.java
modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorTests.java
modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/290_remove_processor.yml

Backport https://github.com/opensearch-project/OpenSearch/pull/10895.
https://github.com/opensearch-project/OpenSearch/issues/10732

[Backport 2.x] Disallow removing some metadata fields by remove ingest processor

---

plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/StatsMetricPublisher.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java

On upload of large shards (large segments or more number of smaller segments), we noticed s3 errors. For large segments, api timeouts were observed and for large shards of small segments connection acquisition timeout was observed as below. Also, for small instances having low cpu cores, stream read pool capacity becomes low which processes upload requests slowly.
This change is to increase the capacity of stream read pool and increase connection acquisition and api timeouts.
```
[2023-10-25T07:47:37,139][ERROR][o.o.i.s.RemoteDirectory  ] [51844e1377c6a637328871dc96b00d5e] Failed to upload blob _3h_Lucene90_0.tim
software.amazon.awssdk.core.exception.SdkClientException: Failed to send multipart upload requests.
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(S …
```

Stream read pool and default s3 timeouts tuning

---

.github/dependabot.yml
plugins/crypto-kms/src/main/java/org/opensearch/crypto/kms/KmsMasterKeyProvider.java

Adding missing encryption context in decrypt call in kms crypto plugin.

Adding missing encryption context in decrypt call in KMS crypto plugin

---

CHANGELOG.md
libs/common/src/main/java/org/opensearch/common/Booleans.java
libs/common/src/test/java/org/opensearch/common/BooleansTests.java
server/src/main/java/org/opensearch/index/mapper/BooleanFieldMapper.java

Bunch of modernization changes to the `Booleans` helper class.
* Improved the performance of `parseBoolean` and `isBoolean` when operating on char arrays.
* Avoid unnecessary `String` to `char[]` conversion in the `BooleanFieldMapper`.
* Removed deprecated/unused methods and their tests.
* Moved UTs to the correct module.
* Updated docs.
Each operation represents parsing the following values: `["11", "00", "sdfsdfsf", "F", "T", "on", "off", "yes", "no", "0", "1", "True", "False", "true", "false", ""]`. The new method is 6.73x faster and has zero allocations.
```
Benchmark                                                     Mode  Cnt         Score   Error   Units
BooleansBenchmark.baseline                                   thrpt       12217820.930           ops/s …
```

Improve boolean parsing performance

---

server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
server/src/main/java/org/opensearch/index/engine/EngineConfig.java
server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/index/shard/ReleasableRetryableRefreshListener.java
server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
server/src/main/java/org/opensearch/index/translog/LocalTranslog.java
server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
server/src/main/java/org/opensearch/index/translog/Translog.java
server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
server/src/main/java/org/opensearch/index/translog/TranslogManager.java
server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
server/src/test/java/org/opensearch/index/shard/CloseableRetryableRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/ReleasableRetryableRefreshListenerTests.java
server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
server/src/test/java/org/opensearch/index/translog/TestTranslog.java

This PR fixes an edge case during primary relocation that can lead to both existing primary and new primary uploading segments/translog metadata having same combination of primary term, segment info generation, translog generation under following scenarios.
1. Internal flush triggered during shard inactivity or snapshot just before the primary mode of the existing primary is set to false. This is race condition where the new primary starts itself with generation n, but n+1 generation gets uploaded to remote store by existing primary. 
2. New primary does a syncTranslog in [here](https://github.com/opensearch-project/OpenSearch/blob/5bb6caec906f9e89d330332ebb74789571409eb1/server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java#L256-L259) before actually becoming a primary …

[Remote Store] Handoff refreshes, translog uploads during relocation from old to new primary

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java

#5907 uses a whitelist to control which settings of searchable snapshot can be changed, but `index.number_of_shards` is not on the list. I think it is necessary to allow user to change the number of replicas based on their cost or performance needs.

Allow changing number of replicas of searchable snapshot index

---

.github/workflows/lucene-snapshots.yml

Adding lucene snapshot to the ci staging repository
Old Location: https://d1nvenhzbhpy0q.cloudfront.net/snapshots/lucene/
New Location: https://ci.opensearch.org/ci/dbc/snapshots/lucene/
https://github.com/opensearch-project/opensearch-build/issues/3874
~New functionality includes testing.~
~All tests pass~
~New functionality has been documented.~
~New functionality has javadoc added~
~Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))~ …

Adding lucene snapshot to the ci staging repository

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/engine/MaxDocsLimitIT.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Whenever lucene document limit(which is currently INT_MAX) is breached for any shard, the error message that is shown currently indicates that the limit is on an index level whereas actually the limit is on a shard level.
Updating the error message in this PR to indicate the same. Also including the Shard Id as well in the message.
Previous message
```
Number of documents in the index can't exceed [2147483647]
```
Updated message
```
Number of documents in shard <index_name>[<shardId>] exceeds the limit of [2147483647] documents per shard
``` …

Update error message when lucene max document limit is breached

---

server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java

Unmuting nested sort related tests for concurrent segment search. It's not super obvious why but both these tests and the underlying race condition itself was addressed by #11249.
The race condition comes from when `SortBuilder::buildSort` is called simultaneously by multiple threads which results in the `LinkedListed` in `NestedScope` being accessed concurrently leading to the stack traces found in #11187 & #11258.
In #11249 this was changed [here](https://github.com/opensearch-project/OpenSearch/pull/11249/files#diff-53095189f47932d79608f3c2fa2127fa0198a32b36c1d5b1b6a3f4e3bdc4c71eL627-L629) to instead pass in the same `SortAndFormats` from the search context instead of rebuilding it on each thread. This means that we won't run into this same race condition anymore for nested sorts and I …

Unmute nested sort related ITs

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/index/engine/MaxDocsLimitIT.java
server/src/main/java/org/opensearch/index/engine/InternalEngine.java
server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java

Auto backport for #11312 failed 
Raising a manual backport PR for the same.

[Backport to 2.x] Update error message when lucene max document limit is breached

---

server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalIT.java
server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalWithNodeSettingsIT.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
server/src/main/java/org/opensearch/snapshots/RestoreService.java

We want to maintain following flows for index refresh interval for Remote Store Clusters. More details in https://github.com/opensearch-project/OpenSearch/issues/11348
Resolves https://github.com/opensearch-project/OpenSearch/issues/11348

[Remote Store] fail index template creation with refresh_interval less than cluster minimum

---

CHANGELOG.md
modules/lang-painless/build.gradle

Fix Shadow JAR dependency publication
Resolves #11353

Fix Shadow JAR dependency publication

---

CHANGELOG.md
modules/lang-painless/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11369 to `2.x`

[Backport] [2.x] Fix Shadow JAR dependency publication (#11369)

---

server/src/main/java/org/opensearch/common/Rounding.java
server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/FilterRewriteHelper.java

Follow up on https://github.com/opensearch-project/OpenSearch/pull/11083
N/A

Revert Rounding API visibility changes

---

CHANGELOG.md
settings.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11339 to `2.x`

[Backport] [2.x] Bump com.gradle.enterprise from 3.14.1 to 3.15.1 (#11339)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java

Backports c4e703f9e7c31e991a57f3719910fdc086120e93 from #11317 to 2.x

[Backport 2.x] Allow changing number of replicas of searchable snapshot index

---

server/src/main/java/org/opensearch/index/engine/Engine.java

Adding log for unreferenced file cleanup

Add log for unreferenced file cleanup

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AllocationDeciders.java
server/src/main/java/org/opensearch/cluster/routing/allocation/decider/Decision.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsAllocateUnassignedTests.java
server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java

Two changes here:
- make sure the primary shard's `AllocationStatus` be set to `DECIDERS_NO` when it cannot be allocated to any nodes;
- remove unused variables

Fix remote shards balancer and remove unused variables

---

CHANGELOG.md
server/src/main/java/org/opensearch/indices/IndicesQueryCache.java
server/src/test/java/org/opensearch/indices/IndicesQueryCacheTests.java
server/src/test/java/org/opensearch/indices/IndicesServiceCloseTests.java

* adding delegation from CachingWeightWrapper#count to internal weight object and its unit test
Signed-off-by: Niyati Aggarwal <niyatiagg4641@gmail.com>
* fixing checkstyle violations
Signed-off-by: Niyati Aggarwal <niyatiagg4641@gmail.com>
* fixing existing tests
Signed-off-by: Niyati Aggarwal <niyatiagg4641@gmail.com>
* adding test for delegating count to internal weight object
Signed-off-by: Niyati Aggarwal <niyatiagg4641@gmail.com>
* Fixing failing unit tests
Signed-off-by: Niyati Aggarwal <niyatiagg4641@gmail.com>
* Adding the change log
Signed-off-by: Niyati Aggarwal <niyatiagg4641@gmail.com>
---------
Signed-off-by: Niyati Aggarwal <niyatiagg4641@gmail.com>
(cherry picked from commit 72e63f2b3e8257d204bedbc2d04e1aa25adaebf6)
Backport of #10543 
Resolves #10060  …

[Backport 2.x] Delegating CachingWeightWrapper#count to internal weight object (#10543)

---

CHANGELOG.md
server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
server/src/main/java/org/opensearch/index/shard/IndexShard.java
server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
server/src/main/java/org/opensearch/node/Node.java
server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java

This fixes an issue where replication lag grows post primary relocation.  After a relocation occurs the new primary will publish a checkpoint to sync with the new replica, the replica if it has not yet processed a cluster state update that the relocation has completed, will respond to the old primary.  If no further action is taken on the shard, the new primary will think the replica is stale.  This change fixes this by triggering a round of replication from the replica once it has processed the cluster state update.
Resolves https://github.com/opensearch-project/OpenSearch/issues/11211 …

Fix bug where replication lag grows post primary relocation

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11445 to `2.x`

[Backport] [2.x] Bump org.apache.maven:maven-model from 3.9.4 to 3.9.6 (#11445)

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11446 to `2.x`

[Backport] [2.x] Bump commons-io:commons-io from 2.13.0 to 2.15.1 (#11446)

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Bump `org.apache.zookeeper:zookeper` from 3.8.0 to 3.8.3 on 1.x line.  This is to resolve https://nvd.nist.gov/vuln/detail/CVE-2023-44981
https://nvd.nist.gov/vuln/detail/CVE-2023-44981

Bump `org.apache.zookeeper:zookeper` from 3.8.0 to 3.8.3

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11450 to `2.x`

[Backport] [2.x] Bump commons-net:commons-net from 3.9.0 to 3.10.0 in /test/fixtures/hdfs-fixture (#11450)

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/11476 to 1.3

Bump `org.apache.zookeeper:zookeper` from 3.8.0 to 3.8.3 (#11476)

---

server/src/internalClusterTest/java/org/opensearch/blocks/SimpleBlocksIT.java

Fix for flaky test SimpleBlocksIT.testAddBlockWhileDeletingIndices
Adds a retry logic for delete index call incase the call fails due to `ProcessClusterEventTimeoutException `
Resolves https://github.com/opensearch-project/OpenSearch/issues/2472

Fix for flaky test SimpleBlocksIT.testAddBlockWhileDeletingIndices

---

server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java

TargetPoolAllocationDecider doesn't use correct format when return `Decision`, resulting in an explanation message that reads something like `Routing pools are incompatible. Shard pool: [{}], Node Pool: [{}] without [{}] role`.

Fix explanation message for TargetPoolAllocationDecider

---

CHANGELOG.md
server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java

- Fix template setting override for replication type for indices created using templates
Resolves #11230

Fix template setting override for replication type

---

server/src/main/java/org/opensearch/threadpool/ThreadPool.java
server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java

Remote Store threadpools were capped to a max count. This leads to threadpool queue getting build up on bigger instances having more cores. 
~- [] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)~

Remove cap of processors on remote store related threadpools

---

.github/workflows/maintainer-approval.yml
.github/workflows/maintainer-approved.yml
CHANGELOG.md

_Implements proposal from https://github.com/opensearch-project/OpenSearch/issues/10613#issue-1942146755_
> Replace Codeowners to control accepting pull requests with a GitHub action check that reads from the list of maintainers any verifies they have approved the PR. Codeowners can still be used for mapping subject matter experts that want to be notified, but isn't a requirement for every maintainer to be listed on the top level.
>
> By modifying the branch protection rules 'maintainer has approved' check, could be required (only bypassable by an Admin), which would offer effectively the same security as Codeowners.
This is a new approval check that effectively doubles as the existing CODEOWNERS checks on this repository - which will allow that code owners check to be _removed_ in favor …

Maintainer approval check

---

test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java

Fix invalid `BulkRequest` construction for indexRandom():
```
org.opensearch.action.ActionRequestValidationException: Validation Failed: 1: RefreshPolicy is not supported on an item request. Set it on the BulkRequest instead.;2: RefreshPolicy is not supported on an item request. Set it on the BulkRequest instead.;3: RefreshPolicy is not supported on an item request. Set it on the BulkRequest instead.;4: RefreshPolicy is not supported on an item request. Set it on the BulkRequest instead.;
at __randomizedtesting.SeedInfo.seed([19EE5058CA5DFA10:CEAC4ADCAF30EA37]:0)
at app//org.opensearch.action.ValidateActions.addValidationError(ValidateActions.java:44)
at app//org.opensearch.action.bulk.BulkRequest.validate(BulkRequest.java:432)
at …
```

Fix invalid BulkRequest construction for indexRandom()

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

hdfs-fixture has more vulnerable dependencies brought in from hadoop-minicluster.  This time logback-core and logback-classic - https://nvd.nist.gov/vuln/detail/CVE-2023-6378.
This forces the version to 1.2.13 to resolve the CVE.
Resolves https://nvd.nist.gov/vuln/detail/CVE-2023-6378

Force version of logback-core and logback-classic to 1.2.13

---

CHANGELOG.md
buildSrc/version.properties

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/11501 to 1.3

[Backport 1.3] Bump jetty from 9.4.51.v20230217 to 9.4.52.v20230823 (#11501)

---

server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java

- Currently, we trigger cleanup of stale segment files from remote segment store on each flush.
- This clean-up is based on metadata file which references to the segment file
- If multiple stale segment metadata files refer to the same segment file, we call `remoteDataDirectory.deleteFile` multiple times.
- Functionally, this is a no-op as RemoteDirectory internally calls `blobContainer.deleteBlobsIgnoringIfNotExists`.
- But this can still make a call to the remote store which is un-necessary.
- In this PR, we keep track of deleted files and avoid calling delete on the same deleted file.
- https://github.com/opensearch-project/OpenSearch/issues/11530 …

[Remote Store] Avoid repeated delete calls for the stale segment files

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/11521 to 1.x

[Backport 1.x] Force version of logback-core and logback-classic to 1.2.13 (#11521)

---

CHANGELOG.md
buildSrc/version.properties

Manual backport of https://github.com/opensearch-project/OpenSearch/pull/11539 to 1.x.

[Backport 1.x] Bump jetty version in hdfs-fixture to 9.4.53.v20231009

---

buildSrc/build.gradle

backport https://github.com/opensearch-project/OpenSearch/commit/6d548cc0d2be2153484aac5ee5cd9b0448bdaafa to 1.3

[Backport 1.3] Bump com.github.tomakehurst:wiremock-jre8-standalone from 2.23.2 to 2.35.1 

---

CHANGELOG.md
buildSrc/version.properties

Backport of https://github.com/opensearch-project/OpenSearch/pull/11540 from 1.x to 1.3

[Backport 1.3] Bump jetty version in hdfs-fixture to 9.4.53.v20231009

---

CHANGELOG.md
client/rest/build.gradle
client/rest/src/main/java/org/opensearch/client/RestClient.java
client/rest/src/test/java/org/opensearch/client/nio/HeapBufferedAsyncEntityConsumerTests.java
client/test/build.gradle

Restore support for Java 8 for RestClient. There are still community asks for 2.x clients compatible with Java 8 baseline. The issue has worsen recently due to breaking changes in 2.x baseline (https://github.com/opensearch-project/OpenSearch/pull/5902, https://github.com/opensearch-project/OpenSearch/pull/9082), runtime replacement 1.x vs 2.x is not transparent anymore (causes compile time issues). 
Part of https://github.com/opensearch-project/opensearch-java/issues/156
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifi …

Restore support for Java 8 for RestClient

---

test/fixtures/hdfs-fixture/build.gradle

We [bumped](https://github.com/opensearch-project/OpenSearch/pull/10210/files) this through dependabot & manual PR's to 1.x branches but we need to also manually exclude the version included by hadoop-minicluster so the version is picked up by the test fixture package.
N/A

Exclude apache avro version included with hadoop-minicluster

---

buildSrc/build.gradle

Remove manual override of jgit and bump grgit-core from 5.2.0 to 5.2.1 that includes patched version of jgit for  https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-4759. 
Also removes redundant declaration of the grgit-core depenedency.
N/A

Bump grgit-core from 5.2.0 to 5.2.1

---

CHANGELOG.md
libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultSpanScope.java
server/src/test/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorageTests.java

Backport of https://github.com/opensearch-project/OpenSearch/pull/11316 to `2.x`

[Backport] [2.x] Fix the issue with DefaultSpanScope restoring wrong span in the TracerContextStorage upon detach (#11316)

---

buildSrc/build.gradle

Fixes the same CVE flagged for main/2.x that was fixed by https://github.com/opensearch-project/OpenSearch/pull/11565.
The malicious version is included by gradle-info-plugin 8.2.0 on the 1.x line instead of git.
N/A

Replace jgit version included through gradle-info-plugin on 1.x line

---

.github/workflows/maintainer-approval.yml
CHANGELOG.md

Backport of 87b3011 from #11378
- Related https://github.com/opensearch-project/OpenSearch/issues/10613#issue-1942146755

[Backport 1.3] Maintainer approval check (#11378)

---

.github/workflows/maintainer-approval.yml
CHANGELOG.md

Backport of 87b3011 from #11378
- Related https://github.com/opensearch-project/OpenSearch/issues/10613#issue-1942146755

[Backport 2.x] Maintainer approval check (#11378)

---

CHANGELOG.md
client/rest/build.gradle
client/rest/src/main/java/org/opensearch/client/RestClient.java
client/test/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11562 to `2.x`

[Backport] [2.x] Restore support for Java 8 for RestClient (#11562)

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11556 to `2.x`

[Backport] [2.x] Bump org.apache.commons:commons-compress from 1.24.0 to 1.25.0 (#11556)

---

server/src/main/java/org/opensearch/search/internal/SearchContext.java

Adds a `slice_size` heuristic for controlling top buckets for terms aggs. See https://github.com/opensearch-project/OpenSearch/issues/11584 for more details
Resolves #11584

Add heuristic slice_size for slice level top buckets in concurrent segment search

---

CHANGELOG.md
plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/AwsEc2ServiceImpl.java
plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/AwsEc2ServiceImplTests.java

Fix the problem that `discovery.ec2.endpoint` forgets to fill in the scheme
https://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region
Example
```
discovery.ec2.endpoint: ec2.us-east-1.amazonaws.com
```

[Backport 2.x] Automatically add scheme to discovery.ec2.endpoint (#11512)

---

server/src/main/java/org/opensearch/search/internal/SearchContext.java

Backport https://github.com/opensearch-project/OpenSearch/commit/074bc6a91c05a5ed0e3d36cd672c905b0bf023c3 from https://github.com/opensearch-project/OpenSearch/pull/11585.

[Backport 2.x] Add heuristic slice_size for slice level top buckets in concurrent segment search (#11585)

---

.github/workflows/triage.yml

Fix regex in triage.yml so that issue labels with spaces are auto assigned.
N/A

Fix regex in triage.yml to support label names with spaces

---

.github/CODEOWNERS

- Backport 9f4296343cc0b0089c8b5e6912910e3a8339a017 from #11600
- Related https://github.com/opensearch-project/OpenSearch/issues/10613

[Backport 2.x] Personalize code ownership areas (#11600)

---

server/src/test/java/org/opensearch/index/shard/IndexShardTests.java

Fix flaky test of `IndexShardTests.testRestoreLocalHistoryFromTranslogOnPromotion`
Reason of flakyness: 
* We perform doc ingestion and update existing doc randomly. 
* After that we will generate random no between -1 to max_seqNo, and use it as `maxSeqNoOfUpdatesOrDelete` on replica operation. 
* Here random number should be generated between -1 to `maxSeqNoOfUpdatesOrDelete` as in first step docs are getting overridden randomly so max_seq no can be higher than `maxSeqNoOfUpdatesOrDelete`. If generated random number is generated higher than `maxSeqNoOfUpdatesOrDelete` then it will be updated during performing replica operation and fail the assertion.
Fix:
* Generate random number during replica operation between -1 to `maxSeqNoOfUpdatesOrDelete`. 
* Test is passing with below seed for …

Fix flaky test of IndexShardTests.testRestoreLocalHistoryFromTranslogOnPromotion

---

CHANGELOG.md
plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/AwsEc2ServiceImpl.java
plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/AwsEc2ServiceImplTests.java

Fix automatic addition of protocol in discovery endpoint 

---

CHANGELOG.md
test/fixtures/hdfs-fixture/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11632 to `2.x`

[Backport] [2.x] Bump com.squareup.okio:okio from 3.6.0 to 3.7.0 in /test/fixtures/hdfs-fixture (#11632)

---

CHANGELOG.md
distribution/packages/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11630 to `2.x`

[Backport] [2.x] Bump com.netflix.nebula.ospackage-base from 11.5.0 to 11.6.0 in /distribution/packages (#11630)

---

.github/workflows/check-compatibility.yml

Bump actions/upload-artifact from 3 to 4
_Note; I'm going to merge this immediately to unblock existing pull requests since this job is used by pull_request_target on main_
- Resolves #11645

Bump actions/upload-artifact from 3 to 4

---

distribution/src/config/jvm.options

Add context for custom GC tunings

---

CHANGELOG.md

Fix CHANGELOG entries that were added to wrong section

---

server/build.gradle

The java11-specific sources were removed back in #2898 and as far as I can tell this configuration has been unneeded since that point.

Remove unused java11 gradle configuration

---

server/src/main/java/org/opensearch/action/admin/cluster/remote/RemoteInfoAction.java
server/src/main/java/org/opensearch/action/main/MainAction.java

Change access modifier of action constructors for consistency.
- MainAction
- RemoteInfoAction
None

Change visibility of action constructor (public -> private)

---

libs/core/build.gradle

This is the same unused java11 configuration that was removed from the server module in #11661.

Remove unused java11 gradle configuration from lib/core

---

server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

This flaky test uses `RandomIndexWriter` to add random number of documents to the search index. As long as the score_count in the concurrent search case matches the non-concurrent search case, we can tune the expected value for min_score/min_score_count to make it less sensitive. I ran the new changes `1000+` times to make sure that they all passed.
Resolves #10139

Fix flaky testPostFilterDisablesCountOptimization with concurrent search enabled

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11671 to `2.x`

[Backport] [2.x] Bump com.netflix.nebula:nebula-publishing-plugin from 20.3.0 to 21.0.0 (#11671)

---

CHANGELOG.md
server/src/main/java/org/opensearch/action/search/PitService.java
server/src/test/java/org/opensearch/action/search/TransportDeletePitActionTests.java

When the DELETE PIT endpoint is called without any PITs in existence, its possible that an IllegalArgumentException (`IllegalArgumentException: groupSize must be greater than 0 but was 0`) is being swallowed and a malformed response (`{"error":{"`) can be returned. 
The opensearch logs contains the following error:
```
ERROR RestResponseListener:91 - failed to send failure response
java.lang.IllegalStateException: Channel is already closed
...
Suppressed: java.lang.IllegalArgumentException: groupSize must be greater than 0 but was 0
```
When the DELETE PIT endpoint is called when no PITs exist, it tries to send multiple responses across the same REST channel. This PR fixes the behavior so that its no longer possible for `channel.sendResponse` to be called multiple times.
- Related …

Fix issue when calling Delete PIT endpoint and no PITs exist

---

server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java

`QueryProfilePhaseTests.testTerminateAfterEarlyTermination` is flaky not only in the concurrent search case but also in the non-concurrent search case. In cases where the test query returns some total hits, it is possible that the `score` breakdown timing for certain rewritten or sub-queries is still zero. Consequently, we need to update the assertion check accordingly.
Additionally, in the concurrent search case, there is a particular scenario where some slices have zero `score` breakdown timing, while others have non-zero `score` breakdown timing. In this case, the `min_score` stat result will be expected zero. I ran the new changes `1000+` times to make sure that they all passed.
Resolves #11611 …

Fix flaky QueryProfilePhaseTests.testTerminateAfterEarlyTermination

---

CHANGELOG.md
buildSrc/build.gradle

Backport of https://github.com/opensearch-project/OpenSearch/pull/11692 to `2.x`

[Backport] [2.x] Bump com.avast.gradle:gradle-docker-compose-plugin from 0.17.5 to 0.17.6 (#11692)

---

server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java

Test `testIndexDeletionDuringSnapshotCreationInQueue` creates a async snapshot (`wait_for_completion=false`) which conflicts during test clean up where repository is deleted. The conflict happens due to in progress snapshot. The fix here is to wait for snapshot to be in `completed` state. 
Resolves https://github.com/opensearch-project/OpenSearch/issues/5031

Fix testIndexDeletionDuringSnapshotCreationInQueue flaky test

---

CHANGELOG.md
buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
gradle/code-coverage.gradle

Switched to more reliable OpenSearch Lucene snapshot location
- Related https://github.com/opensearch-project/opensearch-build/issues/3874

Switch to more reliable OpenSearch Lucene snapshot location

---

CHANGELOG.md
rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java

Added deleted document count in _cat/shards.
Kept is as a non-default column for now (`docs.deleted` will only be returned if present in the header parameter)
```
_cat/shards?v
index  shard prirep state      docs  store   ip        node
index1 0     p      STARTED       4    4.4kb 127.0.0.1 b0be8357b2c9.ant.amazon.com                             
index3 0     p      STARTED       2    4.3kb 127.0.0.1 b0be8357b2c9.ant.amazon.com                              
index2 0     p      STARTED       3    4.3kb 127.0.0.1 b0be8357b2c9.ant.amazon.com       
_cat/shards?v&h=index,shard,prirep,state,docs,docs.deleted,store,ip,node
index  shard prirep state      docs docs.deleted store ip        node
index1 0     p      STARTED       4            0  4.4kb 127.0.0.1 b0be8357b2c9.ant.amazon.com …
```

Add deleted doc count in _cat/shards

---

CHANGELOG.md
modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpChannel.java
modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpChannelTests.java

Follow up on  https://github.com/opensearch-project/OpenSearch/pull/10562 since more type casting code has been added into the `security` plugin.
Relates to https://github.com/opensearch-project/security/issues/3911 

Add the means to extract the contextual underlying channel from HttpChannel without excessive typecasting
